### ISSUE TITLE
Default phoenix port 13000 conflicts with new Azure Monitoring Agent

### ISSUE THREAD

**Issue by jbtule** [CloudFire-LLC/cloudfire#1002]
I was setting up a new Ubuntu 22.04 LTS and it was failing with the setup script on create new admin user. Tracked it down ultimately to the the phoenix logs and it looked liked a port conflict which I was surprised by. But `netstat -ntlp` showed that it was Microsoft's new log agent for azure sentinel (Azure Monitoring Agent).

```
tcp        0      0 127.0.0.1:13000         0.0.0.0:*               LISTEN      839/amacoreagent
```
Workaround: I changed the port in `default['firezone']['phoenix']['port']` in `/etc/firezone/firezone.rb`  and then used `firezone-ctl reconfigure` and then `firezone-ctl create-or-reset-admin` and it all worked.  

Suggestion: I think it might be a good a good idea if your install script check for ports in use first and then changed the default automatically.

**Comment by jamilbk** [comment]
Hi @jbtule thanks for raising this to our awareness. We'll be shipping Docker support soon which will be the default way to deploy Firezone. That'll eliminate the conflict here while keeping the port number deterministic -- I think failing explicitly here is still the best option for a port conflict condition.
