### ISSUE TITLE
Feature Request: Allow custom re-authenticated session length

### ISSUE THREAD

**Issue by jbtule** [CloudFire-LLC/cloudfire#1008]
Trying to balance security and disruptiveness. I'd like a little more customization of the authentication session length.  

1 hr is very disruptive and 24 hrs doesn't help much with limiting  accidental left open connections during the work week, also 24 hrs can be a bit disruptive on a flex time schedule, where a 9hr or 4hr might fall into a work day better. I think having a custom option where you put in the length might be the most flexible.

**Comment by dennislapchenko** [comment]
+1
I was close to writing a same feature request. Having a custom length option would be great.

On top of this, I dont think it's possible to configure this option via `/etc/firezone/firezone.rb`? Can that also be made available? Or pointer on what is the key to update would be helpful 🙏

**Comment by jamilbk** [comment]
@dennislapchenko As a quick hack you could manually edit the `vpn_session_duration` field on the `sites` table to be whatever you want. For runtime config like this we'll be making them available via the REST API coming in 0.7.0.

**Comment by jamilbk** [comment]
This is available via the new REST API.
