### ISSUE TITLE
Feature Request: New Device approval

### ISSUE THREAD

**Issue by jbtule** [CloudFire-LLC/cloudfire#1009]
As middle ground, between only privileged users creating devices or allowing all users to create devices, another option would be a big help: 

Allowing devices to be created by unprivileged users, **but** those devices are disabled until approval by a privileged user.

**Comment by jamilbk** [comment]
Thanks for the suggestion! Things are in flux at the moment as we work to build our own platform apps, and I imagine this may be better managed in another way then.

**Comment by jbtule** [comment]
For us we probably won't be able to use the platform apps since I'm assuming we are not a typically setup. Our WireGuard clients are chromebooks, and for paranoia we are restricting the portal with our own Nginx proxy to authenticate first with client ssl certs if the vpn isn't engaged.

**Comment by AndrewDryga** [comment]
Closing in favor of #1329.
