### ISSUE TITLE
Error on docker

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#1014]
00:58:56.350 [error] GenServer #PID<0.513.0> terminating
** (stop) {:badarg, {'aead.c', 90}, 'Unknown cipher or invalid key size'}

What does this mean?

**Comment by jamilbk** [comment]
Could you post the full backtrace? I believe that's coming from the OIDC backend when fetching your JWKS from your OIDC provider.

**Comment by dillfrescott** [comment]
Ah, sorry to waste your time, but I am no longer having this issue!
