### ISSUE TITLE
Unprivileged accounts device adding checking mechanism

### ISSUE THREAD

**Issue by ecrawford-0** [CloudFire-LLC/cloudfire#1017]
Hello! I was testing out the controls to turn off unprivileged accounts from being able to configure or manage devices, but I noticed that the unprivileged users could try add a new device by entering /new into the url. It will deny them when they try to submit the form, but should the check to see if they should be even able to access the page come before they send it? Below is the gif of the behavior

![unpriv account - Made with Clipchamp](https://user-images.githubusercontent.com/61421800/195679073-fc1e0c53-70e6-4ff3-8bd6-2a171fe27353.gif)

Thank you

**Comment by jamilbk** [comment]
Thanks for the report. Not a big security concern at first glance, but agreed that route probably should be hidden when unprivileged device management is disabled.
