### ISSUE TITLE
`Unprivileged Device Configuration` option does not allow privileged users to fully configure devices when disabled

### ISSUE THREAD

**Issue by bootsie123** [CloudFire-LLC/cloudfire#1043]
Hi! When setting the `Allow unprivileged device configuration` option to false, I would expect unprivileged users to only be able to assign a name and a description to devices while privileged users would still have all options.

As of right now, it looks like privileged users are also limited. I was wondering if this could be fixed so that unprivileged users are still limited, while privileged users are not. Thanks!

**Comment by jamilbk** [comment]
Thanks for the report! Are you setting this option in the UI at `/settings/security`?

**Comment by bootsie123** [comment]
Yes, this is through the UI

**Comment by jamilbk** [comment]
Fix coming in 0.6.4

**Comment by bootsie123** [comment]
Awesome, thank you!

**Comment by bootsie123** [comment]
Just updated and tested it. Everything works. Thanks again!
