### ISSUE TITLE
OIDC automated setup with Docker and Ansible

### ISSUE THREAD

**Issue by JonnyBDev** [CloudFire-LLC/cloudfire#1046]
Hello,

we've deployed the Omnibus version of Firezone with our automated Ansible deployment. Unfortunately one week later you released the Docker version. We'd like to change our deployment to Docker but currently there is no option to setup one or multiple OIDC providers at the startup. We would like to configure this automated instead of the webinterface option.

Is there any timeline when you'll be able to offer this kind of configuration with ENV vars or are there other options available to us like manually change the firezone.rb file in a mounted volume and then restarting the container?

Thanks

**Comment by jamilbk** [comment]
This will be resolved with a REST API coming in 0.7. Unfortunately it didn't make it into the 0.6 release.

**Comment by JonnyBDev** [comment]
Thanks @jamilbk Could you give me a ETA for the 0.7 or a week/month? Just thinking about creating a workaround for this solution. If the release will happen in a few weeks I just pause my current work and wait for the implementation.

**Comment by jamilbk** [comment]
Likely on the order of weeks, if not sooner. It's currently under development: #1006

**Comment by jamilbk** [comment]
@JonnyBDev I spoke too soon 😅 . Merging the final pieces of #1155 for release in 0.7. Thanks for the patience!

**Comment by JonnyBDev** [comment]
That's okay :) Thanks for your work <3

**Comment by jamilbk** [comment]
Released in 0.7.x
