### ISSUE TITLE
SAML authentication details

### ISSUE THREAD

**Issue by ilyatovbin-pp** [CloudFire-LLC/cloudfire#1049]
Hi. I'm attempting to configure SAML2.0 authentication using Google Workspace and I need to provide it with the following details:

- ACS URL (SAML redirect URL)
- Entity ID (might be the same as the ACS URL)
- Name ID (usually EMAIL)

looks like it's undocumented.

**Comment by ilyatovbin-pp** [comment]
took a quick look at the code and if I understood it correctly the URL should tehnically be the same as what's described in the OIDC configuration, just replacing it with "saml"

so i tried the following mixes and mashes of configs on the google saml app side:

ACS URL: 
- https://firezone.fqdn/auth/saml/callback/
- https://firezone.fqdn/auth/saml/auth/signin/gsuite/  

Entity ID: 
- urn:firezone.dev:firezone-app (tested other stuff and this one looks like its the correct answer)

Name ID Format: EMAIL (default in Google)
Name ID: Basic Information->Primary Email (default in Google)

Getting a 403 Forbidden response when passing the SAMLResponse from google to either of the URLs.

**Comment by jamilbk** [comment]
Hi @ilyatovbin-pp -- SAML hasn't been tested extensively with Google Workspace yet -- if you get it working we'd love a simple docs PR!

In the meantime, we're still looking into it -- see if #1048 and #926 help you.

**Comment by ilyatovbin-pp** [comment]
Tried the `/saml/auth/sp/consume/gsuite` path as the ACS URL:

Getting what I can only assume is an exception from samly/esaml:

access_denied {{:badmatch, []}, [{:xmerl_dsig, :verify, 2, [file: '/app/deps/esaml/src/xmerl_dsig.erl', line: 168]}, {:esaml_sp, :"-validate_assertion/3-fun-3-", 3, [file: '/app/deps/esaml/src/esaml_sp.erl', line: 265]}, {:esaml_util, :threaduntil, 2, [file: '/app/deps/esaml/src/esaml_util.erl', line: 92]}, {Samly.Helper, :decode_idp_auth_resp, 3, [file: 'lib/samly/helper.ex', line: 72]}, {Samly.SPHandler, :consume_signin_response, 1, [file: 'lib/samly/sp_handler.ex', line: 37]}, {Samly.SPRouter, :"-dispatch/2-fun-0-", 4, [file: 'lib/plug/router.ex', line: 246]}, {:telemetry, :span, 3, [file: '/app/deps/telemetry/src/telemetry.erl', line: 320]}, {Samly.SPRouter, :dispatch, 2, [file: 'lib/plug/router.ex', line: 242]}]}

I'll update when I have more time to work on this..

**Comment by jamilbk** [comment]
Thanks for the detailed crash log. What's likely happening is the `access_denied` is causing a match failure which is crashing with the trace you see.

**Comment by ilyatovbin-pp** [comment]
can't get it to work.. Only thing I can think of right now is for you to send me an example of a working SAMLResponse payload to Firezone so that I can compare it with one sent by Google. (you can remove any sensitive data from there, what's important is the structure and fields of the XML)

**Comment by jamilbk** [comment]
@ilyatovbin-pp Finally found some time to work on a fix for this -- will be coming in the 0.6.8 release momentarily.

Issue was a bug in `esaml` which is fixed in Dropbox's fork of the library.

**Comment by jamilbk** [comment]
Google works with the following config:

<img width="635" alt="Screen Shot 2022-11-16 at 9 03 34 AM" src="https://user-images.githubusercontent.com/167144/202245765-dd8ff0ca-81be-4a71-a7db-63564471dee5.png">
<img width="1053" alt="Screen Shot 2022-11-16 at 8 39 24 AM" src="https://user-images.githubusercontent.com/167144/202245801-9e63e269-e090-4503-a4dc-d7e3b5343eca.png">

**Comment by ilyatovbin-pp** [comment]
Can confirm its working fine. one thing though, if you sign in using SAML, you can then change your "local" account password under "My Account", and use it to login without SAML next time, which is a security risk. I'll open a separate issue for this.

**Comment by jamilbk** [comment]
> Can confirm its working fine. one thing though, if you sign in using SAML, you can then change your "local" account password under "My Account", and use it to login without SAML next time, which is a security risk. I'll open a separate issue for this.

This is a good point, and something we've thought about solving. In fact, you can login with the same email address using multiple providers, which is something to consider. It may be better to make the user accounts `sticky` so they can only be associated with a `login_method` once.

We're considering removing local authentication altogether and relying on something like Keycloak or Authentik for self-hosted local auth. In the meantime, `LOCAL_AUTH_ENABLED=false` will prevent this particular issue.
