### ISSUE TITLE
Created a terraform module for firezone deployment

### ISSUE THREAD

**Issue by gchamon** [CloudFire-LLC/cloudfire#1057]
Hey there. Thanks for this awesome project!

I created a module to help me deploy the VPN to AWS: https://registry.terraform.io/modules/gchamon/firezone-vpn/aws/latest

Disclosure: I worked for a little while maintaining subspace, and  I based the module on a previous work I did there.

Please feel free to use this module! Any feedback would be greatly appreciated!

**Comment by jamilbk** [comment]
This is fantastic! Thank you for making this. I'll see if we can link it from somewhere more visible.

**Comment by jamilbk** [comment]
Sorry for the delay here -- added you as a collaborator on our forked version of the module. Thanks again @gchamon!

https://github.com/firezone/terraform-aws-firezone-vpn
