### ISSUE TITLE
Support custom `redirect_uri`s in OIDC configs

### ISSUE THREAD

**Issue by guguducken** [CloudFire-LLC/cloudfire#1058]
When I authenticated using firezone's OIDC, I found that the redirection address used in the OIDC was not I had configured in my Settings, but was generated based on the external address. I think you should use the user-configured redirection address here. Is this a bug? @jamilbk

**Comment by jamilbk** [comment]
Thanks for the report @guguducken! Where are you entering the `redirect_uri` in Firezone? We auto-generate that field based on `EXTERNAL_URL` + `/auth/oidc/:provider/callback/`.

We could expose that setting to be overridable by the user -- is that what you're hoping to achieve?

**Comment by guguducken** [comment]
> We could expose that setting to be overridable by the user -- is that what you're hoping to achieve?

Sorry it took so long to reply @jamilbk. Yes, I think firezone should use the `redirect_uri` when I set it in `/etc/firezone/firezone.rb` instead of auto-generate it. Do you think?
