### ISSUE TITLE
Install Fails - Please update install.sh ( docker-compose outdated , please use docker compose ) 

### ISSUE THREAD

**Issue by decyphertek-io** [CloudFire-LLC/cloudfire#1079]
The install script is looking at docker-compose , which is an outdated python version of docker compose. Docker now uses docker compose plugin that is found at docker compose , not docker-compose. Ubuntu 22.04 had docker-compose already installed and following the official docker docs, installed docker compose plugin. I can manually edit the install.sh script to get this working, though many users may not know to do that and the install will fail for most users. 

Snippet of install.sh :

#!/bin/bash
set -e

dockerCheck () {
  if ! type docker > /dev/null; then
    echo "docker not found. Please install docker and try again."
    exit
  fi

  if command -v docker-compose &> /dev/null; then
    dc="docker-compose"
  else
    dc="docker compose"
  fi

Commands I ran from terminal:

$ docker compose verssion
Docker Compose version v2.12.2
$ docker-compose --version
docker-compose version 1.29.2, build unknown
$ bash <(curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh)
\Error: Automatic installation is only supported with Docker Compose version 2 or higher.
Please upgrade Docker Compose or use the manual installation method: https://docs.firezone.dev/deploy/docker

**Comment by decyphertek-io** [comment]
When I uninstall docker-compose ( Outdated python version)  , I get the following error, even though docker compose plugin is installed still:

$ pip uninstall docker-compose
$ sudo pip uninstall docker-compose
$ bash <(curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh)
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/bin/docker-compose", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for docker-compose
Error: Automatic installation is only supported with Docker Compose version 2 or higher.
Please upgrade Docker Compose or use the manual installation method: https://docs.firezone.dev/deploy/docker

**Comment by decyphertek-io** [comment]
Temporary solution, remove the dash in docker-compose:

$ wget https://github.com/firezone/firezone/raw/master/scripts/install.sh
$ vim install.sh 
if command -v docker compose &> /dev/null; then
    dc="docker compose"
$ bash install.sh

**Comment by decyphertek-io** [comment]
Unfortunately , this is unusable. I do not want to use an offical domain name. How can people run this on a home server ?

$ bash install.sh 
Enter the administrator email you'd like to use for logging into this Firezone instance: adminotaur@decyphertek.io
Enter the desired installation directory (/home/adminotaur/.firezone): 
Enter the external URL that will be used to access this instance. (https://decyphertek): localhost
Would you like to enable automatic SSL cert provisioning? Requires a valid DNS record and port 80 to be reachable. (Y/n): n
Could we email you to ask for product feedback? Firezone depends heavily on input from users like you to steer development. (Y/n): n
Press <ENTER> to install or Ctrl-C to abort.
Unable to find image 'firezone/firezone:latest' locally
latest: Pulling from firezone/firezone

The install is seemingly successful. Then when you try to access the Ip of the server via port 80 , it redirects to port 443 and fails. 
There is a lot of bugs with this. I really like the idea of the product, except as of now is unsuable for most users.

**Comment by decyphertek-io** [comment]
This install methods works perfectly on Ubuntu 22.04 LTS. 

$ curl -1sLf  'https://dl.cloudsmith.io/public/firezone/firezone/setup.deb.sh' | sudo -E bash
$ sudo apt install firezone
$ sudo firezone-ctl reconfigure 
$ sudo  firezone-ctl restart 
$ sudo firezone-ctl create-or-reset-admin
access public IP - https://ip-of-server
Email:    firezone@localhost
Password: randomly generated by script

Omnibus method works better than docker, except not a lot of documentation on how to create a login user?
Can there be an Omnibus maintanined alternative to docker still and can you provide better basic instructions 
on how to login ? I had to find the answer on some random website.

**Comment by jamilbk** [comment]
Thanks for the report. Unfortunately it's not always the case that `docker compose` corresponds to version 2 and `docker-compose` version 1. On AmazonLinux2, for example:

```
[ec2-user@ip-172-31-15-162 ~]$ docker-compose version
Docker Compose version v2.11.2
```

Looks like the `pip uninstall` left the `docker-compose` stub behind, causing the install script to think it was still installed.

Working on a fix for the SSL issue when accessing an instance by its IP -- #1073 should hopefully have a fix out shortly.
