### ISSUE TITLE
Blank screen when trying to access by IP (Docker)

### ISSUE THREAD

**Issue by HenrysCat** [CloudFire-LLC/cloudfire#1099]
After accepting the self-signed cetificate error just a white screen, no login page.

Terminal outpuit from install script, .env and docker-compose.yml below

https://url.privatepastebin.com/17w

Caddy log

https://url.privatepastebin.com/17x

**Comment by jamilbk** [comment]
@HenrysCat #1102 should have fixed this. Thanks for the report!

**Comment by HenrysCat** [comment]
Just confirming this now works, Thanks for all your hard work
