### ISSUE TITLE
can not install on vps, ubuntu 20.04

### ISSUE THREAD

**Issue by admiraltidebringer** [CloudFire-LLC/cloudfire#1103]
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory: unknown

**Comment by jamilbk** [comment]
@admiraltidebringer Do you have IPv6 disabled in your kernel? What does `cat /sys/module/ipv6/parameters/disable` show?

**Comment by admiraltidebringer** [comment]
it showed 1. in fact my vps does not have any ipv6.

**Comment by jamilbk** [comment]
You'll want to remove any `ipv6`-related config from your `$HOME/.firezone/docker-compose.yml` template and add `WIREGUARD_IPV6_ENABLED=false` to your `$HOME/.firezone/.env` file.

**Comment by admiraltidebringer** [comment]
thank you sir. it's working  now

**Comment by admiraltidebringer** [comment]
it's solved
