### ISSUE TITLE
Podman Support

### ISSUE THREAD

**Issue by laweschan** [CloudFire-LLC/cloudfire#1105]
Hi,

   since podman is the default container tool in Fedora, however I found that podman-compose can't execute well for the firezone-docker-compose file, here I have rewrite the script and now should able to execute firezone in podman environment.
   
   here is the ref link: 
    https://discourse.firez.one/t/about-podman-container/265/2

    thanks

Regards,
Lawes

**Comment by jamilbk** [comment]
Thank you! Much appreciated.

**Comment by laweschan** [comment]
thx @jamilbk , a long time ago without release update to public, I would share up-to-date podman script that support the change to 0.6.13 version.

here is the link
https://drive.google.com/file/d/1AuUAdOr2wejgBk9HjujuoF_meTwGTsoH/view?usp=share_link

Cheers

**Comment by jamilbk** [comment]
@laweschan Thanks for the update! I've been meaning to merge this in some form, but have not had time. Would you be able to open a PR with this script in `scripts/podman_install.sh`? That way we can review and discuss further.

Thanks again!

**Comment by laweschan** [comment]
em... try my best, sorry I not famous in github or colaborate dev tool.
let me check how to do it

Merry X'mas
