### ISSUE TITLE
Users can bypass SAML login after the first login.

### ISSUE THREAD

**Issue by ilyatovbin-pp** [CloudFire-LLC/cloudfire#1121]
1. Login using SAML.
2. Change your password under "My Account"
3. Logout.
4. Login with email using the SAML email and the password from step 2.
5. You just bypassed SAML

Should probably disable password change on SAML/OAUTH?

**Comment by jamilbk** [comment]
For now, set `LOCAL_AUTH_ENABLED=false` -- I realized the docs are missing this configuration var so I'll open a PR to add them.

Closing in favor of tracking improvements to this in #1123
