### ISSUE TITLE
Suddenly unable to access `/etc/firezone`

### ISSUE THREAD

**Issue by bootsie123** [CloudFire-LLC/cloudfire#1132]
Hi! It seems something happened with my file permissions and I'm unable to access the `/etc/firezone` directory. Anyone know what the default permissions for it are? Currently, it's showing up as: 

`drwx------   2 firezone firezone   4096 Nov 19 21:14 firezone`

Thanks!

**Comment by bcookatpcsd** [comment]
mine are 0755 root:root (docker)

0700 firezone:firezone on local install (fedora)

looks consistent

**Comment by bootsie123** [comment]
Gotcha. After coming back to it a day later, it looks like I'm just an idiot. I was default installation user which while it does have sudo permissions, isn't root. After switching to root I was able to access it
