### ISSUE TITLE
[Suggestion] docker update --restart=unless-stopped

### ISSUE THREAD

**Issue by bcookatpcsd** [CloudFire-LLC/cloudfire#1133]
Possibly was something on my end.. 

Alpine in a vm with linux-virt kernel; new install not upgrade or import

Current alpine does not have docker-compose 2.x in repos.. Installed bailed (as it should) when version was not correct. 

Had to restart install several times, (server name typos, etc) after all was working I restarted docker to confirm, only caddy started.. 

[Suggestion]
```
 docker ps -a | grep firezone | awk '{print $1}' | xargs  docker ps -a | grep firezone | awk '{print $1}'
```

got me what I was looking for.. 

I've not looked at the docker-compose or any log files.. again I may have been the problem.. 

I had an initial could not connect to postgres and after the "x'th" time things came up. 

![image](https://user-images.githubusercontent.com/55087301/202920509-8525c16f-1ca4-4526-858d-cec77f5bee56.png)

Install looks great. 

OT: autoheal
https://hub.docker.com/r/willfarrell/autoheal/#!

**Comment by jamilbk** [comment]
Thanks for the report! Fix incoming in a bit.
