### ISSUE TITLE
Port Forwarding/Translation

### ISSUE THREAD

**Issue by thesosguy** [CloudFire-LLC/cloudfire#1134]
It would be amazing to be able to forward a public TCP/UDP ports to a specific client.

Use case 1 would be to expose a container or application to the internet with out having to open local firewall ports or worry about changing public IPs. Like a reverse proxy but over the wireguard tunnel.

Use case 2 would be a router that is a wireguard client to Firezone that is on a dynamic ip or inside some other restricted network but needs to port forward an arbitrary TCP or UPD port to a local client.

Example:
  VPS Hosting Firezone -----------> Wireguard Client 
        `1.2.3.4:21080 `  --> PAT -->   `10.6.1.2:80 `                 

Currently with wireguard I'm using the following with `UFW`
`DEFAULT_ACCEPT_FORWARD=ACCEPT`
and added the following rule the the `*nat` rule in  `ufw/before.rules`
`-A PREROUTING -i enp1s0 -p tcp --dport 21080 -j DNAT --to-destination 10.6.1.2:80`

Thank you

**Comment by AndrewDryga** [comment]
I think one of the use cases for this is ngrok replacement for local development (eg. testing webhook integrations).

**Comment by jamilbk** [comment]
Good suggestion! We're re-architecting things in this area quite a bit at the moment to support our own platform-native client applications, so this will probably need to wait a bit until that's done. I'll keep this issue open to foster discussion until then.

**Comment by thesosguy** [comment]
Thank you! 

@AndrewDryga I have tested ngrok but it is not stable on OpenWRT for my application yet.
So far wireguard has been flawless.

I look forward to the development of Firezone.
