### ISSUE TITLE
Container crashing when user adding device with subnet ip allocation (v0.6.7)

### ISSUE THREAD

**Issue by spot94** [CloudFire-LLC/cloudfire#1135]
### Impossible to start server, container log: 

`19:51:14.138 [notice] Application fz_wall exited: FzWall.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzWall.Server
    ** (EXIT) an exception was raised:
        ** (RuntimeError)   Error executing command   nft 'add element inet firezone user2_ip_devices { 10.74.6.0/24 }'
.
  Exit code: 1
  Error message:
  Error: interval overlaps with an existing one
add element inet firezone user2_ip_devices { 10.74.6.0/24 }
                                             ^^^^^^^^^^^^
Error: Could not process rule: File exists
add element inet firezone user2_ip_devices { 10.74.6.0/24 }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            (fz_common 0.6.7) lib/cli.ex:28: FzCommon.CLI.exec/2
            (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir 1.14.1) lib/enum.ex:980: anonymous fn/3 in Enum.each/2
            (elixir 1.14.1) lib/enum.ex:4307: anonymous fn/3 in Enum.each/2
            (elixir 1.14.1) lib/enum.ex:4751: Enumerable.List.reduce/3
            (elixir 1.14.1) lib/enum.ex:4307: Enum.each/2
            (fz_wall 0.6.7) lib/fz_wall/cli/live.ex:141: FzWall.CLI.Live.restore/1
            (fz_wall 0.6.7) lib/fz_wall/server.ex:20: FzWall.Server.init/1`

Steps to reproduce:
1. Add device with subnet mask in IP allocation text input: xxx.xxx.xxx.xxx/mask
2. Enjoy permanent crash

**Comment by jamilbk** [comment]
Thanks for the report! `nftables` doesn't allow overlapping subnets, but our device validators should have prevented this hitting the DB in the first place. Will queue this to get fixed. In the meantime, (unfortunately) you'll have to remove the offending device(s) manually from your Postgres DB.

Just to better understand the use-case, may I ask why you're using a `/24` for the device interface IP?

**Comment by jamilbk** [comment]
cc @conectado

**Comment by spot94** [comment]
> Just to better understand the use-case, may I ask why you're using a /24 for the device interface IP?

I made an account for friend, he said its a erroneous copy-past
