### ISSUE TITLE
Serving from another subdirectory than "/"

### ISSUE THREAD

**Issue by tengzl33t** [CloudFire-LLC/cloudfire#1137]
Can't serve firezone with nginx from another subdirectory like "/vpn" properly, getting 404 for paths /images, /dist and some others.
Looks like it's problem with Phoenix configuration, could you fix it?

Similar problem from another repo:
https://github.com/asciinema/asciinema-server/pull/365
And possible solution:
https://geoffreylessel.com/2016/hosting-a-phoenix-app-in-a-subdirectory-with-nginx/

Using dockerized firezone with disabled caddy and standalone nginx as proxy.
[logs.txt](https://github.com/firezone/firezone/files/10064950/logs.txt)

**Comment by jamilbk** [comment]
Thanks for the report! Just a few clarifying questions:

- What version of Firezone?
- Does your `EXTERNAL_URL` reflect the full URL you're trying to serve under? 
- Are you using the bundled nginx config that ships with Omnibus Firezone or a custom one?

**Comment by tengzl33t** [comment]
- Latest one, docker.
- Yes, it's https://domain.com/vpn/
- Latest standalone nginx from dnf/yum

**Comment by jamilbk** [comment]
This is fairly non-trivial to implement as a runtime configuration in Phoenix. Ideally it should be parsed from `EXTERNAL_URL`. Going to track the TODOs here for a future work session:

- [x] Parse `EXTERNAL_URL` and configure `FzHttpWeb.Endpoint` for generating prefixed links
- [ ] Make [font load path](https://github.com/firezone/firezone/blob/157ac0bb38df1ed162e60362d9ba58bedf7d91b6/apps/fz_http/assets/config.prod.js#L23) configurable at runtime
- [ ] Make [websocket prefix](https://github.com/firezone/firezone/blob/157ac0bb38df1ed162e60362d9ba58bedf7d91b6/apps/fz_http/lib/fz_http_web/endpoint.ex#L11) configurable at runtime
- [ ] Make [Plug.Static serve path](https://github.com/firezone/firezone/blob/157ac0bb38df1ed162e60362d9ba58bedf7d91b6/apps/fz_http/lib/fz_http_web/endpoint.ex#L37) configurable at runtime

**Comment by AndrewDryga** [comment]
This is closed in https://github.com/firezone/firezone/commit/4fe6b5ec316444282aad182f6acaba1952d83d12. Once a new version is released you should be able to configure `EXTERNAL_URL` with a subdirectory.
