### ISSUE TITLE
Having trouble setting up Outbound Emails

### ISSUE THREAD

**Issue by Aniket-IN** [CloudFire-LLC/cloudfire#1144]
Hi, 
I just installed Firezone (with Docker), it's working very well.
But I couldn't get the outbound emails to setup.

I'm gonna use Gmail SMTP, couldn't find any guide/example how to setup the emails.

I've tried setting up the env variables like this:
```env
OUTBOUND_EMAIL_FROM="firezone@mydomain.com"
OUTBOUND_EMAIL_PROVIDER="gmail"
OUTBOUND_EMAIL_CONFIGS='{"gmail": {"access_token": "..."}, "smtp": {"relay": "smtp.gmail.com"}}'
```
But this doesn't seem to work.

Can anyone please help?

**Comment by jamilbk** [comment]
You'll want to specify either the `gmail` provider, or `smtp` provider (in your JSON-formatted `OUTBOUND_EMAIL_PROVIDER` config), but probably not both. The `OUTBOUND_EMAIL_PROVIDER` is used to select the provider to use.

See [Swoosh's documentation](https://hexdocs.pm/swoosh/Swoosh.Adapters.SMTP.html) for the SMTP adapter for more details on all the options allowed and [Google's documentation](https://www.labnol.org/gmail-smtp-send-emails-220530) for relaying through SMTP.

FWIW we only use outbound emails for password resets, so if you integrate and OIDC or SAML provider then setting up outbound email won't be used.

The `firezone` container logs should have more information about why the password reset / magic link email would fail to send.

**Comment by Aniket-IN** [comment]
Thank you so much @jamilbk it worked.
Using the SMTP adapter it works.

Here's how I did it (for anyone having this issue in-future)
```env
OUTBOUND_EMAIL_FROM="firezone@mydomain.com"
OUTBOUND_EMAIL_PROVIDER="smtp"
OUTBOUND_EMAIL_CONFIGS='{"smtp": 
    {  
        "relay": "smtp.gmail.com",
        "username": "foo@gmail.com",
        "password": "...",
        "port": 587
    }
}'
```
