### ISSUE TITLE
Bypass Caddy since I already have Nginx

### ISSUE THREAD

**Issue by JohnB17** [CloudFire-LLC/cloudfire#1145]
I already have Nginx running on the host so it is using 80 and 443, how can I bypass caddy and reverse proxy with Nginx? I can't get access to the container on the host.

**Comment by jamilbk** [comment]
You're free to use whatever reverse proxy you'd like, but `caddy` is much easier to configure for Firezone. See [custom reverse proxy for inspiration](https://docs.firezone.dev/deploy/advanced/reverse-proxy/).

**Comment by JohnB17** [comment]
The connection times out from the host.

**Comment by jamilbk** [comment]
> The connection times out from the host.

You'll need to [expose](https://docs.docker.com/compose/compose-file/#ports) the phoenix listen port. In your `$HOME/.firezone/docker-compose.yml`, add somthing like

```yaml
# ...
services:
# ...
  firezone:
# ...
    ports:
      - 13000
```

No you can point Nginx to port 13000 for Firezone.

**Comment by JohnB17** [comment]
Ah oops. I tried something like that, but I did it with the VPN port accidentally.

**Comment by JohnB17** [comment]
Now it's saying connection refused.

docker-compose.yml
```
# ...
services:
# ...
  firezone:
# ...
    ports:
      - 51820:51820/udp
      - 13000
```
Nginx config:
```nginx
server {
    listen         443 ssl;
    server_name    management.mysite.com;
    
    access_log /var/log/nginx/management.app-access.log;
    error_log  /var/log/nginx/management.app-error.log error;
    
    ssl_certificate      /etc/letsencrypt/live/management.mysite.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/management.mysite.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:13000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        gzip off;
    }
}
```
```
root@localhost:~# curl 127.0.0.1:13000
curl: (7) Failed to connect to 127.0.0.1 port 13000 after 0 ms: Connection refused
```

**Comment by JohnB17** [comment]
Just bypassed Docker compose and ran them in separate containers.

**Comment by jamilbk** [comment]
> Just bypassed Docker compose and ran them in separate containers.

This works too -- certainly an option. Thanks for the update.
