### ISSUE TITLE
Custom postup/postdown options

### ISSUE THREAD

**Issue by DanteG41** [CloudFire-LLC/cloudfire#1146]
Hi there. Is there a way to specify postup/postdown options? It would be great if I could add custom postup/postdown options for different OS (e.g. windows, linux, android). thx in advance.

**Comment by jamilbk** [comment]
Thanks for the suggestion! I'm not sure this is in scope for Firezone -- could you elaborate a little more on the use case?

**Comment by DanteG41** [comment]
For me the main reason is private zone dns. PostUp scripts enable using in-office dns servers only for private dns zones therefore the rest of dns traffic go through ISP. By the way, I wrote a small patch to resolve this feature in firezone. I’ve never written Elixir so my code is terrible, but perhaps it could explain my idea. 

For instance:
Windows: PostUp = powershell Add-DnsClientNrptRule -NameServers '10.0.0.1'  -DisplayName 'firezoneDNS' -Namespace '.firezone.dev
PostDown = powershell @(Get-DnsClientNrptRule).where{($_.Namespace -like '.firezone.dev')}.Name.foreach{Remove-DnsClientNrptRule -Force -Name $_}

Linux(systemd): PostUp = resolvectl dns %i 10.0.0.1 && resolvectl domain %i domain.local && resolvectl default-route %i false

https://github.com/DanteG41/firezone/commit/5465a0eb81a123f1cdf02c776871f741d1c0661c

**Comment by jamilbk** [comment]
@DanteG41 Ah -- I see. We actually have Split DNS in our backlog, but this would require our own custom WireGuard clients to implement properly (these are still under construction).

**Comment by michaelmarcuccio** [comment]
Split DNS would be amazing! Pretty important feature for some cloud endpoints that can't get static IPs.

**Comment by jamilbk** [comment]
Tracking in #1158
