### ISSUE TITLE
Group-based Access Policies

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1157]
Add the ability to associate a user to one or more Groups. A Group can either be manually created by an administrator, or automatically created based on some ruleset defined for matching keys from the incoming JWT (OIDC authentication) or XML (SAML authentication).

These Groups can then be associated with a Policy, which is a collection of `AllowRules` and `Configuration` to apply to the users in the Group.

**Comment by ihard** [comment]
As a rule, access to the service is also regulated by the user's membership in any group.
It would be great if it would be possible to refuse a user at the entrance if he is not a member of any (or some specific) group.

**Comment by binaryfire** [comment]
Was just about to open and issue for this. We’re using Headscale’s ACLs to manage groups at the moment. Does the job, but a self-service UI would be much better. A groups feature is the only thing stopping us from giving Firezone a go!

+1 for preventing access if no group is assigned, and syncing groups with SAML / OIDC metadata

**Comment by anemyte** [comment]
Please add this feature!

**Comment by jamilbk** [comment]
This is [coming in 1.0](https://www.firezone.dev/product/early-access) (targeting Q3 of this year). Groups [will be synced from your IdP](https://github.com/firezone/firezone/issues/1437) or can be added manually. A Policy can be created which will then link a Group to a Resource, allowing all users within that Group access.

**Comment by jamilbk** [comment]
Will be released in 1.0-beta due out shortly
