### ISSUE TITLE
Split DNS

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1158]
Similar to how WireGuard's crypto-key routing (`AllowedIPs`), add the ability for a list of names to be resolved using specific(s) DNS resolver, with all others resolved using the system or default DNS resolver.

**Comment by jamilbk** [comment]
This will require our own clients (in development to various degrees).

**Comment by esidate** [comment]
This would be a killer feature. I've always needed it.

**Comment by jamilbk** [comment]
An early version of this will be coming in 1.0 (targeting Q3 of this year).

**Comment by jamilbk** [comment]
Refs #2043

**Comment by jamilbk** [comment]
Will be implemented in #2043
