### ISSUE TITLE
OIDC Logout issues - post_logout_redirect_uri invalid

### ISSUE THREAD

**Issue by ShakataGaNai** [CloudFire-LLC/cloudfire#1159]
When utilizing SSO - specifically Okta via OIDC, there is no option to configure the post_logout_redirect_uri value, and the value set by the application is invalid. If you attempt to logout of the web interface, you get:

> 400 Bad Request
> Your request resulted in an error. The 'post_logout_redirect_uri' parameter must be a Logout redirect URI in the client app settings

![Screenshot 2022-11-30 at 4 43 05 PM](https://user-images.githubusercontent.com/1415068/204938627-018e279d-d43e-4d51-b363-549912105031.png)

Based on Okta logs and https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/authentication.ex#L84 - Firezone sends literally "/" as a logout location. At least in Okta, and probably other systems "The logout redirect URIs must be absolute URIs."

![Screenshot 2022-11-30 at 4 46 54 PM](https://user-images.githubusercontent.com/1415068/204939013-f8d395cb-1d6c-4712-91f0-65063ba271f7.png)

This is only an issue for user experience. They don't *need* to logout (and the application does in fact clear their cookies properly), it just confuses them when they try.

**Comment by jamilbk** [comment]
Thanks for the report! That should be the full URI and not simply a path. Will have a fix out in a bit.

**Comment by asweet** [comment]
Getting the same error on logout, also OIDC with Okta. This is on 0.7.19
