### ISSUE TITLE
Configuration UX improvements

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1162]
- [ ] Allow certain ENV vars to take precedence over `configurations` table, e.g. "LOCAL_AUTH_ENABLED" and other deployment/infrastructre related fields
- [x] Move other ENV var config to `configurations` only
- [ ] Document this in upgrade notes

**Comment by AndrewDryga** [comment]
- [ ] Rewrite `Configurations` module to allow ENV variable overrides for any field with a coded naming convention (split |> upcase |> ...)
- [ ] Write validation for configuration fields and print user-readable errors when data is invalid
- [ ] Provide a migration helper that collects previous version configuration and explicitly asks for missing variables
