### ISSUE TITLE
add version tag to docker deployment script

### ISSUE THREAD

**Issue by laweschan** [CloudFire-LLC/cloudfire#1164]
Hi, 

  for identify and should we redownload the script for deployment, is that possible to add the version tag or change info into the script, so that we can easy to identify the script has any config update?

  thanks

Regards,
Lawes

**Comment by jamilbk** [comment]
@laweschan You can edit the `$HOME/.firezone/docker-compose.yml` file to lock the `firezone/firezone` image to a specific version if you wish. This file is not overwritten on upgrade.
