### ISSUE TITLE
Configuration SAML google error access_denied {:assertion, {:error, :no_signature}}

### ISSUE THREAD

**Issue by rchekhina** [CloudFire-LLC/cloudfire#1165]
HI,

I have tried to configure SAML Google following the doc https://docs.firezone.dev/authenticate/saml/google/#create-a-saml-connector

but when I try to connect to firezone with saml I have this error message:

error access_denied {:assertion, {:error, :no_signature}}

I have create the saml google like following:

- ACS URL: https://firezone-fr.sq1.io/auth/saml/sp/consume/google
- ENTITY ID: urn:firezone.dev:firezone-app
- Signed response: checked
- Name ID format: EMAIL
- Name ID: Basic information > primary email
- Service status: all the organization ON for everyone
- downloaded the metadata 

on  firezone I have added the saml identity provider as following:

- Config ID: google
- Label: Google
- Base URL: https://firezone-fr.sq1.io/auth/saml
- Metadata: content of metadata previously downloaded

Other thing after I created the saml identity provider on firezone, on the login page I have twice "Sign in with Google" one for oidc and the other one for saml. When the saml will works, how can I disable the oidc "Sign in with Google" please.

thanks in advance.
best regards.

**Comment by rchekhina** [comment]
HI,

I have speak with Jamil and to resolve the problem I have to disable this option "Require signed assertions" on Firezone. 
And for the doble Sign in Google to remove the on with oidc I have just to comment this line on the .env file of docker-compose "#AUTH_OIDC_JSON="{\"google\":{\"discovery_document_uri\ .........."
and stop/start the docker-compose.

Best regards.

**Comment by jamilbk** [comment]
Re-opening because this is a bug in our documentation. I can confirm the `Require signed assertions` box shouldn't be checked on the docs page here:

https://docs.firezone.dev/authenticate/saml/google/
