### ISSUE TITLE
Error 403 "Bad Audience" with SAML authentication using AWS SSO

### ISSUE THREAD

**Issue by ghost** [CloudFire-LLC/cloudfire#1179]
Hello! I'm attempting to configure SAML 2.0 authentication for Firezone using AWS SSO (which is undocumented). I created a custom SAML app in AWS Identity Center with the following details:

> Application ACS URL: https://firezone.mydomain.com/auth/saml/sp/consume/aws
Application SAML audience: `SAML_ENTITY_ID`, which I changed from the default to `https://firezone.mydomain.com/sp` in the `.env` file
Attribute mappings: `Subject` mapped to `${user:email}`, format emailAddress
Application properties: left blank

In Firezone's SAML Configuration panel:

> Config ID: aws
Base URL: https://firezone.mydomain.com/auth/saml (unchanged)
Metadata: The metadata downloaded from AWS
Enabled: Sign requests, sign metadata, auto-create users
Disabled: Require signed assertions, require signed envelopes

No other environment variables were changed. When I try to login with SSO, I get the "access_denied: bad audience" 403 error. What could I be doing wrong? Thanks in advance!

**Comment by jamilbk** [comment]
Is the error coming from AWS or Firezone?

**Comment by ghost** [comment]
It's fixed now! The problem was coming from AWS. The attribute mapping `Subject` should have had the format Unspecified, not emailAddress. For whatever reason, setting the attribute as emailAddress would cause authentication on the IdP side to fail, and it wouldn't return the SAML assertion to Firezone.

**Comment by jamilbk** [comment]
cc @gongjason AWS SAML ;-)
