### ISSUE TITLE
/devices page fails to show some info if client is connected over IPv6

### ISSUE THREAD

**Issue by toreanderson** [CloudFire-LLC/cloudfire#1196]
It would appear that if the client is accessing the VPN over IPv6, the following info is missing/incorrect on the /devices page:

* Remote IP – cell is empty
* Latest Handshale – shows as «Never»
* Transfer – shows as «0.00 B received 0.00 B sent»

For clients using IPv4 transport, the above information is reported correctly.

Inspecting the kernel state with `wg` shows everything is fine. The only significant difference between IPv4 and IPv6 users is the `endpoint:` attribute, which is reported as, e.g., `endpoint: 192.0.2.42:54321` for the former and, e.g., `endpoint: [2001:db8::abcd]:43210` for the latter.

This is Firezone v0.6.11 (`:latest` container) running on AlmaLinux 9.1.

**Comment by jamilbk** [comment]
Thanks for the report @toreanderson! cc @conectado -- the new Gateway stats updater in 0.8 will probably fix this by default.

**Comment by jamilbk** [comment]
This may be related to #1202 -- Just merged a fix for IPv6 connectivity. [Docs](https://docs.firezone.dev/deploy/docker) have been updated with instructions to enable IPv6.
