### ISSUE TITLE
/settings/site page has incorrect info about omitting DNS servers

### ISSUE THREAD

**Issue by toreanderson** [CloudFire-LLC/cloudfire#1197]
The `/settings/site` page says that if you leave the *DNS Servers* field empty, the generated WireGuard configs will not contain the `DNS` attribute (note that 1.1.1.1 and 1.0.0.1 are here "greyed out", i.e., they were not input by me, but seems rather to be meant as an example of valid input).

![bilde](https://user-images.githubusercontent.com/4557060/207814136-beba094f-fd35-48ce-a701-2c8cb9164377.png)

However, that does not actually appear to be the case. With the *DNS Servers* field empty, as shown above, the generated settings will default to using 1.1.1.1 and 1.0.0.1 as the DNS servers:

![bilde](https://user-images.githubusercontent.com/4557060/207814709-5bfc5e06-6497-4651-bae7-63aa3a7cd100.png)

I've found that if you enter a space character in the *DNS Servers* field and press *Save* ONCE, the `DNS` attribute will not be included in the generated config files. However if you press *Save* twice (or return to the `/settings/site` page later and press *Save*, possibly after changing some other attribute), the generated config files will again default to using 1.1.1.1 and 1.0.0.1.

**Comment by jamilbk** [comment]
Thanks for the report! Things are improving in this area pretty soon as part of 0.8. Can I ask if you have `WIREGUARD_DNS` env var set?

**Comment by toreanderson** [comment]
`WIREGUARD_DNS` is not set,  no.
