### ISSUE TITLE
Isolate User Devices

### ISSUE THREAD

**Issue by boredgamesdev** [CloudFire-LLC/cloudfire#1199]
Looking for a feature to block devices from each user from communicating with other user devices. I tried creating rules in the Egress Rules but I couldn't get what I had in mind working. Thank you.

**Comment by jamilbk** [comment]
Thanks for the suggestion! Things are changing a bunch around firewall rules in 0.8 so we'll probably hold off on this feature until then. Tracking this in https://github.com/firezone/firezone/issues/833
