### ISSUE TITLE
QR code is *still* too small in some cases

### ISSUE THREAD

**Issue by toreanderson** [CloudFire-LLC/cloudfire#1217]
This is essentially the same bug as #606, which was closed.

Our default `AllowedIPs` setting is 797 characters long, containing 45 prefixes. When I try to scan this code from the Android WireGuard app, it fails with the error message «Unable to import tunnel: Unknown section in Config», if it manages to scan anything at all (sometimes it doesn't).

Other QR/barcode scanners generally fail to scan anything.

If I shorten `AlllowedIPs`, it works. It also works if I download the generated config file and run `qrencode -t ansiutf8` on it.

So I believe the 300x300 px resolution used by Firezone is still too small. I would suggest making the resolution considerably bigger (4K UHD maybe?), admin-configurable, or dynamically determined based on the size of the encoded configuration file.

To prevent it from being too massive in the default key view pop-up, maybe some "click to maximise" function would be appropriate.

Edit: I tried to download the `.conf` file and pipe it to `qrencode -t PNG`.  The resulting PNG was 351x351 px (it would appear that `qrencode` dynamically determines the necessary resolution by default), and the WireGuard app was able to import it without any issues.

**Comment by jamilbk** [comment]
Thanks for the detailed report! Gosh darnit, those pesky QR codes!

There are some inherent limits to the size of QR codes. The [maximum seems to be](https://www.qrcode.com/en/about/version.html) `23,648` bits, or about 2.9 KB.

<img width="847" alt="Screen Shot 2022-12-20 at 10 18 39 AM" src="https://user-images.githubusercontent.com/167144/208715474-09ebf5b1-c5ad-472b-bea7-f0962c6728fe.png">

Assuming one byte per character, configs could theoretically easily surpass that limit with a long AllowedIPs list or many Peers entries. Roughly on the order of 100 or 200 AllowedIPs entries, each about 15 chars, will surpass the limit.

We *are* working on our own custom clients to make this a non-issue, but perhaps for the time being the solution is detect when the WG config is too large to be shown in a QR code, and simply state as such.

**Comment by toreanderson** [comment]
> perhaps for the time being the solution is detect when the WG config is too large to be shown in a QR code, and simply state as such.

Agreed, but that is somewhat orthogonal to the issue I'm reporting because my WG configs are *not* too large to be represented as QR codes, it's just that Firezone squeezes them into a too small PNG so they become unintelligible to the WireGuard app (and other code reader apps).

**Comment by jamilbk** [comment]
#1222 Should fix this.
