### ISSUE TITLE
Problem with 2 servers firezone using same google workspace and SAML entity ID

### ISSUE THREAD

**Issue by rchekhina** [CloudFire-LLC/cloudfire#1224]
HI,

I have 2 Firezone servers that use the same google workspace . I have connected the first one to google SAML without problem but when I try to connect the second one I was forced to put a different Entity ID because i can t be the same as urn:firezone.dev:firezone-app of the first saml so I put urn:firezone.dev:firezone-app-ir and after configure saml on firezone and I try to sign in I have this error message:
`access_denied {:saml_error, 'urn:oasis:names:tc:SAML:2.0:status:Requester', 'Invalid request, ACS Url in request https://firezone.sq1.io/auth/saml/sp/consume/google doesn\'t match configured ACS Url https://firezone-fr.sq1.io/auth/saml/sp/consume/google.'}`

the ACS url that find firezone on google is the one of the first server not the second one. I think that Firezone request the saml ACS url  on google with the entity id urn:firezone.dev:firezone-app for that I have this error message.

Can you check it please?

Best regards.

**Comment by jamilbk** [comment]
Hi @rchekhina -- the ACS URL is entered as part of the SAML setup within Google. Double-check that's correct for each instance:

![acs url](https://user-images.githubusercontent.com/52545545/205353768-0c8696b2-5fb2-42a7-98fa-9d68b23dfb05.png)

**Comment by rchekhina** [comment]
HI Jamil,

Yes I know but look my configuration.
first firezone server:
  - google saml:
 
![image](https://user-images.githubusercontent.com/78473404/209077869-208a6655-e212-45e3-a18a-02df321669ae.png)

 - firezone configuration:
![image](https://user-images.githubusercontent.com/78473404/209078046-1dc72c07-5e65-4d9d-82e4-8e3951b0de5c.png)

second firezone server:
 - google saml:
 
![image](https://user-images.githubusercontent.com/78473404/209078313-3e45c9cd-355a-4e2b-b5be-7e8df7ef84c5.png)

- firezone configuration:

![image](https://user-images.githubusercontent.com/78473404/209078550-cd18cdc5-fb8a-44ea-a43c-1eb3eccd9218.png)

so the configuration is good but when i try to sign in on the second server I have this error message:

access_denied {:saml_error, 'urn:oasis:names:tc:SAML:2.0:status:Requester', 'Invalid request, ACS Url in request https://firezone.sq1.io/auth/saml/sp/consume/google doesn\'t match configured ACS Url https://firezone-fr.sq1.io/auth/saml/sp/consume/google.'}

so I think that firezone use the Entity ID to request the ACS Url from google.

Best regard.

**Comment by jamilbk** [comment]
Thanks for clarifying! Very strange. And the metadata is different between the two as well?

The only other place where configuration may be overlapping is your browser cookies, but those should be isolated per instance as well.

Assuming `EXTERNAL_URL` is correct for both?

**Comment by jamilbk** [comment]
Have you updated `SAML_ENTITY_ID`?

https://docs.firezone.dev/authenticate/saml/#entity-id

**Comment by rchekhina** [comment]
HI Jamil,

ok so I need to set the variable SAML_ENTITY_ID on the .env file. I will try it thanks.
Best regards.

**Comment by rchekhina** [comment]
HI Jamil,

It works. Thank you very much ;)
