### ISSUE TITLE
[BUG]: About data back and restore

### ISSUE THREAD

**Issue by linuxperf** [CloudFire-LLC/cloudfire#1261]
I backup firezone postgres data, then reinstall firezone and restore postgres data. I found deivce config is all the same, but wireguard connect can not establish. 
I debug wireguadr kernel module:
```
echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control
```
and dmesf show:
```
wireguard: wg-firezone: Invalid MAC of handshake, dropping packet from xxx.xxx.xxx.xxx
```
I do not know why. Will firezone reinit mac cookies???

**Comment by jamilbk** [comment]
Thanks for the report! Can I ask which version this is? Also, is this on a Docker or Omnibus install?

If Docker, did you back up the `$HOME/.firezone/.env` file as well? That contains database encryption keys which are used to encrypt sensitive fields.

Though if these were missing, Firezone usually fails to start.

Lastly, does the source ip match the expected ip of the client that’s connecting? And are you using a load balancer or layer 4 proxy of any kind?

**Comment by linuxperf** [comment]
my virtualbox VM network mode is: 
client <--   L2 link  --> firezone server
I have backup $HOME/.firezone/.env. I will repeat this scene. Please wait me some days.

**Comment by jamilbk** [comment]
Hmm, I see. This error usually happens when there's a connectivity issue and not (usually) when the keys don't match. If new configs work fine, then I *think* that would further suggest some kind of connectivity issue, but happy to look into further pending more information.

**Comment by linuxperf** [comment]
I have know reason. firezone reinstall will dynamicly generate wireguad sha key for interface, but this key do not store in
database. So I restore backup data and all the device failed to establish vpn connection.

**Comment by jamilbk** [comment]
Yes, the private key does not the leave the server. [It's stored in `$HOME/.firezone/firezone`](https://docs.firezone.dev/reference/file-and-directory-locations/). I've added #1270 to better document our backup and restore process. Thanks for reporting!
