### ISSUE TITLE
Require Authentication - Redirect to logon page

### ISSUE THREAD

**Issue by mortenbirkelund** [CloudFire-LLC/cloudfire#1262]
When using the functionality "Require Authentication For VPN Sessions", which requires the user to re-authenticate occasionally, then it could be a nice feature to redirect the user the the Firezone logon page. 

This is the same functionality as you see on many public wifi, where you will be redirected to the wifi's login page, where you can be forced to accept terms and conditions or something similar before accessing the internet through the network.

At the moment, what happens is that the you just fail to reach the desired website. I find myself refreshing couple of times, until I suddenly realized that I need to re-authenticate.

**Comment by AndrewDryga** [comment]
Hello @mortenbirkelund, this is a great feature suggestion and something we already have on our backlog! Unfortunately, it won't come fast because we need to build client apps first for each of the platforms, so no ETA for now.

**Comment by mortenbirkelund** [comment]
Thanks for the info.

BTW, are you planning on an linux client for debian based systems?

**Comment by AndrewDryga** [comment]
We plan to have clients for all major OSes (Windows, Linux, iOS, Android).

**Comment by jamilbk** [comment]
Unfortunately client apps are needed as @AndrewDryga points out. See prior discussion: https://github.com/firezone/firezone/issues/689

**Comment by jamilbk** [comment]
In the short-term, we're considering refactoring this feature to be a little clearer about its intended use-case, and up the security a tad. See #1236
