### ISSUE TITLE
Is it possible to not hard-code client's IP Address?

### ISSUE THREAD

**Issue by MohammedNoureldin** [CloudFire-LLC/cloudfire#1263]
Hi,

I am wondering if it is somehow possible to not hard-code the IP of the client interface `[interface] Address = 1.2.3.4/32`, but rather assign it dynamically by the server. So basically to assign any free IP address when the client connects?

**Comment by jamilbk** [comment]
Hi @MohammedNoureldin -- unfortunately it's not. This is due to WireGuard's [cryptokey routing](https://www.wireguard.com/#:~:text=At%20the%20heart%20of%20WireGuard,peer%20has%20a%20public%20key.) which cryptographically associates a Peer's PublicKey to its tunnel address.

Could I ask what you're trying to achieve with a dynamic IP? Maybe we can find a workaround or better solution.

**Comment by MohammedNoureldin** [comment]
Thank you @jamilbk for your reply.

Basically I want to use Firezone with users that authenticate against identity provider (with LDAP backend for example). The admin should only create the users in LDAP directory, without touching anything in Firezone. The user should be able automatically to login to the vpn using his LDAP credentials and download his config without the need to care about what the config is.

So the goal of my question was to be able to send a unified config file for clients without the need to generate new config for each user.

**Comment by jamilbk** [comment]
Ahh I see. I understand now. Thanks for clarifying.

This flow will be enabled by our custom clients, currently under development. With those, users won't have to worry about WireGuard configurations -- they'll simply log into the IdP and be connected, like you'd expect from any other business VPN.

In light of that, going to close this issue. Thanks for the feedback!

**Comment by MohammedNoureldin** [comment]
Thank you for letting me know @jamilbk. Will this custom client feature be open source and free to be used or will it need any license? And is there any expected release date for it?

**Comment by jamilbk** [comment]
Like the core product, we plan to open-source them as well. Though if you're planning to use Firezone in production for your team, it might be good to have a chat to see how we can help further, especially if you're using LDAP. We've had some interest in providing an LDAP connector and want to be sure it's built right.

As for ETA on the client apps, nothing concrete yet. We're aiming for Q1 '23, but you know how engineering timelines go.

**Comment by MohammedNoureldin** [comment]
Sure @jamilbk, I will be glad to help in LDAP. Though, in this phase using LDAP by the mediation of an IdP is also a good enterprise level solution in my opinion. The only cons is that IdP is complexer than using vanilla LDAP.

Just let me know how I can support.

I am excited about this custom client feature! :)

**Comment by MohammedNoureldin** [comment]
Hi @jamilbk, is there any place where I can follow the updates about the custom client feature? I checked the branches but found nothing relevant.

**Comment by jamilbk** [comment]
Hey @MohammedNoureldin -- we're working on publishing some sort of high-level product roadmap to make these things easier to follow, but for now we've opened #1329 to track feedback and progress on them.
