### ISSUE TITLE
Accessing documentation Deploy -> Docker crashes

### ISSUE THREAD

**Issue by szEvEz** [CloudFire-LLC/cloudfire#1264]
When accessing <https://docs.firezone.dev/deploy/docker/> I get the following error message

![image](https://user-images.githubusercontent.com/17480438/210384962-d00d14e7-0394-47ee-ad31-b53bf8be7154.png)

**Comment by jamilbk** [comment]
Fixed in #1257, just deployed. Thanks for the report!

**Comment by szEvEz** [comment]
That was quick, thank you!
