### ISSUE TITLE
Forms UI improvement

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1268]
- [ ]  Real-time LiveView validations (use real changesets for forms and add validation event handles using `phx-change="validate"`)
- [ ] Submit button should be disabled if there are no changes in the changeset 
- [x] Replace modals with regular pages (modals are common sign of bad UX, they are especially bad on mobile devices)
- [x] Disable all password forms if `enable_local_authentication` is false and don't allow to create users with a password
- [x] Add `for` attribute to `label`'s

**Comment by Valentine-Mario** [comment]
@AndrewDryga is this PR still available?

**Comment by AndrewDryga** [comment]
Hey @Valentine-Mario, we are working on most of those points already in #1479 so I think it's not the best time to change UI, at least for the next few weeks

**Comment by jamilbk** [comment]
@AndrewDryga I believe we've addressed most of these in the new 1.0 UI. I'll wrap up these items for the new views before passing off to @bmanifold.
