### ISSUE TITLE
Deploy with traefik - password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by ToxaAdmin** [CloudFire-LLC/cloudfire#1272]
Hello
i run my docker-compose.yaml

version: '3'
 
x-deploy: &default-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  update_config:
    order: start-first
 
networks:
  firezone-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - subnet: 2001:3990:3990::/64
  webproxy:
    name: webproxy
 
services:
  firezone:
    image: firezone/firezone
    ports:
      - 51820:51820/udp
    volumes:
      # IMPORTANT: Persists WireGuard private key and other data. If
      # /var/firezone/private_key exists when Firezone starts, it is
      # used as the WireGuard private. Otherwise, one is generated.
      - ${HOME}/.firezone/firezone:/var/firezone
    environment:
      EXTERNAL_URL: ${EXTERNAL_URL:?err}
      ADMIN_EMAIL: ${ADMIN_EMAIL:?err}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD:?err}
      GUARDIAN_SECRET_KEY: ${GUARDIAN_SECRET_KEY:?err}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?err}
      LIVE_VIEW_SIGNING_SALT: ${LIVE_VIEW_SIGNING_SALT:?err}
      COOKIE_SIGNING_SALT: ${COOKIE_SIGNING_SALT:?err}
      COOKIE_ENCRYPTION_SALT: ${COOKIE_ENCRYPTION_SALT:?err}
      DATABASE_ENCRYPTION_KEY: ${DATABASE_ENCRYPTION_KEY:?err}
 
      # Ensure this includes the traefik service IP.
      EXTERAL_TRUSTED_PROXIES: 172.18.0.7
    networks:
      - firezone-net
      - webproxy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firezone.entrypoints=https"
      - "traefik.http.routers.firezone.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.firezone.tls=true"
      - "traefik.http.routers.firezone.tls.certresolver=letsEncrypt"
      - "traefik.http.services.firezone-service.loadbalancer.server.port=13000"
      - "traefik.docker.network=webproxy"      
  postgres:
    image: postgres:15
    volumes:
      - postgres-data-firezone:/var/lib/postgresql/data
    environment:
      # same value as ## DB section above
      POSTGRES_DB: ${DATABASE_NAME:-firezone}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
    deploy:
      <<: *default-deploy
      update_config:
        order: stop-first
    networks:
      - firezone-net
    labels:
      - "traefik.enable=false"      
# Postgres needs a named volume to prevent perms issues on non-linux platforms
volumes:
  postgres-data-firezone:

my env file

EXTERNAL_URL=mydomain.com
ADMIN_EMAIL=********************
DEFAULT_ADMIN_PASSWORD=********************
GUARDIAN_SECRET_KEY=********************
SECRET_KEY_BASE=********************
LIVE_VIEW_SIGNING_SALT=********************
COOKIE_SIGNING_SALT=********************
COOKIE_ENCRYPTION_SALT=********************
DATABASE_ENCRYPTION_KEY=********************
DATABASE_PASSWORD=********************
DOMAIN=mydomain.com

and i have problem with postgres 
2023-01-08 03:53:01.166 UTC [33] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2023-01-08 03:53:01.173 UTC [34] FATAL:  password authentication failed for user "postgres"

please help me

**Comment by jamilbk** [comment]
Hi @ToxaAdmin -- perhaps the `postgres` user's password got reset or changed somehow.

You should be able to get to a psql prompt with:

```
docker compose -f $HOME/.firezone/docker-compose.yml exec postgres psql -U postgres -h localhost
```

From there you can change the password to match what's set in `$DATABASE_PASSWORD`:

```sql
ALTER ROLE postgres WITH PASSWORD '$DATABASE_PASSWORD';
```

Replacing $DATABASE_PASSWORD with the actual value.

**Comment by ToxaAdmin** [comment]
> ```sql
> ALTER ROLE postgres WITH PASSWORD '$DATABASE_PASSWORD'
> ```

Hi @jamilbk thx for u replay, i do what u recommend and run docker compose restart, and this dont help. I steal have error "password authentication failed for user "postgres""

**Comment by jamilbk** [comment]
Hi @ToxaAdmin -- I'd recommend checking with the [Postgres image docs](https://hub.docker.com/_/postgres) for managing the Postgres docker image. It should provide more troubleshoot help than we're able to provide here.

Closing as a Postgres issue not Firezone issue.
