### ISSUE TITLE
WIREGUARD_ENDPOINT seems removed, now how to set endpoint for VPN?

### ISSUE THREAD

**Issue by shohei-ihaya** [CloudFire-LLC/cloudfire#1296]
Thank you for this great library! It helps me much!

At this commit (https://github.com/firezone/firezone/commit/fbb05b9e7e3b3959c239ba01274def672082530e, https://github.com/firezone/firezone/commit/ec3c075c6715f721f42175c2e71f63699c3707d1), env variable `WIREGUARD_ENDPOINT` was removed.

`WIREGUARD_ENDPOINT` is convenient when you wanna set other value as VPN FQDN instead of `EXTERNAL_URL`.

Then, my question is that how to set other value as VPN FQDN instead of `EXTERNAL_URL` at current codebase?

**Comment by shohei-ihaya** [comment]
I found that I can set the endpoint at `/settings/site` page.

Is it the only way to set VPN FQDN? or can I set VPN FQDN by other ways? ( ex: some kinds of parameter at server start or something)

**Comment by AndrewDryga** [comment]
Hello @Climber22, you can use new REST API to do that programmatically. We do plan to bring back all environment variables but in a much more standardized manner (for pretty much any config), probably it will be part of the next version.

**Comment by AndrewDryga** [comment]
As an idea to simplify it now we can add a release command to return you an API token that can be used in a bash script with curl commands.

**Comment by shohei-ihaya** [comment]
Thank you for quick reply!

> you can use new REST API to do that programmatically. We do plan to bring back all environment variables but in a much more standardized manner (for pretty much any config), probably it will be part of the next version.

Sounds nice! I'm looking forward the new way of configuration!
