### ISSUE TITLE
Add a debug script

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1308]
We need a debug script that will allow us to collect enough information from users to report the issue (related to #1246):
- [ ] Firezone version
- [ ] `docker ps` output
- [ ] `.env` output
- [ ] `docker logs` for every container
- [ ] dump of secure configurations (using either API or from DB)

**Comment by jamilbk** [comment]
- [ ] add erl_crash.dump if exists
- [ ] encrypt with relevant PGP key

**Comment by jamilbk** [comment]
I started working on this but paused due to the data sanitization issue -- would this be printed to the console that is then copy/pasted? So the user would need to remove sensitive data themselves?

Also,

- [ ] Update bug report issue template to run this debug script

**Comment by AndrewDryga** [comment]
Yeah, I think sanitizing should be done manually, we don't want anything critical to accidentally leak if we change log format or logged something unpredictable in a stacktrace/process crash report
