### ISSUE TITLE
CI/PR labeling improvements

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1316]
- [ ] We should apply a labeling schema that will allow marking value, size, etc for PRs manually and instead of using an auto labeler a CI check should simply check for required labels and fail if they are not set.

Labels: 
- size/S-XL (number of line changes; can be auto-labeled);
- priority/important-longterm,important-soon
- value/S-XL (business value of a PR)
- area/panel,gateway,documentation,CI,infrastructure (can be auto-labeled by checking folders for changed files)
- good first issue (for new contributors)
- kind/bug,design,documentation,cleanup,flake,regression,support,feature

- [ ] For UI tests we should render the page diffs between the main and PR branch, highlight changes, and post those somewhere where you can see them as a gallery (eg. a bunch of attachments to GitHub PR comments). [Eg](https://github.com/getsentry/action-visual-snapshot).
- [ ] Move docker build stage to the main workflow (make it dependent on unit and acceptance test), and run a sanity check after containers are built.
- [ ] Add Security Audit step
  - [ ] Sobelov for Elixir
  - [ ] `yarn run improved-yarn-audit` for JS
- [ ] Automatically generate and publish API docs in CI
- [x] Improve the seed script to cover all entities and more complex setups
- [x] Add a CI step to test that seeds are working
  - [x] `main` branch CI should generate and upload SQL dump artifacts from seeds (including migration_schema)
  - [x] PR branches should download the master seeds dump, load it, and then re-apply the rest of the migrations

**Comment by usmailaabdoul** [comment]
Hi @AndrewDryga which subtask can i picked up here?
