### ISSUE TITLE
0.7.2 - SAML Google not working

### ISSUE THREAD

**Issue by Insidek** [CloudFire-LLC/cloudfire#1321]
I have proper configuration in accordance with the documentation. All users gets error 403 with response:
`access_denied {:envelope, {:error, :no_signature}}`

Few days ago, I tested version 6.1.16 and the authentication worked.

**Comment by AndrewDryga** [comment]
@Insidek can be related to #1313? Do you configure SAML providers using ENV variables?

**Comment by Insidek** [comment]
I set up fresh installation and configured SAML in the webgui.

**Comment by jamilbk** [comment]
@Insidek -- thanks for the report. Can you confirm that the `Require signed envelopes` option is switched off in your SAML configuration?

**Comment by Insidek** [comment]
![image](https://user-images.githubusercontent.com/22748563/212972881-5a7ab6dc-4ac4-4c34-9639-22d49efbdc5e.png)
As I mentioned, i have proper configuration in accordance with the documentation.

Additionally, when you add the second SAML in webgui, there is no possibility to remove first or second configuration.

**Comment by jamilbk** [comment]
Thanks for the info. Investigating.

**Comment by jamilbk** [comment]
@Insidek I was able to reproduce the signed assertions error. A fix is coming in 0.7.3. As for this, however:

> Additionally, when you add the second SAML in webgui, there is no possibility to remove first or second configuration.

I wasn't able to reproduce. Could you elaborate a little more on the issue you're seeing and any steps needed to reproduce?
