### ISSUE TITLE
REST API for User

### ISSUE THREAD

**Issue by AYDEV-FR** [CloudFire-LLC/cloudfire#1322]
Hi,

Thanks you for your project ! It's a very nice project !

I would like to create a CLI on top of wireguard so that a user can create and obtain his configuration in a totally transparent way. However it lacks a user-oriented REST API and no administrator configuration REST-API.

For you, do you think it's possible to create a CLI to do that ? Use a JWT Token provided by OIDC (with Keycloak for example) and with this token automaticly create and get configuration of a device for this user ?

I'm not a Elixir Developper but a Rust and Go developper,
if 'I manage to do this, I will share it in open source of course ! If not, do you plan to add this kind of functionality?

Thanks you,
Aydev

**Comment by AndrewDryga** [comment]
Hey @AYDEV-FR, thanks for using Firezone and building with it! :)

We just released REST API, you can find documentation for user management here - https://docs.firezone.dev/reference/rest-api/users/.

**Comment by AYDEV-FR** [comment]
Hi @AndrewDryga,
I saw that there is a REST API, only it only works with an "Admin" API Token. And it's a great job !

The idea for me would be to make a CLI client for the end user, so he can connect and get his device config.

curl -i \
  -X POST "https://{firezone_host}/v0/devices" \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {api_token}' \
  --data-binary @- << EOF

But not a API_TOKEN but a JWT emmit by my IDP (actually Keycloak with OIDC)

Do you have an idea to create a device config for a user ? With his JWT Token.

Thanks you,

**Comment by AndrewDryga** [comment]
@AYDEV-FR for now REST API is only for admin usage, there is no way to access it using JWT tokens. 

To me, it sounds like what you really want is client apps that will abstract the device configuration and we are actively working on them :).

**Comment by AndrewDryga** [comment]
Closing in favor of #1329
