### ISSUE TITLE
Problem activate MFA

### ISSUE THREAD

**Issue by prohand** [CloudFire-LLC/cloudfire#1323]
Hello,

I have a problem with activate MFA and login again in admin portal

For exemple I use the MFA ton login in the admin interface and i have this page after type my password : 
![image](https://user-images.githubusercontent.com/20227162/212719926-a92e0f0f-3ecd-4303-8036-548ae4a00f0e.png)

I Use Europe/Paris in my physical machine and test with UTC and same problem.

And the log : 

```
firezone-firezone-1  |     ** (FunctionClauseError) no function clause matching in DateTime.compare/2
firezone-firezone-1  |         (elixir 1.14.2) lib/calendar/datetime.ex:1362: DateTime.compare(~U[2023-01-16 15:54:54.321799Z], nil)
firezone-firezone-1  |         (fz_http 0.7.2) lib/fz_http_web/live/hooks/live_mfa.ex:13: FzHttpWeb.LiveMFA.on_mount/4
firezone-firezone-1  |         (phoenix_live_view 0.18.6) lib/phoenix_live_view/lifecycle.ex:148: anonymous fn/4 in Phoenix.LiveView.Lifecycle.mount/3
firezone-firezone-1  |         (phoenix_live_view 0.18.6) lib/phoenix_live_view/lifecycle.ex:183: Phoenix.LiveView.Lifecycle.reduce_socket/3
firezone-firezone-1  |         (phoenix_live_view 0.18.6) lib/phoenix_live_view/utils.ex:333: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
firezone-firezone-1  |         (telemetry 1.2.0) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
firezone-firezone-1  |         (phoenix_live_view 0.18.6) lib/phoenix_live_view/static.ex:269: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
firezone-firezone-1  |         (phoenix_live_view 0.18.6) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3

```

Disable the MFA resolved this issue

Is a docker installation.

Can you help me please ?

**Comment by AndrewDryga** [comment]
Hello @prohand, it looks like you hit a bug. Can you please describe how you set up the MFA method so I can have ways to reproduce it? Was it done in the UI, or did you add a record to the database table? Were there any errors during the process?

**Comment by prohand** [comment]
Hello,

I setup the MFA with UI.

I take a screenshot : 

![image](https://user-images.githubusercontent.com/20227162/212755051-7d1b2097-b00f-4aa1-9e48-94e190001356.png)
![image](https://user-images.githubusercontent.com/20227162/212755073-970d0112-dab4-40b8-8c00-08fdd611a3f5.png)
![image](https://user-images.githubusercontent.com/20227162/212755369-164a7653-2ead-462d-afda-834defa19624.png)

I confirm with 6 digits OTP
I logout and login

This is very strange, because while I have just redone the manipulation to reproduce the bug, I no longer have the problem ;).

Could the problem be random?

Thank you

**Comment by AndrewDryga** [comment]
I will add a database constraint to make sure it will never happen again without showing an error. 

It looks like there were some issues with LiveView state and it would be extremely hard to reproduce why, so let's close it for now and see if anyone else will run into the same problem.

**Comment by prohand** [comment]
Hello,

I reproduce this problem and at the stage where he asks us to validate the OTP, I have to enter it twice for it to be taken into account.
Then when trying to connect I get the message "internal server error"

**Comment by AndrewDryga** [comment]
Thank you for clarifying this, I'm working on a fix

**Comment by prohand** [comment]
Ok thank you ;)
