### ISSUE TITLE
[epic] Client Apps

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1329]
We are actively developing client apps for all major platforms, this is an issue to track progress and related feature requests.

- [x] #1763 
- [x] #1767 
- [x] #1768 
- [x] #1762

**Comment by MohammedNoureldin** [comment]
Hi, is there any progress here or expected release time? Mainly to achieve this:

> This flow will be enabled by our custom clients, currently under development. With those, users won't have to worry about WireGuard configurations -- they'll simply log into the IdP and be connected, like you'd expect from any other business VPN.

**Comment by mortenbirkelund** [comment]
Agree. An estimated/planned release date, would be very nice.

**Comment by AndrewDryga** [comment]
Hey guys, we can't give any estimates. At the moment we are working on them but as a business, we need to pivot Firezone to start generating revenue and that will be our top priority for a while, so we can shift our priorities back and forth rapidly.

**Comment by jamilbk** [comment]
Coming Q4
