### ISSUE TITLE
0.7.3 - Next problem with SAML auth (Google)

### ISSUE THREAD

**Issue by Insidek** [CloudFire-LLC/cloudfire#1341]
All users gets error 403 with response:

`invalid_request unknown IdP`

**Comment by jamilbk** [comment]
Thanks for the report @ihard -- working to reproduce.

**Comment by jamilbk** [comment]
Hi @Insidek -- this should be fixed in 0.7.4, along with a few other SAML fixes. I've tested it's working with Google Workspace. Give it a go and let us know if you hit any snags.
