### ISSUE TITLE
Persistent outbound mailer configuration and expose via REST API

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1343]
Outbound email configuration should belong in the `configurations` like other runtime configuration.

Refs #1162

**Comment by jamilbk** [comment]
Also consider adding more supported email fields, such as:

https://hexdocs.pm/swoosh/Swoosh.Email.html#module-email-fields

**Comment by AndrewDryga** [comment]
New ENV vars:
```
OUTBOUND_EMAIL_PROVIDER_ADAPTER="Swoosh.Adapters.SMTP"
OUTBOUND_EMAIL_PROVIDER_ADAPTER_OPTS="{...}"
```

**Comment by jamilbk** [comment]
Closing as irrelevant for now.
