### ISSUE TITLE
Allow creation of local users by list email domain

### ISSUE THREAD

**Issue by ihard** [CloudFire-LLC/cloudfire#1347]
Purpose: to enable users to create their own accounts from the allowed list of email domains. 
Example: an administrator sets the organization's mail domain and simply links to the web interface. 
Users request a magic login link if the mail domain is in the allowed list, this removes the need for the administrator to create accounts for everyone manually or by script. 
Not everyone has the opportunity to use SSO.

**Comment by jamilbk** [comment]
Hmmm, this feels like a feature that belongs in an IdP. Would you be able to use Keycloak, Vault, or Authentik with an OIDC connector and configure this behavior through one of those? They're open-source and self-hosted as well, and provide other authentication features like MFA as well.

**Comment by jamilbk** [comment]
Refs #1157

**Comment by ihard** [comment]
Posting an idp on the Internet is not always possible due to security requirements. We have keycloak, but it is only available on the internal network.

**Comment by AndrewDryga** [comment]
@ihard if the internet is not available, how the users will be able to log in using the link in the email? If your Firezone instance public or it's also on the internal network?

I have two edge cases in mind:
1. Users might not be able to open the email with a magic link
2. The link from the email will lead to the internal, protected resources so it will never reach Firezone

**Comment by ihard** [comment]
Users have internet access and can open the link.  
I can unload all users with a script and create accounts for them in Firezone so that they can request a link to them, but this seems excessive because not everyone needs vpn access.  
I would like to simply limit the ability to request a link by some domain + auto-create a user when successfully clicking on a link from an email.

**Comment by jamilbk** [comment]
We won't be able to implement this for the 0.7 release, and the 1.0 release will include directory sync from your IdP to bring users (and groups) in, along with magic link sign in method which you can add users to manually.
