### ISSUE TITLE
Firezone GUI does not react to close the key generation window

### ISSUE THREAD

**Issue by kinseii** [CloudFire-LLC/cloudfire#1353]
OS: Windows 10
Browser: Google Chrome Version 109.0.5414.75 (Official Build) (64-bit) - Latest
Firezone: 0.7.4 dockerized

There is a little bug - after the generation of the WireGuard key in the GUI Firezone, the generation window does not close. GUI does not react to close the window.

**Comment by jamilbk** [comment]
Thanks for the report @kinseii.

* Does the modal close if you press the escape key or click outside the modal?
* Could you share any browser console logs that appear at the time of click that may be relevant?

That'll help debug the issue. We do have this covered in tests (#1356) that helps ensure the modal is dismissed, but there could be another issue with your browser or session.

**Comment by kinseii** [comment]
I updated to version 0.7.5 today and the problem is gone

**Comment by kinseii** [comment]
Perhaps you can close Isuue

**Comment by kinseii** [comment]
@jamilbk 
Please reopen the Issue. I have a clarification - when you open the `Add Device` window, you can close it with a cross or with the `Esc` key. But when you press `Download WireGuard configuration` the window stops closing, you have to close the browser tab.

**Comment by jamilbk** [comment]
Thanks for the clarification.

**Comment by jamilbk** [comment]
If you could post relevant browser console logs and firezone container logs at the time of occurrence that would help us diagnose the issue.

**Comment by kinseii** [comment]
I opened the browser console, but it's blank. I tried reloading the page, but it also stayed blank.

![image](https://user-images.githubusercontent.com/74458264/213884635-d44a706c-68bb-45c2-a902-c1f5d98f2d0c.png)

Nothing appears in the server logs when you click on the cross, there are only login logs
```
data-firezone-1  | 19:45:41.493 request_id=FzxqkxlnnnMccFgAAAyS [info] GET /
data-firezone-1  | 19:45:41.495 request_id=FzxqkxlnnnMccFgAAAyS remote_ip=20.25.hidd.en [info] Sent 302 in 2ms
data-firezone-1  | 19:45:41.597 request_id=Fzxqkx-WXdqAI08AAAyi [info] GET /user_devices
data-firezone-1  | 19:45:41.604 request_id=Fzxqkx-WXdqAI08AAAyi remote_ip=20.25.hidd.en [info] Sent 200 in 6ms
data-firezone-1  | 19:45:42.186 [info] CONNECTED TO Phoenix.LiveView.Socket in 48µs
data-firezone-1  |   Transport: :websocket
data-firezone-1  |   Serializer: Phoenix.Socket.V2.JSONSerializer
data-firezone-1  |   Parameters: %{"_csrf_token" => "GGUBI1wvFR9jGDE********************************ReV", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "https://vpn-users-hidd.en/dist/unprivileged-f5863ffa9667a9***********************.css?vsn=d", "1" => "https://vpn-users.hidd.en/dist/unprivileged-407b7514465bcf******************b.js?vsn=d"}, "vsn" => "2.0.0"}
data-firezone-1  | 19:45:42.472 [info] CONNECTED TO FzHttpWeb.UserSocket in 169µs
data-firezone-1  |   Transport: :websocket
data-firezone-1  |   Serializer: Phoenix.Socket.V2.JSONSerializer
data-firezone-1  |   Parameters: %{"token" => "SFMyNTY.g2gDbQAA***********i1lYjdhLTQyZj*********************************NuEjH8K7_VsxfUdMqj32y3ehaI6_eTiw", "vsn" => "2.0.0"}
data-firezone-1  | 19:45:42.571 [info] JOINED notification:session in 757µs
data-firezone-1  |   Parameters: %{"token" => "SFMyNTY.g2gDbQ**********1lYjdhLT************************3VhQFiAAFRgA.Y2qHNZZ-9iDvglxWIeGJl7MTpbunXBMCe422cf-4cOE"}
```

**Comment by kinseii** [comment]
@jamilbk 
Please give me the instructions and I will make the necessary report. Thank you!

**Comment by jamilbk** [comment]
Hi @kinseii -- sorry but I'm having trouble reproducing. Tested with Firefox and Chrome on macOS. Is it possible you have a browser extension loaded that's conflicting somehow?

https://user-images.githubusercontent.com/167144/214430443-585a56e8-3f7d-45b8-b9e7-75eccdbe276c.mov

**Comment by kinseii** [comment]
@jamilbk Hi, have you clicked on `Download WireGuard configuration`?

**Comment by kinseii** [comment]
https://user-images.githubusercontent.com/74458264/214949782-e85fce64-6e5a-4ece-95d1-dad6f0c7af6f.mov

**Comment by kinseii** [comment]
None of the plugins are enabled.

**Comment by jamilbk** [comment]
Thanks! I was able to reproduce.
