### ISSUE TITLE
Migration to Docker moves some settings but creates docker-compose ignoring settings.

### ISSUE THREAD

**Issue by jbtule** [CloudFire-LLC/cloudfire#1365]
So I tried to migrate to docker from omnibus.

- `default['firezone']['wireguard']['port']` migrates to -> `WIREGUARD_PORT` but the yml still has  `51820:51820/udp`
- `default['firezone']['nginx']['enabled'] = false` is ignored and caddy reverse proxy is created in yml, and blows up if you have something else running on port `443`
- `default['firezone']['phoenix']['port']` is not migrated to ->PHOENIX_PORT, which is a good default except when default['firezone']['nginx']['enabled'] = false. 

All the above were easily fixable modifying the yml after the fact however the last issue, I have no idea on:

- `default['firezone']['wireguard']['ipv4']['masquerade'] = false` migrates to ->  `WIREGUARD_IPV4_MASQUERADE="false"`, but does not work with the `docker-compose.yml` created.  Traffic doesn't route unless I change to `WIREGUARD_IPV4_MASQUERADE="true"`, however then everything masked behind one ip address is broken with our lan monitoring and segmentation.

So with that last part, I was forced to abort the migration.

**Comment by AndrewDryga** [comment]
Hey @jbtule, can you please also share which Firezone version you were on and which version you attempted to migrate to?

**Comment by jbtule** [comment]
Before attempting migrating, I updated to latest without issue. so Omnibus 0.7.5 -> Docker 0.7.5

**Comment by AndrewDryga** [comment]
@jbtule it looks like the masquerade issue is due to docker using an internal network, but there is a workaround - https://github.com/Place1/wg-access-server/issues/26. Please let me know if that helps and I'll add it to our documentation to prevent other people from running into this.

**Comment by sudousercom** [comment]
Hi! just one more thing, after migration from latest omnibus to latest docker i have env settings 
SAML_CERTFILE_PATH="/var/opt/firezone/ssl/saml.crt"
SAML_KEYFILE_PATH="/var/opt/firezone/ssl/saml.key"
but it is files from my local filesystem, files does not exist in docker container with firezone, and it in crashloop

and same problem with caddle and port 443 as mentioned in topic start

**Comment by jamilbk** [comment]
@sudousercom The SAML keyfiles should be located in ~/.firezone/firezone and mounted from the `docker-compose.yml`.

Going to close this -- feel free if the original issue remains @jbtule

**Comment by sudousercom** [comment]
> @sudousercom The SAML keyfiles should be located in ~/.firezone/firezone and mounted from the `docker-compose.yml`.
> 
> Going to close this -- feel free if the original issue remains @jbtule

i dont care about saml, but caddle port is critical for migration, i am using nginx on my host, and need just run firezone on another ports, not on 80 or 443, is it was fixed too?
