### ISSUE TITLE
HTTP_CLIENT_SSL_OPTS not work after 0.7.3

### ISSUE THREAD

**Issue by AYDEV-FR** [CloudFire-LLC/cloudfire#1368]
Hi,

I have try to set HTTP_CLIENT_SSL_OPTS
```
HTTP_CLIENT_SSL_OPTS='{"verify": "verify_peer", "cacertfile": "/etc/ssl/ca.crt"}'
```

Breaking change between 0.7.2 and higher 0.7.3

Thank you

**Comment by AndrewDryga** [comment]
Hey @AYDEV-FR, can you please add more details about the issue? Do you see any errors? Doesn't HTTP client pick up the config?

**Comment by AYDEV-FR** [comment]
I obtain this error with all version >= 0.7.3
```
is invalid. Reason: %Mint.TransportError{reason: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:2098 generated CLIENT ALERT: Fatal - Unknown CA\n'}}}
```

And I don't have any error with version >= 0.7.0 and <= 0.7.2, and I don't change this envrionment variable on each test
```
HTTP_CLIENT_SSL_OPTS='{"verify": "verify_peer", "cacertfile": "/etc/ssl/ca.crt"}'
```

And in console i have 
```
firezone_1  | 09:39:24.453 [notice] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:2098 generated CLIENT ALERT: Fatal - Unknown CA
```

**Comment by jamilbk** [comment]
Thanks for the info! Taking a look.

**Comment by AndrewDryga** [comment]
@jamilbk I'm already writing tests for this fix :)
