### ISSUE TITLE
Rework http clients to support http proxies

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1373]
Firezone http clients should read the standard `HTTP_PROXY` and/or `HTTPS_PROXY` vars to proxy outbound http requests for OIDC and Connectivity Checks.

https://firezone-users.slack.com/archives/C02PV412LGZ/p1674481099859029

### Todo
- [ ] Posthog
- [ ] ConnectivityChecks
- [x] OpenID Connect

**Comment by furstblumier** [comment]
Are there any updates towards this issue? It looks like the OIDC connect lib is still not using the https_proxy/http_proxy env vars inside the container.

**Comment by jamilbk** [comment]
We probably won't be able to get to this in the 0.7 release, and 1.0 will have a cloud-managed portal which will make this irrelevant for the majority of users.
