### ISSUE TITLE
Webhook Notification 

### ISSUE THREAD

**Issue by aaron791109** [CloudFire-LLC/cloudfire#1388]
Is there any log when user login of this version?
Or can we add some webhook method (like Slack) to notice us when someone login via our vpn?

**Comment by AndrewDryga** [comment]
There is no such feature at the moment, we do plan to add access logs in future version but that would be an enterprise feature.

As a workaround you might try to see if there is a similar feature in your OIDC/SAML provider or setup a log collector from Docker (eg ELK stack or Google Cloud Logger) and configure alerts for logs entries related to auth routes.
