### ISSUE TITLE
Integrate LoggerJSON

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1389]
We should restructure our logs and instead of just writing binary messages write provider-specific JSON logs with rich metadata (eg. when the user logged in we can add user_id to metadata for all log records). A lib that should be used: https://github.com/nebo15/logger_json (supports GCL, DataDog, ELK, and pretty much anything else).

- [ ] Configure JSON logger back-end for production
- [ ] Integrate Ecto logs
- [ ] Integrate LoggerJSON.Plug
- [ ] Provide an ENV configuration to set the logger adapter (GCL, DataDog, Generic)
- [ ] Make sure all error messages are clear to end-users and provide guidance to resolve or report the issue
- [ ] Make sure every place where Logger called has relevant metadata
- [ ] Propagate process dictionary for spawned processes to preserve relevant metadata

**Comment by usmailaabdoul** [comment]
@AndrewDryga is this issue available to be picked up? 
Also do we add the logger across the application or we have specific areas where we want the information to be logged.

**Comment by AndrewDryga** [comment]
Hey @usmailaabdoul, thank you for your interest in this! I added a TODO list to the issue so that it's clear what needs to be done, some parts of it can be done now (like raw integration, but that is more about writing good error messages than writing some code), but configuration piece should wait for #1352.

**Comment by usmailaabdoul** [comment]
ok @AndrewDryga the todo list is helpful, thanks.

**Comment by usmailaabdoul** [comment]
Hi @AndrewDryga please could you provide some more context as regards the last point you mention on the issue, 
``Propagate process dictionary for spawned processes to preserve relevant metadata``

**Comment by AndrewDryga** [comment]
Sure @usmailaabdoul,

When we spawn a process or send a process message and downstream process logs anything it won't have access to the parent metadata, in order to preserve it we want to do something like:
```elixir
parent_metadata = Logger.metadata()
```
and then in the child process
```elixir
Logger.metadata(parent_metadata)
```

This will copy all metadata, like `request_id` to the child processes allowing to group/trace logs.

**Comment by usmailaabdoul** [comment]
alright this makes sense @AndrewDryga

**Comment by jamilbk** [comment]
All 1.0 components will support JSON logging
