### ISSUE TITLE
No field has function

### ISSUE THREAD

**Issue by Beast-Panik** [CloudFire-LLC/cloudfire#1390]
No matter if I want to create a new user or define IP rule no confirmation fields work. Neither the save nor the close function works. So it is unusable in the current version. I use v 0.7.8 with Docker on Debian 11.

**Comment by AndrewDryga** [comment]
Can you please give more details on this issue? What exactly doesn't work? Do you use docker-compose or just pulled a container?

Having screenshot, containers logs, and browser console logs would help a lot to understand what is going on.

**Comment by Beast-Panik** [comment]
I think I found the error, it seemed to be the NGINX proxy running between the browser and Firezone. 
I just tried to log in via the FQDN and only got the message Forbidden. I then tried to reset the password but also got the message Forbidden. When I tried to log in via the LAN IP it worked, but when I tried to reproduce the error, it didn't show up anymore. 
Strangely enough I was able to log in via the FQDN but the error appeared that I could not press any confirmation buttons. 
So there seems to be problems when there is a HTTP/HTTPS proxy between the internet and Firezone.

> 16:54:20.193 [warning] Client IP couldn't be determined! Check to ensure your reverse proxy is properly sending the X-Forwarded-For header. Read more in our reverse proxy docs: https://docs.firezone.dev/deploy/reverse-proxies?utm_source=code 
> 16:54:20.193 [warning] [peer_data: %{address: {172, 25, 0, 1}, port: 33492, ssl_cert: nil}, uri: %URI{scheme: "http", authority: "192.168.0.112", userinfo: nil, host: "192.168.0.112", port: 80, path: "/socket/websocket", query: "token=SFMyNTY.g2gDbQAAACRlMzg5NGRiYy01MTZkLTRiMjMtODJhNi02NTAxNDJkODQxM2VuBgB4Ik35hQFiAAFRgA.FEadYPCyStK6UsyGhEizNCqA3nq_azVOwn5PUKMOhf8&vsn=2.0.0", fragment: nil}, user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0", x_headers: [{"x-forwarded-for", "10.0.0.254"}, {"x-forwarded-host", "192.168.0.112"}, {"x-forwarded-proto", "https"}]]
> 16:54:20.193 [info] CONNECTED TO FzHttpWeb.UserSocket in 637µs
>   Transport: :websocket
>   Serializer: Phoenix.Socket.V2.JSONSerializer
>   Parameters: %{"token" => "SFMyNTY.g2gDbQAAACRlMzg5NGRiYy01MTZkLTRiMjMtODJhNi02NTAxNDJkODQxM2VuBgB4Ik35hQFiAAFRgA.FEadYPCyStK6UsyGhEizNCqA3nq_azVOwn5PUKMOhf8", "vsn" => "2.0.0"}
> 16:54:20.203 [info] JOINED notification:session in 1ms
>   Parameters: %{"token" => "SFMyNTY.g2gDbQAAACRlMzg5NGRiYy01MTZkLTRiMjMtODJhNi02NTAxNDJkODQxM2VuBgB5Ik35hQFiAAFRgA.3d-qjggBrf0lGN7gWbMgiGOsI23b230nV-dNNr2Dq8w"}
> 16:54:29.527 request_id=Fz6HS3GhfjR_uFAAAAch [info] GET /auth/reset_password
> 16:54:29.529 request_id=Fz6HS3GhfjR_uFAAAAch remote_ip=172.25.0.1 [info] Sent 200 in 1ms
> 16:54:37.529 request_id=Fz6HTU6YWo-XmWsAAAdB [info] POST /auth/magic_link
> 16:54:37.570 request_id=Fz6HTU6YWo-XmWsAAAdB remote_ip=172.25.0.1 [info] Sent 403 in 41ms
> 16:54:40.635 request_id=Fz6HTge4V5FiGBUAAAdh [info] POST /auth/magic_link
> 16:54:40.635 request_id=Fz6HTge4V5FiGBUAAAdh remote_ip=172.25.0.1 [info] Sent 403 in 549µs

Possibly the error is written as a note in the first line. I will read this and try to implement...

**Comment by AndrewDryga** [comment]
@Beast-Panik indeed an nginx should be configured to support websockets and set X-Forwarded-For/X-Forwarded-Proto headers, you can find more info at Firezone doc: https://docs.firezone.dev/deploy/advanced/reverse-proxy/.
