### ISSUE TITLE
column u0.sign_in_token does not exist

### ISSUE THREAD

**Issue by shohei-ihaya** [CloudFire-LLC/cloudfire#1393]
Thanks for this great library!

When I updated firezone to latest ( 0.7.8 ), I've got the errors shown below.

I found that the colum [sign_in_token is recently dropped](https://github.com/firezone/firezone/blob/218ad006af33cd4b532df2ca44ecdd71c83648c9/apps/fz_http/priv/repo/migrations/20230104000803_add_users_sign_in_token_hash.exs)

In my environment, there are users signed in by OIDC process. ( signed up with previous version firezone )

Do you have any idea to solve this?

```
10:51:35.385 [error] GenServer #PID<0.475.0> terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) column u0.sign_in_token does not exist

    query: SELECT u0."id", u0."role", u0."email", u0."last_signed_in_at", u0."last_signed_in_method", u0."password_hash", u0."sign_in_token", u0."sign_in_token_created_at", u0."disabled_at", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."disabled_at" IS NULL)
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (fz_http 0.7.2) lib/fz_http/oidc/refresh_manager.ex:41: FzHttp.OIDC.RefreshManager.spawn_refresher/0
    (fz_http 0.7.2) lib/fz_http/oidc/refresh_manager.ex:24: FzHttp.OIDC.RefreshManager.handle_continue/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:865: :gen_server.loop/7
Last message: {:continue, :schedule}
```

When I start firezone:latest for empty database, it works well.

**Comment by jamilbk** [comment]
Hi @shohei-ihaya — from the log output it looks like your firezone image is still at 0.7.2. Could you double-check you’re running 0.7.8?

**Comment by shohei-ihaya** [comment]
@jamilbk 

Oh.... I'm so sorry .... 

You are right!

I specify firezone:latest image, but due to local image cache, old version is continuously used ...


Thanks a lot!
