### ISSUE TITLE
Remove CockroachDB from list of supported databases

### ISSUE THREAD

**Issue by benfuu** [CloudFire-LLC/cloudfire#1394]
According to https://github.com/cockroachdb/cockroach/issues/33441#issuecomment-899316950 there should be the ability to support CockroachDB by disabling the migration lock. However, it's not currently possible to configure that parameter in the Ecto configuration. Could we add an env variable to support that?

**Comment by AndrewDryga** [comment]
@bennycooly what is the use case to run Firezone with CockroachDB? Even though it should be mostly compatible with PostgreSQL, there is no guarantee that Firezone will work with it in the future. There are no plans to support other databases at the moment so it won't be tested - we might install PG plugins or do some very specific queries that will break your instance.

So if you really want to use CockroachDB you can fork the repo, manually edit the migrations or config.exs, and build your own containers (you can look at CI workflows to learn how). 

But be aware: enabling this flag can be more work than it sounds, as we did not write migrations expecting them to run outside of a transaction, some may leave your instance in an invalid state if the migration will complete only partially and then fail on some data-specific edge-case.

**Comment by benfuu** [comment]
I have no issue using Postgres, but I already have some Cockroach instances running and was reading through the external database [docs](https://docs.firezone.dev/deploy/advanced/external-database/#compatibility) and thought that it implied CockroachDB was "generally" supported. It'd probably be good to remove that from the documentation?

**Comment by AndrewDryga** [comment]
@jamilbk should we remove it from docs or add a CI pipeline to test Firezone with different DBs?

**Comment by jamilbk** [comment]
Hmm, while we could expose this via an env var now, I fear it’ll be a slippery slope that may cause issues further down the line if we need to rely on locking or some other PG feature Cockroach isn’t compatible with.

We probably won’t have bandwidth to support Cockroach in general going forward, so agree it should be removed from docs.

Thanks for the report @bennycooly

**Comment by AndrewDryga** [comment]
@jamilbk it would not work already, we are using advisory locks to check out IP from a range and it is not supported: https://github.com/kyleconroy/sqlc/issues/1726#issuecomment-1179658092.
