### ISSUE TITLE
Firezone MFA add column to list users and force users to create mfa

### ISSUE THREAD

**Issue by rchekhina** [CloudFire-LLC/cloudfire#1401]
HI,

is it possible to add a column MFA activated on the users list ? and force the users to create their MFA ?

Best regards.

**Comment by kirmorozov** [comment]
It might be reasonable to marry with KeyCloak for all possible auth methods

**Comment by jamilbk** [comment]
Indeed, we recommend using the IdP for MFA whenever possible.
