### ISSUE TITLE
Create MFA error Something went wrong. Try saving again or stating over

### ISSUE THREAD

**Issue by rchekhina** [CloudFire-LLC/cloudfire#1402]
HI,

I have found an issue with the mfa creation. If a user create a MFA with the default Name "My authenticator" and other user create his mfa with the same name "My authenticator" when he saves it, the error message "Something went wrong. Try saving again or stating over" appear.

Best regards.

**Comment by AndrewDryga** [comment]
Good catch, I will push a fix today
