### ISSUE TITLE
few ideas for development

### ISSUE THREAD

**Issue by ramazankzn** [CloudFire-LLC/cloudfire#1410]
Hello!
You are doing a very cool and useful project.
I have a few ideas for development:
1. Add traffic reset buttons to the device page.
2. Add an option to limit traffic.
3. Add an option to see who is currently using the width of the Internet channel.

**Comment by jamilbk** [comment]
Hi there @ramazankzn -- thanks for the report. (1) is reported from the WireGuard stats, so it'd be better to reset them there. (2) is not planned any time soon, but you could work around with an iptables or `tc`-based filter -- see #326

**Comment by dillfrescott** [comment]
Would love to see this added
