### ISSUE TITLE
Excessive Wan connectivity check, resulting in high cpu usage

### ISSUE THREAD

**Issue by dkgof** [CloudFire-LLC/cloudfire#1414]
I discovered that my firezone instance, was using 1 full core of CPU with the process "beam.smp".

It looks like it has something to do with "Wan Connectivity Check", because according to my pihole, for the last 5hours or so, my firezone has requested a ping to ping.firez.one about 5 times / second.

I can also confirm that from inside firezone, it has quite a lot of connectivity checks for the same minute:

https://imgur.com/a/iOK6RvS

As can be seen on the screenshot, i am running firezone 0.7.12, i am not entirely sure when this started, but i have restarted my firezone docker instance a couple of times in the last week, because it started using so much cpu, and then i investigated it this morning, since it was back.

Please let me know if any additional information is needed.

/Rolf

**Comment by jamilbk** [comment]
Thanks for the report! A fix is coming in 0.7.13.

**Comment by jamilbk** [comment]
0.7.13 is out -- please upgrade :-).
