### ISSUE TITLE
`bin/create-or-reset-admin` fails silently when password doesn't meet requirements

### ISSUE THREAD

**Issue by Insidek** [CloudFire-LLC/cloudfire#1415]
I can't create admin, the below command not working:
`docker compose run --rm firezone bin/create-or-reset-admin`

I have created proper .env file with
ADMIN_EMAIL
DEFAULT_ADMIN_PASSWORD
also tried 
RESET_ADMIN_ON_BOOT=true

and not working too.

Table users in db is empty:
![image](https://user-images.githubusercontent.com/22748563/217497468-e01a72a3-27ae-44dd-a73d-f3e48ff06aac.png)

**Comment by jamilbk** [comment]
Hi @Insidek thanks for the report! Could you share the following to help debug:

- Log output when you run `docker compose up firezone` with `RESET_ADMIN_ON_BOOT=true`?
- Show output of the command with the `-t` switch: `docker compose run -t --rm firezone bin/create-or-reset-admin`
- Log output of `postgres` service when the command is run

**Comment by Insidek** [comment]
> Hi @Insidek thanks for the report! Could you share the following to help debug:
> 
> * Log output when you run `docker compose up firezone` with `RESET_ADMIN_ON_BOOT=true`?

Ok, my password has only 10 chars, should be 12 or more. This method works and inform about requirements for password. I didn't see this before...

> * Show output of the command with the `-t` switch: `docker compose run -t --rm firezone bin/create-or-reset-admin`

The method not inform about too less password, show always::
[info] Password for user specified by ADMIN_EMAIL reset to DEFAULT_ADMIN_PASSWORD!


Finally create-or-reset-admin works but you should consider adding information about password that does not meet the requirements.

**Comment by jamilbk** [comment]
Thanks for the debugging help! I'll update the issue title to reflect the changes needed here.

**Comment by Insidek** [comment]
Only `docker compose run --rm firezone bin/create-or-reset-admin` fail sailently when password doesn't meet requirements.
