### ISSUE TITLE
Wireguard peer configuration disappears

### ISSUE THREAD

**Issue by yefimg** [CloudFire-LLC/cloudfire#1425]
**Describe the bug**
We are seeing an issue on several Firezone installations: after some time passes, wireguard peer configurations dissappear from firezone container leading to VPN server not being available for end users.

**To Reproduce**
1. Create a Firezone installation with docker-compose manually
2. Using Firezone API enable OIDC auth and disable local auth
3. Login successfully, create several device configs
4. VPN works fine
5. Wait (time unknown)
6. VPN stops working. Install wireguard-tools in Firezone container that proves, that only server config is activated.

**Expected behavior**
Peer configuration in wireguard should not dissappear and be restart-proof as well

**Screenshots / Logs**
```bash
docker exec -ti firezone-firezone-1 /bin/sh
# apk add wireguard-tools
# wg
interface: wg-firezone
  public key: 5ND1dQ0BS1m9Q9sAUOpfMzSJq+OaEVk7RpffDRjMlxI=
  private key: (hidden)
  listening port: 51820
```

**Platform (please complete the following information):**
 - Firezone Version 0.7.13
 - OS: Tested on Flatcar Linux 5.15.86-flatcar and Debian 11 5.10.0-9-cloud-amd64
 - Distro: Flatcar Linux or Debian Linux
 - Kernel version: 5.15.86 or 5.10.0-9
 - Deployment method: Docker

**Additional context**
We did not see that problem when we first started testing Firezone back with version 0.6 and Omnibus installation.

**Comment by jamilbk** [comment]
Hi @yefimg -- could you verify the `Require auth for VPN session` is set to `Never` as shown below?

<img width="712" alt="Screenshot 2023-02-13 at 12 05 19 PM" src="https://user-images.githubusercontent.com/167144/218759222-e10725bd-337e-4f13-bc82-1fa8c536fd29.png">

When the auth expires, Firezone removes the user's associated peers from the WireGuard interface.

**Comment by yefimg** [comment]
@jamilbk, thanks a lot, it in fact was the case!
