### ISSUE TITLE
Editing devices

### ISSUE THREAD

**Issue by lgpasquale** [CloudFire-LLC/cloudfire#1428]
There is no way (that I can find) to edit device settings once the device has been created (firezone 0.7.11)

I would expect either an "edit" button somewhere on the device page (which would open the same kind of dialog you get when creating the device), or to be able to edit fields directly from the device page.

Neither the admin nor the user seem to to be able to edit devices.

**Comment by AndrewDryga** [comment]
@lgpasquale can you please tell me what is the use case, which fields do you want to edit? It's not editable because after the user downloaded the config there is no way how he will get an update if you edit something, so there is almost nothing you can change there in practice.

**Comment by lgpasquale** [comment]
I was thinking of a scenario where I, as an admin, want to "push" configuration changes and ask users to simply download the new configurations.
But I guess I can just edit the default values and ask users to recreate their devices.
