### ISSUE TITLE
oidc callback uri

### ISSUE THREAD

**Issue by marafa-sugarcrm** [CloudFire-LLC/cloudfire#1432]
**Describe the bug**
documentation is missing where to get the callback uri for 

**To Reproduce**
- in the web ui go to security
- click on the open id connect providers configuration (may need to set one up first)
- click edit
- go down to the bottom to "redirect uri" - it provided as an example, which means i cannot be copied

**Expected behavior**
- clear instructions in documentation on how to find the redirect uri
- the redirect uri can be copied

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12]0.713
 - OS: [e.g. Linux] linux
 - Distro: [e.g. Ubuntu 18.04]
 - Kernel version: [e.g. 5.10.11]
 - Deployment method: [e.g. Docker / Omnibus / Source] docker

**Additional context**

**Comment by AndrewDryga** [comment]
Should be fixed in #1352
