### ISSUE TITLE
activate / deactivate an sso provider

### ISSUE THREAD

**Issue by cuatrix-bensonlee** [CloudFire-LLC/cloudfire#1436]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the current version, one can configure multiple SSO options (e.g., OIDC, SAML, etc).  However, once an option is entered, it is good as active.  The request is to include an option to activate / deactivate an SSO option so that if it is not yet stable, then it can be temporarily disabled.  This way, not all the settings of the SSO option will be lost.

There might also be situations where an identity provider is experiencing issues and users needs to be temporarily switched over to another option.

**Describe alternatives you've considered**
Remove the SSO option that needs to be temporarily disabled.  Re-enter the details once ready to be reactivated.

**Additional context**
None.

**Comment by jamilbk** [comment]
Thanks for the feature request Benson! Makes sense.

**Comment by jamilbk** [comment]
So this is actually how Identity Providers have been built in 1.0. cc @AndrewDryga. Will keep this open until that's confirmed.

**Comment by AndrewDryga** [comment]
This is already implemented in 1.0.
