### ISSUE TITLE
Provider-agnostic user/group sync (SCIM)

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1437]
## Todo
- User/group provisioning methods
  - Custom 
    - [x] Google Workspace
  - SCIM 2.0 
    - [ ] Integrate WorkOS
  - JIT (User)
    - [x] Generic OIDC
    - [ ] Generic SAML
  - JIT (Group)
    - [ ] Generic OIDC
    - [ ] Generic SAML

There are two places where the authentication provider is used:

- Portal sessions: Authenticating admins to the admin dashboard
- Client sessions: Authenticating end-users and admins to Firezone client apps for remote access

## Prior discussion
refs firezone/product#460 
refs firezone/product#457 

## SCIM support by popular providers

| Provider | SCIM support | Auth method | Sync method |
| --- | --- | --- | --- |
| Google | SAML-only, but only for [apps in the directory](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F7681608%3Fhl%3Den&assistant_id=generic-unu&product_context=7681608&product_name=UnuFlow&trigger_context=a). | OIDC or SAML | Custom |
| Okta | [SAML only](https://help.okta.com/en-us/Content/Topics/Apps/Apps_App_Integration_Wizard_SCIM.htm) | SAML | SCIM | 
| Azure AD | Supported for [both OIDC and SAML](https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/use-scim-to-provision-users-and-groups) | OIDC or SAML | SCIM |
| JumpCloud | [Supported for SAML](https://jumpcloud.com/support/provision-and-manage-users-and-groups-in-apps-using-custom-scim-identity-management-integration) | OIDC or SAML | SCIM |
| Auth0 | Supported by [professional services only](https://auth0.com/docs/authenticate/protocols/scim). GA expected Q4 '23 | OIDC or SAML | None (SCIM in Q3) | 
| OneLogin | [Supported for SAML](https://onelogin.service-now.com/support?id=kb_article&sys_id=1c8d87f2dbcfad1057fac24505961922) | SAML | SCIM |
| AWS IAM Identity Center | [Supported for SAML](https://docs.aws.amazon.com/singlesignon/latest/userguide/scim-profile-saml.html) | SAML | SCIM |
| DUO | integration with [PingIdentity](https://support.pingidentity.com/s/marketplace-integration/a7i1W000000TOcsQAG/duo-security-provisioning-connector) | SAML | SCIM (via PingIdentity) |
| Keycloak | None | OIDC | **None** |
| Authentik | Supported for [both OIDC and SAML](https://goauthentik.io/docs/providers/scim/) | SAML or OIDC | SCIM |
| Zitadel | None | OIDC | **None** |
| Ory Stack | [Not supported](https://github.com/ory/kratos/issues/1028) | OIDC | **None** |

**Comment by jamilbk** [comment]
Even more hurdles for building SCIM: We'll need to get the portal published in the Azure AD Gallery since Azure requires a valid URI for the SCIM endpoint.

https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/v2-howto-app-gallery-listing

See here for the gallery listing: https://portal.azure.com/#view/Microsoft_AAD_IAM/AppGalleryBladeV2

**Comment by jamilbk** [comment]
cc @rbhitchcock for context

**Comment by jamilbk** [comment]
WorkOS has this all figured out already. We just need to configure a couple redirects and build only one set of API endpoints for their webhooks to hit. Sample admin portal: https://demo.workos.com

**Comment by jamilbk** [comment]
Relevant thread on Slack: https://firezone-users.slack.com/archives/C02Q647R3RN/p1692108704182389

**Comment by jamilbk** [comment]
refs #2016

**Comment by jamilbk** [comment]
Closing in favor of #2930 and #2931
