### ISSUE TITLE
Multi WG port listeners on the hub

### ISSUE THREAD

**Issue by amastelek** [CloudFire-LLC/cloudfire#1440]
Would want groups of devices to use different ports on the central WG hub.

Solution would be to allow multi instances of WG to be managed by the UI and then allocate devices to one of the WG instances listening on separate ports.

**Comment by AndrewDryga** [comment]
Hello @amastelek, we have a feature that will allow you to do that on our backlog, but it would be released in around 6 months because it involves changing our architecture a lot. I'm closing it for now.
