### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by FedorAdo** [CloudFire-LLC/cloudfire#1445]
One user, 2 devices. Firezone takes up 2 gigabytes of RAM, immediately, at the start of the container. Isn't it too much? Is that how it should be?
Sorry for bad English.
![image](https://user-images.githubusercontent.com/30267668/219953988-5d8ce0e5-c7f1-4572-94fb-57666a3dfec4.png)

My docker-compose:
> x-deploy: &default-deploy
>   restart_policy:
>     condition: unless-stopped
>     delay: 5s
>     window: 120s
>   update_config:
>     order: start-first
> 
> version: '3.7'
> 
> services:
>   firezone:
>     image: firezone/firezone
>     container_name: firezone
>     ports:
>       - "51820:51820/udp"
>     env_file:
>       - /opt/firezone-wg/.env
>     volumes:
>       - /opt/firezone-wg/firezone:/var/firezone
>       - /etc/localtime:/etc/localtime:ro
>     cap_add:
>       - NET_ADMIN
>       - SYS_MODULE
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=0
>       - net.ipv4.ip_forward=1
>       - net.ipv6.conf.all.forwarding=1
>     networks:
>       default:
>         ipv4_address: 172.5.0.252
> 
>     deploy:
>       <<: *default-deploy
> 
> networks:
>   default:
>     enable_ipv6: false
>     name: application
>     external: true

My env:

> EXTERNAL_URL=https://vpn.my.com
> ADMIN_EMAIL=admin@vpn.com
> DEFAULT_ADMIN_PASSWORD=**********************
> 
> GUARDIAN_SECRET_KEY=*************************************
> SECRET_KEY_BASE=****************************
> LIVE_VIEW_SIGNING_SALT=**********************************
> COOKIE_SIGNING_SALT=********
> COOKIE_ENCRYPTION_SALT=*******
> 
> DATABASE_ENCRYPTION_KEY=************************************
> DATABASE_HOST=postgres15_db
> DATABASE_PORT=5432
> DATABASE_NAME=firezone-wg
> DATABASE_USER=*****
> DATABASE_PASSWORD=**********************
> DATABASE_POOL=10
> 
> TLS_OPTS="tls internal {
>                 on_demand
>               }"
> TELEMETRY_ENABLED=false
> CONNECTIVITY_CHECKS_ENABLED=true
> CONNECTIVITY_CHECKS_INTERVAL=10800
> 
> LOCAL_AUTH_ENABLED=true
> 
> OUTBOUND_EMAIL_FROM=admin@vpn.com
> OUTBOUND_EMAIL_PROVIDER=smtp
> OUTBOUND_EMAIL_CONFIGS={"smtp": {"relay": "************", "port": 587, "username": "admin@vpn.com", "password": "********************"}}
> 
> WIREGUARD_IPV4_ENABLED=true
> WIREGUARD_IPV4_MASQUERADE=true
> WIREGUARD_IPV6_ENABLED=false
> WIREGUARD_IPV6_MASQUERADE=false
> 
> WIREGUARD_IPV4_NETWORK=100.64.0.0/10
> WIREGUARD_IPV4_ADDRESS=100.64.0.1
> WIREGUARD_IPV6_NETWORK=fd00::/106
> WIREGUARD_IPV6_ADDRESS=fd00::1

 - Firezone Version [0.7.16]
 - OS: [Linux]
 - Distro: [ArchLinux]
 - Kernel version: [6.1.12-arch1-1]
 - Deployment method: [Docker]

**Comment by jamilbk** [comment]
Thanks for the report. Is that `docker stats` output? That's not right. Here's what I see on our demo instance:

<img width="886" alt="Screenshot 2023-02-22 at 9 07 23 AM" src="https://user-images.githubusercontent.com/167144/220703532-01488bd9-0c3e-4612-b33d-733f53efbd1c.png">

**Comment by jamilbk** [comment]
How many devices, users do you have?

**Comment by FedorAdo** [comment]
One user and two devices.
This is what the statistic output shows me - 
![image](https://user-images.githubusercontent.com/30267668/220813505-eb038c7e-024d-4b64-ac55-e79f881beaba.png)
This process inside the container eats so much memory.

**Comment by jamilbk** [comment]
Thanks for the added info -- unfortunately it doesn't yield any more insight into why your instance is eating so much memory. It could be related to something in your configuration or device parameters. 0.7.17 (coming in a bit) may fix the issue.

cc @AndrewDryga

**Comment by AndrewDryga** [comment]
@FedorAdo we need more information to investigate the issue, first of all, is the memory consumption the same if you reboot Firezone? Do you run it inside Docker? Also, please run following commands and share an output:
```
docker exec -it firezone-firezone-1 sh
exec bin/firezone remote
:erlang.memory(:total)
:erlang.memory()
```

you should get something like:
```elixir
iex(firezone@127.0.0.1)3> :erlang.memory(:total)
59410296
iex(firezone@127.0.0.1)4> :erlang.memory()
[
  total: 59442776,
  processes: 10890192,
  processes_used: 10890040,
  system: 48552584,
  atom: 991489,
  atom_used: 965873,
  binary: 2076144,
  code: 20414743,
  ets: 1657368
```

**Comment by FedorAdo** [comment]
> run following commands and share an output

```
/app # exec bin/firezone remote
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit]
Interactive Elixir (1.14.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(firezone@127.0.0.1)1> :erlang.memory(:total)
1661582848
iex(firezone@127.0.0.1)2> :erlang.memory()
[
  total: 1661047080,
  processes: 13877720,
  processes_used: 13877720,
  system: 1647169360,
  atom: 770289,
  atom_used: 761481,
  binary: 4196032,
  code: 20025022,
  ets: 1434816
]
```
Rebooting also results in the same memory consumption.


> Do you run it inside Docker?

Yes. My docker-compose.yml and env files are in the first post.

**Comment by AndrewDryga** [comment]
Okay, so first of all if after restart memory usage doesn't drop it's unlikely to be a memory leak. We will need a way to debug system memory (sorry it will be a bit tricky) because for some reason Erlang misbehaves on your host. I'm going to release a new version with some tooling bundled in (see #1467).

Once the new version is released can you please upgrade and run the following commands:
```
docker exec -it firezone-firezone-1 sh
bin/firezone remote
:observer_cli.start()
```

There you will see a list of processes ordered by memory usage, please take a screenshot.

Then you need to hit "b" (downcased) + enter, it will switch you to processes ordered by binary memory usage, please take another screenshot.

Then you need to hit "S" (upcased) + enter, it will switch you to System tab, please make a screenshot of that one too.

They should look something like this:
<img width="1728" alt="Screenshot 2023-02-24 at 10 45 51" src="https://user-images.githubusercontent.com/1877644/221237564-f5603ab0-75e7-488f-ab7d-2ddb96fdee16.png">
<img width="1728" alt="Screenshot 2023-02-24 at 10 45 57" src="https://user-images.githubusercontent.com/1877644/221237595-56113333-5442-4d2b-9fa2-78bfbdbced93.png">
<img width="1728" alt="Screenshot 2023-02-24 at 10 46 00" src="https://user-images.githubusercontent.com/1877644/221237602-bf61d4e0-387e-4c03-90a2-717c225d2217.png">

**Comment by AndrewDryga** [comment]
@FedorAdo I released a new version with tooling included, now you should be able to make those screenshots.

**Comment by FedorAdo** [comment]
:observer_cli.start()
![111](https://user-images.githubusercontent.com/30267668/222021448-fa784a0f-e16c-4c3d-a981-daebb1aff5c8.png)
![222](https://user-images.githubusercontent.com/30267668/222021460-a8bea04d-f208-4992-917b-042ad3f5d771.png)
![333](https://user-images.githubusercontent.com/30267668/222021477-832db86e-6135-4416-891b-e3bc159ae3dc.png)

**Comment by AndrewDryga** [comment]
Thank you! So what I see here is very suspicious, the Firezone application itself doesn't eat a lot of memory (as it should) but the Erlang VM eats a lot. Usually, it means that there is a memory leak with something like "monitors", but because when you restart the usage doesn't drop - something else is going on.

One of the main theories right now is that BEAM can pre-allocate a lot of memory when it boots but don't use it, this memory will be reclaimable by the OS.

If you are up to spending a bit of time to dig deeper I would be happy to help with the investigation, but we need a way to reproduce your situation. Is there any configuration you changed or this is a clean install? What are the Docker and Docker Compose versions you are using? I tried different versions of containers on Linux and MacOS but everywhere Firezone takes less than 100 MB of RAM.

**Comment by FedorAdo** [comment]
I apologize for not answering for a long time and for the poor English.

ArchLinux
_Linux 6.2.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Wed, 08 Mar 2023 04:07:29 +0000 x86_64 GNU/Linux_
- **What are the Docker and Docker Compose versions you are using?**
_Docker version 23.0.1_
_Docker Compose version 2.16.0_
- **Is there any configuration you changed or this is a clean install?**
I put Linux on the server, installed a docker and docker compose through pacman. Everything, actually. The configuration of the docker, docker compose did not touch.

Now I have done everything again. I did everything according to the instructions, without changing anything. https://www.firezone.dev/docs/deploy/docker/

Firezone Version 0.7.22
**docker run --rm firezone/firezone bin/gen-env > .env**
.env ->
```
VERSION=latest
EXTERNAL_URL=https://blabla.com
DEFAULT_ADMIN_EMAIL=blabla@blabla.com
DEFAULT_ADMIN_PASSWORD=blabla
GUARDIAN_SECRET_KEY=IZyqEAsGwmXg6OfSJF2ePPablmpYjLO1qegxI3o3Z5xAHd/DpYnV9u+JGdL+b/hl
SECRET_KEY_BASE=jgWJsMp8yvZEiaACWyVE2gDWnZzXYJfd6YVqdyiYNIsz9WY8I2KqM7M0phZuOlQ7
LIVE_VIEW_SIGNING_SALT=tVwrhhJr+trS0N5OjEzRTlL38q9j5pT1
COOKIE_SIGNING_SALT=kn1T+iLx
COOKIE_ENCRYPTION_SALT=X2LfavpD
DATABASE_ENCRYPTION_KEY=BXcpLUlb8jjWI+fb1/yx8Wemy3fjgq/GlNxv+IWniBs=
DATABASE_PASSWORD=2JSaIqtaREkTFXzg

WIREGUARD_IPV4_NETWORK=100.64.0.0/10
WIREGUARD_IPV4_ADDRESS=100.64.0.1
WIREGUARD_IPV6_NETWORK=fd00::/106
WIREGUARD_IPV6_ADDRESS=fd00::1
```
docker-compose.yml -> curl -fsSL https://raw.githubusercontent.com/firezone/firezone/master/docker-compose.prod.yml -o docker-compose.yml -> Didn't change anything.

**docker compose run --rm firezone bin/migrate
docker compose run --rm firezone bin/create-or-reset-admin
docker compose up -d**

And immediately again 2 gigabytes.
You are unlikely to be able to repeat my "car." The server is working and you can't write everything that is installed on it. Perhaps I can take some logs?
Or wait for "lucky ones" with the same problem. :)

**Comment by AndrewDryga** [comment]
Let's keep this open to see if anyone else also runs into this, so far your instance is the only one I'm aware of that consumes more than a few hundred megabytes of memory

**Comment by med-94** [comment]
I appear to have run into the same issue. On startup my firezone container is using about 1.5G of memory. I have managed to replicate this on a fresh install, which is hopefully helpful.

OS: Rocky 9.0
Docker version: `Docker version 23.0.1, build a5ee5b1`
Docker compose version: `Docker Compose version v2.16.0`

I can replicate as follows:
 - Spin up a fresh install. I'm using DigitalOcean, which I think should give us a fairly clean install of Rocky 9.
 - Install docker by following [this guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-rocky-linux-9).
 - Run the install script [here](https://www.firezone.dev/docs/deploy/docker/#option-1-automatic-install).
 - Once the install is complete, I see the firezone container is using a significant amount of memory:
 ```
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O     PIDS
c6816ff9d7cd   firezone-firezone-1   0.10%     1.558GiB / 3.636GiB   42.84%    140kB / 153kB   0B / 4.1kB    25
218d1bd1c2f8   firezone-caddy-1      0.00%     19.83MiB / 3.636GiB   0.53%     0B / 0B         0B / 246kB    9
9b9665529c41   firezone-postgres-1   0.00%     51.61MiB / 3.636GiB   1.39%     286kB / 297kB   0B / 79.7MB   11
```

Let me know if there is anything else I can do to help investigate this!

**Comment by med-94** [comment]
Continuing discussion from #1552 - @jamilbk have you managed to replicate using the information I gave above? I suspect any Rocky 9 VM would experience the same issue, not just ones on DigitalOcean - that's just what I had conveniently available to test on.

**Comment by viseshrp** [comment]
Hi,
For what it's worth, I run firezone on a 1GB RAM Raspberry Pi 3B+ in my tiny homelab with one device connected to it and the memory consumption is usually around 50%.

**Comment by jamilbk** [comment]
@med-94 Finally had a few minutes to reproduce this. Google searches hint that this is a [ulimit bug with Erlang inside Docker](http://erlang.org/pipermail/erlang-questions/2016-May/089335.html) that seems to be triggered by Rocky's Docker setup.

Try overriding the `nofile` ulimit to something like `1024` in your docker compose's `firezone` service:

```yaml
services:
  firezone:
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
```
