### ISSUE TITLE
Issues when adding new device

### ISSUE THREAD

**Issue by NicLor** [CloudFire-LLC/cloudfire#1460]
**Describe the bug**
After upgrading from 0.7.13 to 0.7.15 (and then 0.7.16 too), it seems that when you try to add a new device on the WebUI nothing happens and the WireGuard configuration isn't prompted.
We have two Firezone instances, one running on Ubuntu 22.04 and one running on Ubuntu 20.04 and we have deployed Firezone with Docker.
Both instances have the same problem.

**To Reproduce**
Go on the Firezone WebUI and try to add a new device.

**Comment by jamilbk** [comment]
Thanks for the report @NicLor -- working on a fix.
