### ISSUE TITLE
users in egress rules

### ISSUE THREAD

**Issue by mvivaldi** [CloudFire-LLC/cloudfire#1464]
Hello, because the user list is arranged in a "random" order if you have more than 30 users, it is rather challenging to create egress rules.
The list should be at least arranged alphabetically.
A checklist of some kind that allows you to choose many users at once would be a nice addition.

We would really benefit from your work with groups, which I am aware of (https://github.com/firezone/firezone/issues/1157).

Thank you

**Comment by AndrewDryga** [comment]
Hello, you should really wait for https://github.com/firezone/firezone/issues/1157 to happen, there are no plans to change how users are ordered or UI around them for now.
