### ISSUE TITLE
Strange IPs in WAN Connectivity Checks

### ISSUE THREAD

**Issue by omnitekton** [CloudFire-LLC/cloudfire#1469]
**Describe the bug**
Strange IP addresses from anothe countries visible in WAN Connectivity Checks tab instead of my own static, public IP. 

**To Reproduce**
Update from 0.7.0 to 0.7.17 with docker compose

**Expected behavior**
See my own public, static IP address from my country.

**Screenshots / Logs**
![obraz](https://user-images.githubusercontent.com/39647585/221355915-ea5d137f-a3e2-4010-a82f-5e26e9771634.png)

**Platform (please complete the following information):**
 - Firezone Version 0.7.17
 - OS: Linux
 - Distro: Ubuntu 22.04.2 LTS
 - Kernel version: GNU/Linux 5.15.0-60-generic x86_64
 - Deployment method: https://www.firezone.dev/docs/deploy/docker/#option-2-manual-install
   (Docker Compose version v2.15.0; Docker version 23.0.1, build a5ee5b1)

Recently I have discovered issues with my ISP (Toya). My offer is 900/60, while I get only 100/60 for last 48 hours. It this possible that somehow my ISP have some issues? How to even start troubleshooting?

**Comment by jamilbk** [comment]
Thanks for the report @TitanSpirit! This is likely a cache issue on our side with our public IP resolver. Will have a fix out in a bit.

**Comment by jamilbk** [comment]
This should be fixed now. If you restart your `firezone` service, you should see the proper public IP after about a minute.
