### ISSUE TITLE
(RuntimeError) Invalid configuration for 'wireguard_ipv4_address' retrieved from environment variable WIREGUARD_IPV4_ADDRESS

### ISSUE THREAD

**Issue by TinLe** [CloudFire-LLC/cloudfire#1483]
**Describe the bug**
I am running docker and firezone:0.7.13.  Works fine.  When I upgraded to 0.7.19, firezone container constantly crash and restart with the errors about `ERROR! Config provider Config.Reader failed with:
** (RuntimeError) Invalid configuration for 'wireguard_ipv4_address' retrieved from environment variable WIREGUARD_IPV4_ADDRESS.`

**To Reproduce**
Upgrade from 0.7.13 to 0.7.19.  Crash loop.  I backed down to 0.7.13 and it works fine.

**Expected behavior**
Upgrade should work seamlessly.

**Screenshots / Logs**
`      - ${FZ_INSTALL_DIR:-.}/caddy:/data/caddy
2,123,54,52,55,54,56,44,32,48,44,32,48,44,32,48,44,32,48,44,32,48,44,32,48,44,32,49,125,44,32,110,101,116,109,97,115,107,58,32,110,105,108,125,96,58,32,105,115,32,110,111,116,32,97,32,115,117,112,112,111,114,116,101,100,32,73,80,32,116,121,112,101>>},[{'Elixir.FzHttp.Config.Errors','raise_error!',1,[{file,"lib/fz_http/config/errors.ex"},{line,10},{error_info,#{module=>'Elixir.Exception'}}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.7.19/runtime.exs"},{line,52}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,309}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,290}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,282}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,283}]}]}}
init terminating in do_boot ({,[{Elixir.FzHttp.Config.Errors,raise_error!,1,[{_},{_},{_}]},{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
ERROR! Config provider Config.Reader failed with:
** (RuntimeError) Invalid configuration for 'wireguard_ipv4_address' retrieved from environment variable WIREGUARD_IPV4_ADDRESS.

Errors:

 - `%Postgrex.INET{address: {64768, 0, 0, 0, 0, 0, 0, 1}, netmask: nil}`: is not a supported IP type
    lib/fz_http/config/errors.ex:10: FzHttp.Config.Errors.raise_error!/1
    /app/releases/0.7.19/runtime.exs:52: (file)
    (elixir 1.14.3) src/elixir.erl:309: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.2) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.2) erl_eval.erl:290: :erl_eval.expr/6
    (stdlib 4.2) erl_eval.erl:282: :erl_eval.expr/6
    (stdlib 4.2) erl_eval.erl:283: :erl_eval.expr/6

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<73,110,118,97,108,105,100,32,99,111,110,102,105,103,117,114,97,116,105,111,110,32,102,111,114,32,39,119,105,114,101,103,117,97,114,100,95,105,112,118,52,95,97,100,100,114,101,115,115,39,32,114,101,116,114,105,101,118,101,100,32,102,114,111,109,32,101,110,118,105,114,111,110,109,101,110,116,32,118,97,114,105,97,98,108,101,32,87,73,82,69,71,85,65,82,68,95,73,80,86,52,95,65,68,68,82,69,83,83,46,10,10,69,114,114,111,114,115,58,10,10,32,45,32,96,37,80,111,115,116,103,114,101,120,46,73,78,69,84,123,97,100,100,114,101,115,115,58,32,123,54,52,55,54,56,44,32,48,44,32,48,44,32,48,44,32,48,44,32,48,44,32,48,44,32,49,125,44,32,110,101,116,109,97,115,107,58,32,110,105,108,125,96,58,32,105,115,32,110,111,116,32,97,32,115,117,112,112,111,114,116,101,100,32,73,80,32,116,121,112,101>>},[{'Elixir.FzHttp.Config.Errors','raise_error!',1,[{file,"lib/fz_http/config/errors.ex"},{line,10},{error_info,#{module=>'Elixir.Exception'}}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.7.19/runtime.exs"},{line,52}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,309}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,290}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,282}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,283}]}]}}
init terminating in do_boot ({,[{Elixir.FzHttp.Config.Errors,raise_error!,1,[{_},{_},{_}]},{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done`

**Platform (please complete the following information):**
 - Firezone Version 0.7.19
 - OS: Linux
 - Distro: Ubuntu 20.04.5
 - Kernel version: [5.15.0-1028-aws
 - Deployment method: Docker

**Additional context**
Simple upgrade via `docker compose pull; docker compose up -d`

**Comment by laweschan** [comment]
Hi @TinLe ,
  I also facing issue and work fine running in 0.7.13, but I forgot to backup those image, and can't found a way to download back 0.7.13, can you help share the firezone image about 0.7.13 ?

   thanks

Regards,
Lawes

**Comment by TinLe** [comment]
> Hi @TinLe , I also facing issue and work fine running in 0.7.13, but I forgot to backup those image, and can't found a way to download back 0.7.13, can you help share the firezone image about 0.7.13 ?

I assume you are using docker compose.  Just update your docker-compose.yml where it loads firezone image.
e.g.

` 
firezone:`
`    image: firezone/firezone:${VERSION:-0.7.13}
`

**Comment by laweschan** [comment]
> > Hi @TinLe , I also facing issue and work fine running in 0.7.13, but I forgot to backup those image, and can't found a way to download back 0.7.13, can you help share the firezone image about 0.7.13 ?
> 
> I assume you are using docker compose. Just update your docker-compose.yml where it loads firezone image. e.g.
> 
> ` firezone:` ` image: firezone/firezone:${VERSION:-0.7.13}`

thank very much, it work

**Comment by jamilbk** [comment]
Hi @TinLe -- thanks for the report. Please double-check your `$HOME/.firezone/.env` file and ensure it contains only **one** `WIREGUARD_IPV4_ADDRESS` variable. There was a bug in earlier versions that included a typo'd version of that variable, and it should be `WIREGUARD_IPV6_ADDRESS=fd00::1` and not `WIREGUARD_IPV4_ADDRESS=fd00::1`

**Comment by TinLe** [comment]
@jamilbk  Yes, I found the typo in .env file and updated it to IPV6.  But now I get other errors.  It's looping/crashing with the following in logs.  Reverting back to 0.7.13 works.

`17:15:19.003 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] == Running 20230206172556 FzHttp.Repo.Migrations.ChangeDnsAndAllowedIpsToInetArray.change/0 forward
17:15:19.007 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] rename column default_client_dns to default_client_dns_string on table configurations
17:15:19.008 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] rename column default_client_allowed_ips to default_client_allowed_ips_string on table configurations
17:15:19.009 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] rename column dns to dns_string on table devices
17:15:19.009 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] rename column allowed_ips to allowed_ips_string on table devices
17:15:19.009 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] alter table configurations
17:15:19.013 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] alter table devices
17:15:19.015 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.179.0> [info] execute "UPDATE configurations\nSET default_client_dns = string_to_array(trim(both ' ' from regexp_replace(default_client_dns_string, ' *, *', ',')), ','),\n    default_client_allowed_ips = string_to_array(trim(both ' ' from regexp_replace(default_client_allowed_ips_string, ' *, *', ',')), ',')::inet[]\n"
** (Postgrex.Error) ERROR 22P02 (invalid_text_representation) invalid input syntax for type inet: " 10.0.30.0/24"
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:326: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)`

**Comment by AndrewDryga** [comment]
@TinLe please try the latest version, the issue should be resolved. If there is anything else wrong I will reopen the issue.

**Comment by TinLe** [comment]
@AndrewDryga yep.  that fixes it.  Thank you!   I am running 0.7.20 now.
