### ISSUE TITLE
update /app/bin/bootstrap to support pod idea

### ISSUE THREAD

**Issue by laweschan** [CloudFire-LLC/cloudfire#1485]
**Is your feature request related to a problem? Please describe.**
when using pod feature in Podman / kubernetes, the current docker script will hit error, since Pod will create the corresponding info into pod container, eg. ip address and interface. hence --rm action will not remove the firezone --> wg-firezone interface, as a result, an error will occurs after "/bin/migrate" --> "create-or-reset-admin" step.

the error message shows like below:
**"ip: RTNETLINK answers: File exists” error**
during deployment

it should due to conflict in interface exists, or ip conflict . etc

error due to the conflict in script line:
**ip link add ${WIREGUARD_INTERFACE_NAME} type wireguard**

because the interface already exists in pod, remove container can't clean up  wg-firezone interface

**Describe the solution you'd like**
a workaround is precheck if wg-firezone interface exists, if not then create it.

  If [ ! -d “/sys/class/net/wg-firezone” ]; then
     ip link add ${WIREGUARD_INTERFACE_NAME} type wireguard
  fi

**Describe alternatives you've considered**
this change should not impact the current docker support, since the interface will create accordingly.
but this change should able to support Podman/Kubernetes pod feature, enhance the compatibility to other container technology.

**Additional context**

**Comment by AndrewDryga** [comment]
Hello @laweschan. Adding an `if` condition would not solve the issue entirely, because we are also adding IP routes and addresses. We are also setting the MTU, which will break in case somebody tries to deploy two separate firezone Pods on the same Kubernetes Node with different MTU settings because one setting will override another one.

I think right now you can work around the issue by either [replacing the environment settings](https://github.com/firezone/firezone/blob/master/rel/overlays/bin/bootstrap#L3-L9) if you need two independent Firezone instances running or if your goal is high availability or throughput what you actually want to do is to add a Pod anti-affinity rule to prevent two Firezone instances be scheduled to the same k8s node. IRL there is no situation when having multiple replicas of the same up on a VM will help with performance or availability, failures are mostly node-specific.

**Comment by AndrewDryga** [comment]
Actually, one more thing you can try doing (but I'm not 100% sure it will work) is to use `valueFrom` in Firezone environment variables and override the interface name for each container, something like:
```
- name: MY_POD_NAME
   valueFrom:
     fieldRef:
       fieldPath: metadata.name
- name: WIREGUARD_INTERFACE_NAME
  value: wg-fz-$(MY_POD_NAME)
```

**Comment by laweschan** [comment]
> Actually, one more thing you can try doing (but I'm not 100% sure it will work) is to use `valueFrom` in Firezone environment variables and override the interface name for each container, something like:
> 
> ```
> - name: MY_POD_NAME
>    valueFrom:
>      fieldRef:
>        fieldPath: metadata.name
> - name: WIREGUARD_INTERFACE_NAME
>   value: wg-fz-$(MY_POD_NAME)
> ```

no I'm not building any advance structure like independent Firezone instances.
in past (0.7.13 version or before), I have rewrite the default dockerfile and run it in Podman without issue.
I have also share the script in forum before.

however after 0.7.13 version I always found error even in new build OS, I have spend sometimes today to check it in firezone container and found that the potential problem and share what I found

how do I know it can fix ?
I am not programmer, I just use a simple and stupid way, add pause one-by-one step in firezone container buildup, pasue /bin/nigrate. puase reset-or-create-admin.
once I pause, I login the firezone container, manually remove the wg-firezone interface, then let the script continues to execute, 
it work !

I know the script still has route and other step, but under my observe, the routing, ip address hasn't break the system using this method.

so I think add that condition check can balance docker and podman issue, at least in this moment

I will keep check to found if any issue,
thanks

Lawes

**Comment by AndrewDryga** [comment]
Can you please describe a use case for why you need two Firezone instances so we can better understand the need?

**Comment by laweschan** [comment]
> Can you please describe a use case for why you need two Firezone instances so we can better understand the need?

Hi @AndrewDryga , I haven't build two firezone instance, any.
I just rewrite and follow the default dockerfile step, in dockerfile some step about firezone like:
step1: --rm for bin/migrate
step2: --rm for bin/reset-or-create-admin
step3: -dt for firezone startup

what I facing is, I using Podman, Pod to group postgres and firezone container together.
it's because postgres port doesn't require to expose externally, only firezone require and allow to access, group into Pod is under this consideration.
however, netns setting, wg-firezone interface is under pod-container and netns, not belong to firezone container like docker setting, in this scenario, pod can't work becasue under each step, the bootstrap will try to recreate wg-interface, that conflict the pod idea.

if recheck wg-inteface exist is not an option, then can we re-consider the step about bin/migrate, reset-or-create-admin into a single step ?  I have no idea why each step require --rm before firezone to startup, I try to follow the existing logic flow into podman script anyway currently.
