### ISSUE TITLE
nginx enable module http_realip_module

### ISSUE THREAD

**Issue by lixtechdev** [CloudFire-LLC/cloudfire#1486]
**Is your feature request related to a problem? Please describe.**
can not recognize real IP if requests going via Cloudflare to firezone nginx

**Describe the solution you'd like**
during build platform please add for compile nginx "--with-http_realip_module"

**Additional context**
for external reverse proxy compatible or for possibility work with CDN's like Cloudflare

**Comment by AndrewDryga** [comment]
Hey @lixtechdev, we are dropping support of Omnibus-based deployments (see #1304) so there will be no nginx shipped with Firezone. Right now you can upgrade to using Docker-based deployment which is using Caddy and it should already support getting real IP from the headers.
