### ISSUE TITLE
OpenIDConnect error

### ISSUE THREAD

**Issue by Lowxorx** [CloudFire-LLC/cloudfire#1488]
**Describe the bug**
Hello,

I have configured a custom OpenId authentication provider (Authentik), but I can't connect with it.

The problem seems to be that I am using a self-signed certificate.
`I added this configuration in my environment file: HTTP_CLIENT_SSL_OPTS={"verify": "verify_none"}`

I removed caddy from the docker-compose because I use my own reverse-proxy (nginx). 

When I log in via Authentik, the authentication server receives and processes my request, but on the Firezone side, there seems to be a problem with the token :

`An OpenIDConnect error occurred. Details: {:invalid_jwt, "verification failed"}`

I don't have any logs or additional details unfortunately, on Authentik side everything is fine. 

Did I miss an option to allow self-signed certificates maybe? 

**To Reproduce**
Deploy Firezone using the official documentation
Configure a custom OpeniD provider
Try to log in with it

**Expected behavior**
I should be able to login with the custom OpenID provider

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/56053431/222991191-8dc1177c-3fb6-4843-8fd8-8c92459a569d.png)

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12] = 0.7.18
 - OS: Linux
 - Distro: Debian 11
 - Kernel version: 5.15
 - Deployment method: Docker

**Additional context**
Firezone, Authentik and the reverse proxy are all hosted on their own virtual machine and are using the same certificate.

**Comment by AndrewDryga** [comment]
@Lowxorx I believe the issue here is not due to the self-signed HTTP certificate, but because Authentic returns a token that can not be verified. Probably there is something wrong with the SAML settings on Firezone or Authentic configuration.

Is there anything else suspicious from the logs? Does Authentic work with other services?

**Comment by Lowxorx** [comment]
> 
@AndrewDryga I got nothing suspicious in the logs, as you can see below :
<details>
<summary>Logs</summary>

>firezone-firezone-1  | 17:15:13.949 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.1200.0> request_id=F0nj5i9qfI1OfTkAAAJB [info] GET /auth/oidc/iB4uivA0

>firezone-firezone-1  | 17:15:14.046 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.1200.0> request_id=F0nj5i9qfI1OfTkAAAJB [info] Sent 302 in 96ms

>firezone-firezone-1  | 17:15:14.791 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.1206.0> request_id=F0nj5mGeCNZb9jIAAAJR [info] GET /auth/oidc/iB4uivA0/callback

>**firezone-firezone-1  | 17:15:14.861 erl_level=error application=fz_http domain=elixir file=lib/fz_http_web/controllers/auth_controller.ex function=oidc_callback/2 line=91 mfa=FzHttpWeb.AuthController.oidc_callback/2 module=FzHttpWeb.AuthController pid=<0.1206.0> request_id=F0nj5mGeCNZb9jIAAAJR [error] An OpenIDConnect error occurred. Details: {:invalid_jwt, "verification failed"}**

>firezone-firezone-1  | 17:15:14.861 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.1206.0> request_id=F0nj5mGeCNZb9jIAAAJR [info] Sent 302 in 69ms

>firezone-firezone-1  | 17:15:14.914 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.1208.0> request_id=F0nj5mjr1rhGa9AAAAJh [info] GET /

>firezone-firezone-1  | 17:15:14.915 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.1208.0> request_id=F0nj5mjr1rhGa9AAAAJh [info] Sent 200 in 1ms

</details>

Authentik works with other appplications such as Nextcloud or Portainer (same config on Authentik side, that's why I believe it's a Firezone problem)

Here you can see how Firezone is configured : 
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/56053431/223184193-e1923223-164c-4d1f-aa33-8189075bf623.png)

</details>

Is there any way to set the log to a more verbose level maybe?

**Comment by AndrewDryga** [comment]
Well, this is very hard to debug, but this error basically means that the token exchange was successful but during login, Firezone tried to verify JWT token issues by Authentic and it is invalid. It can be something in Firezone, but can be in Authentic too (eg. other apps might not be as strict with token verification).

For example, such an issue can occur when JWKS from your Discovery Document URI doesn't match the one used to sign the token.

I can give hints on how to debug it but it will take some effort, try running these commands:
```
docker exec -it firezone-firezone-1 sh
bin/firezone remote
```

This will get you into the Elixir shell, there you want to replace a module to see the actual errors, to do this just copy-paste [this file](https://gist.githubusercontent.com/AndrewDryga/23863b69848a918d95c53216a820eeaa/raw/f19d0bb10738021c6c5c9b52ae09d8bf687a263d/replace.ex) into the shell and hit enter, then you can try to log in using Authentic again and the error will give more details on what is happening there. 

The change is not permanent, the original module will be recovered once you reboot the Firezone.

**Comment by Lowxorx** [comment]
> Well, this is very hard to debug, but this error basically means that the token exchange was successful but during login, Firezone tried to verify JWT token issues by Authentic and it is invalid. It can be something in Firezone, but can be in Authentic too (eg. other apps might not be as strict with token verification).
> 
> For example, such an issue can occur when JWKS from your Discovery Document URI doesn't match the one used to sign the token.
> 
> I can give hints on how to debug it but it will take some effort, try running these commands:
> 
> ```
> docker exec -it firezone-firezone-1 sh
> bin/firezone remote
> ```
> 
> This will get you into the Elixir shell, there you want to replace a module to see the actual errors, to do this just copy-paste [this file](https://gist.githubusercontent.com/AndrewDryga/23863b69848a918d95c53216a820eeaa/raw/f19d0bb10738021c6c5c9b52ae09d8bf687a263d/replace.ex) into the shell and hit enter, then you can try to log in using Authentic again and the error will give more details on what is happening there.
> 
> The change is not permanent, the original module will be recovered once you reboot the Firezone.

Thank you for your advice. After following your procedure, I get the JWT in the error details. 
If I decode it and verify it's signature (on jwt.io) the site tells me that the signature is valid and verified. 

Maybe there is a way to make my signature key known to Firezone?

**Comment by AndrewDryga** [comment]
@Lowxorx when you verified it on jwt.io which public and private key did you use? From `.well-known/openid-configuration/jwks.json`? (Exact path can be different for Authentic.)

**Comment by Lowxorx** [comment]
> @Lowxorx when you verified it on jwt.io which public and private key did you use? From `.well-known/openid-configuration/jwks.json`? (Exact path can be different for Authentic.)

Yes I used the signing key I selected in Authentik (the same one I can see in the jwks url)

**Comment by AndrewDryga** [comment]
@Lowxorx hm, for some reason either there is a bug in signature verification (would be a bug in a library we are using) or for some reason, we can't get valid JWKS from Authentic, can you please run 
```elixir
docker exec -it firezone-firezone-1 sh
bin/firezone remote
discovery_document_uri = "YOUR DISCOVERY URL COMES HERE"
Document.fetch_document(discovery_document_uri)
```
and make sure it's keys are the same as over URL, maybe Authentic rotates them (we keep a cache of the documents).

**Comment by Lowxorx** [comment]
> @Lowxorx hm, for some reason either there is a bug in signature verification (would be a bug in a library we are using) or for some reason, we can't get valid JWKS from Authentic, can you please run
> 
> ```elixir
> docker exec -it firezone-firezone-1 sh
> bin/firezone remote
> discovery_document_uri = "YOUR DISCOVERY URL COMES HERE"
> Document.fetch_document(discovery_document_uri)
> ```
> 
> and make sure it's keys are the same as over URL, maybe Authentic rotates them (we keep a cache of the documents).

I am unable to execute the command you provided. Here is the error: 

`** (UndefinedFunctionError) function Document.fetch_document/1 is undefined (module Document is not available)`

I tried to find how to load a module but I don't know elixir at all :)

**Comment by AndrewDryga** [comment]
My bad @Lowxorx, forgot to add a parent module name, the last one should be: `OpenIDConnect.Document.Document.fetch_document(discovery_document_uri)`

**Comment by Lowxorx** [comment]
> My bad @Lowxorx, forgot to add a parent module name, the last one should be: `OpenIDConnect.Document.Document.fetch_document(discovery_document_uri)`

Thanks. The key in the field "x5c"  of the jwks node is the same public key as the one used for signing auth requests on authentik side.

**Comment by AndrewDryga** [comment]
Thank you, so the issue is somewhere with signature checking, can you please generate a new key the same way you did it for Authentic and share it with me? It should not be the one you use, I just want to see if there is a key generation format that our jwt library does not support and fails to verify.

**Comment by Lowxorx** [comment]
> Thank you, so the issue is somewhere with signature checking, can you please generate a new key the same way you did it for Authentic and share it with me? It should not be the one you use, I just want to see if there is a key generation format that our jwt library does not support and fails to verify.

Sure, here you go : [Firezone test key_.zip](https://github.com/firezone/firezone/files/10971411/Firezone.test.key_.zip)

**Comment by Lowxorx** [comment]
@AndrewDryga I don't know what you did but I updated Firezone and it works. Have you changed anything about this?

**Comment by AndrewDryga** [comment]
@Lowxorx nope, there were were no new releases for 2 weeks, I even wasn't able to reproduce it locally

**Comment by Lowxorx** [comment]
> @Lowxorx nope, there were were no new releases for 2 weeks, I even wasn't able to reproduce it locally

Upgraded from [0.7.23](https://github.com/firezone/firezone/releases/tag/0.7.23) to latest version, and it works :+1:

**Comment by AndrewDryga** [comment]
That's so cool to see things resolved even if unintentionally 🤣
