### ISSUE TITLE
There is no trailing slash in the Redirect URI field in the OIDC Configuration page

### ISSUE THREAD

**Issue by kinseii** [CloudFire-LLC/cloudfire#1492]
**Describe the bug**
If you leave the default value or copy the suggested Redirect URI value, Azure will give a Redirect URI error mismatch after creating App Registration. 

**To Reproduce**
Add OIDC settings for Firezone and leave the Redirect URI field as default, i.e. without filling it.

**Expected behavior**
Add a slash to the default value for Redirect URI at the end. Also add it to the description field below.

**Screenshots / Logs**
![firezone_redirect_url_problem](https://user-images.githubusercontent.com/74458264/223942681-b6e8dfe5-9c7c-4cb1-9bc4-2afe1a0cc28c.png)

**Platform (please complete the following information):**
 - Firezone Version 0.7.20
 - OS: Linux
 - Distro: Ubuntu Server 22.04
 - Deployment method: Docker

**Comment by AndrewDryga** [comment]
Hey @kinseii. I know it's a bit confusing that you need to manually add a slash for Azure, but If we change the default it will break a lot of connections that are already working for all other providers, so I don't think that we will be tackling this.

On the upside, we do have it described in our Azure AD docs so maybe it will help people struggling with it: https://www.firezone.dev/docs/authenticate/oidc/azuread/#step-1-obtain-configuration-parameters.

**Comment by kinseii** [comment]
@AndrewDryga 
You described the slash only for adding App Registration. The OIDC configuration page itself says that you don't need to change it for most cases. This misled me and I spent several hours trying to find the reason.
