### ISSUE TITLE
Not able to use AmazonSES for password reset links 

### ISSUE THREAD

**Issue by maciejprzezdziecki** [CloudFire-LLC/cloudfire#1494]
Hello I've got following error on version 0.7.20

Crash dump is being written to: erl_crash.dump...done
ERROR! Config provider Config.Reader failed with:
** (RuntimeError) Invalid configuration for 'outbound_email_adapter' retrieved from environment variable OUTBOUND_EMAIL_ADAPTER.

Errors:

 - `"Swoosh.Adapters.AmazonSES"`: is invalid
    lib/fz_http/config/errors.ex:10: FzHttp.Config.Errors.raise_error!/1
    /app/releases/0.7.20/runtime.exs:161: (file)
    (elixir 1.14.3) src/elixir.erl:309: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.2) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.2) erl_eval.erl:290: :erl_eval.expr/6
    (stdlib 4.2) erl_eval.erl:282: :erl_eval.expr/6
    (stdlib 4.2) erl_eval.erl:961: :erl_eval.expr_list/7

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<73,110,118,97,108,105,100,32,99,111,110,102,105,103,117,114,97,116,105,111,110,32,102,111,114,32,39,111,117,116,98,111,117,110,100,95,101,109,97,105,108,95,97,100,97,112,116,101,114,39,32,114,101,116,114,105,101,118,101,100,32,102,114,111,109,32,101,110,118,105,114,111,110,109,101,110,116,32,118,97,114,105,97,98,108,101,32,79,85,84,66,79,85,78,68,95,69,77,65,73,76,95,65,68,65,80,84,69,82,46,10,10,69,114,114,111,114,115,58,10,10,32,45,32,96,34,83,119,111,111,115,104,46,65,100,97,112,116,101,114,115,46,65,109,97,122,111,110,83,69,83,34,96,58,32,105,115,32,105,110,118,97,108,105,100>>},[{'Elixir.FzHttp.Config.Errors','raise_error!',1,[{file,"lib/fz_http/config/errors.ex"},{line,10},{error_info,#{module=>'Elixir.Exception'}}]},{elixir_eval
,'__FILE__',1,[{file,"/app/releases/0.7.20/runtime.exs"},{line,161}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,309}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,290}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,282}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]}]}}
init terminating in do_boot ({,[{Elixir.FzHttp.Config.Errors,raise_error!,1,[{_},{_},{_}]},{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]}]})

**Comment by AndrewDryga** [comment]
Hey @maciejprzezdziecki, please use `Elixir.Swoosh.Adapters.AmazonSES` instead. I've pushed a PR to fix the docs.
