### ISSUE TITLE
config change masks DATABASE_URL

### ISSUE THREAD

**Issue by wwkeyboard** [CloudFire-LLC/cloudfire#1499]
**Describe the bug**
A recent configuration change  #https://github.com/firezone/firezone/commit/af431c0a6f2dc9f3ec39d8a9d7090f34aaf2bc4e masks the DATABASE_URL env var in the firezone container, making the `ecto.setup, ecto.seed` steps of bootstrapping the DB fail with a connection error. The new config points to localhost, which masks the env var set in the container.

**To Reproduce**
Follow the [bootstrapping](https://github.com/firezone/firezone/blob/master/CONTRIBUTING.md#bootstrapping) steps with fresh containers and no postgres running locally.

**Expected behavior**
ecto.setup completes successfully

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version: main
 - Deployment method: Docker

**Additional context**
Setting https://github.com/firezone/firezone/blob/master/config/config.exs#L17 to "postgres" will get the bootstrap process working again. Opening a shell on the firezone container can confirm that with the DATABASE_URL variable set the ecto bootstrap still tries to use the value set in config.exs. I suspect https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/config.ex#L68 also needs to break apart the DATABASE_URL and map the components onto the keys needed in the config, if this method of configuration is still to support the env var. Otherwise maybe set up a different environment for running in docker? I don't have a solid answer, I think it's going to depend on what you want to support.

**Comment by AndrewDryga** [comment]
Hey @wwkeyboard,

We dropped support for `DATABASE_URL` but I forgot to remove it from the docker-compose file, we all are using docker just to manage dependencies (PG and IdPs) while the Firezone itself runs on the host (hence localhost works) and nobody noticed it. Pushed a PR to fix it.

**Comment by wwkeyboard** [comment]
Awesome, thank you! I was following through the contributing guide and got tripped up.

**Comment by AndrewDryga** [comment]
Sorry for that 😞, we don't get a lot of contributions because onboarding is rather complex, it's becoming a big product.

Can you please try the branch in that PR and if it works I'll merge it?

**Comment by wwkeyboard** [comment]
The variables get set in the container, but the Repo is still trying to connect to localhost.

**Comment by AndrewDryga** [comment]
Gimme a minute to look into it

**Comment by wwkeyboard** [comment]
There is a workaround at the moment so it's not blocking anything for me. I do appreciate you taking a look so quickly!
