### ISSUE TITLE
0.7.23 bug, about DEFAULT_ADMIN_EMAIL

### ISSUE THREAD

**Issue by laweschan** [CloudFire-LLC/cloudfire#1511]
**Describe the bug**
during deployment, the variable error about ADMIN_EMAIL can't access

**To Reproduce**
default deployment, or simply run the command from install.sh
podman run --rm docker.io/firezone/firezone:${VERSION:-latest} bin/gen-env > "$installDir/.env"

**Expected behavior**
the default .env file, should contain DEFAULT_ADMIN_EMAIL variable, however, the content is DEFAULT_ADMIN, instead of DEFAULT_ADMIN_EMAIL

and look at another script:
sed -i.bak "s/DEFAULT_ADMIN_EMAIL=.*/DEFAULT_ADMIN_EMAIL=$1/" "$installDir/.env"

since DEFAULT_ADMIN_EMAIL not exists,  it can't rewrite to the $1 variable

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/17445193/224872914-363adb27-9189-47a5-8fc2-5f52152462d6.png)

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.23]
 - OS: [e.g. Fedora]
 - Distro: [e.g. 37]
 - Kernel version: [e.g. 6.x]
 - Deployment method: [podman]

**Additional context**
If I manually change to 
sed -i.bak "s/ADMIN_EMAIL=.*/DEFAULT_ADMIN_EMAIL=$1/" "$installDir/.env"

then everything work fine.
so I guess there has something conflict between ADMIN_EMAIL and DEFAULT_ADMIN_EMAIL variable currently

**Comment by AndrewDryga** [comment]
Hello @laweschan, the fix for this issues is already merged to master, we should cut a release tomorrow morning.

**Comment by laweschan** [comment]
thanks @AndrewDryga , appreciate your effort and response.

**Comment by AndrewDryga** [comment]
Resolved in https://github.com/firezone/firezone/releases/tag/0.7.24
