### ISSUE TITLE
Allow download config for restricted user

### ISSUE THREAD

**Issue by maciejprzezdziecki** [CloudFire-LLC/cloudfire#1512]
When I Untick allow unpriv device management and device configuration I wanted users to have ability to download zip package with configuration set by admin

for example download config button

**Comment by AndrewDryga** [comment]
Hello @maciejprzezdziecki, It's a feature that is not possible to implement, we don't store the config secrets so after they are rendered we can't re-render them for clients. Security-wise storing them will be a really bad thing to do.

But I feel that what you really want is native client apps that will distribute configuration for you and we are working on those, see #1329. Closing as a duplicate.
