### ISSUE TITLE
OpenID & Authelia:  `redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls

### ISSUE THREAD

**Issue by gelven4sec** [CloudFire-LLC/cloudfire#1514]
**Describe the bug**
When clicking on the login button, redirecting to authelia, I get the message that `redirect_uri` parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.

So I just had to rename `redirect_uri` to `redirect_uris` to make it work.

**To Reproduce**
Add an Authelia instance as an OpenID provider then try to login.

**Expected behavior**
Simple login though Authelia.

**Screenshots / Logs**
Error message from Authelia : 
```json
{
  "error": "invalid_request",
  "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."
}
```

**Platform (please complete the following information):**
 - Firezone Version: 0.7.24
 - OS: Linux
 - Distro: Debian
 - Kernel version: 5.10.0
 - Deployment method: Docker

**Additional context**
Nothing more to add, looks like Authelia should recieve `redirect_uris` instead of `redirect_uri`.

**Comment by AndrewDryga** [comment]
Hey @sven-eliasen, not sure why you think it's a bug. Does the error basically say that Firezone Redirect URI is not configured properly in Authelia? 

`redirect_uris` is a part of OpenID Connect registration request, but when we integrate to IdP we should use `redirect_uri` by spec, see: https://openid.net/specs/openid-connect-http-redirect-1_0-01.html.

**Comment by gelven4sec** [comment]
Hi @AndrewDryga,

Can you confirm that the problem comes from Authelia which should have accepted `redirect_uri` as parameter ?

I'm really out of my comfort zone, I'm just trying to figure out where does the problem comes from.

**Comment by AndrewDryga** [comment]
I believe yes, we just follow the spec (I've attached the link above) or maybe I don't fully understand the issue. Can you elaborate on where exactly you needed to rename `redirect_uri` to `redirect_uris` (better with a screenshot)?

**Comment by gelven4sec** [comment]
Landing page on Firezone :
![image](https://user-images.githubusercontent.com/37241392/225376386-3aa4e9e2-8213-45dd-84fb-8afb71963289.png)
I click on sign in with authelia.

Then I get here where I see this error : 
![image](https://user-images.githubusercontent.com/37241392/225377990-da980a09-255e-4dd7-a1d7-0b313a65370f.png)

And there is where I rename `redirect_uri` to `redirect_uris`.

Then it works normaly.

**Comment by mostafahussein** [comment]
I think what @sven-eliasen wanted to mentioned, that `Firezone` should support passing `redirect_uris` in the query params in case of using Authelia. [As per their documentation](https://www.authelia.com/configuration/identity-providers/open-id-connect/#redirect_uris), they only mention `redirect_uris` not `redirect_uri`

**Comment by AndrewDryga** [comment]
@mostafahussein I'm not an Authelia user but it looks like the documentation you linked is for configuring the Authelia as IdP, not a part of the OpenID Connect flow when we use it as IdP. 

The thing we can see on the screenshot actually looks like they did not implement the OIDC spec correctly/have a typo in the query parameter name, which is not something we should be adjusting to - we all should follow [the spec](https://openid.net/specs/openid-connect-http-redirect-1_0-01.html). (They even reference it in Authelia docs too.)

**Comment by gelven4sec** [comment]
Alright I just wanted to make that clear, I'm going to recreate this issue at Authelia.

Thanks for your answers ! (And this project btw)

**Comment by AndrewDryga** [comment]
Please put a link to the issue here once you create it, I will follow it too in case there is something we should do too *within the spec scope*.

**Comment by gelven4sec** [comment]
@AndrewDryga 
Okay, so I got the fix. The problem is completely elsewhere, I totally misread the error message.
The `redirect_uri` is an accepted parameter, it just didn't contain a valid url.

When I configured Authelia in Firezone, I left blank the "Redirect URI" field to let it default.
But when it is left blank, there's a bug leading my `redirect_url` to become : 
`https://firezone.exampple.com//auth/oidc/Authelia/callback`
instead of
`https://firezone.exampple.com/auth/oidc/Authelia/callback`

**Comment by AndrewDryga** [comment]
Great you figured this out, closing this for now

**Comment by gelven4sec** [comment]
@AndrewDryga 
No I meant there's actually a bug in Firezone.

If you leave the "Redirect URI" field blank, then the default value contains a double slash, like this : 
`https://firezone.exampple.com//auth/oidc/Authelia/callback`

![image](https://user-images.githubusercontent.com/37241392/225774168-90a1ba06-a2d1-4601-9a9c-d793928429ec.png)

**Comment by sonnysideup** [comment]
I just encountered this same bug while integrating with Google SSO. The **Redirect URI** must be populated to remove the double slash. I'm using version 0.7.24
