### ISSUE TITLE
(ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead

### ISSUE THREAD

**Issue by laweschan** [CloudFire-LLC/cloudfire#1536]
**Describe the bug**
New deployment in version 0.7.25, during the process create-or-reset-admin

**To Reproduce**
follow the bash script.

**Expected behavior**

**Screenshots / Logs**
Creating admin...
Creating WireGuard interface wg-firezone
Adding route 100.64.0.0/10 for interface wg-firezone
Adding route fd00::/106 for interface wg-firezone
Generating a RSA private key
...+++++
..........................................................................................................................................+++++
writing new private key to '/var/firezone/saml.key'
-----
15:56:20.673 erl_level=notice domain=otp file=application_controller.erl function=info_exited/3 line=2119 mfa=:application_controller.info_exited/3 module=application_controller pid=<0.44.0> [notice] Application fz_http exited: exited in: FzHttp.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "configurations" does not exist

    query: SELECT c0."id", c0."allow_unprivileged_device_management", c0."allow_unprivileged_device_configuration", c0."local_auth_enabled", c0."disable_vpn_on_oidc_error", c0."default_client_persistent_keepalive", c0."default_client_mtu", c0."default_client_endpoint", c0."default_client_dns", c0."default_client_allowed_ips", c0."vpn_session_duration", c0."logo", c0."openid_connect_providers", c0."saml_identity_providers", c0."inserted_at", c0."updated_at" FROM "configurations" AS c0
            (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
            (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
            (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (ecto 3.9.4) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.one!/3
            (fz_http 0.7.25) lib/fz_http/config.ex:96: FzHttp.Config.validate_runtime_config!/0
            (fz_http 0.7.25) lib/fz_http/application.ex:12: FzHttp.Application.start/2
            (kernel 8.5.3) application_master.erl:293: :application_master.start_it_old/4
.......
15:56:20.704 erl_level=notice domain=otp file=application_controller.erl function=info_exited/3 line=2119 mfa=:application_controller.info_exited/3 module=application_controller pid=<0.44.0> [notice] Application cidr exited: :stopped
15:56:20.704 erl_level=notice domain=otp file=application_controller.erl function=info_exited/3 line=2119 mfa=:application_controller.info_exited/3 module=application_controller pid=<0.44.0> [notice] Application runtime_tools exited: :stopped
** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
    (ecto 3.9.4) lib/ecto/query/builder.ex:1045: Ecto.Query.Builder.not_nil!/1
    (fz_http 0.7.25) lib/fz_http/release.ex:29: FzHttp.Release.create_admin_user/0
    nofile:1: (file)
    (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7
    (elixir 1.14.3) lib/code.ex:425: Code.validated_eval_string/3

**Platform (please complete the following information):**
 - Firezone 0.7.25
 - OS: Fedora 36
 - Kernel version: 6.2.8-200
 - Deployment method:  Podman

**Additional context**

**Comment by jamilbk** [comment]
Thanks for the report @laweschan. It looks like for some reason the migrations didn't run, and your database is empty.

Could you do a `docker compose run --rm firezone bin/migrate` to run migrations and then `docker compose run --rm firezone bin/create-or-reset-admin` to create-or-reset-admin once more?

**Comment by laweschan** [comment]
yes, the process seems able to continue this time.
thanks
