### ISSUE TITLE
Screen for Login Options

### ISSUE THREAD

**Issue by bensonrlee** [CloudFire-LLC/cloudfire#1542]
**Is your feature request related to a problem? Please describe.**
There is no problem.  This is a feature request.
If there is only one sign-in option left (e.g., SAML is the only option left after disabling login via email and password), hide the text label that says: "Please sign in via one of the methods below.".

The `<h3>` that says "Sign In" might also not be needed if there is only one option left as well.

**Describe the solution you'd like**
In case there is only one sign-in option left, the login may no longer need the h3 for "Sign In" as well as the prompt to select a login option.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by jamilbk** [comment]
Thanks for the request @bensonrlee. We're doing some major reworking of auth and may not be able to get to this soon. Will keep this open to track.

**Comment by bensonrlee** [comment]
@jamilbk Absolutely not an issue.  It is nothing more than nice to have in terms of aesthetics.  Auths fixes / new features should definitely be much higher on the priority list.

**Comment by jamilbk** [comment]
This has changed slightly in 1.0 and may no longer be an issue, but if it is, we can reopen this issue.
