### ISSUE TITLE
In dark mode "Contact support" from levels are not visible

### ISSUE THREAD

**Issue by sajdakabir** [CloudFire-LLC/cloudfire#1546]
**Describe the bug**
In light mode Levels name are visible:

![light-mode](https://user-images.githubusercontent.com/86569763/230758732-f6a8d24f-44a9-421e-b2c8-745b291e83b2.jpeg)

Dake mode:
![dark-mode](https://user-images.githubusercontent.com/86569763/230758748-07e3bd2f-aea0-4054-a0a2-f3d1a11591c9.jpeg)

**Expected behavior**
Users can see the levels.

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12]
 - OS: [e.g. Linux]
 - Distro: [e.g. Ubuntu 18.04]
 - Kernel version: [e.g. 5.10.11]
 - Deployment method: [e.g. Docker / Omnibus / Source]

**Additional context**

**Comment by sajdakabir** [comment]
Hey @AndrewDryga , I would like to work on this issue. Please Assign it to me.

**Comment by jamilbk** [comment]
@sajdakabir Thanks for the report and offer to help! Feel free to give it a shot, but this form is pulled in from HubSpot and may need to be updated there. Let me know if you're not able to make the necessary changes.

**Comment by sajdakabir** [comment]
Hey @jamilbk , You have to change it from HubSpot. I tried but I can't make the changes.

**Comment by jamilbk** [comment]
Ok will look into it. Maybe for now it's quickest just to add a background to the containing `<div>` that stays white independent of the light/dark mode switch.
