### ISSUE TITLE
Using CLI to generate API token causes crash

### ISSUE THREAD

**Issue by med-94** [CloudFire-LLC/cloudfire#1552]
**Describe the bug**
When generating an API token from the CLI using `docker compose -f <COMPOSE_FILE> exec firezone bin/create-api-token` no API token is generated and the firezone container crashes.

**To Reproduce**
Run `docker compose -f <COMPOSE_FILE> exec firezone bin/create-api-token`

**Expected behavior**
An API token to be generated and the firezone container to not crash.

**Screenshots / Logs**
```
[root@xxxxx ~]# docker-compose -f /etc/firezone/docker-compose.yaml exec firezone bin/create-api-token
[root@xxxxx ~]# echo $?
137
```

There are no error logs from the firezone container while running:
```
firezone_1  | 2023-04-12T08:15:35.420804400Z 08:15:35.420 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.522.0> request_id=F1Uh7Hi3juToyxgAAADh [info] Sent 200 in 6ms
<CONTAINER RESTARTS>
firezone_1  | Creating WireGuard interface wg-firezone
```

**Platform (please complete the following information):**
 - Firezone Version: 0.7.25
 - OS: Linux
 - Distro: Rocky Linux 9.1
 - Kernel version: 5.14.0-162.12.1.el9_1.0.2.x86_64
 - Deployment method: Docker

**Additional context**
We have an integration with an OIDC provider enabled and local auth disabled.

**Comment by jamilbk** [comment]
Thanks for the report! Can you confirm whether you have at least one admin user created?

**Comment by med-94** [comment]
Hi @jamilbk, yes, we have a few admin users (including the one created with the default admin email we set).

**Comment by AndrewDryga** [comment]
@med-94 I can not reproduce it, is there any chance that you have very low resource limits (most likely, RAM limit) for a container and it is restarted because it's out of memory?

**Comment by med-94** [comment]
@AndrewDryga Good idea, checking I can see the container is getting oom killed:
```
[  +0.020870] Out of memory: Killed process 52865 (beam.smp) total-vm:3264408kB, anon-rss:1614668kB, file-rss:0kB, shmem-rss:35076kB, UID:0 pgtables:3376kB oom_score_adj:0
```

We do not have any limits set on the containers and Firezone is the only thing running on node with around 4G memory.

I have also experienced the general high memory usage reported at https://github.com/firezone/firezone/issues/1445 - with my Firezone container using 1.5GiB memory in normal operations (with only a couple of testing users on it)

**Comment by jamilbk** [comment]
@med-94 Unfortunately we haven't been able to reproduce the high-memory situation you're hitting. If you're able to create a minimal project on GitHub to demonstrate the issue (e.g. Vagrantfile) we can take a deeper look. Closing as a dupe of https://github.com/firezone/firezone/issues/1445
