### ISSUE TITLE
Endpoint value in device details is incorrect

### ISSUE THREAD

**Issue by vikrtd** [CloudFire-LLC/cloudfire#1556]
**Describe the bug**

When default endpoint is set, the endpoint value in device details shows has extra port. This is a cosmetic issue, no functionality is affected.

**Expected behavior**

Current behaviour
Endpoint: `vpn.<mydomain>.com:500:51820`

Expected
Endpoint: `vpn.<mydomain>.com:500`

**Screenshots / Logs**

<img width="665" alt="Screenshot 2023-04-16 at 4 10 01 PM" src="https://user-images.githubusercontent.com/2617961/232348276-452b9c19-60db-4c66-a261-ab1d9d9399a6.png">

<img width="531" alt="Screenshot 2023-04-16 at 4 06 34 PM" src="https://user-images.githubusercontent.com/2617961/232348133-4fce2d5f-81fa-4ce9-b807-6f5540507726.png">

**Platform (please complete the following information):**
 - Firezone Version [Version 0.7.25](https://github.com/firezone/firezone/tree/refs/tags/0.7.25)
 - Deployment method: Docker

**Comment by jamilbk** [comment]
Thanks for the report! Will get started on a fix.
