### ISSUE TITLE
Implement the ability to add OpenID provider configuration through environment variables

### ISSUE THREAD

**Issue by pdoninv** [CloudFire-LLC/cloudfire#1561]
**Is your feature request related to a problem? Please describe.**
To fully automate the deployment of Firezone, we lack the ability to pass the OpenID provider parameters (scope, client id, client secret, etc.) to the application.

**Describe the solution you'd like.**
Passing OpenID provider parameters (and may be other providers) via environment variables.

**Comment by AndrewDryga** [comment]
Hello. There is a way to do it: https://www.firezone.dev/docs/reference/env-vars/#authorization

**Comment by pdoninv** [comment]
Big thanx!
