### ISSUE TITLE
Allow overide of OIDC 'email' scope requirement (support Authgear)

### ISSUE THREAD

**Issue by xAiluros** [CloudFire-LLC/cloudfire#1572]
**Is your feature request related to a problem? Please describe.**
Tried to connect Authgear.com OIDC. However, the requirement of having `email` in scope seems to block it.
In their docs:

"OpenID Scope: Space separated list of scopes the plugin could access.
* Example: openid offline_access https://authgear.com/scopes/full-userinfo.
* https://authgear.com/scopes/full-userinfo is needed to obtain user's profile (e.g. email). Otherwise the plugin will be able to get the user id only."

So first thing I tried was having both `email` and `https://authgear.com/scopes/full-userinfo` scopes, but this fails because `email` scope is not supported on Authgear end. I don't know that much about OIDC, from what I see compared to other IDP's it's weird they don't support email scope? 

**Describe the solution you'd like**
It would be nice if the requirement of `email` scope in configuration page, can be overridden. So for example the user is warned, but can freely remove email scope and add another. Of course at their own risk of breaking things.

**Describe alternatives you've considered**
Should maybe ask Authgear why no email scope. I've searched docs and didn't find it quickly.

**Additional context**
Just commenting out the validation made it possible to connect Authgear. Of course for the most part it would be good if scope is checked, so therefore the idea of maybe making it a warning / possible to override for the user.

```
diff --git a/apps/fz_http/lib/fz_http/config/configuration/openid_connect_provider.ex b/apps/fz_http/lib/fz_http/config/configuration/openid_connect_provider.ex
index d9273186..002e525f 100644
--- a/apps/fz_http/lib/fz_http/config/configuration/openid_connect_provider.ex
+++ b/apps/fz_http/lib/fz_http/config/configuration/openid_connect_provider.ex
@@ -62,7 +62,7 @@ defmodule FzHttp.Config.Configuration.OpenIDConnectProvider do
     |> Validator.validate_uri(:redirect_uri)
     |> validate_inclusion(:response_type, ~w[code])
     |> validate_format(:scope, ~r/openid/, message: "must include openid scope")
-    |> validate_format(:scope, ~r/email/, message: "must include email scope")
+    #|> validate_format(:scope, ~r/email/, message: "must include email scope")
   end
 
   def validate_discovery_document_uri(changeset) do
```

**Comment by jamilbk** [comment]
Very strange that Authgear does not support the `email` scope and seems to have chosen such an esoteric way to retrieve a user's email via the returned claims.

Making the `email` scope optional in Firezone would require a huge refactor and probably isn't worth the hassle to support edge cases like this. Users need an email in Firezone; we won't be able to relax this requirement any time soon most likely.

**Comment by xAiluros** [comment]
Clear that users need an e-mail so it needs to be present. But in this case it is present, it's just included via different scope than `email`. 
That's why it works when only commenting out the validation.

I understand if Authgear is the one doing something unusual that it may not be worth the effort to change something in Firezone. But it wouldn't require a big refactor just to fix this case (see commenting out validation) :)

In any case I've opened an issue with their project: https://github.com/authgear/authgear-server/issues/3048
Perhaps it will be changed there :)

**Comment by jamilbk** [comment]
@xAiluros I see -- so the user's email is present in the `email` claim within the returned ID token from Authgear?

That should be a bit simpler to fix (as you've noted), but it does feel like specifying the `email` scope should well, request the user's email.

In any case will defer to @AndrewDryga to decide what to do but we'll probably hold off for now.

**Comment by xAiluros** [comment]
> @xAiluros I see -- so the user's email is present in the `email` claim within the returned ID token from Authgear?

Yes indeed `email` claim is present (when I specify their `https://authgear.com/scopes/full-userinfo` scope)
