### ISSUE TITLE
okta docs outdated - Discovery Document URI missing

### ISSUE THREAD

**Issue by marafa-sugarcrm** [CloudFire-LLC/cloudfire#1574]
**Describe the bug**
- [ ]  https://www.firezone.dev/docs/authenticate/oidc/okta/ has no mention of  `Discovery Document URI` which should be `https://${yourOktaDomain}/.well-known/openid-configuration`
- [ ]  also RedirectURI in the docs say to use `okta` .. current version says to use the `Config ID`

 **To Reproduce**
configure okta as per https://www.firezone.dev/docs/authenticate/oidc/okta/ 

**Expected behavior**
docs should not skip steps nor leave out anything

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12]
 - OS: [e.g. Linux]
 - Distro: [e.g. Ubuntu 18.04]
 - Kernel version: [e.g. 5.10.11]
 - Deployment method: [e.g. Docker / Omnibus / Source]

**Additional context**

**Comment by jamilbk** [comment]
Hi there, thanks for the report. However, I'm a bit confused -- `Discovery Document URI` is item #7 at the top of that page:

<img width="841" alt="Screenshot 2023-04-26 at 1 53 07 PM" src="https://user-images.githubusercontent.com/167144/234699782-0078d7ff-a9fb-410f-ab47-c36789715e4c.png">

Also, `okta` is used as the config ID on that page, so they're actually the same. This is noted like so:

> Add your Firezone EXTERNAL_URL + /auth/oidc/<Config ID>/callback/ (e.g. https://firezone.example.com/auth/oidc/okta/callback/) as an entry to Authorized redirect URIs.

Could you clarify which parts were not clear?

**Comment by marafa-sugarcrm** [comment]
👓 i see the discovery document url now. 
still can. you add the URL format to the doc too? it will help a bit. took a little bit of digging to get the format for me.

the other item still holds.  for Config ID

thank you

**Comment by jamilbk** [comment]
Noted, will add to backlog. Alternatively, we welcome PRs if you'd like to contribute the necessary changes.

Could you elaborate a little more about the config ID? `okta` is the example config ID used in the documentation, hence the `e.g.` signifier.
