### ISSUE TITLE
dead doc link in web ui footer

### ISSUE THREAD

**Issue by marafa-sugarcrm** [CloudFire-LLC/cloudfire#1575]
**Describe the bug**
in the footer of each page is a link that says 0.7.0 is here! [Click here to read more.](https://www.firezone.dev/release-0-7-0/?utm_source=product&uid=5a485853-edd5-4ec1-93e5-385b281ece71)

that is a dead link

**To Reproduce**

**Expected behavior**

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.
![Screenshot 2023-04-27 at 7 56 08 AM](https://user-images.githubusercontent.com/69474017/234854602-3634b597-bbfc-48ba-88c6-e2bfa8e775f4.png)

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12]
 - OS: [e.g. Linux]
 - Distro: [e.g. Ubuntu 18.04]
 - Kernel version: [e.g. 5.10.11]
 - Deployment method: [e.g. Docker / Omnibus / Source]

**Additional context**

**Comment by jamilbk** [comment]
Will be fixed in 0.7.27
