### ISSUE TITLE
Limit the number of device a user can add

### ISSUE THREAD

**Issue by alpacaccp** [CloudFire-LLC/cloudfire#1584]
**First a huge thank to the dev team for creating such a great open source project.** 

Firezone might be able to use for kind of decentralized VPN to crack China's GFW if lots of residential users share their VPN with little costs.

But to prevent abuse, if we can set a limit on the devices a user can add in Admin panel, such as 5, so any user can only add 5 devices at most.

It seems that users can add unlimited devices at the moment if we allow unpriviledged device management.

![Screenshot 2023-05-02 194557](https://user-images.githubusercontent.com/120345873/235634462-727ffe29-f7c3-4cd8-8e45-149e86ba7423.png)

**Comment by jamilbk** [comment]
Hmm, you should be able to set `MAX_DEVICES_PER_USER=5` in your `.env`. Not sure why it's missing from the docs, @andrewdryga? Let us know if that doesn't work.

**Comment by AndrewDryga** [comment]
@jamilbk I think I just forgot to uncomment that docs section, but it should work just fine (there is a test for it).

**Comment by alpacaccp** [comment]
Wonderful!!! I'll check it.

I love you guys @jamilbk  @AndrewDryga

**Comment by alpacaccp** [comment]
> Hmm, you should be able to set `MAX_DEVICES_PER_USER=5` in your `.env`. Not sure why it's missing from the docs, @AndrewDryga? Let us know if that doesn't work.

Hi @jamilbk, I added `MAX_DEVICES_PER_USER=5` to the end of $HOME/.firezone/.env it doesn't work.

This should be [Runtime configuration](https://www.firezone.dev/docs/deploy/configure/#runtime-configuration) and no need to restart the docker service, but it still doesn't work after restarting. Could you please have a look? Thanks.

**Comment by AndrewDryga** [comment]
@alpacaccp you do need to restart the Firezone when you change environment variables, they are not part of the runtime configuration. Please run following commands while Firezone is running to verify the configuration was applied:
```
docker exec -it firezone-firezone-1 sh
bin/firezone remote
FzHttp.Config.fetch_env!(:fz_http, :max_devices_per_user)
FzHttp.Devices.count_maximum_for_a_user()
```

Please note that if devices were created over the limit before you changed the configuration, they will remain active.

**Comment by alpacaccp** [comment]
@jamilbk @AndrewDryga Sorry I had problem with my NAS yesterday and didn't have chance to test.

It looks like the MAX_DEVICES_PER_USER has not affect in .env

Please have a look at the screenshot. I only added 1 device for testing.
docker restarted 3 containers, and Debian 11 host has been rebooted as well.

<img width="655" alt="Screen Shot 2023-05-05 at 8 12 26 pm" src="https://user-images.githubusercontent.com/120345873/236432443-f6bc00d9-e407-40a2-89d2-fb55cb40012c.png">

**Comment by alpacaccp** [comment]
It seems that I can't change closed issue to open. I'll start a new bug.

**Comment by itsazzad** [comment]
@AndrewDryga Is there any way to have more than 100 devices per user?
https://github.com/firezone/firezone/issues/2323

**Comment by AndrewDryga** [comment]
@itsazzad you can fork the repo from the `legacy` branch, change it in the source code, and build your own container. That is the only way for now.
