### ISSUE TITLE
MAX_DEVICES_PER_USER has not affect in .env

### ISSUE THREAD

**Issue by alpacaccp** [CloudFire-LLC/cloudfire#1593]
@jamilbk @AndrewDryga Sorry I had problem with my NAS yesterday and didn't have chance to test.

**Describe the bug**
MAX_DEVICES_PER_USER=2 in ~/.firezone/.env not working

**To Reproduce**
1. fresh Debian 11 install
2. Docker deployment from firezone offical script
3. add MAX_DEVICES_PER_USER=2 at the end of ~/.firezone/.env 
4. restart docker all containers, user can still add more devices
5. reboot Debian host, user can still add more devices

**Expected behavior**
User can only add 2 devices

**Screenshots / Logs**

<img width="655" alt="Screen Shot 2023-05-05 at 8 12 26 pm" src="https://user-images.githubusercontent.com/120345873/236432443-f6bc00d9-e407-40a2-89d2-fb55cb40012c.png">

**Platform (please complete the following information):**
 - Firezone Version latest
 - OS: Linux

**Comment by jamilbk** [comment]
Please avoid opening duplicate issues as it makes it harder for us to respond to them.

This was merged yesterday should be in the 0.7.28 release I just cut.

#1584
