### ISSUE TITLE
Privacy protection for end user - access logs only record partial IP address

### ISSUE THREAD

**Issue by alpacaccp** [CloudFire-LLC/cloudfire#1594]
**Is your feature request related to a problem? Please describe.**
There is no problem and it's just a feature request.

**Describe the solution you'd like**
Use case: to give the end users peace of mind that the VPN server is not recording their IP address just for  privacy reason.
the access logs have only partial IP address recorded. For example, if the user's IP address is 8.8.8.8, it only saved in syslog or log file as 8.8.x.x

After enabling this feature, this partial IP is clearly displayed when user logs into web portal.

**Describe alternatives you've considered**
When the feature enabled, the server doesn't save access logs at all.

It would be even better if there is a fingerprint of the source code to show the offical firezone code hasn't been modified inside the docker container. It's all about privacy and prevent phishing/evil parties to misused firezone.

Hope this make sense.

**Comment by Jim-Young** [comment]
@jamilbk Sorry to bother you. Just want to ask if you have any plan to implement this feature in the near future, if not, would you please point out where should I start to look at to contribute.

I don't see the dev docs in your website. I had a look at the Contributing.MD page but it's only for the development environment. Where should I start from if I'm not familiar with  Elixir? Thanks

**Comment by jamilbk** [comment]
@Jim-Young Firezone doesn’t save any WireGuard access logs. We’re just a layer on top that orchestrates the kernel module.

As such we have no control over WireGuard’s logging mechanism — you would have more luck configuring your kernel to silence WireGuard messages so they don’t end up on disk, or using a readonly filesystem. I would start poking at dmesg configuration or journalctl.

**Comment by Jim-Young** [comment]
OK, thanks for pointing out.
