### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by Busurman83** [CloudFire-LLC/cloudfire#1607]
**Describe the bug**
Constantly falls and starts the container with firezone

**To reproduce**
Installed the system using a script from the site
bash <(curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh)

**Expected behavior**
expected to get access to the web interface for further configuration

**Screenshots/Logs**
`Crash dump is being written to: erl_crash.dump...done
Creating WireGuard interface wg-firezone
Adding route 100.64.0.0/10 for interface wg-firezone
Adding route fd00::/106 for interface wg-firezone
15:49:57.603 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=log/2 line=707 mfa=Ecto.Migrator.log/2 module=Ecto.Migrator pid=<0.95.0> [info] Migrations already up
15:50:01.124 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/cowboy2_adapter.ex function=start_link/3 line=103 mfa=Phoenix.Endpoint.Cowboy2Adapter.start_link/3 module=Phoenix.Endpoint.Cowboy2Adapter pid=<0.360.0> [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
15:50:01.152 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/supervisor.ex function=log_access_url/2 line=425 mfa=Phoenix.Endpoint.Supervisor.log_access_url/2 module=Phoenix.Endpoint.Supervisor pid=<0.331.0> [info] Access FzHttpWeb.Endpoint at https://vpn.vacad.ru
15:50:01.272 erl_level=notice domain=otp file=application_controller.erl function=info_exited/3 line=2119 mfa=:application_controller.info_exited/3 module=application_controller pid=<0.44.0> [notice] Application fz_wall exited: FzWall.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzWall.Server
    ** (EXIT) an exception was raised:
        ** (RuntimeError)   Unknown Error from command nft list table inet firezone. Error:

            (fz_wall 0.7.29) lib/fz_wall/cli/helpers/nft.ex:188: FzWall.CLI.Helpers.Nft.table_exists?/0
            (fz_wall 0.7.29) lib/fz_wall/cli/helpers/nft.ex:168: FzWall.CLI.Helpers.Nft.teardown_table/0
            (fz_wall 0.7.29) lib/fz_wall/cli/live.ex:15: FzWall.CLI.Live.setup_firewall/0
            (fz_wall 0.7.29) lib/fz_wall/server.ex:16: FzWall.Server.init/1
            (stdlib 4.2) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.2) gen_server.erl:814: :gen_server.init_it/6
            (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"  Unknown Error from command nft list table inet firezone. Error:\n  \n\">>},[{'Elixir.FzWall.CLI.Helpers.Nft','table_exists?',0,[{file,\"lib/fz_wall/cli/helpers/nft.ex\"},{line,188},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzWall.CLI.Helpers.Nft',teardown_table,0,[{file,\"lib/fz_wall/cli/helpers/nft.ex\"},{line,168}]},{'Elixir.FzWall.CLI.Live',setup_firewall,0,[{file,\"lib/fz_wall/cli/live.ex\"},{line,15}]},{'Elixir.FzWall.Server',init,1,[{file,\"lib/fz_wall/server.ex\"},{line,16}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"  Unknown Error from command nft list table inet firezone. Error:\n  \n">>},[{'Elixir.FzWall.CLI.Helpers.Nft','table_exists?',0,[{file,"lib/fz_wall/cli/helpers/nft.ex"},{line,188},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzWall.CLI.Helpers.Nft',teardown_table,0,[{file,"lib/fz_wall/cli/helpers/nft.ex"},{line,168}]},{'Elixir.FzWall.CLI.Live',setup_firewall,0,[{file,"lib/fz_wall/cli/live.ex"},{line,15}]},{'Elixir.FzWall.Server',init,1,[{file,"lib/fz_wall/server.ex"},{line,16}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,851}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}})

Crash dump is being written to: erl_crash.dump...done
`
[https://disk.yandex.ru/i/7LLiXWyc2BPP1g](url)

**Platform (please complete the following information):**
  - Firezone Version [e.g. 0.7.29]
  - OS: Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-210-generic x86_64)
  - Deployment method: Docker

**Comment by jamilbk** [comment]
Thanks for the report. Your kernel is too old — we recommend upgrading to 5.6+ and that should fix the issue.
