### ISSUE TITLE
SSO OIDC Compatibility Issue with Duo Security

### ISSUE THREAD

**Issue by washcroft** [CloudFire-LLC/cloudfire#1608]
**Describe the bug**
Using Duo Security as an OIDC provider in Firezone doesn't seem to work / isn't compatible. After Duo authentication, the redirect back to Firezone displays the login screen again with an error message (see below).

**To Reproduce**

- Setup Duo Security as an OIDC provider in Firezone
- Login using SSO

**Expected behavior**

Login succeeds

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

`An OpenIDConnect error occurred. Details: {400, "{\"error_title\": \"invalid_request\", \"error_message\": \"Request was malformed\", \"error\": \"invalid_request\", \"error_description\": \"Request was malformed\"}"}`

**Platform (please complete the following information):**
 - Firezone Version 0.7.29
 - OS: Linux
 - Distro: Debian Bullseye
 - Kernel version: 5.10.0-22
 - Deployment method: Docker

**Additional context**

**Comment by jamilbk** [comment]
Thanks for the report! This is a new one. I know we've had success with Duo in the past, so not sure what happened. We're spread thin at the moment probably won't have time to triage soon, but will keep open for when we do.

**Comment by jamilbk** [comment]
In the meantime, you may have more luck with SAML: https://duo.com/docs/sso-generic

**Comment by washcroft** [comment]
> In the meantime, you may have more luck with SAML: https://duo.com/docs/sso-generic

SAML working fine, thanks
