### ISSUE TITLE
Enable "branch must be update to date before merging"

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#1616]
We just had a semantic conflict between https://github.com/firezone/firezone/pull/1610 and https://github.com/firezone/firezone/pull/1613 that results in a broken state on the `cloud` branch.

Can we enable the merge requirement mentioned in the title? That would have surfaced this in one of the two PRs.

**Comment by jamilbk** [comment]
Sure. Looks like I need to require status checks to enable the feature (did GH change this recently? I dont recall this being the case before)

**Comment by jamilbk** [comment]
That should hopefully take care of it.
![IMG_2313](https://github.com/firezone/firezone/assets/167144/d9446701-05bb-4326-87f3-7ac2c9dddfea)

**Comment by thomaseizinger** [comment]
> That should hopefully take care of it.
> ![IMG_2313](https://github.com/firezone/firezone/assets/167144/d9446701-05bb-4326-87f3-7ac2c9dddfea)
> 
> 

I think that was a bit too restrictive because we just disabled the jobs 😬

See https://github.com/firezone/firezone/pull/1618.

**Comment by jamilbk** [comment]
I believe this is completed -- feel free to reopen if it still needs addressing
