### ISSUE TITLE
Feature request: Support editing device details

### ISSUE THREAD

**Issue by DvdGiessen** [CloudFire-LLC/cloudfire#1624]
## The problem
Once a device has been created, its details cannot be edited anymore. The reasoning behind this was mentioned in  #1428: There is no way to get an updated config to the user after they downloaded it.

However, I see two potential use cases where editing the details do make sense:
- 1: Editing details that don't end up in the client configuration, like the name and description.
- 2 & 3: Editing other details because it's a lot less work to change them than to set up a new configuration.

## Use cases
Use case 1 is to change the name or description of a device purely for the purpose of keeping track of it in Firezone. For example:
- A user with a new phone may want to add it, and want to change the description of the old phone from "Phone" to something more descriptive.
- The description a user originally entered wasn't to their liking, and they would like to change it without going through the process of deleting the old config and setting up a new configuration.

Use case 2 & 3 are to edit details that did end up in the client configuration. There are two cases here:
- 2: Details that are also used on the server side, for example the IP or keys.
- ~3: Details that are not actually used on the server side but only in the client config like the DNS, client allowed IP's.~

These have different reasons for wanting to change details:
- In case 2 this is for technical reasons. For example rotate a leaked key, or to swap IP's between two machines instead of having to update all the places these IP's may be hardcoded.
  - Note this is the only case where we will have to do more than just editing the details stored in the database; the changes would also need to be applied to the server Wireguard interface configuration.
- ~In case 3 this is solely so they accurately reflect what is configured on the client. For example, I generated the config with allowedips = 0.0.0.0/0, but now I actually edited it on my client to only allow a specific subrange. Or the DNS server changed, and this was also edited in the client config, but in Firezone it's still showing the old DNS IP.~
  - ~This doesn't accomplish anything technical (only editing the client config matters, what Firezone says isn't actually used anywhere), but people might still prefer to edit this to help with their bookkeeping or just to be able to soothe their OCD. :)~

### Why edit instead of regenerating the entire configuration?
The reason that in case 2 ~and 3~ it might be preferred to edit instead of creating a new configuration is because it's easier when the configuration cannot simply be copy-pasted, for example because the configuration format isn't the same (Wireguard configured via networkctl/systemd which uses a different config format) or because it's on a physically separate system (and they would prefer to not type over newly generated keys but just change this one small thing instead).

## Implementation separability
These three use cases apply to distinct sets of device details, and thus not all of them have to be implemented. ~Use case 1 and 3 are technically similar enough I think, meaning that if one is implemented the other is quite trivial to do too.~ Use case 2 requires a bit more work because as noted it changes details that are actually used and thus need an extra call to re-apply them to the interface.

## Discussion
I'd argue that use case 1 is fairly simple and straightforward, and probably won't have many opponents.

Whether use cases 2 ~and 3~ are implemented could be a bit more contentious, seeing as they depend on how one thinks the user experience should work. They add a little bit of complexity. They make things easier for end users and administrators for the reasons mentioned above, but also in some cases more difficult because now in their mental model of the system have to consider the fact things may have been edited, adding more potential opportunities for human failure. Personally I think the added ease outweighs those downsides, but that's heavily biassed by my own use cases where both users and admins are generally knowledgeable enough about these systems and would prefer having the power user ability to edit things.

EDIT: I only just realized that case 3 doesn't really make that much sense, since we're not actually storing these fields per device, but only showing the defaults there. My mistake. Edited the above to cross them out.

**Comment by jamilbk** [comment]
Thanks for the request! Things are changing a lot at the moment in this arena, and we're spread thin working towards the 1.0 release. I'll add this issue to that milestone, but I do think 1.0 should solve the use case you're after.

**Comment by jamilbk** [comment]
Client configurations are going away in favor of our own custom clients in 1.0. Clients will then be ephemeral to a certain degree in the portal. Device details for authenticated users will show up automatically in the portal, so I'm not sure this issue will be relevant. Peer IPs will also be managed for you automatically, so renumbering won't be a thing.

I'll close this for now, but can re-open if there's still value in adding metadata to clients in the portal.

**Comment by jamilbk** [comment]
![](https://share.balsamiq.com/c/2kW4C1yGreLpbesPoYKqNt.png)

**Comment by DvdGiessen** [comment]
That makes sense in context of devices becoming ephemeral. Presumably the ability to add metadata, to for example annotate devices to be able to recognize them better or mark them as an admin might be useful in the future still.

Those changes also means I'll keep continue using a fork of pre-1.0 Firezone, because being configuration-file based is one of our primary reasons for using Firezone and custom clients won't work for some of our use cases. But that is out of scope for this issue.
