### ISSUE TITLE
How can i find the `log_directory`?

### ISSUE THREAD

**Issue by T-baby** [CloudFire-LLC/cloudfire#1632]
I deployed the firezone using docker-compose and I was hoping to find the file with the wireguard related log output, but I didn't find it in the container.

I would like to find wireguard related logs and firezone related logs.

**Comment by jamilbk** [comment]
Hi @T-baby -- Firezone doesn't interfere or intercept `wireguard` kernel logs, so whatever techniques you use for standard kernel logging (dmesg etc) would work here.

Possible dupe of https://github.com/firezone/firezone/issues/1594
