### ISSUE TITLE
HTTP_CLIENT_SSL_OPTS removed from documentation

### ISSUE THREAD

**Issue by hmhackmaster** [CloudFire-LLC/cloudfire#1635]
I created a thread on Discourse a while ago (https://discourse.firez.one/t/using-adfs-with-internal-ca-certificate-for-oidc/202) regarding SSL cert trust issues when using an non-publicly-trusted CA which resulted in #996 being opened and PR #1221 being merged to add the `HTTP_CLIENT_SSL_OPTS` variable. 

When I went to switch over to Docker, I decided to perform a clean-reinstall and set up Firezone from scratch. 

The current Docs page (https://www.firezone.dev/docs/reference/env-vars/) does not currently reference the `HTTP_CLIENT_SSL_OPTS` variable, though the variable does work as expected.

Based on what I can tell from the commit history, it looks like #1352 is what removed that variable (and potentially others, the commit is huge) from the documentation. 

While it does work today, is the `HTTP_CLIENT_SSL_OPTS` variable still supported or was it removed from the docs as its functionality is expected to be removed at some point? 
If it is supported, should the variable (and potentially whatever other ones were removed) be re-added to the docs page?

Thanks so much!

**Comment by jamilbk** [comment]
Thanks for the report! Hmm, I believe that variable should be in the docs. Our env var docs are automagically generated from [this file](https://github.com/firezone/firezone/blob/98585e1592def21955f29f29cba7b7667dc4897e/apps/fz_http/lib/fz_http/config/definitions.ex#L723) so there must be some bug causing them to be omitted from the generated Markdown.

We're completing overhauling the documentation as part of #1629 and so it may be some time before this is resolved.

**Comment by jamilbk** [comment]
This will be largely irrelevant with 1.0 and the cloud-managed web portal. Documentation is being overhauled as well for 1.0, so I'll close this for now and reopen if it's still needed for 1.0.

**Comment by jamilbk** [comment]
Ah, nevermind, it looks like the docs were already fixed: https://www.firezone.dev/docs/reference/env-vars#webserver
