### ISSUE TITLE
sqlite (or externally-hosted Postgres) support

### ISSUE THREAD

**Issue by Nezteb** [CloudFire-LLC/cloudfire#1639]
**Is your feature request related to a problem? Please describe.**
I run Firezone on a pretty small cloud VPS, and running Postgres alongside Caddy and Firezone sometimes brings the VPS to its knees. 

**Describe the solution you'd like**

It'd be nice to be able to swap out Postgres for sqlite, which is much less resource-intensive. This could even be a prompt during the auto-install script.

Combing through Firezone's dependencies and DB usage I don't see anything obvious that would invalidate sqlite as a database option, though I could easily be wrong.

As an example, [sqlite supports `FOR EACH ROW` triggers](https://github.com/firezone/firezone/blob/98585e1592def21955f29f29cba7b7667dc4897e/apps/fz_http/priv/repo/migrations/20220721164925_add_device_rule_user_notify_triggers.exs#LL37C7-L37C19).

**Describe alternatives you've considered**

If sqlite isn't doable for some reason, another option would be to support any externally-hosted Postgres instance, such as:
- https://www.elephantsql.com
- https://neon.tech
- https://electric-sql.com

**Comment by jamilbk** [comment]
Hi @Nezteb, we probably won’t be able to support sqlite any time soon, but you should be able to use an external DB:

https://www.firezone.dev/docs/deploy/advanced/external-database/#compatibility
