### ISSUE TITLE
Set user valid period when creating a new user

### ISSUE THREAD

**Issue by Jim-Young** [CloudFire-LLC/cloudfire#1645]
**Is your feature request related to a problem? Please describe.**
**Case 1:** You want this user only valid for 6 months when you have a new contractor in your team working for only 6 months. It should be automatically disabled after 6 months
**Case 2:** If you want to sell your VPN service, you want to be able to set a fixed time when adding the user, for instance, 1 day, 1 week or 1 month.

**Describe the solution you'd like**
On the Web UI, when you add a new user, you can define how long the user can last.

**Describe alternatives you've considered**
The user will be activated after the first login and timer starts from there, or when the first VPN connection is established.

**Additional context**
NONE.

**Comment by jamilbk** [comment]
@Jim-Young Thanks for the request!

We're moving towards shifting all user authentication responsibilities to the IdP, and I believe this would fall under that domain. So I don't think we'll have this functionality in Firezone per se.
