### ISSUE TITLE
[API] Disable VPN connection via REST API

### ISSUE THREAD

**Issue by hatkidchan** [CloudFire-LLC/cloudfire#1647]
**Is your feature request related to a problem? Please describe.**
I want to be able to disable users ability to connect to our VPN via REST API. That could be quite useful when adding custom rules and quotas. One use-case I have in mind right now is to disable user when we disable it in our SSO. Currently it is not possible and user still remains connected even after it's being disabled here.

**Describe the solution you'd like**
API endpoint that allows to toggle this little thing:
![image](https://github.com/firezone/firezone/assets/35804000/9973e3f8-51cc-4077-b5b3-19c5b25ddb34)

**Describe alternatives you've considered**
Reverse-engineering how it does via web interface?

**Comment by jamilbk** [comment]
Thanks for the feature request! Setting `disabled_at` will disable the user's VPN, but like you noticed, this is not possible via API.

We're refactoring a bunch of things at the moment, so may not get to this soon, but will keep this open to track.

Are you looking for something like SCIM 2.0 to deprovision the user upon being disabled by your IdP?

**Comment by hatkidchan** [comment]
> Thanks for the feature request! Setting `disabled_at` will disable the user's VPN, but like you noticed, this is not possible via API.
> 
> We're refactoring a bunch of things at the moment, so may not get to this soon, but will keep this open to track.
> 
> Are you looking for something like SCIM 2.0 to deprovision the user upon being disabled by your IdP?

I guess? I'm looking for a way to temporarily disable users' connection whenever we disable its account in Keycloak.

**Comment by jamilbk** [comment]
@hatkidchan I see, sorry for the late reply here. We will support this automatically via directory sync (e.g. 
SCIM) in 1.0. But I don't think Keycloak supports directory sync, so there'll be a mechanism to provision/deprovision via the REST API in 1.0.

**Comment by jamilbk** [comment]
This won't be relevant anymore with the changes coming in 1.0. You'll be able to disable Users which should have the intended effect.

cc @AndrewDryga
