### ISSUE TITLE
Caddy doesn't work as shipped

### ISSUE THREAD

**Issue by ivdok** [CloudFire-LLC/cloudfire#1650]
**Describe the bug**
After deploying docker-compose, caddy reverse proxy fails to serve traffic on both HTTPS and HTTP endpoints.
**To Reproduce**
    Download the docker compose template to a local working directory: 
    > curl -fsSL https://raw.githubusercontent.com/firezone/firezone/master/docker-compose.prod.yml -o docker-compose.yml
    Generate required secrets:
    > docker run --rm firezone/firezone bin/gen-env > .env
    At a minimum, change the DEFAULT_ADMIN_EMAIL and EXTERNAL_URL variables. Optionally modify other secrets as needed.
    Migrate the database:
    > docker compose run --rm firezone bin/migrate
    Create the first admin:
    > docker compose run --rm firezone bin/create-or-reset-admin
    Bring the services up: docker compose up -d

**Expected behavior**
You should now be able to access the Firezone web portal at the EXTERNAL_URL variable you defined above.

**Screenshots / Logs**
wireguard-firezone-1  | Creating WireGuard interface wg-firezone
wireguard-firezone-1  | Adding route 100.64.0.0/10 for interface wg-firezone
wireguard-firezone-1  | Adding route fd00::/106 for interface wg-firezone
wireguard-firezone-1  | 16:58:21.473 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=log/2 line=707 mfa=Ecto.Migrator.log/2 module=Ecto.Migrator pid=<0.95.0> [info] Migrations already up
wireguard-firezone-1  | 16:58:23.317 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/cowboy2_adapter.ex function=start_link/3 line=103 mfa=Phoenix.Endpoint.Cowboy2Adapter.start_link/3 module=Phoenix.Endpoint.Cowboy2Adapter pid=<0.360.0> [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
wireguard-firezone-1  | 16:58:23.326 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/supervisor.ex function=log_access_url/2 line=425 mfa=Phoenix.Endpoint.Supervisor.log_access_url/2 module=Phoenix.Endpoint.Supervisor pid=<0.331.0> [info] Access FzHttpWeb.Endpoint at https://vpn.organization.tld
wireguard-postgres-1  | 
wireguard-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
wireguard-postgres-1  | 
wireguard-postgres-1  | 2023-06-08 16:58:20.096 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
wireguard-postgres-1  | 2023-06-08 16:58:20.133 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
wireguard-postgres-1  | 2023-06-08 16:58:20.133 UTC [1] LOG:  listening on IPv6 address "::", port 5432
wireguard-postgres-1  | 2023-06-08 16:58:20.140 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
wireguard-postgres-1  | 2023-06-08 16:58:20.147 UTC [28] LOG:  database system was shut down at 2023-06-08 16:55:28 UTC
wireguard-postgres-1  | 2023-06-08 16:58:20.155 UTC [1] LOG:  database system is ready to accept connections
wireguard-caddy-1     | {"level":"info","ts":1686243499.7305942,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
wireguard-caddy-1     | {"level":"warn","ts":1686243499.7339923,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":1}
wireguard-caddy-1     | {"level":"info","ts":1686243499.737424,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7378,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7380228,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7380917,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details."}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7381492,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7382014,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7384222,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7384305,"msg":"serving initial configuration"}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7385867,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0004cb3b0"}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7386315,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
wireguard-caddy-1     | {"level":"info","ts":1686243499.7386491,"logger":"tls","msg":"finished cleaning storage units"}

**Platform (please complete the following information):**
 - Firezone latest tag
 - Ubuntu 22.04.2 LTS
 - Kernel version: 5.19.0-1025-aws
 - Deployment method: Docker

**Comment by jamilbk** [comment]
Can you verify that your EXTERNAL_URL uses `HTTPS` and **not** `HTTP`? Firezone expects HTTPS. Unfortunately I'm not able to reproduce based on the info provided.

**Comment by ivdok** [comment]
`EXTERNAL_URL="https://vpn.organization.tld"`

**Comment by jamilbk** [comment]
What's the specific behavior of `curl -vvv -i -k https://vpn.organization.tld`? I'm not seeing any connection attempts in the logs. Do you have a firewall enabled perhaps?

**Comment by ivdok** [comment]
In the meanwhile I've switched to nginx-proxy, but this is what I've got earlier:
````
curl -kv https://vpn.organization.tld:443
*   Trying ???:443...
* Connected to vpn.organization.tld (???) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, internal error (592):
* OpenSSL/3.0.9: error:0A000438:SSL routines::tlsv1 alert internal error
* Closing connection 0
curl: (35) OpenSSL/3.0.9: error:0A000438:SSL routines::tlsv1 alert internal error
```
