### ISSUE TITLE
Per-Group or per-Gateway DNS configuration

### ISSUE THREAD

**Issue by ivdok** [CloudFire-LLC/cloudfire#1651]
**Is your feature request related to a problem? Please describe.**
We want to offer some employees the option to use only internal addresses, or to encapsulate the entirety of their traffic. Each profile (sans default) has to be gated behind some kind of ACL/entitlements system, e.g. don't offer them by default unless granted by admin, because AWS egress fees can quickly skyrocket.

**Describe the solution you'd like**
A customizable set of connection templates for users to pick from - they may differ in e.g. allowed IPs, firewall ACLs, default DNS, and whether user can change them from WebUI to prevent error ID-10T.

**Describe alternatives you've considered**
I've considered to maintain a Confluence page with manuals as to what to enter in device creation screen, but this way people can introduce errors or bypass some network access control policies.

**Additional context**
I'm perfectly fine with this feature being behind Pro/Ultimate/Ultra/Mega/XXX tier, provided it's priced decently, and doesn't exceed $300/mo or scale with users per month.

**Comment by jamilbk** [comment]
I believe the use case you're after here will be implemented in 1.0 via Groups. Could you elaborate a little more on the DNS requirement? Are you looking to customize the DNS server used _per user_ / _per profile_?

**Comment by ivdok** [comment]
> I believe the use case you're after here will be implemented in 1.0 via Groups. Could you elaborate a little more on the DNS requirement? Are you looking to customize the DNS server used _per user_ / _per profile_?

Per profile, for example whether to use authoritative Route53 or CoreDNS with split-horizon, and limit contractors-specific domain zones, without giving out other internal zones - say, give them access to corp.tld, but not corp.internal to limit blast radius in case of the breach. On the firezone side, only switching DNS addresses is required, the rest can be done e.g. on resolver or K8s ingress side.

**Comment by jamilbk** [comment]
@ivdok Thanks for the added context, very helpful. I think with the changes coming in 1.0, this issue will be a dupe of #1158, but I'll leave it open for the time being.

**Comment by jamilbk** [comment]
Things are changing a lot for the 1.0 release, so I've updated the title to be relevant for solving this use case for that.

**Comment by jamilbk** [comment]
So in 1.0 this is already implemented by #1158 -- users will only be able to resolve names for Resources their Groups have access to.
