### ISSUE TITLE
no access to google.com

### ISSUE THREAD

**Issue by t0mZ4** [CloudFire-LLC/cloudfire#1665]
hello
I am running firezone on a google VM

when the tunnel is up, I cannot access google.com and other google services it seems. bing.com works fine.

any idea?

**Comment by jamilbk** [comment]
Possibly a DNS issue? Can you `ping 8.8.8.8` with the tunnel up?

**Comment by spddqd** [comment]
Probably an MTU issue

**Comment by t0mZ4** [comment]
hi @spddqd 

i have ping and also access to bing.com works 

about MTU:

I am running docker compose, and the docker interface is 1500

the Ethernet interface is 1460

I tried 1500, 1460, 1260 on the client MTU and it did not help.

any idea?

**Comment by jamilbk** [comment]
Ah, yes, we've seen things like this happen with MTU. Try setting your Docker MTU to something lower than the outgoing interface, e.g. `1420`. See if this is helpful:

https://mlohr.com/docker-mtu/

**Comment by spddqd** [comment]
Hmm, mine is also 1500 and I had to reduce my client peer MTU to 1280 for it to work correctly. Is it affecting all of your services? Does your client peer resolve names at all? If not, check your DNS. If it does, you can try guessing MTU by sending big packet pings with 20 byte step (1320-1300-1280 etc) to unavailable service.

**Comment by jamilbk** [comment]
Not a Firezone-specific issue, closing
