### ISSUE TITLE
api get "https://{firezone_host}/v0/devices" return empty

### ISSUE THREAD

**Issue by AndryTi** [CloudFire-LLC/cloudfire#1668]
**Describe the bug**
After upgrade from 0.6.8
api request "https://{firezone_host}/v0/devices" returns empty value
what is most interesting, the request GET /v0/users and GET /v0/configuration returns what I need.

**Screenshots / Logs**
--------------------
request /v0/users
--------------------
root@xxxx:~/.firezone# docker 6de90ec1f340
Creating WireGuard interface wg-firezone
Adding route 10.3.2.0/24 for interface wg-firezone
Adding route fd00::3:2:0/120 for interface wg-firezone
13:01:15.444 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=log/2 line=707 mfa=Ecto.Migrator.log/2 module=Ecto.Migrator pid=<0.95.0> [info] Migrations already up
13:01:18.315 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/cowboy2_adapter.ex function=start_link/3 line=103 mfa=Phoenix.Endpoint.Cowboy2Adapter.start_link/3 module=Phoenix.Endpoint.Cowboy2Adapter pid=<0.360.0> [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
13:01:18.330 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/supervisor.ex function=log_access_url/2 line=425 mfa=Phoenix.Endpoint.Supervisor.log_access_url/2 module=Phoenix.Endpoint.Supervisor pid=<0.331.0> [info] Access FzHttpWeb.Endpoint at https://XXX.XXX.XXX.XXX
13:01:40.593 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.499.0> request_id=F2oQ_6XLzNq9POEAAAEh [info] GET /v0/users
13:01:41.058 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.499.0> request_id=F2oQ_6XLzNq9POEAAAEh [info] Sent 200 in 464ms

--------------------
request /v0/devices
--------------------
root@xxxx:~/.firezone# docker logs 802a9bf24890
Creating WireGuard interface wg-firezone
Adding route 10.3.2.0/24 for interface wg-firezone
Adding route fd00::3:2:0/120 for interface wg-firezone
13:03:44.136 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=log/2 line=707 mfa=Ecto.Migrator.log/2 module=Ecto.Migrator pid=<0.95.0> [info] Migrations already up
13:03:46.955 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/cowboy2_adapter.ex function=start_link/3 line=103 mfa=Phoenix.Endpoint.Cowboy2Adapter.start_link/3 module=Phoenix.Endpoint.Cowboy2Adapter pid=<0.360.0> [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
13:03:46.966 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/supervisor.ex function=log_access_url/2 line=425 mfa=Phoenix.Endpoint.Supervisor.log_access_url/2 module=Phoenix.Endpoint.Supervisor pid=<0.331.0> [info] Access FzHttpWeb.Endpoint at https://XXX.XXX.XXX.XXX
13:04:36.123 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.499.0> request_id=F2oRKIQHxlm9POEAAAEh [info] GET /v0/devices
13:04:36.698 erl_level=error domain=cowboy pid=<0.498.0> [error] #PID<0.499.0> running FzHttpWeb.Endpoint (connection #PID<0.498.0>, stream id 1) terminated
Server: XXX.XXX.XXX.XXX:80 (http)
Request: GET /v0/devices
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Protocol.UndefinedError{protocol: Jason.Encoder, value: %FzHttp.Types.IPPort{type: :ipv4, address: {XXX, XXX, XXX, XXX}, port: 51820}, description: "Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @derive Jason.Encoder\n    defstruct ...\n\nFinally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:\n\n    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])\n    Protocol.derive(Jason.Encoder, NameOfTheStruct)\n"} of type Protocol.UndefinedError (a struct), Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.Encoder, NameOfTheStruct)
. This protocol is implemented for the following type(s): Any, Atom, BitString, Date, DateTime, Decimal, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Float, Integer, Jason.Fragment, Jason.OrderedObject, List, Map, NaiveDateTime, Postgrex.INET, Time
        (jason 1.4.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
        (phoenix 1.7.2) lib/phoenix/controller.ex:1010: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
        (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix 1.7.2) lib/phoenix/controller.ex:976: Phoenix.Controller.render_and_send/4
        (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:84: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
        (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2

**Platform (please complete the following information):**
 - Firezone Version 0.7.30
 - OS: Linux
 - Distro: Ubuntu: "Ubuntu 20.04.6 LTS"
 - Kernel version: 5.4.0-132-generic
 - Deployment method: Docker

**Comment by jamilbk** [comment]
Thanks for the report! Should have a fix incoming in a bit.
