### ISSUE TITLE
Error when trying to use cloudflare tunnel with firezone

### ISSUE THREAD

**Issue by thecrazytech1** [CloudFire-LLC/cloudfire#1669]
**Describe the bug**
`Client sent an HTTP request to an HTTPS server.` is displayed when trying to go to webpage forwarded with cloudflare tunnel on port 443

**To Reproduce**
Port forward port 443 to a subdomain using cloudflare tunnel and then go to that subdomain

**Expected behavior**
I should be able to see the webpage

**Platform (please complete the following information):**
 - Firezone Version [latest - 0.7.30]
 - OS: [Linux]
 - Distro: [Debian GNU/Linux 11 (bullseye)]
 - Kernel version: [5.15.84-v8+]
 - Deployment method: [Docker]

**Additional context**
N/A

**Comment by jamilbk** [comment]
Does it work fine without Cloudflare Tunnel? If so, I'm not sure this is a Firezone bug.

See if this is helpful: https://www.firezone.dev/docs/deploy/advanced/reverse-proxy/

The bundled caddy should automatically redirect `http` to `https`, but not sure about Cloudflare Tunnel; there may be a similar configuration option.
