### ISSUE TITLE
Can't specifiy the vpn session duration

### ISSUE THREAD

**Issue by UncleJ4ck** [CloudFire-LLC/cloudfire#1671]
I got Firezone up and running using Omnibus, and i was trying to set the VPN session duration in the firezone.rb file, but no luck. In Docker, it's easy - there's a variable called 'VPN_SESSION_DURATION' for that, but I can't find anything similar in Omnibus.

 - Firezone Version: 0.7.30
 - OS: Linux
 - Distro: Ubuntu 22.04
 - Kernel version: 5.10.0-15-amd64
 - Deployment method: Omnibus

**Comment by jamilbk** [comment]
Hi @UncleJ4ck -- we recommend [switching over](https://www.firezone.dev/docs/administer/migrate) to a Docker install ASAP as Omnibus is EOL by Chef and we don't have the bandwidth to maintain it going forward.

**Comment by UncleJ4ck** [comment]
im having issues in docker because of the network issue, docker installation screwed out my network installation that's why im using omnibus or you should do an alternative without using docker

**Comment by jamilbk** [comment]
https://www.firezone.dev/docs/deploy/advanced/build-from-source
