### ISSUE TITLE
Visual enhancement of the Egress Rules section

### ISSUE THREAD

**Issue by Paulpatou** [CloudFire-LLC/cloudfire#1672]
**Is your feature request related to a problem? Please describe.**
In the rules section, when we use a lot of rules it becomes complicated to visualize them properly.

**Describe the solution you'd like**
It would be nice to be able to move them around when they've already been created, and to be able to group them together.
Creating separators and naming them would also be good for visual clarity, as in many firewall software interfaces.

**Comment by jamilbk** [comment]
Thanks for the request. We'll be announcing 1.0 soon with major changes in this area. The main one being that rules will become Policies and much more simplified, tied to user Groups, and easier to manage.

**Comment by Paulpatou** [comment]
Is there a release date for version 1.0?
In any case, it's good news
Thanks

**Comment by jamilbk** [comment]
We're aiming for 1.0 beta release in a month or so, with general availability due in Q4
