### ISSUE TITLE
OpenID Discovery Document URI Self Signed Certificate

### ISSUE THREAD

**Issue by UncleJ4ck** [CloudFire-LLC/cloudfire#1693]
im hosting keycloak in a test environment using a self signed ssl certificate, im trying to setup a oidc for test with firezone and when i try to put the discoveryt document URI it gives this error: " is invalid. Reason: %Mint.TransportError{reason: {:tls_alert, {:bad_certificate, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:2109 generated CLIENT ALERT: Fatal - Bad Certificate\n'}}}"

![ssl](https://github.com/firezone/firezone/assets/52085661/db50c7c0-3887-4063-8ce4-38482612f1ad)

**Comment by jamilbk** [comment]
You'll need to specify the HTTP_CLIENT_SSL_OPTS variable pointing to a local cafile.

See #1221 and #1635
