### ISSUE TITLE
Configuration of authentification timeout for session more flexible

### ISSUE THREAD

**Issue by TOMCO984** [CloudFire-LLC/cloudfire#1697]
**Is your feature request related to a problem? Please describe.**
Problem 1 :
Actually the authentification timeout is only every hour, every day, every week ...
But if we want a authentification timeout of 12 hours or 2 days it's impossible to set.

Problem 2 : 
Actually the session duration is for every users.
But we cannot define a specific authentification timeout for an user.

**Describe the solution you'd like**
Problem 1 : A more flexible configuration for session duration ti be able to set it more precisely.
Problem 2 : Add the possibility to define a specific authentification timeout for an user or group (if it's implemented in next release)

**Comment by jamilbk** [comment]
With 1.0 the session timeout will be configured in your IdP, and we'll simply replicate this for the end-user session lifetime in the client apps.

**Comment by jamilbk** [comment]
See https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes for an example
