### ISSUE TITLE
Rust workspace no longer works on Linux

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#1714]
I can no longer compile the Rust workspace on my machine because I am hitting the following panic:

https://github.com/firezone/firezone/blob/1882b58bc4f9b98895f62757f1ad20ed0cb5b713/rust/connlib/clients/apple/build.rs#L59

Is there a way we can define this build-script to gracefully fail on non-Mac machines? My workflow is to typically run `cargo clippy --all-targets --all-features` during development and also my IDE indexes all crates in the workspace.

For both of these, it would be great if we can have the build-script not panic.

**Comment by thomaseizinger** [comment]
What do we think of https://github.com/firezone/firezone/pull/1710/commits/8a72b12c34b9fb1686740e3f8d69c4b6cf639b0f (part of https://github.com/firezone/firezone/pull/1710)?

**Comment by francesca64** [comment]
LGTM, though you can use https://doc.rust-lang.org/reference/conditional-compilation.html#target_vendor
