### ISSUE TITLE
how do I bind the web panel to the local ip and port

### ISSUE THREAD

**Issue by yremac** [CloudFire-LLC/cloudfire#1723]
how do I bind the web panel to the local ip and port of another wg network that leads to nginx proxy manager so that I can set the domain.

**Comment by LegandaryRa** [comment]
Hi @yremac 
If you are using Docker use this ENV Variable:

`PHOENIX_EXTERNAL_TRUSTED_PROXIES: "['IP of your NGINX Host']"`

and under ports add:

 `13000:13000` 

BR
LegandaryRa

**Comment by yremac** [comment]
You can show a full example of env , I tried to prescribe these values and I can 't
