### ISSUE TITLE
Configure Max Password Length

### ISSUE THREAD

**Issue by smashedr** [CloudFire-LLC/cloudfire#1724]
**Is your feature request related to a problem? Please describe.**
There is no way to configure max password length.

**Describe the solution you'd like**
Environment variable to override the ridiculous default password strength requirement.

**Describe alternatives you've considered**
Not using Firezone.

**Comment by jamilbk** [comment]
@smashedr What maximum length were you hoping for?

**Comment by smashedr** [comment]
Anything reasonable! Preference would be for it to be configurable, or just the ability disable the requirement all together. If you need a number; 6 would be acceptable.

**Comment by jamilbk** [comment]
Passwords are going away in 1.0 in favor of magic link / OTP login. We strongly urge all users to connect an IdP for authentication instead.
