### ISSUE TITLE
Return to user info after deleting device

### ISSUE THREAD

**Issue by VoyNaLunu** [CloudFire-LLC/cloudfire#1725]
**Is your feature request related to a problem? Please describe.**
When deleting multiple devices it's very inconvenient to be thrown to all devices page and having to go back to user page.

**Describe the solution you'd like**
When deleting device from user page you get back to user page not all devices page.

**Describe alternatives you've considered**
Open each device page separately.

**Comment by jamilbk** [comment]
Devices ("clients" in 1.0 parlance) will be ephemerally created when a user signs in from a new device using our custom Firezone client applications, so this issue will be largely irrelevant going forward.
