### ISSUE TITLE
Dist directory doesn't exist on build from source

### ISSUE THREAD

**Issue by andevatikul** [CloudFire-LLC/cloudfire#1745]
**Describe the bug**
I cloned the master branch and built Firezone with exact Erlang, Elixir, NodeJs versions mentioned on **.tool-versions** file and followed this official [tutorial](https://www.firezone.dev/docs/deploy/advanced/build-from-source).
The build was successful and Firezone runs. But root.js, admin.js and CSS **dists** dir doesn't exist after built inside **fz_http_web** static directory. The browser complains.
There was an error while compiling **fz_http** app. The error is (yet the build was successful):

`[error] Elixir.FzHttpWeb.Mailer.NoopAdapter does not exist`

The config.prod.js contains the outdir but no dist directory after build. I tried to rebuild again after manually creating the dist dir yet same issue:
```
module.exports.config = {
  entryPoints: ['js/admin.js', 'js/root.js', 'js/unprivileged.js'],
  bundle: true,
  outdir: '../priv/static/dist',
  publicPath: '/dist/',
  minify: true,
  plugins: [
    tildePlugin,
    sassPlugin({
      loadPaths: ['.'],
    })],
  loader: {
    '.eot': 'file',
    '.svg': 'file',
    '.ttf': 'file',
    '.woff': 'file',
    '.woff2': 'file',
  }
}
```
**To Reproduce**
Clone the master branch (latest). Build from source.
**Expected behavior**
Dist dir doesn't exist after built from source inside **fz_http_web** static directory. Browser complains. fz_http app compilation error.

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/138834899/4044ab4c-1ce7-4d5c-a4cd-b7b868c68e0a)
![image](https://github.com/firezone/firezone/assets/138834899/efb829cc-fea1-4d20-89bb-374c3fd7ab2e)

**Platform:**
 - Firezone Version [e.g. 0.7.12]
 - OS: Linux
 - Distro: Debian 11 (Up-to-date)
 - Kernel version: 5.10.0-23-amd64
 - Deployment method: Source

**Thanks for this awesome Open Source project.**

**Comment by jamilbk** [comment]
Thanks for the detailed report! Hmm, it's possible that documentation has drifted from how we actually build Firezone in Docker. It looks like the main step you might be missing is asset compilation:

```
# ... do this just before compiling the release
cd apps/fz_http/assets
yarn install --frozen-lockfile
yarn deploy
cd ..
mix phx.digest
cd ../..

# continue compiling the release
mix compile
mix release
```

See if that gives you a working source install. FWIW, the Firezone team relies pretty heavily on Docker (even for development) because of the way Erlang and Elixir are so dependent on OS libs.

I'll open a PR to update docs if this works for you.

See our [Dockerfile](https://github.com/firezone/firezone/blob/master/Dockerfile.prod) for further inspiration.

**Comment by andevatikul** [comment]
That works! Thank you.
I heard Docker is a memory hogger for low memory VMs (e.g. 1GB or 2GB), is it true?
And, is there any way to listen WireGuard on TCP ports? to avoid Firewall related issues on UDP.

Best Regards
