### ISSUE TITLE
NOT_AN_ISSUE: Questions about OIDC + AzureAD auth

### ISSUE THREAD

**Issue by luckman212** [CloudFire-LLC/cloudfire#1755]
Thank you for this amazing project! It was a pleasure to set up thanks to the great Docker compose config and excellent docs 👍 

I have a few questions about [OIDC + AzureAD MFA integration][1] that I couldn't find the answers to.

What happens in the following scenarios:

- User is connected to the VPN, and then they change their AzureAD password—will their session be terminated or just continue until the next token refresh?
- User is connected to the VPN, and then their account is DISABLED from AzureAD. Will the session terminate at some point? Is there some sort of periodic revocation check?
- What happens when I set the "Require Authentication For VPN Sessions" to "Every day" and the user is connected >24h. Will their session be terminated? Or just stop working? How will they know they need to re-auth with the Firezone portal?

Sorry if these are dumb questions.

[1]: https://www.firezone.dev/docs/authenticate/oidc/azuread

**Comment by jamilbk** [comment]
@luckman212 Thanks for the questions. Not dumb questions at all.

> User is connected to the VPN, and then they change their AzureAD password—will their session be terminated or just continue until the next token refresh?

Continue until the next token refresh. Unfortunately OIDC provides no mechanism to know about auth changes. In 1.0 we will sync Firezone token lifetime to the one provided by your IdP when the user signs in, so you should be able to set it to something like 24 hours in your Azure OIDC App to require re-auth at that period in Firezone.

> User is connected to the VPN, and then their account is DISABLED from AzureAD. Will the session terminate at some point? Is there some sort of periodic revocation check?

The OIDC standard doesn't provide for these kinds of checks unfortunately. However, we implemented a temporary solution to this with the env var `DISABLE_VPN_ON_OIDC_ERROR` that uses the `offline_access` scope to periodically refresh a user's token, and if it fails, disables their VPN (read: removes the WireGuard key from the interface). This can sometimes cause the VPN session to go down unexpectedly though if the token refresh fails for any reason, so YMMV.

We're working on SCIM integration in 1.0 to solve this. Unfortunately it's one of those "standards" that isn't implemented in a standard way across providers, so we'll be releasing SCIM support on a per-provider basis as we're able to test and validate the integration. Azure is one of the more popular providers so it's near the top of the list to integrate.

> What happens when I set the "Require Authentication For VPN Sessions" to "Every day" and the user is connected >24h. Will their session be terminated? Or just stop working? How will they know they need to re-auth with the Firezone portal?

It just stops working. Unfortunately we can't do better than this unless we build our own clients. These are coming for 1.0. See https://github.com/firezone/firezone/issues/689

We're aiming to have 1.0 out this quarter. It'll be entering closed beta shortly. You can [request early access](https://www.firezone.dev/contact/1.0-early-access) if you'd like to try it out.

**Comment by luckman212** [comment]
@jamilbk Thank you for the details. That all makes sense. I also signed up for early access.
