### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by SandeshSKrishnan** [CloudFire-LLC/cloudfire#1788]
**Describe the bug**
The docker install script is not working

**To Reproduce**
copy and paste the docker install script found at https://www.firezone.dev/docs/deploy/docker

**Expected behavior**
Step by step installation of Firezone.

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/69599992/d2d3e3fc-205e-4f14-a084-f63e33d00417)

Platform used
 - Firezone Version: 0.7.12
 - OS: Linux
 - Distro: Amazon Linux
 - Deployment method: Docker

**Comment by saadatfar** [comment]
The scripts are removed in #1631 Commit 37a2d7b.

**Comment by jamilbk** [comment]
Thanks for the report! We renamed branches recently and it looks GH only redirects the branch pushes, not artifact URLs.

Fix by #1789 and #1790
