### ISSUE TITLE
Improve `SwiftConnlibError`

### ISSUE THREAD

**Issue by NiwakaDev** [CloudFire-LLC/cloudfire#1796]
Right now `swift-bridge` supports enums with associated data, like so:

```rust
// Rust
#[swift_bridge::bridge]
mod ffi {
    enum SwiftConnlibError {
        Io { description: String, value: usize}, //support struct 
        Base64DecodeError(u32, String), //support tuple
        Base64DecodeSliceError
        //..
    }
```

```swift
// Swift
switch swiftConnlibError {
    case .Io(let description, let value):
       //..
    case .Base64DecodeError(let value):
      //..
}
```

So, we can provide users with more error information by introducing this feature.

**Comment by jamilbk** [comment]
Thanks for the suggestion! copying @francesca64 who's been working on this stuff.

**Comment by wwzeng1** [comment]
Hi @jamilbk @francesca64! I’m one of the developers of Sweep(YC S23), a github app that solves issues by writing pull requests. We used Sweep https://github.com/sweepai/sweep to write this pull request: https://github.com/firezone/firezone/pull/1822. Let me know what you think!
