### ISSUE TITLE
Access to the QR code and configuration file for an existing user

### ISSUE THREAD

**Issue by yblis** [CloudFire-LLC/cloudfire#1797]
**Is your feature request related to a problem? Please describe.**

The issue is that once a user is created, we no longer have access to the QR code or the configuration file.

**Describe the solution you'd like**
Would it be feasible, once a user exists, to download the configuration file or scan the QR code at our convenience?

PS: sorry for my english ^^

**Comment by jamilbk** [comment]
Hi @yblis, thanks for the suggestion.

Showing the config and/or QR code after a device is created would require persisting its PrivateKey in the DB, which we don't want to do. We generate this in the browser itself, so the server never actually sees this data.
