### ISSUE TITLE
Wrong subnet for firezone-network in docker-compose.prod.yml

### ISSUE THREAD

**Issue by NikJen26** [CloudFire-LLC/cloudfire#1820]
**Is your feature request related to a problem? Please describe.**
The used subnet 2001:3990:3990::/64 is a publicly routable address which gets assigned by IANA. Since this is only a bridged network this is the wrong approach.

**Describe the solution you'd like**
 This Ipv6 Address needs to be changed to a Unique Local Address fc00::/7

**Comment by jamilbk** [comment]
Thanks for the report. Indeed, this can changed to whatever you need, but agreed that it should be fc00::/7 by default.
