### ISSUE TITLE
Login issue when setting firezone not on root and on /path

### ISSUE THREAD

**Issue by SandeshSKrishnan** [CloudFire-LLC/cloudfire#1821]
**Describe the bug**
Can't login into firezone using the default admin email and password after successful installation of firezone on https://example.com/path/

**To Reproduce**
Install firezone using the manual docker installation steps and set external URL as https://example.com/firezone.
I have removed the caddy service and postgres service in the docker-compose file as I'm using nginx as a reverse proxy and RDS as the database for firezone. 

I used the template from https://github.com/jitsi/infra-configuration/blob/main/ansible/roles/firezone/templates/docker-compose.yml.j2. My nginx conf is as follows:
    location /firezone {
      proxy_pass         http://localhost:13000;
      proxy_redirect     off;
      proxy_http_version 1.1;

      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_max_temp_file_size 0;

      # websocket support
      proxy_set_header   Connection        $connection_upgrade;
      proxy_set_header   Upgrade           $http_upgrade;

      #this is the maximum upload size
      client_max_body_size       10m;
      client_body_buffer_size    128k;

      proxy_connect_timeout      90;
      proxy_send_timeout         90;
      proxy_read_timeout         90;
      proxy_buffering            off;
      proxy_request_buffering    off; # Required for HTTP CLI commands
      proxy_set_header Connection ""; # Clear for keepalive

  }
and adding the port 13000 in the firezone service in docker-compose.

**Expected behavior**
Logging into Firezone should work as usual.

**Screenshots / Logs**
I've tried multiple combinations in the nginx conf to check the working of trailing slash in the conf.
1. Adding a trailing slash at both /firezone/ and the proxy_pass leads to too many redirects.
2. Adding a trailing slash at either /firezone/ or the proxy_pass would let the site to load but then upon clicking the sign in with email button, it would lead to having double slashes on the address bar: https://example.com/firezone//auth/identity and then logging in with the credentials would lead to the following error:
![image](https://github.com/firezone/firezone/assets/69599992/e3c5290e-b779-4c8e-999f-150a31b0807c)

Upon inspecting the page and then further looking into the div tag, we can see that the form action is incorrect.
![image](https://github.com/firezone/firezone/assets/69599992/7d118a42-e1a6-4891-b47b-257946d9d1a1)

Editing that manually and removing one slash enables me to login to Firezone. Upon login, I have fonts and the some icons missing.

I also tried editing the EXTERNAL_URL in the .env.
1. Adding a trailing slash in the EXTERNAL_URL leads to 2 slashes in the address bar in between the EXTERNAL_URL  and auth/identity.
2. Adding 2 trailing slashes in the EXTERNAL_URL  leads to 3 slashes in the address bar in between the EXTERNAL_URL  and auth/identity.
3. Adding no trailing slashes in the EXTERNAL_URL leads to an application error.

**Platform (please complete the following information):**
 - Firezone Version: Latest
 - OS: Linux
 - Distro: Amazon Linux
 - Deployment method: Docker

**Comment by jamilbk** [comment]
Thanks for the report! We're aware of this issue, but sadly won't be able to fix it any time soon. The 1.0 release will have a cloud-managed portal that will make this irrelevant for the majority of our users.
