### ISSUE TITLE
Create a systemd unit file

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#1828]
## Description

We want a systemd unit file that makes it easy to start the relay. The following things need to be considered:

- We need to set certain environment variables for the relay to be operational. The [current](https://serverfault.com/a/413408) best practice for this is to leave those to override files and not declare them in the unit file. We can set them to empty strings which should have some documentation value in which variables one can override.
- We need to have a dependency on the network being available. I believe `After=network.target` should be sufficient.
- We need to make sure systemd will restart the relay when it crashes

## Open questions

- System supports a concept of [credentials](https://systemd.io/CREDENTIALS/) to load sensitive information in a secure way. Is this something we want to make use of or are we okay with using environment variables for now? We'd have to slightly tweak the interface of the relay for this. Specifically, we'd have to have it read the portal's auth token from a file instead of from an env variable.
- How do we want to report crashes or failures to start? We have statuspage set up, right @jamilbk? Should / can I integrate with that somehow?

**Comment by jamilbk** [comment]
> We can set them to empty strings which should have some documentation value in which variables one can override.

Yeah, that works. I was thinking we could just add a "deploying" section to `rust/relay/README.md` with an inline unit template, env file template, and instructions for downloading the relay binary and setting up. Upgrade would just be re-downloading the binary and swapping it out.

I'll add these notes the main product documentation before launch.

> System supports a concept of [credentials](https://systemd.io/CREDENTIALS/) to load sensitive information in a secure way. Is this something we want to make use of or are we okay with using environment variables for now?

Ah, did not know about systemd's credentials. I say let's just keep it simple for now with standard .env files, maybe with a todo noted for upgrading to systemd credentials later.

**Comment by thomaseizinger** [comment]
I'll close this for now as we are using docker host networking to deploy the relay.

**Comment by jamilbk** [comment]
Reopening since we're planning to support self-hosted Relays:

![](https://share.balsamiq.com/c/c1XfQzpxHUrmNhiKqEo3in.png)

**Comment by jamilbk** [comment]
No need for self-hosted Relays for some time in light of the Data routing feature on Sites.
