### ISSUE TITLE
relay: TCP tunneling

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#1830]
Some deployments do not yet allow for UDP traffic properly. I can't find the reference now but I think Google reported that about 10% of the traffic between Chrome deployments and google servers completely fail over UDP and they have to fall back to TCP.

The TURN spec specifies behaviour for how we can relay between TCP <> UDP and UDP <> TCP:

- https://www.rfc-editor.org/rfc/rfc8656#name-tcp-to-udp-relay
- https://www.rfc-editor.org/rfc/rfc8656#name-udp-to-tcp-relay

As per spec, a client can only requested a relay address for UDP and not TCP: https://www.rfc-editor.org/rfc/rfc8656#name-requested-transport

I believe this means that we will be able to have clients connect to the relay over TCP but the relay address they are getting will always be on UDP. Is that good enough?

**Comment by jamilbk** [comment]
Hm I may be misunderstanding the RFC, but it seems like from the linked sections that the client <-> relay transport can be TCP, but the gateway <-> relay communication must always be over UDP. Am I understanding correctly?

If so, that would work. The main scenario we need to worry about is UDP being blocked in certain public networks like conference WiFis, airports, cafes, etc. The gateway's connection should be much more predictable and UDP would be ok there.

**Comment by thomaseizinger** [comment]
> gateway <-> relay communication must always be over UDP. Am I understanding correctly?

That is my understanding as well given that we can never request a TCP relay address. I'd have to read up why but we could also deviate from the spec here and allow the creation of a TCP allocation. We'd have to think about how to re-identify the allocation for the creation of a channel as that currently happens based on the 4-tuple and thus ignores the transport protocol.

**Comment by jamilbk** [comment]
Hm, the question is -- do we want to tackle this for the 1.0 launch or save it until afterwards? I believe this would be the next item of priority for the Relay. I may suggest get some feedback on the current Relay before taking this on.

**Comment by jamilbk** [comment]
Also, we may want to implement #1962 before doing this work.

**Comment by jamilbk** [comment]
I don't think we need full-on TCP tunneling; the UDP encapsulation that WebRTC is providing currently works great. (DTLS)
