### ISSUE TITLE
error with caddy after upgrade to 0.7.32

### ISSUE THREAD

**Issue by dno-digiserv** [CloudFire-LLC/cloudfire#1858]
**Describe the bug**
upgraded to latest version with docker-compose and caddy fails.

**To Reproduce**
Steps to reproduce the behavior: upgrade

**Expected behavior**
expected the service to come back up again without issue

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/94645458/685f3e1f-9f34-4b4d-8886-60a41adfa4ec)

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.12]
 0.7.32
 - OS: [e.g. Linux]
Linux
 - Distro: [e.g. Ubuntu 18.04]
 Ubuntu 22.04.1
 - Kernel version: [e.g. 5.10.11]
 5.19.0
 - Deployment method: [e.g. Docker / Omnibus / Source]
 Docker

**Comment by jamilbk** [comment]
@dno-digiserv You'll need to remove the `on_demand` from your `$HOME/.firezone/docker-compose.yml` Caddyfile declaration. Unfortunately there's no way for us to do that remotely -- we don't mess with your compose files.

**Comment by dno-digiserv** [comment]
Ahh, will test that asap 👍
Thank you, hope I didn't miss that anywhere, tried searching for the error and checked the release notes, but got no hits.

**Comment by jamilbk** [comment]
Correction -- You'll want to remove this from `TLS_OPTS` in your `.env`, not the `docker-compose.yml`.
