### ISSUE TITLE
VPN is enabled by default after creating user and device

### ISSUE THREAD

**Issue by merclyn** [CloudFire-LLC/cloudfire#1866]
**Describe the bug**
After we add a user and a device that user has immediate access to the vpn before they ever authenticate into the console. 

**Expected behavior**
We would expect that a user should need to authenticate prior to the VPN tunnel being active. The initial VPN status should be expired which would require the user to authenticate prior to having access to the VPN tunne.

**Platform (please complete the following information):**
 - Firezone Version 0.7.30
 - OS: RHEL 9
 - Deployment method: Docker

**Comment by jamilbk** [comment]
Hi @merclyn, thanks for the report. Can you confirm what your `vpn_session_duration` is set to?

**Comment by merclyn** [comment]
The session duration is set to 1 day or "Every Day".

**Comment by jamilbk** [comment]
This will be fixed in our upcoming 1.0 release. We won't likely issue a patch for this for 0.7.
