### ISSUE TITLE
Select Tunnel IPv4 subnets according to user group

### ISSUE THREAD

**Issue by p1nablack** [CloudFire-LLC/cloudfire#1889]
Be able to select the Tunnel IPv4 (Wireguard IP) subnet in accordance with the group in which the user will be located, a very necessary function of which is not currently available.

Also:
Ability to select a Tunnel IPv4 (Wireguard IP) subnet for an individual user.

**Comment by jamilbk** [comment]
Thanks for the report! Coming in 1.0: #1157 . Closing as dupe.
