### ISSUE TITLE
When masquerading is disabled, packets on the return path are dropped or do not find a route

### ISSUE THREAD

**Issue by p1nablack** [CloudFire-LLC/cloudfire#1891]
**Describe the bug**
When masquerading is disabled, packets on the return path are dropped or do not find a route.

**To Reproduce**
1) change WIREGUARD_IPV4_MASQUERADE: **false**
2) docker compose up -d
3) open resource behind vpn (ssh, https)

**Expected behavior**
connect via ssh or access the web

**Screenshots / Logs**

**Platform (please complete the following information):**
 - Firezone Version: 0.7.32
 - OS: Linux
 - Distro: Ubuntu: 22.04
 - Kernel version: 5.15.0-71-generic
 - Deployment method: Docker

**Additional context**
Checked tcpdump. Traffic leaves the firezone and comes back to the firezone, but then stalls.

**Comment by jamilbk** [comment]
@p1nablack Thanks for the report. This is expected behavior. NAT is required to route from private, RFC1918 address space to the public Internet. Could you describe the behavior you're expecting?

**Comment by p1nablack** [comment]
Hi, @jamilbk!

I want so:
<img width="1052" alt="Screenshot 2023-08-14 at 11 57 12" src="https://github.com/firezone/firezone/assets/142028528/365d8f8e-87cf-4068-9aaa-d9d092127e37">


It turns out like this:
<img width="1052" alt="Screenshot 2023-08-14 at 11 57 12" src="https://github.com/firezone/firezone/assets/142028528/abb96a2a-cab5-4a2c-a4a1-a6f0bac9cb68">

**Comment by p1nablack** [comment]
@jamilbk 
It seems that firezone does not know where and through what to send response packets without masquerading in Docker.

**Comment by jamilbk** [comment]
@p1nablack Sorry, I'm still not following. If you disable masquerading/NAT, how will the kernel know which WireGuard client to send the return packets to? Masquerading creates those routes on the fly.

You could disable masquerading and configure routes to suit your needs -- we don't modify existing routes if masquerade is disabled.

**Comment by jbtule** [comment]
I think this is the same thing I was trying to point out in part of #1365

In that issue it was a mentioned that it could be worked around similar to

https://github.com/Place1/wg-access-server/issues/26

I was not able to figure how how to make that work, so continuing to use Omnibus.

If you are using firezone to provide access to private network, and you need to be able to have logging/accountability of the vpn client's connecting to each private server, requiring masquerade/nat is a show stopper.

**Comment by jamilbk** [comment]
I see, thanks for the added color @jbtule. This should be possible with `WIREGUARD_IPV4_MASQUERADE=false` and `WIREGUARD_IPV6_MASQUERADE=false` and then setting up your own custom `iptables` rules to route packets properly as needed. Docker adds a layer of complexity, but shouldn't prevent this from functioning -- you can set the `firezone` service's `network_mode` to `host` which should bypass Docker for networking traffic.

From there I believe simple SNAT should suffice to route packets from your private network to the client devices through the Firezone server.

**Comment by p1nablack** [comment]
@jamilbk , @jbtule  thanks for the help.
**The problem was solved with the help of network host.**

1. cd /opt/firezone
2. vi /opt/firezone/docker-compose.yml

```
# Example compose file for production deployment on Linux.
#
# Note: This file is meant to serve as a template. Please modify it
# according to your needs. Read more about Docker Compose:
#
# https://docs.docker.com/compose/compose-file/
#
#
x-deploy: &default-deploy
  restart_policy:
    condition: unless-stopped
    delay: 5s
    window: 120s
  update_config:
    order: start-first

version: '3.7'

services:
  caddy:
    image: caddy:2
    volumes:
      - ${FZ_INSTALL_DIR:-.}/caddy:/data/caddy
    # See Caddy's documentation for customizing this line
    # https://caddyserver.com/docs/quick-starts/reverse-proxy
    command:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile

        https:// {
          log
          reverse_proxy * 127.0.0.1:${PHOENIX_PORT:-13000}
          ${TLS_OPTS:-}
        }
        EOF
    network_mode: "host"
    deploy:
      <<: *default-deploy

  firezone:
    network_mode: "host"
    image: firezone/firezone:${VERSION:-latest}
      #    ports:
      #      - ${WIREGUARD_PORT:-51820}:${WIREGUARD_PORT:-51820}/udp
    env_file:
      # This should contain a list of env vars for configuring Firezone.
      # See https://www.firezone.dev/docs/reference/env-vars for more info.
      - ${FZ_INSTALL_DIR:-.}/.env
    volumes:
      # IMPORTANT: Persists WireGuard private key and other data. If
      # /var/firezone/private_key exists when Firezone starts, it is
      # used as the WireGuard private. Otherwise, one is generated.
      - ${FZ_INSTALL_DIR:-.}/firezone:/var/firezone
    cap_add:
      # Needed for WireGuard and firewall support.
      - NET_ADMIN
      - SYS_MODULE
        #    sysctls:
      # Needed for masquerading and NAT.
      #      - net.ipv6.conf.all.disable_ipv6=0
        #      - net.ipv4.ip_forward=1
        #      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - postgres
        #    networks:
      #      firezone-network:
        #        ipv4_address: 172.25.0.100
          #        ipv6_address: 2001:3990:3990::99

    deploy:
      <<: *default-deploy

  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-firezone}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
    networks:
      firezone-network:
        ipv4_address: 172.25.0.2
    deploy:
      <<: *default-deploy
      update_config:
        order: stop-first

# Postgres needs a named volume to prevent perms issues on non-linux platforms
volumes:
  postgres-data:

networks:
  firezone-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
        - subnet: 2001:3990:3990::/64
          gateway: 2001:3990:3990::1
```

3. sudo vi /opt/firezone/.env
```
DATABASE_HOST: 172.25.0.2
WIREGUARD_IPV4_MASQUERADE=false
WIREGUARD_IPV6_MASQUERADE=false
```
4. sudo vi /etc/syctl.conf
`net.ipv4.ip_forward=1`
5. sudo sysctl -p
6. docker compose up -d
7. sudo iptables -I FORWARD -i eth0 -o wg-firezone -j ACCEPT
8. sudo iptables -I FORWARD -o eth0 -i wg-firezone -j ACCEPT

**Comment by jamilbk** [comment]
@p1nablack Glad you were able to figure it out, and thanks for posting your solution! I'll mark this closed now.
