### ISSUE TITLE
Setting a custom max API token expire period instead of the default max 90 days

### ISSUE THREAD

**Issue by JaccoVE** [CloudFire-LLC/cloudfire#1902]
**Is your feature request related to a problem? Please describe.**
The maximum expire period for API keys is currently 90 days, would it be possible to make this maximum period customizable?

**Describe the solution you'd like**
I use Firezone in a Docker container, so adding a new environment variable that can be set like 'MAX_VALID_API_DAYS=365' would be a neat feature.

**Describe alternatives you've considered**
- Manually creating a new key every 90 days for my Docker based client application
- Creating a new API key every 90 days using the CLI using a cron job and providing the updated key to the client application

**Additional context**
![image](https://github.com/firezone/firezone/assets/34547046/727fd1eb-dfac-4b19-b845-6287d6eccdbd)

**Comment by jamilbk** [comment]
Thanks for the report. Could you elaborate a little more on the use case behind this? A year seems a bit long for full-privilege API tokens to live.

**Comment by JaccoVE** [comment]
The Docker based client application I'm revering to uses the REST API to check for new active clients, looks up their public IP / location and then sends me a Telegram message to inform me about the connection. This application runs at the same server and adds an additional layer of security for me since I only use the VPN myself. My view would be that the overall security risk is higher when I'm not getting notified about new connections due to an outdated API key then the additional risks of a longer expire period for the API key.

**Comment by jamilbk** [comment]
@JaccoVE I see. In this case I would recommend just editing the DB field (`api_tokens.expires_at` IIRC) directly to an expiry time to your liking. This will prevent us from needing to complicate the expiration time configuration for others, but still allow you to work around the validation.

**Comment by JaccoVE** [comment]
I will look into this, thanks for your time!
