### ISSUE TITLE
Configured DNS server not applied to connections when PersistentKeepalive is set to 0

### ISSUE THREAD

**Issue by enpaul** [CloudFire-LLC/cloudfire#1918]
**Describe the bug**
Setting persistent keepalive to 0 adds an empty line to the generated configuration files, which causes the configured DNS server to not be applied to the connection on Fedora 38 via NetworkManager.

**To Reproduce**
1. Set `default['firezone']['wireguard']['persistent_keepalive']` to `0` (the default value)
2. Set `default['firezone']['wireguard']['dns']` to any non-default value (example: `8.8.8.8`)
3. Generate a Firezone device profile via the normal user workflow
4. Inspect the config and see that it includes a blank line where the `PersistentKeepalive` directive would be, and a valid `DNS` directive
5. Import the config using NetworkManager's "import from file" feature
6. Activate the connection
7. Note that the connection has no assigned DNS servers
8. Manually edit the config file to remove the blank line
9. Re-import the config using NetworkManager's "import from file" feature
10. Activate the connection
11. Note that the connection has the correct assigned DNS server

**Expected behavior**
This may be a bug in NetworkManager's parsing of the config file, however Firezone can mitigate the problem by generating a config that either does not include the `PersistentKeepalive` line if the value is `0`, or including the directive explicitly set to `0`.

**Platform:**
 - Firezone Version: `0.7.30`
 - OS: Linux
 - Distro: Server - Ubuntu 22.04, Client - Fedora 38
 - Kernel version: Server - `5.15.0`, Client - `6.4.10`
 - Deployment method: Omnibus

**Comment by jamilbk** [comment]
Thanks for the report @enpaul.

Are you able to test if this is happening on Docker as well? Many configuration bugs were fixed in the Docker deployment method. Omnibus deployments have been deprecated for some time.

**Comment by enpaul** [comment]
Hi @jamilbk , yes I just ran this test on my dev setup and found that it exhibits the same symptoms on the server side (generates a config with the blank line). I don't have access to my Fedora workstation at the moment to confirm that the config behaves the same on the client, but I'd say it's a safe assumption that it does. I can confirm that later tonight though. Once that's done I'll update the issue with the details from my docker dev setup.

**Comment by jamilbk** [comment]
@enpaul As a workaround, could you leave the PersistentKeepalive field blank? That should keep it from being printed at all I believe. I'm not sure what a PersistentKeepalive value of 0 would achieve in the WireGuard client?

**Comment by jamilbk** [comment]
Fixed in 0.7.36
