### ISSUE TITLE
Firezone connecting with Tor Network

### ISSUE THREAD

**Issue by kutsav** [CloudFire-LLC/cloudfire#1961]
**Describe the bug**
We have Firezone server running on AWS EC2 instanes and AWS Guard Duty enabled in the account. At regular intervals(around every 1-2 months), we get an alert from Guard Duty for the Firezone instane with following message:
```
EC2 instance i-xxxxxxxx is communicating with IP address 66.206.0.138 on the Tor Anonymizing Proxy network marked as an Entry node.
EC2 instance i-xxxxxxxx is communicating with IP address 191.252.111.55 on the Tor Anonymizing Proxy network
```

**To Reproduce**
1. Setup Firezone on EC2
2. Enable Guard Duty for your AWS account

**Expected behavior**
Egress traffic of Firezone should not be going to Tor servers

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version: 0.7.28 
 - OS:  Linux
 - Distro: Ubuntu 20.04
 - Kernel version: 5.11.0-1022-aws
 - Deployment method: Docker

**Comment by jamilbk** [comment]
Thanks for the report @kutsav. We don't initiate outbound connections to those IPs. Is it possible a device connected to your Firezone server is making those connections?

**Comment by kutsav** [comment]
Is it possible to restrict/block such IPs from Firezone UI. If not then maybe this can be added as a feature in next release?

**Comment by jamilbk** [comment]
Yes, you can add deny rules in the UI. That'll block traffic from clients to those IPs.
