### ISSUE TITLE
Caddy return 431 HTTP code

### ISSUE THREAD

**Issue by theophileds** [CloudFire-LLC/cloudfire#1967]
**Describe the bug**
After setting Firezone OICD to Google Oauth, and signing with Google auth, I obtained a 431 error.
Afterward, The Firezone app is no longer available as it's constantly returning the same error unless I clear all the cache or open the tab in private mode.

**To Reproduce**
Sign up/in using Google Auth.

**Platform (please complete the following information):**
 - Firezone Version [e.g. 0.7.35]
 - OS: Amazon Linux 2023
 - Kernel version: 6.1.41-63.114.amzn2023.x86_64
 - Deployment method: Docker

**Comment by theophileds** [comment]
It appears that Caddy may be declining cookies that exceed a specific size threshold. Given our configuration where multiple subdomain applications share the same top domain, Chrome seems to aggregate cookies from various applications. This aggregation potentially results in an overly large header size.

**Comment by jamilbk** [comment]
If the cookie is too large, check your OIDC claims size -- if the JWT is too large from Google that can cause cookie too large issues.

431 however points to headers being too large. You can increase the header field size using the `PHOENIX_HTTP_PROTOCOL_OPTIONS` var. See

https://www.firezone.dev/docs/reference/env-vars#webserver

and

https://ninenines.eu/docs/en/cowboy/2.5/manual/cowboy_http/

**Comment by theophileds** [comment]
It's working now!

Thank you.

**Comment by JzJad** [comment]
Mind sharing that env variable, I cannot for the life of me get the correct formatting or something.

**Comment by theophileds** [comment]
@JzJad Sure,

```
# Allow large headers
PHOENIX_HTTP_PROTOCOL_OPTIONS='{"max_header_value_length": 16384}'
```
