### ISSUE TITLE
Azure AD Discovery Document URI Error

### ISSUE THREAD

**Issue by CarstenRecker** [CloudFire-LLC/cloudfire#1971]
I want to add OIDC Configuration to Sign In via Azure AD.
When I enter the data in the configuration mask, an error appears at Discovery Document URI field: 
`is invalid. Reason: %Mint.TransportError{reason: :nxdomain}`

**Comment by jamilbk** [comment]
This means your Firezone instance isn't able to resolve that domain. What does `host login.microsoftonline.com` print from your Firezone server CLI?

**Comment by CarstenRecker** [comment]
This is my ouput of host:

`ccf@cloudwalker:~$ host login.microsoftonline.com
login.microsoftonline.com is an alias for login.mso.msidentity.com.
login.mso.msidentity.com is an alias for ak.privatelink.msidentity.com.
ak.privatelink.msidentity.com is an alias for www.tm.ak.prd.aadg.akadns.net.
www.tm.ak.prd.aadg.akadns.net has address 20.190.159.68
www.tm.ak.prd.aadg.akadns.net has address 40.126.31.71
www.tm.ak.prd.aadg.akadns.net has address 20.190.159.71
www.tm.ak.prd.aadg.akadns.net has address 20.190.159.73
www.tm.ak.prd.aadg.akadns.net has address 40.126.31.67
www.tm.ak.prd.aadg.akadns.net has address 20.190.159.4
www.tm.ak.prd.aadg.akadns.net has address 20.190.159.75
www.tm.ak.prd.aadg.akadns.net has address 40.126.31.73
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1026:3000:c8::6
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1027:1:d8::4
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1026:3000:d0::b
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1027:1:d8::9
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1026:3000:d0::d
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1026:3000:d0::6
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1027:1:d8::7
www.tm.ak.prd.aadg.akadns.net has IPv6 address 2603:1026:3000:d0::`

**Comment by jamilbk** [comment]
Is outbound DNS and network connectivity functioning in your Docker container?

```
docker compose -f $HOME/.firezone/docker-compose.yml exec -it firezone ping login.microsoftonline.com
```

**Comment by CarstenRecker** [comment]
There seems to be a problem:
```
root@cloudwalker:/home/ccf# docker compose -f /opt/firezone/docker-compose.yml exec -it firezone ping login.microsoftonline.com
ping: bad address 'login.microsoftonline.com'
```

**Comment by jamilbk** [comment]
Seems like you have an issue with your Docker setup. Unable to replicate, so closing for now. Feel free to reopen if you find this to be a Firezone issue!
