### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by Ir0nFir3** [CloudFire-LLC/cloudfire#1972]
**Describe the bug**
Can not access Web UI after Fresh install in docker on Ubuntu Server 22.04.3 LTS
Try to browse to the URL by IP or Name and get the same error.
This happens in Firefox, Chrome and Edge, all are up to date.

**To Reproduce**
Fresh Install of Ubuntu Server 22.04.3 LTS
Ran Updates.
Installed Docker
Ran Docker install Script

**Expected behavior**
Access to the Web UI
The Web UI will not be Public facing.

**Screenshots / Logs**

Firefox Error

Secure Connection Failed

An error occurred during a connection to 192.168.2.110. Peer reports it experienced an internal error.

Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
![2023-08-31 10_35_21-Problem loading page — Mozilla Firefox](https://github.com/firezone/firezone/assets/143733530/4eb7f410-c1fe-4d76-9739-d07eadb5f78e)
------------------------------------------------------------------------------------------
Docker Logs from Caddy
INF ts=1693495346.4079638 msg=using provided configuration config_file=/etc/caddy/Caddyfile config_adapter=

WRN ts=1693495346.4092762 msg=Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies adapter=caddyfile file=/etc/caddy/Caddyfile line=1

INF ts=1693495346.409901 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]

INF ts=1693495346.4101236 logger=http.auto_https msg=server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS server_name=srv0 https_port=443

INF ts=1693495346.4102156 logger=http.auto_https msg=enabling automatic HTTP->HTTPS redirects server_name=srv0

INF ts=1693495346.4101808 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc00038c680

INF ts=1693495346.4106047 logger=http msg=enabling HTTP/3 listener addr=:443

INF ts=1693495346.410613 logger=tls msg=cleaning storage unit description=FileStorage:/data/caddy

INF ts=1693495346.4107559 logger=tls msg=finished cleaning storage units

INF ts=1693495346.4108477 msg=failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.

INF ts=1693495346.4110343 logger=http.log msg=server running name=srv0 protocols=["h1","h2","h3"]

INF ts=1693495346.411131 logger=http.log msg=server running name=remaining_auto_https_redirects protocols=["h1","h2","h3"]

INF ts=1693495346.4112127 logger=http msg=enabling automatic TLS certificate management domains=["gm-wireguard"]

INF ts=1693495346.4115396 msg=autosaved config (load with --resume flag) file=/config/caddy/autosave.json

INF ts=1693495346.411613 msg=serving initial configuration

INF ts=1693495346.4116228 logger=tls.obtain msg=acquiring lock identifier=gm-wireguard

INF ts=1693495346.4751747 logger=tls.obtain msg=lock acquired identifier=gm-wireguard

INF ts=1693495346.4754095 logger=tls.obtain msg=obtaining certificate identifier=gm-wireguard

INF ts=1693495346.8546267 logger=http msg=waiting on internal rate limiter identifiers=["gm-wireguard"] ca=https://acme-v02.api.letsencrypt.org/directory account=

INF ts=1693495346.8546495 logger=http msg=done waiting on internal rate limiter identifiers=["gm-wireguard"] ca=https://acme-v02.api.letsencrypt.org/directory account=

ERR ts=1693495346.9316216 logger=tls.obtain msg=could not get certificate from issuer identifier=gm-wireguard issuer=acme-v02.api.letsencrypt.org-directory error=HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for "gm-wireguard": Domain name needs at least one dot

WRN ts=1693495346.9317946 logger=http msg=missing email address for ZeroSSL; it is strongly recommended to set one for next time

INF ts=1693495347.858271 logger=http msg=generated EAB credentials key_id=oNdqURL1vJdD4HcIjfHjXw

INF ts=1693495348.9252813 logger=http msg=waiting on internal rate limiter identifiers=["gm-wireguard"] ca=https://acme.zerossl.com/v2/DV90 account=

INF ts=1693495348.9253023 logger=http msg=done waiting on internal rate limiter identifiers=["gm-wireguard"] ca=https://acme.zerossl.com/v2/DV90 account=

ERR ts=1693495349.8646212 logger=tls.obtain msg=could not get certificate from issuer identifier=gm-wireguard issuer=acme.zerossl.com-v2-DV90 error=HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Invalid DNS identifier [gm-wireguard]

ERR ts=1693495349.8647153 logger=tls.obtain msg=will retry error=[gm-wireguard] Obtain: [gm-wireguard] creating new order: attempt 1: https://acme.zerossl.com/v2/DV90/newOrder: HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Invalid DNS identifier [gm-wireguard] (ca=https://acme.zerossl.com/v2/DV90) attempt=1 retrying_in=60 elapsed=3.389519767 max_duration=2592000

INF ts=1693495409.865304 logger=tls.obtain msg=obtaining certificate identifier=gm-wireguard
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
Firezone Logs

Creating WireGuard interface wg-firezone

Adding route 100.64.0.0/10 for interface wg-firezone

Adding route fd00::/106 for interface wg-firezone

15:22:27.489 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=log/2 line=707 mfa=Ecto.Migrator.log/2 module=Ecto.Migrator pid=<0.95.0> [info] Migrations already up

15:22:28.642 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/cowboy2_adapter.ex function=start_link/3 line=103 mfa=Phoenix.Endpoint.Cowboy2Adapter.start_link/3 module=Phoenix.Endpoint.Cowboy2Adapter pid=<0.362.0> [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)

15:22:28.648 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/supervisor.ex function=log_access_url/2 line=425 mfa=Phoenix.Endpoint.Supervisor.log_access_url/2 module=Phoenix.Endpoint.Supervisor pid=<0.331.0> [info] Access FzHttpWeb.Endpoint at https://gm-wireguard
------------------------------------------------------------------------------------------
      

**Platform (please complete the following information):**
 - Firezone Version [0.7.35]
 - OS: [Linux]
 - Distro: [Ubuntu Server 22.04.3 LTS]
 - Kernel version: [GNU/Linux 5.15.0-82-generic x86_64]
 - Deployment method: [Docker]
**Additional context**

**Comment by jamilbk** [comment]
You'll need to configure the `on_demand` option in your `TLS_OPTS` in your `.env`. Caddy now doesn't auto-provision SSL certs by default in order to avoid DoS vectors.

See here: https://caddyserver.com/docs/caddyfile/directives/tls#on_demand

Another option is to disable Caddy, set `SECURE_COOKIES=false` in your `.env`, then terminate SSL with another proxy of your choosing.
