### ISSUE TITLE
alternative scheme for auth and access 

### ISSUE THREAD

**Issue by basaran** [CloudFire-LLC/cloudfire#1975]
**Is your feature request related to a problem? Please describe.**
- At the moment, authentication features such as MFA, OIDC etc. requires exposing the management UI at 443.
- We have the option for local auth as well as OIDC, so people can use keycloak etc. themselves.
- This mechanism also requires exposing an IDP on the public network.  

**Describe the solution you'd like**
- When users login, only enable their access to the firezone management network(s) only, block everything else.
- Firezone network(s) are where server's 443 and IDP (if any is used) reside.
- Once they complete OIDC, or TOTP, then remove the the block.
- If the user session expires, redirect browser traffic to management UI. This could be perhaps done with iptables.

**Describe alternatives you've considered**
Netbird, Zerotier, Twingate, Tailscale, Softether

**Additional context**
I believe this scheme would make deploying firezone more secure, as the IDP and the local management interface is not exposed to public internet and would help ease companies with limited resources utilize firezone efficiently.

**Comment by jamilbk** [comment]
@basaran In 1.0 the data plane and control plane are split, removing the need for this feature.
