### ISSUE TITLE
relay: reconsider healthcheck

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#1997]
With https://github.com/firezone/firezone/pull/1996, our health-check endpoint in the relay gets "even more" useless than what it currently is.

I am of the opinion that we shouldn't need a health-check and instead rely on instrumentation and monitoring on what the relay actually does. For startup, we already have the "log in" with the portal before the relay is made available.

Additionally, the relay will exit on any hard-error.

@AndrewDryga What do you think? Am I missing something that we need the health-check for?

**Comment by jamilbk** [comment]
Open to what @AndrewDryga thinks but I'm ok to bias towards removing this feature before launch if we're not sure we need it. Since the Relay will be self-hosted, we don't people to rely heavily on this feature before we remove it.

**Comment by AndrewDryga** [comment]
We discussed it in Slack, health check is needed because not all environments will be able to monitor health by just seeing if the binary is running. They are also required to determine container readiness (if it's ready to be added to the load balancer) even for ourselves - GCE requires it.

**Comment by jamilbk** [comment]
Ah, I see. So this is really just a liveness probe that can be used to determine if the Relay is alive. Telemetry / actual health metrics will be reported by the OTEL stuff you guys are working on?

**Comment by thomaseizinger** [comment]
> Ah, I see. So this is really just a liveness probe that can be used to determine if the Relay is alive. Telemetry / actual health metrics will be reported by the OTEL stuff you guys are working on?

Yes ideally OTEL or direct integration with Google's stuff but I'd like to be vendor-agnostic. Let's see if we can pull it off.
