### ISSUE TITLE
Default Web Access Ports

### ISSUE THREAD

**Issue by cipherw0lf** [CloudFire-LLC/cloudfire#2009]
**Is your feature request related to a problem? Please describe.**
While the system only needs 1 CPU core and 1GB RAM, the default config binds http/s (80 / 443) to the container host. I think most users have NPM/Traefik that occupy these ports and allow access to the other containers' services.

**Describe the solution you'd like**
Option to disable Caddy, or options to change default port settings. 
Allow use of other reverse proxies to the web app and also to handle SSL certificates.

**Additional context**
Dedicated cloud instances defeat the purpose as I believe most users require VPN for remote access to access home/company resources that are behind a firewall.

**Comment by jamilbk** [comment]
This isn't a Firezone feature per se. You're able to customize the `docker-compose.yml` file as you see fit to use a custom reverse proxy. See our docs here for more info: https://www.firezone.dev/docs/deploy/advanced/reverse-proxy
