### ISSUE TITLE
Allow users to switch between recently logged in accounts

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2015]
Use Case: I'm a contractor and I need to be able to sign into different Firezone tenants throughout my workday

Solution: 
1. We need to display a drop-down showing recent logged-in accounts in the UI;
2. Session cookies should be scoped per path so that a user can be signed into multiple accounts at the same time reducing the size of cookies we store (so that we don't hit the max size limit).

Related PR that implements recent account IDs cookie: https://github.com/firezone/firezone/pull/1990

**Comment by jamilbk** [comment]
The admin portal version of this I believe is basically done?
The client-side version of this will be more involved, can open another issue to track

**Comment by AndrewDryga** [comment]
@jamilbk it's a bit more work to switch between accounts without logging in and out, we need #2622 and then to have a simpler dropdown in the UI itself where you can select another account without going to `/`.

**Comment by jamilbk** [comment]
Ah, that's what I suspected, ok.
