### ISSUE TITLE
NAT topology testing

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2028]
See http://mininet.org/walkthrough/

**Comment by AndrewDryga** [comment]
See https://stackoverflow.com/questions/11719572/how-to-simulate-different-nat-behaviours

**Comment by thomaseizinger** [comment]
Related: I was/am working on hole-punching tests across libp2p implementations and there I use docker-compose and `nftables` to establish a NAT: https://github.com/thomaseizinger/test-plans/tree/feat/hole-punch-tests/hole-punch-interop

**Comment by jamilbk** [comment]
Refs #2538

**Comment by thomaseizinger** [comment]
I am planning to add automated tests as part of https://github.com/firezone/firezone/issues/2966.

**Comment by jamilbk** [comment]
Will be implemented with #2996
