### ISSUE TITLE
Report OTLP metrics to Google Cloud Metrics

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#2033]

**Comment by thomaseizinger** [comment]
@AndrewDryga I looked into this and it seems that this is possible but deprecated. See https://cloud.google.com/stackdriver/docs/solutions/gke/prometheus. They recommend to use the hosted prometheus service instead.

**Comment by jamilbk** [comment]
@thomaseizinger / @AndrewDryga -- Would next steps here be to add terraform config for managed prometheus in GCP?

Can add the 1.0 milestone if needed for launch.

**Comment by AndrewDryga** [comment]
We are missing the docs intent here. It's not that they recommend replacing Cloud Metrics with Prometheus, they just deprecated a direct way to export StackDriver metrics in Prometheus format via a sidecar.

We should use a library that can report them directly to Cloud Metrics. A quick googling gave me this one: https://docs.rs/opentelemetry-stackdriver/latest/opentelemetry_stackdriver/ but there can be better options.

The problem with Prometheus is that it consumes a ton of resources (depending on the db backing it up it most likely will be way more than our Panel will consume in the first production months). Plus the cost of maintaining another infrastructure component. At the very least we need to run Kubernetes cluster just to deploy Prometheus 🙃. 

Also see https://cloud.google.com/monitoring/api/metrics_other

**Comment by thomaseizinger** [comment]
> The problem with Prometheus is that it consumes a ton of resources (depending on the db backing it up it most likely will be way more than our Panel will consume in the first production months). Plus the cost of maintaining another infrastructure component. At the very least we need to run Kubernetes cluster just to deploy Prometheus 🙃.

Perhaps I am missing something but what would be wrong with using the managed Prometheus service from GCP? It charges based on how many metrics are being ingested, which ought to be fairly cheap in the first production months.

> We should use a library that can report them directly to Cloud Metrics.

There doesn't seem to be a client library for GCP in Rust unfortunately: https://developers.google.com/api-client-library/

> We should use a library that can report them directly to Cloud Metrics. A quick googling gave me this one: [docs.rs/opentelemetry-stackdriver/latest/opentelemetry_stackdriver](https://docs.rs/opentelemetry-stackdriver/latest/opentelemetry_stackdriver/) but there can be better options.

This would require a move to the open-telemetry ecosystem. I can look into that.

**Comment by thomaseizinger** [comment]
> > We should use a library that can report them directly to Cloud Metrics. A quick googling gave me this one: [docs.rs/opentelemetry-stackdriver/latest/opentelemetry_stackdriver](https://docs.rs/opentelemetry-stackdriver/latest/opentelemetry_stackdriver/) but there can be better options.
> 
> This would require a move to the open-telemetry ecosystem. I can look into that.

Unfortunately, the link library only allows exporting of spans and not metrics. I am not too familiar with the opentelemetry ecosystem but the push-based design doesn't appeal to me. It requires us to pass authentication parameters to the relay (and any other binary) instead of the runtime just retrieving the metrics on an interval.

If you feel strongly about not using the managed Prometheus service, I can look into extending https://docs.rs/opentelemetry-stackdriver/latest/opentelemetry_stackdriver/struct.StackDriverExporter.html to also support exporting of metrics.

My recommendation would be to look into using a managed Prometheus service. It is IMO the cleaner design and should be fairly frictionless to operate. For all components that ought to be self-hosted, I think it makes sense to decouple them from GCP as much as possible.

**Comment by AndrewDryga** [comment]
I might be wrong but I did not find any docs about managed Prometheus for non Kubernetes environments, eg. https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed. This means we will need to run everything in Kubernetes just to have managed Prometheus instance. I can deploy it to a VM but this is a service that will need to be maintained with our small team, and it's very resource hungry.

So if we can write metrics directly to Stackdriver that will hugely reduce our maintenance cost.

**Comment by AndrewDryga** [comment]
Would building a client for https://cloud.google.com/monitoring/api/metrics_other require a lot of work? I assume it's just a buffer data structure (eg. ring buffer) with overflow handling + client lib with a single endpoint?

**Comment by thomaseizinger** [comment]
> This means we will need to run everything in Kubernetes just to have managed Prometheus instance. I can deploy it to a VM but this is a service that will need to be maintained with our small team, and it's very resource hungry.

I am definitely not suggesting that :)

> I might be wrong but I did not find any docs about managed Prometheus for non Kubernetes environments, eg. [cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed).

The docs are a bit convoluted but I _think_ https://cloud.google.com/monitoring/agent/ops-agent/prometheus is what we'd need. From what I understand, this agent just scrapes a prometheus endpoint and ingests the data into the managed prometheus service.

> Would building a client for [cloud.google.com/monitoring/api/metrics_other](https://cloud.google.com/monitoring/api/metrics_other) require a lot of work? I assume it's just a buffer data structure (eg. ring buffer) with overflow handling + client lib with a single endpoint?

I've not looked into it. It is definitely doable but the dependency relation is IMO still wrong if we end up pushing metrics from services like the relay into stackdriver.

**Comment by thomaseizinger** [comment]
> > I might be wrong but I did not find any docs about managed Prometheus for non Kubernetes environments, eg. [cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed).
> 
> The docs are a bit convoluted but I _think_ [cloud.google.com/monitoring/agent/ops-agent/prometheus](https://cloud.google.com/monitoring/agent/ops-agent/prometheus) is what we'd need. From what I understand, this agent just scrapes a prometheus endpoint and ingests the data into the managed prometheus service.

More precisely, we'd need to:

- Install the Ops Agent on the VM that the relay is deployed to. The corresponding terraform module seems to be described here: https://registry.terraform.io/modules/terraform-google-modules/cloud-operations/google/latest/submodules/agent-policy
- Configure it similarly to this: https://cloud.google.com/monitoring/agent/ops-agent/prometheus#oagent-config-json-exporter. More specifically:

```yaml
# /etc/google-cloud-ops-agent/config.yaml:
metrics:
  receivers:
    prometheus:
        type: prometheus
        config:
          scrape_configs:
            - job_name: 'relay_exporter'
              scrape_interval: 10s
              metrics_path: /metrics
              static_configs:
                - targets: ['localhost:9090'] # We will need to configure the `METRICS_ADDR=localhost:9090` env variable for the relay to expose the metrics.
  service:
    pipelines:
      prometheus_pipeline:
        receivers:
          - prometheus
```

I'll let you make a call here. In my opinion, operating pull-based is the cleaner architecture because it decouples the relay from its runtime environment (GCE). Users that self-host the relay may do that on any cloud, not just GCE. Lastly, I'd rather build against an open standard like prometheus instead of something proprietary like Google's metrics.

**Comment by jamilbk** [comment]
I believe this is done? Closing -- if not can reopen

**Comment by thomaseizinger** [comment]
It is not unfortunately. Depends on https://github.com/open-telemetry/opentelemetry-rust-contrib/issues/10.

**Comment by thomaseizinger** [comment]
https://github.com/firezone/firezone/pull/2050 adds and configures an OTLP exporter for traces for the relay. Let's see if that works will with the ops agent side-car.

**Comment by jamilbk** [comment]
I think @AndrewDryga implemented some version of this? Can this be closed?

**Comment by thomaseizinger** [comment]
> I think @AndrewDryga implemented some version of this? Can this be closed?

I am not aware that we export any metrics at the moment.

**Comment by thomaseizinger** [comment]
We actually are recording metrics!

https://console.cloud.google.com/monitoring/metrics-management?referrer=search&project=firezone-staging&pageState=(%22metricsTableFilter%22:(%22p%22:12))
