### ISSUE TITLE
relay: benchmarking

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#2039]
We should do some basic benchmarking to have a rough idea of the performance that we can get out of the relay.

Most importantly, we should work out good defaults for buffer sizes based on the expected up/down link and latency that we will be deploying to.

**Comment by jamilbk** [comment]
Noting here that it would be good to add this information to our docs since it will be useful for users.

**Comment by jamilbk** [comment]
I think we now have some basic benchmarking in each PR. Can reopen this if/when it becomes an issue.
