### ISSUE TITLE
Prevent demoting yourself

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2057]
It would be good to prevent demoting yourself from an Admin to regular user, especially if you're the only remaining Admin in the system.

<img width="979" alt="Screenshot 2023-09-13 at 6 10 55 AM" src="https://github.com/firezone/firezone/assets/167144/100bb269-44ec-479c-9288-2866c9ac7549">

**Comment by AndrewDryga** [comment]
This is already done, you can demote yourself as long as there is at least one other active admin exists. Same for IdPs - you can disable/remove them as long as at least one remains active.

**Comment by AndrewDryga** [comment]
Related code: https://github.com/firezone/firezone/blob/main/elixir/apps/domain/lib/domain/actors.ex#L232

**Comment by jamilbk** [comment]
Thanks for confirming 🙏🏼
