### ISSUE TITLE
Pass logging filters from app / env to connlib

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2067]
Instead of using `debug_assertions` to control what's logged, allow the calling application to pass a string through `connect` to determine what to log.

**Comment by conectado** [comment]
For some of the performance tests I already had to change how I start the logger in the client/gateway, adding a way to configure the logger through clap in an unified manner, let me create a PR later with these changes and we can discuss it there.

**Comment by jamilbk** [comment]
Note to add support for two different logging levels in Swift in Kotlin to pass to clients.

**Comment by jamilbk** [comment]
Closed by #2115
