### ISSUE TITLE
Copied command from "Deploy gateway instance" page includes HTML tags

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#2075]
**Describe the bug**

Clicking on the little "copy" button on the bottom right copies the command but it also includes HTML tags like `<br>`.

**To Reproduce**

Make a new resource group and copy the displayed command.

**Expected behavior**

A functional command.

**Screenshots / Logs**
[Screencast from 2023-09-18 16-32-22.webm](https://github.com/firezone/firezone/assets/5486389/ad3355c4-9469-455b-984e-c0f7032c1828)

(Resource group has been deleted so the displayed token is useless.)

**Comment by AndrewDryga** [comment]
Probably the same bug will be there when copying the relay command.

**Comment by bmanifold** [comment]
This should be fixed by https://github.com/firezone/firezone/pull/2515
