### ISSUE TITLE
Connlib does not check for longest route for conflicting resources

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2091]
Use case:
- admin defines a resource 0.0.0.0/0 and then 1.1.1.1
- user connects to 2.2.2.2 which creates a peer that serves 0.0.0.0/0 (all ips)
- the user opens 1.1.1.1 and the traffic still flows through the gateway serving 0.0.0.0/0

What needs to be done:
- we need to always check if there is a resource with a more specific route on every new connected address

**Comment by jamilbk** [comment]
Feedback from customer was that we can't (shouldn't) assume what route takes precedence, and just expose routing priority to advanced users in the clients.

This will need some UI changes on the clients, have some ideas in #3514
