### ISSUE TITLE
Okta SAML Integration Not Working

### ISSUE THREAD

**Issue by prsf1233** [CloudFire-LLC/cloudfire#2111]
Firezone V0.7.35
Okta

I have configured the Okta tenant and Firezone as per the documentation. When users login they get:

invalid_request unknown IdP

This looks similar to issue 1341 that is fixed in 0.74?

**Comment by jamilbk** [comment]
Thanks for the report @prsf1233 -- usually this happens due to a misconfiguration of some sort. Nothing has changed with our SAML integration in quite some time. Perhaps double-check the config ID, ACS URL, and entity ID?

**Comment by prsf1233** [comment]
Thanks for the hint, I had misspelt the config id.
