### ISSUE TITLE
Unable to add OpenID Connect Provider

### ISSUE THREAD

**Issue by RenneNiku** [CloudFire-LLC/cloudfire#2122]
**Describe the bug**
When trying to add new OpenID Connect Provider via Security -> Add OpenID Connect Provider dialog the following happens:
- I fill in the fields
- Press Save
- The dialog gets cleared, but it stays in the screen
-  I close the dialog, cannot see any OpenID providers listed
 - Reload he page, provider still no providers listed

**To Reproduce**
In my environemnt, just doing the steps above

**Expected behavior**
New OpenId provider would have been listed on the page

**Screenshots / Logs**
 - The same time I press `Save` in the dialog the following is appears in the log:
 
``firezone             | 08:01:50.367 erl_level=error domain=otp file=gen_server.erl function=error_info/8 line=1402 mfa=:gen_server.error_info/8 module=gen_server pid=<0.538.0> [error] GenServer #PID<0.538.0> terminating
firezone             | ** (stop) exited in: :gen_statem.call(#PID<0.561.0>, {:start, 5000}, :infinity)
firezone             |     ** (EXIT) an exception was raised:
firezone             |         ** (CaseClauseError) no case clause matching: {:error, {:asn1, {:bad_range, [{:"OTP-PUB-KEY", :"dec_OTP-X520countryname", 2, [file: '../src/OTP-PUB-KEY.erl', line: 17787]}, {:"OTP-PUB-KEY", :decode, 2, [file: '../src/OTP-PUB-KEY.erl', line: 1233]}, {:pubkey_cert_records, :transform, 2, [file: 'pubkey_cert_records.erl', line: 65]}, {:lists, :map, 2, [file: 'lists.erl', line: 1315]}, {:pubkey_cert_records, :transform, 2, [file: 'pubkey_cert_records.erl', line: 92]}, {:pubkey_cert_records, :decode_tbs, 1, [file: 'pubkey_cert_records.erl', line: 332]}, {:pubkey_cert_records, :decode_cert, 1, [file: 'pubkey_cert_records.erl', line: 42]}, {:public_key, :pkix_decode_cert, 2, [file: 'public_key.erl', line: 521]}]}}}
firezone             |             (public_key 1.13.2) pubkey_cert_records.erl:65: :pubkey_cert_records.transform/2
firezone             |             (stdlib 4.2) lists.erl:1315: :lists.map/2
firezone             |             (public_key 1.13.2) pubkey_cert_records.erl:92: :pubkey_cert_records.transform/2
firezone             |             (public_key 1.13.2) pubkey_cert_records.erl:332: :pubkey_cert_records.decode_tbs/1
firezone             |             (public_key 1.13.2) pubkey_cert_records.erl:42: :pubkey_cert_records.decode_cert/1
firezone             |             (public_key 1.13.2) public_key.erl:521: :public_key.pkix_decode_cert/2
firezone             |             (public_key 1.13.2) public_key.erl:1104: :public_key.pkix_subject_id/1
firezone             |             (ssl 10.8.6) tls_handshake_1_3.erl:1531: :tls_handshake_1_3.split_cert_entries/4
``

**Platform (please complete the following information):**
 - Firezone Version 0.7.35 .Same happens with 0.7.34
 - OS: Linux
 - Distro: Ubuntu 20.04
 - Kernel version: 5.4.122
 - Deployment method: Docke Compose

**Additional context**
- This is fresh installation. 
- Using Caddy v2.6.2 as reverse proxy, with **self-signed** certificates
- Tried adding OpenID connector with authelia (4.37) or authentik (2023.8.3) with same results. Both are self-hosted with self-signed certificates.

**Comment by RenneNiku** [comment]
This is probably about self-signed certificates. I was able try with same Firezone and Autlhelia versions, but using certificates from Let's Encrypt. OpenID provider was correctly added and it is working. So I guess the question is how to I make Firezone work with Authelia that is having self-signed certificates.
I'm assuming I should probably be setting `HTTP_CLIENT_SSL_OPTS`, but unfortunately the docs have no example, so don't have a clue what the variable should contain.
If I run `openssl s_client -verify_return_error -connect authelia.host.intranet:443  -CAfile ca_chain.pem` the verification passes.. So I guess I should tell Firezone to use the same `ca_chain.pem` when verifying the certificate from authelia?

**Comment by jamilbk** [comment]
Hi @RenneNiku -- you'll need to specify the `HTTP_CLIENT_SSL_OPTS` env var to configure Erlang's `ssl` module appropriately. See docs here: https://www.firezone.dev/docs/reference/env-vars#webserver

**Comment by RenneNiku** [comment]
@jamilbk But exactly how should I define that variable, the docs don't show any examples ( and I don't have any knowledge about Erlang either)

**Comment by jamilbk** [comment]
@RenneNiku It depends on what exactly you're trying to achieve with regards to self-signed certificates.

Try `{"cacertfile":"/path/to/pem-encoded-custom-cacerts.pem"}`

https://www.erlang.org/doc/man/ssl#type-client_option

**Comment by RenneNiku** [comment]
Thank you for the example @jamilbk 

I defined it like this:

`HTTP_CLIENT_SSL_OPTS={ "cacertfile": "/tmp/ca_chain.pem"}` in docker-compose .env -file.

and tried to add OpenID connector. Got he following:

``
firezone             | 07:41:58.426 erl_level=notice file=ssl_pkix_db.erl function=decode_cert/2 line=339 mfa=:ssl_pkix_db.decode_cert/2 module=ssl_pkix_db pid=<0.153.0> [notice] SSL WARNING: Ignoring a CA cert as it could not be correctly decoded.~n
firezone             | 07:41:58.426 erl_level=notice file=ssl_pkix_db.erl function=decode_cert/2 line=339 mfa=:ssl_pkix_db.decode_cert/2 module=ssl_pkix_db pid=<0.153.0> [notice] SSL WARNING: Ignoring a CA cert as it could not be correctly decoded.~n
firezone             | 07:41:58.437 erl_level=error domain=otp file=gen_server.erl function=error_info/8 line=1402 mfa=:gen_server.error_info/8 module=gen_server pid=<0.3062.0> [error] GenServer #PID<0.3062.0> terminating
firezone             | ** (stop) exited in: :gen_statem.call(#PID<0.3080.0>, {:start, 5000}, :infinity)
``

After that the same error as above (`(CaseClauseError) no case clause matching` and so on...)

If I exec into firezone container and inside the container run 
`openssl s_client -verify_return_error -connect authelia.host.intranet:443  -CAfile /tmp/ca_chain.pem` I  get verification OK. So the file is there, and openssl thinks it is OK, but apparently the CA file  has something the used library dislikes.
