### ISSUE TITLE
Send portal telemetry to Stackdriver

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2141]
We want to send OTEL metrics to Google Ops (ex Stackdriver). Currently, metrics are in beta for Elixir so we should test them out and wait for a stable release if they don't work from first attempt.

**Comment by jamilbk** [comment]
Waiting on Elixir client for OT to implement metrics

**Comment by AndrewDryga** [comment]
Dupe of #2014
