### ISSUE TITLE
Combine `PhoenixChannel` implementations

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2158]
- [ ] Combine the PhoenixChannel implementations between clients and relay
- [ ] Consider accepting a `String` for the `url` param in the `new` call along with a list of parameters to be added to the query string. This would allow us to pass `Secret`s all the way to _just before_ the connecting library

**Comment by thomaseizinger** [comment]
Re-posting a chat I had with @conectado on Slack the other day:

> While working on the log upload, I came across the following comment: https://github.com/firezone/firezone/blob/e635ee377412b8040e9bcac4bf24ca0caed8b104/rust/connlib/libs/common/src/session.rs#L298-L300

> Thinking about it a bit more, I think we can resolve that if:
> - PhoenixChannel would be implemented as a state machine that emits events rather than taking a handler
> - T: ControlSession gets a new function fn tunnel(&self) -> &Tunnel 

> Session can then have a loop that reads events from PhoenixChannel and hands them over to the Tunnel. Because it is a single loop, you are guaranteed to finish all work on the tunnel related to an event before you read the next event from the websocket.

**Comment by thomaseizinger** [comment]
> PhoenixChannel would be implemented as a state machine that emits events rather than taking a handler

The `phoenix-channel` crate already operates in this manner which is how this issue is related to the above.

**Comment by jamilbk** [comment]
Was this completed? I think we still have PhoenixChannel in connlib and also as a crate in the workspace.

**Comment by thomaseizinger** [comment]
> Was this completed? I think we still have PhoenixChannel in connlib and also as a crate in the workspace.

It was partly and the PR description was worded poorly which accidentially closed this. We can only meaningfully tackle this once `firezone-tunnel` has been entirely de-asyncified which is still a while away.
