### ISSUE TITLE
Connlib: retrieve interface name for filtering ICE candidates

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#2163]
Follow up from https://github.com/firezone/firezone/pull/2152#discussion_r1337483918

**Comment by jamilbk** [comment]
@conectado I think we already have this in all the `tun_*` implementations, we just need to make it available to the WebRTC settings_engine:

https://github.com/firezone/firezone/blob/main/rust/connlib/tunnel/src/device_channel/tun/tun_android.rs#L157

**Comment by jamilbk** [comment]
Fixed by #2335
