### ISSUE TITLE
connlib: move control protocol specific to gateway/client from tunnel to gateway/client crate in control module 

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#2187]
It'll be much easier moving forward to move the functions specific to gateway/client in the tunnel to the gateway/client crates(respectively). This should be easy since they are already in separated modules. 

This will also remove the `signal_ice_candidate` from `ControSignal`.

### Note for implementor
The files that need moving are:
`rust/connlib/libs/tunnel/src/control_protocol/clien.rs`
`rust/connlib/libs/tunnel/src/control_protocol/gateway.rs`

to

`rust/connlib/libs/client/src/control.rs`
`rust/connlib/libs/gateway/src/control.rs`

**Comment by thomaseizinger** [comment]
Taking this over as discussed.

I am afraid it is not going to be _that_ easy. These functions currently access private state on `Tunnel`. How would you like that resolved? I think we will have to come up with a shared, public low-level interface that can be used by both modules.

**Comment by conectado** [comment]
> Taking this over as discussed.
> 
> I am afraid it is not going to be _that_ easy. These functions currently access private state on `Tunnel`. How would you like that resolved? I think we will have to come up with a shared, public low-level interface that can be used by both modules.

@thomaseizinger I was thinking it'd be fine to just make public some fields of the `Tunnel` struct, we can encapsulate that in another struct to make it cleaner.

**Comment by jamilbk** [comment]
Is this issue still relevant post-snownet?

**Comment by thomaseizinger** [comment]
No I think we are going to take a different approach.

**Comment by thomaseizinger** [comment]
See https://github.com/firezone/firezone/issues/3837.
