### ISSUE TITLE
Massive memory allocation prevents firezone container from starting

### ISSUE THREAD

**Issue by stefan-golinschi** [CloudFire-LLC/cloudfire#2216]
**Describe the bug**
Firezone container fails to start due to massive memory allocation failure.

**To Reproduce**
To reproduce,  install Firezone using docker automated install.

**Expected behavior**
Firezone container should start normally.

**Screenshots / Logs**
```
ll_alloc: Cannot allocate 1610612799 bytes of memory (of type "port_tab").
```

**Platform (please complete the following information):**
 - Firezone Version: `0.7`
 - OS: Linux
 - Distro: RockyLinux 9.2
 - Kernel version: `5.14.0`
 - Deployment method: Docker

**Comment by jamilbk** [comment]
This an Erlang issue that seems to crop up from time to time with Rocky Linux users:

https://rabbitmq-users.narkive.com/OtHXmuO6/rabbitmq-discuss-ll-alloc-errors-on-rabbitmq-2-1-1
https://discourse.firez.one/t/excessive-allocated-memory/321

Unfortunately we haven't been able to determine a root cause, as the issue is in the underlying BEAM runtime which we don't have much control over.

What does `ulimit -n` report? Some users have reported success lowering that to something reasonable.

**Comment by stefan-golinschi** [comment]
Ultimit reports `1024`. Maybe 1G Ram on my vps si just not enough?

```
[root@local]# ulimit -n
1024
```

**Comment by jamilbk** [comment]
1 GB _should_ be enough RAM. Erlang shouldn't be trying to allocate 1.6 GB of memory. For some reason Rocky seems to trigger this bug -- if you try another distro it should work fine.

Just to be sure the issue isn't within the container, what does `ulimit -a` report inside a docker container?

e.g. `docker run --rm bash bash -c "ulimit -a"`

**Comment by stefan-golinschi** [comment]
```
[root@local ]# docker run --rm bash bash -c "ulimit -a"

real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 2726
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1073741816
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Comment by jamilbk** [comment]
Aha -- there's the issue. The Docker daemon on Rocky looks to be configured with a massive open files limit. Try adding this to your `firezone` service in your `~/.firezone/docker-compose.yml`:

```
  ulimits:
    nofile:
      soft: "65536"
      hard: "65536"
```
