### ISSUE TITLE
Docker image versioning

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2223]
- ### Relay/Gateway (published)
  - [ ] Publish to _both_ ghcr.io and Docker Hub on release publish (public consumption)
  - [ ] Standard `1.YYYYMMDD.patch` versioning + latest
- ### Web/API/Gateway/Relay (internal / staging)
  - [x] Publish to GCP Artifact Registry (private, accessible to Firezone team only)
  - [x] Standard versioning + GitHub SHA suffix, e.g. `1.20231001.3-deadbeef`

**Comment by jamilbk** [comment]
@AndrewDryga Is that what you had in mind ^?

**Comment by AndrewDryga** [comment]
@jamilbk yes, maybe we should tag the rust parts with sha1 too though? Will make it much easier to find which exact commit is running from the logs.
