### ISSUE TITLE
Clicking "Sign in with Google Workspace" in Chrome on Android opens the system's Google Account manager

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2226]
See attached video. Strange bug indeed. I think our URL might be slightly wrong, or need a param added to it.

https://github.com/firezone/firezone/assets/167144/29c55ce8-96f9-4131-a891-7ecc0f2b9128

**Comment by jamilbk** [comment]
@pratikvelani Is there anything on the Android side that would be causing this? Link seems to work fine on other platforms.

**Comment by jamilbk** [comment]
This is on a OnePlus One with LineageOS 18 (Android 11, SDK 30)

**Comment by AndrewDryga** [comment]
This is really weird, more like an Android bug 🤷‍♂️.

> I think our URL might be slightly wrong

We don't generate it ourselves, Google Workspace provider is just an OIDC one.

**Comment by jamilbk** [comment]
Kk @pratikvelani is investigating I believe

**Comment by jamilbk** [comment]
Seems to be a bug only with me.
