### ISSUE TITLE
Investigate labelling of docker images

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#2269]
I think what happens at the moment is that we push every newly built image (even from PRs) under the label `latest`. However, I _think_ `latest` should mean "latest stable version". I think https://github.com/docker/metadata-action can handle this by only applying `latest` for tag which are effectively releases.

**Comment by AndrewDryga** [comment]
We have separate production and staging registries, so latest on staging doesn't mean much.

**Comment by thomaseizinger** [comment]
> We have separate production and staging registries, so latest on staging doesn't mean much.

Perhaps it should mean latest master? If we don't have any use for it, should we tag it at all?

**Comment by AndrewDryga** [comment]
We can use that tag only for whole image caching but yeah - I would rather label with a branch name instead of it.

**Comment by jamilbk** [comment]
Between https://github.com/firezone/firezone/issues/2269 and #2223 I believe this can be closed
