### ISSUE TITLE
Consider AlwaysOnVpn for Android

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2308]
Enable tunnel on reboots.

Determine if we can configure the Always On behavior.

**Comment by jamilbk** [comment]
Deliverable here would be end-user instructions to enable "Always On" for the firezone tunnel.

Need to make sure there's not an issue where Android restarts TunnelService endlessly and connlib keeps `onDisconnect`ing

**Comment by pratikvelani** [comment]
- When user switches on `Always-on VPN`, our TunnelService is re-runs, and it tries to connect with the saved token. If the token is valid it connects successfully, else it disconnects and the system shows a notification on the device stating the VPN service is disconnected.
- When the device is restarted, our service is started, but it fails to connect and the device shows the disconnected notification.

### Enabling Always-on VPN
[always_on_vpn.webm](https://github.com/firezone/firezone/assets/1523745/71217c63-fc39-4048-9df4-9519042cf072)

### VPN disconnected notification
![Screenshot_20231101_174622](https://github.com/firezone/firezone/assets/1523745/1e284f8c-50df-4d20-915e-90904a3d96a7)

### Reference
https://developer.android.com/develop/connectivity/vpn#always-on

**Comment by jamilbk** [comment]
This has been tested to work
