### ISSUE TITLE
More than 100 devices per user

### ISSUE THREAD

**Issue by itsazzad** [CloudFire-LLC/cloudfire#2323]
**Is your feature request related to a problem? Please describe.**
```
ERROR! Config provider Config.Reader failed with:
** (RuntimeError) Invalid configuration for 'max_devices_per_user' retrieved from environment variable MAX_DEVICES_PER_USER.

Errors:

 - `999`: must be less than or equal to 100
```
**Describe the solution you'd like**
I want unlimited devices per user

**Describe alternatives you've considered**
999

**Additional context**

**Comment by jamilbk** [comment]
@itsazzad Sorry, we're not going to increase this. You're free to fork the repo and [build](https://www.firezone.dev/docs/deploy/advanced/build-from-source) your own [Docker image](https://github.com/firezone/firezone/blob/legacy/Dockerfile.prod) to set the limits you need to, though.
