### ISSUE TITLE
Run integrations tests with `debug_assert`s

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#2339]
At the moment, we are running the integration tests in CI in release mode. I don't think that is very useful because it means we opt-out of all `debug_assert`s within in the code.

**Comment by jamilbk** [comment]
@thomaseizinger Hmm yeah, it might be useful to expose log level as a separate build / ENV var, defaulting to the current `Debug` and `Release` behavior we have now if left unset. I was thinking the same when considering how we'll test the client apps in CI.

**Comment by thomaseizinger** [comment]
I am not talking about the log level though. I am talking about not using `--release` for the Rust crates. That removes all `debug_assert`s from the code and turns them into noop to avoid crashes at runtime. But the whole point of `debug_assert`s is that you can crash during testing and notice bad problems early :)

**Comment by jamilbk** [comment]
@thomaseizinger Gotcha, thanks for clarifying. Makes sense.

**Comment by jamilbk** [comment]
This has been completed as of last week. Refs #2344
