### ISSUE TITLE
Namespace connlib log filename

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2354]
Log files should be easily findable for a particular account-user-client tuple. To do this, we just to prepend the UUIDv4 `client_id` to the log filename. From there we can find the client, and correspondingly user and account the log belongs to.

**Comment by AndrewDryga** [comment]
I think this is a portal issue, we can just slightly change the path structure here: https://github.com/firezone/firezone/blob/main/elixir/apps/domain/lib/domain/instrumentation.ex#L16C1-L16C1
