### ISSUE TITLE
macOS menubar icon stuck in half-connected icon state

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2356]
Not sure how this one happened, but figured I'd document it here in case we hit it again.

<img width="264" alt="Screenshot 2023-10-16 at 1 06 27 PM" src="https://github.com/firezone/firezone/assets/167144/67738fc6-470d-4071-9764-cfad96438c23">

**Comment by jefferenced** [comment]
Video recording of this bug happening (and some troubleshooting). https://www.loom.com/share/199a453f66c24d0ab87f2797c895d66c?sid=5e02b5d1-d61a-4743-8491-8195e0ca8d13

**Comment by roop** [comment]
@jefferenced The app is meant to do that animation thingie only when the tunnel is connecting or reasserting (which should happen only when signed in), or disconnecting. The video starts with the icon doing that animation wrongly. Was the app already running when you noticed it? Or did you launch it and then it did that?

Edit: Sorry, I just saw the video with sound on. You said something in the video about when you hit the bug, but I couldn't catch that. Can you please clarify?

**Comment by jamilbk** [comment]
@roop Jeff had demo'd this on the call -- the app was in the signed out state with the tunnel down if that's helpful information

**Comment by jefferenced** [comment]
@roop great timing! I was just able to recreate the bug from scratch, and record it. https://www.loom.com/share/62b2ec4c8f9e449aa811e33e69dee361?sid=2b0395d6-29ed-4451-8100-fd81541dfe0b If you have any additional questions please let me know.

**Comment by jamilbk** [comment]
Should be fixed in https://github.com/firezone/firezone/pull/2846
