### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2369]
### Firezone User story

As a Firezone API consumer, I'd like to be able to understand how the REST API works and quickly integrate it to my existing tools.

Nice to haves:
- Publish a public Postman collection
- Import an OpenAPI spec

### Firezone Developer story

- As a Firezone engineer, I'd like to be able to easily maintain the API documentation whenever endpoints or schemas change in backwards-compatible ways.
- As a Firezone engineer, I'd like to be able to generate new API version documentation when we publish a new API version

This doesn't need to be overly-complex. We can start with a simple markdown document (or directory structure in the website) and have the API tests generate example json files for each endpoint, then load these into the website docs.

**Comment by jamilbk** [comment]
I think one workflow that could work well is:

- Keep API docs in Postman as source of truth
- Re-publish these using [Postman's API](https://learning.postman.com/docs/developer/postman-api/intro-api/) when a new Firezone release is `Publish`ed from the repo. See @AndrewDryga's [work on docs generation](https://github.com/firezone/firezone/blob/main/elixir/apps/web/test/support/documentation/docs_generator.ex) -- maybe we can refactor this to publish to Postman instead?
- Users can then interact with our public Postman API, or export to OpenAPI or any other format from there

**Comment by jamilbk** [comment]
@bmanifold Edited the description to hopefully keep this simple. It still may be a bit too ambitious.

**Comment by Intuinewin** [comment]
In my opinion, having an openapi spec in the repo would be very useful. It allows you to understand and test the API easily with swagger or to generate API clients in multiple languages (for example in golang to help write a terraform provider :eyes:)

**Comment by jamilbk** [comment]
@Intuinewin Valid points! Perhaps there is a way to keep the API docs in this repo and publish to Postman in CI. From there it looks like we can do all kinds of things with it, including exporting an OpenAPI spec.

**Comment by jamilbk** [comment]
Merged OpenAPI spec served from app itself to enable live API testing.
