### ISSUE TITLE
Configure `sccache` GCP bucket in Terraform

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2443]
https://github.com/firezone/firezone/actions/runs/6570197255/job/17847265431?pr=2344

I think some GitHub runners are IPv6-only (or prefer IPv6), which occasionally causes the build to fail when external resources don't have `AAAA` records.

@thomaseizinger Maybe this is why the `webrtc` ref wasn't found earlier today? github.com is notorious for lacking AAAA records in 2023

**Comment by jamilbk** [comment]
Can be temporarily worked around using our own dedicated GH runners since they can be allocated a static IPv4. Trying that for now.

**Comment by thomaseizinger** [comment]
Wow, that is a new one :joy:

**Comment by jamilbk** [comment]
@thomaseizinger Actually, I think this is a different issue. Somehow, sccache is _intermittently_ using internal GCP URLs (`metadata.google.internal`) when trying to fetch cache entries:

https://github.com/firezone/firezone/actions/runs/6574879404/job/17860901810?pr=2344

Perhaps it's a bug with the cache backend?

**Comment by jamilbk** [comment]
Updating the title / issue to reflect setting this configuration in terraform instead. Need to ensure GCP is giving us only publicly-accessible URLs for cache objects.

**Comment by jamilbk** [comment]
I think some of these need to be adjusted:

- Can probably be a publicly readable cache
- Retention policy can be fairly short (30 days?)

<img width="751" alt="Screenshot 2023-10-19 at 6 30 26 AM" src="https://github.com/firezone/firezone/assets/167144/15cbae27-982f-4322-a592-cb40fc8a2598">

**Comment by jamilbk** [comment]
I think this issue turned out to resolve itself
