### ISSUE TITLE
[NET] peer() - Handshake did not complete after 5 seconds, retrying (try )

### ISSUE THREAD

**Issue by itsazzad** [CloudFire-LLC/cloudfire#2445]
**Describe the bug**
Starting from the sixth device handshake failing

**To Reproduce**
Try to connect the device and the handshake never happens

**Expected behavior**
It should be able to connect at least to the maximum allowed number of devices.

**Screenshots / Logs**
![IMG_1958](https://github.com/firezone/firezone/assets/54909/052ef40d-78ee-4bf9-b478-748a97a542bd)

**Platform (please complete the following information):**
 - Firezone Version: 0.7.35
 - OS: Linux
 - Distro: Ubuntu 22.04
 - Kernel version: 5.15.0-67-generic
 - Deployment method: Docker

**Additional context**
5 out of 23 devices can complete a handshake successfully
1 GB Memory / 25 GB Disk / SYD1 - Ubuntu 22.04 (LTS) x64
![image](https://github.com/firezone/firezone/assets/54909/6fb333b1-f9af-40f8-a787-7d3ea61e0cce)
[wireguard-log.txt](https://github.com/firezone/firezone/files/13044660/wireguard-log.txt)

**Comment by jamilbk** [comment]
This is an issue outside of Firezone's scope -- WireGuard handshake could be blocked, but there won't be anything we can do in Firezone about this.
