### ISSUE TITLE
PostUp and PostDown Scripts

### ISSUE THREAD

**Issue by bensonrlee** [CloudFire-LLC/cloudfire#2447]
**Is your feature request related to a problem? Please describe.**
Is there a possibility to introduce PostUp and PostDown scripts.
Similar to #1146 , #1150 , #1151 

**Describe the solution you'd like**
In the configuration files that are generated, introduce the possibility to provide PostUp and PostDown scripts.

**Describe alternatives you've considered**
Manually adjusting the files.

**Additional context**

**Comment by jamilbk** [comment]
Hey @bensonrlee -- Firezone 0.7 is currently EOL and we won't be able to add support for these. I think the 1.0 gateway should probably solve the use case you're aiming for, but if not, custom iptables rules can always be used too.
