### ISSUE TITLE
`roll_log_file()` returns `None` on apple

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2461]
Log file upload isn't being attempted because `roll_log_file()` in always returns `None` in `rust/connlib/clients/shared/src/control.rs`: https://github.com/firezone/firezone/blob/main/rust/connlib/clients/shared/src/control.rs#L227

**Comment by thomaseizinger** [comment]
Haha, it wasn't included in the FFI bridge. Booooo.

**Comment by jamilbk** [comment]
Ahh, good catch!

**Comment by thomaseizinger** [comment]
Hmm but it shouldn't need to.

**Comment by thomaseizinger** [comment]
See https://github.com/firezone/firezone/blob/124e08c13bd6241d1710ea3a019e7749c642daec/rust/connlib/clients/apple/src/lib.rs#L139-L146

**Comment by jamilbk** [comment]
Yeah, strange that's not being call. I added a `debug!` to the shared callbacks and verified that one's being called instead. I wonder if maybe `self` is a different context? Or maybe all the `self.tunnel.callbacks()` are calling the wrong callback in `control.rs`?

**Comment by jamilbk** [comment]
It's not on the CallbackErrorFacade, maybe that's it?

**Comment by thomaseizinger** [comment]
It is.

**Comment by jamilbk** [comment]
I'll push up a fix since I'm already deep in it :-)

**Comment by thomaseizinger** [comment]
Too slow :)
