### ISSUE TITLE
Provide health-check endpoint for gateway

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2465]
Similarly to the relay, anyone running the gateway will want an HTTP endpoint for health-checks.

We also want OLTP metrics and traces exported, JSON logs, similarly to relay.

**Comment by AndrewDryga** [comment]
@conectado is this one hard to do? It will help a lot in debugging connectivity with IPv6-like issues on prod to have it run within the gateway itself and detect failures after deployment

**Comment by jamilbk** [comment]
Now a customer ask

**Comment by thomaseizinger** [comment]
> Now a customer ask

Just the health-check or also the OTLP metrics and JSON logs as mentioned in the original ticket?

**Comment by jamilbk** [comment]
Let's make this issue about the healthcheck and split the OTEL stuff into another issue
