### ISSUE TITLE
Relay routing

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2472]
Options for beta:
- STUN-only (no Relaying)
- Managed Relays

## Todo
- [x] Portal UI / DB changes
- [x] Distribute setting to clients

Other potential routing options, but don't include these for now:
- Self-hosted Relays
- TURN-only (Relaying *only*)

**Comment by jamilbk** [comment]
![](https://share.balsamiq.com/c/sG3gaW5CxqLDTLhpo8xRFb.png)

**Comment by bmanifold** [comment]
This issue should be completed by PR https://github.com/firezone/firezone/pull/2610
