### ISSUE TITLE
Connections to the Portal from Docker containers can't be upserted

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2482]
Gateways started within a Docker container don't have access to the system's `SMBios` or any other identifiable parameters (such as a hostname) suitable to identify the Gateway for upserting (this is the idea of containers, after all)

By default, a containers `hostname` is its container ID:

```
jamil@Jamils-MacBook-Air:~ % docker run -it alpine uname -a
Linux 69361b814d9b 6.4.16-linuxkit #1 SMP PREEMPT Tue Oct 10 20:38:06 UTC 2023 aarch64 Linux
jamil@Jamils-MacBook-Air:~ % docker run -it alpine uname -a
Linux a39f13381d89 6.4.16-linuxkit #1 SMP PREEMPT Tue Oct 10 20:38:06 UTC 2023 aarch64 Linux
```

This means a new Gateway is created each time a Docker container is created, so the list of Gateways belonging to a particular Instance group grows unbounded if a Gateway with `--restart=always` is crash looping.

This creates a major usability issue with admins trying to understand which Gateways authorized which flows because authorizations are tied to the instances.

We may need another token or some form of state that can be used to identify Gateway instances for upsert

<img width="3120" alt="Screenshot 2023-10-22 at 10 32 17 AM" src="https://github.com/firezone/firezone/assets/167144/453b0205-b8b4-4f29-ae91-3d1aceb10aec">

**Comment by jamilbk** [comment]
This is actually part of a larger issue -- anything connecting to the portal from a Docker container can't be upserted unless we maintain some form of state to identify it.

UI clients don't have this issue because they maintain state.

**Comment by AndrewDryga** [comment]
The plan to solve this one is to introduce two options to fix the external ID:
1. CLI argument/ENV variable to pass it explicitly 
2. Any generated value should be persisted in a file at well known location.

This way devops people that don't like to the a mess can either attach persistent volume or get identifier from a higher level environment.

**Comment by jamilbk** [comment]
Gotcha. If I'm understanding correctly -- the ID of the gateway instance will be supplied by the user? In that case, should we require this parameter at runtime if `SMBios` isn't available? Or perhaps just always require it and not rely on `SMBios`? Will we enforce this ID parameter to be unique within an Account? Or just unique within the Instance Group?

I think the common case is that users will be expecting Gateway sessions to be sticky and reliably upserted, so would the docs then be something like:

```shell
# Create a unique identifier for this gateway
id="$(uuidgen)"

# specify the instance group token
token=<token from portal>

# now launch a sticky gateway instance
firezone-gateway --token $token --id $id
```

**Comment by jamilbk** [comment]
cc @bmanifold -- this may affect the one-liner docker command we show the users.

**Comment by bmanifold** [comment]
What happens if two gateways are started with the same `id`?  Does the last gateway to come online with that `id` win?

**Comment by AndrewDryga** [comment]
@bmanifold right now they both will join and receive all the messages (connection requests, ICE candidates, etc) which might break everything (most likely) or be called a feature `hot-standby-gateways` 🤣
