### ISSUE TITLE
Upgrade to 1.0?

### ISSUE THREAD

**Issue by xeruf** [CloudFire-LLC/cloudfire#2495]
I just stumbled upon this project searching for a VPN solution to replace our homebrewed stuff.
We need to get something running this week on our hardware. Is it advisable to start with the current version, will upgrading to 1.0 be possible?

**Comment by jamilbk** [comment]
Thanks for the question -- and apologies for the lack of clarity. We're in a bit of a transitionary period as we work to launch 1.0.

Unfortunately upgrades won't be possible. 1.0 is a completely new architecture, with a cloud-hosted admin UI.

The good news is it's much easier to set up. You'll only need to install a macOS/iOS/Android/Linux client and deploy a stateless Gateway.

The `legacy` branch of this repo tracks the `0.7` release. If you want to queue up for early access to take 1.0 for a spin, see https://firezone.dev/product/early-access

cc @jefferenced
