### ISSUE TITLE
Can't create Service Accounts

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2501]
Seem to be getting a 404 when trying to create a Service Account:

<img width="1408" alt="Screenshot 2023-10-24 at 5 52 31 PM" src="https://github.com/firezone/firezone/assets/167144/b5984d58-d75d-4760-bb64-f7c5c649af70">

**Comment by AndrewDryga** [comment]
The issue is here: https://github.com/firezone/firezone/blob/main/elixir/apps/web/lib/web/live/actors/service_accounts/new.ex#L8. We need to separately catch the case when a Token provider is not enabled and show a page with a button to enable it in order to use Service Accounts feature.

**Comment by jamilbk** [comment]
Gotcha -- would the token provider be shown here?

<img width="1439" alt="Screenshot 2023-10-24 at 9 52 46 PM" src="https://github.com/firezone/firezone/assets/167144/f52b009a-2cf8-4c7b-8ffc-b60e95daa0a9">


If so, can we just enable it behind the scenes all the time and hide it here? From a user's perspective I think having to enable a Token provider to create Service Accounts is a bit non-intuitive.

**Comment by AndrewDryga** [comment]
Yeah, we need to upsert it on that page.
