### ISSUE TITLE
[Feature] Firezone auto disable user if user dont exist keycloak

### ISSUE THREAD

**Issue by patsevanton** [CloudFire-LLC/cloudfire#2511]
Hi, Team.
I am using Firezone with Keycloak OIDC client.
I dont want public Keycloak OIDC.
May be firezone auto disable user if user dont exist keycloak ?

**Comment by jamilbk** [comment]
Hi @patsevanton, unfortunately OIDC provides no mechanism for user discovery or identity sync. For that we'd need SCIM integration, which KeyCloak unfortunately doesn't support.
