### ISSUE TITLE
Streamline UX

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2513]
- [x] Rename Gateway Groups to Sites in the UI
- [x] Move Resources under Sites
  - [x] Site -> Gateways -> Resources
- [x] Remove Gateway tags
- [x] Add ability to deploy new Gateway
  - [x] Gateway / client binary to read `FIREZONE_ID` variable
- [x] Replace Resources new form to take site as URL param
- [x] Change the unique constraint on `resources.address` to be unique per `gateway_group_id` too

```
docker run \
  FIREZONE_ID=<Ecto.UUIDGenerate()> \
  FIREZONE_TOKEN=<token> \
  FIREZONE_HOSTNAME=`hostname`
```

**Comment by AndrewDryga** [comment]
> Change the unique constraint on resources.address to be unique per gateway_group_id too

This is not possible in a many-to-many setup, so addresses won't be unique for now.
