### ISSUE TITLE
Update on the project?

### ISSUE THREAD

**Issue by luckman212** [CloudFire-LLC/cloudfire#2519]
I saw `master` was renamed to `legacy`. I read the [1.0 announcement](https://www.firezone.dev/blog/firezone-1-0), and still have a couple of questions about the project!

- Last blogpost was over 3 months ago, and says the launch was set for mid-Q3 2023. Is there an update to the launch schedule?
- As dev on the legacy branch has essentially stopped, I'm very curious how the 1.0 product will be priced. Will there be a selfhosted/homelab version, or is going to be enterprise only?

Wishing you best of luck, hope there will be some news soon.

**Comment by jamilbk** [comment]
Thanks for the questions @luckman212.

I'll have PR(s) open to answer these in more detail in the coming days and will reference this issue. In meantime, I hope the below answers are helpful:

> Will there be a selfhosted/homelab version

Our [license](https://github.com/firezone/firezone#license) won't prevent you from self-hosting all of the new components in 1.0, but we won't be able to dedicate the resources to make the whole experience a smooth one at launch. The data plane components are much easier to self-host in 1.0 (all you need are a couple ENV vars), but the control plane is much trickier in many ways. For example: publishing client applications in the respective App Stores means users can't easily control which version is installed on their devices, which translates to a very complex version compatibility matrix between cloud and self-hosted control planes APIs and client application versions we can't rollback.

We're still evaluating the feasibility of this, and may be able to support it down the line if we find a sustainable business use case. There will be developer-focused build from source instructions, so you're free to experiment. There will also be a substantial free (as in beer) cloud-managed tier.

**Comment by jamilbk** [comment]
cc @jefferenced for visibility

**Comment by luckman212** [comment]
Okay, sounds like you're pretty close to announcing. I appreciate the info and as I said before, good luck!

**Comment by jamilbk** [comment]
Updates will continue to trickle in over the next few weeks... stay tuned.
