### ISSUE TITLE
Deploy Metabase to production

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2527]

**Comment by jamilbk** [comment]
@AndrewDryga I'm not sure we'll use Metabase self-hosted for BI just yet -- need to evaluate options -- just FYI

**Comment by AndrewDryga** [comment]
@jamilbk I'm pretty sure we will, I've used Power BI, ChartIO, Metabase, and a few others in the past. All BI is split into three categories: expensive ones, unusable ones, Metabase. Metabase has a ton of flaws, but there is no self-hosted alternative, unfortunately.
