### ISSUE TITLE
POST /auth/identity/callback Error due to Plug.CSRFProtection.InvalidCSRFTokenError

### ISSUE THREAD

**Issue by crkmythical** [CloudFire-LLC/cloudfire#2536]
16:17:17.940 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/supervisor.ex function=log_access_url/2 line=425 mfa=Phoenix.Endpoint.Supervisor.log_access_url/2 module=Phoenix.Endpoint.Supervisor pid=<0.331.0> [info] Access FzHttpWeb.Endpoint at http://0.0.0.0
16:18:35.917 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.518.0> request_id=F5M9gq2dVoX0BMIAAAAj [info] GET /
16:18:36.022 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.518.0> request_id=F5M9gq2dVoX0BMIAAAAj [info] Sent 200 in 104ms
16:18:38.372 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.525.0> request_id=F5M9gz_-0YCFB7oAAAHB [info] GET /auth/identity
16:18:38.392 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.525.0> request_id=F5M9gz_-0YCFB7oAAAHB [info] Sent 200 in 19ms
16:18:39.224 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.527.0> request_id=F5M9g3LFe8VictoAAAHh [info] GET /
16:18:39.226 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.527.0> request_id=F5M9g3LFe8VictoAAAHh [info] Sent 200 in 2ms
16:18:54.962 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.530.0> request_id=F5M9hxzVdKvas_sAAAIB [info] POST /auth/identity/callback
16:18:54.978 erl_level=error domain=cowboy pid=<0.528.0> [error] #PID<0.530.0> running FzHttpWeb.Endpoint (connection #PID<0.528.0>, stream id 1) terminated
Server: 54.250.43.205:13000 (http)
Request: POST /auth/identity/callback
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Plug.CSRFProtection.InvalidCSRFTokenError{message: "invalid CSRF (Cross Site Request Forgery) token, please make sure that:\n\n  * The session cookie is being sent and session is loaded\n  * The request include a valid '_csrf_token' param or 'x-csrf-token' header", plug_status: 403} of type Plug.CSRFProtection.InvalidCSRFTokenError (a struct). This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, FzHttp.Types.IPPort, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Postgrex.INET, Time, Tuple, URI
        (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
        (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
        (phoenix 1.7.2) lib/phoenix/controller.ex:1010: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
        (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix 1.7.2) lib/phoenix/controller.ex:976: Phoenix.Controller.render_and_send/4
        (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:84: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
        (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2

**Comment by jamilbk** [comment]
This will happen if you reuse an old form, and will go away if you refresh the page.
