### ISSUE TITLE
1.0 UX / QA Runbook

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2538]
Create a dogfood / QA runbook to go through before beta is released.

**Comment by jefferenced** [comment]
Here are notes from the November 3, 2023 walkthrough — https://docs.google.com/document/d/1x02b7UjyYp5R0MXyXf7UsxQB_7uRQZeBvDo8BmXz9ZA/edit?usp=sharing

**Comment by jamilbk** [comment]
Fixed by #3043
