### ISSUE TITLE
Postgrex.Error FATAL 28P01

### ISSUE THREAD

**Issue by MHunton** [CloudFire-LLC/cloudfire#2541]
I'm getting the following message after running: docker compose run --rm firezone bin/migrate

erl_level=error application=db_connection domain=elixir file=lib/db_connection/connection.ex function=connect/2 line=103 mfa=DBConnection.Connection.connect/2 module=DBConnection.Connection pid=<0.163.0> [error] Postgrex.Protocol (#PID<0.163.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"

If someone could help that would be greatly appreciated. Thanks.

**Comment by jamilbk** [comment]
Hi @MHunton, looks like your Postgres password is wrong. Make sure your compose file is using the correct password, especially if you've changed the default. Closing as not a Firezone issue.
