### ISSUE TITLE
Decide if users should be allowed to change traffic filter rules without creating a new resource

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2569]
We don't allow to change of address to avoid its abuse - users should create a new one any time it needs to be changed so that logs are idempotent and don't allow ID reuses. Probably we should also prohibit changing filtering rules for the same reason.

**Comment by jamilbk** [comment]
refs #2504

**Comment by jamilbk** [comment]
Closing to track discussion in #2504
