### ISSUE TITLE
Support for 2FA / SSO

### ISSUE THREAD

**Issue by pschichtel** [CloudFire-LLC/cloudfire#259]
I was just made a aware of firezone and I like what I see. This is fairly close to something I thought about implementing several times in the past.

The part that is missing but *feels* fairly straight forward to add would be a way to support 2FA. My request here would be to provide infrastructure to enable the second verification step, but not actually implement it.

In the concept I had in mind I would have had 2 firewall setups:

1. a very restrictive setup, which allows access only to systems necessary for the second factory verification (e.g. a captive portal)
2. the normal firewall setup for clients that have been successfully verified

By default a new client would receive the restrictive setup. The client can then performs the second factor verification and when successful, the VPN manager switches the firewall rules for that client to the normal setup.

The second factor verification could for example be managed by Keycloak server, where the user authenticates in the browsers with additional factors. Upon successful authentication a webhook could be called on the VPN manager on the backend side, that would switch the client firewall rules:

1. Client connects to wireguard (vpn)
2. Client goes to https://2fa-vpn.example.com (2fa service)
3. 2fa service redirects client to https://keycloak.example.com (keycloak) as part of oauth2 authorization code flow
4. Client authenticates to keycloak
5. Keycloak redirects back to 2fa service
6. 2fa service verifies oauth2 authorization code and on success triggers firewall switch in vpn

I think this could be integrated nicely into firezone:

Currently firezone provides a single allow/block list pair. if it had a way to manage several of these lists and a way to select a default list, then this could be used to model the different states a client is in (e.g. non-authenticated vs authenticated). Additionally some form of API would be necessary, so that outside systems could change the active list for a certain client. All other parts (the 2fa service, keycloak, captive portal detection, some wireguard client integration maybe, ...) could and should be handled by different systems. A nice to have would be some kind of webhook mechanism in firezone, so that it can notify another system about new client connections (e.g. to trigger some cloud-powered auth mechnism on a phone).

The only thing where I'm still not entirely clear on how to correctly (and securely) implement: Uniquely identifying a client, so other systems could switch firewall rules for a specific client.

**Comment by jamilbk** [comment]
Hi Phillip,

Thanks for such a detailed and well-written feature request! I was planning to add 2FA (via time-based OTP) relatively soonish, so your timing is perfect.

Brainstorming through your request a little more, it seems like this can be broken down into a few rough high-level feature requests:

* **Addition of "users"**, perhaps via an identity provider like Keycloak
  * A user "has_many" devices
* **Multi-factor authentication**, via one of the following:
  * Time-based one-time password
  * External 2FA oracle (e.g. 2fa-vpn.example.com or [Duo Security](https://duo.com/product/remote-access/vpn-protection))
* **Outbound webhooks** for certain events:
  * client_connect:success
* **Firewall "groups"** or "zones"
  * restricted and unrestricted (at a minimum)
* **API** for handling multi-factor authentication requests from external services
  * On success, switches firewall group for the user in question from "restricted" to "unrestricted"


Does this capture the main features needed to facilitate your workflow? If so I can begin breaking them down further and prioritizing them.

**Comment by pschichtel** [comment]
Users through external identity providers via e.g. OpenID Connect would certainly be nice and would probably help securing the firezone UI itself. Implementing simple TOTP for the UI authentication without external provider also makes sense.

For the 2fa approach on the VPN connection I made a quick sketch of how the flow might look like, that I'm imagining:

![image](https://user-images.githubusercontent.com/526104/135355863-a0a7f899-a256-45b5-a014-f5e4a6e17598.png)

* Step `(2)` would require the outbound webhook you mentioned. The event would need to supply enough information to the helper service, that it can recognize the VPN user once the HTTP request from the browser comes in (step `(4)`). I assume this has to be IP-address based (or something derivable from the IP). It should probably also provide some kind of session secret, so that the helper service can be authenticated at step `(10)`.
* Steps `(3)` to `(9)` would not involve firezone
* Step `(10)` would require an API to switch the zones as you suggested. This could be a really generic API and I could imagine implementing more complicated state transitions using it than just "restricted" and "unrestricted". For example I could take user information from step `(9)` (e.g. an OpenID Connect id_token) to select from a set of different zones (e.g. admin, family, friends and guests zones)

I would implement other 2fa providers like Duo Security in a similar fashion. The user will need some kind of client application to drive the authentication after connecting. Many solutions currently available do some kind of custom GUI or customization. My approach utilizes the web browsers because I prefer to use the trust-worthy vanilla VPN clients and not some proprietary UI thingy that doesn't integrate with my desktop. Browsers also have good support for Kerberos, NTLM and all the new WebAuthn stuff in case someone wants to use that for authentication. I could also imagine a simple GTK app with an embedded browser that can be triggered via commandline (e.g. using networkmanager's dispatcher stuff) that does persistent sessions, maybe even involving a TPM or so.

So my point is: How specifically the authentication flow/2fa would look like is probably very use-case specific and any built-in flow will not work for some people or eventually start feature-creeping.

**Comment by sandys** [comment]
hey guys - chiming in from the HN post. This is superb to discuss. IMHO would be a killer feature for wireguard based products in general.

Quick point here - in general, I would request you to first do 2-FA via integration as opposed to building TOTP on your own. Because 2-FA is important for compliance heavy industries. It is far easier to do that if you have second factor via a compliant mechanic (like U2F hardware or a third party like Okta/Google Auth) versus something that we will have to convince auditors that works well.

I second @pschichtel in that way - it would be super great if u implement 2FA through integrations at this point. In case you do want to eventually implement your own, that should go in the direction of hardware tokens (U2F or epass2003) because they are usually audit-safe.

If I had the choice to make - I would say Okta, Firebase Auth (which includes a TOTP based SMS) and Google Auth would cover 90% of the 2-FA requirements there. 

as a parallel, this is what Pritunl does
- https://docs.pritunl.com/docs/okta
- https://docs.pritunl.com/docs/google
- https://docs.pritunl.com/docs/yubikey

**Comment by pschichtel** [comment]
btw I would definitely put my ~~money~~ time where my mouth is and implement such a service (steps `(2)` - `(10)`) backed by a generic OIDC provider

**Comment by jamilbk** [comment]
Thank you @pschichtel and @sandys for facilitating such a productive discussion.

@pschichtel I agree that relying on the web browser for the 2FA auth flow is best, especially for now as a first iteration of this system. It allows us to use the vanilla WireGuard client apps and just have the user open a browser on his/her device that redirects all traffic to our captive portal to begin the authentication flow.

@sandys I've noted your suggestion to prioritize external 2FA providers for this. Makes sense from a compliance standpoint.

I think we'll need to implement the following changes at a minimum:

- Add rudimentary RBAC for local unprivileged users: Firezone currently assumes all user accounts are admins
- Simple API for switching firewall zones on a per-device basis (as @pschichtel suggested) when that user authenticates
- Simple captive portal that allows the user to select which MFA auth provider to use (in the case there are multiple configured providers)
- Simple UI for admins to set up MFA for their Firezone instance

Firezone is still a very young project, so there's lots to implement here. Multi-factor support is our highest priority for the immediate future, so expect to see some more progress here in the coming days. I'll start taking a stab at a prototype tomorrow :-)

**Comment by sandys** [comment]
@jamilbk thanks for considering this. 
I also wanted to mention the simplest user story here - i think ur architecture is fairly more complex/sophisticated, however is tough for people to understand. Especially the zone concepts.

here's the 90 percentile usecase:
- I'm a developer with no devops experience
- I have a AWS cluster in a VPC. I need to connect to this cluster in a safe manner using 2-FA.
- i will create a new EC2 instance inside the VPC with an public facing IP and one single port open (which should be choosable)
- i will install firezone - or run a docker instance with firezone. QUESTION: how to do this ? example Tailscale - https://tailscale.com/kb/1141/aws-rds/
- i will add my Google Auth or Okta API key inside firezone admin settings
- I will create a few users. 
- these users will now try connect to the VPC using their linux/windows/mac laptops. QUESTION: What client should they use ? will it be a standard wireguard client or will it be a special firezone client ?
- these users will get a 2-FA challenge in the form of a URL that they must open in their browser.
- once 2-FA challenge is addressed, the login to Firezone goes through. These users are now in the VPC network of AWS.

**Comment by jamilbk** [comment]
@sandys Thanks -- this flow makes sense. To answer your questions:

> i will install firezone - or run a docker instance with firezone. QUESTION: how to do this ?

We're investigating Docker support in #260 but for the time being, I'd recommend installing one of the [supported releases](https://github/firezone/firezone/releases). If your distro isn't listed there (e.g. Amazon Linux), we can probably add it fairly quickly assuming there's a [Vagrant box](https://app.vagrantup.com/boxes/search) available for it.

> these users will now try connect to the VPC using their linux/windows/mac laptops. QUESTION: What client should they use ? will it be a standard wireguard client or will it be a special firezone client ?

For now your users will install the official WireGuard client, connect, and open a browser to perform the 2FA authentication flow. We have plans for custom client apps, but these won't be a reality soon.

**Comment by sandys** [comment]
Hi
Sorry my language was a little weird. I didn't mean how will they setup for
"docker".

I meant "how will they setup" in the AWS+VPC context. Most cloud services
have an equivalent of the vpc.

**Comment by jamilbk** [comment]
Hi @pschichtel --

Just an update. A rudimentary version of this (with local email/password authentication) is planned for the 0.2.0 release, coming Soon™.

**Comment by jamilbk** [comment]
Another open-source identity provider: https://www.freeipa.org/page/Main_Page

**Comment by jamilbk** [comment]
This is (finally) implemented as part of #485. This will be included the 0.3.0 release, dropping imminently.

Okta and Google are supported for now. Keycloak is *almost* working. I've opened another issue specifically to track Keycloak SSO integration: #497
