### ISSUE TITLE
Don’t copy `/32` in resources list on the client

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2600]
This forces user to always manually remove the CIDR.

**Comment by AndrewDryga** [comment]
Examples of things we want to support in the UI and back-end:
127.0.0.1:8080
localhost:8080
myapp.local:8080
192.168.1.1/24
mycorp.com
100.100.100.100:100

**Comment by jamilbk** [comment]
Closing in favor of #2664
