### ISSUE TITLE
Clients must send device name to portal

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2605]
The Portal accepts `name` attribute and all clients should resolve the internal name (eg `hostname`) and send it to the portal, to prevent flooding the UI with random names.

**Comment by roop** [comment]
@AndrewDryga Should we pass the `name` as a parameter to the authentication URL opened when the user clicks on 'Sign In'. (For example: `https://app.firezone.dev/firezone/?client_platform=apple&name=roops-mac`)

**Comment by AndrewDryga** [comment]
@roop it should be done by the `connlib` when joining a WebSocker API `channel`.

**Comment by jamilbk** [comment]
Could possibly call this from `connlib` to avoid needing an FFI change for this.

**Comment by jamilbk** [comment]
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name

**Comment by ReactorScram** [comment]
The randomly-generated and persisted device ID replaces this, right?

**Comment by AndrewDryga** [comment]
@ReactorScram ID and name are two different stories, `id` is used to uniquely identify a device, `name` is for UX purposes so that the user can identify the device in the UI and it doesn't have to be unique.

**Comment by ReactorScram** [comment]
@AndrewDryga Okay. Is this something connlib does / will do, or should I do it in the client since it's platform-specific?

**Comment by jamilbk** [comment]
@ReactorScram Good question -- on some hosts, `gethostname()` returns a valid name to use. On others (like iOS), this just returns `localhost` and we have to request a special entitlement from Apple to get the user's device name to use (in progress).

On Windows I think this might [already be solved here](https://github.com/firezone/firezone/blob/main/rust/connlib/shared/src/lib.rs#L53)?

**Comment by ReactorScram** [comment]
Might be. I don't call that directly but it looks like it's somewhere between user sign-in and making the websocket connection, so I probably don't need to.

**Comment by jamilbk** [comment]
@ReactorScram Ah, it's not. See #3082
