### ISSUE TITLE
WSL2 support

### ISSUE THREAD

**Issue by radhikasethi2011** [CloudFire-LLC/cloudfire#262]
Hi! Tried installing for WSL2, keep running into this error: 
![image](https://user-images.githubusercontent.com/44310177/135391849-d9dfd6aa-2527-44ef-90a8-f5ce831ff099.png)
Any idea how I can set this up in WSL2? I thought it would be similar to setting up in Ubuntu 20.04 (that's the distro I'm using)

**Comment by PAStheLoD** [comment]
Using WSL2 seems like an uphill battle (compared to a more VM-like VM, for example VirtualBox)

But first you need to get systemd running https://gist.github.com/djfdyuruiry/6720faa3f9fc59bfdf6284ee1f41f950 
And I guess you'll need the WireGuard kernel module https://centerorbit.medium.com/installing-wireguard-in-wsl-2-dd676520cb21

**Comment by jamilbk** [comment]
@radhikasethi2011

As @PAStheLoD alluded, getting Firezone working for WSL2 is going to a very long and painful process. Firezone relies heavily on the WireGuard kernel module and netfilter subsystem and I'm not sure WSL2 exposes these in a way Firezone expects. We may very well have a native Windows package one day, but for now, you're much better off setting up Firezone in a VM using something like Virtualbox.

Going to close this for now. If you still help getting Firezone working inside a VM, feel free to open another issue.
