### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2623]
Add a Quickstart guide that aims to be an introductory guide for users new to Firezone looking to test out a basic walkthrough as quickly as possible. In this guide, Terraform and other automation tools don't apply since the user will be looking to simply get acquainted / familiar with Firezone and see how it works.

**Comment by bmanifold** [comment]
Started a markdown doc currently located at: https://github.com/bmanifold/firezone-docs since I wasn't sure what format the docs would end up in.  This can be changed, moved, whatever is necessary.
