### ISSUE TITLE
Sign in / authentication token button color consistency

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2639]
<img width="640" alt="Screenshot 2023-11-14 at 3 11 57 PM" src="https://github.com/firezone/firezone/assets/167144/efea777e-f3ab-4441-811b-5d860066b770">

**Comment by jamilbk** [comment]
@bmanifold Ah, I finally found the button I had noticed earlier :-)

**Comment by bmanifold** [comment]
Nice!  Ok, I'll make sure to get that updated.

**Comment by jamilbk** [comment]
Refs #2682

**Comment by bmanifold** [comment]
Closed by #2693
