### ISSUE TITLE
Disable actors/groups when they're deleted in the IdP

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2646]
Currently we wait for a user's session to expire before knowing that they aren't allowed to access resources, but one big customer ask for larger orgs was making this more immediate so that terminated employees and removed groups pose less of a security risk to the organization.

**Comment by jamilbk** [comment]
[Relevant Slack thread](https://firezonehq.slack.com/archives/C04HRQTFY0Z/p1700006522691279?thread_ts=1700000942.910599&cid=C04HRQTFY0Z)

tl;dr: Just need to broadcast token revocation to clients when user's IdP status has changed

**Comment by jamilbk** [comment]
Edge case: What happens to the associated Policy when a Group is removed from IdP?

**Comment by AndrewDryga** [comment]
@jamilbk the group will be deleted if it's removed from IdP but it will stay if it's in IdP but has no members, basically if IdP sends is to us we will sync it.

The Policy will be hidden from UI once the group is deleted (we use inner join with where clause) and it will look like it's also deleted. If it's added to IdP again (with the same ID) it will add it back and Policy will reactivate.

**Comment by jamilbk** [comment]
Gotcha, thanks!

**Comment by AndrewDryga** [comment]
Closing as it looks like it already behaves the way we want it.
