### ISSUE TITLE
Can't sign out of client sessions

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2647]
It seems that the client's browser session is loaded automatically from cookies when navigating to the sign_in page, preventing users from being able to successfully sign out of their clients.

@AndrewDryga I'm guessing this'll probably be fixed as a side effect of #2032, but just noting here for posterity.

We could just disable cookie session loading for clients if that's easiest, since the actual IdP cookie should be unaffected by our session.

**Comment by jamilbk** [comment]
The browser window opens very briefly before being successfully redirected automatically:



https://github.com/firezone/firezone/assets/167144/abf70b74-7f30-4f29-8df0-ff94a07ac844

**Comment by AndrewDryga** [comment]
On Sign Out clients must open a web view with `/account_id/sign_out`, otherwise IdP features like post-logout redirects won't work. 

Or we don't store cookies for web view but then people will have to enter IdP password all the time. (And we still won't be OIDC compliant because of post logout redirects.)

Lets get back to this one after #2032 if needed

**Comment by jamilbk** [comment]
> Or we don't store cookies for web view but then people will have to enter IdP password all the time.

I was thinking moreso this, just because it's simpler to do in the near-term. The IdP session itself will still be cookied right? So a user will see the "Log in with" screen, click "Log in with Google Workspace", and then be authed via the stored IdP cookie in their browser window.

> (And we still won't be OIDC compliant because of post logout redirects.)

That's fine I think. Out of the 18 months we've had OIDC auth enabled, I don't think we've ever had one request to configure the post logout redirect uri (or to be OIDC compliant), so we can probably avoid building for that use case for now.

**Comment by AndrewDryga** [comment]
> That's fine I think. Out of the 18 months we've had OIDC auth enabled, I don't think we've ever had one request to configure the post logout redirect uri (or to be OIDC compliant), so we can probably avoid building for that use case for now.

It's already built, just not for clients.

**Comment by AndrewDryga** [comment]
> I was thinking moreso this, just because it's simpler to do in the near-term. The IdP session itself will still be cookied right? So a user will see the "Log in with" screen, click "Log in with Google Workspace", and then be authed via the stored IdP cookie in their browser window.

I don't know about all the platform but as I remember for iOS you either get cookies or complete sandbox/incognito view.

**Comment by jamilbk** [comment]
For Apple, it's the same for both iOS and macOs -- we currently have [session persistence enabled](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio).

On Android they're persistent as well, but we're stuck using Chrome due to the ChromeTabs and AppLink behavior -- they don't work on Firefox :-(

**Comment by AndrewDryga** [comment]
@jamilbk I was trying to say that if you disable session persistence the IdP cookies won't be picked up in the WebView so users will have to enter the password to their IdP all the time. It always throws me off when some app opens a web view to "Log in with Google" and then I need to enter my Gmail password there.

**Comment by jamilbk** [comment]
@AndrewDryga Ah gotcha. Yeah we originally had it disabled, but then enabled it due to this exact usability issue

**Comment by AndrewDryga** [comment]
@jamilbk so what is the solution, let's add a second redirect URL that will be triggered by the client on sign out?
```
sign_out: %{
      "apple" => [method: :external, dest: "firezone://handle_client_sign_out_callback"],
      "android" => [method: :to, dest: "/handle_client_sign_out_callback"]
    }
```

if we do it let's rename other endpoints too for consistency:

```
sign_in: %{
      "apple" => [method: :external, dest: "firezone://handle_client_sign_in_callback"],
      "android" => [method: :to, dest: "/handle_client_sign_in_callback"]
    },
```

**Comment by AndrewDryga** [comment]
Pushed a change required for this to #2696

**Comment by jamilbk** [comment]
I think just resetting the Firezone session cookie for the client when the user loads the sign in page is the best solution for now.

Otherwise, users will see "Firezone wants to use firez.one to sign in" when they click "Sign out", and we have to add the code to open the webview to all the clients.

**Comment by jamilbk** [comment]
Hmm now that I think about it, do we even need to set a browser-based Firezone session for client logins? If they're signed into their IdP it'll still load the IdP session, but for generating the connlib token maybe it makes more sense just to not have a persisted cookie in the browser for client logins, or maybe clear it on the final redirect

**Comment by jamilbk** [comment]
I think this may still be happening:


https://github.com/firezone/firezone/assets/167144/d37e03af-5a03-48e3-8e9a-ca78c1616c45

**Comment by jamilbk** [comment]
False positive. This is a new bug due to #3126
