### ISSUE TITLE
Support full-route tunneling, aka "Internet Resources"

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2667]
```[tasklist]
- [ ] #5844
- [ ] #5797
- [ ] #5840
- [ ] #5819
- [ ] https://github.com/firezone/firezone/pull/5900
- [ ] #5902
- [ ] https://github.com/firezone/firezone/pull/6028
- [ ] https://github.com/firezone/firezone/pull/6051
- [ ] https://github.com/firezone/firezone/pull/6032
- [ ] https://github.com/firezone/firezone/issues/5955
- [ ] #5852
- [ ] https://github.com/firezone/firezone/issues/6047
- [ ] https://github.com/firezone/firezone/issues/6074
- [x] State machine prop tests for internet resource
- [ ] Windows: Set routing metric to 0 for our TUN device
- [ ] https://github.com/firezone/firezone/issues/5841
```

**Comment by jamilbk** [comment]
Aiming to start prototyping this, hidden with a feature flag. I think we need a better UX than simply allowing `0.0.0.0/0` or `::/0` to be entered as a Resource. Perhaps a `Full-route` or `Internet security` feature flag.

For reasons why, see: https://firezonehq.slack.com/archives/C06F51698RK/p1715442524672899

**Comment by jamilbk** [comment]
## Update

Currently testing how well this works today:

- [ ] Apple: mostly works as-is. Network roaming breaks internet.
- [ ] Android: packet loop -- `fd00:2021:1111:8000:100:100:111:0Unknown resource`
- [ ] Linux:
- [ ] Windows:


https://github.com/hickory-dns/hickory-dns/issues/2220

**Comment by jamilbk** [comment]
Also need the ability to allow users to disable Resources, otherwise this can cause unexpected consequences with Policy conditions.

This can work as follows:

- [ ] Add boolean `allow_disabling` to `policies` when an `ip`, `cidr`, or `internet` Resource is being linked, so admins can select whether users are allowed/disallowed the ability to enable/disable IP, CIDR, or internet Resources.
- [ ] Add list of `resource_ids` to clients
- [ ] Add new FFI `disable_resources([resource_id])` and `enabled_resources([resource_id])` to tell connlib the IP/CIDR/Internet resource shouldn't be matching packets
- [ ] Add button in client settings, or documentation for headless client, to "Reset settings", (or use existing button to do this).

**Comment by conectado** [comment]
> Also need the ability to allow users to disable Resources, otherwise this can cause unexpected consequences with Policy conditions.
> 
> This can work as follows:
> 
>     * [ ]  Add boolean `allow_disabling` to `policies` when an `ip`, `cidr`, or `internet` Resource is being linked, so admins can select whether users are allowed/disallowed the ability to enable/disable IP, CIDR, or internet Resources.
> 
>     * [ ]  Add list of `resource_ids` to clients
> 
>     * [ ]  Add new FFI `disable_resources([resource_id])` and `enabled_resources([resource_id])` to tell connlib the IP/CIDR/Internet resource shouldn't be matching packets
> 
>     * [ ]  Add button in client settings, or documentation for headless client, to "Reset settings", (or use existing button to do this).

For enabling/disabling resources FFI API I'd go with a single `disabled_resources([resource_id])` that's idempotent, meaning we only keep the resources disabled in connlib from the last call.

Seems easier to implement and test.

**Comment by jamilbk** [comment]
Maybe we can just make this an `update_resources` call from app -> connlib like so:

`session.update_resources([{"resource_id": "...", "disabled": true}])`

Only resources that are that list should be updated, and resources that aren't shouldn't be affected in connlib.

When we have multi-site, we can expand on that to allow users to "prefer" sites too, or change route priority, etc.

**Comment by conectado** [comment]
Listing full list of requirements for this feature:

- [x] #5797 
- [x] #5840 
- [ ] #5819 
- [ ] #5852
- [ ] `update_resources` FFI to enable/disable resources
- [ ] FFI to add internet resource
- [ ] (MAYBE) FFI to add internet resource route
