### ISSUE TITLE
Disable changing settings when signed in

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2668]
Changing the settings while signed in causes the tunnel to go down (crash?).

Then, if I sign out with the Settings window still open, the Auth Base URL resets to the staging URL, and the API URL resets to the production URL.

It would probably make sense to prevent users from changing these while signed in. Or, we could allow changing them, and then warn the user upon hitting Apply that it will sign them out.

**Comment by roop** [comment]
What I had in mind when I wrote the code about changing auth URL / account id while being signed in was:
  - if the settings changes, we should [look for an entry in the keychain](https://github.com/firezone/firezone/blob/main/swift/apple/FirezoneKit/Sources/FirezoneKit/Features/SettingsView.swift#L88) for the new auth-URL+account-id in the keychain, and act accordingly
  - if a keychain entry was found, consider us signed in for that user, restart tunnel; else, consider us signed out, stop tunnel
  - no alert

So our options are:
- Keep above behaviour, fix any bugs with it (like the issue with signing out with the settings window open)
- Keep above behaviour, show alert on clicking on "Apply" in macOS or "Save" in iOS. Alert could say "Changing settings might cause you to lose the connection with your current resources. [Cancel] [Proceed]".
- Disable changing settings when connected. Do we make the fields uneditable, or do we disable the 'Apply' / 'Save' button? Do we need some explanatory text somewhere saying you can't edit it when signed in?

@jamilbk What do you think?

**Comment by jamilbk** [comment]
@roop While that's a clever solution, I think it's a bit overkill for right now. It also will mean implementing similar behavior for the Windows and Android clients, which I'm not sure how complicated will be.

It's not the end of the world if the user is signed out, as long as it happens expectedly. They can always sign in again. 

Thinking more about this, the control plane doesn't use the accountID, right? Changing that field shouldn't affect the status of the tunnel. So what if we do this:

- Allow the user to change the account ID at any time. Tunnel remains unaffected.
- If the user wants to change Advanced settings, warn them this **will** sign them out (Cancel / Continue)

For 99% of people who aren't changing the Advanced settings, this prevents them from being signed out. For the remaining 1%, I think signing them out is an acceptable outcome (and easy to replicate in the other clients)

**Comment by roop** [comment]
@jamilbk:

- Changing account ID should also affect the signed-in-ness, I think. If someone's is signed in via something.org/account1, then if account1 changes, the signed-in-ness shouldn't hold good anymore. (Or the user will be seeing resources for account1 while the saved account id is account2.)
- Changing auth URL should change signed-in-ness.
- Changing control plane URL / log filter should not sign us out, but I think we should either (a) turn the tunnel off and back on, or (b) tell them it will take effect only when they connect next time.

**Comment by jamilbk** [comment]
@roop Ah yes, you're completely right

> Changing control plane URL / log filter should not sign us out, but I think we should either (a) turn the tunnel off and back on, or (b) tell them it will take effect only when they connect next time.

It should also sign them out for the same reasons you've listed in the first two points. It wouldn't make sense to connect to the production control plane with a token from staging. The token is only valid for the API URL counterpart of the auth URL you've authenticated to, so they're inherently tied together.

Yeah, let's do this:

> Keep above behaviour, show alert on clicking on "Apply" in macOS or "Save" in iOS. Alert could say "Warning: Changing settings will sign you out and disconnect you from resources. [Cancel] [Continue]".

**Comment by jamilbk** [comment]
^ That will be fairly simple to replicate on other clients as well, i.e. "clear token when relevant settings change"

cc @ReactorScram for visibility

**Comment by roop** [comment]
Okay. So, to summarize, this is what we'll do:

When settings are changed (any of: Account ID, Auth Base URL, API URL, Log Filter) while the user is signed in, on clicking on 'Apply' / 'Save', we show an alert saying: "Changing settings will sign you out and disconnect you from resources. [Cancel] [Continue]". If the user chooses "[Continue]", we sign out the user and save the settings. If the user chooses "[Cancel]" we do nothing (we don't sign out; we don't save the settings).

Is that correct?

**Comment by jamilbk** [comment]
@roop Sounds like a plan!
