### ISSUE TITLE
OIDC Keycloak: PKCE code verifier not specified

### ISSUE THREAD

**Issue by alekseydemidov** [CloudFire-LLC/cloudfire#2680]
**Describe the bug**
We configured OIDC Keycloak, and everything works like a charm, but first login to the firezone UI returns error:
```
An OpenIDConnect error occurred. Details: {400, "{\"error\":\"invalid_grant\",\"error_description\":\"PKCE code verifier not specified\"}"}
```
Any other login without issues

**To Reproduce**
Login to WebUI first time if user doesn't exist in keycloak.

**Expected behavior**
No error and successful login

**Screenshots / Logs**
In Firezone LOG:
```
15:53:48.880 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.24318.2> request_id=F5lfw82A8n3NCbEABheh [info] GET /auth/oidc/*********/callback/
15:53:49.109 erl_level=error application=fz_http domain=elixir file=lib/fz_http_web/controllers/auth_controller.ex function=oidc_callback/2 line=91 mfa=FzHttpWeb.AuthController.oidc_callback/2 module=FzHttpWeb.AuthController pid=<0.24318.2> request_id=F5lfw82A8n3NCbEABheh [error] An OpenIDConnect error occurred. Details: {400, "{\"error\":\"invalid_grant\",\"error_description\":\"PKCE code verifier not specified\"}"}
15:53:49.110 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.24318.2> request_id=F5lfw82A8n3NCbEABheh [info] Sent 302 in 229ms
```
In keycloak LOG:
```
2023-11-20 13:34:29,029 WARN  [org.keycloak.protocol.oidc.utils.PkceUtils] (executor-thread-879) PKCE code verifier not specified, authUserId = ca6468c9-53db-4927-9de3-ae1dabddb13a, authUsername = devopstest@example.org
2023-11-20 13:34:29,029 WARN  [org.keycloak.events] (executor-thread-879) type=CODE_TO_TOKEN_ERROR, realmId=a3ceaf6e-9632-4923-a7e6-4193833c5306, clientId=firezone, userId=ca6468c9-53db-4927-9de3-ae1dabddb13a, ipAddress=***.***.***.135, error=code_verifier_missing, grant_type=authorization_code, code_id=fd872907-a199-4388-8a64-a3fa89d466da, client_auth_method=client-secret
```
**Platform (please complete the following information):**
 - Firezone Version 0.7.35
 - OS: Linux
 - Distro: Ubuntu 22.04
 - Kernel version: 6.2.0-1015-aws
 - Deployment method: Docker
 
**Additional context**

Thanks for any advance.

**Comment by jamilbk** [comment]
Hi there, thanks for the report. We have many users who've integrated KeyCloak successfully without hitting this issue.

Could it be a misconfiguration on the KeyCloak end? Perhaps try resetting your browser session/cookies?

This looks like a KeyCloak issue -- the code verifier param is missing from the redirect URI upon successfuly authentication, so Firezone complains.

**Comment by alekseydemidov** [comment]
Hi, Thanks a lot for your answer,
I suppose you're right and perhaps this's keycloak issue. BTW we use Keycloak version 22.
Just forgot mentioning, this's situation actual for the user who's taken from Google via Keycloak IdP.
For now, I don't have any idea, why it happens, but seems like Keycloak can't generate code_verifier immediately after creation of the local user from google IdP.
Anyway, thanks one more time. Maybe someone met the same behaviour...
