### ISSUE TITLE
Gateway Docker Image Doesn't Display Error On Second Install

### ISSUE THREAD

**Issue by jefferenced** [CloudFire-LLC/cloudfire#2686]
Running the Docker command for a gateway more than once (e.g. on a second VM), fails but doesn't print an error that gives me enough information to solve this.

**Comment by AndrewDryga** [comment]
I don't think that we can do anything about it: this is the way docker works. The only fix would be to wrap the docker script into our own and handle edge cases there.

**Comment by jefferenced** [comment]
Is there no way to recognize that the auth key or ID is already in use, and fail the install with a readout to that effect?

**Comment by jefferenced** [comment]
My concern is — how would someone know they can't re-use the Docker install script?

**Comment by jamilbk** [comment]
Hm yeah, `docker run -d` doesn't bubble the underlying command exit code or output through to the terminal.

@jefferenced There's not a great solution to this particular issue -- ideally we'd nudge users to either copy the command once from the UI, or send them to docs for a different command that can be re-used successfully.

What @AndrewDryga is suggesting could work too, but wrapping in a script obfuscates the actual commands that are being run which is a security turn-off for some folks.

I think probably the best thing to do in the short term is to just make the deploy page more clear that the command only runs successfully once. Users with any familiarity with Docker will know to check the container's exit status / logs.

**Comment by jefferenced** [comment]
That makes sense, and maybe something like "one-time use / single use" would be sufficient?
