### ISSUE TITLE
Update IPs range used by resources/clients/gateways to support Wildcard split DNS

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2691]
Refs #2661 

- Limit client/gateway IP allocation to `100.64.0.0/11` (~ 2 million addresses)
- Make IP allocation optional since DNS resources don't require them anymore

**Comment by AndrewDryga** [comment]
@jamilbk @conectado do we also want to limit out IPv6 address range? Currently it's: `ipv6: %Postgrex.INET{address: {64_768, 8_225, 4_369, 0, 0, 0, 0, 0}, netmask: 106}`.

**Comment by AndrewDryga** [comment]
@jamilbk @conectado  does it mean that we don't need internal IP addresses for resources at all?

**Comment by conectado** [comment]
> does it mean that we don't need internal IP addresses for resources at all?

@AndrewDryga now that I think about it, no.

**Comment by jamilbk** [comment]
> does it mean that we don't need internal IP addresses for resources at all?

> now that I think about it, no.

Nice :-)

> do we also want to limit out IPv6 address range?

Yeah maybe we should just limit it to always match the IPv4 range structure as a general rule?

**Comment by AndrewDryga** [comment]
Replaced by #2670
