### ISSUE TITLE
table connectivity_checks is bloated

### ISSUE THREAD

**Issue by ihard** [CloudFire-LLC/cloudfire#2700]
**Describe the bug**
The size of the connectivity_checks table is unlimited; it takes up 99% of the space in the entire database.

**To Reproduce**
Use the service for several months. 

**Expected behavior**
A clear connectivity_checks table or limit size

**Comment by jamilbk** [comment]
Hi @ihard --

What version are you on?

You can disable these with `CONNECTIVITY_CHECKS_ENABLED=false`

**Comment by ihard** [comment]
Version 0.7.32

Yes, of course they can be disabled, but it seems that some kind of limiter is needed for the storage time of this information

**Comment by jamilbk** [comment]
@ihard There was a bug in 0.7.9 - 0.7.12 that caused lots of records to be created in very quick succession. It's safe to truncate the table as you see fit, e.g. `TRUNCATE connectivity_checks;`
