### ISSUE TITLE
Allow deleting synced users/groups

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2708]
If a user/group is deleted from the IdP, we disable it. However, it would be nice to be able to clean up old users/groups in cases where there are duplicate Actors or a user/group was mistakenly synced from the IdP.

We could warn the admin with "warning: if this group still exists in your IdP, it will be recreated in Firezone" etc

**Comment by jamilbk** [comment]
<img width="926" alt="Screenshot_2023-11-24_at_9_52_30_AM" src="https://github.com/firezone/firezone/assets/167144/714dc63d-3a7a-49d7-a566-e675cd757db9">

**Comment by AndrewDryga** [comment]
I think the proper solution for this would be default UI filters. The reason why we keep the actors is audit logging and being able to restore them if IdP syncs them back, and we don't have a good heuristic to know if IdP will do that or not. Alternatively, we can try deleting all actors without identities after each sync, but I feel it would be worse.

**Comment by jamilbk** [comment]
refs #3751
