### ISSUE TITLE
Windows client auth

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2711]
The Windows client will need to handle user authentication to the portal within a secure webview and then save the resulting token to a persistent, secure location for establishing the control plane websocket.

One solution could be to use [UWP's WebAuthenticationBroker](https://learn.microsoft.com/en-us/uwp/api/windows.security.authentication.web.webauthenticationbroker?view=winrt-22000)

The URL to use for authentication should be `AUTH_BASE_URL/ACCOUNT_ID?client_platform=windows` where `AUTH_BASE_URL` and `ACCOUNT_ID` are from settings.

After authentication is successful, the portal will redirect the browser to `AUTH_BASE_URL/handle_client_auth_callback?token=<TOKEN>` which the client will need to intercept in order to store the token and connect the WebSocket.

Note that the token returned from the portal is an **opaque** token. The client _should not_ try to introspect it to determine lifetime or other parameters. Token validity is determined by connlib -- if the Session `connect` call succeeds, the token is valid. Otherwise, the token is invalid and should be discarded, moving the app to the signed out state.

If a token expires while the client is connected, the portal will disconnect the websocket, causing connlib to call `onDisconnect`, at which point the client should discard the token and move to the signed out state.

**Comment by ReactorScram** [comment]
(making a note for when I get to this)
That WebAuthenticationBroker does seem to be exposed in the Windows crate: https://microsoft.github.io/windows-docs-rs/doc/windows/Security/Authentication/Web/struct.WebAuthenticationBroker.html#method.AuthenticateAndContinue 

I'm not sure what my account ID is, so I'll ask about that some time.

**Comment by jamilbk** [comment]
> I'm not sure what my account ID is, so I'll ask about that some time.

We use [`firezone`](https://app.firez.one/firezone) for internal testing

**Comment by ReactorScram** [comment]
That's the URL, right? Looking at Session::connect, I'm not sure where the get the device ID and token. When I open that URL and put in my firezone email, I don't get any email.
![image](https://github.com/firezone/firezone/assets/13400041/c096c259-6ef4-413f-9f00-e8af4289a8d3)

**Comment by jamilbk** [comment]
@ReactorScram Sign in with Google workspace (not magic link)

The token is returned from the portal in a final redirect to `AUTH_BASE_URL/handle_client_auth_callback?token=<token>`

The device ID should be pulled from SMbios and should (hopefully) be unique and consistent across devices. If SMBios won't work, Microsoft might have some other identifier we can use, or simple SHA256 hash the primary network inteface's MAC address and use that.

**Comment by jamilbk** [comment]
See this PR for inspiration for retrieving the SMbios:

https://github.com/firezone/firezone/pull/2477/files#diff-9d5ec593addfe28407db74bd8b8b4b9a918258ddf4da6e92dff0ba67dcfee6c8L76

**Comment by ReactorScram** [comment]
The Windows API returns an error when I try to launch the authentication, even before I check the async result.

I'm seeing people having trouble with the UWP API, saying maybe it doesn't work on desktop, or it needs the app to be UWP. They're getting the same error I am.

- https://github.com/microsoft/WindowsAppSDK/issues/441
- https://github.com/microsoft/WindowsAppSDK/issues/398

Some people mentioned spinning up a temporary localhost web server and making the OAuth flow redirect through that, so the web browser can get the end URI and token back to the app. But I'm not sure if this is compatible with Firezone's particular OAuth setup. I'd have to somehow tell the server "Don't tell me the URI, redirect the user to my localhost callback URI"

And it would show up in the default browser, it sounds like phones and Apple do some system-controlled webview for security.

If that could work, there is a crate for it - https://docs.rs/yup-oauth2/8.3.0/yup_oauth2/#installed-flow-usage

**Comment by ReactorScram** [comment]
I'll check what the Linux client does and see if that can be a "good enough to start with" impl since AIUI auth has to happen before I can test out connlib

**Comment by ReactorScram** [comment]
We discussed on the call today that app-links / deep-links / custom uri scheme protocol / whatever it's called might be usable instead of a local web server.

The auth endpoint doesn't allow me to request a custom redirect / callback URI, so I couldn't use an ephemeral port, and picking a designated port is a little unappealing. So I'll try app links first. I think the only catch is that I need to register the exe with Windows, but it doesn't look complicated.

**Comment by ReactorScram** [comment]
App links work in that commit. `firezone://` is registered whenever the app runs, and we could have the installer register it if we need.

So the local web server is not needed. Unfortunately there isn't a secure webview yet, it just opens in the default browser, on my system it's Firefox.

**Comment by jamilbk** [comment]
The issue we had with custom URI schemes is that a malicious app could register the handler and intercept the callback and token.

Does Windows prevent against that somehow? Apple has the [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) for example. Otherwise we might need to figure out the local webserver method -- we can make whatever portal changes necessary to support it.

E.g. we could tell the portal which port to redirect to using a `redirect_to` param or something

**Comment by ReactorScram** [comment]
Yeah, you're right, Windows' scheme registration just seems to be "Last write wins", it didn't have any trouble flipping back and forth between the debug and release exes. So malware could just call itself 'firezone-windows-client.exe' and periodically try to register until it gets the token. Detecting that we missed the token and revoking it wouldn't be airtight.

I'll switch to the local webserver idea. That way we can hold the port open. It would still be a problem if Firezone crashes during authentication.

I think both problems would be more bullet-proof if the client could attach an in-memory single-use public key to these requests, then the server would encrypt (the responses, including the token) so only the client could read them. But that is a gigantic change.

By the way, is there a good place to document things like "We considered URI schemes and rejected it for this reason"? Like a decision journal? I'll just stick it in code comments for now.

**Comment by jamilbk** [comment]
> I think both problems would be more bullet-proof if the client could attach an in-memory single-use public key to these requests, then the server would encrypt them so only the client could read them. But that is a gigantic change.

It's not too bad actually from the portal's perspective. This might be the winner here. It would also simplify auth across platforms since we could use the same parameters and flow for each platform (every platform has deep links / URI handlers). We're discussing how this'd work in the other clients. In the meantime, maybe just keep the custom URI scheme you have here for now while we wait on the portal changes?

Also we probably want to use a URI with a slightly lower chance for collision like `firezone-fd0020211111://` (our IPv6 unique local prefix)

> By the way, is there a good place to document things like "We considered URI schemes and rejected it for this reason"? Like a decision journal? I'll just stick it in code comments for now.

Good question, we started a [MADR](https://adr.github.io/madr/) document [here](https://github.com/firezone/product/blob/main/architecture/madr.md) but it didn't seem to stick. Welcome to add more records there if useful.

**Comment by ReactorScram** [comment]
Sure. I was already looking into the local webserver so I'll just wrap that up and leave it un-called in the code somewhere.

**Comment by jamilbk** [comment]
Awesome.

Just a note on retrieval via SMbios -- it looks like that may not be as reliable as we thought after chatting with @conectado (and introduces another dependency).

What if we just generate a random UUID on first launch and persist it with the [`store`](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/store) plugin? Key value is how we store settings in the other clients (i.e. no need for SQL). This would serve as the device ID, so we'd hash it and use it for `external_id` when connecting the websocket to the portal.

Then we could even use the [`stronghold`](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/stronghold) plugin for storing the token.

**Comment by ReactorScram** [comment]
@jamilbk Is that SHA256 hash intended for any obscurity or security or just to normalize the length?

I've heard that SHA256 is vulnerable to length extension attacks, so personally I've switched to other hashes - https://en.wikipedia.org/wiki/SHA-2#Comparison_of_SHA_functions

**Comment by jamilbk** [comment]
@ReactorScram Great question -- the sha256 is for normalization and obscurity. We don't want to store a raw device ID in case the client sends something private for example.

Noted on the length extension attack, but for our purposes the security of SHA256 is fine since we don't use it for authentication or authorization, only client metadata.

**Comment by ReactorScram** [comment]
Closing, we didn't get the secure webview and we're waiting for the new auth flow to be complete but in general the Windows client does auth with the portal.
