### ISSUE TITLE
Windows client tray icon and menu

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2712]
![Wireframes](https://share.balsamiq.com/c/j1W5ykKNXrMr9HqtLaEGfT.png)

**Comment by ReactorScram** [comment]
Since the sign-in can take time there will probably be some middle state where the menubar says something like "Cancel sign-in" (If it's cancelable) Then About, Settings, and Quit below that. Although it may not be possible to change settings while signing in.

**Comment by jamilbk** [comment]
@ReactorScram Good catch. I think for the other clients we just open a new browser and initiate a new flow if the user does that.

Perhaps we can do that same here? And maybe just automatically cancel the old flow if it's still alive, i.e.

```
fn sign_in () {
  if existing_sign_in_thread() {
    // close view
    // close server
    // clear csrf_token
  }

  launch_sign_in_flow()
}
```
