### ISSUE TITLE
Windows client settings

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2714]
Add a settings view to allow the user to configure the `account_id`, advanced settings, and manage logs.

**Note**: Changing the Account ID or Advanced settings invalidates the current connlib session, so we should warn the user they will be signed out and disconnected if they're signed in when changing these settings.

### Input Validation
- Account ID: This is a URL component, so only allow URL-safe params. See the [validation here](https://github.com/firezone/firezone/blob/main/elixir/apps/domain/lib/domain/accounts/account/changeset.ex#L27) for what's allowed in the portal
- Auth Base URL: This should be a valid URL
- API URL: This should be any valid URI
- Log Filter: This should be any non-empty string

### Logs
"Export Logs" should create a zip file with a name like "$DATETIME-firezone-logs.zip" where `$DATETIME` is a file-path safe datetime string normalized to UTC.

"Clear Logs" should delete all the logs in the directory.

![](https://share.balsamiq.com/c/a8bLd8yvQmQcMK1FR9RhMi.png)
![](https://share.balsamiq.com/c/94PKzFcUZRYmU7KmDnz7L6.png)
![](https://share.balsamiq.com/c/rb6MgKZi6kXFz1z8jNAkbx.png)

**Comment by jamilbk** [comment]
Note: `Logs` should be middle tab not last

**Comment by jamilbk** [comment]
Use the same logging scheme described here: https://github.com/firezone/firezone/issues/2721

**Comment by ReactorScram** [comment]
And these are the values that get saved in encrypted storage when you hit "Apply" and automatically loaded when the app starts, right?

**Comment by jamilbk** [comment]
These don't need to be encrypted -- they aren't secrets. Only the token needs to be stored and loaded securely

**Comment by ReactorScram** [comment]
Okay so probably JSON file in config_local_dir from [directories](https://crates.io/crates/directories)
If we're worried about handling power loss correctly in future versions, then either [rust-atomicwrites](https://github.com/untitaker/rust-atomicwrites) or SQLite. rust-atomicwrites doesn't mention anything about power loss so personally I'd trust the SQLite team more.

**Comment by ReactorScram** [comment]
Started on the GUI parts with Tauri. I'm a little weak on HTML/JS so it'll take a while if I do it, but in theory I could. 
![image](https://github.com/firezone/firezone/assets/13400041/9deb938f-89df-4b0d-80b4-8e5f0a4ff3e8)

**Comment by jamilbk** [comment]
Nice. If you just get something rough together and working, I can come in and apply our brand style guide to it pretty quickly.

Just let me know when the functionality is working and I'll spend a Saturday morning polishing it

**Comment by ReactorScram** [comment]
![image](https://github.com/firezone/firezone/assets/13400041/715c47cb-8cdb-4331-8128-be17de38e055)

They save JSON files now but they aren't loaded back automatically.

**Comment by ReactorScram** [comment]
@jamilbk Yeah, whenever is fine. If you have a Windows environment then `cargo tauri dev` runs a hot-reload server. If you don't have Windows, the easiest way might be if you copy the HTML out, fix it in a web browser, and then I can merge the changes back.

Should I try to land it in main first? I'm not sure whether it's better in general to ask for reviews on stuff that is likely to change, or hold back and end up with lots of un-reviewed changes.

**Comment by jamilbk** [comment]
Yeah probably good to land it first.

Looks good!

**Comment by jamilbk** [comment]
Use different servers and log_filter depending on debug/release

**Comment by ReactorScram** [comment]
Done in main https://github.com/firezone/firezone/blob/baae3bd693d3ad0dbd2fff955f344a1aef0fd26c/rust/windows-client/src-tauri/src/client/settings.rs#L18-L38
