### ISSUE TITLE
Windows client handle connlib callbacks

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2716]
The Windows userspace application will need to handle the connlib callbacks appropriately.

- `onUpdateResources`:
  - Add/Remove CIDR ranges for `cidr` type Resources to send through the tunnel
  - If the `dns_fallback_strategy` is set to `system_resolver`, ensure that any `dns` type Resources' address field is added to the Split DNS configuration
- `onSetInterfaceConfig`: Create the tunnel interface and configure DNS appropriately
- `onDisconnect`: Log the error (if provided), delete token, then shut down the tunnel interface and move to signed out state
- `onError`: Log the error
- `onTunnelReady`: Move app to "signed in" state

**Comment by ReactorScram** [comment]
Handling on_update_resources in a feature branch now 
![image](https://github.com/firezone/firezone/assets/13400041/d345bda1-8e59-4853-8c6e-dfb9d8aea705)
