### ISSUE TITLE
feat(windows): Client auto-update

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2717]
For 1.0 could just check for new binary available on the GitHub release and link to it in a UI notification

**Comment by ReactorScram** [comment]
I think the only thing needed to be forwards-compatible with this is to set up a well-known path for the system-wide installation of the client, e.g. `C:\Program Files\FireZone\FireZone Client`. That way whatever auto-start we use can always find it, and new versions with auto-update can correctly install themselves over old versions if needed.

**Comment by ReactorScram** [comment]
ChatGPT showed me this: `curl https://api.github.com/repos/firezone/firezone/releases/latest`

Piping it into `jq`, both "name" and "tag_name" give "1.0.0-pre.8". "html_url" gives a link to the release page: `https://github.com/firezone/firezone/releases/tag/1.0.0-pre.8`

The rate limit without a token is 60 requests per hour, so checking every 10 or 15 minutes is probably fine. No need to have all users try to update at once anyway. https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users

That way if some other app is doing the same thing, or there's 10 Firezone instances behind NAT, we won't accidentally get someone's IP blocked from the updater.

So I'll make a PR for that probably this week

**Comment by ReactorScram** [comment]
In standup we agreed to just check on launch, that removes a lot of timer logic that would have been hard to test.
