### ISSUE TITLE
Log android app logs to log directory as well

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2722]
It would be useful if the Android clients also logged to the same log directory as connlib, perhaps under the app/ subfolder.

E.g.

`/data/data/dev.firezone.firezone/caches/logs/app`

- [ ] Logging calls in the app should log to both logcat and the above path
- [ ] Logs written to disk should be in JSON format similar to the existing connlib logs
- [ ] Test to ensure that "Export logs" also zips up this directory.

**Comment by jamilbk** [comment]
Use the same logging scheme described here: #2721

**Comment by jamilbk** [comment]
Refs #2714

**Comment by jamilbk** [comment]
This is largely unnecessary since we have Crashlytics logs.

**Comment by jasonboukheir** [comment]
Doing some investigation, there isn't an easy way to redirect `android.util.Log` to a file, except for periodically exporting android logcat to a file. When looking at that solution, there's some information about permissions in later android verisons that might not make that solution viable (?).

We might need to use a logging solution with more features to make this easier. I've seen suggestions for using [Timber](https://github.com/JakeWharton/timber). This article looks like a good summary:

https://medium.com/@karnsaheb/logging-to-disk-reactively-on-android-68c4d0ec489

**Comment by jasonboukheir** [comment]
Still doing some more reading... Check this out:
https://github.com/square/logcat

They say this:

> The name logcat() is intentionally boring and identical to the Android command line tool. This makes it easy to remember and developers know exactly what this does, i.e. log to the local device. One could setup a custom logger that send logs remotely in release builds, however we do not recommend doing so: in our experience, remote logs should be distinct in code from local logs and clearly identified as such, because the volume and performance impact should be very distinct.

Maybe we don't need Timber? Just a custom log to file and log separately for each use case.

**Comment by jasonboukheir** [comment]
What is your thought on logging only in debug builds vs release builds? Doesn't connlib always log, and having those logs a useful feature for bug reporting from our clients?

It sounds like the Android developers shouting "Never Log in Release Builds!!!1!!1!" are doing so because of performance reasons. However, Firezone runs in the background for the most part. Logging in the `TunnelService` is the only performance critical part (I'm assuming the connlib logs are "performant"?) and we want the logs anyway there.

**Comment by jamilbk** [comment]
Logging in release builds helps to troubleshoot issues only occurring in release builds. That said, it does appear that Android _really_ doesn't want you to write logcat logs in release, hence "isDebuggable = false" build configuration setting.

Firebase, however, works.

Let's just use `Firebase.crashlytics.log(..)` for the time being.
