### ISSUE TITLE
Public IP for Endpoints Behind NAT

### ISSUE THREAD

**Issue by jacobcb** [CloudFire-LLC/cloudfire#273]
The current device configuration page only lists internal IP addresses for the endpoint when they exist.

An option to display a public IP for endpoints behind NAT would be nice .

**Comment by jamilbk** [comment]
Thanks for the feature request. Just so I'm clear, you're referring to the device's remote IP as seen by the firezone instance, correct? As in the peer `endpoint` field shown by `/opt/firezone/embedded/bin/wg` here?

```
root@demo:~# /opt/firezone/embedded/bin/wg
interface: wg-firezone
  public key: 4NStQuawcL+uFy8hcHyXX6czqbG3yCnRkGIOaufgLlQ=
  private key: (hidden)
  listening port: 11820

peer: iU2T6/2gKZUV1X1Z4YGKuRls34iatpufK+bUTAtu0D8=
  endpoint: 98.143.118.229:50370
  allowed ips: 10.3.2.4/32, fd00:3:2::4/128
  latest handshake: 14 hours, 8 minutes, 17 seconds ago
  transfer: 139.48 KiB received, 146.96 KiB sent
```

**Comment by jacobcb** [comment]
Thanks for getting back to me, and sorry for the confusion. In my case, in the web ui, the client configuration shows the following:

```
[Interface]
PrivateKey = (redacted)
Address = 10.3.2.4/32, fd00:3:2::4/128
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = qMJ3nOxnnQb3sne3xE7Osi3DTtI4ZhCbPoShD2DgFSw=
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = 172.20.19.18:11820
```


The peer endpoint here should optionally be replaced with a NATed address

**Comment by jamilbk** [comment]
@jacobcb Ahh I gotcha. Yeah, by default we use the IPv4 address of the default egress interface on the Firezone server.

I can make this editable without too much hassle. Let me get started on that.
