### ISSUE TITLE
Pick a new outbound email provider

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2738]
Need to do some research on a new email provider that meets the following requirements:

- SOC 2 Type II certified
- Friendly Email API with Phoenix/Swoosh
- Doesn't store contents of sent emails
- Good deliverability

I know Sendgrid would work (and we're already sending emails for discourse, metabase and other adhoc outbound), but perhaps there's alternatives we could consider switching to.

Does Google have something we can use?

**Comment by AndrewDryga** [comment]
Looks like they have option not to save it:
<img width="673" alt="Screenshot 2023-11-29 at 12 40 58" src="https://github.com/firezone/firezone/assets/1877644/275d96d8-dfe2-4adc-93a9-0f4cd2516e54">

**Comment by jamilbk** [comment]
If you click `Requirements` though, it says:

> There will be no way to see it, retrieve it or view it via the UI, however it will still be accessible using the API, and the [Postmark iOS app](https://postmarkapp.com/ios).

**Comment by jamilbk** [comment]
Data retention policy for Sendgrid 

https://support.twilio.com/hc/en-us/articles/4410585868443-Data-Retention-and-Deletion-in-Twilio-Products#h_01FMXDYRR2N4RDECNP69Q9HAME

**Comment by AndrewDryga** [comment]
Looks like both their policies are practically the same: 
- Postmark can reduce data retention to 7 days for 5$/mo (actually deleting emails) or to 0 but they will just hide them in UI;
- Sendgrid will store email bodies between 72 hours (delivery window) to 7 days (sampling window; but won't store all of them).

We are not married to Postmark so whatever you feel the best, the only thing with Sendgrid is that I would actually try to get a dedicated IP if we use them.

**Comment by jamilbk** [comment]
@AndrewDryga Makes sense. I'll do a little more research today on other options but currently leaning towards SendGrid just so that we're covered for SOC2

**Comment by jamilbk** [comment]
cc @rbhitchcock
