### ISSUE TITLE
Recursive group sync

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2743]
Currently we only sync members of top-level groups and OUs in Google Workspace. Opening an issue to track / prioritize work on syncing members from nested groups too.

**Comment by AndrewDryga** [comment]
@jamilbk just to clarify we do sync nested groups, we just do not add members of child groups to the parent one. Eg.

IdP view:
```
Group A: Alex, Bob, Group B (Mike)
Group B: Mike
```

Firezone View:
```
Group A: Alex, Bob
Group B: Mike
```

**Comment by jamilbk** [comment]
@AndrewDryga Ah, that's how I thought it worked. Ok then I'll update the docs to match this. I think that's how I had it before.
