### ISSUE TITLE
Windows client permissions

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#2751]
**Is your feature request related to a problem? Please describe.**
Windows requires special permissions to create a network adapter, equivalent to `sudo` on Linux, since un-privileged users can't do that. The Wintun docs don't mention this directly, but the Wintun crate does and it's a feature of the OS not of the Rust wrapper. https://github.com/nulldotblack/wintun#example

**Describe the solution you'd like**
I don't know if this will come up in beta, but for some clients we might have to split it into an install step that requires admin privilege from an admin or an MDM, and then the day-to-day GUI running must run unprivileged.

This will overlap with auto-start - I think Gabi said you guys had already encountered this in research - It might be practical to register a Windows service (equivalent to a systemd service, sort of) that runs as a user with permissions to create network adapters (not per se Admin) and then the GUI would have to do IPC with that service. Since the GUI runs unprivileged, we'd probably want to do as much as possible inside that service so that a malicious GUI can't reconfigure the tunnel, only start and stop it. (Similar to Chromium's IPC security model)

**Describe alternatives you've considered**
For internal testing, just running as Admin, or escalating with UAC, with no auto-start, is enough to test other features.

**Additional context**
We discussed it in standup today. Jamil and Gabi have already done research on it.

**Comment by ReactorScram** [comment]
Confirmed with an unprivileged user that you can't create the network adapter, but you can open the local TCP port.

**Comment by ReactorScram** [comment]
If auto-start (i.e., when you boot up the computer and log in, it starts the tunnel without extra clicks) is needed for 1.0 then this will probably be a big problem. If not it could be low priority.

What happens if there are two users? On my laptop I can be signed in to two accounts at once, and it keeps apps open for the non-active account. Would we have two tunnels then, or just disable the tunnels for all but the active accounts? Or even say multiple users aren't supported for 1.0.

**Comment by ReactorScram** [comment]
We agreed 1.0 will not support multiple accounts on the same computer.
@jamilbk What was the decision for un-privileged users? 1.0 or not 1.0?

**Comment by jamilbk** [comment]
@ReactorScram -- the client won't have to do anything to support multiple accounts. It'll just worry about sign out, and then when a user signs in, the webview will allow them to pick the account (see #2791), in other words, "account agnostic"

We'll need more specific requirements to support running the Windows client as an unprivileged user. It's safe to assume all end-users of the Windows client will have admin (open a UAC dialog?) when the app is installed. Would that be doable, or did you mean that the UAC dialog would be prompted each time the tunnel connects?

**Comment by ReactorScram** [comment]
@jamilbk Right now it's looking like UAC ~~each time the tunnel connects~~. (actually it's probably just "Run as admin" and then it's fine after that.) From the wintun crate docs https://github.com/nulldotblack/wintun#example

> //Must be run as Administrator because we create network adapters

Since the network adapter is system-wide, it requires 'sudo'-like permissions, same as mounting a disk in Linux. (Desktop Linux works around this by having a privileged daemon that can mount USB flash drives on behalf of users)

I'll check if Windows has some equivalent to `setuid` that would let us do Admin stuff automatically as long as the exe is in C:\Program Files where an unprivileged user can't modify the binary. I think the attack surface for that would be arguably similar to setting up a systemd-like background service, but the code would be similar.

I'll start documenting these assumptions / restrictions in the README.md.

**Comment by ReactorScram** [comment]
Notes from standup - Jamil said it's okay if they need UAC when the app starts as long as sign-in / sign-out doesn't need UAC

I'll double-check this and see if we can escalate on startup so they don't have to right-click "Run as admin" every time

**Comment by ReactorScram** [comment]
Checked that with a testing GUI, it only asks for UAC when you start the program with "run as admin", after that it's as if the program is running with sudo powers, you can open and close the network adapter any number of times without another UAC window.

I want to detect if we launch without admin privileges and either escalate from within the process, or re-launch ourselves. It might not work if it interferes with the single-instance feature.

**Comment by ReactorScram** [comment]
#2838 should solve most of it without re-launching or escalating in-process. It's still going through CI and stuff.

**Comment by jamilbk** [comment]
Nice work, will take a look shortly

**Comment by ReactorScram** [comment]
Done in main. Went with the re-launching solution so we don't get a UAC popup on every deep link https://github.com/firezone/firezone/blob/baae3bd693d3ad0dbd2fff955f344a1aef0fd26c/rust/windows-client/src-tauri/src/client.rs#L37-L63
