### ISSUE TITLE
Description field in the Rules table

### ISSUE THREAD

**Issue by alekseydemidov** [CloudFire-LLC/cloudfire#2783]
Hello, Dear team, I'd like to propose add addtional field into Rules like a "Description"

<img width="643" alt="image" src="https://github.com/firezone/firezone/assets/34508402/25b1a02b-4611-4dfc-aed5-466319bab523">

Since sometimes we add a lot of specific IP addresses in to rules would great to put some remark what does this IP mean.

If that not hard work, could you please implement it.

Thanks in advance.

**Comment by jamilbk** [comment]
Hi @alekseydemidov, thanks for the suggestion.

Unfortunately 0.7 is end-of-life (EOL) and we won't be adding further features to it.

You're welcome to fork and make the change yourself if you're familiar with Elixir/Phoenix.
