### ISSUE TITLE
Client UX "Settings" Update

### ISSUE THREAD

**Issue by jefferenced** [CloudFire-LLC/cloudfire#2787]
Change "Account ID" to "Workspace" in local clients & documentation.

![Screenshot 2023-12-01 at 11 04 16 AM](https://github.com/firezone/firezone/assets/148512665/52bdf7cf-11d1-4fd6-a938-46a8ec6a9f34)

**Comment by jamilbk** [comment]
I think we're going to remove this altogether in the clients in favor of relying on the webview to manage, closing
