### ISSUE TITLE
Move account slug selection to the webview

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2791]
After discussing with @AndrewDryga and since the portal has this functionality already, it'd greatly simplify the clients to remove the `Account ID` from settings.

This has the following benefits:

- All clients simplified to have only the Advanced and logs tabs in Settings
- Improved UX: Users wouldn't even need to open settings prior to authenticating to their Firezone account on first launch
- Managing authentication to multiple accounts is now a portal/webview issue much easier since the clients don't have to worry about it

**Comment by ReactorScram** [comment]
So "Sign In" always goes to a URI in the web app, and the account slug doesn't need to be stored on the client's disk at all? (Since even on the 2nd sign-in, the web browser would remember it)

**Comment by jamilbk** [comment]
@ReactorScram Yep! The app would just navigate to `AUTH_BASE_URL`, e.g. `https://app.firezone.dev`

**Comment by jamilbk** [comment]
Updated wireframes

![](https://share.balsamiq.com/c/a8bLd8yvQmQcMK1FR9RhMi.png)
![](https://share.balsamiq.com/c/6sPJLKZFHWqcgCD8QzinsW.png)

**Comment by roop** [comment]
@jamilbk Should the ‘Log’ tab come before the ‘Advanced’ tab?

**Comment by jamilbk** [comment]
@roop Hmm I see where you're coming from, but nah I think this is good for now.

The reason is because we are using this tab internally quite heavily, and will be asking beta users to update their Advanced settings as well to modify log strings and possibly point to the staging instance.
