### ISSUE TITLE
Decouple IdP ID token lifetime from Firezone session lifetime

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2794]
Okta for example hardcodes [ID token lifetimes to 1 hour](https://developer.okta.com/docs/api/openapi/okta-oauth/guides/overview/#token-lifetime), which will make Firezone unusable.

Need the ability for admins to set the session token lifetime for clients and for portal sessions.

**Comment by AndrewDryga** [comment]
Dupe of #2924
