### ISSUE TITLE
Refactor client auth to pass `nonce` to portal to append to token

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2802]
Per discussion on #2711 --

1. Client creates ephemeral, single-use, ttl'd public/private keypair.
  a. Keypair should only be valid for ~15 minutes
1. Client sends pubkey with initial sign in request to `AUTH_BASE_URL?pubkey=<base64-encoded public key>`
1. Portal encrypts token with pubkey, redirects to `firezone-fd0020211111://handle_client_auth_callback?token=<ENCRYPTED_TOKEN>`
1. Client intercepts redirect, decrypts token and stores securely as before
  a. Client zeroes out memory containing private key upon consumption
  b. If time-based error, write to app log: `logger.error("Unable to decrypt token, timeout")`
  c. If decryption error, write to app log: `logger.error("Unable to decrypt token, wrong key?")`

**Ensure the above flow can only be trigger when the app is in the signed out state**

Reasons:

- Android AppLinks require Chrome to be installed and even then, are finicky and buggy (see #2123)
- There's not a great secure WebView story for Windows and spinning up a local webserver is overhead
- Reduces codepath complexity in the portal since we can remove platform-specific redirects

# Todo
- [ ] Portal
- [ ] Android/ChromeOS
- [ ] Apple
- [ ] Windows

**Comment by jamilbk** [comment]
cc @roop -- ~~I think I can probably handle these Apple client changes in case you see a PR come in for it.~~

Edit: @roop to take over

**Comment by ReactorScram** [comment]
What crypto would we use? Is there a preferred lib like libsodium?
Asking so I can look into dependencies and make sure it gets through CI - won't do full integration until the spec is done

**Comment by jamilbk** [comment]
@ReactorScram Let's use the `x25519-dalek` crate since this is already required by `boringtun`, which means we'll want to use base64-encoded Curve25519 keys (same as WireGuard)

**Comment by ReactorScram** [comment]
Okay. I skimmed the docs and it shows how to do a key exchange, which might be possible for this, but it doesn't show how to actually encrypt and decrypt data, that would have to be separate. Wikipedia says Wireguard uses ChaCha20 for the symmetric encrypt/decrypt step.

I'm not great at crypto so I'll just leave this for a bit

**Comment by jamilbk** [comment]
@ReactorScram Ah yes, sorry -- yeah you'll need to use a symmetric step as well.

Here's what our AI overlord thinks is an example

```rust
use ring::aead;
use ring::hkdf;
use x25519_dalek::{EphemeralSecret, PublicKey, SharedSecret, StaticSecret};

fn main() {
    // Generate an ephemeral key pair for the client
    let client_secret_key = EphemeralSecret::new(rand::SystemRandom::new());
    let client_public_key = PublicKey::from(&client_secret_key);

    // Serialize the public key to share with the receiver (in this case, the client itself)
    let serialized_public_key = client_public_key.as_bytes().to_vec();

    // Simulate the receiver receiving the public key
    let receiver_public_key = PublicKey::from(&serialized_public_key[..]);

    // The client performs ECDH with its own public key
    let shared_secret = client_secret_key.diffie_hellman(&receiver_public_key);

    // Derive a key using HKDF from the shared secret
    let salt = [];
    let mut hkdf_output = [0u8; 32]; // Output key length for ChaCha20Poly1305
    hkdf::derive(
        &hkdf::HKDF_SHA256,
        Some(&salt),
        &shared_secret.as_bytes(),
        b"encryption-key",
        &mut hkdf_output,
    );

    // Use the derived key for ChaCha20Poly1305
    let sealing_key = aead::SealingKey::new(&aead::CHACHA20_POLY1305, &hkdf_output)
        .expect("Failed to create sealing key");

    let nonce = aead::Nonce::assume_unique_for_key([0u8; 12]); // Unique nonce for each encryption
    let associated_data = b""; // Additional data authenticated but not encrypted

    // Encrypt the message
    let mut plaintext = Vec::from("Hello, world!".as_bytes());
    let ciphertext = aead::seal_in_place(
        &sealing_key,
        nonce,
        associated_data,
        &mut plaintext,
    )
    .expect("Encryption failed");

    // Display the encrypted message
    println!("Encrypted message: {:?}", ciphertext);

    // Decrypt the message using the same key
    let opening_key = aead::OpeningKey::new(&aead::CHACHA20_POLY1305, &hkdf_output)
        .expect("Failed to create opening key");

    let mut decrypted_message = Vec::from(ciphertext);
    aead::open_in_place(
        &opening_key,
        nonce,
        associated_data,
        0, // The AAD length
        &mut decrypted_message,
    )
    .expect("Decryption failed");

    let decrypted_str = String::from_utf8(decrypted_message).expect("Invalid UTF-8");
    println!("Decrypted message: {}", decrypted_str);
}
```

**Comment by jamilbk** [comment]
And Swift

```swift
import CryptoKit

func encryptAndDecrypt() {
    // Generate an ephemeral key pair for the client
    let clientPrivateKey = Curve25519.KeyAgreement.PrivateKey()
    let clientPublicKey = clientPrivateKey.publicKey

    // Serialize the public key to share with the receiver (in this case, the client itself)
    let serializedPublicKey = clientPublicKey.rawRepresentation

    // Simulate the receiver receiving the public key
    let receiverPublicKey = try! Curve25519.KeyAgreement.PublicKey(rawRepresentation: serializedPublicKey)

    // The client performs ECDH with its own public key
    let sharedSecret = try! clientPrivateKey.sharedSecretFromKeyAgreement(with: receiverPublicKey)

    // Derive a key using HKDF from the shared secret
    let hkdfOutput = sharedSecret.hkdfDerivedSymmetricKey(using: SHA256.self, salt: Data(), info: Data(), outputByteCount: 32)

    // Use the derived key for ChaChaPoly
    let nonce = ChaChaPoly.Nonce()
    let sealedBox = try! ChaChaPoly.seal("Hello, world!".data(using: .utf8)!, using: hkdfOutput, nonce: nonce)

    // Display the encrypted message
    print("Encrypted message: \(sealedBox.ciphertext)")

    // Decrypt the message using the same key
    let decryptedData = try! ChaChaPoly.open(sealedBox, using: hkdfOutput)
    let decryptedString = String(data: decryptedData, encoding: .utf8)!
    print("Decrypted message: \(decryptedString)")
}

// Run the example
encryptAndDecrypt()
```

**Comment by roop** [comment]
@jamilbk: Thanks for the Swift code. So I assume that the `<ENCRYPTED_TOKEN>` in the callback (`token=<ENCRYPTED_TOKEN>`) will be a base64 data that's the ChaChaPoly tag+data (which we can use to init a [ChaChaPoly.SealedBox](https://developer.apple.com/documentation/cryptokit/chachapoly/sealedbox/init(combined:))). Is that correct?

**Comment by jamilbk** [comment]
@roop Yeah I think that's correct. You'd base64-decrypt `ENCRYPTED_TOKEN` which should give you the bytes of the encrypted token, then you'd probably want to init the SealedBox and then use [`open`](https://developer.apple.com/documentation/cryptokit/chachapoly/open(_:using:)) to get the unencrypted token (String) out.

**Comment by jamilbk** [comment]
Superseded by #2823 in order to simplify the crypto primitives we rely on.
