### ISSUE TITLE
windows: Panic in tauri-plugin-deep-link if 2 Windows users try to run the client at the same time

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#2808]
**Describe the bug**
The 2nd instance will panic here https://github.com/FabianLars/tauri-plugin-deep-link/blob/0c28b75ac663b4ba0fb1f0d1ea4220f82a583764/src/windows.rs#L59

I'm guessing this is what happens to the 2nd instance:
- `prepare` tries to connect to the local socket and fails, because it's owned by the instance in another desktop session, so it believes we are the only instance
- `register` tries to listen on its own local socket and fails because the sockets share the same namespace

**To Reproduce**
1. Log in to unprivileged Windows account
2. Start Firezone
3. Switch users to another Windows account, leaving the unprivileged account signed in but locked
4. Start Firezone in debug mode in a terminal

**Expected behavior**
Expected the 2nd instance to either send a message to the first instance on the other account, or the 2nd instance to consider itself the first instance for this user and not panic.

**Screenshots / Logs**
```
thread '<unnamed>' panicked at C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-deep-link-0.1.2\src\windows.rs:59:18:
Can't create listener: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
```

**Platform (please complete the following information):**
 - Firezone Version 3518937ad1fad2
 - OS: Windows 11

**Additional context**
Probably need to report this upstream to Tauri. Since we aren't going to allow multiple Windows users for 1.0 we can probably call this a known issue on our side.

**Comment by jamilbk** [comment]
Good find, and thanks for testing this edge case.

**Comment by ReactorScram** [comment]
In 76635eb33, we get "Error: named pipe server couldn't start listening, we are probably the second instance"
We're not using tauri-plugin-deep-link anymore, so I'll close this.

That message is an error we could handle, and we can do something user-friendly like popping up the currently running instance or showing a "Firezone already running but not responding" like Firefox does.
