### ISSUE TITLE
Persist token on reboot and sign out

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2809]
@roop There's currently a security bug with the way the token is stored in the Tunnel on macOS devices:

1. Alice signs into Firezone
2. Token is stored in the tunnelStore
4. Alice quits Firezone
5. Alice signs out of her macOS account
6. Bob signs into his macOS account
7. Bob launches Firezone
8. Bob is now signed into Alice's Firezone account

**Comment by jamilbk** [comment]
I think one way to fix this would be to "Disconnect and quit" whenever the user is switched or logged out.

@roop Is it possible to keep the token and Settings out of the TunnelStore and in the user's Keychain, and then pass this to the tunnel onStart?

**Comment by jamilbk** [comment]
False alarm -- looks like the client can only be connected when the user is signed in. Upon signout or app quit the token is cleared.

**Comment by ReactorScram** [comment]
@jamilbk If quitting the app clears the token, does rebooting clear it too?

**Comment by jamilbk** [comment]
Ah, wait a second -- the Apple client keeps the token if "Disconnect and quit" is clicked from the menubar. But **not** when logging out and restarting.

@roop Would it be possible to add a `case` condition for these two tunnel stop reasons (restart / logout) and *not* clear the token? Technically these would be user-initiated Disconnects and so we'd want to keep the token.

Also, I can confirm that logging in as another user does *not* reuse the token from other users, so we're good there. It *does* however clear the stored token, which is expected I think because the Tunnel process (NetworkExtension) can only store one token at a time, and is system-wide (i.e. you can't have two Firezone apps running at once)

**Comment by jamilbk** [comment]
@ReactorScram The Windows client should probably be set up to follow the above behavior too. I.e. --

- User clicks "Disconnect and quit" from menu -> Disconnect and persist token
- User clicks "Sign out" from menu -> Disconnect and clear token
- User logs out of Windows or Restarts -> Disconnect and persist token

If the tunnel goes down for whatever reason while the app is running, currently the Apple clients attempt to reconnect it using the existing token **3 times** with a 1 second timer in between, and then if those fail, it **signs out and clears token**.
