### ISSUE TITLE
Support for ARM-based OSes

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#282]
Firezone would be useful on Raspberry Pi OS (and other ARM-based OSes):

https://www.reddit.com/r/elixir/comments/pyrlcq/comment/hew67bk/?utm_source=reddit&utm_medium=web2x&context=3
https://news.ycombinator.com/item?id=28702827

This will require either AWS Grativon instances or the purchase of a few Raspberry Pis to run self-hosted runners on.

Support for the following ARM-based Linux distros:

- Raspberry Pi OS
- Ubuntu 18.04, 20.04
- Red Hat 7, 8
- Amazon Linux 2
- SUSE

**Comment by boomam** [comment]
Seconded.  
I use [PiVPN](https://www.pivpn.io/) in a few places, and whilst its perfectly fine, the extra flexibility that firezone seems to offer would be a game changer for the home/IoT market if it was rolled up into an arm compatible package, or container.

**Comment by jamilbk** [comment]
This has been implemented as part of #424 and is available in the [Firezone 0.2.10 release](https://github.com/firezone/firezone/releases/tag/0.2.10). For RaspberryPI OS users, please use the Debian package that corresponds with your RaspberryPI OS version. Thanks!
