### ISSUE TITLE
Standardize auth flow among clients to handle insecure WebViews

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2823]
**Note**: This supersedes #2802 in order to make use of simpler crypto primitives. Only secure random numbers are required now.

Some clients cannot open secure WebViews or they're buggy. We need a standardized auth flow that can make use of custom URI redirects (aka deep links) in a secure way. This issue concerns itself with that implementation.

When "Sign in" is clicked:

1. Client generates two secure random 32-byte hex-encoded strings (64 hex digits), `state`, `nonce`;
2. Client temporarily stores `state` and `nonce` in memory;
3. Client opens the webview to `AUTH_BASE_URL?as=client&state=${state}&nonce=${nonce}`;
4. Client authenticates inside WebView as normal;
5. Portal stores `token=nonce+fragment`, where fragment is a strong random string;
6. Portal issues a final redirect to `firezone-fd0020211111://handle_client_sign_in_callback?fragment=${fragment}&state=${state}`.

At this point, the client intercepts this callback and then:

1. Secure compares `state` against its stored `state`, if they match, clear `state` and continue. If they don't, clear `state` and `nonce`, log the error and move to signed out state;
2. Store the `token="NONCE" + "FRAGMENT"`, where the token is the NONCE concatenated directly to the received `FRAGMENT`;
3. Clear the `nonce`;
4. Store this `token` in secure storage (like the old `token` was).

**Comment by ReactorScram** [comment]
So the token is generated half by the client and half by the server, and if malware intercepts the deep link, it only gets the server half, which isn't enough to authenticate.

And `state` does the same as the CSRF token, ~for~ to protect against replay attacks and "click here to instantly break Firezone" on any HTML page.

Yeah that's a lot simpler than pubkey encryption. Good thing I didn't start on the crypto stuff today lol

**Comment by ReactorScram** [comment]
When there's a failed auth flow, does the server invalidate the old token after some time? If it doesn't know the device ID, it can't delete it when connlib connects, right?

**Comment by AndrewDryga** [comment]
@ReactorScram all our tokens have a lifetime so we will invalidate and delete them eventually.

We can also have a procedure to quick-delete client tokens that were never used for 1+ hours, because we assume that token should be used right away after flow is completed, if their amount becomes a problem.

**Comment by jamilbk** [comment]
I think the windows client work in still in progress.

**Comment by ReactorScram** [comment]
Yep, almost got a PR for it. (Now #3147)

The tab with Google's sign-in gets stuck on signing in, even though I got the token and connlib is working fine. Anyone else getting that?

![image](https://github.com/firezone/firezone/assets/13400041/d0625f64-31ba-44eb-94d7-d5cf6c517f55)

Edit: To clarify, this isn't a regression, it did this for me before the update too.

**Comment by jamilbk** [comment]
@ReactorScram Yeah, I'm seeing the same thing on the Apple client(s).

**Comment by ReactorScram** [comment]
Maybe it's confused because it's redirecting to a scheme that doesn't actually open as a web page. I'll leave it be, looks like it's on the web side.
