### ISSUE TITLE
Support `ip` resource types

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2829]
We need it so that in UI users won't copy-paste the default netmask and have to remove it later in the browser

**Comment by conectado** [comment]
I think it might be better to support this from the UI-side, if the suffix is `/32` or `/128` (depending on ip-type) we should treat them as plain IP.

I mean, we could still do it in connlib , while in the client-side it'd just be just a change on how it's display/copied.

We also could just check for plain ip(/32 or /128) when calling `on_update_resources` which would achieve the same result less invasive in the connlib code-base.

I think the point is that we don't need a separate `Ip` type.

**Comment by jamilbk** [comment]
> I think the point is that we don't need a separate Ip type.

Assuming users don't need to differentiate between the two, this works.

**Comment by jamilbk** [comment]
Add a `client_address` field to `Resources` schema which is sent and passed up to the clients for copy-paste.

**Comment by jamilbk** [comment]
Fixed via the Address Description field
