### ISSUE TITLE
`last_updated_at` and online/offline status are out of sync

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2830]
These three screenshots were taken at the same time

<img width="300" alt="screen" src="https://github.com/firezone/firezone/assets/167144/21e48fc4-c59c-47d0-945c-bc27c72e6b82" />
<img width="1128" alt="Screenshot 2023-12-08 at 7 48 41 AM" src="https://github.com/firezone/firezone/assets/167144/f63b153c-7e90-499c-9e19-fca952210873">
<img width="267" alt="Screenshot 2023-12-08 at 7 48 37 AM" src="https://github.com/firezone/firezone/assets/167144/845445d2-2bde-4b0a-a50e-04f1b54a9b94">

**Comment by jamilbk** [comment]
It was working for a few minutes, but then it looks like the iPhone went offline in the portal, even though it showed connected in the app

**Comment by jamilbk** [comment]
This state persisted for about 30 minutes before the iOS app moved to the signed out state

**Comment by jamilbk** [comment]
Happening for gateways too:

<img width="684" alt="Screenshot 2023-12-15 at 5 34 37 AM" src="https://github.com/firezone/firezone/assets/167144/1245b462-e289-4cfc-8699-9da6c40e740d">

**Comment by AndrewDryga** [comment]
Closed
