### ISSUE TITLE
"Internal connlib error: Pending connection"

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2848]
I was pinging `1.1.1.1` via staging on my flight, when it suddenly started timing out (maybe the internet was too slow or flapped?)

After this point, traffic to `1.1.1.1` continued to timeout indefinitely with `Pending connection` errors.

<img width="726" alt="Screenshot 2023-12-09 at 8 45 48 PM" src="https://github.com/firezone/firezone/assets/167144/de53be4e-4c8e-4276-9fe4-9b05a2d7a757">

<img width="1552" alt="Screenshot 2023-12-09 at 8 43 21 PM" src="https://github.com/firezone/firezone/assets/167144/f9713b4f-2d4a-4550-a043-1c0836cfa1d9">

**Comment by conectado** [comment]
Just a clarifying question, after it reconnected how much time did you wait for this to stop?

**Comment by jamilbk** [comment]
But wait! There's more. It gets weirder. Somehow `google.com` started returning `1.1.1.1` as its IP (both for Unix CLI tools and `dscacheutil`). Also, `dscacheutil -flushcache`, quitting Firezone, and signing out didn't fix the issue (disconnecting from Wifi seemed to reset the DNS cache finally and fix the issue)

<img width="477" alt="Screenshot 2023-12-09 at 8 58 04 PM" src="https://github.com/firezone/firezone/assets/167144/b5923418-acfe-4e68-a709-ddcc005af7d3">
<img width="211" alt="Screenshot 2023-12-09 at 8 56 12 PM" src="https://github.com/firezone/firezone/assets/167144/1bece2ea-ced6-450d-8f63-b70b5a2147c9">
<img width="508" alt="Screenshot 2023-12-09 at 8 55 49 PM" src="https://github.com/firezone/firezone/assets/167144/c6d6f77d-b461-4608-9c4f-fae6bf2bd8bf">

**Comment by jamilbk** [comment]
@conectado I waited over 10 minutes

**Comment by conectado** [comment]
> But wait! There's more. It gets weirder. Somehow `google.com` started returning `1.1.1.1` as its IP (both for Unix CLI tools and `dscacheutil`). Also, `dscacheutil -flushcache`, quitting Firezone, and signing out didn't fix the issue (disconnecting from Wifi seemed to reset the DNS cache finally and fix the issue)
> 
> <img width="477" alt="Screenshot 2023-12-09 at 8 58 04 PM" src="https://github.com/firezone/firezone/assets/167144/b5923418-acfe-4e68-a709-ddcc005af7d3">
> <img width="211" alt="Screenshot 2023-12-09 at 8 56 12 PM" src="https://github.com/firezone/firezone/assets/167144/1bece2ea-ced6-450d-8f63-b70b5a2147c9">
> <img width="508" alt="Screenshot 2023-12-09 at 8 55 49 PM" src="https://github.com/firezone/firezone/assets/167144/c6d6f77d-b461-4608-9c4f-fae6bf2bd8bf">
> 

This is super weird! Will look into it

**Comment by conectado** [comment]
Ah, I think I know what it is, a race condition when waiting for responses on dns from gateway, I will fix it on monday
