### ISSUE TITLE
"packet not allowed" when pinging an IPv6 Resource

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2852]
Happening on staging the "Demo" site.

<img width="926" alt="Screenshot 2023-12-10 at 8 37 26 AM" src="https://github.com/firezone/firezone/assets/167144/bcaa0525-858b-4ef2-b3c4-f159da539378">
<img width="1552" alt="Screenshot 2023-12-10 at 8 37 11 AM" src="https://github.com/firezone/firezone/assets/167144/c12e2770-be58-4cb2-ad72-8febd00884c3">

**Comment by conectado** [comment]
> Happening on staging the "Demo" site.
> 
> <img alt="Screenshot 2023-12-10 at 8 37 26 AM" width="926" src="https://private-user-images.githubusercontent.com/167144/289372984-bcaa0525-858b-4ef2-b3c4-f159da539378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzc1MjksIm5iZiI6MTcwMjMzNzIyOSwicGF0aCI6Ii8xNjcxNDQvMjg5MzcyOTg0LWJjYWEwNTI1LTg1OGItNGVmMi1iM2M0LWYxNTlkYTUzOTM3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQyMzI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzhjZGMyNWJlZDM3N2RmMmY4ZjExNGIyMjM0ZTAyOWUxY2Y5MjhiYTBlNDU2ODc5MWFmNWMxMzgzZmI3OGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1EYW3-sjaVWcKmyCmahRO-1fDkaFyHgnrAFm2iEBGFU"> <img alt="Screenshot 2023-12-10 at 8 37 11 AM" width="1552" src="https://private-user-images.githubusercontent.com/167144/289372987-c12e2770-be58-4cb2-ad72-8febd00884c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzc1MjksIm5iZiI6MTcwMjMzNzIyOSwicGF0aCI6Ii8xNjcxNDQvMjg5MzcyOTg3LWMxMmUyNzcwLWJlNTgtNGNiMi1hZDcyLThmZWJkMDA4ODRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQyMzI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWU3ZWQ5NDQzOGM4YTM2NmZkOTMzZTkwYTcxMWFjZWY2NTJhNzdmYmVjMTRkYjFkNzJjMjMzYWM2ZGVhMDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TyllU2toUEHCBQ6IvO5lXr4N23iq_tLQj3T8j2rOWwE">

@jamilbk were you able to still use firezone?

I think this can happen because of some spurious packets on ipv6 interfaces, since `fd00:2021:1111::f:2225` is not a resource, it kind be some kind of service on macos auto-calculating and using that ip for something else or...
The other 2 things that ip could be is the wireguard ip for:

* the client
* the gateway

We should still never see a packet for neither destination on the tunnel (the packet gets wrapped with that ip later on!) so I will try to see what's going on. :

**Comment by jamilbk** [comment]
@conectado I can't recall if Firezone was still working. Maybe this IP was my WireGuard interface IP?

**Comment by conectado** [comment]
> @conectado I can't recall if Firezone was still working. Maybe this IP was my WireGuard interface IP?

Could be the case, but it's weird that we decapsulate a packet with your own ip as a source

**Comment by jamilbk** [comment]
Yeah strange indeed. FWIW that IP I was trying to ping is a Resource (NextDNS IPv6)

**Comment by jamilbk** [comment]
Update: I think this happens when a Resource isn't being served by a Gateway (or the Gateway has no IPv6 connectivity)
