### ISSUE TITLE
Add `100.64.0.0/10` and `fd00:2021:1111::/48` as Routes at Session start instead of calling `onAddRoute` and `onRemoveRoute` for each IP

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2853]
We're currently spamming the `NetworkSettings.apply` call on Apple because we add individual routes for each dummy IP generated. This causes errors in browsers like Chrome and other apps that may listen for network settings changes.

Instead, we should start each connlib session in `catch_all` mode, which simply calls `on_add_route("100.64.0.0/10")` and `on_add_route("fd00:2021:1111::/48")` once at the beginning of the session and be done with it.

Later on, when we hit edge cases arising from IP conflicts (currently this is an imaginary problem for us), we can expose an option for using granular `/32`s and `/128`s again. This could even be set remotely by the Admin in `Settings -> Addressing`.

<img width="1575" alt="Screenshot 2023-12-10 at 9 09 57 AM" src="https://github.com/firezone/firezone/assets/167144/40273af7-ed21-4ed5-9904-09eaf963bef4">
<img width="773" alt="Screenshot 2023-12-10 at 9 09 45 AM" src="https://github.com/firezone/firezone/assets/167144/d80e4237-4f5c-4d7d-a4c3-190874d36e5b">

**Comment by conectado** [comment]
@jamilbk I'm starting with this(should be quite easy to implement and it'll simplify a lot of things!).

I've seen this reproduced this but are we sure that the `ERR_NETWORK_CHAGNED` is due to changes in the routing config?
