### ISSUE TITLE
remove `on_error` call

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#2867]
This has been brought up by @thomaseizinger before but we don't have any case were we do anything but log the error with the `on_error` callback. If it's a fatal error we use `on_disconnect` and we are already logging errors from connlib.

Until we have any non-fatal error that we want to show the users we probably should remove this callback that only adds boiler plate.

I'm also fine having the API still there but getting rid of the callbacks.

WDYT @jamilbk @roop ?

**Comment by thomaseizinger** [comment]
Big thumbs-up from my end! I'd like to advocate for keep things as lean as possible.

Even for fatal errors, it appears to me that we wouldn't need to call them from within `firezone-tunnel`. The entire session is essentially one function that doesn't exit until the session is closed (either gracefully or due to an error). Thus, we shouldn't need to call back to the app with `on_disconnected` from anywhere but the `firezone-connlib-{apple,android,...}` crates. Let me know if I am missing something!

**Comment by jamilbk** [comment]
Yeah these aren't user-actionable, so we already do with them the most that we can: log to connlib logdir to view later.

Vote yes

**Comment by conectado** [comment]
> Big thumbs-up from my end! I'd like to advocate for keep things as lean as possible.
> 
> Even for fatal errors, it appears to me that we wouldn't need to call them from within `firezone-tunnel`. The entire session is essentially one function that doesn't exit until the session is closed (either gracefully or due to an error). Thus, we shouldn't need to call back to the app with `on_disconnected` from anywhere but the `firezone-connlib-{apple,android,...}` crates. Let me know if I am missing something!

right now that's how it works, `on_disconnect` is only called from `firezone-connlib-{apple,android..}`, actually it's in a helper function  in connlib-clients-shared.
This helper function is only called by `firezone-connlib-<client>` or by a panic

**Comment by thomaseizinger** [comment]
> > Big thumbs-up from my end! I'd like to advocate for keep things as lean as possible.
> > Even for fatal errors, it appears to me that we wouldn't need to call them from within `firezone-tunnel`. The entire session is essentially one function that doesn't exit until the session is closed (either gracefully or due to an error). Thus, we shouldn't need to call back to the app with `on_disconnected` from anywhere but the `firezone-connlib-{apple,android,...}` crates. Let me know if I am missing something!
> 
> right now that's how it works, `on_disconnect` is only called from `firezone-connlib-{apple,android..}`, actually it's in a helper function in connlib-clients-shared. This helper function is only called by `firezone-connlib-<client>` or by a panic

Nice! It would be great if we could express this in the type system by e.g. splitting the callbacks to only pass those into `firezone-tunnel` that are actually called from within there. (My dream would be that we refactor the code such that we don't need them at all and all the client-specific code is surfaced to the `firezone-connlib-<client>` crates in a way that doesn't result in duplication between them).

While we are at it: We never call `on_remove_route` so you can delete that too :)

**Comment by conectado** [comment]
> > > Big thumbs-up from my end! I'd like to advocate for keep things as lean as possible.
> > > Even for fatal errors, it appears to me that we wouldn't need to call them from within `firezone-tunnel`. The entire session is essentially one function that doesn't exit until the session is closed (either gracefully or due to an error). Thus, we shouldn't need to call back to the app with `on_disconnected` from anywhere but the `firezone-connlib-{apple,android,...}` crates. Let me know if I am missing something!
> > 
> > 
> > right now that's how it works, `on_disconnect` is only called from `firezone-connlib-{apple,android..}`, actually it's in a helper function in connlib-clients-shared. This helper function is only called by `firezone-connlib-<client>` or by a panic
> 
> Nice! It would be great if we could express this in the type system by e.g. splitting the callbacks to only pass those into `firezone-tunnel` that are actually called from within there. (My dream would be that we refactor the code such that we don't need them at all and all the client-specific code is surfaced to the `firezone-connlib-<client>` crates in a way that doesn't result in duplication between them).

👍 

> While we are at it: We never call `on_remove_route` so you can delete that too :)

We will very soon! see #2022

**Comment by jamilbk** [comment]
> We will very soon! see #2022

Isn't this unnecessary too with the changes from #2853?

The OS handles route removal when the tunnel goes down.
