### ISSUE TITLE
Have an alternative ipv6-only DNS_SENTINEL

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#2868]
For the DNS_SENTINEL we're using `100.100.11.1`. This requires an ipv4 stack.

Since we're trying to support ipv6-only configs, we should have an alternative ipv6-only sentinel.

**Comment by jamilbk** [comment]
We could just set both ipv4 and ipv6 DNS servers and let the OS choose which one to use.

**Comment by jamilbk** [comment]
`fd00:2021:1111:8000:100:100:111:1`

**Comment by conectado** [comment]
Fixed in #3317
