### ISSUE TITLE
windows: should probably show up in the VPN dialog

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#2875]
![image](https://github.com/firezone/firezone/assets/13400041/ce9d86fd-82c6-4d08-b0b8-57e7b651f07e)

**Describe the bug**
The Windows client isn't considered to be a VPN by Windows
I guess this is something you have to register, I'll look into it some time.

**Comment by jamilbk** [comment]
I think this just needs a config file to be written. See 

- https://learn.microsoft.com/en-us/windows/win32/rras/ras-phone-books
- https://learn.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2022-ps

**Comment by ReactorScram** [comment]
With the DNS fixes from a month ago (NRPT rules) it doesn't seem like we need this badly
