### ISSUE TITLE
Handle expired token properly

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#2879]
Right now when a token is expired while a client is connected, a message is sent.

We need to either:
disconnect the socket from the portal and get a 401 when we retry connection
handle the message properly and call disconnect from connlib

**Comment by jamilbk** [comment]
@AndrewDryga I think this is being implemented in #2240 ?

**Comment by jamilbk** [comment]
I believe the client is disconnected now when its token expires. Feel free to reopen if that's not the case.
