### ISSUE TITLE
macOS: Login web view window should be selected / visible automatically when it appears

### ISSUE THREAD

**Issue by roop** [CloudFire-LLC/cloudfire#2881]
Reported by @conectado on Slack:

idk if there's something we can do about it but there's a usability issue in macos I've encountered quite a bit:
If I'm using safari to browse and I try to log in to Firezone, the login webview doesn't pop up, instead, just what I'm browsing pops up and then I need to juggle the windows to access the login webview

**Comment by jamilbk** [comment]
Weirdly, I've now started experience this bug. The auth window refused to show. My Chrome instance would gain focus, but the new window failed to appear. When I quit Chrome with Cmd+Q, it suddenly showed all of the pending window.

**Comment by jamilbk** [comment]
See this comment for a video: https://github.com/firezone/firezone/issues/2647#issuecomment-1883995540
