### ISSUE TITLE
Don't automatically delete connlib logs after upload to GCP

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2886]
This leads to fragmentation where some logs are in GCP and others saved to a user's phone. When debugging, it's helpful to have them all in one place.

**Comment by AndrewDryga** [comment]
@jamilbk when they should be deleted then? We have to make sure we don't take too much memory on the device too..

**Comment by jamilbk** [comment]
@AndrewDryga See #2895

**Comment by AndrewDryga** [comment]
@jamilbk Im not sure that uncapped logs is a good idea, device that runs out or memory can get unresponsive, especially if its a headless client

**Comment by jamilbk** [comment]
@AndrewDryga Long-term we'll need a different solution but for now this is in the "not an issue" category since `release` clients will have very quiet log_filter.

That work will be tracked in https://github.com/firezone/firezone/issues/2343
