### ISSUE TITLE
Relay is taken down if the portal disconnects

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#2915]
Easy steps to reproduce locally:
1. `docker compose up -d`
1. `docker kill $(docker compose ps -q api)`
1. obvserve `docker compose logs relay`

The problem is this kills any data plane going through that relay, so we need to decouple the control-plane from the data-plane.

**Comment by thomaseizinger** [comment]
This is by design! I remember talking to @AndrewDryga and he said the relay should exit immediately when the connection to the portal has issues.

**Comment by AndrewDryga** [comment]
This is intentional because we might want to reboot the relay host and that was the easiest way to do it with docker - we want it to restart to resolve any potential internal issues with the relay if it can't connect to the portal, ideally after for some timeout.

Long-term we probably want to fail health checks and have the sysadmin control the restart policy and timeouts.

**Comment by conectado** [comment]
> This is intentional because we might want to reboot the relay host and that was the easiest way to do it with docker - we want it to restart to resolve any potential internal issues with the relay if it can't connect to the portal, ideally after for some timeout.

we should still implement a similar backoff strategy similar to what the client have, after ~5minutes it stops trying but before that we keep it alive with an exponential backoff trying to connect to the portal, this way we can keep the data-plane for clients going.

**Comment by jamilbk** [comment]
Just to make sure I'm following:

- If the portal disconnects, the relay restarts
- Any clients connected to that relay (actively flowing packets through it) will then pick a new, healthy one after ~10-15 seconds

So anytime we re-deploy the portal, we will disrupt all clients with an active Relay flow for ~15 seconds?

I think that's a reasonable limitation for now, just need to make sure we know about it.

**Comment by conectado** [comment]
> Just to make sure I'm following:
> 
>     * If the portal disconnects, the relay restarts
> 
>     * Any clients connected to that relay (actively flowing packets through it) will then pick a new, healthy one after ~10-15 seconds
> 
> 
> So anytime we re-deploy the portal, we will disrupt all clients with an active Relay flow for ~15 seconds?
> 
> I think that's a reasonable limitation for now, just need to make sure we know about it.

Precisely right

**Comment by AndrewDryga** [comment]
@jamilbk we don't need to restart it right away, we do it now because it was quick and dirty. But I'm with Gabi here - we should have some timeout before crashing the relay process because if the portal does down it doesn't mean that we have to kill all connections that are already established through relays.

> Any clients connected to that relay (actively flowing packets through it) will then pick a new, healthy one after ~10-15 seconds

If after 15 seconds portal is already available. For availability purposes I would retry the connection from the relay to the portal every `rand(1-20)` seconds for at least 5 minutes.

**Comment by jamilbk** [comment]
So the work here in this issue is then just to add a reconnect timer to the Relay and update our CD strategy to be smarter about deploying new Relays? Or the second part isn't needed?

**Comment by conectado** [comment]
> @jamilbk we don't need to restart it right away, we do it now because it was quick and dirty. But I'm with Gabi here - we should have some timeout before crashing the relay process because if the portal does down it doesn't mean that we have to kill all connections that are already established through relays.
> 
> > Any clients connected to that relay (actively flowing packets through it) will then pick a new, healthy one after ~10-15 seconds
> 
> If after 15 seconds portal is already available. For availability purposes I would retry the connection from the relay to the portal every `rand(1-20)` seconds for at least 5 minutes.

Retrying the connection depends on the webrtc channel state updating and then packet flow

**Comment by AndrewDryga** [comment]
@jamilbk the task is just to introduce the reconnect timer and don't fail health checks/stop the binary while we are on a grace period.

> for at least 5 minutes.

"X minutes" should be picked to be the same on gateway, relay, and client - this is how long of a portal downtime we tolerate without taking down the connectivity. It should be dictated by the security, the question sounds like "how long you can access a resource after its policy was revoked?"

> Retrying the connection depends on the webrtc channel state updating and then packet flow

@conectado but if the tunnel is already open you can send packets through the tunnel as long as client, relay and gateway keep the state, right?

By saying connection I meant WS connection to the portal.

**Comment by conectado** [comment]
@AndrewDryga 
> @conectado but if the tunnel is already open you can send packets through the tunnel as long as client, relay and gateway keep the state, right?

yep

> By saying connection I meant WS connection to the portal.

Ah I see what you mean, from relay to portal. Yeah, I'd propse we do the same as we do with clients:
> Exponential backoff for a maximum of 5 minutes, after that we take the relay down

**Comment by thomaseizinger** [comment]
Just for the record: When restarting the connection to the portal, it is important to keep the `Server` state around as that one contains the relay's secret which is used by the portal to generate TURN credentials.

Another thing to consider is that TURN channels need to be refreshed at least every 10 minutes. To perform this refresh, the clients need to use their credentials. A viable strategy could be to disallow any form of resource refresh (channels as well as allocations) if we are not connected to the portal at the moment. We could reply to the clients with a 401 which should trigger them to get a new set of credentials from the portal. This way, we don't have to write any special code but can hook into the regular flow of needing to renew credentials.

This also avoids an additional timer on the relay side and instead, we just need a piece of state that records whether we are connected to the portal.

**Comment by thomaseizinger** [comment]
I don't think we currently have any functionality for a credentials refresh, right? If we implement this as a "give me a (new) set of relays to use for connection to gatway X", then this could also easily be used by the portal to fail-over to a new set of relays. Thus, if the connection between portal and relay somehow dies but both are functioning individually, we can use this to have the client fail-over to a different relay. That would also require an ICE restart though.

**Comment by jamilbk** [comment]
This came up today. The effect is that deploying prod causes (all?) signed in clients to hang.

**Comment by AndrewDryga** [comment]
@thomaseizinger the `username` and `password` that the portal gives back to the client live as long as the client token lives, so the same credentials can be reused to refresh channels as long as needed. With this even if the portal goes down client-relay-gateway connections that are already established can keep working as long as we want.

**Comment by thomaseizinger** [comment]
> @thomaseizinger the `username` and `password` that the portal gives back to the client live as long as the client token lives, so the same credentials can be reused to refresh channels as long as needed. With this even if the portal goes down client-relay-gateway connections that are already established can keep working as long as we want.

I am assuming you are responding to https://github.com/firezone/firezone/issues/2915#issuecomment-1867025806? What I theorized there is a graceful drain by having the relay tell the clients that their credentials are invalid (401).

But, when thinking more about, I realized this would be much easier to do by having the portal actively tell the clients to stop using a certain relay instead of waiting for the clients to come to that conclusion.

**Comment by AndrewDryga** [comment]
@thomaseizinger portal doesn't know which relays client is using, broadcasting updates for all relays to all clients would be a bad idea for us if we want to have lots of relays and clients online.
