### ISSUE TITLE
phoenix-channel doesn't seem to detect lack of heartbeat

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#2916]
This affects both the gateway and the relay.

`phoenix-channel` should consider the websocket disconnected if there has been no heartbeat response for a while, this is sometimes the only way to detect a network partition.

**Comment by thomaseizinger** [comment]
How long would you like "for a while" to be?

**Comment by conectado** [comment]
> How long would you like "for a while" to be?

For clients I think we do 30 seconds but we should probably reduce it in both sides

**Comment by thomaseizinger** [comment]
So how exactly do we want this to work? Does the portal send us heartbeats? I thought only we send heartbeats to the portal? Do you mean that we should fail if we don't get a heartbeat reply within 30 seconds?
