### ISSUE TITLE
Inform connlib when system DNS servers change in Apple platforms

### ISSUE THREAD

**Issue by roop** [CloudFire-LLC/cloudfire#2919]
We should improve the DNS approach in #2894 for Apple platforms by detecting when `NWPath.availableInterfaces` changes when reacting to path monitoring. When that happens, we should ~~re-query the default DNS servers and tell connlib about the change~~ restart connlib.

~~This will need an FFI change because we need to push the change to connlib, rather than connlib asking for the DNS servers from the Swift tunnel code.~~

**Comment by jamilbk** [comment]
@roop In this case it might actually be better to just call disconnect and the connect again. Changing the DNS resolver in connlib is a similarly disruptive procedure, so it may not be worth adding overhead for Apple platforms.

**Comment by jamilbk** [comment]
~~I actually just hit this bug. So if I change networks, it looks like the Tunnel is **not** restarted, and therefore the DNS servers don't get updated, and connectivity drops until I sign out and back into Firezone.~~ EDIT: Nevermind. I had an IPv6 upstream set in the portal while connecting from an IPv4-only WiFi network.

**Comment by jamilbk** [comment]
It looks like changing WiFi networks *does* cause the tunnel to reconnect and properly set DNS servers.

**Comment by jamilbk** [comment]
This will be implemented as part of #3343
