### ISSUE TITLE
Timeout proxied DoH and DoT queries

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2920]
It looks like there's an iOS that seems to cause DNS resources not to be routed through the tunnel.

![IMG_112703FAB029-1](https://github.com/firezone/firezone/assets/167144/07a703d9-732d-4528-8448-72ff15a228cc)

**Comment by jamilbk** [comment]
Seems to only happen when I have a valid IPv6 address.

On IPv4-only networks, it gets routed properly

**Comment by jamilbk** [comment]
```
DNS lookup failed: Error with the DNS fallback lookup  err=DNSFallbackKind(Proto(ProtoError { kind: Msg("Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules })") }))
```

**Comment by jamilbk** [comment]
The plot thickens:

* ~~When the tunnel is up, some apps like Safari and Chrome ignore the `matchDomains` catch-all setting of `[""]` and send their queries to the DHCP-provided resolvers (`192.168.1.254` in my case).~~ Edit: it looks like they *are* being routed through the tunnel, but failing to be matched by the `ifconfig.net` resource in connlib.
* Other apps like ISC Dig and Ping (e.g. random Network utilities on the App Store) correctly resolve to the CGNAT space.
* Routes are fine; I can manually ping the IP mappings that connlib's DNS proxy creates.
* If I manually change my DNS server to `100.100.111.1`, iOS detects "No internet available" and I lose my connection to the Xcode debugger. But then Safari starts resolving correctly. Also, if I do this, connlib fails to forward non-Firezone queries (they start timing out with the error here: https://github.com/firezone/firezone/issues/2920#issuecomment-1858379810)
* If I try changing `matchDomains` to `["ifconfig.net"]`, Safari _still_ doesn't send queries to connlib's resolver.

**Comment by jamilbk** [comment]
Issue persists, re-opening. Seems to be intermittent.

**Comment by jamilbk** [comment]
@conectado Ok I'm certain this an issue with `connlib`. It seems that it's forwarding some queries to the default resolver for certain applications in iOS (namely: browser applications like Firezone, Chrome, Safari) instead of proxying to a gateway with a generated `100.64.96.0/11` or `fd00:2021:1111:8000::/107` address.

Here's a sample log:

```
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	sending request: [Query { name: Name("ifconfig.net"), query_type: HTTPS, query_class: IN }]	09:03:03.582626-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	enqueueing message:QUERY:[Query { name: Name("ifconfig.net"), query_type: HTTPS, query_class: IN }]	09:03:03.583146-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	enqueueing message:QUERY:[Query { name: Name("ifconfig.net"), query_type: HTTPS, query_class: IN }]	09:03:03.583115-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	enqueueing message:QUERY:[Query { name: Name("ifconfig.net"), query_type: HTTPS, query_class: IN }]	09:03:03.583322-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	final message: ; header 60969:QUERY:RD:NoError:QUERY:0/0/0
; query
;; ifconfig.net. IN HTTPS	09:03:03.583416-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	final message: ; header 42163:QUERY:RD:NoError:QUERY:0/0/0
; query
;; ifconfig.net. IN HTTPS	09:03:03.583497-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	enqueueing message:QUERY:[Query { name: Name("ifconfig.net"), query_type: HTTPS, query_class: IN }]	09:03:03.583070-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	enqueueing message:QUERY:[Query { name: Name("ifconfig.net"), query_type: HTTPS, query_class: IN }]	09:03:03.583296-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	final message: ; header 60969:QUERY:RD:NoError:QUERY:0/0/0
; query
;; ifconfig.net. IN HTTPS	09:03:03.583389-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	final message: ; header 42163:QUERY:RD:NoError:QUERY:0/0/0
; query
;; ifconfig.net. IN HTTPS	09:03:03.583471-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	enqueueing message:QUERY:[Query { name: Name("ifconfig.net"), query_type: HTTPS, query_class: IN }]	09:03:03.583348-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	final message: ; header 60969:QUERY:RD:NoError:QUERY:0/0/0
; query
;; ifconfig.net. IN HTTPS	09:03:03.583442-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	final message: ; header 42163:QUERY:RD:NoError:QUERY:0/0/0
; query
;; ifconfig.net. IN HTTPS	09:03:03.583523-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	Response:; header 42163:RESPONSE:RD,RA:NoError:QUERY:1/0/0
; query
;; ifconfig.net. IN HTTPS
; answers 1
ifconfig.net. 300 IN HTTPS 1 . alpn=h3,h2, ipv4hint=104.21.44.124,172.67.199.190, ipv6hint=2606:4700:3032::6815:2c7c,2606:4700:3033::ac43:c7be,
; nameservers 0
; additionals 0	09:03:03.589692-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	Response:; header 42163:RESPONSE:RD,RA:NoError:QUERY:1/0/0
; query
;; ifconfig.net. IN HTTPS
; answers 1
ifconfig.net. 300 IN HTTPS 1 . alpn=h3,h2, ipv4hint=104.21.44.124,172.67.199.190, ipv6hint=2606:4700:3032::6815:2c7c,2606:4700:3033::ac43:c7be,
; nameservers 0
; additionals 0	09:03:03.589718-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	Response:; header 42163:RESPONSE:RD,RA:NoError:QUERY:1/0/0
; query
;; ifconfig.net. IN HTTPS
; answers 1
ifconfig.net. 300 IN HTTPS 1 . alpn=h3,h2, ipv4hint=104.21.44.124,172.67.199.190, ipv6hint=2606:4700:3032::6815:2c7c,2606:4700:3033::ac43:c7be,
; nameservers 0
; additionals 0	09:03:03.589742-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	Response:; header 42163:RESPONSE:RD,RA:NoError:QUERY:1/0/0
; query
;; ifconfig.net. IN HTTPS
; answers 1
ifconfig.net. 300 IN HTTPS 1 . alpn=h3,h2, ipv4hint=104.21.44.124,172.67.199.190, ipv6hint=2606:4700:3032::6815:2c7c,2606:4700:3033::ac43:c7be,
; nameservers 0
; additionals 0	09:03:03.589798-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	Response:; header 42163:RESPONSE:RD,RA:NoError:QUERY:1/0/0
; query
;; ifconfig.net. IN HTTPS
; answers 1
ifconfig.net. 300 IN HTTPS 1 . alpn=h3,h2, ipv4hint=104.21.44.124,172.67.199.190, ipv6hint=2606:4700:3032::6815:2c7c,2606:4700:3033::ac43:c7be,
; nameservers 0
; additionals 0	09:03:03.589824-0800
debug	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	Response:; header 42163:RESPONSE:RD,RA:NoError:QUERY:1/0/0
; query
;; ifconfig.net. IN HTTPS
; answers 1
ifconfig.net. 300 IN HTTPS 1 . alpn=h3,h2, ipv4hint=104.21.44.124,172.67.199.190, ipv6hint=2606:4700:3032::6815:2c7c,2606:4700:3033::ac43:c7be,
; nameservers 0
; additionals 0	09:03:03.589771-0800
```

Is it possible that we fail to match certain types of queries?

**Comment by jamilbk** [comment]
I think what's happening is that iOS opportunistically uses DoH or DoT for the query, which we don't detect. Maybe we should block non-UDP/53 queries until we support those?

**Comment by conectado** [comment]
> I think what's happening is that iOS opportunistically uses DoH or DoT for the query, which we don't detect. Maybe we should block non-UDP/53 queries until we support those?

Yeah, that's exactly what's happening those are https requests and we just forward them here https://github.com/firezone/firezone/blob/main/rust/connlib/tunnel/src/dns.rs#L309

We should check if the question is a domain is a resource firezone handles we should respond with NXDomain.

**Comment by conectado** [comment]
I wonder how `hickory_resolver` is even getting a response for those since we set only udp dns nameservers. I guess it tries to use it to resolve the https query and succeeds anyways.

**Comment by jamilbk** [comment]
Yeah this is how:

```bash
% kdig -t HTTPS ifconfig.net
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 35569
;; Flags: qr rd ad; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; ifconfig.net.       		IN	HTTPS

;; ANSWER SECTION:
ifconfig.net.       	300	IN	HTTPS	1 . alpn=h3,h2 ipv4hint=104.21.44.124,172.67.199.190 ipv6hint=2606:4700:3032::6815:2c7c,2606:4700:3033::ac43:c7be

;; Received 103 B
;; Time 2023-12-16 16:22:21 PST
;; From 100.100.111.1@53(UDP) in 27.3 ms

```


TIL about the `HTTPS` record type: https://gcore.com/docs/dns/dns-records/what-is-an-https-record-and-how-is-it-configured

**Comment by jamilbk** [comment]
We could probably intercept these too?

**Comment by jamilbk** [comment]
Some more interesting data:

* So macOS updates `/etc/resolv.conf` when the tunnel comes up and goes down to our sentinel `100.100.111.1`.
* `scutil --dns` does have the info we want, but sadly this API isn't available from iOS. Also note that it doesn't show the connlib DNS server as "reachable":
```
jamil@Airbook-Mac:~ % scutil --dns
DNS configuration

resolver #1
  nameserver[0] : 100.100.111.1
  if_index : 52 (utun13)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 104400

resolver #2
  nameserver[0] : 10.128.128.128
  if_index : 12 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
```

**Comment by jamilbk** [comment]
So here's what's happening:

- `Session.connect` -> `getSystemDefaultResolvers` returns `1.1.1.1` (example)
- Change WiFi networks, or change other connectivity
- Tunnel goes into `reasserting` state, `Session.disconnect` is **not** called
- Tunnel connectivity resumes (connlib detects this), and "reinitializes"
- connlib calls `getSystemDefaultResolvers` again, but this time with the Tunnel state `connected` and it now returns `100.100.111.1`.

So here's my proposed fix:

- Remove `getSystemDefaultResolvers` callback
- Send `systemDefaultResolvers` in the `connect` call instead. These should not change as long as the tunnel is up.
- When `connlib` receives the `init`, if `upstreamDNS` is set, use those resolvers. Otherwise, use the `systemDefaultResolvers` from the `connect` call.
- On the app-side, eagerly call `Session.disconnect` and then `connect` when the network path changes

This way, connlib only `reinitializes` with the current resolvers.

**Comment by conectado** [comment]
> We could probably intercept these too?

Yeah, should be easy enough it seems very similar to an A/AAAA record. As long as we can respond with a udp packet we're fine.

**Comment by jamilbk** [comment]
So actually this has nothing to do with DoT or DoH. It is actually a new record type (agnostic to the underlying transport) that saves a roundtrip by telling the application (typically browsers) the requested domain is available over https and even what versions of HTTP the server supports. It can send a pubkey to use for encrypted client helo for TLS.

Supporting HTTPS records would be similar to A and AAAA where we need to query for the actual IP on the gateway to use for the mapping, but with additional rabbit holes.

We could approach it in a timeboxed manner to spend maybe a couple days on it and if it’s still not reliable, just save HTTPS record support for later (and respond with NXDOMAIN for them for now)

https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns/

**Comment by conectado** [comment]
> So actually this has nothing to do with DoT or DoH. It is actually a new record type (agnostic to the underlying transport) that saves a roundtrip by telling the application (typically browsers) the requested domain is available over https and even what versions of HTTP the server supports. It can send a pubkey to use for encrypted client helo for TLS.
> 
> Supporting HTTPS records would be similar to A and AAAA where we need to query for the actual IP on the gateway to use for the mapping, but with additional rabbit holes.
> 
> We could approach it in a timeboxed manner to spend maybe a couple days on it and if it’s still not reliable, just save HTTPS record support for later (and respond with NXDOMAIN for them for now)
> 
> https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns/

I will take a stab at this today, and try to see how hard this would be.

**Comment by conectado** [comment]
@jamilbk 
> We could approach it in a timeboxed manner to spend maybe a couple days on it and if it’s still not reliable, just save HTTPS record support for later (and respond with NXDOMAIN for them for now)

let's save this for later, we need to change how we approach DNS queries for gateways completelty. For `HTTPS` queries we need things that are encoded in the DNS answer that're not the server IPs and are not provided by [`to_socket_addrs`](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html) and neither in [`get_addr_info`](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html) for that matter.

We will want to change this later, and use something like `hickory-resolver` instead of the standard syscall but it will take quite some work.
