### ISSUE TITLE
Handle duplicate / overlapping Resource addresses

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2941]
This happens on the Apple client because `postgres.firez.one` is defined in two sites:

```
ForEach<Array<Resource>, String, HStack<TupleView<(Text, Spacer, Text, Button<ModifiedContent<ModifiedContent<Label<Text, Image>, _EnvironmentKeyWritingModifier<Optional<SymbolRenderingMode>>>, _EnvironmentKeyWritingModifier<Optional<Color>>>>)>>>: the ID postgres.firez.one occurs multiple times within the collection, this will give undefined results!
```

We could solve this with #2801 that we enforce to be unique across the entire account.

**Comment by AndrewDryga** [comment]
Should we make resource addresses unique again? This won't let users to get undefined behavior (eg two equal cidrs), which can be useful especially for DNS and IP resources where "shortest prefix" doesn't apply at all.

**Comment by jamilbk** [comment]
Hmm, I think we'll need a more robust way to handle address collisions. For now we can just allow them and add a note in the docs to avoid overlaps. If we enforce uniqueness that would prevent the use cases where the admin wants to grant access to two identical Resources with the same address in different sites.

**Comment by jamilbk** [comment]
Refs #2801

**Comment by jamilbk** [comment]
Closing to track this in #2801
