### ISSUE TITLE
Authorizations aren't consistent across all identities for an actor

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2942]
Hit an interesting bug just now:

When logging in via magic link, I can't access any of the Resources in my resource list. Pings timeout and connections hang in the client with:

```
error	dev.firezone.firezone	connlib	FirezoneNetworkExtensioniOS	Error request connection details: Pending connection	08:06:29.224345-0800
```

When logging in via Google Workspace, things work fine

This is on staging trying to ping the `8.8.8.8` resource

**Comment by AndrewDryga** [comment]
This looks extremely unlikely to be tied to auth, after you signed in we don't care which method you used. I will try to see what else might be the reason

**Comment by jamilbk** [comment]
You're right, something else must have been happening.
