### ISSUE TITLE
Gracefully handle portal disconnections lasting more than a few seconds

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2946]
If the connection to the portal drops for more than 60 seconds, all hell breaks loose in connlib, and its state never successfully heals. We shouldn't depend on the client to `disconnect` us because some OSes don't know how to do that (Linux). Instead, we should handle it ourselves.

connlib should be able to handle network partitions lasting up to `X seconds` (configurable) global timeout with the portal, after which point it calls `onDisconnect` without an error (so that the token is *not* cleared). `X seconds` is expected to be on the order of ~300 seconds (5 minutes), but could be longer.

**Comment by jamilbk** [comment]
The intention for this issue is to have a reliable reconnect / connection down detector than we can use to issue callbacks _to the client_ on the state of the tunnel/adapter and not the other way around. In essence, doing our own path monitoring.

This cross-platform approach would make it easier to communicate to the user the _real_ connection status of their Firezone client and not rely on a mixture of OS-specific path monitoring and connlib errors to derive a client state to show to the user. That seems like an endless rabbithole of UI state bugs

**Comment by conectado** [comment]
> connlib should be able to handle network partitions lasting up to X seconds (configurable) global timeout with the portal, after which point it calls onDisconnect without an error (so that the token is not cleared). X seconds is expected to be on the order of ~300 seconds (5 minutes), but could be longer.

How will it be configurable? will it be handed down by `Session::connect`?

**Comment by jamilbk** [comment]
@conectado Could just be a constant/hidden env var for now that we can override for tests.

**Comment by conectado** [comment]
@jamilbk kk, I will use an env var and default to 5 mins if it's not there
