### ISSUE TITLE
Default-Admin user is only changeable via firezone.rb, and password is only changable via secrets.json

### ISSUE THREAD

**Issue by PhoenixSheppy** [CloudFire-LLC/cloudfire#296]
I was able to successfully install Firezone in a VM on my Synology NAS, but when I went to configure my default admin user, I was unable to change the email address, or the password. It seems that they're "hardcoded" into Firezone.

When attempting to change, the page sits for a second, then refreshes and repopulates with firezone@localhost and nothing in the password field(s).

I would highly suggest moving away from that model due to security concerns. If someone manages to get ahold of your FZ password it isn't easy to change without having to edit a file, and reconfigure.

**Comment by jamilbk** [comment]
Thanks for the bug report! Is this happening on the Account page? The email and password should be editable on the form there:

<img width="1552" alt="Screen Shot 2021-10-15 at 9 49 28 AM" src="https://user-images.githubusercontent.com/167144/137524166-28f8b270-12d2-4d00-bc10-b0d2bc66cadc.png">

If the whole page is reloading when you try to submit the form, that means the WebSocket likely crashed. Does adding a Device work or does that cause page reload as well?

**Comment by PhoenixSheppy** [comment]
Both cause the page to reload, I'm guessing I didn't enable websockets via NGINX.

I'll have to re-install and take a look later. I'll let you know what I find.

**Comment by jamilbk** [comment]
> I'm guessing I didn't enable websockets via NGINX.

The issue is likely that your FQDN used in the URL bar to access Firezone and the FQDN configured in /etc/firezone/firezone.rb don't match. WebSockets requires these to be the same in order to securely connect. Make sure these match and run `firezone-ctl reconfigure` and see if that fixes your issue.

**Comment by PhoenixSheppy** [comment]
With further testing, I turned on websockets and got it to work. Thanks!
