### ISSUE TITLE
Intermittent `422` received when connlib tries to connect for existing actors

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2980]
Getting a 422 when trying to sign into the client with a magic link identity that has the `account_admin` role:

```
error	dev.firezone.firezone	connlib	FirezoneNetworkExtensionmacOS	Portal connection error  error=PortalConnectionError(Http(Response { status: 422, version: HTTP/1.1, headers: {"cache-control": "max-age=0, private, must-revalidate", "content-length": "40", "date": "Thu, 21 Dec 2023 15:07:14 GMT", "server": "Cowboy", "via": "1.1 google", "x-cache-hit": "disabled", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000", "connection": "close"}, body: Some([]) }))	07:07:14.599127-0800
```

**Comment by jamilbk** [comment]
Actually it seems to be happening regardless of whether I use Google or Email to sign in. Strange.

Authentication to the admin dashboard works fine.

**Comment by AndrewDryga** [comment]
@jamilbk 422 means that the request payload is malformed, eg. one of the required properties is empty. Do you happen to have the JSON and headers connlib sent to the portal?

**Comment by jamilbk** [comment]
@AndrewDryga I'll see if I can get a dump for you

**Comment by jamilbk** [comment]
```
Request: "GET /client/websocket?token=<snipped>&public_key=aZIJdbK1azPlk0IGN4SgENvTlPf7JYEluxr0CZjDpw0%3D&external_id=77dd744aeca093f8ba2fbc7181132164050acb2aecef45040638ce364aba8a78&name=Airbook-Mac.local HTTP/1.1\r\nHost: api.firez.one\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: p1FPEIJ3elRGFK7RjEw2AQ==\r\nuser-agent: Mac OS/13.6.3 connlib/1.0.0\r\n\r\n"  log.file="/Users/jamil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tungstenite-0.20.1/src/handshake/client.rs" log.line=177 log.module_path="tungstenite::handshake::client" log.target="tungstenite::handshake::client"
```

**Comment by jamilbk** [comment]
Did the hostname recently get added to connlib? ~~Maybe `Airbook-Mac.local` needs to be URL-encoded... cc @conectado~~ Nevermind, that shouldn't be the issue

**Comment by jamilbk** [comment]
Wild guess -- `name` upsert isn't working for existing clients? Let me try a new client ID.

**Comment by jamilbk** [comment]
Yeah I think that's it. If I connect via WiFi (different MAC address, different client ID) it's successful:

```
Request: "GET /client/websocket?token=SFMyNTY.g2gDaAN3CGlkZW50aXR5bQAAACQ3NTk0ODQzOS1lN2U3LTQwNDAtOWU5OC0zYmJkN2JiMWQ2NGZ3Bmlnbm9yZW4GAKf7CI2MAWIAAAeL.IaAyxXPKFawIS8z-29eR1EUyAeigu8Vc2PW1JefkQzM&public_key=fZi7BdoVTe2fLfjxjaXsNFukUl3PpghikUpHsHBgjXc%3D&external_id=fc67d2cd7f0f912a0511f48432806512310f3e11ed1a25cefe1830499ebd5f3f&name=Airbook-Mac.attlocal.net HTTP/1.1\r\nHost: api.firez.one\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: llqJmSFgzAvf6hcJscAAvw==\r\nuser-agent: Mac OS/13.6.3 connlib/1.0.0\r\n\r\n"  log.file="/Users/jamil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tungstenite-0.20.1/src/handshake/client.rs" log.line=177 log.module_path="tungstenite::handshake::client" log.target="tungstenite::handshake::client"
```

**Comment by AndrewDryga** [comment]
@jamilbk we have tests for pretty much every wild guess in the portal :). I think the issue here is that nobody deployed to prod this: https://github.com/firezone/firezone/commit/fa35658db6a7b3924b2e918bcd5a584ab706d308

**Comment by AndrewDryga** [comment]
Oh, you use staging. Okay, let me push a debug statement and we will see what changeset is saying

**Comment by jamilbk** [comment]
On macOS we should probably persist the device UUID to disk like we do for Windows and other clients that don't have a platform-provided device hardware ID

**Comment by AndrewDryga** [comment]
@jamilbk can you try that request once more and see what the response body is? I've patched the staging API instances to render changeset errors

**Comment by conectado** [comment]
> Did the hostname recently get added to connlib? Maybe `Airbook Mac.local` needs to be URL-encoded... cc @conectado 

@jamilbk in the pasted URL it's using a hyphen which doesn't need to be encoded. AFAIK the `Url` type should already properly encode urls, I will do a bit more testing.

**Comment by conectado** [comment]
> > Did the hostname recently get added to connlib? Maybe `Airbook Mac.local` needs to be URL-encoded... cc @conectado 
> 
> @jamilbk in the pasted URL it's using a hyphen which doesn't need to be encoded. AFAIK the `Url` type should already properly encode urls, I will do a bit more testing.

But I think this segment proves it's url-encoded:

`aZIJdbK1azPlk0IGN4SgENvTlPf7JYEluxr0CZjDpw0%3D`

**Comment by jamilbk** [comment]
@conectado Can we get response bodies decoded easily in the trace log?

```
Some([73, 110, 118, 97, 108, 105, 100, 32, 111, 114, 32, 109, 105, 115, 115, 105, 110, 103, 32, 99, 111, 110, 110, 101, 99, 116, 105, 111, 110, 32, 112, 97, 114, 97, 109, 101, 116, 101, 114, 115, 58, 32, 110, 97, 109, 101, 58, 32, 104, 97, 115, 32, 97, 108, 114, 101, 97, 100, 121, 32, 98, 101, 101, 110, 32, 116, 97, 107, 101, 110, 10])
```

**Comment by jamilbk** [comment]
Haha nevermind, Elixir does it automatically (sorry @conectado)

```
iex(1)> bytes = [73, 110, 118, 97, 108, 105, 100, 32, 111, 114, 32, 109, 105, 115, 115, 105, 110, 103, 32, 99, 111, 110, 110, 101, 99, 116, 105, 111, 110, 32, 112, 97, 114, 97, 109, 101, 116, 101, 114, 115, 58, 32, 110, 97, 109, 101, 58, 32, 104, 97, 115, 32, 97, 108, 114, 101, 97, 100, 121, 32, 98, 101, 101, 110, 32, 116, 97, 107, 101, 110, 10]
'Invalid or missing connection parameters: name: has already been taken\n'
```

**Comment by AndrewDryga** [comment]
@jamilbk ah, so the issue is that you keep changing names without keeping the ID because, as you mentioned, we don't persist UUID to disk - which we should totally do. I will remove the constraint.

**Comment by jamilbk** [comment]
Sounds good. I can probably knock that out real quick.

**Comment by AndrewDryga** [comment]
@jamilbk the core of the issue is that the name was created by a different client and then when you change the ID but keep the name we are trying to create a duplicate client and hit a conflict, I've pushed a PR to fix it, and render errors whenever that happens.

**Comment by jamilbk** [comment]
@AndrewDryga I'm not sure we can rely on or expect the name being unique. E.g. `John's Macbook Air`

**Comment by AndrewDryga** [comment]
@jamilbk yeah, that was my wrong assumption that I put in the codebase 6 months ago thinking it would be good for UX, but we can't enforce it
