### ISSUE TITLE
Generate UUIDv4 as `deviceId` and persist on macOS

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2981]
On macOS we don't have the luxury of `UIDevice`, so we need to persist a UUIDv4 to disk on first run (Keychain?). This ID should persist for as long as the app is installed, and passed to the `Session.connect` call instead of the PrimaryMacAddress functionality we use today.

Similar to how we have the Windows and (soon) Linux clients.

**Comment by jamilbk** [comment]
Causing part of the problem in #2980

**Comment by jamilbk** [comment]
Should be stored independent of TunnelStore and AuthStore so that it's not settings or tunnel dependent. I.e. the user can change settings and reset the tunnel configuration without affecting the `deviceId`.

**Comment by AndrewDryga** [comment]
When we persist it to Keychain can be make sure it won't be synced across devices?

**Comment by jamilbk** [comment]
@AndrewDryga This should be the case already with the tunnel settings 👍
