### ISSUE TITLE
Public address without port

### ISSUE THREAD

**Issue by w202mg** [CloudFire-LLC/cloudfire#301]
Don't know if really an issue. I'm running nginx for several other instances so to get Firezone running I had to use another port for SSL (444). Now together with the public address I have to use also the port- https://fire.example.net:444. Maybe there is a way to eliminate this to make it looking better.

**Comment by jamilbk** [comment]
Hi @w202mg -- It's not possible for two processes to listen on the same port, so you'll either need to combine your nginx configs or redirect / proxy requests somehow.

Your best bet is probably disabling the bundled Firezone nginx service and instead adding the Firezone nginx config to your own nginx instance's `sites-enabled`. This is an unsupported configuration (for now), but you may have luck if you try something like this:

1. Set `default['firezone']['nginx']['enable'] = false` in /etc/firezone/firezone.rb, then run `firezone-ctl reconfigure`. This disables the Firezone nginx service.
2. Link the Firezone phoenix web app config to your own nginx sites-enabled: `ln -s /var/opt/firezone/nginx/etc/sites-enabled/phoenix /etc/nginx/sites-enabled/firezone`
3. Reload your nginx config: `systemctl reload nginx`

**Comment by w202mg** [comment]
OK, thank you, I'll give it a try

**Comment by jamilbk** [comment]
@w202mg Did this work? Can I close this issue?

**Comment by w202mg** [comment]
@jamilbk didn't try so far. Don't know if I shall because I understood this will be supported in the future. If I'm right. If not I will try.

**Comment by jamilbk** [comment]
Hi @w202mg 

I just tested this, and confirm it works. Something like the following should work for you:

1. Set `default['firezone']['nginx']['enabled'] = false` in your `/etc/firezone/firezone.rb` config file
2. Run `firezone-ctl reconfigure`
3. Copy the nginx site config from `/var/opt/firezone/nginx/etc/sites-enabled/phoenix` to your local nginx sites at `/etc/nginx/sites-enabled/`
4. Copy the relevant nginx.conf sections out of `/var/opt/firezone/nginx/etc/nginx.conf` to your `/etc/nginx/nginx.conf` file.

That should allow your existing nginx server to proxy the firezone app.
