### ISSUE TITLE
Properly handle DNS TTL

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#3010]
Currently the gateway gets the DNS resolution using `ToSockAddr` trait which doesn't expose the DNS response, with fields such as the TTL.

We need to change it, get the proper TTL, have the client use it and update the DNS records accordingly.

This will require a sizeable refactor for how we handle DNS updates.

**Comment by jamilbk** [comment]
refs #3975

**Comment by jamilbk** [comment]
I don't think this is relevant anymore. Feel free to reopen otherwise.
