### ISSUE TITLE
iOS app stuck at connecting on first sign in

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3023]
iOS app was stuck in "Connecting..." at first sign in (token received, but callback from connlib not received). Issue persisted across app restarts. Ultimately resolved by uninstalling and reinstalling the application.

Potential underlying network instability could have caused this, but we should have a fairly short timeout in this state.

**Comment by roop** [comment]
So, if we don't get onTunnelReady within sometime (say 20 seconds), should we tear down the tunnel and try to restart the tunnel process?

**Comment by jamilbk** [comment]
@roop Hmm Yeah that makes sense. I was thinking more like 10 seconds, because this user was accustomed to it connecting almost immediately the majority of the time.

But the more I think about it, the more I feel like this scenario should come connlib and the clients just handle it.

@Conectado Did we ever define a connlib timeout between calling `connect` and returning the onTunnelReady? Maybe we can call onDisconnect in that window if the initial portal connection doesn't get established within 10 seconds

**Comment by roop** [comment]
But if connlib calls onDisconnect, we'll sign the user out. We need some other call / way to tell the client tunnel process that the app should retry connecting.

**Comment by jamilbk** [comment]
@roop That's right.

But I might argue the token isn't valid if it can't be used to successfully connect connlib. Consider the case where the API_URL and AUTH_BASE_URL are mismatched by accident.

When the user arrives at this scenario, they're still in the "signing in" flow. I think it'd be fine to let connlib call onDisconnect with an error like "API server connection timeout" at this point. The user is present and is expecting a quick success/fail response to their attempt at signing in.

When connlib is _already_ connected in the background, portal timeouts and errors should trigger reconnect retry logic before calling onDisconnect.

But if a successful connection hasn't been made yet (i.e. user hasn't completed the sign in flow), calling onDisconnect right away with an appropriate error should resolve the problem experienced by the user in this case.

**Comment by jamilbk** [comment]
This would be implemented as a side effect of the refactoring done in #3343
