### ISSUE TITLE
Own DNS server

### ISSUE THREAD

**Issue by w202mg** [CloudFire-LLC/cloudfire#303]
Hey, tried my best to find the point to change to save my own DNS server instead of 1.1.1.1. Any chance to change it?

**Comment by jamilbk** [comment]
You can edit the DNS server per-device -- just click the `Edit` button when viewing a device. This just updates the config (and QR code) displayed for that device so you'll want to re-copy and paste it (or rescan the QR code) as your WireGuard config on the device.

**Comment by w202mg** [comment]
This is clear, but would be great to change this by default because I use same DNS server for all devices. This option would be great.

**Comment by w202mg** [comment]
By default I mean in the same way I can change the endpoint in `/etc/firezone/firezone.rb`.

**Comment by jamilbk** [comment]
Noted! This feature is actually already in our backlog and should be fairly straightforward to implement. I hope to tackle it soon.

Thanks for the suggestion.

**Comment by w202mg** [comment]
By the way I tried to edit the DNS server in the UI using the edit button but after saving in the right part the DNS is still the same, and the QR code still contains the default DNS server.

> You can edit the DNS server per-device -- just click the `Edit` button when viewing a device. This just updates the config (and QR code) displayed for that device so you'll want to re-copy and paste it (or rescan the QR code) as your WireGuard config on the device.

**Comment by w202mg** [comment]
To make it perfect I think there shall be a possibility to leave DNS server also blank (like nil). This is usefull for everybody who has their own DNS servers in the local network configured in DHCP. Last thing I personally miss after Firezone got reboot safe.

**Comment by jamilbk** [comment]
> By the way I tried to edit the DNS server in the UI using the edit button but after saving in the right part the DNS is still the same, and the QR code still contains the default DNS server.

Hmmm. I'm not able to reproduce this issue on my end. Are you still experiencing this issue?

**Comment by w202mg** [comment]
Yes, it still persists. You can see in the attached image left and right the DNS servers are different. So if I change the DNS server left on the right it stays unchanged.

![image](https://user-images.githubusercontent.com/84856053/138701111-8786c120-6cac-4c77-8902-cc5e95e011d0.png)

**Comment by jamilbk** [comment]
Thanks for the report! I've reproduced the issue and will have a fix out in a bit.

**Comment by w202mg** [comment]
@jamilbk thank you for a great job. one thing I noticed. I had in 1.15 2 devices. Once I change (or better to say deleted) the DNS server in one device, it disappeared also in the second. After I added 2 new devices I could change the DNS server in them without any issue. So this issue seems to exist only with existing devices.

Is there now a possibility to set a default DNS server in the config?

**Comment by jamilbk** [comment]
@w202mg I don't think I can reproduce your new issue -- device DNS should default to `1.1.1.1, 1.0.0.1` for new devices and changing a device's DNS servers shouldn't affect other devices. That's a strange issue -- wonder if something else is going on there.

The global DNS config setting change is still coming. It's going to require a little more rearchitecting than originally thought but is still planned.
