### ISSUE TITLE
Handshake did not complete after 5 seconds, retrying...

### ISSUE THREAD

**Issue by PhoenixSheppy** [CloudFire-LLC/cloudfire#304]
Got websockets working, web-end works great, but I can't get my clients to connect over WAN.

Tested this for 3+ hours last night, got literally nowhere.

I create a device, I scan the QR code on my Pixel 4 XL, and then attempt to connect and it won't establish a handshake with the server.

I've port-forwarded the port I'm using to the local address of the VM that's running firezone / wireguard. I completely disabled UFW/IPTables, and got local handshakes to work, but still nothing over WAN.

**Comment by jamilbk** [comment]
Firezone uses the kernel's netfilter system to set up NAT/masquerading so if ufw or iptables rules are active it will likely interfere. If the handshakes are working but you're not getting any WAN connectivity, it's probably a routing issue.

What's the output of `route -n`, `iptables -L`, and `/opt/firezone/embedded/sbin/nft list ruleset`?

Is your VM using a host network adapter or is it NATed?

**Comment by jamilbk** [comment]
Edit: Ahh I see, the handshakes *aren't* working for you actually.

Are you able to reach other services on the VM like SSH? What's the output of `/opt/firezone/embedded/bin/wg` and `ip link`? Sounds like either the WireGuard interface isn't up or the UDP packets aren't reaching the VM on the right port.

**Comment by jamilbk** [comment]
@PhoenixSheppy Also, check to ensure the `Endpoint` config option is set properly in the device config that Firezone generates. This is pulled from the `default['firezone']['wireguard']['endpoint']` configuration variable in `/etc/firezone/firezone.rb` and is set to the egress IP of the host if not specified. In your case, that would likely result in an RFC1918 address since you're running on a VM, which would explain your scenario.

**Comment by PhoenixSheppy** [comment]
@jamilbk I'll have to check my VM, but it's got it's own IP (i.e. 192.168.1.x) and I can SSH into it.

I purposely disabled the firewall entirely (UFW + iptables) in an attempt to get it to work, and saw success on my local network.
(WG can make handshakes over the local network, but not the internet)

The endpoint is set to a domain that is reachable over the internet that directs to a public IP.

Still tripped up...

**Comment by jamilbk** [comment]
Hmm if WireGuard can make handshakes on the local net, I'm willing to be the problem is unlikely to be Firezone.

Does the port show as open if you do a `sudo nmap -sU -p51820 firezone.example.com` over WAN?

**Comment by PhoenixSheppy** [comment]
Tried checking the port, it's showing as closed, but I have it port forwarded in my UniFi OS Console...

I've also tried using other ports that are lower, no dice.

**Comment by jamilbk** [comment]
Hmmm. Very strange. If you add a new device, and try using the config for that new device, does that work? I found an edge case where peers aren't loaded correctly at Firezone bootup that may be causing this.

I'm also working to add WireGuard kernel debugging logs to Firezone so you can see if WireGuard is picking up the failed handshakes (assuming you're on a 5.6 or above kernel).

These should be ready in the next day or so.

**Comment by PhoenixSheppy** [comment]
Tried adding new devices, still nothing. This is really baffling me, I've never had this much trouble hosting a VPN.

My Pritunl Install works just fine over OVPN, but I'd like to migrate away from it if possible. Hence using firezone.

WG doesn't work there either.

**Comment by jamilbk** [comment]
If your kernel is 5.6 or newer, you can view enable WireGuard module debugging with:

```bash
sudo echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control
```

And view with:

```bash
sudo dmesg -T -f kern | grep wireguard
```

That will show any failed handshakes. You can also use `/opt/firezone/embedded/bin/wg` to view the WireGuard interface private key, loaded peers, etc. Hope that helps.

Lastly, I personally use UniFi devices for my home network and have had issues with the port forwarding settings not being applied (even though they show as enabled in the UI), so you may want to double-check that your changes are being applied there. The `closed` port from your nmap scan may be a hint. FWIW, nmapping my working demo Firezone instance shows the port as `open|filtered`.

**Comment by PhoenixSheppy** [comment]
Tried using both of those commands, first one didn't display anything.
Second just says Wireguard is started.

And I'm looking to see if there were any issues with applying my rules...

**Comment by jamilbk** [comment]
> Second just says Wireguard is started.

Once you enable debugging with `sudo echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control` you should see failed handshake messages in dmesg if the packets are reaching the Firezone VM:

```
root@demo:~# dmesg -w -f kern -T | grep wireguard
[Tue Oct 19 17:38:03 2021] wireguard: WireGuard 1.0.0 loaded. See www.wireguard.com for information.
[Tue Oct 19 17:38:03 2021] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[Tue Oct 19 18:32:55 2021] wireguard: wg-firezone: Invalid handshake initiation from ...
[Tue Oct 19 18:33:00 2021] wireguard: wg-firezone: Invalid handshake initiation from ...
[Tue Oct 19 18:33:05 2021] wireguard: wg-firezone: Invalid handshake initiation from ...
```

If there's nothing there, the packets must be blocked somewhere upstream.

**Comment by jamilbk** [comment]
@PhoenixSheppy Any luck getting to the root of this? Can I go ahead and close this issue?

**Comment by PhoenixSheppy** [comment]
@jamilbk After further research this may be NAT related. Something about UDP packets having trouble traversing over NAT.

In the end I ended up going with Tailscale. I like their software / model so I bit the bullet and went with them. It's still Wireguard in the end, just have to use a relay.

I'm tossing this issue up to network / use-case scenario limitations.

Thanks again! Perhaps in the future I can get it working, who knows. ¯\_(ツ)_/¯

**Comment by jamilbk** [comment]
Ahhh bummer. Yeah we're still pretty new so maybe we'll hit this issue again and be able to identify it better in the future.

I wonder if the issue was related to double NAT (your home router + VM NAT).

**Comment by Mafioso** [comment]
Have the same issue. Fresh install using docker my VM have internal IP but from the internet it NATed from public IP. I can't ping the docker address and main host.
