### ISSUE TITLE
Use wildcard syntax to match subdomains

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3040]
It's not clear when creating a DNS resource that it matches subdomains as well. We should add a note in the portal clarifying, or simply use the standard `*.google.com` syntax to match subdomains.

In the docs, we should add:

- How DNS routing works (summary)
- How to match subdomains

**Comment by AndrewDryga** [comment]
Portal already supports this syntax, along with ?.domain.com. But connlib doesn't.

**Comment by jamilbk** [comment]
There's two syntaxes we may want to support:

- `*.google.com` -- all subdomains recursively
- `?.google.com` -- just one level of subdomains

**Comment by conectado** [comment]
@jamilbk should `*.google.com` include `google.com`(and same for `?`)?

**Comment by jamilbk** [comment]
@conectado Yeah, that's how I've seen most DNS apps behave
