### ISSUE TITLE
Windows crash logs

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3111]
Investigate adding Windows crash logs support similar to how we do it for Apple and Android (Microsoft-supported)

**Comment by ReactorScram** [comment]
After digging through the docs, Windows Dev Center might be it https://developer.microsoft.com/en-us/windows/
Checking this out now

**Comment by ReactorScram** [comment]
Thomas recommended Sentry. Their onboarding is really smooth and it looks promising.

I have a 14-day free trial. Their cheap plan starts at $30 / month. Not sure what the limits are but if it gets pricey we could ditch it for some custom Breakpad thing. @jamilbk Your call https://sentry.io/pricing/

![image](https://github.com/firezone/firezone/assets/13400041/897cca15-99a2-4739-9f93-51b48a1a490f)

**Comment by ReactorScram** [comment]
We decided against Sentry due to cost / trouble of hosting.
Today I'll go ahead with trying to integrate Breakpad into a Hello World program and, if that works, into the Windows GUI client.

Update: Sentry is still on the table for the future https://github.com/firezone/firezone/issues/3450#issuecomment-1921377685
Instead of Breakpad I ended up using a Rust crash handler someone made based on the same principles as Breakpad

**Comment by ReactorScram** [comment]
There's a Rust re-implementation of Breakpad that worked well in a Hello World test program.
Here's the steps to get it ready as if it were going to prod in the Firezone client:

1. Copy the sample code from https://github.com/EmbarkStudios/crash-handling/blob/main/minidumper/examples/diskwrite.rs
2. Add deps to Cargo.toml until it compiles
3. Put this in Cargo.toml

```
[profile.release]
# Generate debug symbols for the crash handler to use
debug = "full"
```

4. Build it (In CI we would need to add the pdb files as artifacts)

To prepare a dev system for parsing dumps:

1. `cargo install dump_syms` to install Mozilla's pdb --> sym converter tool
2. `dump_syms -o target/debug/my-program.syms target/debug/my-program.pdb` to convert the Microsoft PDB format to Breakpad syms file.
3. Manually compile minidump-stackwalk with this PR from the antagonist of Celeste included https://github.com/rust-minidump/rust-minidump/pull/891

When you get a crash dump, run `minidump-stackwalker --symbols-path my-program.syms 1d6b12bf-fce8-4426-8697-f3765d7596dc.dmp` to see the stack traces of all threads and some other info.
