### ISSUE TITLE
windows: DNS / stale connection issues

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3113]
**Describe the bug**
Web browsers don't seem to pick up the tunnel DNS as expected, sometimes

**To Reproduce**
Pick a test web browser. (I'll use Chrome since it's not my default)
Make sure the Firezone client has a valid token.
Completely close the test browser and the Firezone client.

Start the test browser and load ifconfig.net. It should show your real IP.
Start the client and wait 30 seconds for the tunnel to come up. (The Windows client is slow to bring the tunnel up)
Refresh the test browser. It should show the gateway's IP.

Reset the test and re-run it, but instead of waiting 30 seconds, refresh the page every 5 seconds for 30 seconds. The browser will keep showing the real IP. Wait another 30 seconds (a total of 60 seconds since starting the client) and then refresh, and it should show the gateway IP.

**Expected behavior**
I expect that I can refresh ifconfig.net any number of times and it will switch from showing my IP to showing the gateway's IP as soon as the tunnel is up.

I don't expect that refreshing the page would cause the browser to not use the tunnel.

**Screenshots / Logs**
N/A

**Platform (please complete the following information):**
 - Firezone Version 3a4f2cf9c0 (MTU fixed)
 - OS: Windows 11

N/A

**Comment by ReactorScram** [comment]
If I do `ipconfig /release` and `ipconfig /renew` this seems to fix Firefox immediately, but it's a pretty big thing to do since it'll mess up all networking stuff on the system.

Chrome doesn't seem to take that hint at all. I have to either restart Chrome, or stop using it for 30 seconds and then refresh, and it'll pick up the new DNS server.

All this time, curl and nslookup work perfectly, which makes me think Windows itself is aware of everywhere and the browsers just didn't get the hint.

**Comment by ReactorScram** [comment]
`ipconfig /registerdns` and `ipconfig /flushdns` from Tailscale don't seem to do anything

**Comment by ReactorScram** [comment]
Updating etc/hosts didn't seem to affect Firefox or Chrome.

**Comment by ReactorScram** [comment]
Loading another page doesn't seem to hint at Chrome that its DNS cache is stale:

1. Close everything
2. Open Chrome to ifconfig.net, it shows my real IP
3. Start the client
4. Open whatismyip.com in Chrome, it shows the gateway IP
5. Refresh the ifconfig.net page, it still shows my real IP

If I start the client first and then start Chrome, it does show the gateway IP.

**Comment by ReactorScram** [comment]
My new hypothesis is that Chrome is actually fine, but Firezone has an interval of about 10 seconds during startup where the DNS server returns errors or allows requests to time out. You can see this interval by spamming `nslookup`. If Chrome tries to load _any_ page during this interval, even a non-resource page, it will decide that our DNS server is broken and never use us for lookups again.

If that startup interval passes without Chrome talking to our DNS, Chrome works perfectly.

The only exception is private windows. When you open a private window in Chrome, the new browsing session gives our DNS server another chance, and tunnels instantly if the server is working. This state is not shared between the sessions, so the main window will still not tunnel.

I haven't tested Firefox because I don't want to restart my main browser constantly, but it probably works the same. I can test it in the VM or as a portable app or something.

The faster add_route patch #3118 reduces this interval, but it's still present. I think if we could either add the DNS server's route last, once the server is running, or if we could get the server to set up faster, that interval would vanish.

The only exception.

If you do this, Chrome will tunnel correctly:
1. Load ifconfig.net in Chrome, and start a stopwatch (t=0 seconds)
2. Start the client
3. Wait for the client (including the #3118 faster add_route patch) to start up
4. At t=15 seconds, reload ifconfig.net. Chrome will tunnel it.

When I did this, Chrome did not tunnel properly:
1. Load ifconfig.net in Chrome, and start a stopwatch (t=0 seconds)
2. Start the client
3. At t=5 seconds, reload ifconfig.net. Chrome will not tunnel because our DNS server gives a response it doesn't like
4. At t=15 seconds, reload. Chrome will still not tunnel.
5. At t=60 seconds, reload. Chrome will still not tunnel.
6. Load ifconfig.net in a private window. Chrome does tunnel it.

**Comment by ReactorScram** [comment]
Well it's hard to test accurately until the IPv6 fixes land, because sometimes our DNS server gives Chrome an IPv6 address that won't work. Maybe that's part of it.

**Comment by ReactorScram** [comment]
Now I'm seeing chrome://net-internals/#dns say that it has cached the tunneled IPs for ifconfig.net, and in another tab it's still going outside the tunnel. Even with the add_route, ipv6 address, and ipv6 MTU fixes merged into a dev branch.

**Comment by ReactorScram** [comment]
I talked to Gabi a lot and now I don't know if DNS is involved in this.

It might be the socket pools / connection pools. HTTP 1.1 allows multiple requests to go through the same TCP connection.

I think Chrome is aware that the network status changed, but if it sees that the existing connection over a physical interface still works, it might decide not to re-connect, even though the Chrome DNS cache knows that the IP address has changed.

**Comment by ReactorScram** [comment]
Jamil and I agreed to put this on pause.

It seems like the issue is just this: If some process has an existing connection to a server, over TCP or QUIC, and the tunnel comes up, that connection may keep running and not get reset.

In my testing I spammed reloads to ifconfig.net from Firefox and Chrome, which can re-use TCP or QUIC connections to an HTTP/1.1, HTTP/2, or HTTP/3 web server. (ifconfig uses Cloudflare so the browsers ended up using h2 and h3)

Even if I try to do it slow and cheat by watching the logs to see when the tunnel is fully up, sometimes the browsers don't quite notice. They need 30-90 ish seconds for their old connections to time out before they'll redo DNS, which will hit our DNS server, and then they'll reconnect using the CGNAT IP.

We figured if a resource is insecure outside the tunnel, it's a problem with the resource. If you load a resource and it says "hey you're not inside the secure tunnel", then raise the tunnel and it still gives that error, it's inconvenient, but not insecure, so that's okay until we have time to really figure this out.

I kept thinking there must be a way to solve it, because Chromium _definitely_ watches for IP address changes. I guess it just sees us as like plugging in another USB Ethernet adapter, not as something that should change the fundamental network behavior of the whole system.

So when we come back to this, I can try using the official Windows VPN APIs like this https://microsoft.github.io/windows-docs-rs/doc/windows/Networking/Vpn/struct.VpnChannel.html to send a stronger hint of "Hey restart all your connections, we're tunneling now". These classes require UWP, which requires MSIX, so it's a whole song and dance to make An Official Windows Vpn App, but it might pay off.

**Comment by jamilbk** [comment]
I came across a related problem when running a longterm background `ping ifconfig.net`. I think this issue is inherent to DNS and ttl. Even if applications respect the ttl, most records will have a long ttl (1 - 24 hours) if Firezone is not up, which the application is perfectly valid to cache.

I think the problem might be related to how DNS and connectionless protocols like ICMP and UDP interact:

- Firezone comes up
- Nothing changes network-wise to cause a TCP reset or otherwise indicate to the upstream application to re-query DNS (the ttl likely hasn't expired yet)
- packets keep flowing as before

The upstream application will need some trigger to re-query DNS for existing "connections". With browsers a simple page refresh is likely not enough. Quitting and re-opening the upstream application and deleting any on-disk DNS cache should kill any persisted state the connectionless protocol is keeping around (`ping` keeps none, but browsers probably do).

I'll go ahead and close this. Good debugging notes for when we inevitably hit this edge case in the future.

Refs #3010

**Comment by jamilbk** [comment]
Note that the Tailscale trick probably helps to clear Windows' internal DNS cache used by internal system services and other apps probably, so it's a trick we may still want to employ.
