### ISSUE TITLE
fix(windows): add_route is slow

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3114]
Shelling out to ~~netsh~~ Powershell's New-NetRoute is slow.

**Comment by ReactorScram** [comment]
This API function will probably do the trick. Just need to test it manually once. https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/NetworkManagement/IpHelper/fn.CreateIpForwardEntry2.html

**Comment by ReactorScram** [comment]
Powershell takes about 800-900 ms, shouldn't be hard to beat 
![image](https://github.com/firezone/firezone/assets/13400041/97c99657-7c8e-4ac5-bc21-8411538bf8ef)

**Comment by ReactorScram** [comment]
13,000 ms to about 200 ms. It wasn't critical but I need to bring the tunnel up and down a lot for DNS testing so that 13 seconds really adds up. 
![image](https://github.com/firezone/firezone/assets/13400041/6016baef-eb75-422e-86d7-903d05313519)

**Comment by jamilbk** [comment]
> 13,000 ms to about 200 ms

Awesome work! Seconded re: IPv6. Even though it's not working currently it's probably good to make sure the linked PR doesn't further prevent it from doing so.

What does `route print` show?

**Comment by ReactorScram** [comment]
@jamilbk The IPv6 bug was simple so I have a fix in PR #3120 
Wintun just wasn't setting the tunnel's IPv6 address correctly, it had the wrong syntax for `netsh`
