### ISSUE TITLE
Decide if deleting a site should delete it's resources

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#3117]
We hit an edge case with Sites: deleting a site leaves a resource that will be offline forever, however, if we delete it we will make it not possible to have multi-site resources.

**Comment by jamilbk** [comment]
Ah, this was me and I hit this today on one of the demo calls. I was wondering why the resource was showing up twice in the client.

Would it be easy to add a `on_delete` constraint for now, and then remove this constraint later on when we can better support multi-site resources?

**Comment by AndrewDryga** [comment]
We don't delete anything so constrains do not help, but deleting them is a few lines of code anyway. 

We do support multi-site resources already. I just feel like at this point, knowing customers requested to have them, "Sites" doesn't look like the best idea and just makes everything more complex
