### ISSUE TITLE
windows: GUI should change to signed-out state when the token expires and tunnel closes

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3128]
**Describe the bug**
When the auth token expires, the system tray menu still shows as signed-in.

**To Reproduce**
Run the client and stay signed-in until the token expires.

**Expected behavior**
The system tray menu should change to signed-out mode

**Screenshots / Logs**
N/A

**Platform (please complete the following information):**
 - Firezone Version 375252f8fc (equivalent to 8dab84ef205 after rebasing)
 - OS: Windows 11

**Additional context**
N/A

**Comment by ReactorScram** [comment]
We're getting a callback from connlib already, I just need to handle it: `firezone_windows_client::client::gui: on_disconnect Some(TokenExpired)`

**Comment by jamilbk** [comment]
Good catch
