### ISSUE TITLE
windows: MSI un-installer doesn't work

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3140]
**Describe the bug**
When you run the "Un-install Firezone Windows Client", it leaves files behind in "Program Files/Firezone Windows Client"

On my Windows server VM it leaves wintun.dll. This is understandable since the MSI doesn't know about it.
On my dev laptop it also left the 19 MB main exe.

**To Reproduce**
1. Install the MSI
2. Try to un-install it

**Expected behavior**
Expected "Program Files/Firezone Windows Client" to be removed, or at least emptied.

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/13400041/607b66f6-b718-4a59-b8b4-733ca1fbc662)

**Platform (please complete the following information):**
 - Firezone Version (idk, circa Jan 8th)
 - OS: Windows 11 and Windows Server 2022
 - Deployment method: MSI

**Additional context**
N/A

**Comment by ReactorScram** [comment]
Should un-installing wipe the device ID, or installing generate it? It was discussed today and I wasn't clear if having the device ID outlive an installation is okay or if we don't want that.

**Comment by ReactorScram** [comment]
We could change where wintun.dll is extracted, as long as it doesn't mess up the permissions. It feels like editing it should require elevated permissions.

**Comment by jamilbk** [comment]
> Should un-installing wipe the device ID, or installing generate it? It was discussed today and I wasn't clear if having the device ID outlive an installation is okay or if we don't want that.

We should try to keep it around as much as possible as it will help dedup logs and other metadata in the portal.

**Comment by ReactorScram** [comment]
Because of #3425 I'll keep this open a little later. If it turns out wintun.dll is going in the wrong dir or accidentally being reused from Tailscale or something weird, that can affect the un-installer behavior

**Comment by ReactorScram** [comment]
I think the un-installer behaves as expected if you don't have a terminal or explorer window parked in Program Files/Firezone. It just removes that folder and the shortcut and tells Windows it's un-installed.

wintun.dll is moving over to %LOCALAPPDATA%.

The registry entries like the deep link scheme, and tunnel interface config, and the %LOCALAPPDATA% files like wintun.dll, advanced settings, logs, and crash dump, are left behind, the MSI isn't aware of those. It might be possible to patch it to remove those, too, somehow.

The device ID is intentionally left in C:/ProgramData to persist across re-installs. None of these are very large files, and everything is namespaced by 'dev.firezone.client', so it's easy for a generic cleanup tool to get them if really needed.
