### ISSUE TITLE
windows: log Git commit hash on GUI startup

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3141]
**Is your feature request related to a problem? Please describe.**
It will be a little quicker to debug logs if I don't have to look up version tags and wonder if they're accurate when going from logs to source code.

**Describe the solution you'd like**
I think I've used this crate in PTTH or some work project before - https://crates.io/crates/git-version
For CI builds it'll put the commit number. If you have changes in the working dir on a dev system it'll put the last commit number and "-dirty" so you know what commit the changes were based off of.

@jamilbk Is that okay?

I want to log that as `info` so it's always in the logs from startup.

**Describe alternatives you've considered**
We could log the package version but it's just one step and one more thing that can go wrong when asking "what code exactly was running when this log was generated?"

**Additional context**
N/A

**Comment by jamilbk** [comment]
Don't have a problem with it per se, but how does it embed the commit id into the code? Isn't that a chicken and egg situation?

**Comment by ReactorScram** [comment]
Nope it embeds it at build time, so the binary has it but the source code does not

**Comment by jamilbk** [comment]
Ah, sounds good

**Comment by ReactorScram** [comment]
This got merged
