### ISSUE TITLE
Filter webrtc candidates that are resources

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#3150]
We used to do that but at some point we removed that filter.

We should start doing that, otherwise it might cause some weird routing loops where tunnel over tunnels are formed.

**Comment by conectado** [comment]
Figuring out when and if this is needed:

There's a non-triviality here, since a resource, in theory though not implemented yet, could be added after connections are established and candidates are filtered 

There are 2 cases where a candidate can be also a resource:
1. The gateway has a local interface with an ip that's part of a resource.
2. The client has a local interface with an ip that's part of a resource.

## For case #1

If the IP is reachable by the client, there's a possibility(depending on how the routes exists in the client) that a channel is established through the resource's IP. If this happens packets can be routed either directly or through the tunnel, if a packet is routed through the tunnel, it'll enter a routing loop except if prevented(which is for the macos client or windows client), when we support in-flight adding of resources, this will happen even if we filter candidates since they are only filtered before connecting.

If it's not reachable, everything works as normal, connection is not established using the candidate and then packets will be unwrapped and injected into the device and then  it will reach the IP. Except when we implement ICE restart, then we will have the weirdness tunnel over tunnel, so for this case, **filtering the candidates is needed**, and it will work since this will only happen when we establish new connections.

> **filtering the candidates is needed**, and it will work since this will only happen when we establish new connections.

An added note on this, there might be a race condition, when we do an ICE restart, while it's happening we add the resource after the candidates are filtered but before trying to establish the connection.

## For case #2

If the IP is not reachable from the gateway it's not really a valid resource configuration so I'll not dwelve on that case.

If the IP is reachable it might be a problem:
1. Let's say a link is established using that candidate
2. Now a packets comes from the client to the resource
3. That packet will (might) be routed to the tunnel, and come back from the gateway
4. The packet will be read from the socket and written to the interface
5. Now the route through the tunnel might be prioritized creating a longer loop, that we can't avoid with fwmark

Though this is unlikely(probably the local route will be prioritized), we need to consider this later on because even if we filter candidates this might happen if we add the resource later on after the connection is established. 

## Conclusion

This might not be the best way to prevent the possible bugs laid out here but it certainly reduces the possibility and it's almost trivial to implement.

Maybe after #2966 is implemented there might be better ways to detect that we never establish tunnels-over-tunnels and we also need to consider implementing something such as fwmark (or leveraging network namespaces), though both solutions will be platform dependent.

We will need to keep this issue in mind moving forward as I believe these routing loops are not so trivial to prevent as they might first appear to be.

**Comment by jamilbk** [comment]
@conectado Good write up, thanks.

Let's consider the following (probably more common than we think) edge case:

- client has ip 10.0.0.1 in subnet 10.0.0.0/24
- gateway has ip 10.0.1.1 in subnet 10.0.1.0/24
- resource is the gateway's IP, 10.0.1.1
- both 10.0.0.0/24 and 10.0.1.0/24 are one hop away (share a common router)

You're saying there could be a routing loop because we have two routes with the same destination:

- candidate for direct (hairpinned) connection to gateway at 10.0.1.1
- tunnel's `addResource` IP of 10.0.1.1 to route packets into the tunnel

In this case, if a routing loop does happen, we should still be able to connect through the nearest Relay right? So as long as the loop causes the connection to fail consistently, the channel will be established using the nearest Relay.

**Comment by jamilbk** [comment]
I think we can close this one based on the conclusions from #3167
