### ISSUE TITLE
feat(windows): logging improvements

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3164]
**Is your feature request related to a problem? Please describe.**
Logs could be better

**Describe the solution you'd like**
- Use tracing's structured log features more, e.g. device IDs and routes could be structured
- Log clean shutdowns so any log not ending in a clean shutdown will be known to be a crash (#3290 fixed this, it's not read back by the program, but we do print a log line before graceful shutdowns)

**Describe alternatives you've considered**
N/A

**Additional context**
I just learned this week that tracing supported structured logging.

**Comment by jamilbk** [comment]
Add one more to the list:

- implement the "Clear Logs" function

```
←[2m2024-01-14T15:11:19.676296Z←[0m ←[34mDEBUG←[0m ←[2mfirezone_windows_client::client::gui←[0m←[2m:←[0m started log counting
←[2m2024-01-14T15:11:22.004103Z←[0m ←[31mERROR←[0m ←[2mtracing_panic←[0m←[2m:←[0m A panic occurred ←[3mpanic.payload←[0m←[2m=←[0m"not yet implemented" ←[3mpanic.location←[0m←[2m=←[0m"windows-client\\src-tauri\\src\\client\\logging.rs:71:5"
←[2m2024-01-14T15:11:27.832726Z←[0m ←[34mDEBUG←[0m ←[2mfirezone_windows_client::client::gui←[0m←[2m:←[0m cancelled log counting
←[2m2024-01-14T15:11:29.220279Z←[0m ←[34mDEBUG←[0m ←[2mfirezone_windows_client::client::gui←[0m←[2m:←[0m started log counting
```

**Comment by ReactorScram** [comment]
Closing, I'll just improve logs gradually as I touch them.
