### ISSUE TITLE
Default client allowed_ips property is not updated

### ISSUE THREAD

**Issue by romainDavaze** [CloudFire-LLC/cloudfire#3170]
**Describe the bug**

When updating the **default['firezone']['wireguard']['allowed_ips']** property inside the configuration, the new value is not taken into account.

**To Reproduce**

Change the default value of **default['firezone']['wireguard']['allowed_ips']** from **"0.0.0.0/0, ::/0"** to "10.0.0.0/16" 

Launch the **firezone-ctl reconfigure** command.

Go to the UI and check the Allowed IPs value in the settings

**Expected behavior**

The default Allowed IPs value should be changed and applied to every device configuration

**Platform (please complete the following information):**
 - Firezone Version: **0.7.30**
 - OS: **Linux**
 - Distro: **Debian 11**
 - Kernel version: **5.10.162-1**
 - Deployment method: **Omnibus**

**Additional context**

I found a way to temporarily fix this by connecting to the postgres database and update the settings manually with this query

```bash
UPDATE configurations SET default_client_allowed_ips = '{10.0.0.0/16}';
```

**Comment by jamilbk** [comment]
Hi @romainDavaze, thanks for the report! Unfortunately our Omnibus build was EOL long ago and we have no way to build or test a fix for this.

Have you tried switching to the Docker version? This issue is likely fixed there.
