### ISSUE TITLE
bug(windows): webrtc_mdns::conn: Error receiving from socket connection: Os { code: 10040, kind: Uncategorized, message: "A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." }

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3173]
**Describe the bug**
Not sure yet. Jamil said I may need to set the Maximum Segment Size for the interface in addition to setting MTU. (MTU I believe is working, it shows up as 1280 in Get-NetIPInterface)

**To Reproduce**
Run the tunnel, connect to Github or something, eventually it seems to just show up.
Github also runs kinda slow, both in Git operations and in the web UI. ~~Might be related.~~

**Expected behavior**
~~Expected Github to be faster,~~ expected the log to not be spammed with errors.

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/13400041/6be39836-6ab5-4984-94c1-51ab7af41cec)

**Platform (please complete the following information):**
 - Firezone Version - Probably current tip of main ab04c73e
 - OS: Windows 11
 - System - My dev laptop, not the VM.

**Additional context**
N/A

**Comment by ReactorScram** [comment]
I looked around for leads on setting MSS but I can't find anything. Also the errors don't come up when I'm experiencing Github being slow.

**Comment by jamilbk** [comment]
Will be fixed incidentally by `snownet`
