### ISSUE TITLE
Race condition when app is restarted quickly

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#3174]
If you close the app and start is quickly again you can hit a race condition where the user is blocked from connecting the tunnel:

![image](https://github.com/firezone/firezone/assets/1877644/2165d10a-1809-4585-8a2b-94951e96a7d3)

Reproduced reliably on MacOS 12 (me) and macOS 14 (on Jamil's laptop).

**Comment by jamilbk** [comment]
The above was performed with the TestFlight release build. Another easy way to reproduce this is to launch the app via Xcode, sign in, then click "Run" again to build and re-launch the app.

**Comment by jamilbk** [comment]
@roop I just hit this now. To reproduce:

- Launch app from Xcode, sign in
- Click "Stop" from Xcode
- Notice that Network extension is still running and connected
- Manually disconnect the tunnel from System prefs
- Launch app again -- now it's in a quasi state of signed in but not signed in


<img width="284" alt="Screenshot 2024-02-26 at 9 34 32 PM" src="https://github.com/firezone/firezone/assets/167144/7d8e5e61-1fd0-4dcb-ae6a-1b4541f4236a">
