### ISSUE TITLE
Support of Kubernetes Cluster Strategy

### ISSUE THREAD

**Issue by Intuinewin** [CloudFire-LLC/cloudfire#3209]
**Is your feature request related to a problem? Please describe.**
I'm trying to make the erlang cluster works inside kubernetes and found that libcluster has already a strategy available for kubernetes.

**Describe the solution you'd like**
I would like [`Elixir.Cluster.Strategy.Kubernetes`](https://hexdocs.pm/libcluster/Cluster.Strategy.Kubernetes.html) to be a valid value of `erlang_cluster_adapter`.

**Describe alternatives you've considered**
Others strategy could probably work but this strategy is easier to setup.

**Additional context**
When dumping the cluster configuration, some options' type are charlists(`mode`,`kubernetes_ip_lookup_mode`). It'll probably need a custom dumper.

**Comment by jamilbk** [comment]
Thanks for the report! Is this occurring with 1.0?

**Comment by Intuinewin** [comment]
Yes, this feature request is for 1.0
