### ISSUE TITLE
bug(windows): copying an IP resource copies the "/32" at the end

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3210]
**Describe the bug**
If I click on a resource it copies the /32 as if it's a CIDR, which makes it impractical to paste in a web browser.

**To Reproduce**
Sign in, open the tray menu, click on a resource, try pasting it in a browser

**Expected behavior**
If it's actually a CIDR resource like a /24, this is fine, but for an IPv4 /32 or an IPv6 /128, it should drop that off. Otherwise it'll be interpreted as the path in a URL I think.

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/13400041/aa7a4b6f-02fe-40b9-bf28-206c1824a280)

**Platform (please complete the following information):**
 - Firezone Version - Any recent version
 - OS: Windows 11

**Additional context**
N/A

**Comment by jamilbk** [comment]
@ReactorScram The issue here is with connlib -- it normalizes IPs coming from the portal IIRC. See https://github.com/firezone/firezone/issues/2829
