### ISSUE TITLE
Sort resources by name alphabetically before calling `onUpdateResources`

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3217]
**Describe the bug**
Resources are in random order. If you close the client and restart it, they shuffle again.

**To Reproduce**
Open the client and sign in, close it, open it again.

**Expected behavior**
I expect them to be ordered alphabetically, and maybe grouped by site. I'm not sure what the other clients do.

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/13400041/d168ef9f-bf46-42fa-9c19-d34c4a72b2a4)

![image](https://github.com/firezone/firezone/assets/13400041/d0e2d0ec-df97-45ca-978e-af533e3b38f2)

**Platform (please complete the following information):**
 - Firezone Version 04aeee2e7bf84
 - OS: Windows 11

**Additional context**
N/A

**Comment by jamilbk** [comment]
@ReactorScram Hmmm. It looks like the Apple client orders them by label alphabetically:

<img width="394" alt="Screenshot 2024-01-12 at 2 48 18 PM" src="https://github.com/firezone/firezone/assets/167144/c3efe96c-acba-4189-9f9b-ca15a013ac33">

The Android client shows them in the order sent by the portal, probably the same as the Windows client:

![Screenshot 2024-01-12 2 58 33 PM](https://github.com/firezone/firezone/assets/167144/51fcd388-e283-416d-bc8f-78c097ba129c)



I think probably want to order them in the portal so it's consistent, wdyt @AndrewDryga ?

**Comment by jamilbk** [comment]
Refs #2024

**Comment by jamilbk** [comment]
Edited to perform the sort in connlib instead. The portal should spend its DB and CPU resources doing more important things.

**Comment by jamilbk** [comment]
@ReactorScram I think if we do this in connlib that should fix the Windows case too and incidentally all other clients?

**Comment by ReactorScram** [comment]
@jamilbk Yeah cause I'm pretty sure I just use the Vec in whatever order connlib gives it to me, I don't de-dupe or anything.

I looked real quick and it seems like Rust does the right thing by default which is just sorting by byte values, so the order will always be the same regardless of platform / language settings. This isn't human-friendly but it's perfect for a first version

- https://users.rust-lang.org/t/rust-sort-and-locale/20846/3
- https://users.rust-lang.org/t/unicode-aware-string-sorting/28464

Ran into that problem in C# where the default is to silently do different stuff depending on your locale... or OS...

**Comment by roop** [comment]
@ReactorScram @jamilbk Yes, the Apple tunnel extension orders them alphabetically at present. Agree that it's better done in connlib.
