### ISSUE TITLE
ci(windows): figure out and document how to validate the MSI's sha256sum.txt

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3221]
**Describe the bug**
There's no obvious equivalent to `sha256sum --check` for the Windows MSI.

**To Reproduce**
N/A

**Expected behavior**
Something like this in the docs https://stackoverflow.com/questions/63396620/how-can-i-compare-a-files-sha256-hash-in-powershell-to-a-known-value

I'll need to remove that Select-Object here https://github.com/firezone/firezone/blob/de2d9c1ce9db25e589afa8285fd422b37aa1e1e2/.github/workflows/cd.yml#L275 so that the format is simpler, too.

**Screenshots / Logs**
N/A

**Platform (please complete the following information):**
 - Firezone Version N/A
 - OS: Windows, any

**Additional context**
https://github.com/firezone/firezone/pull/3201#issuecomment-1890059684

**Comment by jamilbk** [comment]
@ReactorScram Yeah, based on my Googling there doesn't seem to be a standard way of verifying these. Based on that, I think the output you've got in that txt is fine.
