### ISSUE TITLE
feat(gateway): Create `/dev/net/tun` if not found to remove the `--device` requirement

### ISSUE THREAD

**Issue by Intuinewin** [CloudFire-LLC/cloudfire#3226]
I was trying to launch a firezone gateway(1.0.0) in Kubernetes when I got this error.

```
2024-01-14T18:40:09.242251Z INFO init{user_agent="Alpine Linux/3.19.0 (x86_64;5.15.0-91-generic;) connlib/1.0.0" login_topic="gateway"}: phoenix_channel: Received init message from portal
2024-01-14T18:40:09.242340Z DEBUG firezone_gateway: connected to portal
Error: Failed to set interface
Caused by:
No such file or directory (os error 2)
Stack backtrace:
...
```

I've found 2 solutions to this error:
- Running the container as privileged (there is no `--device` equivalent in k8s)
- Creating the device `/dev/net/tun` on startup (This is what is done in projects like gluetun: https://github.com/qdm12/gluetun/blob/master/cmd/gluetun/main.go#L334, https://github.com/qdm12/gluetun/blob/master/internal/tun/check.go#L18, https://github.com/qdm12/gluetun/blob/master/internal/tun/create.go#L14)

The second solution seems better to me, as I don't want the gateway container to run as privileged. 
Here is a very basic patch to create the device. It works on my cluster but obv it needs to be improved (that's why it's not a PR, I'm bad at rust). With this patch the flag `--device` is no longer needed when launching the gateway with docker.

```diff
diff --git a/rust/connlib/tunnel/src/device_channel/tun_linux.rs b/rust/connlib/tunnel/src/device_channel/tun_linux.rs
index 9f5eddb5a..46d484bd4 100644
--- a/rust/connlib/tunnel/src/device_channel/tun_linux.rs
+++ b/rust/connlib/tunnel/src/device_channel/tun_linux.rs
@@ -5,16 +5,15 @@ use futures_util::future::BoxFuture;
 use futures_util::FutureExt;
 use ip_network::IpNetwork;
 use libc::{
-    close, fcntl, open, F_GETFL, F_SETFL, IFF_MULTI_QUEUE, IFF_NO_PI, IFF_TUN, O_NONBLOCK, O_RDWR,
+    close, makedev, mknod, fcntl, open, F_GETFL, F_SETFL, IFF_MULTI_QUEUE, IFF_NO_PI, IFF_TUN, O_NONBLOCK, O_RDWR, S_IFCHR,
 };
 use netlink_packet_route::RT_SCOPE_UNIVERSE;
 use parking_lot::Mutex;
 use rtnetlink::{new_connection, Error::NetlinkError, Handle};
 use std::task::{Context, Poll};
-use std::{
-    fmt, io,
-    os::fd::{AsRawFd, RawFd},
-};
+use std::{fmt, fs, io, os::fd::{AsRawFd, RawFd}};
+use std::os::unix::fs::PermissionsExt;
+use std::path::Path;
 use tokio::io::unix::AsyncFd;
 
 mod utils;
@@ -81,6 +80,27 @@ impl Tun {
     }
 
     pub fn new(config: &InterfaceConfig, _: &impl Callbacks) -> Result<Self> {
+        let s = match std::str::from_utf8(TUN_FILE) {
+            Ok(v) => v,
+            Err(e) => panic!("Invalid UTF-8 sequence: {}", e),
+        };
+        let path = Path::new(s);
+        if !path.exists() {
+            let parent_dir = path.parent().unwrap();
+            fs::create_dir_all(parent_dir)?;
+            let permissions = fs::Permissions::from_mode(0o751);
+            fs::set_permissions(parent_dir, permissions)?;
+
+            const MAJOR: u32 = 10;
+            const MINOR: u32 = 200;
+            unsafe {
+                mknod(
+                    TUN_FILE.as_ptr() as _,
+                    S_IFCHR,
+                    makedev(MAJOR, MINOR),
+                )
+            };
+        }
         let fd = match unsafe { open(TUN_FILE.as_ptr() as _, O_RDWR) } {
             -1 => return Err(get_last_error()),
             fd => fd,
@@ -163,7 +183,7 @@ impl Tun {
 
                         Ok(())
                     }
-                    .boxed(),
+                        .boxed(),
                 )
             }
         }

```

**Platform (please complete the following information):**
- Firezone Version 1.0.0-c73dd141709bc2b7c3f66bf6952065691f968286
- OS: Linux
- Distro: Ubuntu 22.04
- Kernel version: 5.15.0
- Deployment method: Kubernetes

**Comment by jamilbk** [comment]
Thanks for the patch! We do plan to support k8s eventually, but it may take some time for us to fully test and support it at the production level. Refs #902 

Until then, it might be nice to reduce a flag needed for our docker deployment method with this patch.

**Comment by jamilbk** [comment]
Updated the title accordingly.

**Comment by Intuinewin** [comment]
> Thanks for the patch! We do plan to support k8s eventually, but it may take some time for us to fully test and support it at the production level. Refs #902

yep, I saw this issue, I will try to write some helm charts soon. I already deployed all the services on my cluster (web, api, relay and gateway) and it works fine with the android client. Sadly I was not able to make the windows client auth works and I'm still waiting for appstore early access :eyes:

But yes with this feature, the flag --device will no longer be mandatory. My patch creates the device from the rust code but I think it could also be done in the [init bash script](https://github.com/firezone/firezone/blob/main/rust/docker-init.sh)

**Comment by jamilbk** [comment]
> Sadly I was not able to make the windows client auth works and I'm still waiting for appstore early access 👀

The windows client isn't quite ready for beta testing _just_ yet, but is expected to be soon (A Few Weeks™).

I'll double-check on your early access request and see if there's anything I can do to push it through.
