### ISSUE TITLE
Update "About" screen to show logo and version

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3229]
#3225 should enable the About screen to show the Firezone logo and version number, similar to the Apple client:

<img width="396" alt="Screenshot 2024-01-15 at 6 39 34 AM" src="https://github.com/firezone/firezone/assets/167144/117487b4-7c7d-4de4-b7d7-6a7e599fe81e">

**Comment by ReactorScram** [comment]
For the part in parentheses, is there a build number from CI I should get, or can I just drop the Git commit ID in there?

**Comment by jamilbk** [comment]
Git commit ID works great.
