### ISSUE TITLE
Implement `ZeroizeOnDrop` trait

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3232]
https://firezonehq.slack.com/archives/C05KAA18L1Z/p1705293435280239

**Comment by jamilbk** [comment]
Refs #3259

**Comment by thomaseizinger** [comment]
I think this might actually be solved because we are using the `secrecy` crate and not `Zeroize` directly.

**Comment by jamilbk** [comment]
https://github.com/RustCrypto/utils/pull/699

**Comment by jamilbk** [comment]
Whoops, yeah that might be the case: https://docs.rs/secrecy/latest/secrecy/trait.Zeroize.html
