### ISSUE TITLE
Relay doesn't consider DNS names as a valid OTLP_GRPC_ENDPOINT

### ISSUE THREAD

**Issue by Intuinewin** [CloudFire-LLC/cloudfire#3251]
**Describe the bug**
I'm trying to make the relay generates traces but the endpoint must be an IP address.

**Expected behavior**
The relay should consider a DNS name as a valid input for this argument.

**Screenshots / Logs**
```
error: invalid value 'firezone-collector.firezone.svc.k8s.intuinewin.local:4317' for '--otlp-grpc-endpoint <OTLP_GRPC_ENDPOINT>': invalid socket address syntax
For more information, try '--help'.
```

**Platform (please complete the following information):**
 - Firezone Version 1.0.0-b6f72a5fa8cbfe5afff8ec0589c55f13255a95e3
 - OS: Linux
 - Distro: Ubuntu 22.04
 - Kernel version: 5.15.0
 - Deployment method: Kubernetes

**Comment by thomaseizinger** [comment]
Does it work if you just resolve it via `dig` before passing to the relay?

**Comment by Intuinewin** [comment]
Yep it works. IMHO the type of the argument(`SocketAddr`) is not good.
You can try with your staging env to put localhost instead of 127.0.0.1 I think it will crash

**Comment by thomaseizinger** [comment]
> Yep it works. IMHO the type of the argument(`SocketAddr`) is not good. You can try with your staging env to put localhost instead of 127.0.0.1 I think it will crash

That is what the underlying telemetry library accepts I think. Would have to double check. If `dig` works then I'll say "good enough for now" :)

Minor correction: It doesn't crash. It is a graceful exit because the arguments cannot be parsed.

**Comment by Intuinewin** [comment]
Indeed it doesn't crash it's a parsing issue. Couldn't you just change the type of the argument to string? The ip of my collector is not static :'(

https://github.com/firezone/firezone/blob/85304329b9f31efb7d832666e8a146b30d29aa1d/rust/relay/src/main.rs#L159
https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/struct.TonicExporterBuilder.html#method.with_endpoint

**Comment by thomaseizinger** [comment]
> Couldn't you just change the type of the argument to string?

PRs welcome!
