### ISSUE TITLE
 Expire LiveView sockets when subject is expired

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#3258]
There is no good way to disconnect a LiveView socket when the auth subject it's using is expired, we will have to build some tracker process that will monitor LiveView processes and kill them on timeout. This also means we will have some `handle_info` in all LiveView modules.

**Comment by jamilbk** [comment]
One small UX request, instead of disconnecting the socket, can you `put_flash("Your session expired")` or maybe `JS.alert("Your session expired. Click Ok to return to the sign in page")` first

**Comment by jamilbk** [comment]
refs #2890

**Comment by AndrewDryga** [comment]
We can't push any alerts since the socket is just closed. Maybe it's better if the client renders this error when 4XX is returned on reconnect?

**Comment by jamilbk** [comment]
Ah I see, maybe the fix here is just to show a flash message "You must be signed in to do that" so that when the socket disconnects and the browser reloads the page they'll see that?

(Taking them to sign in)

**Comment by AndrewDryga** [comment]
Closing this as we already expire subject tokens and broadcast it to the clients, there is no easy way to change the behavior when that happens (without ugly hacks) - the user will be just redirected to sign in with a message "You must sign in to access this page.".
