### ISSUE TITLE
Limit Trafic user

### ISSUE THREAD

**Issue by AnonymousWebHacker** [CloudFire-LLC/cloudfire#326]
can control the total traffic of the connecting user. ? In my case I do not want to exceed the traffic of my vps

**Comment by jamilbk** [comment]
We don't currently support bandwidth quotas, but that would be a useful feature to implement. WireGuard already reports traffic statistics for us, so it would just be a matter of monitoring that and cutting traffic when the threshold is hit.

I'll add this to our backlog. Thanks for the question!

**Comment by AnonymousWebHacker** [comment]
I look forward to the next release :)

**Comment by AnonymousWebHacker** [comment]
@jamilbk vnstat could be used against the wireguard interface, in such a way to control total traffic of the interface, sending notifications via email, etc.

**Comment by WaxySteelWorm** [comment]
> would be a useful feature to implement. WireGuard already reports traffic statistics for us, so it would just be a matter of monitoring that and cutting traffic when the th

Would it be possible to display the traffic information on the dashboard?

**Comment by jamilbk** [comment]
@WaxySteelWorm Yep! This is present in the WireGuard output so it's a matter of pulling it out and sending it up to the UI.

I've opened to #450 to track this.

**Comment by jamilbk** [comment]
Upon deeper investigation, we probably won't get to this any time soon. Could probably revisit after the new architecture.
