### ISSUE TITLE
Gracefully handle network switching

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3302]
In the Apple and Windows clients, we use the platform-provided network change detectors to call `Session.disconnect` when "internet connectivity drops" and then `Session.connect` when it's back online.

We can use [`ConnectivityManager`](https://developer.android.com/reference/android/net/ConnectivityManager) to do the same on Android.

See here for more reference:

- Apple has a [`PathDidUpdate`](https://developer.apple.com/documentation/network/nwpathmonitor/2998735-pathupdatehandler) callback [that we subscribe to](https://github.com/firezone/firezone/blob/main/swift/apple/FirezoneNetworkExtension/Adapter.swift#L316) to receive network change events and react accordingly
- Windows provides a mechanism for this as well. See [this Slack thread](https://firezonehq.slack.com/archives/C067DSY7TFX/p1705451053915679) for an in-depth discussion.

**Comment by jamilbk** [comment]
Just tested this with connlib's built-in connection retrying, and it works as long as there's a fallback internet connection. If there's no fallback internet connection, connlib will eventually sign the user out, which is probably not what we want -- we want connlib to retry for a very long time, otherwise this will cause problems for headless clients.

In the Android simulator:
- I was connected to WiFi and cellular
- I disconnected WiFi
- Connlib lost connection to portal  and reconnected after a few seconds, like 2 (!!)
- Connectivity resumed

**Comment by ReactorScram** [comment]
(Windows doesn't call Session.disconnect yet but I'm very close and #3000 is tracking it)
