### ISSUE TITLE
Closing sign in tab in windows leaves Firezone in Signing In state

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#3316]
Not sure if this is already tracked already, feel free to close if it's but after closing the sign in tab, Firezone is still in Signing in state and I can't try again.

**Comment by ReactorScram** [comment]
Yeah there's no feedback from the browser to the client that I'm aware of, since I didn't end up using the secured webview like Apple / Android used to.

Maybe the tray menu needs a "Cancel" or "Sign in again" button? :thinking:

**Comment by ReactorScram** [comment]
I'll do a "Cancel sign-in" button and then we can bikeshed it if we want
