### ISSUE TITLE
UI notification for reauth

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3329]
When a client calls `on_disconnect` due to a `401` error, the client should display a UI popup notification on desktops or push notification on mobile with a button to open the sign in flow again.

This prevents the usability issue of being silently signed out with no alert or warning.

This functionality will also be used down the line when we require users to re-auth for certain policies that have shorter session lifetimes to more sensitive resources.

**Comment by jamilbk** [comment]
See Windows for an example message: https://github.com/firezone/firezone/pull/3416/files#diff-8ee58783aeb973dcbf764b93d3038dd0133d981cc0caae8c5429020eb002a52eR581

**Comment by roop** [comment]
@jamilbk:

Should we look for the string "401" in the error string passed to `on_disconnect()`?

 For the Apple clients:
  - For macOS:
     - The main app will monitor the tunnel and can show an alert when it detects the "401".  The macOS app shall always do this (no settings).
     - `displayMessage` (Edit: the deprecated API to show an alert from the tunnel) works in macOS, but we won't use that.
  - For iOS:
     - I tried `UNUserNotificationCenter`-based local notifications from the tunnel and it works, so we can use that.
         - It requires the user to authorise it (can ask for authorisation either from the tunnel or the app; authorising from the app works for the tunnel as well).
         - Notification is not shown if the app is the currently-in-foreground app (which is fine, I think).
         - The default is banner style, which auto-disappears after a few seconds. User can change that in OS Settings.
     - Edit: `displayMessage` doesn't work in iOS anymore
     - So, the plan is to add a settings tab called _Notifications_ only for iOS, with a switch marked "Notify when token is expired or invalid". When the user enables the switch, we'll ask the OS to prompt for notification permissions.

Does this sound good? Or do you think we need to have a user-configurable setting for macOS as well for consistency?

**Comment by jamilbk** [comment]
@roop Thanks for doing that research. That sounds great.

Re: Detecting the 401: I don't think it's worth adding. We can use a generic message in the UI notification ("Your session has ended. Please sign in again to reconnect."). If it happens repeatedly for a user, they'll tell us and we'll peek at the logs.

We'll be refactoring the FFI anyway in #3343 and in that work we'll probably send over better types as well, or at least have a schema defined for errors so that we don't have to hack it.

**Comment by jamilbk** [comment]
Closed in #3684

**Comment by jamilbk** [comment]
@jasonboukheir Re-opening this one to revisit on Android. I think we'll need it after all, because we plan to use the functionality for future features.

I'll re-open the associated PR you had open.

I'll push out a Test Flight build to iOS you can test to see how it functions.

**Comment by jamilbk** [comment]
The thing to test here would be

- app is in background
- initiate a disconnect from the portal (revoke token under Actors)
- move app to foreground
- are we at the sign in screen

**Comment by jamilbk** [comment]
Acceptance criteria:

- Sign in
- Go to portal, Revoke token (from Actors page)
- [ ] View should move to Sign in screen if activity is loaded
- [ ] If app is in background, ensure Connlib is disconnected (stopped?) and user is notified somehow to reauth
