### ISSUE TITLE
Support some further configuration

### ISSUE THREAD

**Issue by DerSeb90** [CloudFire-LLC/cloudfire#333]
Hello,
i'm using wireguard primary for accessing my cloud server private networks. Yes i know it can be changed with the edit function but changing every time is non usable for me. So following configuration options would be good:
1. Disable/Change DNS: When disabled the DNS setting is completely deleted from server&client configs.
2. Change AllowedIPs: Because of just accessing private networks it would be good to set this variable also manually. 
3. Option to disable IPv6.
4. Download button for download the client config file.

**Comment by jamilbk** [comment]
Hi @DerSeb90 

Thanks for the feedback! 1) and 2) are being worked on right now. 4) is in our backlog and will (hopefully) make its way into the next major release.

For 3) -- could you elaborate a little more on the use case for this? Can you get around this for now by simply removing the the IPv6 parts from the generated WireGuard config?

**Comment by DerSeb90** [comment]
For 3)
In my case i use only IPv4 in my private networks. And on some Clients is IPv6 disabled. I'm not sure if this configs causes any problems on the clients. But i can live with this configs.

Please remember that if DNS is disabled the DNS Variable ist just complete deleted in the client configs and not just empty.

And maybe just one more enhancement:
A function to disable nftables feature. In my case i host this interface just internal and do firewall and routing on my own.

**Comment by jamilbk** [comment]
Gotcha! I'll have to think a little more about how to tackle disabling IPv6. The simplest would be to just omit the IPv6 addresses from the generated device configs, but there are some edge cases to think through here. (e.g. what if someone has IPv6 enabled, creates some devices, then disables it? Does it disconnect all connected devices?).

For disabling nftables, your best option is to just leave the rules empty. We set up NAT/masquerading through nftables so we can't remove reliance on it completely, but if you don't add any rules then it won't affect any other traffic.

You can view the rules that Firezone creates with `/opt/firezone/embedded/sbin/nft list ruleset`.

**Comment by DerSeb90** [comment]
Thanks for the answer. Now i see the Problem with v6. Maybe an install variable.
Firewall is ok if there are no rules then no blocking.

**Comment by jamilbk** [comment]
Created an issue to track IPv4 / IPv6 enable/disable here: #340

**Comment by jamilbk** [comment]
@DerSeb90 This has been merged into the master branch and will make it into the next release (0.2.0) which is scheduled for next week.

Closing issue.
