### ISSUE TITLE
"Portal offline error" -> can also occurred when a policy is disabled

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3332]

**Comment by AndrewDryga** [comment]
@jamilbk not sure what is the exact issue described here, `offline` can be only returned when there is no online gateway or relay to access the resource, if policy is `disabled` or `deleted` client can't even know about resource existence and the error will be `not_found`.

**Comment by jamilbk** [comment]
May have hit a false positive (user error) or perhaps the policy was disabled/deleted while I was trying to access its resource
