### ISSUE TITLE
How to deploy on Kubernetes?

### ISSUE THREAD

**Issue by clayrisser** [CloudFire-LLC/cloudfire#335]
How can I deploy this on Kubernetes?

**Comment by jamilbk** [comment]
We don't currently support containerized deployments. Some work needs to be done to determine how big of a task it would be to do this.

See this issue for more details:

https://github.com/firezone/firezone/issues/260

**Comment by jamilbk** [comment]
@clayrisser Going to close this issue in favor of #260.
