### ISSUE TITLE
Don't redeploy binaries that haven't changed

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3350]
Deploying a new release should keep elixir and relay images from redeploying if their checksum did not change so that websockets are not needlessly closed.

**Comment by jamilbk** [comment]
After chatting with @thomaseizinger. This is not really feasible in Rust: binaries' checksums aren't necessarily deterministic

**Comment by thomaseizinger** [comment]
> After chatting with @thomaseizinger. This is not really feasible in Rust: binaries' checksums aren't necessarily deterministic

FTR: It is possible but already quite hard if we use the same Git commit. Building an exactly identical binary across _different_ commits of a monorepo is probably even harder.

I don't think it is worth the effort at this point. Maybe once we do things like f-droid for Android we can look more into entirely deterministic builds. It would be nice from a security PoV.
