### ISSUE TITLE
SSO Support

### ISSUE THREAD

**Issue by yarons** [CloudFire-LLC/cloudfire#336]
Adding SAML, OAuth2, etc. support could increase overall security and will save the need to self store and protect user data.

**Comment by jamilbk** [comment]
Hi @yarons,

Thanks for the feature request! We're working on it. See #259 for more info.

**Comment by yarons** [comment]
@jamilbk You're awesome, thank you, good luck!

**Comment by jamilbk** [comment]
Thanks @yarons. Closing this issue in favor of tracking this work on that one.
