### ISSUE TITLE
Support Android headless operation

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3371]
Needed for an IoT deployment.

- [x] Support [managed configurations](https://developer.android.com/work/managed-configurations#define-configuration)
- [x] #2308

**Comment by jasonboukheir** [comment]
## Notes for implementing

- There are 3 Settings
  1. `authBaseUrl`
  2. `apiUrl`
  3. `logFilter`
- Use `PreferenceRepository` to save the 3 settings.
- ~~When the `MainActivity` starts, check for these settings in `RestrictionsManager`, and save the preferences in the `PreferenceRepository`. (Maybe have a preference Activity?)~~
- ~~When the `MainActivity` (starts/is created), register the `BroadcastReceiver` to the `ACTION_APPLICATION_RESTRICTIONS_CHANGED` event. Unregister when it (stops/is destroyed).~~
- When the `SettingsActivity` (starts/is created), check for the settings in the `RestrictionsManager` and update enabled states of the UI based on set restrictions.
- Add similar receiver and register/unregister it for the enabled state of the relevant settings fields in `SettingsActivity`.


~~There are two activities that are using these restrictions -- one uses it to determine the enabled state of UI fields, the other uses them to set the preferences.~~

I need to rethink this. This will require some background receiving, and dependency injection around that. I think it should be in a modular form too, and not bolted onto the `MainActivity`.

**Comment by jamilbk** [comment]
@jasonboukheir The settings shouldn't need to be adjusted for headless mode operation, but there won't be a user present to complete the auth flow, so we need some mechanism to load a stored auth token from a file (or the managed configuration linked in the description).

**Comment by jasonboukheir** [comment]
Just tested it in main, and it appears to work with the Always-On VPN.

## Case 1:

When setting firezone token managed configuration and then set it as the always on vpn, the vpn starts up and connects.

## Case 2:

After setting firezone as always on vpn, then restarting the phone, the firezone vpn connects successfully

**Comment by jasonboukheir** [comment]
New issues:
- [ ] #3550
- [ ] #3549
