### ISSUE TITLE
Sign in page UX

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3390]
At the moment, the sign-in page uses the accent colour (blue/purple) for the "Request Sign-In Token":

![image](https://github.com/firezone/firezone/assets/5486389/dc707e3c-fa19-4a69-a8c6-a0aef13c4cf6)

Visually, this makes it seem like this is the most important action and the button the user should be clicking. However, as far as I understand, we really want them to click "Sign in with Google Workspace" and requesting a token is just the fallback.

Even though signing in with google workspace comes "first", it doesn't capture the users intention. It would be better if the use of space and colours would suggest signing in with google rather than requesting a token.

**Comment by thomaseizinger** [comment]
cc @jamilbk Feel free to re-word. That is the idea I suggested earlier!

**Comment by jamilbk** [comment]
The easy fix here might be to just swap the button colors

**Comment by thomaseizinger** [comment]
Here is what zoom does for example:

![image](https://github.com/firezone/firezone/assets/5486389/8dbaf0ef-df90-4b44-a501-99b56c532188)

There is one "call to action": Launch the meeting. All other options, like joining via web is a regular, tiny link at the bottom.

If it is not too difficult, it could be nice if "Sign in with email" is a separate page that you get to via a link that says "Don't have a Google Workspace account? Sign in with email."

**Comment by jamilbk** [comment]
Since we allow dynamic auth providers what we could do is just

- Simplify the form to just have buttons (moving the "Sign in with email" form to its own page)
- Add an Icon to each provider "Mail icon, Google icon, and OIDC"

This is staging for example:

<img width="553" alt="Screenshot 2024-01-29 at 1 31 47 PM" src="https://github.com/firezone/firezone/assets/167144/642c10e4-58ae-4089-a20c-a3d218ffe199">

**Comment by thomaseizinger** [comment]
> Simplify the form to just have buttons (moving the "Sign in with email" form to its own page)

With multiple buttons I would refrain from using the accent colour (purple) multiple times. That overloads the page too much. Just the above 3 buttons with a text-link to "sign in with email" sounds good to me. That moves the user's focus to clicking those buttons instead of filling out the form.

**Comment by AndrewDryga** [comment]
@jamilbk @bmanifold I think this one is outdated? I believe one of you already fixed this in one of PR's :).

**Comment by bmanifold** [comment]
Yeah, I think @jamilbk had a PR that changed the "Request sign in token" button to remove the accent color

<hr />

Latest staging sign in page:

<img width="614" alt="Screenshot 2024-02-12 at 4 36 56 PM" src="https://github.com/firezone/firezone/assets/2646332/5599d03c-bb23-40dd-a172-cc2efde79348">
