### ISSUE TITLE
connlib: allocate IPv6 address with relay

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3406]
Currently, we only ever allocate an IPv4 address with the relay in `firezone-connection`:

https://github.com/firezone/firezone/blob/f9f95677d5854cc013f9c794fde2af0e683b2c66/rust/connlib/connection/src/allocation.rs#L447-L457

We should also (always?) request an IPv6 address. This would allow us to talk to IPv6-only gateways or clients.

**Comment by jamilbk** [comment]
> We should also (always?) request an IPv6 address.

Always should be a fine assumption if that reduces complexity a bit

**Comment by thomaseizinger** [comment]
Unfortunately, I can't test this with docker because IPv6 networks with compose aren't properly supported. We are essentially waiting for https://github.com/moby/moby/pull/43033 to be merged and release.
