### ISSUE TITLE
Flaky connection integration test

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3424]
Spotted this one and wanted to capture it in an issue so that we have a log for debugging:

https://github.com/firezone/firezone/actions/runs/7699046449/job/20979831123?pr=3422#step:4:17

**Comment by thomaseizinger** [comment]
> Spotted this one and wanted to capture it in an issue so that we have a log for debugging:
> 
> [firezone/firezone/actions/runs/7699046449/job/20979831123?pr=3422#step:4:17](https://github.com/firezone/firezone/actions/runs/7699046449/job/20979831123?pr=3422#step:4:17)

Well, not sure what we can do if the network connection to the docker registry is flaky :(

**Comment by jamilbk** [comment]
Ah didn't catch that
