### ISSUE TITLE
Send network change events to connlib to refresh candidates

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3429]
ICE restart will more quickly establish new channels when network conditions change

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart

**Comment by jamilbk** [comment]
@thomaseizinger Is this still relevant or was this already implemented with the switch to `snownet`?

**Comment by thomaseizinger** [comment]
We may use ICE restart when we implement notifications from the OS to connlib that our network changed. That should be the goal of the ticket I think. Whether or not we do that with an ICE restart or individual invalidation of candidates doesn't matter I'd say.

**Comment by jamilbk** [comment]
Updated title to match
