### ISSUE TITLE
bug(windows): debug symbols aren't produced by CI

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3450]
**Describe the bug**
Without debug symbols the crash dumps will be useless. Generating debug symbols after-the-fact is difficult because deterministic builds are difficult.

**To Reproduce**
N/A

**Expected behavior**
Expected production exes to have a detached symbols file produced by CI/CD somewhere around here <https://github.com/firezone/firezone/blob/f2f8464f027d73963200e99b6ea21a2ebf9ea38f/.github/workflows/_rust.yml#L110-L129> and here <https://github.com/firezone/firezone/blob/f2f8464f027d73963200e99b6ea21a2ebf9ea38f/.github/workflows/cd.yml#L273-L285>

**Screenshots / Logs**
N/A

**Platform (please complete the following information):**
 - Firezone Version f2f8464f0
 - OS: Windows

**Additional context**
I was going to add this when crash handling was added, and I forgot

**Comment by jamilbk** [comment]
Would these be picked up by the MSI or something? We currently point people to the releases page to find our latest clients so it's probably not a good place to stick em to live on their own there

**Comment by ReactorScram** [comment]
No, devs would need these to read crash dumps we get back from production.

I wasn't sure if Github would expire old CI artifacts or anything, but I did manage to find the MSI from a CI run for a month-old release, so it should be okay to only have them in `_rust.yml` and not `cd.yml` as you recommended.

- https://github.com/firezone/firezone/releases/tag/1.0.0-pre.4
- https://github.com/firezone/firezone/actions/runs/7403687439#artifacts
- https://github.com/firezone/firezone/actions/runs/7403600233#artifacts
Took like 5 clicks

**Comment by thomaseizinger** [comment]
FWIW, with sentry, you can upload these files for a particular release (i.e. commit hash) and then it will automatically pull them together when a crash is reported. See https://docs.sentry.io/platforms/native/data-management/debug-files/file-formats/#pe-and-pdb.

I've not verified this for Windows but when I used it with source maps under JS when code was transpiled from TS it worked quite well. I'd assume they do the same thing for Windows too!

**Comment by ReactorScram** [comment]
Probably. Sentry looked really nice but we ended up opting against it because of cost or something in a meeting https://github.com/firezone/firezone/issues/3111#issuecomment-1887710660

**Comment by jamilbk** [comment]
It's more about adding another third-party processor to our log data. [Sentry's got a healthy compliance scorecard though](https://docs.sentry.io/product/security/soc2/)

If GCP ends up not being enough, happy to look into a Sentry contract further.
