### ISSUE TITLE
feat(windows): CI smoke test

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3534]
**Is your feature request related to a problem? Please describe.**
#3531 theoretically could have been caught in CI.

**Describe the solution you'd like**
A `--smoke-test` flag similar to `--crash-on-purpose`. When this flag is true, the client will boot up, start the GUI, perform a few self-checks, wait 10 seconds, then shut down gracefully.

This could catch the following types of issues:
- Crash when loading token / settings on a fresh install
- Hang when exiting gracefully

**Describe alternatives you've considered**
We don't have to do this, but it might catch issues like #3531 faster in the future.

**Additional context**
The existing `--crash-on-purpose` flag is used to exercise the crash handler. It causes a segfault after 10 seconds of uptime.

**Comment by jamilbk** [comment]
This SGTM. We should try to smoke test all clients in CI really.

**Comment by ReactorScram** [comment]
Doing it in release mode in the `build-tauri` step would not be simple. In release mode the exe is a GUI application, so it detaches from its terminal and returns exit code 0 even though the app is still running.

Doing it in debug mode in the `build-tauri` step would probably make the slowest step of CI/CD even slower.

Doing it in the `cargo test` step would require it to be separated from what all other platforms do.

I'll make two PRs:
1. Smoke test subcommand for local dev
2. Run smoke test in its own job in parallel with all the other `_rust.yml` tests.
