### ISSUE TITLE
When using managed configuration with an unauthorized token, the sign in UI constantly retries

### ISSUE THREAD

**Issue by jasonboukheir** [CloudFire-LLC/cloudfire#3549]
**Describe the bug**
When using managed configuration with an unauthorized token, the sign in UI will keep refreshing the webview, attempting to reconnect.

**To Reproduce**
Set a managed configuration for firezone with the key "token" to something that is not an authorized token.

**Expected behavior**
I would expect the app will not cause a UI loop. I realize the app probably should keep trying to reconnect, but maybe it shouldn't show the settings / sign in buttons if the managed configuration is there. Instead it should show the attempted connection with a constant failure message like "token invalid, please contact your admin"

As long as the UI is not constantly jumping between activities.

**Platform (please complete the following information):**
 - Firezone Version: bbab37f1e19bae4d143575ce22c4418c603cf39f
 - OS: Android
 - Deployment method: Source

**Comment by jamilbk** [comment]
Should have been fixed
