### ISSUE TITLE
When token becomes invalid, then reset in managed configuration, Tunnel is not reconnected

### ISSUE THREAD

**Issue by jasonboukheir** [CloudFire-LLC/cloudfire#3550]
**Describe the bug**
When using always on VPN with managed configuration, and the token becomes revoked, the connection drops. However, the connection is not retried when a new token is set in the managed configuration until the app is opened by the user.

**To Reproduce**
1. Set a token and Always On VPN via managed configuration.
2. Revoke the token and observe VPN disconnect
3. Assign a new, authorized token in managed configuration.
4. Observe the VPN not reconnecting.

**Expected behavior**
When the token is updated in managed configuration, the tunnel should try to reconnect and be supported via AlwaysOnVPN.

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version: bbab37f1e19bae4d143575ce22c4418c603cf39f
 - OS: Android
 - Deployment method: Source

**Comment by jamilbk** [comment]
How does the VPN get reconnected in this case? Would stopping the tunnel and starting it again cause it to reload with the new token?

I think that's fine -- I don't think detecting managed configuration changes and reconnecting the tunnel after being disconnected with a `401` is a requirement (or maybe not even desired)
