### ISSUE TITLE
relay: ensure allocations can only be interacted with using the username they were created with

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3588]
The spec recommends checking for the username that created the allocation when it is being interacted with after (e.g. when binding a channel or refreshing it). See https://www.rfc-editor.org/rfc/rfc8656#name-general-behavior.

**Comment by jamilbk** [comment]
related: https://github.com/firezone/firezone/security/advisories/GHSA-qj4g-gwfx-5x2f

**Comment by jamilbk** [comment]
Closing this in favor of tracking there.
