### ISSUE TITLE
Redirect to a static success page after client auth is successful

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3608]
On some platforms (Android), the Firezone client is not able to control the WebView opened to close the tab.

After the user is taken back to the authenticated Firezone app, it's likely they will be returning to their browser in order to access the protected resource they were trying to.

Right now on Android they'll see this:

<img width="400" alt="Screenshot 2024-02-08 at 9 52 44 AM" src="https://github.com/firezone/firezone/assets/167144/60337eb5-1847-4442-a8ed-e3d2784321b7">

The LiveView load indicator is still on-screen, so it looks like it's still trying to load the page.

It would be better to take them to a static "Success! You can now close this browser tab" before we send the final redirect to our custom URI.

**Comment by AndrewDryga** [comment]
To do this we will have first to redirect to some static page and then have it redirect to the deep link.

**Comment by jamilbk** [comment]
@ReactorScram What's the behavior for this on Windows? Does the browser tab get closed automatically or does it appear to hang at the sign in screen like Android?

**Comment by ReactorScram** [comment]
@jamilbk Same on Windows, the tab stays open loading forever

**Comment by ReactorScram** [comment]
![image](https://github.com/firezone/firezone/assets/13400041/3021448f-9e6a-4672-86db-eef075cdaa2e)

This is after the "Firezone connected" notification comes up. The browser doesn't know what to do

**Comment by jamilbk** [comment]
> To do this we will have first to redirect to some static page and then have it redirect to the deep link.

Yeah I was thinking the same. On the static page maybe we don't connect the Liveview (or disable the topbar loading indicator) to prevent the loading appearance.
