### ISSUE TITLE
Per-app VPN for Android

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3613]
Allow only select apps to route packets through Firezone.

Needed by some orgs for security reasons.

- Apple: [Native support](https://developer.apple.com/documentation/networkextension/neapprule)
- Windows: Native support, though maybe not via Wintun?
- [x] Android: [Native support](https://developer.android.com/develop/connectivity/vpn#per-app)
  - [x] Add RestrictionsManager field to read AllowList set by MDM at TunnelService startup
  - [x] Optionally, expose this configuration in the Settings View
  - [x] If configuration is present, allow only specified apps to route packets through Firezone
- Linux: ???

**Comment by roop** [comment]
@jamilbk: On Apple platforms, this is possible only on managed devices (i.e. devices using MDM). Is that acceptable?

**Comment by jamilbk** [comment]
@roop Yep, that's the intended use case. Not a priority yet for Apple platforms just Android for now.
