### ISSUE TITLE
Request - Allow DNS vs. IP in endpoint config

### ISSUE THREAD

**Issue by RamboRogers** [CloudFire-LLC/cloudfire#365]
I'd like to request for the next update to allow for DNS updates to the endpoint.  I set this in my current DSNET WireGuard stuff.  I use dynamic DNS to reach my home lab in case the IP changes.  This application is so awesome.  Thank you!

<img width="1722" alt="Screen Shot 2021-12-27 at 10 20 28 PM" src="https://user-images.githubusercontent.com/7763805/147524511-4a09387a-75f7-4e47-bf94-db2531150af5.png">

**Comment by jamilbk** [comment]
Thanks for the suggestion, makes total sense and should be fairly easy to change. I'll add this to our backlog and queue it for the next release.
