### ISSUE TITLE
`dns_alias` for IP resources

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3661]
As a user, I want to be able to define DNS resources directly in Firezone without having to also configure them somewhere else so that the gateways can resolve them. Managing `/etc/hosts` on each Gateway is too cumbersome.

This could be as simple as a `dns_ipv(4|6)` field that exists for DNS resources (that _don't_ use wildcard matching). If the gateway sees that field, it simply responds with that IP instead of doing a lookup.

Note that #2801 could solve this too -- the user would create an IP resource, then add a DNS alias to it.

**Comment by AndrewDryga** [comment]
> This could be as simple as a dns_ipv(4|6) field that exists for DNS resources (that don't use wildcard matching)

I feel it's better to do it on top of IP resource and simply add `dns_host` as design described in this issue feels reverse from what I would expect as a user.

**Comment by jamilbk** [comment]
Closing in favor of #2801
