### ISSUE TITLE
connlib: re-consider `Session` API for clients

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3683]
With https://github.com/firezone/firezone/pull/3682, the `Session` API is a very thin wrapper around the client `Eventloop`. The only significant thing it does is starting a `tokio` runtime.

For the Windows client, we don't need to do that as that one already has a `tokio` runtime. (cc @ReactorScram)

Even though it will create a little bit of duplication, I am tempted to eliminate the `Session` abstraction for the clients and make it explicit, which clients needs to start up a runtime.

With the move to `snownet`, we are also no longer spawning any tasks inside `connlib`. Thus, I am not sure we need all of the `runtime_stopper` stuff. Plus, a single-threaded runtime is probably good enough now? Will need to do some performance benchmarking.

**Comment by ReactorScram** [comment]
That would be nice, I know OS threads aren't that expensive but since Tokio starts one executor thread per core, I ended up with 30-something threads in the Windows client on my 12-core system. (I guess there's the Tauri runtime, my runtime which sadly Tauri doesn't share, and the connlib runtime)

So it'd be nice to free up 12 OS threads.

**Comment by thomaseizinger** [comment]
@conectado and I discussed this further today. Very likely, we will move the `phoenix-channel` connection to the portal into `Tunnel`. That will pretty much remove the entire public API of `Tunnel` and all you have to do is call `.poll` on it forever, i.e. on Windows you can then do:

```rust
tokio::spawn(std::future::poll_fn(move |cx| tunnel.poll(cx)));
```

**Comment by thomaseizinger** [comment]
After working a bit more on https://github.com/firezone/firezone/pull/3682, here are some thoughts:

- We now have an API `async fn connect` that returns `()`. Internally, this will call `on_disconnect` when something fails.
- All clients that already run a tokio runtime can use this new `connect` function.
- We can refactor the existing `Session` to start a new, single-threaded tokio runtime and spawn the `connect` function onto that one. Because we would only do this for all clients that don't yet have a runtime, we can just store the `Runtime` as a field and drop it normally. No need for runtime stopper.

What I haven't figured out yet is how we best handle panics. Eventually, I'd like to get to a point where the clients are connected to connlib via two channels: one for commands sent to connlib and one for emitted events. If connlib panics, the task would exit and the ends of the channel would be closed. That is how clients could detect panics without us needing to install a separate panic handler.

Instead of listening for callbacks, clients should eventually just (re)-render the UI whenever they get a new event. If the stream of events ends, connlib is dead and the UI state should be reset.

**Comment by conectado** [comment]
Just a note that comes from #3830 

The reason we have a `runtime_stopper` channel is that we can't close the runtime from within the runtime itself. So when there's a fatal error we use it to close the runtime we had.

But now I think we can make the responsibility of whoever created the session to clean it up, part of that closing the runtime.

> We can refactor the existing Session to start a new, single-threaded tokio runtime and spawn the connect function onto that one. Because we would only do this for all clients that don't yet have a runtime, we can just store the Runtime as a field and drop it normally. No need for runtime stopper.

Or rather, adding to this, we just need to make sure that the `Session` is dropped when `on_disconnect` is called.

**Comment by thomaseizinger** [comment]
> The reason we have a `runtime_stopper` channel is that we can't close the runtime from within the runtime itself. So when there's a fatal error we use it to close the runtime we had.
> 
> But now I think we can make the responsibility of whoever created the session to clean it up, part of that closing the runtime.

AFAIK, we no longer call `on_disconnect` within the tasks right? So we should just be able to drop it now, cool! :)

How easy was it to reproduce that? How can I best test that?

**Comment by conectado** [comment]
> > The reason we have a `runtime_stopper` channel is that we can't close the runtime from within the runtime itself. So when there's a fatal error we use it to close the runtime we had.
> > But now I think we can make the responsibility of whoever created the session to clean it up, part of that closing the runtime.
> 
> AFAIK, we no longer call `on_disconnect` within the tasks right? So we should just be able to drop it now, cool! :)
> 
> How easy was it to reproduce that? How can I best test that?

Using an invalid/expired token should reproduce it, the portal should send us an error and we would like to drop the tunnel in response

**Comment by thomaseizinger** [comment]
> > > The reason we have a `runtime_stopper` channel is that we can't close the runtime from within the runtime itself. So when there's a fatal error we use it to close the runtime we had.
> > > But now I think we can make the responsibility of whoever created the session to clean it up, part of that closing the runtime.
> > 
> > 
> > AFAIK, we no longer call `on_disconnect` within the tasks right? So we should just be able to drop it now, cool! :)
> > How easy was it to reproduce that? How can I best test that?
> 
> Using an invalid/expired token should reproduce it, the portal should send us an error and we would like to drop the tunnel in response

Okay, I'll test this once https://github.com/firezone/firezone/pull/3682 is merged.

**Comment by thomaseizinger** [comment]
All points in the original description have been resolved. We still have a `Session` API but that might go away with https://github.com/firezone/firezone/issues/3837.
