### ISSUE TITLE
android: access logs while I am signed in

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3698]
I'd like to access the logs whilst I am signed in. Like get the directory or a "share" button etc.

I want to see the logs whilst firezone is running, not when it is stopped.

**Comment by thomaseizinger** [comment]
Currently, I have to:

- Sign out
- Click export logs
- Save them to a directory
- Unpack the zip
- Open the textfile

And even then I am greeted with "JSON" logs. It would be nice to see "normal" logs from within the app somehow or at least access them conveniently.

**Comment by jamilbk** [comment]
refs #2722
