### ISSUE TITLE
Make IP range configurable

### ISSUE THREAD

**Issue by hebgit** [CloudFire-LLC/cloudfire#370]
I would like to replace an existing environment with Firezone. Unfortunately, it seems that the internal IP range cannot be changed. This should be configurable.

**Comment by jamilbk** [comment]
Are you referring to the IPv4 and IPv6 subnets `10.3.2.1/24` and `fd00:3:2::1/120`? That's a very good point! This should be straightforward to expose in the main configuration file. I'll queue this into our backlog for the next minor release :-)
