### ISSUE TITLE
Add configuration option for changing the default web interface port

### ISSUE THREAD

**Issue by millerjs2** [CloudFire-LLC/cloudfire#377]
Hello,
I'm interested in running firezone on my home infrastructure, and I already have a reverse proxy set up for HTTP and HTTPS traffic, so my outbound port 443 is already tied up. I understand that port 443 can be changed in the nginx config included with firezone, but it would be very handy to include a configuration option to change this port easily.

Thanks!

**Comment by jamilbk** [comment]
Hi @millerjs2 

You should be able to change this in the main configuration file. See this line:

```ruby
default['firezone']['nginx']['ssl_port'] = 443
```

Closing this issue. Please open a new one if that doesn't work for you.

Thanks!
