### ISSUE TITLE
Support for Arch Linux-based distros

### ISSUE THREAD

**Issue by Amine-Kadi** [CloudFire-LLC/cloudfire#378]
Firezone would be very useful for **Arch Linux** based distribution as they are widely used for both desktop and server cases.

A package in the AUR could be accessible for :

- [Arch Linux](https://distrowatch.com/table.php?distribution=arch)
- [Manjaro](https://distrowatch.com/table.php?distribution=manjaro)
- [EndeavourOS](https://distrowatch.com/table.php?distribution=endeavour)
- [Garuda](https://distrowatch.com/table.php?distribution=garuda)

Links are distrowatch pages and ranks.

**Comment by jamilbk** [comment]
Hi @Amine-Kadi! Thanks for the request.

This is going to require some effort. We bundle all our dependencies into the final distributable `.deb` or `.rpm` using [Chef Omnibus](https://github.com/chef/omnibus). All our dependencies (even down to openssl and wireguard-tools) are essentially version-locked, built, and packaged into the final product. On top of that, we rely on Chef-solo for configuration management.

This is a tradeoff -- it saves us time having to maintain separate package build scripts for each distro/version of Linux we support, and it helps ensure that Firezone is running in a consistent environment. The downsides are obviously that some distros aren't easily supported, and our package size is fairly large.

We're hoping to make this more flexible in the future! If you wanted to start investigating what would be required to build an Arch-native package, you could start checking the top-level dependencies that Firezone relies on here: https://github.com/firezone/firezone/blob/master/omnibus/config/projects/firezone.rb#L36

**Comment by Amine-Kadi** [comment]
I'm not familiar with Chef Omnibus but I understand the pros and the cons!
I'll try to figure out how it works and see what's required to build an arch-native package. I'll keep you informed.

**Comment by adRn-s** [comment]
I have seen examples of AUR packages that bring DEB or RPM to Arch. Also, there is this tool: `alien_package_converter` in AUR that helps with this task. Last, if you feel up to the task, and firez.one developer(s) agree, omnibus could be replaced with [pacur](https://github.com/pacur/pacur). Good Luck!

**Comment by jamilbk** [comment]
I expect to Arch Linux fans to throw a few tomatoes thrown at me for saying this, but the most feasible way to do this now is [with Docker](https://docs.firezone.dev/deploy/docker/).

We also now have [build from source](https://docs.firezone.dev/deploy/advanced/build-from-source/) instructions that can be used as a basis for building an AUR package. Closing for now in an effort to clean up the ol' backlog.

**Comment by italogama** [comment]
Garuda user in suffer here 😢

**Comment by thomaseizinger** [comment]
> Garuda user in suffer here 😢

Assuming you came to this (very old) issue because you need the new Firezone 1.x _clients_ to run on Arch, then the best way to get an arch build is by lobbying upstream at Tauri to support Arch in their bundler: https://github.com/tauri-apps/tauri/issues/3728
