### ISSUE TITLE
Add security page to docs

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3784]
`/kb/reference/security`

- What data Firezone tracks, for how long, and what you can do about it
- What encryption we use and where
- Our process for handling security incidents
- Status of latest audit / pentest / compliance report
- Documentation on our operational procedures as they relate to security

See the outline [here](https://firezonehq.slack.com/archives/C06L41XN05T/p1709300424317399?thread_ts=1709160044.910229&cid=C06L41XN05T) for a starting point

**Comment by jamilbk** [comment]
@bmanifold I might ask to pair with you on outlining this doc.

**Comment by bmanifold** [comment]
Sounds good 👍
