### ISSUE TITLE
Allow using external Postgresql database

### ISSUE THREAD

**Issue by efossas** [CloudFire-LLC/cloudfire#379]
I use Cockroachdb to host several Postgres databases and would like to use it with this project. Plus, if Firezone will be horizontally scalable one day, it will need to be able to connect to an external db.

For this to work, I primarily need to be able to set these options for the Postgres connection:

https://github.com/firezone/firezone/blob/master/config/releases.exs#L43
```
connect_opts = [
  ...
  ssl: true,
  ssl_opts: [
    cacertfile: ...,
  ],
  parameters: [options: "--cluster=..."]
]
```

When I was hacking around Firezone, I discovered that `:ssl` is not currently compiled into the app; at least that's what i think this error is telling me (I'm not an Elixir dev):

```
SSL connection can not be established because `:ssl` application is not started,
    you can add it to `extra_applications` in your `mix.exs`
```

Finally, the chef recipe that creates the user, database and extensions would need to be updated to accept those params.
[firezone/omnibus/cookbooks/firezone/recipes/database.rb](https://github.com/firezone/firezone/blob/master/omnibus/cookbooks/firezone/recipes/database.rb)

although an option to skip that would be great as well.
(I've been manually editing the recipes to just skip those parts as I manually created the user, database, and extensions)

**Comment by jamilbk** [comment]
Thanks for the suggestion! I'll add this to our backlog.

You're correct -- we'll have to change how Postgres gets initialized via Chef. There's already a config option to disable Postgres, and Gitlab (also uses Omnibus) achieves this, so it should be entirely possible.

**Comment by jamilbk** [comment]
@efossas This was added in #421 and will roll out with the next release `0.2.10` in the next day or two.

**Comment by jamilbk** [comment]
Release 0.2.10 is live: https://github.com/firezone/firezone/releases/tag/0.2.10

See the new configuration file options `default['firezone']['database']['ssl_opts']` and `default['firezone']['database']['parameters']` as referenced here: https://docs.firez.one/docs/reference/configuration-file/
