### ISSUE TITLE
Legacy Firezone // Failure in WAN Connectivity Checks (404 for ping.firez.one)

### ISSUE THREAD

**Issue by l4rm4nd** [CloudFire-LLC/cloudfire#3794]
The legacy Firezone version 0.7.36 tries to contact `ping.firez.one` in order to obtain the WAN IP address. However, the domain is down and not accessible anymore (404).

This is displayed in the Firezone frontend too and creates the assumption that the VPN server is somehow not functioning properly. Also fills the psql database with bogus results.

Under the hood though, it is just an old legacy domain that does not respond properly anymore.

One may disable WAN connectivity checks via an env variable:

````
CONNECTIVITY_CHECKS_ENABLED=false
````
However, the proper fix would be to set a new, working domain or endpoint for those ping checks.

**Comment by jamilbk** [comment]
Thanks for the report! Sorry about that -- that server should still be functioning.

Should be fixed now!
