### ISSUE TITLE
connlib: connection fallback

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3807]
Summarised by @AndrewDryga, we need to come up with a design around connection establishment and fallback that fulfills the following requirements:

- Minimal initial latency (as soon as we find a working candidate we should start using it right away, and probably we should try candidates in the order that makes the most likely one to work first)
- Upgrades (as we find better candidates by priority we upgrade to them, this also helps to reduce our relaying cost)
- Reduce background traffic (keep checking only the N best pairs)
- Best throughput (select from N the best pair using RTT or some better metric than just priority)
- Battery efficiency (don’t wake up network interface too often when there is no actual traffic)

How to balance these trade-offs is tricky. Some the problems that we need to consider are:

- IPv4 vs IPv6 connectivity: If we can bind to a socket for either, we should (and we do currently). The network routes for both might be different, meaning just because we have an IPv6 socket doesn't mean we can actually reach anybody on it.
- Relays are reachable via IPv4 and IPv6: In many cases, we can reach the relay via its IPv4 and IPv6 address. Today, we treat those as different relays, which doubles the number of allocations that we make.
- How to eliminate all by the best N pairs for a connection: This needs to be a deterministic algorithm on both client and gateway to ensure we actually have a working fallback.
- Up-time dependency on portal: Eliminating too many candidates (i.e. all but 1 which is what we currently do) imposes a stricter up-time dependency on the portal because we need to run the signalling protocol again once the connection fails.

To effectively devise a design here, we need to answer the following questions (not exhaustive):

- Which network failure scenarios do we want to recover from without failing the connection and using the portal to establish a new one?
- How much background traffic is acceptable to support such a fallback?

**Comment by jamilbk** [comment]
Good discussion.

After more testing overnight on my iPhone, I actually don't think this is as big of an issue as first thought. @thomaseizinger I see you did [more scientific testing](https://github.com/algesten/str0m/issues/464) than my armchair approach :-).

I'll try to answer the above questions:

> Which network failure scenarios do we want to recover from without failing the connection and using the portal to establish a new one?

The main network failures scenarios for us are:

- Clients switching networks (Wifi -> Cellular, Ethernet -> WiFi, etc). In this case the connection will most likely fail and need to be recreated because the underlying physical interface has changed.
- Deployments. This is probably the biggest reason to have redundant Relay pairs, assuming we have a rolling deployment strategy for Relays. It would be nice to be able to deploy new releases stress-free, at any time of the day.

> How much background traffic is acceptable to support such a fallback?

In your comment linked above, you mention 80 KB / minute for an active connection. But what's an active connection? I think the right number here should be **0** for inactive connections, and something like a few KB / minute for active connections.

Instead of reducing the number of candidate pairs (this is the biggest thing that affects reliability and control plane load), would this be feasible instead:

- I noticed keepalives are sent every 1s? Maybe we can reduce that 5s, and fail after 3 missed, giving a connection failover timeout of 15s? I think 15s is an acceptable timeout for finding a new gateway -- based on customer feedback this seems to be low enough still that they can roll over their gateways **without** a planned maintenance window for their organization.
- Expire connections to gateways if no application data was seen for 1 minute. This is probably the biggest thing we can do to reduce overall battery life / bandwidth. Any layer 4 and above procotol wishing to keep a connection alive will know to send its own keepalives (TCP). Since WireGuard is silent by default, any packet seen through the tunnel has a high likelihood of being an application data packet and not a WireGuard message packet.

**Comment by thomaseizinger** [comment]
> * In this case the connection will most likely fail and need to be recreated because the underlying physical interface has changed.

All we need from the OS here is a hint that network interfaces might have changed. We can use that to refresh all STUN bindings and allocations which will immediately give us new host, srflx and relay candidates. Plus, we are invalidating the old ones with str0m so we shouldn't even need to wait for the ICE timeout here.

Probably needs a bit more tuning and testing but this should be really fast and we shouldn't need to make a new connection.

**Comment by thomaseizinger** [comment]
> * I noticed keepalives are sent every 1s?

I think it should be 3, will need to check with str0m in detail.

**Comment by jamilbk** [comment]
> All we need from the OS here is a hint that network interfaces might have changed. We can use that to refresh all STUN bindings and allocations which will immediately give us new host, srflx and relay candidates. Plus, we are invalidating the old ones with str0m so we shouldn't even need to wait for the ICE timeout here.

I see, so the only difference between this approach and waiting for a timeout is that we preemptively refresh bindings when we get a new interface.

All platforms have a trivial way to send interface change notifications into Connlib, so we could just do it then.

**Comment by thomaseizinger** [comment]
> Deployments. This is probably the biggest reason to have redundant Relay pairs, assuming we have a rolling deployment strategy for Relays. It would be nice to be able to deploy new releases stress-free, at any time of the day.

That part doesn't seem worth the cost to me, both in terms of complexity (we always have to deal with a list of relays instead of a single one. The 1-n relationship creates a fair bit of complexity in snownet) and in resource usage (every single connection made with firezone keeps a redundant relay allocation active).

My naive approach to zero-downtime deployment would have been to:

- Deploy blue (new) relays and exclusively use them over green (old) ones for new connections
- After some grace-period (a few hours, a day, etc), shut down old relays

As soon as connections idle (like the above mentioned 1 min), clients will gradually move their connections over to new relays at times where it doesn't cause any disruption to a user's traffic.

We could also be fancier here by measuring, how many connections are still in use on the relay. All relays export metrics for that so the shutdown could be tied to that instead of time.

**Comment by thomaseizinger** [comment]
> Deploy blue (new) relays and exclusively use them over green (old) ones for new connections

We might not even need to do anything specific in the portal here if we add a capability to the relays to "logout" of the portal but continue their relay operations.

**Comment by jamilbk** [comment]
> My naive approach to zero-downtime deployment would have been to:
> 
> Deploy blue (new) relays and exclusively use them over green (old) ones for new connections
> After some grace-period (a few hours, a day, etc), shut down old relays

Yeah, I think this might be a good approach. We might want to make sure we can deploy multiple times within this window however (in case we need to hotfix a bad deployment for example). Then we'd have more colors, one for each deployment right?

I realize now that even if we have two relays per client for "redundancy", they'll still be rolled over the same when redeploying, causing connections to possibly fail and be re-established.

The use case here is -- imagine an administrator taking a large snapshot of a VM or DB and `scp`ing it over Firezone to another host which might take a few hours.

I'd be curious if the connection would be recreated fast enough to prevent the scp from failing (they "should" be using rsync!).

Anyway, maybe our approach can be this then?:

* When establishing a connection, use candidate priority to settle on the best candidates
* If that happens to be a relay, keep two physical relay candidates alive for redundancy for the lifetime of this connection. Our Relays aren't as reliable as the regular Internet, we're likely to find bugs and see them overloaded at times, etc. As they mature we could reduce this to a single Relay.
* If the connection is host or direct candidate, discard all other candidate pairs. Firezone infrastructure is no longer in the hot path here, removing the most likely cause for a failed connection. The connection is now only likely to die if the client or gateway state changes.
* Kill idle connections that haven't seen application data for 1 minute.

With the above approach, we save battery life and bandwidth in most (> 90%) cases, and make the tradeoff for reliability in the relayed case.

I know it's still 1+n Relay complexity, but what do you think of the above approach?

If we find Relays to be incredibly stable we could then experiment with reducing the count to 1.

**Comment by thomaseizinger** [comment]
> > My naive approach to zero-downtime deployment would have been to:
> > Deploy blue (new) relays and exclusively use them over green (old) ones for new connections
> > After some grace-period (a few hours, a day, etc), shut down old relays
> 
> Yeah, I think this might be a good approach. We might want to make sure we can deploy multiple times within this window however (in case we need to hotfix a bad deployment for example). Then we'd have more colors, one for each deployment right?

I don't think so. Every time you deploy, all current instances would be considered "old" and no longer actively assigned. It shouldn't matter how many different versions there are at that point.

> I realize now that even if we have two relays per client for "redundancy", they'll still be rolled over the same when redeploying, causing connections to possibly fail and be re-established.

Even if we keep a redundant candidate pair of relays, the switch the new connection is still bound to the ICE connection timeout. If the current candidate pair times out and we don't have any redundant ones, the connection fails, otherwise we fall back to the next best pair.

In other words, if our ICE connection timeout is 15 seconds. It will take 15 seconds until we fail-over to the next pair or trigger the creation of a new connection upon the next connection intent from the upper application. Given that our signalling layer only takes a second or maybe two, there is no real difference in terms of latency here compared to the ICE timeout. We should tune the overall time it takes to make a new connection to common timeouts to ensure we can make an entirely new connection.

IMO, what is important is to recognise that the timeout value itself doesn't really matter when we compare the approach of having a redundant pair vs only one and making a new connection if it fails. Likely, the more important factor here in the design is the dependency on the portal to do the latter. But I think even that is a bit of a weak argument. The entire design of firezone depends on the portal being highly available. I don't see why we should make use of that to simplify how we treat broken connections, especially when it means we can reduce resource usage in other places.

> The use case here is -- imagine an administrator taking a large snapshot of a VM or DB and `scp`ing it over Firezone to another host which might take a few hours.

This sounds like something we should test in CI:

- Take the hash of an input file
- `scp` it in the background to a resource via a relay (not sure if `scp` can limit the bandwidth it uses, we'd have to make sure the transfer takes long enough to not complete before we restart the relay)
- Restart the relay
- Assert that the file received on the other end has the same hash

> If that happens to be a relay, keep two physical relay candidates alive for redundancy for the lifetime of this connection. Our Relays aren't as reliable as the regular Internet, we're likely to find bugs and see them overloaded at times, etc. As they mature we could reduce this to a single Relay.

It is unfortunately not as easy. Connectivity is tested by forming pairs among all candidates. Meaning if each peer keeps two relay candidates active, that is already 4 candidate pairs. That doesn't yet take into account IPv4 and IPv6 (both, which one we use to talk to the relay AND which of the two allocated IPs per relay we are talking about.)

What if talking to the relay on IPv4 and IPv6 are different network paths? We can reach a relay over both IPv4 and IPv6 but it also means we appear as different clients to the relay (clients are identified by their 3-tuple of IP, port and protocol). Technically, only the IPv4 network path to a relay could fail. Does that mean we should just choose one of the two IP versions for the current & backup relay candidate? How do we decide which one? If we see the relay itself as the failed component, then obviously all candidates on that relay are dead and we have to fall-back to the 2nd one (which again doubles all candidates).

I don't really see a good solution here to trim down the number of candidates to a set that actually provides redundancy for different failure modes. IMO, it is much simpler and likely more resilient to:

- Start out of with all candidates.
- Once a connection is found, narrow them down to only allow upgrades to better connections. If hole-punching fails, the other, "better" ones will automatically get invalidated so we should always end up with just one.
- If that path fails, fail the entire connection and make a new one. Latency-wise, that takes pretty much the same amount of time as failing over to a backup pair.

**Comment by thomaseizinger** [comment]
> IMO, it is much simpler and likely more resilient to:
> 
>  * Start out of with all candidates.
>  * Once a connection is found, narrow them down to only allow upgrades to better connections. If hole-punching fails, the other, "better" ones will automatically get invalidated so we should always end up with just one.
>  * If that path fails, fail the entire connection and make a new one. Latency-wise, that takes pretty much the same amount of time as failing over to a backup pair.

FTR, this is what we do today, except that we haven't optimised the timeouts yet.

**Comment by jamilbk** [comment]
Thanks for clarifying -- I did not realize failing over to a backup pair of candidates takes the same time as recreating the connection. That makes sense.

**Comment by AndrewDryga** [comment]
> My naive approach to zero-downtime deployment would have been to:

> Deploy blue (new) relays and exclusively use them over green (old) ones for new connections
> After some grace-period (a few hours, a day, etc), shut down old relays
> As soon as connections idle (like the above mentioned 1 min), clients will gradually move their connections over to new relays at times where it doesn't cause any disruption to a user's traffic.

It's important to remember that we do not deploy gateways, they are hosted on our clients' infrastructure, they will deploy them the way they want and rollout them the way they want, and we must ensure zero- or near-zero downtime during deployments. We can give them an advice like "one gateway should always be online per site to reach zero-downtime deployments" and hope they will follow it. 

I don't think that it's a good idea to tradeoff complexity of an algorithm inside connlib/snownet to the complexity of running our software by every single client of ours.

> Even if we keep a redundant candidate pair of relays, the switch the new connection is still bound to the ICE connection timeout. If the current candidate pair times out and we don't have any redundant ones, the connection fails, otherwise we fall back to the next best pair.

I can give connlib a way to subscribe for relays presence and this timeout will be near-realtime. We can do the same for gateways presence in the future.

> Likely, the more important factor here in the design is the dependency on the portal to do the latter. But I think even that is a bit of a weak argument. The entire design of firezone depends on the portal being highly available. I don't see why we should make use of that to simplify how we treat broken connections, especially when it means we can reduce resource usage in other places.

I don't see it as designing for the portal to be down but rather improving our SLA in case the portal is not available (deploying, network splits, third-party downtimes, the websocket connection is currently reconnecting due to roaming, etc). The timeout of failing back the connection can be part of the SLA too, but this is more for @jamilbk to define.

**Comment by thomaseizinger** [comment]
> > My naive approach to zero-downtime deployment would have been to:
> 
> > Deploy blue (new) relays and exclusively use them over green (old) ones for new connections
> > After some grace-period (a few hours, a day, etc), shut down old relays
> > As soon as connections idle (like the above mentioned 1 min), clients will gradually move their connections over to new relays at times where it doesn't cause any disruption to a user's traffic.
> 
> It's important to remember that we do not deploy gateways, they are hosted on our clients' infrastructure, they will deploy them the way they want and rollout them the way they want, and we must ensure zero- or near-zero downtime during deployments. We can give them an advice like "one gateway should always be online per site to reach zero-downtime deployments" and hope they will follow it.

Yes, this issue only concerns itself with the infrastructure we control. Any form of connection fallback is only possible if the gateway is still reachable. If the gateway restarts, it will have a different wireguard key, ICE credentials, listening port etc so we have to make an entirely new connection. At the moment, we also only connect to 1 gateway per resource. To me, having a "backup gateway" that we can fail-over to is a related but different feature to what we are discussing here.

> I don't think that it's a good idea to tradeoff complexity of an algorithm inside connlib/snownet to the complexity of running our software by every single client of ours.

If you put it as a general statement like that, I tend to agree. It is not just about the complexity of the algorithm though. What I tried to portrait above is the fact that any "optimization" we make in which candidates we keep alive also comes at a cost of reducing the utility of the entire fallback design in terms of which failure modes it can actually recover from. For example, the network paths for IPv4 and IPv6 might be different but if we want to reduce the amount of background traffic, we will have to decide which one we throw away. At that point, we are loosing one connectivity path that might just be the one we need in a particular failure scenario.

My conclusion from this is: Don't bother with trying to be clever in optimising which candidates to keep alive. Settle on one and let's instead optimise, how quickly we can make new connections in case the current one fails. That will cover a lot more failure scenarios and IMO has a better ROI.

> > Even if we keep a redundant candidate pair of relays, the switch the new connection is still bound to the ICE connection timeout. If the current candidate pair times out and we don't have any redundant ones, the connection fails, otherwise we fall back to the next best pair.
> 
> I can give connlib a way to subscribe for relays presence and this timeout will be near-realtime. We can do the same for gateways presence in the future.

That would be very helpful because it means we can invalidate those candidates instantly instead of having to wait for the ICE timeout.

> > Likely, the more important factor here in the design is the dependency on the portal to do the latter. But I think even that is a bit of a weak argument. The entire design of firezone depends on the portal being highly available. I don't see why we should make use of that to simplify how we treat broken connections, especially when it means we can reduce resource usage in other places.
> 
> I don't see it as designing for the portal to be down but rather improving our SLA in case the portal is not available (deploying, network splits, third-party downtimes, the websocket connection is currently reconnecting due to roaming, etc). The timeout of failing back the connection can be part of the SLA too, but this is more for @jamilbk to define.

But how much can we really do in a scenario of the portal (temporarily) being down? We can't make new connections because it is our signaling layer. A user can't roam because that would also require the exchange of new candidates. An admin can't update resources, ...

We should definitely not interrupt the data plane when we reconnect to the portal (and we don't do that today). But if reconnecting to the portal fails (currently after 15 min for clients), then we shut down the tunnel. I don't know what SLAs we want to provide here. To me, it just doesn't seem to be worth the trade-off of investing potentially a lot of time into trying to be clever in regards to connection fallback when that doesn't even cover all failure modes compared to just making a new connection and depending on the portal to be there for that.

**Comment by jamilbk** [comment]
> currently after 15 min for clients

Very good to know. I'll remember to document this.

**Comment by AndrewDryga** [comment]
> A user can't roam because that would also require the exchange of new candidates. An admin can't update resources, ...

I think one of the important things we should have mentioned is that we were discussing proactively opening a tunnel to the most common X resources to "warm them up" and reduce the latency for the initial request. If we do that then users that have just a few resources (would be the majority of our customers) will have everything connected at all times, so browsing will not be flaky as long as we can keep the data plane active.

Even now, I think people don't have lots of resources so they end up being connected all the time (the lifetime of connection is 1 week). 

But I would agree right now that it's not so beneficial to have fallbacks as if we will have everything pre-connected, so we can postpone it for later.

Added: just realized that we also use the control plane to exchange DNS messages, which makes it a really hard runtime dependency, probably should have used the wireguard connection for that. cc @jamilbk

**Comment by jamilbk** [comment]
> probably should have used the wireguard connection for that

+1 https://github.com/firezone/firezone/issues/3975

> we were discussing proactively opening a tunnel to the most common X resources to "warm them up" and reduce the latency for the initial request.

Interesting idea to decrease latency. Gotta keep in mind Activities / flow logs though -- we would want those to still track access time to resource

FWIW I've been testing on Cell and WiFi and our latency is actually pretty good with the latest adjustments. I think with a little more fine-tuning (and perhaps more geographically-distributed Relays) our connection establishment time should consistently be under 1s.

**Comment by AndrewDryga** [comment]
> we would want those to still track access time to resource

We will because we will get packet metrics per connection from the gateway, so authorization will be logged early but see activity will only happen when authorization is used.

**Comment by jamilbk** [comment]
> so authorization will be logged early but see activity will only happen when authorization is used.

So "Authorized at" in the activity page would correspond in this case to the time the user launched their client and not to the time the actual access to the resource was requested?

**Comment by thomaseizinger** [comment]
> > A user can't roam because that would also require the exchange of new candidates. An admin can't update resources, ...
> 
> I think one of the important things we should have mentioned is that we were discussing proactively opening a tunnel to the most common X resources to "warm them up" and reduce the latency for the initial request. If we do that then users that have just a few resources (would be the majority of our customers) will have everything connected at all times, so browsing will not be flaky as long as we can keep the data plane active.
> 
> Even now, I think people don't have lots of resources so they end up being connected all the time (the lifetime of connection is 1 week).

This doesn't really play that well together with an idle timeout of connections as discussed above. It is an interesting idea though. With only one active candidate pair per connection, I think that is worthwhile doing. Something we can do to speed up even the first connection is warm up the allocations. For that, we'd need a list of relays that we are most likely going to use. That would shave off at least 2 RTTs to the relay for the very initial connection because we'd have all candidates instantly ready.

**Comment by thomaseizinger** [comment]
I am considering this solved with the current implementation of "eliminate all pairs apart from the active one".
