### ISSUE TITLE
we need Support for ARM！

### ISSUE THREAD

**Issue by JohyC** [CloudFire-LLC/cloudfire#381]
It is very convenient and cheap to run on your own ARM machine! Running this task on AWS alone will be very expensive!
![image](https://user-images.githubusercontent.com/38210128/148003984-99e70cf3-0114-4ab6-b84e-8edf55a9d017.png)

**Comment by Amine-Kadi** [comment]
Same issue already exists : https://github.com/firezone/firezone/issues/282

**Comment by JohyC** [comment]
> Same issue already exists : #282

Wow! OK! I will close it.
