### ISSUE TITLE
fix(gui-client): Ensure Tauri client honors `LOG_DIR` on Linux

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3811]
Next step: Decide how GUI clients handle env vars (Obey, silently ignore, log a warning if detected), document it, then either cancel or complete this task

Per https://github.com/firezone/firezone/pull/3810/files#diff-1a04997a5ad650a6038e9bb30f6e136f6c18a7940112933612db15d07e61e046

**Comment by jamilbk** [comment]
Yeah there's been some discussion around this. Maybe we don't need to expose env vars for the gui clients?

The others expose their log filter etc from the settings view.

Will need to think more of a long term approach, whether the gui client can also run headless or we require you to use a separate binary to run headless (currently it's the latter)

**Comment by ReactorScram** [comment]
Whatever we decide, I'd like to have an informal spec somewhere. I haven't been maintaining that manual test list cause it's too verbose, and I haven't been adding stuff to the decision list either 😶 

Just a "CLI clients obey env vars, GUI clients keep settings in a JSON file and ignore env vars"

I've had an issue with debugging where I forgot that the Windows GUI ignores env vars, so I kept trying to set the log level and it was ignoring it. 

So I see two obvious options:
1. Let env vars override the JSON file and assume that anyone using env vars on a GUI knows what they're doing, and maybe show "(overridden)" in the Settings pane (Could be better for debugging)
2. Don't obey env vars in the GUI, and put a `tracing::warn!` if we detect any well-known Firezone env vars were set. This is much simpler and as I type it, I think I prefer that one.
