### ISSUE TITLE
Revert `/etc/resolv.conf` on app exit

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3817]
This will handle the happy path case in the headless linux client where a user has rebooted, restarted the client, or ~~restarted the Docker container~~ restarted via systemd.

**Comment by jamilbk** [comment]
It would be nice if there was some way to simply mask `/etc/resolv.conf` with our own while the process is alive. I could have sworn Linux had some fancy linking that could do this.

**Comment by ReactorScram** [comment]
The closest I can think of is using a mount like https://github.com/xetdata/nfsserve to overlay it, assuming Linux has an option to auto-unmount an NFS share if the server quits responding. This would also revert it on reboot.

We could even do a bind mount without NFS and that would at least revert it on reboot and simplify the manual revert command from `mv /etc/resolv.conf.before-firezone /etc/resolv.conf` to `umount /etc/resolv.conf`

I did some searches and asked ChatGPT but nothing obvious came up. Everyone says basically, trap this signal in your Bash script. If we have to run a Bash sidecar we may as well do something else entirely

**Comment by jamilbk** [comment]
We could instead modify the file in-place by adding our configuration to a sentinel stanza:

```
# BEGIN Firezone DNS configuration
nameserver 100.100.111.1
# END Firezone DNS configuration
```

**Comment by ReactorScram** [comment]
I think we'd have to prefix all other lines with `# `? Or will later servers in resolv.conf be ignored as long as our responds fast enough?

**Comment by jamilbk** [comment]
We insert our stanza in the top, beginning line 1. Order matters here.

**Comment by ReactorScram** [comment]
Okay. But that means if we take too long, network clients will move on to other DNS servers below us, right?

**Comment by jamilbk** [comment]
> network clients will move on to other DNS servers below us, right?

Correct, which might actually be a feature not a bug?
