### ISSUE TITLE
connlib: re-evaluate design of client's `Session`

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3830]
The client's `Session` currently sets a dedicated panic handler and uses a channel to remote shutdown the runtime. I think we no longer need either of those things.

- `tokio` already installs a panic handler for each worker-thread. We no longer spawn tasks in connlib so if the current panics, all resources are automatically freed.
- To shutdown the runtime, I think we can just store the `Runtime` in the `Session` and call `shutdown_background` on it once the client calls `disconnect`. There shouldn't be any more need for a channel.

**Comment by thomaseizinger** [comment]
@conectado Please have a look at this and let me know what you think.

**Comment by conectado** [comment]
> tokio already installs a panic handler for each worker-thread. We no longer spawn tasks in connlib so if the current panics, all resources are automatically freed.

Sounds good!

> To shutdown the runtime, I think we can just store the Runtime in the Session and call shutdown_background on it once the client calls disconnect. There shouldn't be any more need for a channel.

I remember there was kind of a convoluted reason on why it was done like this instead of keeping the handle to the runtime, in fact, if I remember it correctly we used to have that, let me look for the commit where we changed it to see if it is still valid

**Comment by thomaseizinger** [comment]
Closing as a duplicate of https://github.com/firezone/firezone/issues/3683.
