### ISSUE TITLE
Flaky elixir unit test

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3838]
First run: https://github.com/firezone/firezone/actions/runs/8107029420/job/22157871663?pr=3836
Second run: https://github.com/firezone/firezone/actions/runs/8107029420/job/22158327666?pr=3836

**Comment by thomaseizinger** [comment]
Another test failure: https://github.com/firezone/firezone/actions/runs/8150718136/job/22277437187?pr=3934

**Comment by thomaseizinger** [comment]
Another instance: https://github.com/firezone/firezone/actions/runs/8199319563/job/22424220568?pr=3682

**Comment by thomaseizinger** [comment]
Another instance: https://github.com/firezone/firezone/actions/runs/8271011839/attempts/1?pr=4127

**Comment by jamilbk** [comment]
Another one: https://github.com/firezone/firezone/actions/runs/8327482227/job/22785266019

**Comment by jamilbk** [comment]
@AndrewDryga I have a PR open which highlights the prevalence of the issue, it's about 3-5%:

https://github.com/firezone/firezone/pull/3996
