### ISSUE TITLE
Settings changes don't seem to be taking effect until app is restarted

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3862]
Steps to reproduce:

- Open the `release` client
- Sign into prod
- Change the URLs to use staging in Settings
- Sign in again, notice that prod is still being used

(Tasklist moved to #3868)

**Comment by jamilbk** [comment]
If the issue here is not being able to apply settings while signed in, we can show a warning when hitting `Apply` to that effect:

<img width="1012" alt="Screenshot 2024-03-01 at 6 39 52 AM" src="https://github.com/firezone/firezone/assets/167144/b23aa04e-71b7-4c00-8154-6bfa0e8d2d81">

**Comment by jamilbk** [comment]
From @bmanifold 

> yeah, it seems to be whatever setting I have at the time the app starts is what I'm stuck with until I quit the app

**Comment by ReactorScram** [comment]
~~👍 I'll add the warning. I remember a thread where we agreed it's okay if it needs a restart but I never got around to the warning dialog~~

**Comment by ReactorScram** [comment]
Oh wait I misread, it's related to signing out without quitting the app.

**Comment by jamilbk** [comment]
Yeah sorry, I should have been more clear

**Comment by ReactorScram** [comment]
No problem. Also I might move those TODOs to the PR when it opens, if the issue closes I'll probably lose track of them.
