### ISSUE TITLE
Graceful fallback when UAC is declined

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3863]
When UAC is declined, Firezone starts but gets stuck at `Signing in` presumably because the interface creation fails.

Maybe we can gracefully exit if UAC is declined, "Firezone requires admin and will now exit. See our docs at https://www.firezone.dev/kb/user-guides/windows-client"

**Comment by jamilbk** [comment]
User reported I think that he explicitly needed to "Run as administrator". Maybe that'll go in #3864

**Comment by ReactorScram** [comment]
Hm I can't get it to replicate on my Windows 11 dev system, with Firezone 1.0.0-pre.9 (127b97e):
- If I refuse UAC, the app just exits
- If I run as admin and refuse UAC, same thing

I saw the user is on a Windows 10 VM with some different settings so maybe 10 handles UAC differently.

**Comment by jamilbk** [comment]
Gotcha. Maybe behavior on Windows 10 is different. We can revisit this after #3230 is completed as that might affect this
