### ISSUE TITLE
Windows client sometimes stuck at 'signing-in' state on startup

### ISSUE THREAD

**Issue by bmanifold** [CloudFire-LLC/cloudfire#3867]
When using the Firezone Windows client  and clicking 'Disconnect and quit Firezone', the next start of the application seems to get hung in a 'Signing In...' state.

OS Info:
|Key | value |
|----|----|
|Edition |	Windows 10 Pro |
|Version |	22H2 |
|Installed on |	‎12/‎25/‎2021 |
|OS build |	19045.4123 |
|Experience |	Windows Feature Experience Pack 1000.19054.1000.0 |

To reproduce:
* Start Firezone Windows client and sign-in
* Click the 'Disconnect and quit Firezone' option
* Restart the client
* View the app stuck in the 'Signing in...' state
* Attempt to click 'Cancel sign-in' (this should have no effect)
* Click 'Quit Firezone'
* Restart the client
* Wait for 'Firezone Connected' notification to appear

<img src="https://github.com/firezone/firezone/assets/2646332/616715f9-6bf5-449a-9b94-f0154c842431" width="150">
<img src="https://github.com/firezone/firezone/assets/2646332/cb115a30-8cfa-432b-b6f1-d36e20cebd1c" width="150">
<img src="https://github.com/firezone/firezone/assets/2646332/629acb7d-8edb-430a-ac08-6c42b2f7c8e2" width="150">
<img src="https://github.com/firezone/firezone/assets/2646332/10e80465-d82a-4ffe-9ea6-66a360655aca" width="150">
<img src="https://github.com/firezone/firezone/assets/2646332/8034867d-32cb-4769-8fb3-7b7f1412374b" width="150">

**Comment by ReactorScram** [comment]
@bmanifold I tried a few times and couldn't replicate it on Win 11. Can you attach logs if it replicated on your system?

**Comment by bmanifold** [comment]
I triggered the issue and then let it stay in the "Signing in...." state for a couple of minutes.  Hopefully that caught enough in the logs to help.

[connlib-2024_03_01-11-51.zip](https://github.com/firezone/firezone/files/14463712/connlib-2024_03_01-11-51.zip)

**Comment by ReactorScram** [comment]
Yeah, I see an error from wintun saying it can't create a device that already exists. So maybe the old one didn't get torn down in time. I'll make a test case to replicate that.

There's also some `PortalConnectionError` mentioning `WSAStartup`, those happen when the app is already shutting down maybe they're harmless. I'm mentioning it here because it was not in Github's search index. It is mentioned in a Slack thread.

**Comment by ReactorScram** [comment]
I'll close this for now as can't reproduce

- We haven't seen it replicate
- We don't have any leads on it
- There's been a couple changes related to Tauri setup and wintun setup that may have incidentally fixed it
- It should be obvious once customers start using it, if it recurs we can revisit this.

**Comment by bmanifold** [comment]
If there is a new windows client, I can try again to see if I'm still seeing it.  Out of curiosity, do we know if any of our current users are using it with Windows 10?

**Comment by ReactorScram** [comment]
Sure, you could try with the newest one from the draft release: https://github.com/firezone/firezone/releases/download/untagged-512161b46488e1913d28/firezone-windows-client-x64.msi

I don't know who is using it. My dev system is 11 and my test VM is I think Server 2022, so it's probably under-tested on 10.
