### ISSUE TITLE
linux: provide a NetworkManager plugin

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3892]
I figured this is worth tracking separately.

To be able to use the Linux client with a decent UX, it needs to be a NetworkManager plugin:

- Avoids having to run the GUI / CLI as root
- Directly integrates with DE like Gnome (not sure about others)
- DE integration enables features like autostart

**Comment by jamilbk** [comment]
This has been requested a few times by users, but AFAICT the integration won't be trivial. There isn't a clean way to integrate Firezone webview-based auth with NM. I could be wrong here.

> Avoids having to run the GUI / CLI as root

Yeah this will need to be fixed regardless of NM -- see #3713

**Comment by thomaseizinger** [comment]
> This has been requested a few times by users, but AFAICT the integration won't be trivial. There isn't a clean way to integrate Firezone webview-based auth with NM. I could be wrong here.

Once things run in two processes, we can just give the token to the background process, no? The split might not be trivial but I don't see why it couldn't be done. I think the important bit is that we separate "The background process is active" from "The tunnel is active". I think NM plugins talk over DBus so we should be able to send messages to it and then start up the tunnel with the token.

**Comment by jamilbk** [comment]
Hm, if the NM plugin is started without the Firezone userspace process running (could this happen?), and the token's expired, where should connlib send the `onDisconnect(error=401)` callback to? Will the user be prompted to open the Firezone app to sign in?

I lean towards maybe kicking this can down the road for a bit, because we'll have to maintain all future client features with NM, so it increases our surface area of integrations to maintain. For example, prompting for user authentication depending on which Resource is accessed (some may have stricter session requirements) would be an upcoming feature we'll need to get working with NM.

Do note that systemd-resolved and NM already play nicely together, which means we already play nicely with NM DNS (similar to our peers' products in the space)

**Comment by thomaseizinger** [comment]
> Hm, if the NM plugin is started without the Firezone userspace process running (could this happen?), and the token's expired, where should connlib send the `onDisconnect(error=401)` callback to? Will the user be prompted to open the Firezone app to sign in?

It is my understanding the NM plugin is reachable via dbus so it should also be able to [send a notification to the user via dbus](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#protocol).

> I lean towards maybe kicking this can down the road for a bit, because we'll have to maintain all future client features with NM

Devil's advocate: Maybe it would be good to integrate with NM early on then to ensure we only design features that we can actually ship?

**Comment by thomaseizinger** [comment]
Closing this as not relevant. Firezone isn't a VPN that you need to turn on/off. Instead, it should just run as a daemon in the background and offer the additional network interface.

**Comment by minecraftchest1** [comment]
> Closing this as not relevant. Firezone isn't a VPN that you need to turn on/off. Instead, it should just run as a daemon in the background and offer the additional network interface.

Just because you don't use it for that doesn't mean there aren't people who use it like that.

**Comment by minecraftchest1** [comment]
> This has been requested a few times by users, but AFAICT the integration won't be trivial. There isn't a clean way to integrate Firezone webview-based auth with NM. I could be wrong here.

I don't know much about developing plugins for Network-Manager, but I can think of no reason why the plugin couldn't spin up a quick and dirty webserver, have the user open a link in there browser, and then send the user to the local server to finish logging in as is done for OpenID Connect in many applications? This even allow nm-cli to work.

**Comment by jamilbk** [comment]
@minecraftchest1 Happy to reopen this if someone in the community wants to take a stab at it. The requirement would be that it needs to integrate into our existing auth flow - I think our appetite for adding a new auth flow to the portal to support NM plugins on Linux is extremely low due to the increased attack surface it brings. Combined with the fact none of us know much about developing plugins for NetworkManager either, unfortunately this issue probably won't be a priority for us in the immediate future.

**Comment by jamilbk** [comment]
Giving an example of a NM plugin that uses a browser-based auth flow to authenticate the tunnel might be a good first step.

**Comment by thomaseizinger** [comment]
> > Closing this as not relevant. Firezone isn't a VPN that you need to turn on/off. Instead, it should just run as a daemon in the background and offer the additional network interface.
> 
> Just because you don't use it for that doesn't mean there aren't people who use it like that.

Can you explain how you want to use it? One of the core features is split tunneling and split DNS so you don't need to turn firezone off to access things that aren't defined in firezone. They just work as if firezone wasn't running in the first place :)

**Comment by thomaseizinger** [comment]
> > > Closing this as not relevant. Firezone isn't a VPN that you need to turn on/off. Instead, it should just run as a daemon in the background and offer the additional network interface.
> > 
> > 
> > Just because you don't use it for that doesn't mean there aren't people who use it like that.
> 
> Can you explain how you want to use it? One of the core features is split tunneling and split DNS so you don't need to turn firezone off to access things that aren't defined in firezone. They just work as if firezone wasn't running in the first place :)

FWIW, I closed this as not-relevant myself because I had finally understood how it is meant to be used (which I didn't when I opened the issue).

**Comment by thomaseizinger** [comment]
> > > Closing this as not relevant. Firezone isn't a VPN that you need to turn on/off. Instead, it should just run as a daemon in the background and offer the additional network interface.
> > 
> > 
> > Just because you don't use it for that doesn't mean there aren't people who use it like that.
> 
> Can you explain how you want to use it? One of the core features is split tunneling and split DNS so you don't need to turn firezone off to access things that aren't defined in firezone. They just work as if firezone wasn't running in the first place :)

If you have a usecase that isn't solved by this, it would be great if you could write it up in an issue and - in addition - explain, why you think an NM plugin could solve this. Then we can more easily explore what other solutions there are to the same problem / usecase.
