### ISSUE TITLE
Request: Allow device defaults to be set via config file

### ISSUE THREAD

**Issue by colonelpanik** [CloudFire-LLC/cloudfire#391]
There are two options I currently have to set by hand after I install, specifically DNS and allowed routes.

Its a Must-Have to set DNS globally via a config option and not just via UI. I have dnsmasq running on the firezone server and expect clients to use that, as there are a few domain/wg specific things I've set (host names to wg interfaces for example), and this really ties the whole room together with FQDN resolution on mail and etc.

Allowed routes is a nice-to-have since i really have two use cases, and mostly I just want a couple of private networks routing across wireguard, since this is bridging a private cloud + public VPC and only certain classes of networks are trusted on this bridge. However I have another use case where I want all traffic to be routed (vpn use case). Maybe there can be an option to set one of the following:

1. Route all traffic (0.0.0.0/0)
2. Route only WG traffic (10.3.2.0/24 or whatever subnet is set to)
3. Custom allowed-ips config line ([ 10.3.2.0/24, 192.168.142.128/28, 10.99.14.0/23 ])

**Comment by jamilbk** [comment]
@colonelpanik Thanks for the suggestions! I think the AllowedIPs field change to a 3-option radio makes sense. Those are fairly common scenarios.

For the global DNS config option, this could be exposed via config entry that would be overridable in the Web UI. That's pattern for other config options currently. I can queue this up for the next release.

**Comment by colonelpanik** [comment]
That would be great, thanks @jamilbk ! I'm ok with any method to set (both|either) of these options and am looking forward to this change.

**Comment by jamilbk** [comment]
@colonelpanik This was added in #422 and is now live with the Release 0.2.10 you can find here: https://github.com/firezone/firezone/releases/tag/0.2.10

For the AllowedIPs UI improvement, I held off because we are going to be introducing some changes in the near future that will make that easier.
