### ISSUE TITLE
Fix SplashViewModel crash when upgrading to hilt 2.51

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3915]
Upgrading from hilt 2.50 -> 2.51 causes the dependency injection to fail, causing a crash on App start.

**Comment by aappiya-tby** [comment]
**!important**
2.51 has not been fixed yet. Downgrading is the only option.

**Comment by jamilbk** [comment]
Hi @aappiya-tby, is this causing an issue with the latest version of the Android app for you?
