### ISSUE TITLE
Allow devices to be created via firezone-ctl

### ISSUE THREAD

**Issue by colonelpanik** [CloudFire-LLC/cloudfire#392]
Right now in order to create a device I have to go into the UI, add it, edit it, change the name and potentially last octet.

It would be great if I could do something like:

firezone-ctl add-device

And get a device and maybe something like:

firezone-ctl add-device 'device-name' '100'

To specific my devicename with 10.3.2.100

This would make automating the addition of firezone clients possible whereas today it is very difficult.

**Comment by jamilbk** [comment]
@colonelpanik Thanks for the suggestion! More automation features are on our roadmap, including a REST API that can be called by `firezone-ctl` to do what you're describing. No ETA yet, but I'll link any relevant PRs to this issue when they're ready!

**Comment by rchekhina** [comment]
HI,

It will be create that we can install firezone in front of an existing wireguard server and import the existing peers maybe the api can do this.

**Comment by jamilbk** [comment]
Closing this in favor of #903 -- the REST API will allow CLI creation of devices.
