### ISSUE TITLE
bug(ci): version-check probably doesn't check the versions for the Tauri clients

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#3923]
Since those are disabled from compiling on macOS. Maybe a Linux runner could check `gui-client`? I don't know how version-check works.

**Comment by ReactorScram** [comment]
If #3977 merges, we can probably allow version-check to cover the Tauri GUI client.

**Comment by jamilbk** [comment]
In fact it does -- it just uses grep and sed to replace the `# mark:automatic-version` sentinels, no runtime required.

**Comment by jamilbk** [comment]
See `scripts/Makefile`
