### ISSUE TITLE
connlib: invalidate relay candidates when relay goes down

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3938]
This avoids having to wait for the ICE timeout of a connection. Any connection that was depending on this relay will instantly fail and we will make a new one upon the next connection intent.

Depends on https://github.com/firezone/firezone/issues/3937.

**Comment by thomaseizinger** [comment]
Whilst thinking about https://github.com/firezone/firezone/issues/4521, I had an idea.

We can also invalidate relay candidates as soon as we hit an unauthorized error. If we have wrong credentials, then the allocations are useless and we need to stop using them for the data plane.

**Comment by thomaseizinger** [comment]
Here is where we need to invalidate them (not the srvflx candidate though)

https://github.com/firezone/firezone/blob/95c7f41a527322dd684dd462dc09c7a3f568e571/rust/connlib/snownet/src/allocation.rs#L212-L217

**Comment by jamilbk** [comment]
> we will make a new one upon the next connection intent.

I wonder if waiting this long will cause problems with DNS resources. The connection intent only happens there when the name is originally requested, and not when a packet is seen through the tunnel for an existing mapping IIRC. cc @conectado

**Comment by thomaseizinger** [comment]
Superseded by #4548.
