### ISSUE TITLE
Don't show Settings window on App Start

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3961]

**Comment by ReactorScram** [comment]
Agreed. But there is a problem that Windows hides our tray icon by default, and a tray icon may not be an obvious enough launch notification on the first time.

So we can try forcing the tray icon to show, at least while Firezone is signed out: https://superuser.com/questions/1753209/

And we could use the generation of the device ID (firezone-id) as a cue to do a little "first-time install" thing, maybe have a notification saying, "Firezone is in the tray, sign in to access resources"

At the most extreme we could show a notification every time Firezone starts signed-out saying "Sign in to Firezone"

**Comment by jamilbk** [comment]
I like the `firezone-id` trick. Could we use that to show a simple Welcome to Firezone view, with a little screenshot / arrow pointing to the lower right?

E.g. "Welcome to Firezone. Use the taskbar icon to sign in."

I can whip up a graphic / view

**Comment by jamilbk** [comment]
Ah but I guess on Linux it'd be in the upper-right most likely. Instead of the arrow we could just show a zoomed in screenshot of the icon running in the Taskbar / Menubar

**Comment by ReactorScram** [comment]
Yeah that could work. On Windows XP the notifications used to point right at the tray icon and for some reason they removed that, so you can't tell where stuff is coming from as easily 
![image](https://github.com/firezone/firezone/assets/13400041/90470bbb-b79b-41a3-b327-4cfbae2c1968)

**Comment by jamilbk** [comment]
Oh, does Tauri support UI notifications? Maybe we could show that on first launch instead?

**Comment by jamilbk** [comment]
Either or, I don't feel strongly. The macOS / iOS / Android apps shows a welcome screen with the "Grant VPN permission" button.

On Tauri it could be similar, minus the "Grant" buton

**Comment by ReactorScram** [comment]
Yeah not sure if it's Tauri or some other dep but we have notifications for updates, re-auth and signed-in events: 
![image](https://github.com/firezone/firezone/assets/13400041/6e75074f-9932-407b-a59e-a277ca5a6ec2)

**Comment by ReactorScram** [comment]
Agreed on standup to add a third window "Welcome" which can't be explicitly shown but is shown after first install and then not shown once the user dismisses it (for some bikeshed-able definition of "dismiss")

I'm not sure if we can somehow detect an "Install ID" for this case:
- User installs, runs, dismisses Welcome, un-installs, installs, runs, window should appear
- User installs, runs, dismisses Welcome, updates, runs, window should not appear

**Comment by jamilbk** [comment]
> User installs, runs, dismisses Welcome, un-installs, installs, runs, window should appear

Maybe it can be assumed the user already knows where to find Firezone in this case.

I think it's mostly to help users who have never seen Firezone at all
