### ISSUE TITLE
Flaky Relay test

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3965]
https://github.com/firezone/firezone/actions/runs/8152130288/job/22281106356?pr=3956#step:5:1289

**Comment by thomaseizinger** [comment]
Can't reproduce without a backtrace unfortunately. I opened https://github.com/firezone/firezone/pull/4137 so in case this ever happens again, we can look into it.

**Comment by thomaseizinger** [comment]
And we have one!

https://github.com/firezone/firezone/actions/runs/8289707456/job/22686594463?pr=4156
