### ISSUE TITLE
UI requires refresh to show updated email address

### ISSUE THREAD

**Issue by colonelpanik** [CloudFire-LLC/cloudfire#397]
The currently logged in user's email address is displayed in the upper right corner. However one can update the user's email address via /settings/account, which works as expected. After saving, the page is refreshed and shows the correct email in the primary display, but the user's email address in the upper right corner remains the old address and initially confused me..

However, a full page refresh sets this to display correctly so this is a just minor UI display issue.

**Comment by jamilbk** [comment]
Thanks for the report! Will queue for the next release.
