### ISSUE TITLE
bug(gui-client): Flaky smoke test

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3972]
- Windows 2019 - https://github.com/firezone/firezone/actions/runs/8104640577/job/22151626943#step:11:36
- Windows 2022 - https://github.com/firezone/firezone/actions/runs/8159147312/job/22302766244?pr=3950#step:11:24
- Ubuntu 22.04 - https://github.com/firezone/firezone/actions/runs/8365676251/job/22904084776

**Comment by ReactorScram** [comment]
Looks like it did not write the device ID to disk, whereas the other version of Windows did. https://github.com/firezone/firezone/actions/runs/8159147312/job/22302765664?pr=3950#step:11:23

Weird... Nothing comes to mind yet.

**Comment by ReactorScram** [comment]
Looks like it could have hung up somewhere in here: https://github.com/firezone/firezone/blob/f69e645a20c388d65bd583c5fd9293a777b7a276/rust/gui-client/src-tauri/src/client/gui.rs#L158-L187
Or when setting up the device ID: https://github.com/firezone/firezone/blob/f69e645a20c388d65bd583c5fd9293a777b7a276/rust/gui-client/src-tauri/src/client/gui.rs#L785

I'll add more `tracing::debug!` in that block. The device ID is pretty simple, I think it's the deep link server.

**Comment by ReactorScram** [comment]
Looks similar to #3699 
> I narrowed it down to app.build: https://docs.rs/tauri/1.5.4/src/tauri/app.rs.html#1554-1710
This is a huge chunk of Tauri code that builds the app instance and gets it ready to run. We call that function, and at the end it's supposed to call our callback to start run_controller, but it never does.

**Comment by ReactorScram** [comment]
I think it's getting stuck on creating the GTK event loop for the window: https://docs.rs/tauri/1.6.1/src/tauri/app.rs.html#1594
https://github.com/firezone/firezone/actions/runs/8366214531/job/22905919159#step:10:614

I'll try moving some initialization after that happens, maybe it's racing something I'm doing in a Tokio task.

**Comment by ReactorScram** [comment]
#4232 may have fixed it. Let's re-open this if it recurs.
