### ISSUE TITLE
"Peer is already bound to another channel"

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3979]
#### Describe the bug

Gateway stops allowing connections

#### To Reproduce

Run a Gateway for a few days with heavy usage

#### Expected behavior

Connections resume once the backoffs subside

#### Screenshots / Logs

https://firezonehq.slack.com/archives/C0691K7382G/p1709611053234289

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Gateway
- _Firezone Version (e.g. 1.0.0 or N/A):_ 1.0.0-pre.10
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ N/A
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Docker

**Comment by thomaseizinger** [comment]
> Connections resume once the backoffs subside

Once a backoff completely fails, we won't restart it by itself. It will be reset upon the next successful interaction with the `Allocation` which typically happens when a client wants to establish a connection. We always refresh all `Allocation`s that we are about to use for the new connection.

I think this works as expected. We have to give up talking to the relay at some point if all we are getting is timeouts.

**Comment by jamilbk** [comment]
Closing as can't reproduce

**Comment by thomaseizinger** [comment]
The more interesting logs are the following:

```
2024-03-05T03:47:12.619241Z  WARN decapsulate{from=34.102.56.34:3478 num_bytes=40}:handle_input{relay=34.102.56.34:3478 id=TransactionId(0x0DECA0E42F2DC59A20E0B138) method=channel bind class=error response rtt=222.323839ms}: snownet::allocation: STUN request failed error=Bad Request
2024-03-05T03:47:12.729503Z  WARN decapsulate{from=35.195.41.65:3478 num_bytes=40}:handle_input{relay=35.195.41.65:3478 id=TransactionId(0xE1BEFC40CCBCE67558E4E78D) method=channel bind class=error response rtt=221.969838ms}: snownet::allocation: STUN request failed error=Bad Request
```

I would be interesting to see the related logs on the relay for these two transaction IDs.

**Comment by thomaseizinger** [comment]
I can only see IPv4 traffic in these logs so likely, all the timeouts are for the IPv6 relays. I am improving the logs to make that more obvious.

**Comment by jamilbk** [comment]
@thomaseizinger Here are the matching logs -- looks like this particular case went to europe-west-1d:

https://console.cloud.google.com/logs/query;query=%2528resource.type%3D%22gce_instance%22%20AND%20resource.labels.instance_id%3D%227104780589755144343%22%2529%20OR%20%2528resource.type%3D%22global%22%20AND%20jsonPayload.instance.id%3D%227104780589755144343%22%2529%0A--Show%20similar%20entries%0AjsonPayload.message%3D~%22channel%20bind%20failed:%20Bad%20Request%22%0A--End%20of%20show%20similar%20entries;cursorTimestamp=2024-03-05T04:36:31.272864290Z;startTime=2024-03-05T03:40:39.000Z;endTime=2024-03-05T04:44:09.000Z?project=firezone-prod

**Comment by jamilbk** [comment]
```
{
  "insertId": "1d44m19fc6xajd",
  "jsonPayload": {
    "target": "relay",
    "span": {
      "allocation": "AID-3",
      "transaction_id": "e1befc40ccbce67558e4e78d",
      "peer": "172.56.105.13:11559",
      "sender": "64.38.135.132:42039",
      "channel": "16388",
      "name": "handle_client_input"
    },
    "time": "2024-03-05T03:47:12.660110317Z",
    "cos.googleapis.com/container_id": "b4da913684e939f64c99e75c6241b1f2cbf854147de1dae5064916d72ccebcb3",
    "spans": [
      {
        "name": "Eventloop::poll"
      },
      {
        "name": "handle_client_input",
        "transaction_id": "e1befc40ccbce67558e4e78d",
        "allocation": "AID-3",
        "channel": "16388",
        "peer": "172.56.105.13:11559",
        "sender": "64.38.135.132:42039"
      }
    ],
    "cos.googleapis.com/container_name": "klt-relay-bfgi",
    "cos.googleapis.com/stream": "stdout",
    "message": "channel bind failed: Bad Request"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "project_id": "firezone-prod",
      "zone": "europe-west1-d",
      "instance_id": "7104780589755144343"
    }
  },
  "timestamp": "2024-03-05T03:47:12.660460740Z",
  "severity": "WARNING",
  "logName": "projects/firezone-prod/logs/cos_containers",
  "sourceLocation": {
    "file": "relay/src/server.rs",
    "line": "320"
  },
  "receiveTimestamp": "2024-03-05T03:47:13.097130951Z"
}
```

And

```
{
  "insertId": "1d44m19fc6xajd",
  "jsonPayload": {
    "target": "relay",
    "span": {
      "allocation": "AID-3",
      "transaction_id": "e1befc40ccbce67558e4e78d",
      "peer": "172.56.105.13:11559",
      "sender": "64.38.135.132:42039",
      "channel": "16388",
      "name": "handle_client_input"
    },
    "time": "2024-03-05T03:47:12.660110317Z",
    "cos.googleapis.com/container_id": "b4da913684e939f64c99e75c6241b1f2cbf854147de1dae5064916d72ccebcb3",
    "spans": [
      {
        "name": "Eventloop::poll"
      },
      {
        "name": "handle_client_input",
        "transaction_id": "e1befc40ccbce67558e4e78d",
        "allocation": "AID-3",
        "channel": "16388",
        "peer": "172.56.105.13:11559",
        "sender": "64.38.135.132:42039"
      }
    ],
    "cos.googleapis.com/container_name": "klt-relay-bfgi",
    "cos.googleapis.com/stream": "stdout",
    "message": "channel bind failed: Bad Request"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "project_id": "firezone-prod",
      "zone": "europe-west1-d",
      "instance_id": "7104780589755144343"
    }
  },
  "timestamp": "2024-03-05T03:47:12.660460740Z",
  "severity": "WARNING",
  "logName": "projects/firezone-prod/logs/cos_containers",
  "sourceLocation": {
    "file": "relay/src/server.rs",
    "line": "320"
  },
  "receiveTimestamp": "2024-03-05T03:47:13.097130951Z"
}
```

**Comment by jamilbk** [comment]
"Channel is already bound to a different peer"

https://console.cloud.google.com/logs/query;cursorTimestamp=2024-03-05T03:47:12.660460740Z;endTime=2024-03-05T04:44:09.000Z;query=%2528resource.type%3D%22gce_instance%22%20AND%20resource.labels.instance_id%3D%227104780589755144343%22%2529%20OR%20%2528resource.type%3D%22global%22%20AND%20jsonPayload.instance.id%3D%227104780589755144343%22%2529%0Atimestamp%3D%222024-03-05T03:47:12.660400443Z%22%0AinsertId%3D%221d44m19fc6xajc%22;startTime=2024-03-05T03:40:39.000Z?project=firezone-prod

**Comment by thomaseizinger** [comment]
Interesting. I'll look into that. Appears that we are not advancing the channel numbers correctly somewhere.

**Comment by jamilbk** [comment]
@thomaseizinger Yeah it looks like it's happening a lot:

https://console.cloud.google.com/logs/query;query=%2528resource.type%3D%22gce_instance%22%20AND%20jsonPayload.message%3D~%22Channel%20is%20already%20bound%20to%20a%20different%20peer%22%2529;cursorTimestamp=2024-03-06T19:49:41.006205674Z;duration=P14D?project=firezone-prod

**Comment by jamilbk** [comment]
This is still an issue.

More recent logs:

https://console.cloud.google.com/logs/query;query=%2528resource.type%3D%22gce_instance%22%20AND%20resource.labels.instance_id%3D%227607456471087978648%22%2529%20OR%20%2528resource.type%3D%22global%22%20AND%20jsonPayload.instance.id%3D%227607456471087978648%22%2529;cursorTimestamp=2024-03-11T18:55:51.005111792Z;duration=PT1H?hl=en&project=firezone-prod

**Comment by jamilbk** [comment]
The result of this is that the gateway becomes unable to establish connections. The other error seen during this scenario is "Channel is already bound to a different peer".

The two cases are checked [here](https://github.com/firezone/firezone/blob/main/rust/relay/src/server.rs#L667) and [here](https://github.com/firezone/firezone/blob/main/rust/relay/src/server.rs#L679).

It seems like for this to happen, either:

- There's a channel mapping bug in the lookup, or
- Channel allocations are re-using existing numbers?
