### ISSUE TITLE
Refactor `onDisconnect`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3993]
Handle the cases more explicitly:

- Remove the `onDisconnect(null)` success callback -- this won't fail in connlib so we can just instantly perform cleanup when `Session.disconnect` returns
- `onDisconnect(error)` should now be the only place where connlib notifies the app to disconnect, and this should log the error and clear the token.

**Comment by thomaseizinger** [comment]
> * Remove the `onDisconnect(null)` success callback -- this won't fail in connlib so we can just instantly perform cleanup when `Session.disconnect` returns

I'll attempt this today and see if we can actually do this.
