### ISSUE TITLE
Windows app shortcut icon is not HiDPI

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3999]

**Comment by bmanifold** [comment]
Here's what it looks like on my screen.  My resolution is set to: 3840 x 2160
![firezone-logo-pixelated](https://github.com/firezone/firezone/assets/2646332/005e3819-8e66-4fd0-ad58-bd3d8c5e265d)

**Comment by jamilbk** [comment]
@bmanifold Think a fix was merged for this, may want to double-check if you're able?

**Comment by bmanifold** [comment]
Unfortunately, the icon is still pixelated on my machine.

**Comment by ReactorScram** [comment]
Ah I wasn't subscribed to this issue.

That's too bad. I marked it with a late milestone since it's visual and we can probably put it off.

**Comment by bmanifold** [comment]
Yeah, it's not definitely not a priority, just a small thing I noticed.  Let me know if/when you need me to test something again.

**Comment by bmanifold** [comment]
Just wanted to report back.  The last time I installed the windows client (which was Apr 3, 2024) I noticed that the icon on my desktop was a hi-res icon like the others 🎉
