### ISSUE TITLE
connlib: remove `Result` return values from `Callbacks`

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4064]
Currently, all callback methods can return an error. That is super convoluted because it creates a circular control-flow between the clients and connlib.

If a callback method would fail or throw an exception, then we currently just end up logging that and continue:

https://github.com/firezone/firezone/blob/d8df8d8b7e0b934d171b8e2cb29349cfcae73f46/rust/connlib/clients/shared/src/control.rs#L435

It would be much easier to understand to not hand this errors up and down the stack and either:

1. Log them directly in the client code
2. Panic in the client code

My preference would be for (2) because all the errors in the FFI layer should be statically asserted, i.e. if we get a function signature or something else wrong, then there isn't really any point in bubbling that up as a normal error.

Similarly, I don't think it is connlib's responsibility to handle exceptions that are thrown in the client code. Connlib has no idea how fatal such an error is. On the other hand, a client can either continue with normal operation or call `disconnect` if the Tunnel is otherwise broken.

**Comment by thomaseizinger** [comment]
cc @conectado Let me know if I am missing something.

**Comment by conectado** [comment]
Yeah, this makes sense, when we used to set routes individually there were certain cases where we *should*(we did at a time but we stopped doing that for simplicity) have failed and cases where we didn't, say at leas ipv4 or ipv6 should have succeeded. But we the current and future design this doesn't make sense anymore.

What this brings up, with current or future design is we need to think what the client would consider a "failed" state. For example given the routes we **need** to have at least one sentinel DNS route, but the client has not knowledge of what routes are sentinels. And there are other routes that have such consideration and not handling that could mean a degraded UX, i.e., someone starting Firezone and thinking it's working while it's not and preventing all internet connections.

But overall I think this would be a good change.

**Comment by thomaseizinger** [comment]
Unless I am misunderstanding the code we have today, then any error from the callbacks will only be logged because any `Err` returned from `Tunnel::poll_next_event` is just logged (now in the `Eventloop` and previously in the `ControlPlane`).

From that, I'd conclude that we can remove that return value now to make it more obvious that this can't really fail. For example, none of _actual_ callbacks in Swift return a `Result` so those are always "successful". I am not sure what happens if the swift side throws an exception.

On Android, we do catch the exception and return it as an error but again, those are only logged in the `Tunnel` which is confusing to reason about.

> What this brings up, with current or future design is we need to think what the client would consider a "failed" state. For example given the routes we **need** to have at least one sentinel DNS route, but the client has not knowledge of what routes are sentinels.

We can easily make the clients have knowledge about that though, right? We just need to send two different lists of routes and the clients can chose to disconnect the tunnel if the "critical" one fails.
