### ISSUE TITLE
doc: Ubuntu dependencies

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4083]
# appindicator

To launch Firezone, Ubuntu 20.04 needs

```bash
sudo apt-get install \
libayatana-appindicator3-1 \
libayatana-indicator3-7
```

~~But even then, the tray icon doesn't show up. (#4053)~~

(The tray icon bug was caused by sudo. #3713 will fix it)

# ~~FUSE~~

(Don't worry about FUSE. It's needed for AppImage, and we aren't gonna ship AppImages)

**Comment by thomaseizinger** [comment]
I think we need a lot more than that: https://github.com/firezone/firezone/blob/b668f8944bfdc3018c924008ebe1c1b57c6cb912/scripts/nix/flake.nix#L20-L43

Not all of these are runtime dependencies though.

**Comment by ReactorScram** [comment]
I ran `dpkg --info` on a release deb and got this:

- `libayatana-appindicator3-1`
- `libwebkit2gtk-4.0-37`
- `libgtk-3-0`

And installing those works on my test VMs for Debian and Ubuntu 20.04

**Comment by ReactorScram** [comment]
Closing in favor of #4873
