### ISSUE TITLE
Investigate why eur-west1-d Relay is being offered to client in NE

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4088]
Follow up from #3979 and [the discussion on Slack](https://firezonehq.slack.com/archives/C04HRQTFY0Z/p1710191360930539).

In this particular case, the Client is located in the New Jersey, US and the Gateway near the west coast (Nevada).

The eur-west1-d (Belgium) Relay is being consistently provided to the client to connect to when it seems like a Relay near the US west coast or east coast should be used instead.

**Comment by jamilbk** [comment]
Issue is not enough geographically-distributed Relays. Closing as dupe of #4043

**Comment by AndrewDryga** [comment]
@thomaseizinger I bet you want to know this: right now we return to the client two geographically nearest relays, which means in US East you can get one relay in US East and one in EU West easily. I guess there is nothing we are doing to pick the one that is better between those two so we will just use one of them at random?

**Comment by jamilbk** [comment]
Just had another thought on this: if the gateway and client pick **different** Relays, our bandwidth bill is doubled. May be worth a cost optimization down the road, not a major issue to work around now.
