### ISSUE TITLE
Handle errors returned from FFI calls

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#4107]
Currently we assume on all platforms that most calls succeed. For example, [`on_update_routes`](https://github.com/firezone/firezone/pull/3825#discussion_r1510478890).

We should respond with error cases for calls that can fail and react accordingly, even if it's just ignoring the error.

- [ ] Android: buildVpnService can return null `fd` if not successful
- [ ] `on_update_routes`, `on_set_interface_config`, etc

**Comment by thomaseizinger** [comment]
Our FFI no longer has errors.
