### ISSUE TITLE
MacOS: re-consider automated re-connects from the app side

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4138]
Connlib has its own internal re-connection mechanism to the portal. Whilst debugging a crash-loop of the MacOS app with @conectado , we discovered that there is an additional re-connect loop on the swift side.

Do we necessarily need that? It seems like we should map 1 user action of clicking sign-in to 1 call to `Session::connect`. That should greatly simplify the app and from wearing my user hat, that is what I'd expect it to do. `connect` only fails on errors that connlib deems non-retryable (otherwise we would just retry internally).

**Comment by conectado** [comment]
I second removing this from all apps. We should either re-try connections from connlib or client and right now it makes more sense to do that from connlib.

Exceptions such should leave firezone in a disconnected state and make them obvious.

**Comment by conectado** [comment]
cc @jamilbk

**Comment by jamilbk** [comment]
Yeah this is probably a remnant from an earlier design.

However, keep in mind the tunnel start can fail before connlib is ever loaded (rare). This is true for Android too.

To keep things simple, we can just stay disconnected instead of retrying.

@roop designed this IIRC in the Apple clients, not sure if I'm missing something.

**Comment by thomaseizinger** [comment]
> However, keep in mind the tunnel start can fail before connlib is ever loaded (rare). This is true for Android too.

If it is rare, then it doesn't sound like it is worth keeping the retry complexity around. Sounds more like a bug that would need fixing.

Can we rely on the user to retry in these situations? Would also be nice to get a crash report so we can see why it failed.

**Comment by jamilbk** [comment]
I'll clean this up in a subsequent PR to #1735
