### ISSUE TITLE
"Waiting for Gateway connection..." changes to "Connected!" with an already-deployed Gateway in the Site

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4170]
- Deploy a Gateway in a new Site
- Deploy another Gateway in the Site, notice that before connecting the new Gateway, the button changes state prematurely because I think it detects the already-deployed Gateway is connected. The second Gateway hasn't been deployed.

**Comment by AndrewDryga** [comment]
Its already fixed in filtering PR
