### ISSUE TITLE
AzureSigning tool fails to install in CI

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4185]
Is currently blocking CI on all PRs and main: https://github.com/firezone/firezone/actions/runs/8319140155/job/22762247052?pr=4168

**Comment by jamilbk** [comment]
This is failing because AzureSignTool released a new version that doesn't seem to work on the GitHub actions runner because I think it doesn't have .NET 8 installed.

Will fix shortly.

**Comment by jamilbk** [comment]
Yeah, the windows-2019 runner [doesn't have](https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md#net-core-tools) .NET 8:

> .NET Core SDK: 6.0.127, 6.0.203, 6.0.321, 6.0.419, 7.0.116, 7.0.203, 7.0.313, 7.0.406
