### ISSUE TITLE
Add select with live search component to replace dropdowns with all groups/resources

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#4186]
The dropdowns for group/resource IDs can be huge (some accounts have thousands of groups synced from IdP) and `Actors.all_groups!/1`/`Resources.all_resources!/1` to render those take a bit of time. Only good way to address this would be to only fetch first 25 groups or so and allow to use live search to find others.

**Comment by jamilbk** [comment]
cc @bmanifold I think this was something brought up your notes

**Comment by bmanifold** [comment]
@jamilbk, yep.

@AndrewDryga, I'm wondering if fetching the first 25 is even necessary.  If you think about `groups` as an example, we've already seen accounts where they have many more groups than 25 and in those instances there would be a very negligible percentage chance of finding what you need in that first 25 that would be shown in the list.  Even if you had 50 groups, you'd only be looking at a 50/50 chance of seeing what you need.  If that's the case, my mind goes to just providing a search box and letting the user search for what value they want.
