### ISSUE TITLE
connlib: actively invalidate candidates when interfaces change

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4243]
Based on the capabilities of the clients, it would be useful to add APIs that tell connlib early that a certain interface (and its IP) is now down or up.

Or maybe we want to consider adding `if-watcher` back? Especially _invalidating_ an interface should greatly speed up failover because we don't need to wait for the ICE timeout.

**Comment by thomaseizinger** [comment]
> because we don't need to wait for the ICE timeout.

This is because invalidating a candidate will cause str0m to instantly try and nominate a new one.

**Comment by thomaseizinger** [comment]
Actually, I think we should be able to do this internally by invalidating the srflx candidate.

**Comment by jamilbk** [comment]
`reconnect` already handles this no? IMO we should invalidate all other interface's candidates when we get a primary interface change. We only read primary interface DNS servers and only use host addresses from the primary interface... it's not that the best path will continue to be the old interface when the system has decided on a "better" default interface.

Mobile OSes especially do this, they have quite complex rules to determine which interface to use, in some cases exposing a knob to the user to control.

I.e. if I switch from cellular to WiFi I would expect connlib to switch over my Firezone traffic too.

**Comment by thomaseizinger** [comment]
> Actually, I think we should be able to do this internally by invalidating the srflx candidate.

We now do this so this can actually be closed :)
