### ISSUE TITLE
refactor(gui-client): panic in network change listener instead of using the `close` function

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4247]
Next step: No rush, we can do this refactor next time that code changes.

Per me and Gabi agreeing here https://github.com/firezone/firezone/pull/4198#discussion_r1533123407

This needs to be inlined into `Drop` and the errors replaced with panics https://github.com/firezone/firezone/blob/b0904e382ac9c08af6ff9005700c490eff38ad84/rust/gui-client/src-tauri/src/client/network_changes/windows.rs#L231

**Comment by ReactorScram** [comment]
@conectado I have a local branch for this, but I still don't quite like it. If I have `close` then it's easier to control when everything shuts down, e.g. I can make sure the logger is still up to log errors while everything else is closing down.

I think there is some precedent for this in the Rust ecosystem, like `UnixStream` closes itself on Drop, but it also has an async `shutdown` method to send a close signal and return a `Result`: https://docs.rs/tokio/latest/tokio/io/trait.AsyncWriteExt.html#method.shutdown

**Comment by jamilbk** [comment]
I'm doing a grooming sweep -- still relevant?

**Comment by ReactorScram** [comment]
Not really. I think the current design achieves both goals: (https://github.com/firezone/firezone/blob/184c982d756076734ae62ae4ec463b91b0e4bec8/rust/gui-client/src-tauri/src/client/network_changes/windows.rs#L243)

- `Drop` automatically calls `close` and panics if anything goes wrong
- You can manually call `close` and then the caller can decide how to handle any errors
