### ISSUE TITLE
bug(ci): Windows GUI client is not in the release assets for the draft release

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4248]
#### Describe the bug

Windows MSI installer is not in the assets list

#### To Reproduce

Go to the draft release, the Windows GUI client doesn't seem to be there

#### Expected behavior

Expected the Windows MSI installer to be there, since the Linux CLI client is too.

#### Screenshots / Logs

(This link will invalidate on the next merge) https://github.com/firezone/firezone/releases/tag/untagged-2325a83e0d02891ac838

The last merge was 50 minutes ago and it came up green, so it should have had time to build and publish the MSI:

![image](https://github.com/firezone/firezone/assets/13400041/c2ca4246-e89d-474b-8c50-cccec338c01a)

![image](https://github.com/firezone/firezone/assets/13400041/46145236-8355-40b6-adff-2486b8a1ec68)

#### Platform (please complete the following information)

N/A

#### Additional context

It definitely called CI and ran the build job for Tauri: https://github.com/firezone/firezone/actions/runs/8378555286/job/22943390176

But `$TAG_NAME` was not set.

This might be a bug in the `upload-windows.sh` script, I'll see if I can get it, but I'm not sure.

For comparison, here's a successful upload from 3 weeks ago before the big CI refactor: https://github.com/firezone/firezone/actions/runs/8134733605/job/22228485128#step:10:1

https://github.com/firezone/firezone/commit/8c59ff7aa1a50b9ad86a8afd446852a3999f86dd

**Comment by ReactorScram** [comment]
Darn, `$TAG_NAME` is fixed but it still didn't upload somehow https://github.com/firezone/firezone/actions/runs/8382215105/job/22955539118#step:14:20

![image](https://github.com/firezone/firezone/assets/13400041/1a2b0de7-daf0-46d2-a510-0673da67a6c9)

**Comment by jamilbk** [comment]
~~Hm, I think I know -- I don't think we're uploading the tauri build anywhere in CD.~~

Edit: nevermind.

**Comment by ReactorScram** [comment]
Maybe I got the `if` directive wrong? It doesn't look like it's even trying to upload either of the Tauri builds https://github.com/firezone/firezone/actions/runs/8382215105/job/22955539118#step:14:1

But I thought if Github skipped it, it would be a different symbol than the checkmark.

But if the script ran, why didn't it print any error?

**Comment by jamilbk** [comment]
Looks like the script ran but didn't print an error... Might need -x on it.

**Comment by ReactorScram** [comment]
#4256 fixed it
