### ISSUE TITLE
bug(windows): Spurious TunnelReady notifications

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4272]
#### Describe the bug

When I sign in, I get 3 "Connected to Firezone" messages in a row. These are only showed when the Client gets the `on_tunnel_ready` callback.

I also get one "Connected to Firezone" when switching between home Wi-Fi and the iPhone's hotspot Wi-Fi.

#### To Reproduce

- Build the Windows Client from the tip of main
- Sign in. You will see more than 1 notification
- Change Wi-Fi networks so that DNS changes or Internet goes down/up or something. You will see another notification

#### Expected behavior

Expected 1 "Connected" message when I sign in. If I change from one Wi-Fi that has Internet to another, I expect no notification.

#### Screenshots / Logs

I saved `connlib-2024_03_22-12-47.zip`. There might be sensitive data, so I can post it in Slack or something.

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 1.0.0-pre.10-268-g141253fe1
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Built from source

#### Additional context

Probably a result of the recent network change work and refactoring

Since this affects Windows on `main` I will look into it pretty soon.

I can put upstream DNS servers in `tracing::debug!`, right? They might be considered private, but debug won't be written to log files for customers with the default filter.

**Comment by thomaseizinger** [comment]
As mentioned somewhere else, we call this more often now when DNS servers are updated.

My recommendation would be:

- Don't listen for on-tunnel-ready
- When you get an on-interface-config-changed event, it means we have a TUN device and can start routing packets

You can flip a flag for the notification after the first call and reset it when you call `reconnect`. Eventually it would be nicer if you don't have to flip your flag on `reconnect` but connlib tells you with an event that we are disconnected / reconnecting.

It is easier to manage if connlib is the source of truth and you don't need to actively manage state. WIP :)

**Comment by jamilbk** [comment]
FWIW the Apple clients don't have on_tunnel_ready anymore, just noting here. We can remove it from Android too probably.

**Comment by jamilbk** [comment]
refs #4262

**Comment by ReactorScram** [comment]
Closing in favor of #4305 right?
