### ISSUE TITLE
Relay candidates seem to be chosen even when direct exists

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4290]
I occasionally (1 out of 4 or 5 times) see that connections to a gateway in the test net (an adjacent subnet to my local home LAN) settle on US-west relay. The remaining times they're direct (~~hairpinning off my local router or ISP first hop router~~ Edit: actually it sometimes even picks the direct LAN ip using host candidates).

When this happens, pings to the gateway are around ~35ms instead of the usual ~3ms (with little variation).

I'll keep an eye out for capturing logs, just noting this issue down.

**Comment by thomaseizinger** [comment]
Related and possibly obsolete after https://github.com/firezone/firezone/issues/4164.

**Comment by jamilbk** [comment]
See #4358 for log capture

**Comment by thomaseizinger** [comment]
Closing as outdated.
