### ISSUE TITLE
Add Team plan

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4306]
- Adjust starter counts
- Add "Team plan", communicate limits to @AndrewDryga 
- Make website changes
- Ensure they don't get IdP sync

```[tasklist]
- [ ] Check the billing with a real card after Sign Up's are enabled
- [ ] Double-check enabled payment methods
- [ ] Double-check all plans content (features, name, descriptions, prices) and make it up to date with the information we show on the website
- [ ] Check plan changes with a real card
```

**Comment by AndrewDryga** [comment]
@jamilbk I've added Team plan on Stripe end and configured the portal, you need to update the metadata (name, description, features list). Also check accepted payments method and maybe enable/disable some of them: https://dashboard.stripe.com/settings/payment_methods?config_id=pmc_1KOrs4ADeNU9NGxv6A3QtZNn
