### ISSUE TITLE
Shareable link "Not authorized" error when accessed by non-privileged user

### ISSUE THREAD

**Issue by anortiz08** [CloudFire-LLC/cloudfire#431]
Following the creation of a new device and generating a shareable link, when the user attempts to access the link, they are prompted to authenticate and, upon successful authentication, receive the following error:

![image](https://user-images.githubusercontent.com/15962187/152254198-3248c709-0bce-4ecf-b284-2a7ffa46914f.png)

**Comment by jamilbk** [comment]
Thanks for reporting! Looks like the authorization logic is kicking in when it shouldn't be. I'll have a fix out momentarily.

**Comment by jamilbk** [comment]
@anortiz08 This has been fixed in master and will roll out with the next release in a few hours.
