### ISSUE TITLE
bug(apple client): can't sign in

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4321]
#### Describe the bug

I can't sign in on my Macbook

#### To Reproduce

I try to sign in. The webview opens, I click "Firezone" and "Google Workspace" as usual. It says, "You may close this window" and auto-closes as usual.

Then the icon animates for a while, and it says "Signed in, resources unavailable, connecting..." and eventually goes back to signed-out state.

#### Expected behavior

Sign-in should succeed

#### Screenshots / Logs

https://firezonehq.slack.com/archives/C04JR58F7ND/p1711414860003079?thread_ts=1711413805.387969&cid=C04JR58F7ND

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (1711413647)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ macOS Sonoma
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

Was this the bug that was mentioned about the NetworkExtension needing to be cycled during updates? That should only be for local builds, not CI/CD builds, even in TestFlight, right?

**Comment by jamilbk** [comment]
> Was this the bug that was mentioned about the NetworkExtension needing to be cycled during updates? That should only be for local builds, not CI/CD builds, even in TestFlight, right?

Hmm, hard to say. It does seem like your NetworkExtension is crashing, but working fine on my end.

I'll see if I can reproduce. IIRC this has happened a couple times in the wild. I think regular App Store updates happen when the user is not active, and restart the application in question. Maybe Test Flight auto updates are more aggressive.

**Comment by ReactorScram** [comment]
Hm still having it with "Version 1.0.0 (1711416021)"

I've been doing manual updates in TestFlight.

**Comment by jamilbk** [comment]
Could you post logs again? That build has some more error logging.

**Comment by ReactorScram** [comment]
https://firezonehq.slack.com/archives/C067DSY7TFX/p1711475586518129

I also swapped between prod and staging at some point. Not sure which one I should be on for TestFlight, but staging has the resources I've set up for dogfooding.
