### ISSUE TITLE
bug(ci): Staging gateway was down for maybe 30 minutes

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4331]
#### Describe the bug

This might be more like an incident report.

I opened #4329 thinking that my Linux Client had a bug, but actually the staging gateway was down and so I couldn't contact any resources.

I think this happened because this CD job failed and left the gateway un-deployed: https://github.com/firezone/firezone/actions/runs/8443528430/job/23127530331

The job may have failed because of an AWS incident in us-east-1 around the time this happened: https://health.aws.amazon.com/health/status?eventID=arn:aws:health:us-east-1::event/EC2/AWS_EC2_OPERATIONAL_ISSUE/AWS_EC2_OPERATIONAL_ISSUE_19EDD_8784715220E

#### To Reproduce

Not sure. Fail a Terraform deploy in CD?

#### Expected behavior

Expect one of these conditions to always be met:
- The staging gateway is up, or
- The gateway is being replaced with a new version, or
- We get some actionable notification if it's down for 5 minutes

Maybe there was a notification - I have the `#feed-staging` channel muted because the Terraform messages don't make sense to me. If there was a notification, I don't think I would have understood it.

#### Screenshots / Logs

None

#### Platform (please complete the following information)

N/A

#### Additional context

https://firezonehq.slack.com/archives/C04HRQTFY0Z/p1711492766428859

**Comment by jamilbk** [comment]
I think it was one of the recent changes to the PhoenixChannel heartbeats. See the gateway logs (uptime 2 hours, still not connected). If I simply restart the gateway it connects.

[logs.txt](https://github.com/firezone/firezone/files/14768255/logs.txt)

**Comment by thomaseizinger** [comment]
> I think it was one of the recent changes to the PhoenixChannel heartbeats. See the gateway logs (uptime 2 hours, still not connected). If I simply restart the gateway it connects.
> 
> [logs.txt](https://github.com/firezone/firezone/files/14768255/logs.txt)

I think I know where the bug is. We need to reset the `Heartbeat` struct when we re-connect, otherwise we will constantly fail it :sweat_smile:

**Comment by thomaseizinger** [comment]
> > I think it was one of the recent changes to the PhoenixChannel heartbeats. See the gateway logs (uptime 2 hours, still not connected). If I simply restart the gateway it connects.
> > [logs.txt](https://github.com/firezone/firezone/files/14768255/logs.txt)
> 
> I think I know where the bug is. We need to reset the `Heartbeat` struct when we re-connect, otherwise we will constantly fail it 😅

Actually no, that is not the issue. The delay resets itself automatically on error. And the logs are all 1 minute apart which makes me think that we get at least 1 heartbeat in-between. It appears that the portal does in fact not respond to the heartbeat.

It would be useful to have `wire` logs here to see which messages we actually exchange with the portal.

**Comment by jamilbk** [comment]
> does in fact not respond to the heartbeat.

@AndrewDryga Is it possible there's some kind of rate limit or blacklisting happening to a gateway that reconnects too eagerly?

**Comment by jamilbk** [comment]
It's also possible that the PhoenixChannel API changed on the Elixir side, though not likely.

**Comment by AndrewDryga** [comment]
@jamilbk Phoenix did not have any breaking changes and we don't have any rate limits at this moment, I don't see any error logs, so I don't think it was something on the portal side.

**Comment by jamilbk** [comment]
I think we can safely chalk this up to being caused by the deploy pipeline being held up and then the issue mentioned in #4348.
