### ISSUE TITLE
bug(apple client): crashing without error log in `session.setDns`

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4350]
#### Describe the bug

This was probably the cause of #4321

#### To Reproduce

Run Firezone and sign in, the tunnel crashes and never changes from "Loading resources" to the actual signed-in state

#### Expected behavior

Expected:
- To be able to sign in
- Crashes to result in logs

#### Screenshots / Logs

Don't have any yet

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ macOS Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ ab35a5ea762e0
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ macOS Sonoma 14.3.1
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Built in XCode

#### Additional context

Jamil knows about this

**Comment by ReactorScram** [comment]
`dns_servers="[\"fe80::96a6:7eff:fe78:edb7%en7\",\"192.168.1.1\"]"`

IPv6 scopes strike again

**Comment by conectado** [comment]
Fixed by #4353
