### ISSUE TITLE
site-webmanifest not found 

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4383]
These are used to install app shortcuts on mobile devices mostly. Probably a quick fix, if not I'll just remove it.

<img width="762" alt="Screenshot 2024-03-28 at 2 14 23 PM" src="https://github.com/firezone/firezone/assets/167144/48b61862-775a-4b4f-9a82-ac143c204985">

**Comment by AndrewDryga** [comment]
The same issue happens for `<link rel="icon" href="/favicon-aa12384fc0d056702cebe048b69d1bd7.ico?vsn=d" sizes="any">`. Let me check if there is a way to fix it by configuring the `phx.digest`.
