### ISSUE TITLE
ci(apple): CI/CD check for forbidden syscalls like `fstat`

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4393]
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://github.com/Wooder/ios_17_required_reason_api_scanner/tree/main

**Comment by jamilbk** [comment]
I managed to prune out all of our dependencies on `fstat`, but rustc still links against `libSystem` at the end of the day, which pulls in `fstat` and `stat`, so this CI check won't be that useful.

#4400 should eliminate the need for this CI check.
