### ISSUE TITLE
GA throughput improvement

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4406]
We haven't yet focused on performance, and it's probably too early to go super deep here, but we should do a first pass to see if there's any low-hanging fruit we can find to improve throughput.

## What to test (in order of priority)

- [ ] Relay: We're able to trigger CPU alarms (> 0.800 load) with a single stream (~100 Mbps) on an f1-micro instance (0.2 CPU). We could bump up the CPU size, but that will only make it harder to find issues. I tested running a speedtest from within an `f1-micro` instance and it looks like it's able to saturate Mbps:
- [ ] Gateway, both docker and systemd (I presume results should be similar)
- [ ] Clients: macOS, Linux, and Windows are probably the best places to start (desktop OSes)

## How to test (WIP)

Cloudflare's speed.cloudflare.com is certainly one way to test, but I think a more consistent test would be to simply `scp` a 10GB file of random data.

This is using the perf test gateway on Prod, which is recent as of about 2 days ago (it's manually upgraded).

Here is how I performed this test:

```bash
# 10GB
dd if=/dev/urandom of=./random bs=1m count=10000
scp random <gateway host/ip>:~/
```

I tested with both IPv6 and IPv4 terminated at the client and gateway, all with similar numbers. 
Settles at about 2 MB/s. Apple build 1711778711.

<img width="267" alt="Screenshot 2024-03-30 at 8 54 00 AM" src="https://github.com/firezone/firezone/assets/167144/5157beb8-a96f-4aed-a7c3-95bfdebb7318">

## CPU Usage
CPU usage is quite low still but a little higher than I'd expect:

#### client
<img width="307" alt="Screenshot 2024-03-30 at 8 58 56 AM" src="https://github.com/firezone/firezone/assets/167144/28c28e5c-cd02-4187-8349-ba37143ec475">

#### gateway

<img width="249" alt="Screenshot 2024-03-30 at 8 59 20 AM" src="https://github.com/firezone/firezone/assets/167144/4174e19a-12c3-4dcf-9734-dc153600eb02">

---

Without Firezone I get about 150 MB/s or ~1250 Mbps and `scp` uses about 50% CPU on both ends.

**Comment by jamilbk** [comment]
Happy to test again after #4398 is merged, but I'm not sure if that will make a difference.

**Comment by thomaseizinger** [comment]
At the moment, we only read packets from the UDP socket using a single buffer: https://github.com/firezone/firezone/blob/439b9704b1f5b09b3e4da59f1d68377a88625998/rust/connlib/tunnel/src/sockets.rs#L256-L264

I think this limits us to only read packets coming from 1 destination at a time (because that is stored in `Meta`). We should scale that up to 32 or something (that is what `quinn` uses) and see if it improves throughput.

**Comment by thomaseizinger** [comment]
Another thing that might need optimisation is the order in which we de-multiplex traffic in `snownet`. At the moment, we mostly go by `SocketAddr` of in the incoming packet here: https://github.com/firezone/firezone/blob/439b9704b1f5b09b3e4da59f1d68377a88625998/rust/connlib/snownet/src/node.rs#L270-L298

In a high-throughput scenario, these hashmap looks-up might actually become a bottleneck. We should be able to optimise this by looking at the first couple of bytes of the message:

- `0..=3`: STUN message, thus either for an `Allocation` or an `IceAgent` in a connection
- `64..=79`: Channel data message: Definitely for an `Allocation`
- other: Either a wireguard packet or garbage

This should allow us to fast-path the packet routing which might improve throughput. At least in the relay, hashmap look-ups are the next bottle-neck together with syscalls for reading and writing packets.

**Comment by jamilbk** [comment]
The bottleneck here was verified to be IOPS without any low-hanging fruit left to optimize.
