### ISSUE TITLE
Admins count as a seat

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4413]
Could just be a minor UI update to add `1` to the seats used / allowed

<img width="635" alt="Screenshot 2024-03-31 at 8 49 01 AM" src="https://github.com/firezone/firezone/assets/167144/328eb2e3-1506-44f8-bcb0-e452bdafec8d">

**Comment by AndrewDryga** [comment]
@jamilbk this means the admin did not ever sign in to the client and since we have separate limits we don't count is as active user for future MAU billing

**Comment by jamilbk** [comment]
That's fine, I think we can assume `activeUser: bool = isAdmin? || signedInRecently?`
