### ISSUE TITLE
Unable to add CIDR resources.

### ISSUE THREAD

**Issue by Taner314** [CloudFire-LLC/cloudfire#4449]
#### Describe the bug

Then you try to add CIDR resource, it wouldn't allow you to. Instead, it silently throws error into browser console and does nothing.

#### To Reproduce

1. Log into app.firezone.dev
2. Try to add CIDR resource

#### Expected behavior

CIDR resource is added.

#### Screenshots / Logs

Browser console log:
`An invalid form control with name='resource[address_description]' is not focusable. <input type=​"text" name=​"resource[address_description]​" id=​"resource_address_description" class=​"bg-neutral-50 p-2.5 block w-full rounded border text-neutral-900 text-sm phx-no-feedback:​border-neutral-300 disabled:​bg-neutral-50 disabled:​text-neutral-500 disabled:​border-neutral-200 disabled:​shadow-none border-neutral-300 border-rose-400" required placeholder=​"xxx.xxx.xxx.xxx/xx" value>​`

#### Platform (please complete the following information)

- Component: Admin portal
- Firezone Version: N/A
- OS and version: N/A
- Deployment method: N/A

#### Additional context

It is possible to bypass this error by manually setting address description in elements.
Was tested in: 
- Microsoft Edge Version 123.0.2420.65 (Official build) (64-bit)
- Firefox browser 124.0.1 (64-bit)

**Comment by ReactorScram** [comment]
@Taner314 Is this still happening for you?

**Comment by Taner314** [comment]
No, as of now it's fixed.
