### ISSUE TITLE
relay: attempt to move back to `Instant` from `SystemTime`

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4464]
Discovered in https://github.com/firezone/firezone/pull/4455#discussion_r1548552244.

**Comment by thomaseizinger** [comment]
I just tried this and the problem is our authentication scheme. The TURN credentials which we generate have an embedded UNIX timestamp that indicates for how long they are valid. I cannot compare that to an `Instant` because `Instant`s can only be compared against each other.

It might be possible to only use `SystemTime` for the auth scheme and `Instant`s everywhere else?

cc @ReactorScram

**Comment by ReactorScram** [comment]
@thomaseizinger Yeah that's what I was thinking. `SystemTime` is needed over the network but that should only be 1 or 2 places in the auth code, everything else should be `Instant`

I suppose if there's auth code embedded in something else you can pass both 🤔 not familiar enough with the code to know

**Comment by thomaseizinger** [comment]
I think I managed to do something neat in the above linked PR :)
