### ISSUE TITLE
Re-add AppLinks to Android app

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4479]
Refs https://github.com/firezone/firezone/issues/4442

The only we can reliably close a tab is to use Chrome CustomTabs and AppLinks.

See https://github.com/firezone/firezone/pull/2826 -- we basically need to revert that + clean things up.

**Comment by jamilbk** [comment]
This should improve UX by opening a auth sheet for sign in that gets auto-dismissed or closed after sign in, otherwise there's no point to this

**Comment by jamilbk** [comment]
@jasonboukheir Hold on this. We are reworking how we do redirects which should fix this issue for Android

**Comment by jasonboukheir** [comment]
Reopening to simplify testing the `CustomUriViewModel`

**Comment by jamilbk** [comment]
Closing until this is a priority.
