### ISSUE TITLE
bug(apple Client): github.com loading slow on macOS

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4480]
#### Describe the bug

When I turn on Firezone, Github often slows down.

#### To Reproduce

1. Turn on Firezone
2. Click around Github for a few minutes
3. It may work at first, but eventually page loads time out

#### Expected behavior

Expect network requests to either return quickly if the tunnel is up, or error out if the tunnel is down

#### Screenshots / Logs

https://firezonehq.slack.com/archives/C067DSY7TFX/p1712163087167669

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ macOS Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (1711778711)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Version 1.0.0 (1711778711)
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ TestFlight

#### Additional context

None

**Comment by ReactorScram** [comment]
(May have been caused by #4481

**Comment by jamilbk** [comment]
This is likely caused by the gateways flapping or simply being re-deployed, or the outage yesterday.

Going to close, if it continues to happen feel free to re-open
