### ISSUE TITLE
RFC: Opt-in Client metrics / telemetry for dev builds on dev machines

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4482]
#### Is your feature request related to a problem? Please describe.

During today's incident (need to cross-link) we weren't sure when the Gateways were most recently working

#### Describe the solution you'd like

Something outside of the logs that allows us to automatically record how the dogfooding is going without any chance for human error or forgetfulness.

- More like a set of data points than a string-based log, something you could graph in Prometheus
- Not deleted when the logs are cleared
- Only used on dev systems, so privacy is not a problem
- Machine-readable to find things like, "This new Client is slower" or "Staging quit working at this exact date and time"

This would give us a little bit of visibility / coverage into tricky platform-specific I/O things that are otherwise undertested or impractical to test properly in CI. CI can't do soak tests either.

#### Describe alternatives you've considered

This could come from the normal logs, but I usually clear my logs dir before replicating an issue, so that information is lost. The logs may also be either too verbose (using debug defaults) or too terse (using release defaults)

#### Additional context

_Add any other context or screenshots about the feature request here._

**Comment by jamilbk** [comment]
This might be a lot of work to add to the existing clients running on dev machines. Would #4506 deliver most of the value here?

**Comment by ReactorScram** [comment]
Let's do #4506 first. But for this I'd like to also catch I/O problems, since I/O for Linux is well-covered and for Windows is almost not covered at all.

Like right now I've still had to turn off my macOS Client because it was interfering with my UTM dev VM and music player. That isn't automatically captured anywhere.

**Comment by ReactorScram** [comment]
Might schedule later if it seems useful
