### ISSUE TITLE
Have different logging levels

### ISSUE THREAD

**Issue by WaxySteelWorm** [CloudFire-LLC/cloudfire#449]
It would be nice to see an option to change the level of information logged depending on a setting.

0 - No logs at all
1 - Minimal logs
2 - Normal logs
3 - Verbose

I run a non-profit organization focused on deploying privacy based tools. Having a VPN solution that could disable all logging would be an helpful addition.

**Comment by jamilbk** [comment]
@WaxySteelWorm Thanks for the suggestion! Would this be to disable just the WireGuard connection logs or all service logs? The former should be straightforward. The latter still doable but a little more involved.

**Comment by WaxySteelWorm** [comment]
> @WaxySteelWorm Thanks for the suggestion! Would this be to disable just the WireGuard connection logs or all service logs? The former should be straightforward. The latter still doable but a little more involved.

@jamilbk I believe the setting should cover both WireGuard and FireZone. As a privacy based organization I would like to run VPN services without any logs being generated.

**Comment by jamilbk** [comment]
Understood. I’ll queue this into our backlog for the next release.

**Comment by jamilbk** [comment]
@WaxySteelWorm So having different log levels is a much larger task. We need to define what each of these log levels mean in the context of our 4 services (`nginx`, `postgresql`, `phoenix`, `wireguard`). That's going to require some thought and adding logic to the main application to conditionally log certain operations or not.

In the meantime, I've [added support for disabling logging entirely in the 0.2.17 release](https://github.com/firezone/firezone/releases/0.2.17).

Simply ensure `default['firezone']['logging']['enabled'] = false` is in your `/etc/firezone/firezone.rb` and you shouldn't see any logging statements printed anymore to the log files in `/var/log/firezone`.

Keep in mind you can set `default['firezone']['log_directory'] = /tmp` or some other ephemeral directory and that will prevent any logs from hitting the disk.

Let me know if this works for you.

**Comment by WaxySteelWorm** [comment]
@jamilbk I believe that will work, once a 0.2.17 deb installer is uploaded I can upgrade and test out the new release.

**Comment by WaxySteelWorm** [comment]
> @WaxySteelWorm So having different log levels is a much larger task. We need to define what each of these log levels mean in the context of our 4 services (`nginx`, `postgresql`, `phoenix`, `wireguard`). That's going to require some thought and adding logic to the main application to conditionally log certain operations or not.
> 
> In the meantime, I've [added support for disabling logging entirely in the 0.2.17 release](https://github.com/firezone/firezone/releases/0.2.17).
> 
> Simply ensure `default['firezone']['logging']['enabled'] = false` is in your `/etc/firezone/firezone.rb` and you shouldn't see any logging statements printed anymore to the log files in `/var/log/firezone`.
> 
> Keep in mind you can set `default['firezone']['log_directory'] = /tmp` or some other ephemeral directory and that will prevent any logs from hitting the disk.
> 
> Let me know if this works for you.

Sorry for the delay, so I did some testing today on 0.2.17 and it appears that logs are still being sent to 

/var/log/firezone/nginx/access.log - Contains IP address
/var/log/firezone/phoenix/current - Contains token and user agent details

**Comment by jamilbk** [comment]
@WaxySteelWorm Sorry! Completely missed your reply on this. Hmm, checking a bit further, I'm unable to reproduce what you're seeing. Here's what I've done:

1. Set `default['firezone']['logging']['enabled'] = false` in `/etc/firezone/firezone.rb`
2. Remove current logs: `sudo rm -rf /var/log/firezone`
3. Reconfigure application: `sudo firezone-ctl reconfigure`
4. Restart services: `sudo firezone-ctl restart`

I did notice an issue with the WireGuard logs still coming through though, so I'm cutting release 0.2.22 to fix that issue.

**Comment by jamilbk** [comment]
@WaxySteelWorm See https://github.com/firezone/firezone/pull/490

**Comment by WaxySteelWorm** [comment]
> ly on this. Hmm, checking a bit further, I'm unable to reproduce what you're seeing. Here's what I've done:

That is my bad I did not reconfigure application after setting changed. Thank you for working on this :)

**Comment by jamilbk** [comment]
Closing this. Will open another issue for different logging levels, but this might be the domain of the logging backend.
