### ISSUE TITLE
Deploy Linux client with monitoring VM in staging GCP

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4506]
It would be helpful to know as soon as possible if we've deployed something that causes core client functionality to fail.

We could do this by deploying a Linux client in staging that performs some basic checks and writes errors to `STDERR` so they're picked up by GCP monitoring.

Basic checks could be:

- Ping an IP resource periodically
- Ping hosts within a CIDR resource periodically
- Ping DNS resource periodically
- `curl` or `scp` a non-trivial file periodically
- run an iperf3 periodically and report output

A good log level to start might be:

```
firezone_linux_client=trace,connlib_client_shared=trace,firezone_tunnel=trace,connlib_shared=trace,boringtun=debug,snownet=debug,str0m=debug,info
```

We could deploy two clients to start:

- One that can hole-punching connections (should happen automatically)
- One that's forced to use a Relay with iptables rules that block direct coms with the staging gateways.

**Comment by jamilbk** [comment]
@bmanifold WDYT? I was thinking this might be the best return on investment in terms of effort required to catch yesterday's issue and even performance / other issues eventually.

We could even deploy 10 or 100 clients if we want to test scale.

**Comment by bmanifold** [comment]
Yeah, this would probably be a good start.  Scale test might be interesting, but definitely think the focus right now should just be on connectivity testing.

**Comment by jamilbk** [comment]
Might be good to check how feasible it is to host/deploy our static binaries and installer packages with Google Artifact Registry

**Comment by bmanifold** [comment]
I'm going to modify this to just be the monitoring VM itself and open another issue to add the monitors later, because I think it's going to take a little bit of time to figure out exactly what to alert on.

Created: https://github.com/firezone/firezone/issues/4801
