### ISSUE TITLE
Health check not reporting unhealthy status

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4510]
Add the heartbeat status to be factored into the Relay's reported health at `/healthz`

**Comment by thomaseizinger** [comment]
What is the expected behaviour here?

- Determine ourselves if we are healthy and return a 400 if not?
  - What is considered unhealthy? 1 missed heartbeat? N missed heartbeats?
- Return raw data? i.e time since last heartbeat?

**Comment by thomaseizinger** [comment]
https://cloud.google.com/architecture/best-practices-for-operating-containers#liveness_probe suggests that simply returing non-200 means unhealthy.

How do we define unhealthy? Missing a single heartbeat to the portal? What if we are currently reconnecting to the portal? How much partition time is okay until we say it is unhealthy?

Missing a heartbeat already means we reconnect to the portal. If we i nstantly flip to unhealthy whenever we are disconnected from the portal then we interrupt the dataplane on portal re-deploys.

If we set a max partiton time, then we can also just use that as the max partition time for the phoenix-channel. Upon reaching that, we will already fail the entire relay. I am not sure it is worth extending the health-check here. Seems redundant.

**Comment by thomaseizinger** [comment]
> Seems redundant.

It is my understanding that GCP will restart the relay as soon as the health check returns non-healthy.

**Comment by jamilbk** [comment]
I'm just the messenger here -- no strong opinion. Brought up during standup today by @AndrewDryga -- wdyt?

**Comment by jamilbk** [comment]
- If heartbeats aren't working, tell the liveness probe (don't return 200)
- Start liveness probe right away but don't return 200 until websocket is connected

With the above that should prevent Relays without healthy WS connections to the portal from being used.

**Comment by thomaseizinger** [comment]
- Fail health-check after same partition time as websocket when not receiving heartbeats
- Consider adding an additional check at the end of the eventloop
