### ISSUE TITLE
bug(relay): Relay VMs sitting at 50% CPU constantly

### ISSUE THREAD

**Issue by bmanifold** [CloudFire-LLC/cloudfire#4511]
After the incident/outage yesterday I quickly looked at the CPU usage graph on the Relay VMs and saw they were all sitting at 50% CPU usage while prior to the incident they were sitting much lower.  Here's a screenshot.

<img width="699" alt="Screenshot 2024-04-04 at 1 07 47 PM" src="https://github.com/firezone/firezone/assets/2646332/d4fe1273-8370-420d-ba06-a3fffbf94feb">

**Comment by ReactorScram** [comment]
Maybe fixed with the half-sleep in https://github.com/firezone/firezone/pull/4457/files#diff-c3200f3bb4414a260c930e656ddb673a1ad2a8ee292e508bfebf5dbf670c2b8dR198

**Comment by thomaseizinger** [comment]
Did #4457 make a difference on staging?

**Comment by bmanifold** [comment]
It looks like it did.

<img width="1300" alt="Screenshot 2024-04-04 at 5 36 11 PM" src="https://github.com/firezone/firezone/assets/2646332/bb987c15-0ce3-40b8-af88-6da30ec85d7d">

**Comment by thomaseizinger** [comment]
Awesome!
