### ISSUE TITLE
refactor(linux-client): use Tokio `codec` API for IPC

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4514]
What you want is a codec: https://docs.rs/tokio-util/latest/tokio_util/codec/index.html

That turns an `AsyncRead` into a `Stream` and allows you to read entire messages using `.next()`. It already comes with the codec you are implementing here: https://docs.rs/tokio-util/latest/tokio_util/codec/length_delimited/struct.LengthDelimitedCodec.html

_Originally posted by @thomaseizinger in https://github.com/firezone/firezone/pull/4465#discussion_r1550846660_

**Comment by thomaseizinger** [comment]
Happy to pair on this next week.
