### ISSUE TITLE
Unit test DNS on connlib

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#4560]
DNS `resource_intents` don't have any test coverage at the moment, should at least get some basic unit tests in.

**Comment by thomaseizinger** [comment]
Now that https://github.com/firezone/firezone/pull/4503 is merged, I am planning to work on some basic property-based tests tomorrow that attempt to connect a client and a gateway together, add a CIDR resource and send ICMP packets to it.

We can then use that as a baseline for doing the same with DNS resources.

I'll open a separate ticket to track that kind of work: https://github.com/firezone/firezone/issues/4589

**Comment by jamilbk** [comment]
I think this has been merged
