### ISSUE TITLE
Modify Shareable Link

### ISSUE THREAD

**Issue by WaxySteelWorm** [CloudFire-LLC/cloudfire#457]
Right now when you share a link it is only valid for 10 minutes.  This makes the feature not practical unless the administrator is working with the client/end user actively.

A better solution would be to have the time be configurable or have a this page can be viewed X number of times.

**Comment by jamilbk** [comment]
Thanks for the suggestion @WaxySteelWorm !

We're planning on dropping this feature in favor of allowing users to generate and download their own configs as part of #451 which will be in `0.3.0`. We'll be moving away from having device private keys on the server, so shareable links won't be possible anymore. Instead, a user would login (using the credentials you provided them) and then be able to download / generate their own configs from there.

Would that be suitable for your use case?

**Comment by WaxySteelWorm** [comment]
@jamilbk This would be perfect, ill go ahead and close this out.
