### ISSUE TITLE
Failing elixir unit test

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4586]
https://github.com/firezone/firezone/actions/runs/8641202346/job/23690335980?pr=4583

**Comment by thomaseizinger** [comment]
Seems to be a permanent error, here the 2nd run: https://github.com/firezone/firezone/actions/runs/8641202346/job/23692737104?pr=4583

**Comment by jamilbk** [comment]
I believe this may have been an infra or other issue that's now resolved.

Can reopen if it pops back up.
