### ISSUE TITLE
snownet: don't update socket based on WG activity

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4613]
When updating a socket via ICE, we invalidate all other candidates that are equal or worse in priority. We also update the socket on wireguard activity.

These states can in theory diverge which isn't good. We should always treat ICE as the source of truth for our socket.

**Comment by thomaseizinger** [comment]
I looked into this today and ran into some issues. You can see the failing test in https://github.com/firezone/firezone/actions/runs/8682303755/job/23806698516?pr=4615.

What ends up happening is that the test times out because we don't switch sockets fast enough. From ICE's point of view, the old socket is still active and we'd only switch over after the ICE timeout. I do believe that this is an upstream bug though. As the controlled agent (i.e. the gateway), we should just follow whatever the client nominates and not wait for the ICE timeout of the old candidate pair before switching over.

**Comment by thomaseizinger** [comment]
Working on #4615 made it more obvious that the idea of updating the socket from WG activity was a bad one. We should treat ICE as our source of truth and bend it such that it works for our usecase.

This "feature" was masking the above bug. I am not sure it is related to some of the odd behaviour we have been seeing but diverging state machines certainly sound like they could cause weird behaviour!

**Comment by thomaseizinger** [comment]
Upstream fix is here: https://github.com/algesten/str0m/pull/496

With the above applied, CI in https://github.com/firezone/firezone/pull/4615 is green.

**Comment by thomaseizinger** [comment]
> Upstream fix is here: [algesten/str0m#496](https://github.com/algesten/str0m/pull/496)

Damn, it is not as easy unfortunately. I think this means that our current strategy of _not_ doing an ICE restart and instead keep trickling candidates is a bit flawed. ICE restart is the event that both parties use to figure out that they are no longer using a certain socket. But a full on ICE restart is way to destructive because it also resets the credentials and invalidates all candidates.

**Comment by jamilbk** [comment]
> it also resets the credentials and invalidates all candidates

Invalidates candidates seems appropriate, though right? If we're actually roaming networks or changing our default interfaces, then I would expect the Direct candidates to no longer be valid because NAT has likely changed, but Relayed candidates should stick around?

If we're calling `reconnect` too eagerly that would be a source of woe

**Comment by thomaseizinger** [comment]
> > it also resets the credentials and invalidates all candidates
> 
> Invalidates candidates seems appropriate, though right?

Yes and no. If we invalidate all candidates in one go, then the connection "fails" and we clean up associated state like DNS resolutions. We could catch that by tracking more state on whether we just issued an ICE restart. Possible but makes things a bit more complicated.

> If we're actually roaming networks or changing our default interfaces, then I would expect the Direct candidates to no longer be valid because NAT has likely changed, but Relayed candidates should stick around?

Yes, that is correct. Also the relay candidates are dead because they are identified by the 3-tuple. 

> If we're calling `reconnect` too eagerly that would be a source of woe

That is the issue. We would have to be more careful in when we are calling this because it would trigger communication with the portal each time.

**Comment by thomaseizinger** [comment]
#4634 is a pre-requisite for this. We need to let the other party know that we've invalidated a candidate so that both sides can switch over to a new one without having to wait for the ICE timeout.
