### ISSUE TITLE
control-plane: introduce a message for invalidating candidates

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4634]
Currently, our control plane can:

- handshake a new connection by exchanging ICE credentials
- signal candidates to the other party

In several situations, we learn about _new_ candidates. For example, when we roam between networks, we discover new interfaces. Recently, we've been working on https://github.com/firezone/firezone/issues/4548 with the intent of allowing a client to migrate a connection between relays. From the perspective of ICE, this is kind of the same as roaming: An old candidate becomes invalid and a new one appears.

I think there is still a missing piece though: Signaling to the remote party that a candidate is no longer in use.

What currently happens is:

- Client learns about a new candidate and forms new pairs with all candidates from the gateway
- Gateway learns about the new candidate and also forms pairs and starts testing
- To avoid socket hopping, the gateway will not migrate to the new candidate pair right away unless the priority is better (i.e. relay -> srflx candidate)
- Client invalidates a local candidate and thus all candidate pairs that were formed with it.
- If the current nominated socket was part of the now invalid pairs, the next best one will be nominated immediately
- Gateway has no idea that the client invalidated the currently nominated socket and will keep testing it until the ICE timeout
- Gateway nominates the next best candidate

At the moment, we somewhat work-around this using https://github.com/firezone/firezone/issues/4613. However, for reasons stated there, I don't think it is a good idea.

My proposal is to add a new message to the control plane where we can signal to the other party to invalidate a certain candidate. Basically the inverse of signaling a newly discovered candidate. This would allow the gateway (or more generally, the other side) to discard the existing candidate pair and directly move to a new pair without having to wait for the ICE timeout.

At present, str0m doesn't have an API for this but it is easy to add in our fork, the maintainer is open to accepting it: https://github.com/algesten/str0m/pull/496#issuecomment-2058523877.

Related: https://github.com/algesten/str0m/pull/496.
Related: https://github.com/firezone/firezone/issues/4613.
Related: https://github.com/firezone/firezone/issues/4548.

**Comment by thomaseizinger** [comment]
@AndrewDryga @conectado Input please.

**Comment by thomaseizinger** [comment]
@AndrewDryga The message I'd need is:

```json
{
  "topic": "client",
  "event": "invalidate_ice_candidates",
  "payload": {
    "gateway_ids": [
      "b3d34a15-55ab-40df-994b-a838e75d65d7"
    ],
    "candidates": [
      "candidate:7031633958891736544 1 udp 50331391 35.244.108.190 53909 typ relay"
    ]
  },
  "ref": 6
}
```

So it is exactly like the messge for `broadcast_ice_candidates` but with a different name. Plus the same message from the gateway to the client.

**Comment by jamilbk** [comment]
@thomaseizinger Just so I'm aware where things are at -- is this the last piece of the #4548 puzzle or is there more needed you think?

**Comment by thomaseizinger** [comment]
It isn't strictly necessary. I think #4568 should fix #4548 by itself. That is because we currently rely on #4613 but I would like to remove that so we have a single source-of-thruth for our socket: ICE.

**Comment by thomaseizinger** [comment]
I've patched str0m now and got a passing unit-test that migrates a connection without running into the ICE timeout: https://github.com/algesten/str0m/pull/498

I am optimistic that this is a good idea.

**Comment by thomaseizinger** [comment]
@AndrewDryga We obviously also need a message from the portal to the gateway / clients that communicates the new candidates. Currently, I believe that message uses the event `ice_candidates`. It might be good to align that naming at some point but for now, we can just add another message `invalidated_ice_candidates`.

**Comment by thomaseizinger** [comment]
> So it is exactly like the messge for `broadcast_ice_candidates` but with a different name. Plus the same message from the gateway to the client.

It might be a bit too long but more correct would be to say: `broadcast_invalidated_ice_candidates`.

**Comment by thomaseizinger** [comment]
I've implemented this in https://github.com/firezone/firezone/pull/4615 where the control-plane is simulated in the unit-tests and it works :tada:

**Comment by jamilbk** [comment]
Awesome, this is great news. This was a blocker for wider rollout / marketing efforts.

Nice work.

**Comment by jamilbk** [comment]
Just waiting on the Apple client to pass review. Any day now...
