### ISSUE TITLE
Flaky elixir unit tests

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4635]
https://github.com/firezone/firezone/actions/runs/8701133193/job/23862542757

**Comment by jamilbk** [comment]
Another one: https://github.com/firezone/firezone/actions/runs/8725396789/job/23938263443

**Comment by jamilbk** [comment]
Another (different?) one: https://github.com/firezone/firezone/actions/runs/8749603540/job/24011564931?pr=4708

**Comment by jamilbk** [comment]
https://github.com/firezone/firezone/actions/runs/8759711394/job/24043292462

**Comment by jamilbk** [comment]
Adding some more data points in case it's helpful

https://github.com/firezone/firezone/actions/runs/8786759713/job/24110365779?pr=4734

**Comment by jamilbk** [comment]
Still occurring occasionally: https://github.com/firezone/firezone/actions/runs/8907610107/job/24461787301?pr=4843

**Comment by jamilbk** [comment]
More flaky tests -- seems to happen more in the middle of the when our CPU is slow:

https://github.com/firezone/firezone/actions/runs/9008328005/job/24750130826

**Comment by jamilbk** [comment]
https://github.com/firezone/firezone/actions/runs/9052663558/job/24870602094?pr=4962

**Comment by AndrewDryga** [comment]
@jamilbk This is the same failure, to fix it we would need to rewrite/replace the Bypass library.

Here is an additional issue from the job logs: https://github.com/open-telemetry/opentelemetry-erlang/issues/741

**Comment by jamilbk** [comment]
Noted, thanks for looking further into it

**Comment by jamilbk** [comment]
Has been mostly resolved by increasing timeouts (GH runners are slow!)
