### ISSUE TITLE
docs: unclear how to run Docker Compose locally

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4641]
The docs recommend `docker compose up -d --build` or `docker compose build`. I'm approximating it with `docker-compose` but it looks like it's meant to work in Github Actions. How are the other devs doing it?

<img width="636" alt="image" src="https://github.com/firezone/firezone/assets/13400041/6e6a9c9b-9840-4be1-9701-d890314b3749">

**Comment by jamilbk** [comment]
`docker-compose` and `docker compose` are two different things -- you want to make sure you have a newer `docker` command since it has `compose` built-in

**Comment by ReactorScram** [comment]
okay I'll try installing Docker Desktop :(

**Comment by ReactorScram** [comment]
I don't think they're building it for aarch64 Ubuntu yet

**Comment by jamilbk** [comment]
Docker engine supports the compose plugin I think?

https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

**Comment by jamilbk** [comment]
What does docker-compose --version show?

**Comment by ReactorScram** [comment]
1.25.0, build unknown

**Comment by ReactorScram** [comment]
I have the apt packages `docker.io` and `docker-compse`, I'm not sure if those are Docker Engine or something else

**Comment by jamilbk** [comment]
Wrong version you need Compose 2, follow the docker docs instructions to install

**Comment by jamilbk** [comment]
Unfortunately the apt repos offer the wrong version by default :-(
