### ISSUE TITLE
Flaky elixir test?

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4695]
https://github.com/firezone/firezone/actions/runs/8746975460/job/24004709161?pr=4615

**Comment by thomaseizinger** [comment]
cc @AndrewDryga

**Comment by thomaseizinger** [comment]
Not flaky, fails on all PRs: https://github.com/firezone/firezone/actions/runs/8746968198/job/24004687258

**Comment by thomaseizinger** [comment]
And main: https://github.com/firezone/firezone/actions/runs/8746968198/job/24004687258

**Comment by jamilbk** [comment]
Fixed I think?
