### ISSUE TITLE
ci: migrate JS stack to deno

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#4696]
In https://github.com/firezone/firezone/pull/4569, we've added a browser-based integration test that uses puppeteer via TypeScript to control the browser. This adds a lot of boilerplate which could be miitgated by a different toolchain like deno. Unfortunately, puppeteer isn't fully compatible with deno yet.

This is a tracking issue for the migration of this test to deno.

Upstream issue: https://github.com/denoland/deno/issues/20179

**Comment by thomaseizinger** [comment]
Draft PR for reference: https://github.com/firezone/firezone/pull/4697

**Comment by jamilbk** [comment]
We'd want to migrate Phoenix assets and website to Deno as well to avoid two JS runtimes (one is painful enough)

**Comment by jamilbk** [comment]
Likely not a priority soon.
