### ISSUE TITLE
Gather feedback docs widget

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4707]
It would be helpful to allow users to submit feedback directly from docs pages so we know where they may be hitting issues.

**Comment by dgarcia360** [comment]
Hello @jamilbk ,

I came across this issue while searching for "docs feedback widget" on GitHub. I'm the founder of [PushFeedback](https://pushfeedback.com/), a feedback widget designed specifically for documentation sites that integrates seamlessly with [Next.js](https://docs.pushfeedback.com/installation/nextjs) projects.

![](https://github.com/camunda/camunda-docs/assets/9107969/ba1cdc90-6dfc-44f9-98dd-6a4126c20d21)

We offer a complimentary plan for open-source projects, which includes unlimited feedback entries for one project while maintaining PushFeedback branding. If you're considering adding a feedback mechanism to your documentation, I invite you to [create an account](https://app.pushfeedback.com/accounts/signup/). Once you're set up, please let me know, and I'll remove the limitations for your docs project.

Looking forward to hearing from you!
