### ISSUE TITLE
`reconnect` on the gateway doesn't refresh credentials, causing outage until restart

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4717]
All existing deployed Gateways are failing with these messages after today's hotfix push to prod:

<img width="801" alt="Screenshot 2024-04-19 at 3 01 46 PM" src="https://github.com/firezone/firezone/assets/167144/a7e3046f-b624-49c3-9eac-c9dcff7265e2">

Restarting the Gateway fixes it.

It seems that a simple `reconnect` does not initialize new TURN credentials?

**Comment by jamilbk** [comment]
Could it be related to this? https://github.com/firezone/firezone/pull/4705

**Comment by jamilbk** [comment]
This is logspamming latest release gateways with 100s of `WARN` messages a second. @AndrewDryga is rolling back relays now to see if that fixes the issue.

**Comment by thomaseizinger** [comment]
Was fixed in https://github.com/firezone/firezone/pull/4537 but offending gateway wasn't using the latest version.
