### ISSUE TITLE
DNS mapping fails during roaming if new Relays are received in `reconnect`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4756]
1. `ping github.com`
2. Switch from Ethernet -> Hotspot
3. Portal sends different relays in the new `init` for the `reconnect`
4. `ping` times out indefinitely

See https://github.com/firezone/firezone/pull/4755#issuecomment-2074016191

**Comment by jamilbk** [comment]
Actually I'm not so sure new Relays are the issue. This happened when switching from Ethernet -> WiFi as well.

Also, about 10% of the time it successfully roams for DNS resources. Perhaps a clue.

Also, I experienced another panic, same as #4736 as I was testing this. Trying to reproduce that now.

**Comment by thomaseizinger** [comment]
I tried to reproduce this on Linux by roaming between my WiFi and a hotspot a couple of times and it didn't hit this. It took 10s to restore the ping which is quite reasonable when taking into account that the OS needs a few seconds too to actually switch between WiFi networks.

**Comment by jamilbk** [comment]
Did some more testing on this, but was unable to reproduce. I think the cause of this might be some kind of DNS query buffer bug, re: #4800
