### ISSUE TITLE
bug(connlib): connlib doesn't write to new logfile after logs are cleared

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4764]
#### Describe the bug

There's no log files in `C:\Users\User\AppData\Local\dev.firezone.client\data\logs`, when I open the Logs tab it shows 0 files and 0 MB, and when I export a zip file it's empty.

#### To Reproduce

Can't replicate it.

I had the filter set to `firezone_gui_client=debug,firezone_tunnel=info,phoenix_channel=info,connlib_shared=info,connlib_client_shared=info,boringtun=info,snownet=info,str0m=info,warn`

but that worked when I tried it again.

#### Expected behavior

Expected at least some logs since `firezone_gui_client=debug` and `warn` are in there

#### Screenshots / Logs

N/A

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (d656cd5)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ MSI from draft release

#### Additional context

I set the filter to `debug` and restarted the app and it worked.

**Comment by jamilbk** [comment]
I remember hitting this a while back and I may have forgotten to open an issue about it. Perhaps `tracing` isn't being initialized properly?

**Comment by jamilbk** [comment]
Or maybe the log filter isn't taking effect until being re-saved?

**Comment by ReactorScram** [comment]
I don't think I had changed the filter since I installed the new version yesterday.
The hypotheses I've got are this:

1. Clearing the logs maybe messes up the logging system because it doesn't expect the file to vanish from under it?
2. Maybe if the computer goes to sleep, when it wakes up and the clock suddenly changes, the logging code gets confused?

**Comment by ReactorScram** [comment]
Yeah I'm not sure if we still roll the log files, but when I hit "Clear logs" it definitely deletes the current file and doesn't try to write any more logs to that.

Since we know when that happens maybe we can signal to the logger, "recreate your file, we just deleted it"

**Comment by jamilbk** [comment]
> Clearing the logs maybe messes up the logging system because it doesn't expect the file to vanish from under it?

Ah yes! I hit this recently with the Apple client as well -- also happened with the Swift-side logs.

Yeah we should either detect the file is missing and recreate it.

**Comment by jamilbk** [comment]
@ReactorScram I think this has been probably hit enough times to make it worth fixing after #5123. Maybe it would be simpler if we just updated the clear behavior to remove all files except the most recent one? Or expose an FFI `rotateLogfile` function or something

**Comment by ReactorScram** [comment]
Yeah, maybe we can go off the filenames and keep the last one, when sorted lexicographically. (mtime would work, but I prefer not to use mtime if I can help it)

**Comment by ReactorScram** [comment]
Status: PR got reviewed, so I can make more progress on it today
