### ISSUE TITLE
bug(scripts): Update gateway upgrade script to handle new permalinks

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4770]
@jamilbk Made an issue for this since I didn't see one.

With #4746 having merged, the gateway upgrade script is out of date: https://github.com/firezone/firezone/blob/e1eda7977c43f6958dc707b0fcb9582b5be87d90/scripts/gateway-systemd-install.sh

The Docker one is probably still fine?

Long-term I'd rather package the gateway as a deb but that's a big change.

```[tasklist]
- [ ] Test the gateway upgrade script in a local VM
- [ ] Change the script to download itself from `main` and then do whatever that version of the script says
```

**Comment by jamilbk** [comment]
I already did this in the PR -- see https://github.com/firezone/firezone/blob/e1eda7977c43f6958dc707b0fcb9582b5be87d90/scripts/gateway-systemd-install.sh#L62

**Comment by ReactorScram** [comment]
oh whoops

**Comment by jamilbk** [comment]
The issue is with existing gateways. I'm planning to send users an email with instructions to update their `/usr/local/bin/firezone-init` script.
