### ISSUE TITLE
Add `blocked_tx` to gateway metrics

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#4787]

**Comment by jamilbk** [comment]
refs #2060

**Comment by AndrewDryga** [comment]
@jamilbk do we even get blocked traffic at the gateway nowadays or it should be filtered on the client already? cc @conectado

**Comment by conectado** [comment]
> @jamilbk do we even get blocked traffic at the gateway nowadays or it should be filtered on the client already? cc @conectado

Right now yes, but that's changing due tp #4789 but still a malicious client could work around that and get blocked on the gateway
