### ISSUE TITLE
`x-real-ip` header doesn't seem to be read by Phoenix upstream

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#480]
<img width="1195" alt="Screen Shot 2022-02-27 at 9 16 29 AM" src="https://user-images.githubusercontent.com/167144/155892432-9c136098-7d10-414f-b9c4-020d5b807687.png">

**Comment by mdp** [comment]
Unfortunately the fix on #558 only work for [x-forwarded-host/port/proto](https://github.com/elixir-plug/plug/blob/v1.13.6/lib/plug/rewrite_on.ex#L11-L15).

But it should trivial to take this code and create a version that does IP's - [Example - https://websymphony.net/blog/how-to-get-remote-ip-from-x-forwarded-for-in-phoenix/](https://websymphony.net/blog/how-to-get-remote-ip-from-x-forwarded-for-in-phoenix/)
