### ISSUE TITLE
"Too many DNS queries"

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4800]
This seems to happen whenever roaming.

**Comment by jamilbk** [comment]
@conectado I was able to replicate this with just a ping to `github.com` and a reload of github.com on a slow network. I'm not sure how many DNS queries `ping github.com` is supposed to generate, but if the underlying network is slow or dropping them (e.g. hotspot), then somehow this fills the buffer, and then we get log spammed with the error message in the title.

Questions:

- Why is `Too many DNS queries` printed in each iteration of the eventloop it seems? Shouldn't this correspond to when the actual DNS query was attempted?
- Can we dedup the queries by host?
- Can we increase the buffer *much* higher? 1,000 or even 5,000 might be more appropriate if we're **actually** filling up the buffer with valid queries.


When I see this error, the peer is dropped, so we have to get a new `resource_intent` for things to work again.

**Comment by thomaseizinger** [comment]
> * Why is `Too many DNS queries` printed in each iteration of the eventloop it seems? Shouldn't this correspond to when the actual DNS query was attempted?

It should only be per query but if the browser generates many DNS queries, we will see it a lot.

> * Can we dedup the queries by host?

Should be possible, we would need to buffer all incoming queries and answer them once the result comes back.

> * Can we increase the buffer _much_ higher? 1,000 or even 5,000 might be more appropriate if we're **actually** filling up the buffer with valid queries.

Definitely. It was set to a pretty arbitrary number. We should probably also decrease the timeout from 60s to something shorter. Even on a slow network, a DNS query should resolve within 5(?)s?

**Comment by jamilbk** [comment]
This seemed to be a weird bug --

Steps to reproduce:

- Connect firezone (macOS)
- Keep browser closed
- ping github.com
- roam networks judiciously

I seemed to be able to hit it with just those steps, which doesn't seem to make sense.

**Comment by jamilbk** [comment]
It might be good to dedup them at least

**Comment by jamilbk** [comment]
Closing for now as can't reproduce.

**Comment by ReactorScram** [comment]
Replicating for me on the Windows x64 dev laptop
- Check out deae9a982 (current tip of main, after Linux process split, before Windows process split) and build
- Have a few normal apps open (Firefox with Slack, Google Calendar, GMail, Github, and music tabs, and an Ubuntu VM)
- Run the GUI Client on Windows
- Turn off Wi-Fi so the laptop has no Internet
- Wait 30 seconds (almost exactly 30)
- connlib logs `WARN firezone_tunnel::io: Too many DNS queries, dropping existing one` in bursts, averaging about 2.2 per second.

Checking if it replicates in the headless Linux Client in an Ubuntu VM or WSL

**Comment by ReactorScram** [comment]
The Headless Linux Client running in WSL doesn't replicate it. Maybe because it doesn't watch for network changes or call `reconnect` like the GUI Client does? There will also be much less stuff running in WSL making DNS queries, but I did a `curl ifconfig.net` and that didn't set it off.

**Comment by thomaseizinger** [comment]
Thanks for the repro @ReactorScram !

Does it ever stop doing that? Does it affect connectivity?

**Comment by ReactorScram** [comment]
@thomaseizinger When I turn the Wi-Fi back on, there's a gap where accessing `ifconfig.net` shows my home IP, not the Gateway IP. Judging from the logs, this is because we're resetting the DNS control there. But after that, it pretty quickly shows the Gateway IP again, as if it had started fresh.

I'll leave it running a while. I know it will do this for at least a few minutes. I'm assuming it does it forever.

**Comment by jamilbk** [comment]
Had a similar experience with Apple (macOS) client when first opened this issue

**Comment by ReactorScram** [comment]
I am seeing some query timeout messages after maybe 7 minutes. I haven't been looking closely so I don't know if they happened sooner than that.

**Comment by ReactorScram** [comment]
@thomaseizinger It never stops. I left the Windows laptop overnight and 15 hours later it's still printing new warnings.

**Comment by thomaseizinger** [comment]
@ReactorScram Could you retest on the following branch https://github.com/firezone/firezone/pull/5263?

**Comment by ReactorScram** [comment]
Trying https://github.com/firezone/firezone/issues/4800#issuecomment-2121212375 
with MSIs GitHub built from a recent draft release (fd27f0d) and #5263 (c40fe3688)

- fd27f0d still replicates it, as expected
- c40fe3688 (built as 5b08c92) now says "Failed to send DNS query: Too many ongoing DNS queries"
@thomaseizinger

**Comment by ReactorScram** [comment]
Didn't think to do a soak test. I've started this again around 17:42 UTC on 5b08c92 and I'll see how long it keeps printing those messages.

Update: It kept going until I stopped it at 18:51 UTC. 
From 17:42 until 18:26 it printed 5,566 lines, averaging 2.1 lines per second, similar to before. At 18:26 there's no more lines until 18:50, I think maybe the laptop fell asleep.

**Comment by thomaseizinger** [comment]
> * [c40fe36](https://github.com/firezone/firezone/commit/c40fe36889cb4aae647d55e7f5b2d7763e39d014) (built as [5b08c92](https://github.com/firezone/firezone/commit/5b08c92c16c5b525516bdaa3e615059236e744e7)) now says "Failed to send DNS query: Too many ongoing DNS queries"

Which domain is it? Should be in the tracing span attached to it.

This makes me think that there is an upstream application that keeps making DNS queries despite us replying with an error :(

**Comment by ReactorScram** [comment]
It's a bunch
- `calendar.google.com`
- `chat.google.com`
- `discovery-v4.syncthing.net`
- `discovery-v6.syncthing.net`
- `geo.prod.do.dsp.mp.microsoft.com`
- `mail.google.com`
- `mobile.events.data.microsoft.com`
- `peoplestack-pa.clients6.google.com`
- `push.services.mozilla.com`
- `relays.syncthing.net`
- `signaler-pa.clients6.google.com`
- `ssl.gstatic.com`
- `stun.callwithus.com`
- `stun.counterpath.com`
- `stun.internetcalls.com`
- `stun.voip.aebc.com`
- `stun.voipstunt.com`
- `stun.xten.com`
- `waa-pa.clients6.google.com`

(There's more but I got bored of pasting)

That sure is a lot of random STUN domains...

They sometimes repeat multiple times, e.g.
```jsonl
[
  "2024-06-06T18:25:54.5309241Z",
  "calendar.google.com"
]
[
  "2024-06-06T18:25:54.5313586Z",
  "calendar.google.com"
]
[
  "2024-06-06T18:25:54.5318725Z",
  "calendar.google.com"
]
[
  "2024-06-06T18:25:54.5319365Z",
  "calendar.google.com"
]
[
  "2024-06-06T18:25:54.5323846Z",
  "calendar.google.com"
]
[
  "2024-06-06T18:25:54.5324425Z",
  "calendar.google.com"
]
[
  "2024-06-06T18:25:54.6364051Z",
  "assets.msn.com"
]
[
  "2024-06-06T18:25:54.6364944Z",
  "assets.msn.com"
]
[
  "2024-06-06T18:25:54.6365261Z",
  "assets.msn.com"
]
[
  "2024-06-06T18:25:54.6365527Z",
  "assets.msn.com"
]
[
  "2024-06-06T18:25:54.6371233Z",
  "assets.msn.com"
]
[
  "2024-06-06T18:25:54.6372124Z",
  "assets.msn.com"
]
[
  "2024-06-06T18:25:54.6372469Z",
  "assets.msn.com"
]
```
or
```jsonl
[
  "2024-06-06T18:25:55.897179Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.8972753Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.8978429Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.8979506Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.897989Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.8980194Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.8985125Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.8986308Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.898674Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:55.8987076Z",
  "discovery.syncthing.net"
]
[
  "2024-06-06T18:25:57.6498198Z",
  "stun.callwithus.com"
]
[
  "2024-06-06T18:25:57.6504561Z",
  "stun.callwithus.com"
]
[
  "2024-06-06T18:25:57.6510243Z",
  "stun.callwithus.com"
]
```
(After `jq '[.time, .name]' < temp.txt`)

Even the Firezone API URL does it
```jsonl
{"time":"2024-06-06T17:42:41.994761Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"api.firez.one","server":"fd00:2021:1111:8000:100:100:111:0"}
{"time":"2024-06-06T17:42:41.9948769Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"api.firez.one","server":"100.100.111.1"}
{"time":"2024-06-06T17:42:41.9949593Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"api.firez.one","server":"fd00:2021:1111:8000:100:100:111:0"}
{"time":"2024-06-06T17:42:41.9950717Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"push.services.mozilla.com","server":"100.100.111.1"}
{"time":"2024-06-06T17:42:41.9950949Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"push.services.mozilla.com","server":"fd00:2021:1111:8000:100:100:111:0"}
{"time":"2024-06-06T17:42:41.9954893Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"api.firez.one","server":"100.100.111.1"}
{"time":"2024-06-06T17:42:41.9955222Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"api.firez.one","server":"fd00:2021:1111:8000:100:100:111:0"}
{"time":"2024-06-06T17:42:41.9955555Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"api.firez.one","server":"100.100.111.1"}
{"time":"2024-06-06T17:42:41.9956127Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"api.firez.one","server":"fd00:2021:1111:8000:100:100:111:0"}
{"time":"2024-06-06T17:42:43.6313707Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib\\tunnel\\src\\client.rs","line":"662"},"severity":"WARNING","message":"Failed to send DNS query: Too many ongoing DNS queries","name":"accounts.google.com","server":"100.100.111.1"}
```

And it's definitely 5b08c92. I could send the full log on Slack if you need

**Comment by thomaseizinger** [comment]
Interesting, thanks for the test. Needs more work it seems.

**Comment by thomaseizinger** [comment]
I've looked a bit more into this:

1. Our DNS resolver, hickory, applies a 5s timeout with 2 retries.
2. 5s timeout matches the behaviour of `dig`.
3. I don't know what the timeout of MacOS is.
4. `nslookup` seems to use 2s based on logs in https://github.com/firezone/firezone/pull/5263.

Essentially, what seems to happen here is that for whatever reason, a previous upstream DNS resolver is now unreachable. Internally, hickory only times out after 5s. If the OS times out before that, it sends a new DNS query, adding more "load" to our DNS resolver.

We cap the maximum number of concurrent DNS queries to 100.

Really, what the application _should_ do is apply an exponential backoff and not keep retrying with the same timeout values but we can't change all applications :upside_down_face: 

I am unsure how to "fix" this:

- We cannot just increase the `100`, that just means using more memory. We have to bound this queue to something.
- We can shorten our timeout but something like < 2s seems really short and I am worried we might cut off legitimate responses early here.

What we should probably do is remove that bad DNS server once we detected repeated timeouts? But so far, connlib only ever reacts to DNS servers changing. We don't update them proactively. Should we?

**Comment by jamilbk** [comment]
Hm, can we replace old lookups with newer ones for the same query? I.e. Set not Queue

**Comment by thomaseizinger** [comment]
> Hm, can we replace old lookups with newer ones for the same query? I.e. Set not Queue

And reply to the one that we replaced immediately with an error? DNS queries are identified by ID so replacing one with another just means one query gets answered instead of the other.

I do think that head-drop might be better than tail-drop here, given UDPs nature of an unreliable protocol answering a more recent query is probably better than a very old one.

**Comment by thomaseizinger** [comment]
Another way to deal with such a burst would be to clear the entire queue and drop all current in-flight DNS queries. That would at least make space for another 100 where some may actually resolve.

**Comment by conectado** [comment]
> Hm, can we replace old lookups with newer ones for the same query? I.e. Set not Queue

> > Hm, can we replace old lookups with newer ones for the same query? I.e. Set not Queue
> 
> And reply to the one that we replaced immediately with an error? DNS queries are identified by ID so replacing one with another just means one query gets answered instead of the other.
> 
> I do think that head-drop might be better than tail-drop here, given UDPs nature of an unreliable protocol answering a more recent query is probably better than a very old one.

I think here we could keep a map of (name, type, source_port) -> query, so if the same application retries we replace only that query, that's a way to keep track when an application times out and retries?

> Another way to deal with such a burst would be to clear the entire queue and drop all current in-flight DNS queries. That would at least make space for another 100 where some may actually resolve.

Could there be a situation where this causes burst of +100 queries that keep replacing the previous burst?

**Comment by thomaseizinger** [comment]
Could somebody retest with https://github.com/firezone/firezone/pull/5306 so we see what the upstream response is?

**Comment by thomaseizinger** [comment]
> > > Hm, can we replace old lookups with newer ones for the same query? I.e. Set not Queue
> > 
> > And reply to the one that we replaced immediately with an error? DNS queries are identified by ID so replacing one with another just means one query gets answered instead of the other.
> > I do think that head-drop might be better than tail-drop here, given UDPs nature of an unreliable protocol answering a more recent query is probably better than a very old one.
> 
> I think here we could keep a map of (name, type, source_port) -> query, so if the same application retries we replace only that query, that's a way to keep track when an application times out and retries?

That could be an option yeah. I am a bit hesitant implementing stuff like this before understanding this fully.

hickory has a built-in cache but that doesn't seem to cache timeouts (which is fair I guess?).

> > Another way to deal with such a burst would be to clear the entire queue and drop all current in-flight DNS queries. That would at least make space for another 100 where some may actually resolve.
> 
> Could there be a situation where this causes burst of +100 queries that keep replacing the previous burst?

I don't think so. The sender side will still timeout after the same time period which is unlikely to coincide with other DNS queries being sent on the system?

I think the main thing that happens here is that once we build up a queue of DNS queries that timeout for whatever reason, they take too long too clear and by the time we respond, the original application no longer cares about the response because it has already sent a new one. So clearing all of them would actually reset things nicely.
