### ISSUE TITLE
WG config download naming pattern..

### ISSUE THREAD

**Issue by bcookatpcsd** [CloudFire-LLC/cloudfire#482]
When downloading device configuration files for use in the Wireguard client, they download in the name of firezone_fq_dn.conf and import into Wireguard as such.

I would like to suggest that if the device profile is firezone-rocks it should download as firezone-rocks.conf

This would allow the matching of device profiles to configuration files.

Possibly including the Updated date/timestamp in the configuration name as well? 

firezone-rocks-022720221413.conf for example.. 

Thank you in advance.

**Comment by jamilbk** [comment]
Thanks for the suggestion! This makes sense -- we were actually considering this naming scheme off the bat. This is a fairly simple change -- I'll queue this up into our backlog. It'll probably make it into the 0.3.0 release coming in the next few days.

**Comment by bcookatpcsd** [comment]
If you've never seen this.. https://github.com/StreisandEffect/streisand

You could learn a lot from them.. it was an amazing project..

This is where I initially exposed to the naming patterns.. 

https://github.com/StreisandEffect/streisand/blob/af5eb7dac157a2416ea64cba96cf32f7f505d9ff/playbooks/roles/common/files/english.txt

This random "naming-pattern.conf" was consistent throughout the openvpn, shadowsocks, wireguard, etc. services offered.. 

I cannot find Streisand screenshots to share..

**Comment by jamilbk** [comment]
Fixed in #495 and being released imminently with 0.3.0
