### ISSUE TITLE
Possible note area per device

### ISSUE THREAD

**Issue by bcookatpcsd** [CloudFire-LLC/cloudfire#484]
fqdn/devices/1

Is there space to extend the db to include a possible text area for notes.. 

"user has iPhone, running IOS 1.2.3, installed wg app from Apple Store.."

(for users with multiple devices this seems to make more sense.. )

Possibly fqdn/devices/1/edit being able to change the Name and being able to append -iphone-xsmax or something was the intent.. 

Is there a max length on the Name field?

Thank you in advance..

**Comment by jamilbk** [comment]
Great suggestion. Would a `description` field suit this use case?
