### ISSUE TITLE
doc(linux GUI): install script

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4873]
```[tasklist]
### Before merging
- [ ] Someone other than me should test it
```

We could get rid of this* if we use a post-install script in the deb package. But Tauri's deb bundler doesn't support that, so we'd need to switch to `cargo-deb`. I'd really like to do that and use `build.rs` or something instead of `build.bat` and `build.sh`, but it's a big time sink.

*The `adduser` step probably should be manual, but systemctl and groupadd can be done in a post-install script.

```bash
#!/usr/bin/env bash
# Usage: bash firezone-setup.bash firezone-client-gui_VERSION_ARCH.deb
# This script should be idempotent
set -euox pipefail

echo "Adding your user to the firezone group..."
sudo groupadd --force firezone
sudo adduser "$USER" firezone

echo "Installing Firezone..."
sudo apt install "$1"

echo "Starting and enabling Firezone IPC service..."
sudo systemctl enable --now firezone-client-ipc

# Unfortunately Ubuntu seems to need a reboot here, at least 20.04 does
echo "Reboot to finish adding yourself to the group"
```

**Comment by thomaseizinger** [comment]
Users can be added declaratively too if we already have systemd as a prerequisite.

https://www.freedesktop.org/software/systemd/man/latest/sysusers.d.html

**Comment by jamilbk** [comment]
@ReactorScram We do this for Gateways -- See https://github.com/firezone/firezone/blob/main/scripts/gateway-systemd-install.sh#L26

**Comment by ReactorScram** [comment]
@jamilbk Hm, so that creates both a user and group "firezone". I only need the group, but maybe I should use "firezone-client" instead.

btw if you set User and Group in systemd you could probably drop that entire `sudo` command: https://github.com/firezone/firezone/blob/9606dde1d8c4f36404fe885e94e57bc906af704e/rust/gui-client/src-tauri/firezone-client-ipc.service#L46-L47
