### ISSUE TITLE
bug(gui-client/linux): The Tauri GUI Client doesn't work on Ubuntu 24.04

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4883]
#### Describe the bug

The WebKit library in Ubuntu 24.04 has a different name than the ones in Ubuntu 20.04 and 22.04, and Tauri can't seem to dynamic link with it.

#### To Reproduce

Try to install any deb package from CI on an Ubuntu 24.04 system. Apt will fail with `unmet dependencies` since webkit2gtk 4.0 is not available anymore on Ubuntu 24.04.

#### Expected behavior

Expected a package built for Ubuntu 20.04 to work on Ubuntu 24.04.

#### Screenshots / Logs

Internal discussion https://firezonehq.slack.com/archives/C067DSY7TFX/p1714683378145499

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ N/A
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Ubuntu 24.04
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Debian package

#### Additional context

Fixes considered:

- Build 2 deb packages, one for 24.04 and one for 20.04 + 22.04
- Ditch Tauri + WebKit for something smaller like FLTK, GTK+, LVGL, etc. - Lots of work, may not look as slick without CSS
- ~~Require 2 downloads for the GUI, AppImage for the GUI itself, deb for the IPC service~~ - Inconvenient for users, AppImages built on 20.04 don't work on 24.04
- ~~Bundle WebKit ourselves in the deb package~~ - Might not work, WebKit expects the worker binaries at a certain path. If I install to that path, it'll break on 20.04, if I don't, it'll break on 24.04.
- ~~Build the GUI as an AppImage, then embed that AppImage inside a debian package~~ - An AppImage built on 20.04 doesn't render anything on 24.04
- ~~Switch back to AppImage bundling~~ - An AppImage built on 20.04 doesn't render anything on 24.04

**Comment by ReactorScram** [comment]
The AppImage bundle isn't working right in 24.04 either, just shows white in the windows, can't even get a context menu 
<img width="1045" alt="image" src="https://github.com/firezone/firezone/assets/13400041/5b56da93-a4c0-46b0-8631-3d6b6db308d0">

**Comment by ReactorScram** [comment]
If we switch toolkits, we can still use `tray_icon` and `tao`, which are the underlying crates that Tauri uses to spawn a tray icon and menu. (tao is the windowing framework)

I tested those just now and it's no problem to build on 20.04 and run on 24.04.

We could probably find something that can draw inside of a Tao window.

It's a lot of work though, that's maybe a "after a year" solution. If Github gets a 24.04 runner in May or June, we can just build 2 deb packages.

**Comment by ReactorScram** [comment]
Probably same as this https://github.com/tauri-apps/tauri/issues/9662

**Comment by jamilbk** [comment]
I wonder if the real fix here is to just use a service like Cloudsmith.io or Google artifact hosting to provide an apt repository. Then we can build for other distros too and just provide `apt` configuration instructions. Otherwise I foresee the `/changelog` becoming no fun to manage.

**Comment by thomaseizinger** [comment]
> We could probably find something that can draw inside of a Tao window.

I had a play with https://github.com/lapce/floem, https://github.com/zed-industries/zed/tree/main/crates/gpui and https://github.com/linebender/xilem. Out of these three, floem seems to be the easiest one to get working.

- GPUI is too low-level and doesn't provide any widgets
- Xilem provides widgets but I couldn't figure out how to style them

The downside of anything Rust-native is that we can't use flowbite so we'd have to re-create the styles. For the little bit of GUI that we have, this shouldn't be much of an issue though?

Another advantage is lower memory usage (~15MB) when running the application.

**Comment by thomaseizinger** [comment]
The following screenshot is made with floem:

![image](https://github.com/user-attachments/assets/0c7beade-e5b6-45c5-9018-61281a269535)

I pushed the code to https://github.com/firezone/firezone/pull/6333.

**Comment by ReactorScram** [comment]
We can probably keep using Tauri's bundler (one of the nicest parts of it) and just remove Tauri from `Cargo.toml` so that Tauri bundles up a plain Rust exe for us
