### ISSUE TITLE
WebUI only reachable over ipv4

### ISSUE THREAD

**Issue by NikJen26** [CloudFire-LLC/cloudfire#4941]
#### Describe the bug

Whenever I try to reach the WebUI over ipv6 it uses the fallback ipv4 version.

#### To Reproduce

Try to access the WebUI over a ipv6 only DNS-Entry or with the ipv6 address directly. Do not use Caddy or else in front of the WebUI Service.

#### Expected behavior

The WebUI should be reachable over ipv4 and ipv6 at the same time. Especially when ipv6 in docker gets enabled.

#### Platform (please complete the following information)

- Component: WebUI
- Firezone Version: 0.7.36
- OS and version: Ubuntu 22.04 as Server
- Deployment method: Docker

**Comment by jamilbk** [comment]
Hi @iehfned! Firezone 0.7 has reached EOL. You may have some luck making sure IPv6 [is enabled](https://www.firezone.dev/docs/deploy/docker#step-4-optional-enable-ipv6) for your Docker env and ensuring your Caddy config is correct.
