### ISSUE TITLE
Support for Authentik SSO

### ISSUE THREAD

**Issue by fnpanic** [CloudFire-LLC/cloudfire#498]
Hi,

i like firezone a lot and would love to have support for Authentik as an SSO provider.

https://github.com/goauthentik/authentik

Having a gerneral Oauth2 or an example config with oauth_proxy or vouch proxy would also be a good and more general approach.
Thanks!

**Comment by jamilbk** [comment]
@fnpanic Thanks for the feature request. Would generic OIDC support like in #501 solve your use-case?

**Comment by ranomier** [comment]
Yes, a generic oidc or oauth2 would be awesome.

**Comment by jamilbk** [comment]
@fnpanic #586 has been merged to support this and will be available in the next release.
