### ISSUE TITLE
ux(gui-client): add pre-install / post-install scripts to the deb package

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4987]
#### Is your feature request related to a problem? Please describe.

Right now you need an external Bash script to install / upgrade the Linux GUI Client. This is an extra step for users and could lead to version skew if someone installs e.g. a new package with the old script.

#### Describe the solution you'd like

Deb packages already have a place to put scripts that apt will call, but Tauri's deb bundler doesn't support this.

We should switch to something more customizable like `cargo-deb`. This would mean taking apart the Tauri build process, but then we'd have more control over everything.

#### Describe alternatives you've considered

- We can let it go for a while.
- We could also run the Tauri build process, then take apart the deb package, put the scripts in, and create a new package.
- Pacur

#### Additional context

This is the install script: https://github.com/firezone/firezone/blob/3ba7962c230ef9b360e71430d559ca80d98c84d6/scripts/firezone-client-gui-install.sh

Info on maintainer scripts: https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html

**Comment by jamilbk** [comment]
I'm pretty surprised Tauri doesn't allow specifying custom `postinst` et al scripts. The nice thing about using those, though is that tools like [`alien`](https://wiki.debian.org/Alien) will work well with it so we might get RPMs for free too.

**Comment by jamilbk** [comment]
If we're going custom, this one is also worth looking into:

- [pacur](https://github.com/pacur/pacur)
