### ISSUE TITLE
Support for Microsoft Azure AD SSO

### ISSUE THREAD

**Issue by brumle80** [CloudFire-LLC/cloudfire#499]
This is looking great!

Would love to see 365 SSO support

**Comment by jamilbk** [comment]
Noted, we've had many ask for this! It's planned, just a matter of getting to it :-). Will likely be started after generic OIDC integration is done in #501

**Comment by jamilbk** [comment]
Hi @brumle80 -- since Azure AD [supports the OpenID Connect](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal-setup-oidc-sso) protocol for auth, will that work for your case?

#586 adds provider-agnostic OIDC to Firezone, due out for release soon.

**Comment by jamilbk** [comment]
Closing, 0.3.12 implements this via OIDC. Please try it out and open another issue if you hit any problems!

**Comment by findmyname666** [comment]
Hello all,

Documentation mentions support only for Google and Okta SSO - https://docs.firezone.dev/docs/authenticate/. Did you forget to update it or this isn't supported yet ?

BR

**Comment by findmyname666** [comment]
hmm I see this commit https://github.com/firezone/firezone/pull/615/files now so it is coming ...
