### ISSUE TITLE
Login with non 443 port redirects back to port 443 (and several other issues)

### ISSUE THREAD

**Issue by stuffeh** [CloudFire-LLC/cloudfire#500]
I'm on version 0.3.0. Thank you for any help and insight you can offer. 

I have `default['firezone']['nginx']['ssl_port'] = 8080` setup in /etc/firezone/firezone.rb and I see the correct settings in `/var/opt/firezone/nginx/etc/sites-enabled/phoenix`, and the site loads correctly on my browser at `https://<domain>:8080/`. But once I hit login button, it redirects me to `https://<domain>/auth/identity/callback` (port 443). No idea if it's a setting I'm missing or something else.

However when I set the port back to 443 to login, then change the port back to 8080, it works and I can pretty much do anything (until I need to login again anyways). I'm going to eventually disable the packaged nginx and use my own.

I noticed if I set both `default['firezone']['nginx']['ssl_port']` and `default['firezone']['nginx']['non_ssl_port']` to 8080, nginx fails to load and I get: nginx: [emerg] a duplicate default server for 0.0.0.0:8080 in /var/opt/firezone/nginx/etc/sites-enabled/phoenix:23. Line 23 is `listen 8080 default_server;` which is the 2nd server block. If I change `non_ssl_port` to 8081 and go to http://<domain>:8080 I get the error `400 Bad Request: The plain HTTP request was sent to HTTPS port`. Dunno if this is how you guys prefer it to fail or something.

I also noticed that `sudo firezone-ctl show-config` shows the default fresh install settings and nothing changed from firezone.rb.

**Comment by jamilbk** [comment]
@stuffeh

Thanks for the detailed bug report! The nginx port change causing the `redirect_uri` to break is definitely a bug, as is the `show-config` command printing the config template values as opposed to what's in `/etc/firezone/firezone-running.json` so I'll work on a fix for those.

The nginx `ssl_port` and `non_ssl_port` must be two distinct ports at the moment, but it looks like this could be supported using [nginx's `ssl_preread` option](https://www.nginx.com/blog/running-non-ssl-protocols-over-ssl-port-nginx-1-15-2/). Would something like that suit your use case?

**Comment by stuffeh** [comment]
You're welcome. I'm always finding weird use cases that'll break things.

I found a solution for my situation. I'm dropping the first server block, and add a line `error_page 497 =200 https://$host:<port>$request_uri;` in the block that's left. This lets us do it without adding the module.

By the way, I'm also seeing a few warnings in tail about the line of code `ssl on;` (line 26ish) is being depreciated and how it should be tied with listen. Can also add `http2` support but need to add `ngx_http_v2_module` while we're at it for a small performance boost. So the config file for my managed nginx basically becomes `listen 8080 default_server ssl http2;`.

**Comment by jamilbk** [comment]
@stuffeh 

One more question before I begin diving into work on these fixes (things have been crazy lately) --

What's the status of your `default['firezone']['nginx']['force_ssl']` setting? By default it's `true`, which will redirect HTTP to HTTPS. Just making sure that one didn't slip past you before I begin triaging :-).

**Comment by stuffeh** [comment]
@jamilbk I didn't change that setting in the fz config file. I also didn't look into what that setting changes in the nginx config file before manually deleting the first server block or commenting out `ssl on;`. Kinda assumed that it setup those two.

**Comment by jamilbk** [comment]
@stuffeh Ah I see. Yeah the redirect behavior is likely being caused by the `default['firezone']['nginx']['force_ssl']` setting, which is on by default. You'll probably have better luck changing that to false.
