### ISSUE TITLE
"Deploy more Gateways for high availability" on Sites show

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5009]

**Comment by AndrewDryga** [comment]
@Patticatti would be nice in the new UX to have a place in the table views that allows to show suggestions in a tooltop (or something along those lines), for example:
- in the list of sites to show hints like the one described in this issue
- on Policies page "This policy was last used more than X months ago, do you want to disable it?"
- on Actors page "This actor did not log in for more than X months, do you want to disable it?"
etc

**Comment by thomaseizinger** [comment]
Related: https://github.com/firezone/firezone/issues/6312.
