### ISSUE TITLE
Oidc integration

### ISSUE THREAD

**Issue by nmass-betpawa** [CloudFire-LLC/cloudfire#501]
It would be great to have oidc integration, so anything like Azure, Google, Dex could be used for SSO

**Comment by jamilbk** [comment]
Thanks for the suggestion! We've had a few users asking to [expose more OIDC controls](https://hexdocs.pm/openid_connect/readme.html) so I'll queue this into the backlog to work on next.

**Comment by lukasmrtvy** [comment]
Fastest way to develop agains Generic OIDC provider would be a https://github.com/dexidp/dex

**Comment by martijndeb** [comment]
I wanted to weigh in on this, as I'm currently running a Dex setup. This would be very helpful for my usecase.
Thanks for the top notch work 👍

**Comment by crrodriguez** [comment]
This will help us inmesely to get rid of openvpn..

**Comment by jamilbk** [comment]
#586 has been merged to support this and will be available in the next release, due out in the next day or two. Please open another issue if you face any issues getting it set up!
