### ISSUE TITLE
bug(gui-client): the tray icon has poor contrast against the default dark Ubuntu task bar

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5014]
#### Describe the bug

It's hard to see

#### To Reproduce

1. Glance at the task bar
2. Judge whether Firezone is running or not

#### Expected behavior

Expect the icon to be easy to see

#### Screenshots / Logs

![image](https://github.com/firezone/firezone/assets/13400041/2eae1248-1b43-497c-9c64-e5914b7057c9)

Taken on an x86-64 VM of Ubuntu 20.04

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Linux GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ N/A
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Ubuntu 20.04
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ deb

**Comment by jamilbk** [comment]
@ReactorScram Does Tauri allow light and dark versions? We have an orange icon we can use that works for both light and dark https://www.firezone.dev/favicon.ico

**Comment by ReactorScram** [comment]
Yeah I think we can detect the theme and listen for changes using these
- https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.theme
- https://docs.rs/tauri/latest/tauri/enum.WindowEvent.html#variant.ThemeChanged

And then set the tray icon using https://docs.rs/tauri/latest/tauri/struct.SystemTray.html#method.with_icon

**Comment by ReactorScram** [comment]
Closed in #5817
