### ISSUE TITLE
Linux GUI client disconnected right after connecting.

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5027]
![image (1)](https://github.com/firezone/firezone/assets/167144/98230acc-3363-40e1-a790-c229358f47b3)

**Comment by ReactorScram** [comment]
Closing, it turned out to be that `systemd-resolved` was not enabled, and we weren't showing any logs for that. There are issues open to improve error reporting, and this case will be added to troubleshooting in #5007
