### ISSUE TITLE
bug(client): adding service actor to group / enabling policy only takes effect after restarting the Client

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5052]
#### Describe the bug

_A clear and concise description of what the bug is._

#### To Reproduce

By adding a service actor to a group:

1. Set up the Headless Client but don't put the service actor in any groups that have access to Resources
2. Run the Headless Client
3. Check IP with `ifconfig.net`, expect the computer's real IP address
4. Add the service actor to a group that has a Policy with access to `ifconfig.net`
5. Check IP a few more times, it still shows the computer's real IP address
6. Restart the Headless Client
7. Check IP again, it's instantly changed to the Gateway's IP

By enabling a policy:

1. Disable `ifconfig.net` policies for your actor
2. Start the Client
3. Run `curl -4 https://ifconfig.net/ip`, expect your real IP
4. Enable the policy
5. Run curl again, expect the gateway IP, it should fail

#### Expected behavior

Expected that the Gateway's IP should appear immediately after Step 4, and not need the Client to restart to take effect

#### Screenshots / Logs

None

#### Platform (please complete the following information)

Reproduces on:
- Linux GUI Client
- Linux Headless Client
- Windows Headless Client

May reproduce on:
- Windows GUI Client

Doesn't reproduce on:
- macOS Client

#### Additional context

_Add any other context about the problem here._

**Comment by conectado** [comment]
Does closing and re-opening the browser solves it?

What does `curl ifconfig.net` shows?

**Comment by ReactorScram** [comment]
I was using `curl` the whole time, no browser involved. It's possible that there is some DNS caching in systemd that gets reset when the tunnel goes down and back up?

**Comment by conectado** [comment]
> I was using `curl` the whole time, no browser involved. It's possible that there is some DNS caching in systemd that gets reset when the tunnel goes down and back up?

I've never seen that, maybe a portal bug? we should print the resources with `on_update_resources` and check if it's actually there.

**Comment by ReactorScram** [comment]
Looks like I already had `tracing::debug` in `on_update_resources` and it's definitely getting called as soon as I click in the portal.

Actually, the "everyone" group has `ifconfig.net` as a resource, so I'm not sure why it doesn't route through Firezone all the time. I'm seeing DEBUG showing `ifconfig.net` as a resource both when I add and when I remove it from my personal group.

**Comment by conectado** [comment]
> Looks like I already had `tracing::debug` in `on_update_resources` and it's definitely getting called as soon as I click in the portal.
> 
> Actually, the "everyone" group has `ifconfig.net` as a resource, so I'm not sure why it doesn't route through Firezone all the time. I'm seeing DEBUG showing `ifconfig.net` as a resource both when I add and when I remove it from my personal group.

That's weird, for service account `everyone` shouldn't be included

**Comment by conectado** [comment]
I just repro'd this by adding/disabling my allow policy for ifconfig.

Turns out it does seem like systemd-resolved cache responses :(

Seems like queries are just sent to `127.0.0.53:53` where the cache just responds and this cache is as long as the TTL so that's why it only happens when going from disable to enable and not the other way around.

Using etc-resolv-conf "fixes" this for me. Does the same happen for you?

**Comment by ReactorScram** [comment]
I saw `Note: Users will always belong to the Everyone group.` even though it's a service account so that's why I assumed. 
Opened a ticket asking to clarify https://github.com/firezone/firezone/issues/5064

**Comment by ReactorScram** [comment]
Yeah I'm seeing the same thing:
- `etc-resolv-conf` doesn't have this issue (but I had to set 1.1.1.1 as my upstream resolver, resolv.conf and systemd-resolved didn't seem to play along)
- Removing the actor from the group applies instantly even with `systemd-resolved`

**Comment by conectado** [comment]
> Yeah I'm seeing the same thing:
> 
>     * `etc-resolv-conf` doesn't have this issue (but I had to set 1.1.1.1 as my upstream resolver, resolv.conf and systemd-resolved didn't seem to play along)
> 
>     * Removing the actor from the group applies instantly even with `systemd-resolved`

Yeah, removing works instantly because our TTL is 1 but probably the real TTL is much greater and systemd-resolved caches it as long as the TTL (or at least hinted by it)

Even with #4994 this won't be solved since once the IP, but-- maybe a simple solution is mangling the DNS response to always have a low TTL (though this would only work with UDP requests), then we could even do the caching ourselves.

**Comment by conectado** [comment]
I mean [here](https://github.com/firezone/firezone/blob/84cd1574ffbecf5ee5ac5decfe861503b72aaf41/rust/connlib/tunnel/src/dns.rs#L185-L195) we can add something like:

```rs
message.answers_mut().iter().for_each(|a| a.set_ttl(1));
```

**Comment by jamilbk** [comment]
I don't think TTL is a reliable means of controlling cache behavior in stub resolvers. Isn't the solution here to flush `systemd-resolved`'s DNS cache upon connecting Firezone?

**Comment by ReactorScram** [comment]
Yeah `resolvectl flush-caches` might be the command we want. If that doesn't delete `/home` or anything

Edit: Docs clarify that `resolvectl` replaces `systemd-resolve` https://manpages.ubuntu.com/manpages/focal/man1/resolvectl.1.html

**Comment by ReactorScram** [comment]
I'm changing the title back because the replication steps are known to work but I'm still checking out the root cause(s)

**Comment by ReactorScram** [comment]
I think it's something more subtle than just not flushing the cache, because it replicated on Windows with the headless Client, and I see this line about flushing the Windows DNS cache in the logs https://github.com/firezone/firezone/blob/a7b14229fca94efd59aac680cecf448f5bca9321/rust/connlib/tunnel/src/device_channel/tun_windows.rs#L250

**Comment by conectado** [comment]
> I think it's something more subtle than just not flushing the cache, because it replicated on Windows with the headless Client, and I see this line about flushing the Windows DNS cache in the logs
> 
> https://github.com/firezone/firezone/blob/a7b14229fca94efd59aac680cecf448f5bca9321/rust/connlib/tunnel/src/device_channel/tun_windows.rs#L250

@ReactorScram  For what I can see `flush_routes` is only called for `set_routes` not `add_routes` nor `remove_routes`, for most of normal operation only the latter 2 are called.

**Comment by ReactorScram** [comment]
Okay. So it's not just "Flush when we connect", but "Flush when we connect, or when we add or remove routes"? Do we need to flush when we call `set_dns` too? I don't fully understand what's happening but it's something like, Firezone's stub returns the real IP of a Resource, the OS caches that, and then we don't flush (since the Client is already running and the tunnel is already up), and then we change the policies and the OS needs to be flushed again, right?

**Comment by ReactorScram** [comment]
I really wish I could get this tested in CI but once again, can't do it with no portal and no mock portal 🤔

**Comment by conectado** [comment]
> Okay. So it's not just "Flush when we connect", but "Flush when we connect, or when we add or remove routes"? Do we need to flush when we call `set_dns` too? I don't fully understand what's happening but it's something like, Firezone's stub returns the real IP of a Resource, the OS caches that, and then we don't flush (since the Client is already running and the tunnel is already up), and then we change the policies and the OS needs to be flushed again, right?

Yeah, you got that right:
1. Query is sent through Firezone's stub resolver
2. Response is forwarded back to os's stub resolver
3. It has a TTL of X and it's cached for that long
4. Resource is added
5. Before query can even hit Firezone's stub resolver the os's stub resolver responds with the cached record

**Comment by conectado** [comment]
> I really wish I could get this tested in CI but once again, can't do it with no portal and no mock portal 🤔

Once we have a REST API we could use that, but for now I think we can use, in the docker tests, we can actually execute commands for the api using `iex remote`

**Comment by ReactorScram** [comment]
Yeah. But running the tunnel inside a unit test would be even easier, then I could run that test locally too

**Comment by ReactorScram** [comment]
> @ReactorScram For what I can see `flush_routes` is only called for `set_routes` not `add_routes` nor `remove_routes`, for most of normal operation only the latter 2 are called.

It looks like those are private functions though, and `set_routes` has the only call sites for them?

https://github.com/firezone/firezone/blob/a7b14229fca94efd59aac680cecf448f5bca9321/rust/connlib/shared/src/tun_device_manager/linux.rs#L162-L168

https://github.com/firezone/firezone/blob/a7b14229fca94efd59aac680cecf448f5bca9321/rust/connlib/tunnel/src/device_channel/tun_windows.rs#L129-L135

And when I enable the policy, the Windows headless Client shows the resource being added, but it doesn't show `add_route` or `remove_route` being called, even though I added `tracing::debug!` calls there, and I see it adding routes at startup.

I think that's because it adds the entire CGNAT CIDR all at once:

```
2024-07-03T17:46:28.817478Z DEBUG firezone_tunnel::device_channel::tun_windows: add_route route=V4(Ipv4Network { network_address: 100.96.0.0, netmask: 11 })
```

**Comment by ReactorScram** [comment]
I'll see if flushing on `on_update_resources` does anything 🤔
