### ISSUE TITLE
connlib: packets are routed based on connected gateways and not resources

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5054]
#### Describe the bug

We currently have a mismatch in how we handle the first and subsequent packets of overlapping IP ranges of two resources.

#### To Reproduce

1. Add resource `foo` with IP range `0.0.0.0/8` accessible via gateway A
2. Send a packet and establish a connection to gateway A
3. Add resource `bar` with IP range `0.0.0.0/16` (overlapping but more specific) accessible via gateway B
4. Send a packet to the narrower range (`bar`)
5. Packet will be routed to gateway A because we check which IP ranges gateway A covers (based on all the resources we connected to)

#### Expected behavior

Packet in (5) should be routed to gateway B.

**Comment by thomaseizinger** [comment]
I discussed this with @conectado. The fix for this is easy, we simply need to always check the `longest_match` of each incoming packet against the list of resources and route it to the gateway that is responsible for serving this particular resource.

For now, I'll implement the current behaviour in my tests in #4728 and we can then fix it in a separate PR.

**Comment by jamilbk** [comment]
Fix sgtm!

**Comment by jamilbk** [comment]
Note this should apply for DNS matches too ideally (if it doesn't already).
