### ISSUE TITLE
Failure to install on freshly deployed Fedora 35

### ISSUE THREAD

**Issue by harishpillay** [CloudFire-LLC/cloudfire#511]
I followed the instructions to install (https://docs.firez.one/docs/deploy/server/) and am hitting an issue with when chef is invoked in the install script. The output from /var/opt/firezone/cache/cache/chef-stacktrace.out.txt is appended.

Fully updated F35, "dnf install wireguard*" all done.

Thanks.

Harish

```
[chef-stacktrace.out.txt](https://github.com/firezone/firezone/files/8357804/chef-stacktrace.out.txt)
```

**Comment by jamilbk** [comment]
Hey @harishpillay thanks for the report! This is a known issue and will be fixed in the next release. Firezone requires a cron implementation to handle the logrotate functionality. The fix is to simply install a cron implemention like so: `sudo dnf install -y cronie-anacron`.

See #479 for more.

**Comment by harishpillay** [comment]
Thanks. And now I could proceed.
