### ISSUE TITLE
connlib: unify packet routing between CIDR and DNS resources

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5114]
This is a follow-up from a discussion in https://github.com/firezone/firezone/pull/5082#discussion_r1612425212.

I think it might make sense to unify how we route packets in connlib, in particular, have every packet go through the same look-up process, regardless of whether the IP belongs to a CIDR resource or is an IP that we resolved for a DNS resource because, ultimately, it shouldn't matter for connlib.

With the above PR, we always route a packet to the configured gateway that got assigned to a resource. CIDR resources and DNS resources already uses non-overlapping IP ranges so they can be tracked in a single "routing table".

I think this would be much easier to understand conceptually and would emphasize even more that with https://github.com/firezone/firezone/issues/4994, we are essentially "just" building a DNS resolver that otherwise doesn't interfere with how connlib routes packets to gateways.

**Comment by jamilbk** [comment]
I think is done with the DNS refactor?

**Comment by thomaseizinger** [comment]
Conceptually yes, there are still different routing tables but that may not be worth unifying. What do you think @conectado?

I was thinking we could have an `IpNetworkTable` of `ResourceIds` and all resolved DNS IPs also get added to that and so would CIDR resources.

**Comment by conectado** [comment]
> Conceptually yes, there are still different routing tables but that may not be worth unifying. What do you think @conectado?
> 
> I was thinking we could have an `IpNetworkTable` of `ResourceIds` and all resolved DNS IPs also get added to that and so would CIDR resources.

@thomaseizinger  I'm changing the packet routing a lot for #4789 with the current model I'm working this will end up happening as part of that PR! And I'm planing to have it ready early this week. So let's wait until then.

But to give a quick overview of how that will work is: a routing table which is an `IpNetworkTable` and when adding any resource or when resolving a DNS resource the routing table would be updated, similarly to what's described in this PR. With the only difference that each entry on the table would point to a `RangeMap` that also points to a `ResourceId`. Will go into more details when I have the initial implementation done.

**Comment by jamilbk** [comment]
I think this is done?
