### ISSUE TITLE
Do you plan to support multiple wireguard interfaces?

### ISSUE THREAD

**Issue by svenwanzenried** [CloudFire-LLC/cloudfire#513]
Thank you for this fine piece of software. I've been searching for a simple and user friendly wireguard GUI for some time and I think I may have found it now.
Out of curiosity I wanted to ask, if you plan to implement multiple wireguard interfaces / multiple address ranges in the future? Where I could assign different users to different nets with different rules. Maybe even assign different devices of the same user to different nets.

**Comment by jamilbk** [comment]
Hey @svenito92 absolutely. It's a feature request we've gotten in different channels a few times. Things have been crazy these past few weeks, but we plan to have this within the next major release or two.

Thanks for the suggestion!

**Comment by svenwanzenried** [comment]
Thanks @jamilbk for the quick reaction.
Nice to hear that! In the mean time I will probably just use multiple instances of firezone on individual VMs.
I want to point out , that I really like your installation script, that makes installation so easy. As fond as I am of Docker, for this kind of security relevant service I prefer a separate VM with only firezone on it. So docker would only be an additional layer to maintain in my case. So thanks for providing so easy installation!
