### ISSUE TITLE
Docker Gateway not starting on Raspberry Pi

### ISSUE THREAD

**Issue by elangelo** [CloudFire-LLC/cloudfire#5139]
#### Is your feature request related to a problem? Please describe.

I would like to run the firezone gateway on a raspberry pi with a docker image

#### Describe alternatives you've considered

I now run it as a systemd service

**Comment by ReactorScram** [comment]
I think we do build the Gateway for aarch64, I see it here https://github.com/firezone/firezone/pkgs/container/gateway

Does `docker pull ghcr.io/firezone/gateway:1.0.5-49a965a6867aef90952252b6a30b37d2660c1f15@sha256:68c872831900536633d8908aa1c51171f1c5fd1f1161f6683fc0d56e4174e45d` work on your RPi? It worked on my aarch64 Ubuntu VM.

**Comment by elangelo** [comment]
that worked like a threat.... so what is missing then? just a tag? I have no idea how multi-arch image tags are supposed to work

**Comment by ReactorScram** [comment]
Me neither, I've only done simple stuff with Docker. @jamilbk might know?

**Comment by jamilbk** [comment]
> that worked like a threat.... so what is missing then? just a tag? I have no idea how multi-arch image tags are supposed to work

I'm not sure I'm following. Our published images are multi-platform images. You shouldn't need to do anything special to use them -- Docker should pick the right one when you do `docker pull ghcr.io/firezone/gateway:1`.

If that's not the case, could you show the specific error you're getting?

**Comment by elangelo** [comment]
OK you are right. The image that was pulled was actually arm64. 
I was a bit quick with my conclusions apparently.
I was trying to run a gateway from my r.pi. Used the docker command that was suggested on the 'register new site gateway' . The container is running but it never actually registered. I jumped conclusions and thought I just pulled the wrong image architecture... but something else must be going on.
docker logs shows no output whatsoever

**Comment by jamilbk** [comment]
@elangelo We've seen this behavior if the Docker container doesn't have DNS working properly. Can you exec into the container and ensure `api.firezone.dev` resolves and is reachable?

**Comment by elangelo** [comment]
that seems to be the issue indeed. good catch, i'll close the ticket then
```
/bin # nslookup api.firezone.dev
;; connection timed out; no servers could be reached
```

**Comment by ReactorScram** [comment]
> docker logs shows no output whatsoever

Hm we should probably have some logs if the portal can't be resolved

We could replicate that by putting in a bogus API like `wss://does-not-exist.example.com`

**Comment by jamilbk** [comment]
It _should_ time out with an error that prints to the console, but this may be currently affected by #5141 perhaps
