### ISSUE TITLE
Mobile popups are  rather small and unusable

### ISSUE THREAD

**Issue by martijndeb** [CloudFire-LLC/cloudfire#514]
When using a mobile device, the popups could greatly benefit from having a width of at least 90%. Even better they could be full size.

It could be easily solved for instance by adding a CSS media query for smaller screens like so:

```
@media (max-width: 768px) {
  .modal-card{
    width: 90%;
  }
}
```

![Screenshot 2022-04-03 134932](https://user-images.githubusercontent.com/60222/161426541-f4a6b4cb-4ece-4b54-b341-9f23943afc2e.png)

**Comment by jamilbk** [comment]
Thanks for the suggestion! Hmm this should already be set here: https://github.com/firezone/firezone/blob/master/apps/fz_http/assets/local_modules/admin-one-bulma-dashboard/src/scss/_theme-firezone.scss#L136

Looks like it's not being applied for some reason. I'll take a look!
