### ISSUE TITLE
Gateway upgrade notification

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5140]
Send an email to admins when a Gateway upgrade is available.

Configurable on Sites.

**Comment by jamilbk** [comment]
Careful not to spam this - might to limit it to 1x per week.

**Comment by thomaseizinger** [comment]
> Careful not to spam this - might to limit it to 1x per week.

Show a badge next to the gateway too?

**Comment by jamilbk** [comment]
Just a thought - might be good to have these also in Weekly Report scorecard email.

- Gateways out of date
- Clients out of date
- Metrics
- etc

**Comment by bmanifold** [comment]
What are we using for the source of truth for the latest gateway version?

**Comment by thomaseizinger** [comment]
> What are we using for the source of truth for the latest gateway version?

https://github.com/firezone/firezone/blob/947db254cc968ca0f4112d0aa54f78b3131700c6/scripts/Makefile#L23

You can put a

```
# mark:current-gateway-version
```

Wherever you need it in the source code and it will be auto-updated on rebuilds. If you need it dynamically, I would hit the GH releases API and look for the latest Gateway release.

**Comment by bmanifold** [comment]
Yeah, I think I'll need it dynamically, because we can release the gateway without deploying the portal right?

**Comment by jamilbk** [comment]
@bmanifold correct

**Comment by bmanifold** [comment]
Just marking down some notes from discussion with @jamilbk 

- This will be an opt-in feature
- Only online gateways will be checked at the time the weekly job is run
- The email portion of this feature will only be for paid accounts
