### ISSUE TITLE
Gateway script doesn't have a default log level

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5141]
#### Describe the bug

Customer had DNS issues but we didn't have logs so we didn't know what was happening.

#### To Reproduce

_Steps to reproduce the behavior._

#### Expected behavior

_A clear and concise description of what you expected to happen._

#### Screenshots / Logs

_If applicable, add screenshots and log traces to help debug your problem **with
any sensitive data removed**._

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_
- _Firezone Version (e.g. 1.0.0 or N/A):_
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

_Add any other context about the problem here._

**Comment by jamilbk** [comment]
This relevant? https://github.com/firezone/firezone/commit/6f3ac132aeaeab2568e81ccde1f8fee94efbdd45

**Comment by thomaseizinger** [comment]
> This relevant? [6f3ac13](https://github.com/firezone/firezone/commit/6f3ac132aeaeab2568e81ccde1f8fee94efbdd45)

Don't think so. This particular gateway was started via docker (should have mentioned that), not systemd. It is the docker command generated in the portal I believe?

**Comment by ReactorScram** [comment]
In the debug IPC service I force the filter to `INFO` if `RUST_LOG` isn't set, using `with_default_directive`: https://github.com/firezone/firezone/blob/d561e0ee0d82493e0169d231f30f81334652171b/rust/headless-client/src/lib.rs#L572

We could hard-code that here and then all the CLI Clients and Gateway and stuff will default to INFO https://github.com/firezone/firezone/blob/d561e0ee0d82493e0169d231f30f81334652171b/rust/firezone-cli-utils/src/lib.rs#L12-L14

**Comment by thomaseizinger** [comment]
Yeah that is a good idea!
