### ISSUE TITLE
Allow option to configure whether users are auto-created from OIDC-backed logins.

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#515]
Add a configuration option, `default['firezone']['authentication']['auto_create_users']` that determines whether users are created when signing in via OIDC for the first time.

This will allow admins to only create users they wish to allow into the instance (leaving the password empty).

**Comment by rchekhina** [comment]
HI,

We want to limit users from our google organization that can create an account on firezone because they mustnt to access private resources on your network.

**Comment by jamilbk** [comment]
Related to https://github.com/firezone/firezone/issues/585

**Comment by jamilbk** [comment]
@rchekhina #728 will fix this and be available in the next release.
