### ISSUE TITLE
integration with letsencrypt to create SSL certificate and manage auto-renewals

### ISSUE THREAD

**Issue by rchekhina** [CloudFire-LLC/cloudfire#524]
HI,

Can you integrate letsencrypt to create SSL certificate and manage auto-renewals.

Thanks in advance.

**Comment by jamilbk** [comment]
@rchekhina Already in our backlog! Planning to add a `certbot` service that provisions SSL certs for the `nginx` service.

**Comment by princemaple** [comment]
Replacing nginx with [caddy](https://caddyserver.com/) will do

**Comment by rchekhina** [comment]
Ok perfect thank you very much.

**Comment by fliphess** [comment]
@jamilbk I have a working letsencrypt setup for firezone that I'm now trying to port to chef.
Would it be appreciated if I create an MR for it?

**Comment by souhaiebtar** [comment]
@fliphess  can you please share it with us ?

**Comment by fliphess** [comment]
@souhaiebtar I can share the configuration, but running `firezone-ctl reconfigure` removes it and it still requires some manual commands and packages which is not ideal... 

I'd rather create an MR that allows setting it up using chef to save the firezone devs from all the additional support requests that my instructions would result in :)

**Comment by jamilbk** [comment]
@fliphess 

This is awesome! Thank you so much.

Let us know if we can help in any way. Curious to hear your thoughts on your approach. Least friction approach would probably be adding `certbot` to the Omnibus build and making it a new Runit service alongside `nginx`, `postgres`, `phoenix`, and `wireguard`

**Comment by fliphess** [comment]
@jamilbk Sorry! Due to some unforeseen busyness with another project and work I'm currently not working on this. 

It took me a bit more time than expected because instead of installing the dependencies using a local package manager, I think it should be added to the bundle from source. 

What might be an easy option in the meantime is to add an include statement in the nginx config so that people can create additional configuration for nginx to set it up theirselves (I can push a working fix for that within days)

**Comment by jamilbk** [comment]
@fliphess No worries :-). Any contribution is welcomed with open arms.

We'll likely be switching from Nginx to caddy as the bundled proxy in the future (which gives us this out of the box), but this will still be useful for users wanting to use Nginx.

**Comment by jamilbk** [comment]
Relevant thread: https://discourse.firez.one/t/certbot-bundled-nginx-and-acme-http-01-challenge/107/4

I think we could could accomplish this fairly straightforward with a boolean config setting that generates this config when enabled.

Adding an option to include a custom nginx config could be useful as well.

Thanks for the writeup @gbe0 :-).

**Comment by conectado** [comment]
Refs #779

**Comment by jamilbk** [comment]
Coming in 0.5.0
