### ISSUE TITLE
Port forwarding issue

### ISSUE THREAD

**Issue by harishpillay** [CloudFire-LLC/cloudfire#527]
I've gotten 0.3.2 installed on a Fedora 35 instance in a VM.

The VM has ports forwarded to it from the router so instead of https://myfirezone.my.dom is https://myfirezone.my.dom:50443. 

a) click on the login and the URL changes to https://myfirezone.my.dom:50443/auth/identity
b) provide the emailID and password ahd it then switches to https://myfirezone.my.dom/auth/identy/callback. It is missing the port 50443 and so i can't proceed.

Thanks.

**Comment by jamilbk** [comment]
Hey @harishpillay -- thanks for the report :-). `0.3.3` fixes this issue. You'll want to set `default['firezone']['external_url'] = 'https://myfirezone.my.dom:50443/'` in `/etc/firezone/firezone.rb`. This will be used for all URLs generated by the application.

That should fix it!

**Comment by harishpillay** [comment]
thanks.
