### ISSUE TITLE
snownet spams log with "Adding TURN server" if STUN/TURN is blocked

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5281]
Customer's network is blocking STUN/TURN, causing snownet to emit a log each event loop iteration (I think) with "Adding TURN server":

```
...
Jun 07 13:52:54 foo sudo[1250]: 2024-06-07T17:52:54.531134Z  INFO snownet::node: Added new TURN server id=a4a5b9fd-f2a5-4f93-b5bb-aabb055b62c3 address=Dual { v4: 34.89.103.253:3478, v6: [2600:1900:40c0:ae33:0:1a::]:3478 }
Jun 07 13:52:54 foo sudo[1250]: 2024-06-07T17:52:54.537403Z  INFO snownet::node: Added new TURN server id=a4a5b9fd-f2a5-4f93-b5bb-aabb055b62c3 address=Dual { v4: 34.89.103.253:3478, v6: [2600:1900:40c0:ae33:0:1a::]:3478 }
Jun 07 13:52:54 foo sudo[1250]: 2024-06-07T17:52:54.546573Z  INFO snownet::node: Added new TURN server id=a4a5b9fd-f2a5-4f93-b5bb-aabb055b62c3 address=Dual { v4: 34.89.103.253:3478, v6: [2600:1900:40c0:ae33:0:1a::]:3478 }
...
```

**Comment by jamilbk** [comment]
It would be extremely helpful in this case if we can time this out or otherwise somehow detect STUN/TURN connectivity issues and log `ERROR: STUN/TURN timed out. Blocked?` so that this can be debugged by the customer/user.

**Comment by thomaseizinger** [comment]
Can we have more logs? I am surprised blocked traffic causes this.

The expected behaviour is several messages about timeouts that eventually stop.

We can definitely add something in case _none_ of the relays got any reply. We can't distinguish that case from all relays being down but I guess that is less likely.

**Comment by jamilbk** [comment]
Sent on Slack

**Comment by thomaseizinger** [comment]
The logs show some odd behaviour at:

- `2024-06-07T17:52:53.069945Z`: Relay `a4a5b9fd-f2a5-4f93-b5bb-aabb055b62c3`
- `2024-06-07T17:58:36.557685Z`: Relay `2d3a2a0a-d7d2-42a1-9b2a-877eea545fcd`

Could it be that the two relays got just deployed at that time and we receive the `relays_presence` message multiple times?

The spammy logs did not get emitted as part of setting up a connection but as part of getting sent `relays_presence` from the portal. We execute those one-by-one so if the portal sends us that message multiple times, we will see the same log over and over again.

The remaining logs show repeated connection attempts from different clients. I can add an additional log if we can't even perform STUN with the relay although we cannot definitely say that STUN is blocked. All we can detect is that we don't get a response from the relay so it could also be that the relay is down.

**Comment by jamilbk** [comment]
> The logs show some odd behaviour at:
> 
> * `2024-06-07T17:52:53.069945Z`: Relay `a4a5b9fd-f2a5-4f93-b5bb-aabb055b62c3`
> * `2024-06-07T17:58:36.557685Z`: Relay `2d3a2a0a-d7d2-42a1-9b2a-877eea545fcd`
> 
> Could it be that the two relays got just deployed at that time and we receive the `relays_presence` message multiple times?
> 
> The spammy logs did not get emitted as part of setting up a connection but as part of getting sent `relays_presence` from the portal. We execute those one-by-one so if the portal sends us that message multiple times, we will see the same log over and over again.
> 
> The remaining logs show repeated connection attempts from different clients. I can add an additional log if we can't even perform STUN with the relay although we cannot definitely say that STUN is blocked. All we can detect is that we don't get a response from the relay so it could also be that the relay is down.

He we haven't deployed recently though. Is there some other case where the portal sends relays presence message? Perhaps after the client signs in? If it's expected maybe that can be DEBUG
