### ISSUE TITLE
gateway: perform DNS resolution using hickory instead of libc

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5304]
Currently, we are using `libc` to perform DNS resolution on the gateway:

https://github.com/firezone/firezone/blob/e1877bc250d12dd88223cb3333160be63e2858c1/rust/gateway/src/eventloop.rs#L308-L326

The `Io` component within `firezone-tunnel` can already perform DNS resolution using hickory but today, that is only used by the client to foward DNS for non-resources.

Moving DNS resolution in the gateway also into `firezone-tunnel` would:

- help with better handling errors during DNS resolution as part of the normal flow (currently, the connection just fails)
- help with testing different scenarios when DNS resolution fails / times-out
- reuse more code between clients and gateways
- allow `firezone-gateway` to also work on Windows
- help with reducing `Eventloop` boilerplate on the gateway

**Comment by conectado** [comment]
Why we want to change it to hickory? Using the system's allows the gateway to just use the system's DNS without having to worry about changes and updates.

If we start using hickory now we need to worry about reading the system's dns and its changes which can get quite tricky

**Comment by thomaseizinger** [comment]
> Why we want to change it to hickory? Using the system's allows the gateway to just use the system's DNS without having to worry about changes and updates.
> 
> If we start using hickory now we need to worry about reading the system's dns and its changes which can get quite tricky

I guess it wouldn't have to be hickory, we could make the `Io` component configurable to also use `libc` if we wanted to?

**Comment by thomaseizinger** [comment]
Not a good idea, needs to be rephrased.
