### ISSUE TITLE
Basic monitoring and activity dashboard

### ISSUE THREAD

**Issue by gongjason** [CloudFire-LLC/cloudfire#537]
Activity reporting in the Web UI for:
* upload/download over time
* general performance (speed, dropped packets, connection issues)

This would be helpful for admins to diagnose issues and demonstrate Firezone is doing its job.

thanks @bcookatpcsd for the suggestion!

**Comment by jamilbk** [comment]
A first crack at this would be to pull the `wg show` information into the Web UI per device. We have an issue to track this here: #450 

Will close this in favor of tracking work on a stats dashboard there.
