### ISSUE TITLE
Feature Request: View data transferred between each device and server!

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#540]
This would be a very nice addition! :)

**Comment by jamilbk** [comment]
@DillFrescott Thanks for the suggestion! Something like wouldn't be too hard to add -- we already have a few asking for it here: #450 

I'll see if I can get to it in the next day or two. Parts of this functionality have already been completed -- just need to tie it up to the UI:

https://github.com/firezone/firezone/blob/master/apps/fz_vpn/lib/fz_vpn/cli/live.ex#L45

**Comment by jamilbk** [comment]
Going to close this as a dupe, but thanks again for the suggestion!
