### ISSUE TITLE
bug(gui-client): Tauri panic `FailedToReceiveMessage`

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5448]
#### Describe the bug

🤷‍♀️ 

#### To Reproduce

1. Reboot the system
2. Start the GUI
3. The GUI panics

I don't have a clue. This happened on the Windows Server 2022 VM after a fresh reboot, and I'd been AFK for 10 minutes. So the IPC service was idling smoothly, the system RAM couldn't be corrupted, the GUI just failed to start.

#### Expected behavior

The GUI should not panic for no reason on a perfectly fine system.

#### Screenshots / Logs

https://firezonehq.slack.com/archives/C067DSY7TFX/p1718820779141219
Logs are in the internal Slack in case they contain my IP or anything

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ GUI Client
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ MSI built by GitHub

Observed on:
- 1.0.9, resource-constrained Windows Server 2022 VM
- 1.1.2, Windows 11 dev laptop

#### Additional context

I'm finding a lot of Windows bugs today. I must have been under-testing it before.

**Comment by ReactorScram** [comment]
Happened just now on 1.1.2 on the Windows dev laptop. Same deal, I checked the logs and after a few minutes restarted the GUI and it was fine.

We haven't updated Tauri since 1.1.2, so this bug can probably still happen.

**Comment by jamilbk** [comment]
Think this might have been fixed? Could this have been related to the admin rights?

**Comment by ReactorScram** [comment]
It couldn't have been the admin thing because that always failed before the logs were opened.
I haven't seen it replicate. I wonder if it was a bug in upstream that got fixed
