### ISSUE TITLE
bug(gui-client/windows): Clear Logs button isn't working on `main`

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5453]
This is a user-facing bug that should stay in the user guide until it's closed
Supersedes #5257

#### Describe the bug

The logs aren't being cleared

#### To Reproduce

Click `Clear Logs`, nothing happens

#### Expected behavior

1. Expect the logs to be cleared
2. Expect at least the GUI logs to be cleared, even if the service logs can't be cleared
3. Expect an error message in the terminal / logs

#### Screenshots / Logs

The JS console is saying access denied, it's probably because we're trying to delete logs that the IPC service created.

Also there's two different shades in the background of the logs tab, it made me think the page wasn't loading
<img width="102" alt="image" src="https://github.com/firezone/firezone/assets/13400041/d507e03c-78ae-4f3e-9775-8c09af77ec42">

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 97cfb90cae
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11, maybe others
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Built from source in Parallels

#### Additional context

```[tasklist]
### Tasks
- [x] ~~Figure out how to do paired request-response over IPC~~
- [ ] See PR for remaining tasks https://github.com/firezone/firezone/pull/5890
```

**Comment by jamilbk** [comment]
Able to reproduce. Could we just send an IPC message to clear logs in both processes?

**Comment by ReactorScram** [comment]
We could do it while signed in, but the IPC connection is down while signed out. I could keep the IPC connection up at all times but then I need to redo the smoke test because right now it doesn't run the IPC service

**Comment by jamilbk** [comment]
Interesting. Yeah it might be good to have the IPC connection up at all times because it's our only way for a user to control the service?

I imagine exporting logs would require it too.

Otherwise any user that has authentication issues can't export logs to troubleshoot.

**Comment by ReactorScram** [comment]
There's a PR open for this, but if it's not important to users I'll start on #5846 instead

**Comment by ReactorScram** [comment]
Status: Nothing new. Still blocked on IPC refactors. This is the first thing where request-response is needed in IPC so I'd planned to rearrange things and just didn't get it merged both times
