### ISSUE TITLE
gui client - websocket encoding issue

### ISSUE THREAD

**Issue by gleam-ru** [CloudFire-LLC/cloudfire#5467]
#### Describe the bug

On some macos-devices connection stucks at "Loading resources...".
In logs I see strange message:

{"time":"2024-06-20T14:38:32.031742Z","target":"phoenix_channel","logging.googleapis.com/sourceLocation":{"file":"phoenix-channel/src/lib.rs","line":"357"},"severity":"DEBUG","backoff":"535.529012ms","maxElapsedTime":"Some(86400s)","message":"Reconnecting to portal on transient client error: websocket connection failed: UTF-8 encoding error"}

#### To Reproduce

Connect to firezone on macos device ¯\_(ツ)_/¯ 
Problem reproduces on one macos device and not reproduces on another one.
Versions of fz-client are same - 1.0.5 (1718231772)

#### Expected behavior

---

#### Screenshots / Logs

[connlib.2024-06-20-14-38-31.log](https://github.com/user-attachments/files/15917955/connlib.2024-06-20-14-38-31.log)
[2024-06-20T14:38:31.744Z.log](https://github.com/user-attachments/files/15917956/2024-06-20T14.38.31.744Z.log)

#### Platform (please complete the following information)

- macOS client
- server - 1.0.5, client - 1.0.5 (1718231772)
- macos ventura 13.5.1
- server - self-hosted, client - app store

#### Additional context

Firezone is under nginx reverse proxy.
Config:

proxy_read_timeout       90s;
proxy_connect_timeout    90s;
proxy_send_timeout       90s;
proxy_redirect           off;
proxy_busy_buffers_size  64k;
proxy_set_header         Host $host;
proxy_http_version       1.1;
proxy_set_header         Upgrade $http_upgrade;
proxy_set_header         Connection "upgrade";
proxy_set_header         X-Real-IP $remote_addr;
proxy_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header         X-Forwarded-Host $host;
proxy_set_header         X-Forwarded-Proto $scheme;
proxy_set_header         Proxy "";

**Comment by gleam-ru** [comment]
UPD: issue reproduces if main language of OS is different than "English"

**Comment by jamilbk** [comment]
Thanks for the report! We've tested with a few different languages successfully. Could you share the language/region setting in macOS that's causing the issue for you?

**Comment by gleam-ru** [comment]
region - Russia, language - Русский.

**Comment by jamilbk** [comment]
@gleam-ru thanks. This is a strange one. UTF-8 should support virtually any language, so the fact that the system is non-English is probably a red herring, and the actual issue may be related to TLS certs, some proxy in between, or some other issue localized to that machine.

**Comment by gleam-ru** [comment]
@jamilbk 
there are several machines with the same issue.
Proxy settings attached in my first message :)

If you need additional info - feel free to ask.

UPD: after change OS language to English everything works as expected (proxy settings and other settings are same).

**Comment by jamilbk** [comment]
Thanks for the added info. I've managed to replicate the issue. Will have a fix out shortly.

**Comment by jamilbk** [comment]
Issue stems from an upstream library. refs https://github.com/hyperium/http/issues/706
