### ISSUE TITLE
Self-serve seat counts

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5474]
Paying for 1 seat, but see this:

<img width="495" alt="Screenshot 2024-06-20 at 5 36 49 PM" src="https://github.com/firezone/firezone/assets/167144/90b695fb-ac1b-4811-ae51-05bcfefe0b09">

**Comment by jamilbk** [comment]
Hmm it doesn't seem like there's any way to change seat counts from the customer portal in Stripe?

<img width="404" alt="Screenshot 2024-06-20 at 6 53 45 PM" src="https://github.com/firezone/firezone/assets/167144/94c7c8ed-00f6-4cfb-aff8-226d4549b2ef">

**Comment by AndrewDryga** [comment]
<img width="1728" alt="Screenshot 2024-06-21 at 10 11 23" src="https://github.com/firezone/firezone/assets/1877644/08ab7709-aa6e-4428-a7dd-864fe146f2e7">

**Comment by AndrewDryga** [comment]
@jamilbk please DM me the account ID where that happens.

**Comment by AndrewDryga** [comment]
This was a miss-configuration on the Stripe for the Team plan.
