### ISSUE TITLE
Portal doesn't allow login with development version

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5481]
I think this may be a regression from https://github.com/firezone/firezone/commit/eb7b3f62ab65d21aeec027e0e94f6c1644c50473. Currently, I cannot login with a locally built client. It fails with:

```json
{"event":"phx_reply","ref":0,"topic":"client","payload":{"status":"error","response":{"reason":"join crashed"}}}
```

Mu user-agent is:

```
NixOS/24.11.0 (x86_64;6.8.12;) connlib/development
```

**Comment by thomaseizinger** [comment]
I noticed that connlib doesn't handle this case very well so I opened https://github.com/firezone/firezone/pull/5480.

**Comment by jamilbk** [comment]
@thomaseizinger Good catch -- the fix here is probably to set `FIREZONE_PACKAGE_VERSION` in your build env. https://github.com/firezone/firezone/pull/5344

This will allow testing the compat matrix too

**Comment by AndrewDryga** [comment]
@thomaseizinger can you please show HTTP requests that the connlib made? Probably the User Agent is invalid.

**Comment by jamilbk** [comment]
@AndrewDryga Yeah I know what the issue is -- it's `connlib/development`. I'll add a fix to set the version for development builds too so they don't fallback to that string.

**Comment by thomaseizinger** [comment]
> the fix here is probably to set `FIREZONE_PACKAGE_VERSION` in your build env. #5344

Hmm, that is a bit silly. I usually run the client using `cargo run` and use the same command from my shell history. I wouldn't want to have to make sure I have to set the correct version every time via an ENV var.

I'll think about this some more.
