### ISSUE TITLE
Form state is lost when navigating away or WebSocket sleeps

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5501]
- Go to app.firezone.dev
- Enter any account slug
- Navigate away (Click sign up, or wait until WebSocket sleeps (some browsers))
- Navigate back, form is reset

**Comment by AndrewDryga** [comment]
I don't think this would be easy to fix as we don't do anything special with the forms, it's just a nature of LiveView, unless we start storing form state in Local Storage (but then we can have security / cache invalidation issues)
