### ISSUE TITLE
Relayed connections fail seemingly randomly with "Packet is a STUN message but no agent handled it"

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5519]
I'm testing with a forced Relay connection on macOS. I'm blocking direct access to the Vultr stable Gateway in my firewall to make sure Relayed connections are used:

```
block drop out from any to 155.138.222.187
block drop out from any to 2001:19f0:5401:14df::
```

Things were mostly smooth all day, until a few minutes ago. Internet connectivity hung, no logs being printed in the Client (logLevel = `debug`). Quad9 is the upstream DNS, so it's possible access to this Resource went down and caused my Internet to "hang". Happened about an hour or two into my Client's auth session.

I verified no deploy was happening at this time. Gateway was running stable.

Here are the full Client logs:
[firezone_logs_2024-06-24T202406Z.zip](https://github.com/user-attachments/files/15960974/firezone_logs_2024-06-24T202406Z.zip)

And Gateway logs:

[logs.txt.zip](https://github.com/user-attachments/files/15960976/logs.txt.zip)

Seems that the TURN credentials expired somehow?

**Comment by AndrewDryga** [comment]
The relay credentials are valid for lifetime of your authorization which is ~1 week or until relay forgets it's secret (eg. reboots).

**Comment by thomaseizinger** [comment]
Some preliminary investigation results:

- The "Unallowed packet" logs are for one of GitHub's IPs.
- Prior to them being unallowed, there are multiple functional NAT sessions on the gateway.
- About a minute before the unallowed logs, the NAT session expires on the gateway.

@conectado I think one thing that happens here is that after an expired NAT session, we drop the mapping so any packets that are sent from that resource don't get translated and then show up as "Unallowed packet" on the client-side.

Should we extend the lifetime of the NAT sessions?

**Comment by thomaseizinger** [comment]
I think the problem might be this:

> snownet::allocation: Allocation is suspended

The gateway fails to use most if not all of its allocations and therefore the connection is broken.

**Comment by thomaseizinger** [comment]
Should we optimistically consider this fixed with https://github.com/firezone/firezone/pull/5512 merged?
