### ISSUE TITLE
Connectivity via IPv6 to IPv4-only resource does not work

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5535]
Haven't investigated in detail but @conectado already reported the same.

Opening this issue here to track it.

**Comment by jamilbk** [comment]
Hmm I don't think I'm having this issue. If I disable IPv4 in macOS, then ping the `9.9.9.9` resource it works. This is on Vultr though with the latest release Gateways.

Could it be an issue with the Gateway environment?

**Comment by thomaseizinger** [comment]
Try pinging `github.com`! Doesn't work for me.

```
❯ ping -6 github.com
PING github.com (fd00:2021:1111:8000::) 56 data bytes
^C
--- github.com ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7149ms
```

**Comment by jamilbk** [comment]
Working for me:

```
jamil@Airbook-Mac:~/Developer/firezone/firezone/terraform/examples/aws/nat-gateway [fg: 1] (feat/aws-example$*+%) % ping6 github.com
PING6(56=40+8+8 bytes) fd00:2021:1111::16:c3d3 --> fd00:2021:1111:8000::4
16 bytes from fd00:2021:1111:8000::4, icmp_seq=1 hlim=49 time=110.364 ms
16 bytes from fd00:2021:1111:8000::4, icmp_seq=2 hlim=49 time=103.209 ms
```

Maybe you need working IPv6 in your Client's net?

**Comment by thomaseizinger** [comment]
Interesting, I wonder what is going on there! Could be a Linux vs MacOS thing again?

@ReactorScram Could you check if this works on Windows? (Haven't setup a VM yet, sorry)

**Comment by thomaseizinger** [comment]
> Working for me:
> 
> ```
> jamil@Airbook-Mac:~/Developer/firezone/firezone/terraform/examples/aws/nat-gateway [fg: 1] (feat/aws-example$*+%) % ping6 github.com
> PING6(56=40+8+8 bytes) fd00:2021:1111::16:c3d3 --> fd00:2021:1111:8000::4
> 16 bytes from fd00:2021:1111:8000::4, icmp_seq=1 hlim=49 time=110.364 ms
> 16 bytes from fd00:2021:1111:8000::4, icmp_seq=2 hlim=49 time=103.209 ms
> ```
> 
> Maybe you need working IPv6 in your Client's net?

You are on staging yeah?

**Comment by jamilbk** [comment]
> > Working for me:
> > ```
> > jamil@Airbook-Mac:~/Developer/firezone/firezone/terraform/examples/aws/nat-gateway [fg: 1] (feat/aws-example$*+%) % ping6 github.com
> > PING6(56=40+8+8 bytes) fd00:2021:1111::16:c3d3 --> fd00:2021:1111:8000::4
> > 16 bytes from fd00:2021:1111:8000::4, icmp_seq=1 hlim=49 time=110.364 ms
> > 16 bytes from fd00:2021:1111:8000::4, icmp_seq=2 hlim=49 time=103.209 ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe you need working IPv6 in your Client's net?
> 
> You are on staging yeah?

yes

**Comment by jamilbk** [comment]
@thomaseizinger ah -- I think you guys are using a different `github.com` than me.

Try the one on Vultr (systemd). It looks like the one in Docker on AWS `main` is causing your issue I bet.
