### ISSUE TITLE
Consider stopping IPC service when stopping GUI

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5550]
If the GUI fails to launch or crashes, the IPC runs in zombie mode with no ability to control. Only a reboot fixes it.

Perhaps instead we should stop the IPC service if the pipe disconnects. And only start it when launching the GUI app.

Marking as Tauri because I think it's a Linux issue too?

**Comment by ReactorScram** [comment]
A fix merged for this yesterday https://github.com/firezone/firezone/commit/058b04178a4828c95c4d23136fe2d8b2bb5b1778
Sounds like a dupe of https://github.com/firezone/firezone/issues/5450

**Comment by ReactorScram** [comment]
Also the IPC service runs with elevated privileges so I don't think we can allow the GUI to start it unless we do something like, put all the connlib stuff into a subprocess and restart that process. (Like a Chromium web content worker) But this was a problem of just bailing out when we shouldn't bail out, so we don't need a subprocess for that

**Comment by ReactorScram** [comment]
Wait, did this also happen on 409039a?

**Comment by jamilbk** [comment]
> Wait, did this also happen on [409039a](https://github.com/firezone/firezone/commit/409039afde30ec51f7f3522d856f5b0e343ae50d)?

Yeah I think so -- it happened with the last `main` windows client built this morning (~3 hours ago).

**Comment by jamilbk** [comment]
> Also the IPC service runs with elevated privileges so I don't think we can allow the GUI to start it unless we do something like, put all the connlib stuff into a subprocess and restart that process. (Like a Chromium web content worker) But this was a problem of just bailing out when we shouldn't bail out, so we don't need a subprocess for that

I gotcha. Can we disconnect the tunnel then if the GUI isn't connected? Then we can leave the service running harmlessly in the BG.

If it's modifying network stuff without a GUI to manage it then we have an accidental headless client.

**Comment by ReactorScram** [comment]
We do disconnect the tunnel, right now connlib is supposed to start when the GUI asks for a connection and drop when the GUI disconnects 🤔 

The only thing the IPC service should do without a GUI connected is deactivate DNS control (which is supposed to be safe and idempotent) and then loop around to wait for another GUI. If you have matching GUI and IPC logs showing the GUI quitting and the IPC service continuing to do stuff, that would be very interesting

**Comment by jamilbk** [comment]
> If you have matching GUI and IPC logs showing the GUI quitting and the IPC service continuing to do stuff, that would be very interesting

Challenge accepted, hold my beer!

**Comment by jamilbk** [comment]
You're right -- I was unable to get the IPC service into a zombie connected state without the GUI running.

Would it be hard to show an error if the IPC service isn't running when the GUI starts? Or if it isn't able to connect? I think that might at least let the user know it "tried" and to check the log directory.

I thought we had that error but what was happening for me was that I quit Firezone completely (users might do this from Task Manager) and then when I tried to re-launch the GUI, it just didn't open.

We could say something like "Unable to connect to Firezone IPC service. Is it running?"

**Comment by ReactorScram** [comment]
> show an error if the IPC service isn't running when the GUI starts?

I was working on that last week, it needs conflicts resolved now and then I need to have conectado review it https://github.com/firezone/firezone/pull/5454

There's a lot of WIP

**Comment by ReactorScram** [comment]
> I was unable to get the IPC service into a zombie connected state without the GUI running.

We should be okay then, so I'm closing this as unplanned. There's been a lot of bugs the last week or two but these ones did get fixed. The IPC service could still panic or something, but that's less likely and hasn't been seen yet.
