### ISSUE TITLE
portal: consider not opening an alert when enabling / disabling policies

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5583]
More of a UX idea. Disabling a policy is destructive but I'd be surprised if there are actually "accidental" clicks on the "Disable policy" button. Plus, we could delay the actual action by a few seconds to allow users to toggle it back in case they did click it accidentally.

I noticed this because in some testing, I had to disable quite a few policies and having to confirm each one was a bit tedious.

**Comment by jamilbk** [comment]
I think the fix here is #5508. With the current design there are just too many to manage.

**Comment by jamilbk** [comment]
Yeah going to make the call to close this in favor of #5508. I do think it's important to confirm policy changes since those form buttons can be triggered accidentally with a keypress.
