### ISSUE TITLE
"Dead IPs detected" spams Gateway log

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5593]
When wildcards like `*.google.com` are used, the log is spammed with messages regarding matched domains that may not be seen again for quite a while.

Maybe this log should be disabled or moved to `debug`?

<img width="2831" alt="Screenshot 2024-06-27 at 2 50 54 AM" src="https://github.com/firezone/firezone/assets/167144/8c822d1f-a282-4f2e-930c-1520955bd613">

**Comment by thomaseizinger** [comment]
Hmm, so this means we sent traffic to this domain but never received any response. I'll take a look at the code again tomorrow.

**Comment by thomaseizinger** [comment]
Looking into this now.
