### ISSUE TITLE
bug(client): Cloudflare packet loss test shows "ICE connection timeout"

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5596]
#### Describe the bug

Cloudflare's speed test works except that the packet loss part, which uses WebRTC to send UDP packets, fails

#### To Reproduce

1. Sign in to Firezone staging
2. Run the test at https://speed.cloudflare.com
3. The packet loss section of the test will fail

#### Expected behavior

If Firezone is off I get 100% packets received.
<img width="624" alt="image" src="https://github.com/firezone/firezone/assets/13400041/af4ba19c-ac3b-4eba-8662-0dd7feb3e809">

#### Screenshots / Logs

<img width="624" alt="image" src="https://github.com/firezone/firezone/assets/13400041/3f8e600e-00f1-4f3d-a8fb-337b31f5d3df">

#### Platform (please complete the following information)

macOS

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ macOS Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 1.1.0
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ macOS 14.3.1 Sonoma
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ App Store

Windows

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 7e67fa55f9a (1.1.0)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11 in Parallels VM
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Built from source with `--release` and run with the debug IPC service

Probably affects Linux too

Edit: Strangely I got it to pass with 1.2% loss on Windows while working on the fix for #5589 

#### Additional context

Noticed while investigating #5589

**Comment by jamilbk** [comment]
refs #5274

**Comment by conectado** [comment]
> refs #5274

Yeah, that's probably it, if you can somehow connect to cloudflare using cidr instead, like adding the ip as a resource instead of the dns name, you won't see this.

I do see speed.cloudflare.com always with the same IP, so it might be possible to test it

**Comment by ReactorScram** [comment]
okay this is probably a duplicate then

**Comment by thomaseizinger** [comment]
For reference, one needs to add `turn.cloudflare.com` as a resource for this to work. Otherwise the TURN connection fails (at least in Firefox). Chrome and Safari appear to not use the primary interface for this but instead gather candidates on all interfaces, effectively bypassing the tunnel.
