### ISSUE TITLE
gateway: allow NATing ICMP messages other than echo requests & replies

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5614]
Currently, the NAT table in the gateway can only route ICMP requests and replies but not ICMP error messages. The error messages don't contain an identifier and can thus not directly be mapped. However, RFC6146 outlines strategies of how they can be mapped nonetheless. We should implement this instead of silently dropping them.

See https://datatracker.ietf.org/doc/html/rfc6146#section-3.6.1.

**Comment by jamilbk** [comment]
When does our NAT64 implementation take effect? I think it's when we resolve the A and AAAA records right?

Can we not just add a second condition to that logic to activate it when the Gateway receives an ICMP error?

We wouldn't need to propagate ICMP back to the client if that works.

**Comment by thomaseizinger** [comment]
We establish the mapping when we resolve the addresses yeah. Changing the mapping on the fly would mean that we probably break all existing connections for that domain and client.

The NAT64 logic is merely a by-product of having to assign our proxy IPv6 addresses to something. If there are no resolved IPv6 addresses, we have to cycle around and assign them to IPv4 ones.

How to NAT ICMP unreachable errors is well-defined, we are just not doing it yet. I think we should try that first.

**Comment by thomaseizinger** [comment]
I guess we could only re-assign that one address when we receive an ICMP unreachable. It is an interesting idea although it feels like we are trying to be a bit too clever? I think transparency might be the better solution here.

**Comment by thomaseizinger** [comment]
> However, RFC6146 outlines strategies of how they can be mapped nonetheless. We should implement this instead of silently dropping them.
> 
> See https://datatracker.ietf.org/doc/html/rfc6146#section-3.6.1.

This is actually irrelevant for us because we don't algorithmically generate the IPv6 address from the IPv4 address.
