### ISSUE TITLE
Android logFilter changes aren't applied until app is forcibly restart instead of connlib `disconnect` & `connect`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5634]
This seems like a bug introduced in https://github.com/firezone/firezone/pull/5558 possibly.

Log filter changes require quitting the app and re-launching it to take effect. Perhaps they're set in the main thread and not reset when connlib `connect`s.

**Comment by jamilbk** [comment]
Android studio isn't ANSI-aware either :-(

```
handle_timeout{[3mid[0m[2m=[0m5a7e19cc-9928-4123-85bc-9e3d59d01ea6}: boringtun::noise::timers: KEEPALIVE(PERSISTENT_KEEPALIVE)
```

**Comment by thomaseizinger** [comment]
> Android studio isn't ANSI-aware either :-(

We disable ANSI so I am not sure that is related?

**Comment by thomaseizinger** [comment]
> This seems like a bug introduced in #5558 possibly.

I think this because we cache the logger in a `static`. There is a code comment about that. Should have already been the case prior to #5558.

**Comment by jamilbk** [comment]
> We disable ANSI so I am not sure that is related?

See the log output pasted above. It seems that logcat logs are still being written with ANSI colors? This is a new thing.

**Comment by jamilbk** [comment]
> > This seems like a bug introduced in #5558 possibly.
> 
> I think this because we cache the logger in a `static`. There is a code comment about that. Should have already been the case prior to #5558.

Maybe not that PR, but this hasn't always been the case. It was working, otherwise doing any kind of Android development becomes a hassle due to the default log level.

**Comment by thomaseizinger** [comment]
> > We disable ANSI so I am not sure that is related?
> 
> See the log output pasted above. It seems that logcat logs are still being written with ANSI colors? This is a new thing.

Do you get ANSI escape codes when do you `adb logcat`? Just want to make sure it is not related to Android Studio? Can you identify what exact escape code it is?

**Comment by thomaseizinger** [comment]
> > > This seems like a bug introduced in #5558 possibly.
> > 
> > 
> > I think this because we cache the logger in a `static`. There is a code comment about that. Should have already been the case prior to #5558.
> 
> Maybe not that PR, but this hasn't always been the case. It was working, otherwise doing any kind of Android development becomes a hassle due to the default log level.

I think we might be able to fix this using https://docs.rs/tracing-subscriber/latest/tracing_subscriber/reload/index.html.

**Comment by jamilbk** [comment]
> Do you get ANSI escape codes when do you adb logcat

I do, but my terminal interprets them. Android Studio doesn't unfortunately and they're printed with a bunch of codes like `�[3m`, `�[0m�[2m` and `�[0m`. This only applies to the logs emitted by connlib -- `Log.` calls are unaffected.

Is there a way to disable ANSI colors for logcat output but keep them for the file writer?

**Comment by jamilbk** [comment]
<img width="2117" alt="Screenshot 2024-06-29 at 11 52 56 PM" src="https://github.com/firezone/firezone/assets/167144/173ae0d1-1303-4bc2-a57e-ea510c35e6f5">

**Comment by thomaseizinger** [comment]
> > Do you get ANSI escape codes when do you adb logcat
> 
> I do, but my terminal interprets them. Android Studio doesn't unfortunately and they're printed with a bunch of codes like `�[3m`, `�[0m�[2m` and `�[0m`. This only applies to the logs emitted by connlib -- `Log.` calls are unaffected.
>
> Is there a way to disable ANSI colors for logcat output but keep them for the file writer?

They are already meant to be disabled: https://github.com/firezone/firezone/blob/53557f46e452c0fe5195a4326873753a356c6005/rust/connlib/clients/android/src/lib.rs#L137

I thought I didn't get them but I can now reproduce this. Let me have a look.

**Comment by thomaseizinger** [comment]
> I thought I didn't get them but I can now reproduce this. Let me have a look.

Lol. It is `tracing_subscriber` wanting to write things in italic. Can't believe it.

**Comment by thomaseizinger** [comment]
I can reproduce this on my phone but I can't reproduce it on my computer. There, setting `ansi=false` won't make the fields italic.

**Comment by ReactorScram** [comment]
Yeah I just tried that `reload` module for the Tauri Client and it seems to work. It takes a few seconds or a few log events to kick in though, I'm not sure why.

**Comment by jamilbk** [comment]
> I can reproduce this on my phone but I can't reproduce it on my computer. There, setting `ansi=false` won't make the fields italic.

How did you manage to run Android Studio on your phone?! Just to be clear this issue is just an annoyance affecting day-to-day Android development -- viewing logs in my terminal is no issue.

**Comment by thomaseizinger** [comment]
> > I can reproduce this on my phone but I can't reproduce it on my computer. There, setting `ansi=false` won't make the fields italic.
> 
> How did you manage to run Android Studio on your phone?! Just to be clear this issue is just an annoyance affecting day-to-day Android development -- viewing logs in my terminal is no issue.

Ha! With reproduce I meant I can see the Android app producing _some_ ANSI escape codes when I get them via `adb logcat` but when I use the exact same logger configuration in a unit-test, there are no escape codes. This appears to be a bug in `tracing-subscriber` maybe? I looked at its code for a bit but couldn't find anything obvious.

**Comment by jamilbk** [comment]
@thomaseizinger I can confirm these issues persist.

The log format issue was introduced by adding a `fmt()` layer in https://github.com/firezone/firezone/commit/8973cc5785a31666d5657bbdae0f4e552ff54688 -- judging from the [crate docs](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Format.html#) they don't seem to have a good way to disable italicized parts in `Format`, but maybe `env_logger` can do it? https://docs.rs/env_logger/latest/env_logger/struct.Env.html. We are doing that with the Gateway for example to prevent this issue there.

I haven't pinpointed which commit introduced the log handle failing to be discarded after `disconnect()` but I suspect that's what may be happening.

**Comment by thomaseizinger** [comment]
> The log format issue was introduced by adding a `fmt()` layer in [8973cc5](https://github.com/firezone/firezone/commit/8973cc5785a31666d5657bbdae0f4e552ff54688) -- judging from the [crate docs](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Format.html#) they don't seem to have a good way to disable italicized parts in `Format`,

Thanks for digging into this! There is the `with_ansi` function which we already call with `false` that is meant to trickle down to everything as far as I can follow the code.

> I haven't pinpointed which commit introduced the log handle failing to be discarded after `disconnect()` but I suspect that's what may be happening.

Regarding log-filter: I suspect this may be the case since we introduced the `static`. Anyway, I almost certain we can fix this using a reload handle. I just didn't get around to it yet because priorities :)

**Comment by jamilbk** [comment]
> Thanks for digging into this! There is the `with_ansi` function which we already call with `false` that is meant to trickle down to everything as far as I can follow the code.

Yeah, maybe a bug. Maybe we need to [set it for the spans too](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Format.html#options)?

> However, a field formatter must be manually provided to avoid ANSI in the formatting of parent spans

> Regarding log-filter: I suspect this may be the case since we introduced the `static`. Anyway, I almost certain we can fix this using a reload handle. I just didn't get around to it yet because priorities :)

Yeah I think @ReactorScram is planning to use that too for the IPC service. You're probably right this being a historical bug. We could probably fix this actually on the JVM side by unloading the lib after `disconnect`, similar to how we load it just before calling `connect`. That may be wise to do anyhow.

**Comment by jamilbk** [comment]
Nevermind on my unloadLibrary idea:

> Unloading a library in the JVM, specifically the opposite of System.loadLibrary, is not directly supported. Once a native library is loaded into the JVM, there is no direct mechanism provided by the JVM to unload it. This is primarily because the JVM maintains a reference to the loaded native library for the entire duration of the application's runtime to ensure stability and consistency.

**Comment by ReactorScram** [comment]
Yep the Tauri Client has a reloader in the GUI and after #5704 merges, we can add that to the IPC service too, so changing the log filter will take effect immediately. https://github.com/firezone/firezone/blob/90ea603584174837c22e0909430d8044ee094593/rust/gui-client/src-tauri/src/client/gui.rs#L502-L513

**Comment by thomaseizinger** [comment]
Related: https://github.com/tokio-rs/tracing/issues/3065.

**Comment by thomaseizinger** [comment]
https://github.com/firezone/firezone/pull/7024 fixes the ANSI issue.
