### ISSUE TITLE
Normalize all datetimes to users browser

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5635]
Some are normalized and some aren't. Would be good to have this consistent:

<img width="1597" alt="Screenshot_2024-06-29_at_12_19_41 AM" src="https://github.com/firezone/firezone/assets/167144/f45744b3-28e8-4ec6-98e3-6246d0fb25fa">

**Comment by cooldude6000** [comment]
Is the code based in TypeScript?

**Comment by jamilbk** [comment]
They are Heex templates: https://github.com/firezone/firezone/tree/main/elixir/apps/web/lib/web
