### ISSUE TITLE
GCM notifications not coming through on Android with Firezone connected

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5637]
#### Describe the bug

- Firezone connected for a few hours
- Disconnect on purpose
- Telegram notifications came through

#### To Reproduce

_Steps to reproduce the behavior._

#### Expected behavior

_A clear and concise description of what you expected to happen._

#### Screenshots / Logs

_If applicable, add screenshots and log traces to help debug your problem **with
any sensitive data removed**._

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_
- _Firezone Version (e.g. 1.0.0 or N/A):_
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

_Add any other context about the problem here._

**Comment by jamilbk** [comment]
I wonder if you're hitting the same bug as me in #5633 with the `*.google.com` resource impacting system services.

**Comment by thomaseizinger** [comment]
Can confirm, this affects GCM notifications in general, not just Telegram.

**Comment by thomaseizinger** [comment]
We need to fix this. Kind of defeats the point of having Firezone always on in the background.

Wonder how to best debug this ..

**Comment by jamilbk** [comment]
Maybe try making sure the Google play services are always routed outside the VPN?

https://stackoverflow.com/questions/36629360/not-receiving-gcm-push-notification-when-vpn-is-connected-in-my-android-phone

**Comment by jamilbk** [comment]
I.e. make sure `com.google.com.android.gms` (maybe others) is always in the disallowedApplications list.

**Comment by jamilbk** [comment]
You'll want to check how this behaves with the block traffic that doesn't go through the VPN feature (i.e. when Internet Resource is enabled).

**Comment by thomaseizinger** [comment]
> I.e. make sure `com.google.com.android.gms` (maybe others) is always in the disallowedApplications list.

And every user has to set this themselves? That is not good, is it?

**Comment by jamilbk** [comment]
> > I.e. make sure `com.google.com.android.gms` (maybe others) is always in the disallowedApplications list.
> 
> And every user has to set this themselves? That is not good, is it?

No, we set it in TunnelService.kt
