### ISSUE TITLE
Investigate disabling WireGuard keepalives

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5638]
With snownet, these are redundant and just extra packets on the wire. The idle connection logic doesn't take WireGuard packets into account anyhow. Is there any reason to keep them around?

**Comment by thomaseizinger** [comment]
https://github.com/firezone/firezone/blob/25b65289424db8c6b4e381d26010087846a783d6/rust/connlib/snownet/src/node.rs#L556-L559

**Comment by jamilbk** [comment]
Noted, thanks! So this is helpful when an application wishes to send packets past the 30s mark but before the 5m mark, where it'll incur the latency of holepunching anyhow.
