### ISSUE TITLE
Allow trying Firezone without signing up

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5681]
Need a temporary "demo mode" of some sort to try Firezone without signing up that we can use for launch day. This was the most important thing we need according to HN. This can be turned back off or completely removed the next day.

Some thoughts:

- What does it mean to try Firezone without an account?
- Maybe we do this on staging? That will keep it from affecting current customers, but they'll need to update their Clients' settings...
- Maybe just limit it to the admin portal? I imagine signing in from a Client will be hard to do without an account, so we can maybe just disable logins for accounts in "demo mode".

Perhaps it could be "SSH to a machine with no exposed ports" as an MVP.

**Comment by jamilbk** [comment]
This sounds like a pain but I think if we're creative we can come up with a quick hack for just this launch. Assigning the team for crowd-sourcing ideas!

**Comment by jamilbk** [comment]
@firezone/engineering

**Comment by ReactorScram** [comment]
So we'd like a way for a free user to run, say, a Client on one of their systems and a Gateway on the other, and see that they can SSH (or even HTTP) from one to the other?

It's too bad we need root for both Clients and Gateways, that will be a little scary for the security-conscious. We could bundle an HTTP server with a Gateway as a demo, that would be less scary than an sshd

**Comment by thomaseizinger** [comment]
How difficult would it be to:

- Make the `demo` slug a thing
- Pre-create a site with a few gateways
- Disable revoking gateway tokens and any other destructive action
- Pre-create some resources like `ifconfig.net` etc, don't allow to change anything about it
- Users "login" with email but don't require a password and can thus continue straight away
- There is only one group `Everyone` and each "login" adds that user to that group

If we control the resources, we pretty much limit what they can do with that free account and they can't really hammer our gateways with heaps of traffic.

This "demo" slug could also be useful for something more permanent when you want to demo firezone on somebody's device :)

**Comment by AndrewDryga** [comment]
We can make signup transparent, you follow up a link and get an account without an email attached to it and can use everything right away. Then you can add email to make sure you won't lose the account when signed out. We will also need a way in the portal to show a client sign-in code or something similar to that.

**Comment by thomaseizinger** [comment]
> Users "login" with email but don't require a password and can thus continue straight away

An advantage of this would be that we could build up an email list of users that have tried firezone and follow-up with a newsletter or something. Sign-up to that mailing list could be part of the T&C of using the demo!

**Comment by jamilbk** [comment]
> We can make signup transparent, you follow up a link and get an account without an email attached to it and can use everything right away. Then you can add email to make sure you won't lose the account when signed out. We will also need a way in the portal to show a client sign-in code or something similar to that.

Ah yes, good call -- presumably some folks would actually like to continue using their account after trying things out. We would need some way to start an account in `demo` / trial mode then. Perhaps they can start on the Team plan.

We might need some way to prevent dupe sign ups, or just disable this special "sign up without email" workflow after Launch day.

**Comment by thomaseizinger** [comment]
> presumably some folks would actually like to continue using their account after trying things out.

Isn't the account bound to the slug you signed in with? If you actually want to use firezone, they'd properly sign-up afterwards, no? Or am I misunderstanding the model here?

**Comment by AndrewDryga** [comment]
@thomaseizinger we will generate an account with a slug, but the identity of the admin will be something we need to build (like `secret` identity that just has a code/password, which can be used to sign in to the portal and client). In the portal we show a warning that the user needs to replace that with actual email. Fortunately, everything is built with assumption that IdP doesn't return emails so it should be pretty easy.

@jamilbk We can put everyone on Team with some trial during the first days and then make it create accounts on the free plan afterward.

**Comment by thomaseizinger** [comment]
> @thomaseizinger we will generate an account with a slug, but the identity of the admin will be something we need to build (like `secret` identity that just has a code/password, which can be used to sign in to the portal and client). In the portal we show a warning that the user needs to replace that with actual email. Fortunately, everything is built with assumption that IdP doesn't return emails so it should be pretty easy.

Do we need to generate so many different slugs? Why not set up one `demo` slug that people can use without a password (or some other auth mechanism)? It might even be okay to require confirmation of the email.

I'd imagine when people want to "Try Firezone", they have little interest to log into an AWS account and spin up an EC2 instance for a gateway to be able to see their IP change when they use `ifconfig.net` or something like that. It would be a much more powerful demo if they can:

- Download the Android / iOS app
- Select `demo` slug
- Enter any email
- Be logged in as "unverified"
- Go to `ifconfig.net` and see their location change

No need to set up gateways or define resources.

Then, if they are interested in how it works, they can log into the portal with the same email and "browse" around (but not change anything).

**Comment by ReactorScram** [comment]
Trial / demo users won't be able to see each other's email addresses, right? Or any other user-entered string? Someone will definitely put something offensive in any text field

**Comment by AndrewDryga** [comment]
@thomaseizinger because if we have one `demo` slug then all users will be in the same account and won't be able to try Firezone for real, they won't deploy their own gateways (everything will be accessible for anyone) - I believe we should try to convert the audience to get some ROI rather than just mark a checkbox "can use without sign up". If they are not going to deploy a gateway at all - it's not our target audience but at least we will be fair to them and not fake anything. And making most of the UI read-only with proper error messages is more work than creating accounts without emails.

**Comment by AndrewDryga** [comment]
> Trial / demo users won't be able to see each other's email addresses, right? Or any other user-entered string? Someone will definitely put something offensive in any text field

If they are in the same account and read-only they will see everything under that account, unless we also hide some fields based on user role (which is even more work).

**Comment by thomaseizinger** [comment]
> @thomaseizinger because if we have one `demo` slug then all users will be in the same account and won't be able to try Firezone for real, they won't deploy their own gateways (everything will be accessible for anyone) - I believe we should try to convert the audience to get some ROI rather than just mark a checkbox "can use without sign up". If they are not going to deploy a gateway at all - it's not our target audience but at least we will be fair to them and not fake anything. And making most of the UI read-only with proper error messages is more work than creating accounts without emails.

Yeah, converting some users would definitely be good!

I am just cognisant of the number of steps a user has to go through before they can use firezone. Signing up is one thing, having to deploy your own software is a much bigger step that e.g. anybody coming to the Launch HN post from their phone sitting on a sofa isn't going to do.

The `demo` slug would be more of an appetizer to have them set up a real account where they then can setup their own gateway etc.

I don't know the backend codebase so maybe there are better ways other than making things read-only yet they come to an already set up environment with resources and a gateway?

What if we deploy a separate portal instance where things are read-only hardcoded? I remember @jamilbk said that this could be something that will be thrown away after so we don't have to modify prod code.

**Comment by bmanifold** [comment]
Personally, I think letting each user have their own account is a better way to go, being that we've set everything up in the portal to have a boundary at the account level.  It feels like it would be the least amount of work, rather than trying to figure out how to let a lot of new users share an account.  Along with that, running a completely separate portal would require everyone to adjust their client settings to point to the temporary portal, which is not the end of the world, but it does introduce friction and then would require them to reset their client settings if they decide to use the prod portal.

All that said, I do recognize how much effort it is to get all of the pieces setup just to try out Firezone.  I know we all know this, but at a minimum you need to have a machine to run a gateway and then also install a client on another machine.  And ideally you'd need to run at least one other machine as a resource.

I'm wondering if we can split the difference and also make it kind of a game.  What if we made a small CTF game that if the user finds the flags we offer a discount of some sort? Each user would get a free Firezone account on prod and the only thing they would need to do is to download and install the client. Then we could run a cluster of machines that will run the gateways and resources for the game.  We'd need to add a few things in the portal for spinning up one of the "Firezone Hosted Gateways", but those machines could be shared between accounts since each account would have it's own instance of the Firezone Gateway running on one of them.  We'd have instructions for how to create a Site, how to spin up a Gateway (although this would be kind of simulated, because we'd have a button to deploy one of our hosted Gateways), and how to add a Resource.  Then they would need to add the first resource, which could be an HTTP server with some type of vulnerability they need to figure out to find the address of the second resource to add and then with the second resource that would give them the flag for the discount.  Even if they don't figure it out it would show them the basics of how to use Firezone.

I recognize this may be a decent amount of work, but I think just about anything we do is going to be a decent amount of work.  In doing this, after the 'launch', we'd at least have all new users in their won accounts that they could keep long term if they wanted and it wouldn't require everyone to spin everything up just to try it out.

Thoughts?

**Comment by thomaseizinger** [comment]
> All that said, I do recognize how much effort it is to get all of the pieces setup just to try out Firezone. I know we all know this, but at a minimum you need to have a machine to run a gateway and then also install a client on another machine. And ideally you'd need to run at least one other machine as a resource.

To get how firezone works, we can use any resource on the Internet, right? Something like `ifconfig.net` that shows the location of your IP address makes it clear enough that traffic is now going through the gateway. To demonstrate split-DNS, we can also tell them to use a 2nd, similar website that that isn't a resource and they'll see that their IP for that one is different!

> I'm wondering if we can split the difference and also make it kind of a game. What if we made a small CTF game that if the user finds the flags we offer a discount of some sort? Each user would get a free Firezone account on prod and the only thing they would need to do is to download and install the client. Then we could run a cluster of machines that will run the gateways and resources for the game. We'd need to add a few things in the portal for spinning up one of the "Firezone Hosted Gateways", but those machines could be shared between accounts since each account would have it's own instance of the Firezone Gateway running on one of them. We'd have instructions for how to create a Site, how to spin up a Gateway (although this would be kind of simulated, because we'd have a button to deploy one of our hosted Gateways), and how to add a Resource. Then they would need to add the first resource, which could be an HTTP server with some type of vulnerability they need to figure out to find the address of the second resource to add and then with the second resource that would give them the flag for the discount. Even if they don't figure it out it would show them the basics of how to use Firezone.
> 
> I recognize this may be a decent amount of work, but I think just about anything we do is going to be a decent amount of work. In doing this, after the 'launch', we'd at least have all new users in their won accounts that they could keep long term if they wanted and it wouldn't require everyone to spin everything up just to try it out.

I love this idea! I played through https://gandalf.lakera.ai/ recently and really enjoyed it. The idea of "Firezone Hosted Gateways" is good! We already have the terraform modules, right? How much effort would it be to add a button that says "Deploy Demo Gateway" that is perhaps shut-down again after a day or so? That would take some of the friction out.

A CTF game could be an additional thing we build on top later?

**Comment by jamilbk** [comment]
These are all good suggestions. To get this shipped super quickly though I thought of the following:

- We have a `demo mode`. Can be enabled / disabled via Domain.Ops (or possibly just by reverting the PR since this will just be a one-time thing)
- Arrive at `app.firezone.dev/new_demo_account`: we create `demo-x31fda@firezonedemo.com` admin
- Session is only good for one hour
- We display banner message warning them about session, link to `Actors` to create a new Actor for themselves or to sign in from a Client

**Comment by jamilbk** [comment]
Another option is to spend a little bit of time on a new self-hosted docker-compose.yml that is geared towards spinning up locally for demos.

The most important thing would be to convey the fact that no ports are exposed. We can do this by ensuring the compose file is super minimal so it's clear how the network infra is configured.

**Comment by thomaseizinger** [comment]
> * We have a `demo mode`. Can be enabled / disabled via Domain.Ops (or possibly just by reverting the PR since this will just be a one-time thing)
> 
> * Arrive at `app.firezone.dev/new_demo_account`: we create `demo-x31fda@firezonedemo.com` admin

Does the demo mode come with a pre-deployed gateway or do they have to deploy there own?

**Comment by jamilbk** [comment]
@thomaseizinger We were discussing this on standup yesterday with @bmanifold and I think adding a pre-deployed Gateway to each account when it's provisioned is quite a large amount of infra work. We'd also have to make the site readonly so no additional Resources can be added to it, otherwise we end up with liability issues.

I was thinking the local docker-compose up thing could work, but unfortunately the client auth process seems to require `HTTPS` so that approach is going to be tricky as well.

See #5687.

The way we can "hack" the above for desktop clients is to inject a service account token into the secure keychain for each OS prior to the app launching. I'll think more about that... maybe it can be done with a simple script that does the following:

1. `docker compose up`
1. Generate a service account + token with `mix ecto.seed` or similar
1. Inject the token into the expected place in the keychain (Apple has CLI utilities for this)
1. Prompt the user to install the app for his/her platform and configure the control plane URL
1. Upon launching the app it _should_ autoconnect to the local Firezone cluster

That's incredibly hacky though.

**Comment by jamilbk** [comment]
Maybe we can get away with storylane.io

**Comment by jamilbk** [comment]
I think the consensus here was:

- Add a simple 'demo' landing page - `https://app.firezone.dev/try`. Has a big button "Launch a demo instance" which creates an account with 1 actor `<random-id@firezonedemo.com>` and signs them into the admin portal.
- Signing in via email with a valid `@firezonedemo.com` email always works so that we can bypass auth for these non-signed-up accounts
- For "demo" accounts, show a banner (#1732) with:
```
Welcome to your Firezone demo! You may sign in to the admin portal and <a>using a Firezone Client</a> with the account slug <account_slug> and the email <random-id>@firezonedemo.com. This account will be removed after <creation + 24 hours>.
```
- For demo accounts, show a new, default tab in the Deploy Gateway page that has a minimal docker compose file that consists of a Gateway + 1 simple resource, a very prominent "Notice no ports need to be forwarded!", and instructions to set it up
