### ISSUE TITLE
bug(gui-client/linux): Broken pipe error / installing a new deb while the GUI is signed in

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#5790]
#### Describe the bug

1. IPC service starts, Git commit 0447688
2. About 2h10m pass
3. GUI Client logs in via deep link auth
4. The Client operates normally for about 2 hours (Are UTC times of logs considered private?)
5. Last log line from IPC service, unclear if it gracefully shut down or crashed
6. About 20 seconds pass
7. New IPC instance starts, Git commit 35926eb (modified)
8. 1 second passes
9. GUI tries to send `SetDns` to IPC service and fails with Broken pipe error

#### To Reproduce

Synthetic:

1. Run the IPC service in `run-debug` mode on a dev system
2. Run the GUI and sign in
3. Ctrl+C the IPC service
4. The GUI will exit with the same "Broken pipe" error, and it will be triggered by `SetDns` since the system's DNS changes when the IPC service exits

More likely:

1. Install 0447688
2. Run the GUI and sign in
3. Install any newer version on top of it
4. Within 5 seconds, the GUI will show the SetDns error

#### Expected behavior

1. Expected the IPC service to stay up

#### Screenshots / Logs

Internal Slack: https://firezonehq.slack.com/archives/C07312PRYE4/p1720440317393909?thread_ts=1720437611.153999&cid=C07312PRYE4

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Linux GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 0447688, 1.1.2, but the synthetic repro steps work on 0ff45c34f9, the tip of `main`
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ PopOS, unknown arch
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Production deb

#### Additional context

~~The Linux GUI Client doesn't get DNS change events from the OS, it polls every 5 seconds. So the `SetDns` call likely succeeded a couple times before failing~~ (We poll every 5 seconds but it only goes up to the GUI and over to the IPC service if anything changed)

**Comment by jamilbk** [comment]
Fix here is just to display a better error instructing the user to restart the service upon / after upgrade?

**Comment by ReactorScram** [comment]
Yeah. So right now it doesn't detect that IPC dropped until the next send, which happens to be SetDns because if the IPC service restarts while signed in, the DNS will change. 

#5795 will change that to detect the drop immediately on the receiving side (as immediately as possible anyway) and so it will say "IPC connection closed" instead of "SetDns failed" which is more useful.

#5789 allowed the IPC service to detect when systemd is stopping it, so the final fix should be for the service to send an "I'm shutting down, possibly due to an update" message to the GUI, then the GUI will say, "The IPC service gracefully shut down, probably due to an update, please restart the GUI" and close itself.

We could go further and have the GUI auto-restart or have the two processes compare versions or have the GUI auto-reconnect but that's all brittle. Closing with an error dialog should be enough for now

**Comment by jamilbk** [comment]
If it's simpler I think another acceptable UX could be just a `preinst` check that prompts with `Firezone seems to be running. Stop it now? (Y/n)` and then a `postinst` that prompts `Start Firezone now? (Y/n)`.

You would have to check for `DEBIAN_FRONTEND=noninteractive` and just assume `Y` if that's the case.

**Comment by jamilbk** [comment]
Or we could have both. The above would hopefully avoid showing an error in the typical case with a client signed in though, which might not be best.
