### ISSUE TITLE
ux(gui-client): Add signed in / signed out icon states to menubar icon

### ISSUE THREAD

**Issue by samuelverstraete** [CloudFire-LLC/cloudfire#5810]
#### Is your feature request related to a problem? Please describe.

The tray icon of the gui-client does not show state. My firezone client is always on and it will not report if the connection was broken and I need to re-auth. It usually takes me a couple of moments to realize that my tunnel is broken

#### Describe the solution you'd like

Either a notification but at least a visual clue that I need to re-auth with firezone.

#### Describe alternatives you've considered
none

#### Additional context

I'm using the linux client on PopOS (Ubuntu 22.04 derivative)

**Comment by jamilbk** [comment]
Thanks for the report @samuelverstraete. @ReactorScram let me know if you need on/off icon states. The macOS client has a custom animation but that may not be possible for others.

**Comment by ReactorScram** [comment]
@jamilbk Probably will. I'll build it with placeholders to start with and see how it goes

**Comment by samuelverstraete** [comment]
thank you very much!
