### ISSUE TITLE
gui-client: Check for updates periodically via website API endpoint and notify in menubar icon and menu

### ISSUE THREAD

**Issue by samuelverstraete** [CloudFire-LLC/cloudfire#5811]
#### Is your feature request related to a problem? Please describe.

It would be nice if the gui-client could show that there is a new version available, or even better just install it (or provide apt repo so it gets updated with my system)

#### Describe the solution you'd like

i want to keep my system up2date

#### Describe alternatives you've considered

none

#### Additional context

Using the gui-client on PopOS (Ubuntu 22.04 derivative)

**Comment by ReactorScram** [comment]
Right now it should check at startup and show a pop-up like this
![image](https://github.com/firezone/firezone/assets/13400041/e4428dd7-39da-418d-9e0f-c85dc132a2f2)

We could do that check more often, maybe once a day?

Self-assigning so the issue has an assignee

**Comment by samuelverstraete** [comment]
Hmm yeah... I never see these notifications, Linux systems have so many notifications that I usually miss these... I was thinking something in the menu of firezone? Maybe like slack (and others do) with a blue/red dot on the icon so you know something requires attention.

**Comment by jamilbk** [comment]
I'll update this issue to mark it as a feature. @ReactorScram I'm wondering if it makes sense to add a simple JSON or API endpoint to the website that tracks versions, perhaps from the changelog page. That will keep bandwidth minimized if we're going to scale this out across all users.

**Comment by ReactorScram** [comment]
@jamilbk We could but I don't think it's needed. Right now we just do a `HEAD` request and then parse the `Location` header, which is about 110 bytes, Adding a response body could shrink it a little bit, but the TLS certs are already bigger than that.

I'm thinking:
1. Run a stress test with like 10,000 requests, representing 1 day of 10,000 Clients checking once per day
2. If the website can handle that, just have the Clients pick a random ~~time of day~~ offset up to 24 hours from startup (to avoid everyone checking at 9:00 am US time) and then check daily
3. If the website can't handle that, see if we can do it through the WebSocket connection to the portal. Then we can re-use the TLS connection and skip HTTP overhead if we're really trying to squeeze for individual bytes.

**Comment by jamilbk** [comment]
Website should be able to handle that no problem.

**Comment by ReactorScram** [comment]
Now that #5817 has merged, we could build on top of this, maybe show a `!` exclamation mark if an update is ready to download
