### ISSUE TITLE
resources are unavalable

### ISSUE THREAD

**Issue by gleam-ru** [CloudFire-LLC/cloudfire#5814]
#### Describe the bug

1. I've registered on: https://app.firezone.dev/sign_up
2. I've installed gateway via docker compose: https://www.firezone.dev/kb/automate/docker-compose?utm_source=product
3. The installed gateway is "online" (a0269110-4ab6-411f-aaa0-90c535175bde)
4. I've added resource, which is available from vm with gateway (resource ip is 10.7.0.2)
5. I've tried to ping it - no result ¯\_(ツ)_/¯ 

#### Screenshots / Logs

[firezone_logs_2024-07-09T183640Z.zip](https://github.com/user-attachments/files/16147962/firezone_logs_2024-07-09T183640Z.zip)

<details><summary>Gateway logs</summary>
<p>

gleam@dolly-ubuntu-24--gleam:~/firezone$ docker compose logs
firezone-gateway-1  | 2024-07-09T18:35:16.170156Z  INFO phoenix_channel: Connected to portal host=api.firezone.dev
firezone-gateway-1  | 2024-07-09T18:35:16.317602Z  INFO snownet::node: Added new TURN server id=dab9dbbd-8786-4175-985e-a41ceadf34ed address=Dual { v4: 34.88.70.83:3478, v6: [2600:1900:4150:253:0:1a::]:3478 }
firezone-gateway-1  | 2024-07-09T18:35:16.317633Z  INFO snownet::node: Added new TURN server id=16d232d1-2180-438e-b558-737a5ae0b1e1 address=Dual { v4: 34.116.142.25:3478, v6: [2600:1900:4140:6d2c:0:1f::]:3478 }
firezone-gateway-1  | 2024-07-09T18:35:16.317743Z  WARN quinn_udp: sendmsg error: Os { code: 99, kind: AddrNotAvailable, message: "Address not available" }, Transmit: { destination: [2600:1900:4140:6d2c:0:1f::]:3478, src_ip: None, enc: None, len: 20, segment_size: None }
firezone-gateway-1  | 2024-07-09T18:35:16.318472Z  INFO connlib_shared::tun_device_manager::linux: Setting new routes new_routes={V6(Ipv6Network { network_address: fd00:2021:1111::, netmask: 107 }), V4(Ipv4Network { network_address: 100.64.0.0, netmask: 11 })}
firezone-gateway-1  | 2024-07-09T18:35:16.319033Z  WARN firezone_gateway: Failed to set routes: Failed to add route: Received a netlink error message Permission denied (os error 13)
firezone-gateway-1  | 2024-07-09T18:35:16.341584Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=None relay_ip6=None lifetime=None
firezone-gateway-1  | 2024-07-09T18:35:16.362003Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=None relay_ip6=None lifetime=None
firezone-gateway-1  | 2024-07-09T18:35:16.386340Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=34.88.70.83:53780/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4150:253:0:1a::]:53780/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 9070, tv_nsec: 32157547 }, 600s))
firezone-gateway-1  | 2024-07-09T18:35:16.446008Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=34.116.142.25:60200/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4140:6d2c:0:1f::]:60200/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 9070, tv_nsec: 91825753 }, 600s))
firezone-gateway-1  | 2024-07-09T18:35:27.960514Z  INFO accept_connection{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Created new connection
firezone-gateway-1  | 2024-07-09T18:35:28.318581Z  INFO handle_timeout{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Updating remote socket old=None new=Direct { source: 172.18.0.2:48705, dest: 192.168.50.180:63607 } duration_since_intent=250ms
firezone-gateway-1  | 2024-07-09T18:35:28.330289Z  INFO connection{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Completed wireguard handshake duration_since_intent=369.950872ms
firezone-gateway-1  | 2024-07-09T18:36:05.710790Z  INFO handle_timeout{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Connection failed (ICE timeout)
firezone-gateway-1  | 2024-07-09T18:36:26.452487Z  INFO accept_connection{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Created new connection
firezone-gateway-1  | 2024-07-09T18:36:26.961367Z  INFO handle_timeout{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Updating remote socket old=None new=Direct { source: 172.18.0.2:48705, dest: 192.168.50.180:56944 } duration_since_intent=500ms
firezone-gateway-1  | 2024-07-09T18:36:26.966644Z  INFO connection{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Completed wireguard handshake duration_since_intent=514.330525ms
firezone-gateway-1  | 2024-07-09T18:39:11.453044Z  WARN handle_timeout{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: boringtun::noise::timers: HANDSHAKE(REJECT_AFTER_TIME - KEEPALIVE_TIMEOUT - REKEY_TIMEOUT (on receive))
firezone-gateway-1  | 2024-07-09T18:40:16.410053Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=34.88.70.83:53780/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4150:253:0:1a::]:53780/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 9370, tv_nsec: 55858444 }, 600s))
firezone-gateway-1  | 2024-07-09T18:40:16.499913Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=34.116.142.25:60200/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4140:6d2c:0:1f::]:60200/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 9370, tv_nsec: 145724395 }, 600s))
firezone-gateway-1  | 2024-07-09T18:40:32.453235Z  INFO handle_timeout{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Connection failed (ICE timeout)
firezone-gateway-1  | 2024-07-09T18:40:52.257379Z  INFO accept_connection{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Created new connection
firezone-gateway-1  | 2024-07-09T18:40:52.572103Z  INFO handle_timeout{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Updating remote socket old=None new=Direct { source: 172.18.0.2:48705, dest: 192.168.40.101:56944 } duration_since_intent=310.446724ms
firezone-gateway-1  | 2024-07-09T18:40:52.586364Z  INFO connection{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Completed wireguard handshake duration_since_intent=329.207953ms
firezone-gateway-1  | 2024-07-09T18:42:00.069393Z  INFO handle_timeout{id=28ab64e0-58f2-455d-840b-d83fa5a7d466}: snownet::node: Connection failed (ICE timeout)
firezone-gateway-1  | 2024-07-09T18:45:16.434822Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=34.88.70.83:53780/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4150:253:0:1a::]:53780/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 9670, tv_nsec: 80622163 }, 600s))
firezone-gateway-1  | 2024-07-09T18:45:16.544982Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=193.201.90.105:48705/udp base=172.18.0.2:48705 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=34.116.142.25:60200/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4140:6d2c:0:1f::]:60200/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 9670, tv_nsec: 190799433 }, 600s))

</p>
</details> 

#### Platform (please complete the following information)

- Gateway: ghcr.io/firezone/gateway:1
- Firezone Version 1.1.2
- OS and version: Macos 14.5 (23F79)

**Comment by jamilbk** [comment]
Thanks for the report! How is your docker daemon configured? This line is the issue:


```
firezone-gateway-1 | 2024-07-09T18:35:16.319033Z WARN firezone_gateway: Failed to set routes: Failed to add route: Received a netlink error message Permission denied (os error 13)
```

Is the `CAP_NET_ADMIN` permission defined in the docker-compose.yml being used correctly?

**Comment by gleam-ru** [comment]
> Is the `CAP_NET_ADMIN` permission defined in the docker-compose.yml being used correctly?

Is it correct?

![image](https://github.com/firezone/firezone/assets/6701480/3021db8c-1f98-48fe-9920-5e5f7f4151e1)

**Comment by jamilbk** [comment]
The `docker-compose.yml` looks correct, yes -- but if your Docker daemon doesn't have the underlying permissions to apply added capabilities, then this won't work.

How did you install / setup Docker Engine?

**Comment by gleam-ru** [comment]
> did you install

sudo apt update && sudo apt install apt-transport-https ca-certificates curl software-properties-common && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" && sudo apt install docker-ce

that is all...
ubuntu 24

**Comment by jamilbk** [comment]
Could you try again using the official Docker instructions here? https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

It looks like you've set this up for `focal` but you're on 24 which is `noble`.

Please double-check your Docker installation is working correctly.

**Comment by jamilbk** [comment]
Closing as unable to reproduce. Tested on a fresh ubuntu 24.04 instance and Gateway and Resources route just fine. Here is expected output:


```
root@test:~# docker compose up 
[+] Running 1/1
 ✔ Container root-firezone-gateway-1  Recreated                                                                                                                               0.1s 
Attaching to firezone-gateway-1
firezone-gateway-1  | 2024-07-09T21:26:32.649892Z  INFO phoenix_channel: Connected to portal host=api.firez.one
firezone-gateway-1  | 2024-07-09T21:26:32.676158Z  INFO snownet::node: Added new TURN server id=126a903b-5c93-4197-8637-e7c537100255 address=Dual { v4: 35.184.125.140:3478, v6: [2600:1900:4000:102d:0:4::]:3478 }
firezone-gateway-1  | 2024-07-09T21:26:32.676208Z  INFO snownet::node: Added new TURN server id=d511683e-8022-4bcd-a701-60105419e9d9 address=Dual { v4: 34.139.28.45:3478, v6: [2600:1900:4020:eb:0:4f::]:3478 }
firezone-gateway-1  | 2024-07-09T21:26:32.676370Z  WARN quinn_udp: sendmsg error: Os { code: 101, kind: NetworkUnreachable, message: "Network unreachable" }, Transmit: { destination: [2600:1900:4020:eb:0:4f::]:3478, src_ip: None, enc: None, len: 20, segment_size: None }
firezone-gateway-1  | 2024-07-09T21:26:32.678038Z  INFO connlib_shared::tun_device_manager::linux: Setting new routes new_routes={V6(Ipv6Network { network_address: fd00:2021:1111::, netmask: 107 }), V4(Ipv4Network { network_address: 100.64.0.0, netmask: 11 })}
firezone-gateway-1  | 2024-07-09T21:26:32.705509Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=144.202.23.151:55089/udp base=172.18.0.2:55089 prio=1694498559)) srflx_ip6=None relay_ip4=None relay_ip6=None lifetime=None
firezone-gateway-1  | 2024-07-09T21:26:32.710583Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=144.202.23.151:55089/udp base=172.18.0.2:55089 prio=1694498559)) srflx_ip6=None relay_ip4=None relay_ip6=None lifetime=None
firezone-gateway-1  | 2024-07-09T21:26:32.742889Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=144.202.23.151:55089/udp base=172.18.0.2:55089 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=34.139.28.45:54140/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4020:eb:0:4f::]:54140/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 284, tv_nsec: 880799053 }, 600s))
firezone-gateway-1  | 2024-07-09T21:26:32.758357Z  INFO snownet::allocation: Updated allocation srflx_ip4=Some(Candidate(srflx=144.202.23.151:55089/udp base=172.18.0.2:55089 prio=1694498559)) srflx_ip6=None relay_ip4=Some(Candidate(relay=35.184.125.140:51736/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4000:102d:0:4::]:51736/udp prio=50331647)) lifetime=Some((Instant { tv_sec: 284, tv_nsec: 896259095 }, 600s))
```
