### ISSUE TITLE
Unable to run nginx alongside firezone

### ISSUE THREAD

**Issue by DokStook** [CloudFire-LLC/cloudfire#582]
I installed firezone and changed the default url to the url I want. I stopped nginx while setting firezone up so that nginx doesn't break something. Now I am unable to start it.

> My server:$ sudo systemctl start nginx.service
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
My server:$ systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-05-09 06:39:34 UTC; 7s ago
       Docs: man:nginx(8)
    Process: 351075 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 351077 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 59ms

> May 09 06:39:32 mail nginx[351077]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
May 09 06:39:32 mail nginx[351077]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
May 09 06:39:33 mail nginx[351077]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
May 09 06:39:33 mail nginx[351077]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
May 09 06:39:33 mail nginx[351077]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
May 09 06:39:33 mail nginx[351077]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
May 09 06:39:34 mail nginx[351077]: nginx: [emerg] still could not bind()
May 09 06:39:34 mail systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May 09 06:39:34 mail systemd[1]: nginx.service: Failed with result 'exit-code'.
May 09 06:39:34 mail systemd[1]: Failed to start A high performance web server and a reverse proxy server.

I am kinda newbie. I don't know what else to provide. Please don't be rude for that. I am trying to learn.

Thanks in advance!

`

**Comment by jamilbk** [comment]
@DokStook 

Firezone actually bundles an nginx server and by default it *also* listens on the default port of 443. You'll need to change either your existing nginx listen port, or the Firezone nginx listen port:

```ruby
default['firezone']['nginx']['ssl_port'] = 8443 # change to something other than 443
```

You'll also want to make sure your `external_url` includes this custom port as well. After `firezone-ctl reconfigure`, Firezone's nginx will now be listening on another port and you should be able to start up your existing nginx service.

**Comment by DokStook** [comment]
Thanks, that worked! One more thing to note is that you need to change the non-ssl port also. It looks like it is also used by firezone nginx.

Thanks one more time!

**Comment by DokStook** [comment]
I forgot to close the issue
