### ISSUE TITLE
Add `internet` resource type and related portal updates required for full-route

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#5852]
Right now all resources have either a single address. However, for "Internet Resource"/Full route we need 2 different routes, IPv6/IPv4.

To be able to achieve this in a backwards compatible way, we can't just add a new resource kind, as this would break the `init` message deserialization.

What we should do instead is on the init message add a new field `internet_resource: bool` and then have a special message to enable/disable.

With this in mind we can also have the UI reflect this, having a single "Internet Resource"(such as a checkbox?) per-site, since it doesn't need no can handle many of the nuances that a normal resource have, such as filters and a particular name.

This requires updates both to connlib and the portal.

Feel free to chip in in this design @AndrewDryga

```[tasklist]
- [ ] Add `allow_user_to_disable: boolean` to `policies` shown only for internet resources
- [ ] Add `internet` resource type
- [x] Determine what to do about `address` field
- [ ] DB constraint to only have one `internet` resource per account
- [ ] Policy conditions don't apply to `internet` resources.
- [ ] Traffic filters don't apply to `internet` resources.
- [ ] Only send 'internet' resources to client versions that can support it (`v1.2`)
```

**Comment by thomaseizinger** [comment]
We should change our deserialisation to gracefullu handle unknown resource types, then we can roll this out iteratively.

Another option is to version the `init` message:

- Portal sends `init` & `init2`
- Client ignores whichever one they don't support

**Comment by conectado** [comment]
> We should change our deserialisation to gracefullu handle unknown resource types, then we can roll this out iteratively.
> 
> Another option is to version the `init` message:
> 
>     * Portal sends `init` & `init2`
> 
>     * Client ignores whichever one they don't support

I agree that's a good idea to add handling for unkown resource types going forward! But that'd still require a breaking change right now.

2 Different init messages do work in a backward compatible way.

**Comment by thomaseizinger** [comment]
> I agree that's a good idea to add handling for unkown resource types going forward! But that'd still require a breaking change right now.

Why would that be breaking? We can ship the "ignore unknown resources types" now, have people upgrade and then ship the new resource type. It is the same story as with the DNS resource changes :)

**Comment by conectado** [comment]
> > I agree that's a good idea to add handling for unkown resource types going forward! But that'd still require a breaking change right now.
> 
> Why would that be breaking? We can ship the "ignore unknown resources types" now, have people upgrade and then ship the new resource type. It is the same story as with the DNS resource changes :)

We can do that but I think we are trying to minimize those kind of changes, meaning requiring people to upgrade their client

**Comment by thomaseizinger** [comment]
> > > I agree that's a good idea to add handling for unkown resource types going forward! But that'd still require a breaking change right now.
> > 
> > 
> > Why would that be breaking? We can ship the "ignore unknown resources types" now, have people upgrade and then ship the new resource type. It is the same story as with the DNS resource changes :)
> 
> We can do that but I think we are trying to minimize those kind of changes, meaning requiring people to upgrade their client

A new version of `init` would also allow us to remove this cruft: https://github.com/firezone/firezone/blob/d95193be7d1651a3c876b79dcc0bae44518371ed/rust/connlib/tunnel/src/utils.rs#L8-L58

**Comment by conectado** [comment]
> > > > I agree that's a good idea to add handling for unkown resource types going forward! But that'd still require a breaking change right now.
> > > 
> > > 
> > > Why would that be breaking? We can ship the "ignore unknown resources types" now, have people upgrade and then ship the new resource type. It is the same story as with the DNS resource changes :)
> > 
> > 
> > We can do that but I think we are trying to minimize those kind of changes, meaning requiring people to upgrade their client
> 
> A new version of `init` would also allow us to remove this cruft:
> 
> https://github.com/firezone/firezone/blob/d95193be7d1651a3c876b79dcc0bae44518371ed/rust/connlib/tunnel/src/utils.rs#L8-L58

So what we can do

* Add new `InternetResource` resource description
* `init` must never contain an `InternetResource`
* new `init_v2` message(we can decide on a different name) which includes all valid resources
* `init_v2` should change the `relay` message to just have the `turn` type and no `stun` things.

Though, the `InternetResource` will need quite a lot of special handling in connlib compared to other resources.

**Comment by jamilbk** [comment]
@thomaseizinger As we thought through it, we realized that would be email-blasting another breaking change "upgrade your gateway now" and then "upgrade your client after X weeks" messages.

- If we introduce a breaking Client change and update the portal to start version, minor needs to be bumped (the clients all have slightly different patch versions, so conditionally sending the new resource type based on this would be not ideal)
- New Client minor means new Gateway minor, which means version incompatibility
- We could blast thousands of admins again, but this doesn't come for free. While the actual DNS refactor switchover went smoothly, consider the following pains: some wanted the Clients before we released them, some didn't upgrade at all (presumably their access broke and they possibly left -- we may want to measure this), and some did it begrudgingly because they weren't using DNS Resources.

If we can keep those to a minimum and settle on some kind of regular cadence so that breaking changes are expected (I know this is hard with everything moving quickly) then we can break things for _very_ old clients/gateways without eroding too much trust in the product.

**Comment by jamilbk** [comment]
I mentioned this on standup today -- I feel these breaking changes are a side effect of the rigid, zero-abstraction type system when deserialized strings into structs and such.

Currently, if the shape of any the data is off by just one field, we break the whole API. We have some flexibility on the message types, but that's it right? I'm guessing it's a pain to extend this flexibility to all structs?

**Comment by thomaseizinger** [comment]
> I mentioned this on standup today -- I feel these breaking changes are a side effect of the rigid, zero-abstraction type system when deserialized strings into structs and such.
> 
> Currently, if the shape of any the data is off by just one field, we break the whole API. We have some flexibility on the message types, but that's it right? I'm guessing it's a pain to extend this flexibility to all structs?

I understand why you are making that connection but it isn't quite that way. It is certainly possible to configure our deserialiser to be forwards-compatible. We are already forwards compatible for addition of new fields, that is the default. Enums are a bit trickier, we should probably avoid using those in the API with the portal wherever we can.

> If we can keep those to a minimum and settle on some kind of regular cadence so that breaking changes are expected (I know this is hard with everything moving quickly) then we can break things for _very_ old clients/gateways without eroding too much trust in the product.

Yeah I agree with this. My comment about the similarity to the DNS changes wasn't meant to imply that we need to do it with the same cadence. Plus, we can just go with the `init_v2` route where we don't have these issues at all!

**Comment by thomaseizinger** [comment]
> > I mentioned this on standup today -- I feel these breaking changes are a side effect of the rigid, zero-abstraction type system when deserialized strings into structs and such.
> > Currently, if the shape of any the data is off by just one field, we break the whole API. We have some flexibility on the message types, but that's it right? I'm guessing it's a pain to extend this flexibility to all structs?
> 
> I understand why you are making that connection but it isn't quite that way. It is certainly possible to configure our deserialiser to be forwards-compatible. We are already forwards compatible for addition of new fields, that is the default. Enums are a bit trickier, we should probably avoid using those in the API with the portal wherever we can.

The main reason we aren't is simply because it wasn't a priority so far amongst all the other things to think about how we want to be forwards-compatible.

Whilst we are at it, we should also introduce a hard split of types and have a dedicated set of types that represent the API vs what is used in connlib internally. Those may change for different reasons so they should be different types.

**Comment by jamilbk** [comment]
Got it, thanks for clarifying!

**Comment by thomaseizinger** [comment]
I've had a look through our messages and apart from `resources` and `relays` (both discussed further above), we don't have any enums in our messages. The resources one also applies to the gateway though, there we also have a `resource` field that is currently an enum.

Instead of using enums, I think we should have different fields & messages to express this variability:

`init_v2` could look like this:

```json
{
    "event": "init_v2",
    "payload": {
        "interface": { },
        "dns_resources": [ ],
        "cidr_resources": [ ]
    },
    "ref": null,
    "topic": "client"
}
```

This is much easier to extend in a forwards-compatible way because unknown fields are always ignored, meaning we can easily add an `internet_resource` field or add additional fields within a particular resource type.

For the `request_connection` message to the gateway, I am wondering why we are even sending the entire resources in a JSON encoded way? Instead, we could simply reference it by `resource_id` and push the resources to the gateway the same way we do for the client. The same applies to the `allow_access` request. IMO that one should also carry the `resource_id` and not the entire resource payload.

**Comment by thomaseizinger** [comment]
> I've had a look through our messages and apart from `resources` and `relays` (both discussed further above), we don't have any enums in our messages. The resources one also applies to the gateway though, there we also have a `resource` field that is currently an enum.

I just discovered that we have the same problem for the resource filters. There, we are also using an `enum` to express the various filter types.

**Comment by jamilbk** [comment]
Will the init_v2 handle updates to the Site / internet resource too? We discussed it probably makes sense actually to just have a toggle on sites for "use for internet" or "exit node".

Still undecided on that, but the reasons for it would be that:
- filters don't make sense for internet resources
- address, name and address description don't quite make sense either
- neither do policy conditions

Regardless of how the backend looks, we want internet "resources" in a special section of the client menu at the top to stand out and allow users to enable/disable.

we probably still want admins to enable/disable the internet resource for groups of users via policies though. refs #5121

**Comment by thomaseizinger** [comment]
> Will the init_v2 handle updates to the Site / internet resource too?

Init is only sent once but we can apply the same idea the resource update message if that is what you mean?

**Comment by conectado** [comment]
> I've had a look through our messages and apart from `resources` and `relays` (both discussed further above), we don't have any enums in our messages. The resources one also applies to the gateway though, there we also have a `resource` field that is currently an enum.
> 
> Instead of using enums, I think we should have different fields & messages to express this variability:
> 
> `init_v2` could look like this:
> 
> ```json
> {
>     "event": "init_v2",
>     "payload": {
>         "interface": { },
>         "dns_resources": [ ],
>         "cidr_resources": [ ]
>     },
>     "ref": null,
>     "topic": "client"
> }
> ```
> 
> This is much easier to extend in a forwards-compatible way because unknown fields are always ignored, meaning we can easily add an `internet_resource` field or add additional fields within a particular resource type.
> 
> For the `request_connection` message to the gateway, I am wondering why we are even sending the entire resources in a JSON encoded way? Instead, we could simply reference it by `resource_id` and push the resources to the gateway the same way we do for the client. The same applies to the `allow_access` request. IMO that one should also carry the `resource_id` and not the entire resource payload.

We don't need to use separate fields for different types for this. Enums would work if we just have an `other` fallback for all portal enums.

If we separate the api/connlib types, as I agree we should, we can discard those enums when mapping the api types to connlib types.

**Comment by conectado** [comment]
I just talked with @AndrewDryga and the portal can just send the message to the clients above a certain minor, and those can still connect to any gateway.

So, we can just not make thiese changes, at least for now, just add a new resource type (we can also add the `unknown` resource type so that in the future we are compatible with newer resource types), and the portal will only send the internet resource type for clients with the new minor.

**Comment by thomaseizinger** [comment]
> We don't need to use separate fields for different types for this. Enums would work if we just have an `other` fallback for all portal enums.

They would also not be a problem if we didn't have any. By default, serde is leniant to field additions, hence I was thinking to make it an API design rule to not use any enums. Then we can't forget to add a fallback variant.

The question becomes "what is easier to not forget?":

- Always having an "other" variant
- Not using enums entirely

I feel like the latter would be a bit easier because new designs would likely be inspired by existing ones and thus also not use enums.

Unrelated to that, "flat" APIs have a nice simplicity to them because there is no variability in the messages. Basically, less things can go wrong if the data always has the same shape.

**Comment by thomaseizinger** [comment]
For resource types specificially, we handle them entirely separate in pretty much every part of the codebase, so I don't really see much of an appeal in handling them using an enum.

It would be an interesting experiment to even separate the IDs on a type-level. Being able to statically enforce that a certain resource ID is a DNS resource could be useful.

**Comment by conectado** [comment]
> > We don't need to use separate fields for different types for this. Enums would work if we just have an `other` fallback for all portal enums.
> 
> They would also not be a problem if we didn't have any. By default, serde is leniant to field additions, hence I was thinking to make it an API design rule to not use any enums. Then we can't forget to add a fallback variant.
> 
> The question becomes "what is easier to not forget?":
> 
>     * Always having an "other" variant
> 
>     * Not using enums entirely
> 
> 
> I feel like the latter would be a bit easier because new designs would likely be inspired by existing ones and thus also not use enums.
> 
> Unrelated to that, "flat" APIs have a nice simplicity to them because there is no variability in the messages. Basically, less things can go wrong if the data always has the same shape.

This makes sense, I just find the express-ability of enums quite nice to work with smeantically.

Though, I do see how for an the API to communicate with the portal this might not be so important, since we can always and should always transform the message to our internal type before handling that, and that's where methods should live.

**Comment by conectado** [comment]
> For resource types specificially, we handle them entirely separate in pretty much every part of the codebase, so I don't really see much of an appeal in handling them using an enum.
> 
> It would be an interesting experiment to even separate the IDs on a type-level. Being able to statically enforce that a certain resource ID is a DNS resource could be useful.

Routing is where they are the same, so if we do something like this, a function `get_resource_by_destination` would need to return a `ResourceId` enum which is either `Gateway` or `Client`.

But then again, routing will be changing quite a bit on #4789 so maybe we can take a look into this when we address that.

**Comment by jamilbk** [comment]
Just summarizing where we landed on this -- we can conditionally send the `internet` Resource type to only Clients v1.2 and above. So I think this isn't needed, correct?

We'll need to do that for #5056 anyhow.

**Comment by thomaseizinger** [comment]
> Just summarizing where we landed on this -- we can conditionally send the `internet` Resource type to only Clients v1.2 and above.

My opinion is that introducing new fields that are automatically ignored by older clients is going to be easier to maintain going forward because the portal contains less conditional code based on the client-version. My suggestion would be to do something like:

```diff
{
     "event": "init",
     "payload": {
         "interface": { },
         "resources": [ ],
+        "internet_resource": { } // There can only be 1 internet resource, hence this is an object, not an array.
      },
     "ref": null,
     "topic": "client"
}
```

**Comment by conectado** [comment]
> > Just summarizing where we landed on this -- we can conditionally send the `internet` Resource type to only Clients v1.2 and above.
> 
> My opinion is that introducing new fields that are automatically ignored by older clients is going to be easier to maintain going forward because the portal contains less conditional code based on the client-version. My suggestion would be to do something like:
> 
> ```diff
> {
>      "event": "init",
>      "payload": {
>          "interface": { },
>          "resources": [ ],
> +        "internet_resource": { } // There can only be 1 internet resource, hence this is an object, not an array.
>       },
>      "ref": null,
>      "topic": "client"
> }
> ```

We need to additionally add a new message for the case equivalent to `create_or_update_resource`.

In that case a new message would make the most sense.

**Comment by thomaseizinger** [comment]
> In that case a new message would make the most sense.

Yeah, that one will also just be ignored silently by old clients.

**Comment by conectado** [comment]
> > In that case a new message would make the most sense.
> 
> Yeah, that one will also just be ignored silently by old clients.

Something like this I think would work:

```
{
    "event": "internet_resource_updated",
    "payload": {
        "enabled": bool
        "site": <SiteId>
    }
    "ref": null,
    "topic": "client"
}
```

**Comment by jamilbk** [comment]
```
{
  "event": "internet_resource_updated",
  "payload": {
    "allow_user_to_disable": bool,
    "sites": [{"site_id": "...", "name": "SJC"}]
  },
  "ref": null,
  "topic": "client"
}
```

@conectado `sites` is an array, no? And we need a field to allow the user to toggle on/off.

**Comment by conectado** [comment]
> ```
> {
>   "event": "internet_resource_updated",
>   "payload": {
>     "allow_user_to_disable": bool,
>     "sites": [{"site_id": "...", "name": "SJC"}]
>   },
>   "ref": null,
>   "topic": "client"
> }
> ```
> 
> @conectado `sites` is an array, no? And we need a field to allow the user to toggle on/off.

Yeah, but we do also need the enable/disabled field, we need to update when the resource is deactivated from the portal.

```
{
   "event": "internet_resource_updated",
   "payload": {
       "allow_user_to_disable": bool,
       "sites": [{"site_id": "...", "name": "SJC"}]
       "enabled": bool
     },
    "ref": null,
    "topic": "client"
}
```

Or 2 different messages would also work

**Comment by thomaseizinger** [comment]
What is the difference between disabled in the portal and removing it with `remove_resource`? All our other resources just get removed when the policy is disabled.

**Comment by conectado** [comment]
> What is the difference between disabled in the portal and removing it with `remove_resource`? All our other resources just get removed when the policy is disabled.

Yeah, that works too, we just need to add the `resource_id`

**Comment by thomaseizinger** [comment]
> > What is the difference between disabled in the portal and removing it with `remove_resource`? All our other resources just get removed when the policy is disabled.
> 
> Yeah, that works too, we just need to add the `resource_id`

I would have assumed that same as all other resources, an Internet resource has a resource ID. There is an overlap here in what we are discussing in https://github.com/firezone/firezone/issues/5056. I think we should normalise (in the database design meaning) things here and reference resources by ID everywhere except when they actually get updated themselves.
