### ISSUE TITLE
Trigger CI build package when release is drafted

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#591]
Now that release drafter is implemented, need to trigger the package builds corresponding to the tag when release is published.

**Comment by princemaple** [comment]
When release is drafted or when release is published (tag pushed) ?

We can break the build into a separate workflow.

If you want it to run on draft, it's the same as on push but limited to master.
If you want published, we can do on push but with a tag.

**Comment by jamilbk** [comment]
@princemaple Ah, I think when release is published (tag pushed). The way it was working before, the release is created in the GH action when the tag is pushed, then the built artifacts are renamed accordingly and uploaded and attached to the release. I can take a look on this one -- probably involves dropping the create-release step and uploading to the existing drafted release, then publishing it.

https://github.com/firezone/firezone/blob/master/.github/workflows/ci.yml#L245

**Comment by jamilbk** [comment]
Fixed by #619 among others
