### ISSUE TITLE
index html?

### ISSUE THREAD

**Issue by ghost** [CloudFire-LLC/cloudfire#594]
Where is the index html or files that generate it located at? I want to include some text and a link on the page.

**Comment by jamilbk** [comment]
Hi @vontainment -- You can find the root template for unauthenticated users here:

https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/templates/root/auth.html.heex

**Comment by ghost** [comment]
That I found. But on an already installed installation, where is the file?

**Comment by jamilbk** [comment]
@vontainment Ah unfortunately Elixir is a compiled language, so that template file is compiled to BEAM bytecode and becomes a binary file.

If you'd like to try your luck hacking on it, check the installation at `/opt/firezone/embedded/service/firezone`.

Good luck!

**Comment by ghost** [comment]
I'm sadly not experienced with Elixir. If I clone this repo and change it. 
Would i beable to update a currently installed version?

Or would it be easier to clone, change, install on a temp VM.  copy the /opt/firezone/embedded/service/firezone directory and overwrite the current install?

**Comment by jamilbk** [comment]
You could, but you'd have to rebuild Firezone on the server you want to install the package on. Not impossible -- see how it's built: .github/workflows/ci.yml

Depending on what you're trying to accomplish you'll probably have an easier time accomplishing this by editing the bundled nginx config at /opt/firezone/embedded/service/nginx. You could add an index.html for the root path and use a prefix for the Firezone upstream phoenix app, e.g. `/firezone` then update your external_url setting to match.

**Comment by ghost** [comment]
Your amazing!! That is a totally easy solution. TY so much!!! Nginx i know well so I can do that lol
