### ISSUE TITLE
"You have exceeded" displayed even after reducing users to within limit

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5941]
<img width="705" alt="Screenshot 2024-07-21 at 9 55 35 PM" src="https://github.com/user-attachments/assets/ce467ce9-beb1-428e-a920-b13a3b741fc0">

<img width="579" alt="Screenshot 2024-07-21 at 9 55 49 PM" src="https://github.com/user-attachments/assets/2738186d-fef1-4fc1-90bf-79669ba7550b">

**Comment by jamilbk** [comment]
Maybe deleted users still count against limit?

**Comment by AndrewDryga** [comment]
This was an issue of background job not recalculating the account warnings.
