### ISSUE TITLE
settings/[device_id]/edit page does not exist

### ISSUE THREAD

**Issue by sincerite** [CloudFire-LLC/cloudfire#595]
Hello,

Described in the docs page doesn't exist. Is this my configuration problem or something is wrong with docs?
Currently there's no option to edit device settings so I have to remove device and add with new settings.

![image](https://user-images.githubusercontent.com/29306505/168426311-f976dee1-d781-47df-821e-9464601524a7.png)

![image](https://user-images.githubusercontent.com/29306505/168426440-5ca7b4aa-1635-45aa-b6d5-83801395f13e.png)

**Comment by jamilbk** [comment]
cc @gongjason 

Thanks for reporting! Things changed a bit in 0.3.0 around the way keys were generated and stored, so apologies for the cobwebs. We'll get the docs cleaned up.

Could you clarify which device settings specifically you're interested in changing?
