### ISSUE TITLE
`connlib` crashes with no backtrace / log if DNS upstream can't be reached during `Session.connect`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5965]
I only have the `demo-postgres` DNS Resource added in a fresh `demo` account on staging.

I've noticed that forwarded queries sometimes hang and time out with hickory. This is happening sporadically and intermittently.

Latest Test Flight client on macOS. Will try to capture better logs.

**Comment by jamilbk** [comment]
This is using my local DHCP resolvers:

<img width="258" alt="Screenshot 2024-07-22 at 3 10 01 PM" src="https://github.com/user-attachments/assets/9722ecb7-e4a6-4e0b-af6f-90515c95d4da">

**Comment by jamilbk** [comment]
Here's a failed query:

```
jamil@Airbook-Mac:~ % dig vercel.live

; <<>> DiG 9.10.6 <<>> vercel.live
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 54807
;; flags: qr; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; Query time: 2992 msec
;; SERVER: 100.100.111.1#53(100.100.111.1)
;; WHEN: Mon Jul 22 15:04:58 PDT 2024
;; MSG SIZE  rcvd: 12
```

**Comment by jamilbk** [comment]
Seeing a few of these in the logs:

```
connlib	15:13:13.961047-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
```

Not sure why. `dig @<dns_ip>` works fine.

Perhaps we have a bug with hickory opening too many sockets?

**Comment by jamilbk** [comment]
cc @conectado for visibility.

**Comment by jamilbk** [comment]
This could very well be my crappy Router. I'll test with a different upstream to rule that out.

**Comment by jamilbk** [comment]
If a DNS server can't be reached in `Session.connect`, connlib crashes with no error trace and nothing reported in logs. Not sure if this is a `hickory` issue connecting to IPv6 DNS servers, but should probably at least log an error.

Log level I'm hitting this with is `debug`. Outcome is that client moves to sign out state a few seconds after successfully signing in, without successfully loading resources.

**Comment by thomaseizinger** [comment]
> Outcome is that client moves to sign out state a few seconds after successfully signing in, without successfully loading resources.

This means `on_disconnected` got called, right? I'll see what codepaths there are that don't end up logging anything.

**Comment by thomaseizinger** [comment]
> > Outcome is that client moves to sign out state a few seconds after successfully signing in, without successfully loading resources.
> 
> This means `on_disconnected` got called, right? I'll see what codepaths there are that don't end up logging anything.

There are none. We always log something if connlib shuts down.

Are you sure connlib even boots up and it is not the `connect` call itself that already fails? We do try to connect to the portal synchronously in `connect` so if that isn't possible, you won't be able to create a session.

**Comment by thomaseizinger** [comment]
> Are you sure connlib even boots up and it is not the `connect` call itself that already fails?

Do you see this error log?

https://github.com/firezone/firezone/blob/c94f9edb27eae47e2b1880be60de0f300c69008e/swift/apple/FirezoneNetworkExtension/Adapter.swift#L151

**Comment by jamilbk** [comment]
No I don't. I see adapter start failed log with a null error, which usually means the connect call crashed.

If it crashes before tokio is initialized that would prevent any logging right?

**Comment by jamilbk** [comment]
No I don't. I see adapter start failed log with a null error, which usually means the connect call crashed.

If it crashes before tokio is initialized that would prevent any logging right?

**Comment by thomaseizinger** [comment]
> No I don't. I see adapter start failed log with a null error, which usually means the connect call crashed.
> 
> If it crashes before tokio is initialized that would prevent any logging right?

If it does indeed crash (i.e. panic in Rust terms) then we won't see a log yes. We only catch panics once connlib is started up.

However, `connect` returns a `Result` so it can just fail. The return type is a `String` on the Rust end. If you see `null` here then it means we loose the error message somewhere. Let me see what we can do here.

**Comment by jamilbk** [comment]
My first thought was that it's the DNS lookup we perform as connlib starts up.

**Comment by thomaseizinger** [comment]
> My first thought was that it's the DNS lookup we perform as connlib starts up.

That should get returned as an error from `connect`. But it seems this conversion might not work correctly? From reading https://chinedufn.github.io/swift-bridge/built-in/string/index.html, it seems that String's aren't directly converted. So perhaps the Rust string is de-allocated by the time the `connect` actually returned / is caught on the Swift side?

**Comment by jamilbk** [comment]
Session.connect returns a pointer though -- if it fails before the callbacks handle is initialized there wouldn't be a way to return a String. 

I'm afk I'll take a look in a fewZ

**Comment by thomaseizinger** [comment]
Could you try if you see any logs with https://github.com/firezone/firezone/pull/5969?
