### ISSUE TITLE
ci: disable vercel bot comment 

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5966]
As far as I know, we don't really use the functionality of commenting on the preview build of a website. Can we disable vercel's comment bot and thus reduce the notification / comment noise on GitHub?

**Comment by jamilbk** [comment]
@thomaseizinger We do use it from time to time -- also just added @Patticatti to Vercel so we can use this workflow now 😃

**Comment by thomaseizinger** [comment]
Ha! Is there a way we can disable it for PRs that don't actually change the website?

**Comment by jamilbk** [comment]
Updated it to prevent builds that don't touch `website/`

**Comment by thomaseizinger** [comment]
Just opened another PR (https://github.com/firezone/firezone/pull/5967) and still seeing the comment. Is this meant to be in effect already?

**Comment by jamilbk** [comment]
We can't disable the comment unfortunately. It did skip the build though.

**Comment by thomaseizinger** [comment]
> We can't disable the comment unfortunately. It did skip the build though.

That is a bummer. I don't mind the build, it is the comment-noise that is mildly annoying.
