### ISSUE TITLE
Running firezone behind dedicated nginx reverse proxy

### ISSUE THREAD

**Issue by onyxkyr** [CloudFire-LLC/cloudfire#601]
Hello everyone,

I was very excited to setup firezone seeing the new universal odic implementation.
However, I am running into trouble setting it up behind a reverse proxy.
In my environment, I have one central nginx reverse proxy which handles all ssl termination etc.

My desired setup is the following, where `mydomain.com` is my domain.
I want firezone to be under `firezone.mydomain.com`, which terminates (Ports 80 and 443) on my reverse proxy. 

Just setting the `default['firezone']['external_url'] = firezone.mydomain.com` in the firezone.rb and running `firezonectl reconfigure` does not suffice, I can't get the integrated nginx working properly. 

Is it possible to bind the phonix upstream 
`upstream phoenix {
  server 127.0.0.1:13000;
}`

to a specific interface of the machine firezone runs on (which is reachable from my reverse proxy)?
Then I could have the nginx configuration (ssl termination and so forth) on my dedicated reverse proxy?
Or, alternatively, can the firezone integrated nginx be configured to use a different servername than it is serving?

**Comment by jamilbk** [comment]
I think this may be possible if we expose a setting to configure the phoenix listen address. That way you'll be able to disable the bundled nginx and use your dedicated proxy, pointed to the Firezone instance. I'll see if I can merge an update shortly.

**Comment by jamilbk** [comment]
Hi @onyxkyr -- does #604 look like it'll address your issue?

**Comment by onyxkyr** [comment]
Hey @jamilbk -- looking at the changes this should suffice. However, I am unsure how I can test it without finding the location of those 5 changed files and changing them manually?

Thanks already for the quick response!

**Comment by jamilbk** [comment]
@onyxkyr Hmm, are you referring to Firezone's nginx config files?

What if you did something like this:

- Configure your dedicated reverse proxy based on inspiration from Firezone's generated Nginx config: `/var/opt/firezone/nginx/etc/nginx.conf` and `/var/opt/firezone/nginx/etc/sites-enabled/phoenix`
- Set `default['firezone']['nginx']['enabled'] = false` in your `/etc/firezone/firezone.rb`
- Set `default['firezone']['phoenix']['listen_address']` to your desired interface address
- `firezone-ctl reconfigure`

If that suffices, I'll cut a release today-ish to include #604

**Comment by onyxkyr** [comment]
No, that is quite exactly what I had in mind configuration-wise.
I can't test it because I don't know how to deploy your pull request branch onto my machine,
because my git knowledge is insufficient (besides manually editing the files changed in your pr).
If you put it into a release I will happily test it out tomorrow.

**Comment by jamilbk** [comment]
@onyxkyr Great, I'll cut `0.3.13` then soon!

**Comment by onyxkyr** [comment]
@jamilbk Just a quick follow up, it works nicely behind a nginx reverse proxy.

I wanted to also serve the static files found in the firezone nginx config, but found the path `/opt/firezone/embedded/service/firezone/public` to be empty in my installation? Or rather, the subfolder `public` does not exist for me.
