### ISSUE TITLE
DNS forwarding to upstream resolver occasionally times out

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6033]
Seeing this consistently on macOS. After some time (maybe 30 minutes to an hour), all queries to my local network IPv6 upstream fails. `dig @` directly to the IPv6 DNS server continues to work during this time.

Maybe a socket pool exhaustion issue? Marking as high priority since this will effectively break internet while Firezone is signed in if the upstream resolver behaves like this and may be an issue on all platforms.

Using latest version of the TestFlight client. Logs attached.

```
connlib	21:43:08.033915-0700	hickory_resolver::name_server::name_server: reconnecting: NameServerConfig { socket_addr: [2600:1700:3ecb:2410::1]:53, protocol: Udp, tls_dns_name: None, trust_negative_responses: true, bind_addr: None }
connlib	21:43:08.034082-0700	hickory_proto::xfer: enqueueing message:QUERY:[Query { name: Name("github.com"), query_type: A, query_class: IN }]
connlib	21:43:08.034177-0700	hickory_proto::udp::udp_client_stream: final message: ; header 48505:QUERY:RD:NoError:QUERY:0/0/1
; edns version: 0 dnssec_ok: false z_flags: 0x0000 max_payload: 1232 opts: 0
; query
;; github.com. IN A
connlib	21:43:08.034343-0700	hickory_proto::udp::udp_stream: created socket successfully
connlib	21:43:08.415698-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
connlib	21:43:08.416038-0700	on_dns_result{name=github.com server=fd00:2021:1111:8000:100:100:111:0}: firezone_tunnel::client: DNS query failed: proto error: request timed out
connlib	21:43:08.416218-0700	hickory_proto::xfer::dns_exchange: io_stream is done, shutting down
connlib	21:43:09.662375-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
connlib	21:43:09.662558-0700	hickory_resolver::name_server::name_server_pool: sending request: [Query { name: Name("github.com"), query_type: A, query_class: IN }]
connlib	21:43:09.662683-0700	hickory_resolver::name_server::name_server: reconnecting: NameServerConfig { socket_addr: [2600:1700:3ecb:2410::1]:53, protocol: Udp, tls_dns_name: None, trust_negative_responses: true, bind_addr: None }
connlib	21:43:09.662760-0700	hickory_proto::xfer: enqueueing message:QUERY:[Query { name: Name("github.com"), query_type: A, query_class: IN }]
connlib	21:43:09.662844-0700	hickory_proto::udp::udp_client_stream: final message: ; header 33719:QUERY:RD:NoError:QUERY:0/0/1
; edns version: 0 dnssec_ok: false z_flags: 0x0000 max_payload: 1232 opts: 0
; query
;; github.com. IN A
connlib	21:43:09.662898-0700	hickory_proto::xfer::dns_exchange: io_stream is done, shutting down
connlib	21:43:09.663047-0700	hickory_proto::udp::udp_stream: created socket successfully
connlib	21:43:10.506659-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
connlib	21:43:10.506970-0700	on_dns_result{name=github.com server=fd00:2021:1111:8000:100:100:111:0}: firezone_tunnel::client: DNS query failed: proto error: request timed out

```

refs #5965

**Comment by jamilbk** [comment]
This can be reproduced with a "DNS bomb":

```
for i in {1..50}; do
dig -t A $(openssl rand -hex 2).github.com &
done
```

Actually, I think this might be because my local DNS resolver stops responding. Does hickory perform any kind of caching?

I tested with Cloudflare's IPv6 upstream and it seems to work without issue.

**Comment by jamilbk** [comment]
Update: issue not related to IPv6. Happening for my local resolver IPv4 as well. I wonder if the `WARNING: recursion requested but none available` is causing an issue with my router's resolver.

This is only happening when Firezone is enabled, and that's the only difference I see in replies from the connlib sentinel vs normal use (where DNS is 100% reliable).

**Comment by jamilbk** [comment]
Update: Google public DNS also _does not_ exhibit the issue. My router (stock firmware) provided by my ISP (AT&T) does.

I imagine it will be prevalent on many other home routers as well.

**Comment by conectado** [comment]
Hickory does indeed do some caching, I don't know the internals.

If caching is the issue, roaming should "fix it" as in we discard the resolver therefore any cache. 

@jamilbk do you mind testing if roaming, you can disconnect for a few seconds and reconnect, while this is happening fixes it?

**Comment by jamilbk** [comment]
Interesting result:

- If I run the `dig` bomb after a fresh sign in, I hit this issue. This can be at any point after signing in, though I imagine there are DNS requests immediately hitting hickory after signing in.
- If I roam (turn WiFi off and on), I can't hit the issue no matter how many dig bombs I try

Are we doing something different when initializing hickory's Resolver after roaming than we do when initially starting a session?

**Comment by jamilbk** [comment]
Is is possible there's a race condition when picking the socket for hickory to use when starting connlib?

**Comment by thomaseizinger** [comment]
MacOS is the only platform where we don't do any socket / routing loop protection. Could it be related to that?

**Comment by jamilbk** [comment]
This is on prod with only a handful of resources active. I also tested on demo with only a single resource active and it still behaved the same, so I don't _think_ it could be a loop, but I can check on Linux too and see.

**Comment by jamilbk** [comment]
Tested on the Linux VM and can't reproduce. But that is going through systemd-resolved first, so a bit different.

**Comment by ReactorScram** [comment]
Did you want me to test this on bare metal Windows?

**Comment by jamilbk** [comment]
@ReactorScram Yeah that would be helpful (and even macOS too). I've been able to reliably reproduce using the dig bomb above:

```
for i in {1..50}; do
dig -t A $(openssl rand -hex 2).github.com &
done
```

**Comment by jamilbk** [comment]
I'll build new TestFlight clients to just be sure it's still an issue.

**Comment by ReactorScram** [comment]
I thought I updated Firezone on macOS to 1.1.2 but now it's saying 1.1.0 again. I haven't gotten this issue to replicate. I'll try it on Windows eventually

**Comment by jamilbk** [comment]
Ok. Update - this happens after roaming as well. I've narrowed it down to using two or more upstreams. When that's the case, one of them inevitably times out.

**Comment by thomaseizinger** [comment]
> Ok. Update - this happens after roaming as well. I've narrowed it down to using two or more upstreams. When that's the case, one of them inevitably times out.

So it is not reproducible with a single upstream? This is honestly puzzling. What are we meant to do if the upstream DNS server stops responding?

I see that your upstream servers are UDP-only. Is there a way you can test with a TCP DNS server?

**Comment by thomaseizinger** [comment]
> Maybe a socket pool exhaustion issue?

I did notice in the past the hickory doesn't really keep its sockets around for some reason.

**Comment by jamilbk** [comment]
> I see that your upstream servers are UDP-only. Is there a way you can test with a TCP DNS server?

Ah, maybe that's the culprit. The issue does not happen when I use public DNS servers like Cloudflare or Google.

The UDP-only servers are my DHCP-provided ones by my ISP.

Could there be an issue with hickory trying to connect over TCP or DoT/DoH?

**Comment by thomaseizinger** [comment]
> The UDP-only servers are my DHCP-provided ones by my ISP.
> 
> Could there be an issue with hickory trying to connect over TCP or DoT/DoH?

We configured hickory to use UDP & TCP. On failing shouldn't invalidate the other but what I suspect is that they don't support TCP at all and for some reason, UDP starts to fail eventually.

**Comment by jamilbk** [comment]
Even when using Cloudflare's DNS server `hickory` still connects over UDP

```
hickory_resolver::name_server::name_server: existing connection: NameServerConfig { socket_addr: 1.1.1.1:53, protocol: Udp, tls_dns_name: None, trust_negative_responses: true, bind_addr: None }
```

Also, my local DNS servers _do_ respond on TCP as well, so that may not be the issue.

The only difference I can see is that the `WARNING: recursion requested but none available` occurs with Firezone active.

**Comment by thomaseizinger** [comment]
> The only difference I can see is that the `WARNING: recursion requested but none available` occurs with Firezone active.

Yeah hickory sets this by default. We can turn it off? I'd have to research what it does.

**Comment by thomaseizinger** [comment]
Can you test with https://github.com/firezone/firezone/pull/6063?

**Comment by jamilbk** [comment]
Actually, the other thing that's different between connlib's sentinel and a public DNS server is our reported maximum EDNS payload size:

```
jamil@Airbook-Mac:~ % dig google.com

; <<>> DiG 9.10.6 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17051
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		182	IN	A	142.250.189.206

;; Query time: 46 msec
;; SERVER: 100.100.111.2#53(100.100.111.2)
;; WHEN: Fri Jul 26 07:32:48 PDT 2024
;; MSG SIZE  rcvd: 55
```

`connlib` is reporting `4096` here while Cloudflare only reports `1232`:

```
jamil@Airbook-Mac:~ % dig google.com

; <<>> DiG 9.10.6 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5695
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		239	IN	A	142.250.191.46

;; Query time: 53 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Jul 26 07:32:55 PDT 2024
;; MSG SIZE  rcvd: 55
```

Could this cause fragmentation or result in applications making EDNS queries that my local network resolver cannot handle because the payload is too large?

**Comment by jamilbk** [comment]
This is still happening quite often, making the macOS (possibly iOS) client unusable in my current network.

```
connlib	07:36:08.144969-0700	hickory_proto::udp::udp_client_stream: final message: ; header 25524:QUERY:RD:NoError:QUERY:0/0/1
; edns version: 0 dnssec_ok: false z_flags: 0x0000 max_payload: 1232 opts: 0
; query
;; i2-xlblwzcaksqtdfroqwcmuqlsblpkuq.init.cedexis-radar.net. IN AAAA
connlib	07:36:08.145076-0700	hickory_proto::udp::udp_client_stream: final message: ; header 7928:QUERY:RD:NoError:QUERY:0/0/1
; edns version: 0 dnssec_ok: false z_flags: 0x0000 max_payload: 1232 opts: 0
; query
;; i2-xlblwzcaksqtdfroqwcmuqlsblpkuq.init.cedexis-radar.net. IN A
connlib	07:36:08.145158-0700	hickory_proto::xfer::dns_exchange: io_stream is done, shutting down
connlib	07:36:08.145396-0700	hickory_proto::udp::udp_stream: created socket successfully
connlib	07:36:08.145566-0700	hickory_proto::udp::udp_stream: created socket successfully
connlib	07:36:08.165060-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
connlib	07:36:08.165278-0700	on_dns_result{name=i2-xlblwzcaksqtdfroqwcmuqlsblpkuq.init.cedexis-radar.net server=100.100.111.1}: firezone_tunnel::client: DNS query failed: proto error: request timed out
connlib	07:36:08.165462-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
connlib	07:36:08.165586-0700	on_dns_result{name=i2-xlblwzcaksqtdfroqwcmuqlsblpkuq.init.cedexis-radar.net server=100.100.111.1}: firezone_tunnel::client: DNS query failed: proto error: request timed out
connlib	07:36:08.165707-0700	hickory_proto::xfer::dns_exchange: io_stream is done, shutting down
connlib	07:36:08.165785-0700	hickory_proto::xfer::dns_exchange: io_stream is done, shutting down
connlib	07:36:10.017328-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
connlib	07:36:10.017570-0700	hickory_resolver::name_server::name_server_pool: sending request: [Query { name: Name("i2-xlblwzcaksqtdfroqwcmuqlsblpkuq.init.cedexis-radar.net"), query_type: A, query_class: IN }]
connlib	07:36:10.017673-0700	hickory_resolver::name_server::name_server: reconnecting: NameServerConfig { socket_addr: 192.168.1.254:53, protocol: Udp, tls_dns_name: None, trust_negative_responses: true, bind_addr: None }
connlib	07:36:10.017894-0700	hickory_proto::xfer: enqueueing message:QUERY:[Query { name: Name("i2-xlblwzcaksqtdfroqwcmuqlsblpkuq.init.cedexis-radar.net"), query_type: A, query_class: IN }]
connlib	07:36:10.018032-0700	hickory_resolver::name_server::name_server: name_server connection failure: request timed out
```

I can confirm that a `dig @192.168.1.254` for these domains succeeds when this issue is occurring. Feels like a possible socket or fragmentation issuue on Apple platforms, maybe others.

**Comment by jamilbk** [comment]
Let me see if I can capture a pcap.

**Comment by jamilbk** [comment]
Verified to be happening on Windows too, and for a customer.
