### ISSUE TITLE
QR code is too small in some cases

### ISSUE THREAD

**Issue by greenfork** [CloudFire-LLC/cloudfire#606]
If the config file contains a bit more information, for example if Allowed IPs field has a lengthy value such as `0.0.0.0/3, 32.0.0.0/7, 34.0.0.0/10, 34.64.0.0/11, 34.96.0.0/12, 34.112.0.0/14, 34.116.0.0/16, 34.117.0.0/19, 34.117.32.0/20, 34.117.48.0/21, 34.117.56.0/23, 34.117.58.0/24, 34.117.59.0/26, 34.117.59.64/28, 34.117.59.80/32, 34.117.59.82/31, 34.117.59.84/30, 34.117.59.88/29, 34.117.59.96/27, 34.117.59.128/25, 34.117.60.0/22, 34.117.64.0/18, 34.117.128.0/17, 34.118.0.0/15, 34.120.0.0/13, 34.128.0.0/9, 35.0.0.0/8, 36.0.0.0/6, 40.0.0.0/5, 48.0.0.0/4, 64.0.0.0/2, 128.0.0.0/1`, the phone can't read this code. Tested on two Android phones.

My suggestion would be to make the QR code generated bigger, probably taking the full width of a modal window. You can test this behavior, in two cases with a short value and a long value the distinction is clearly visible. I can't include example images since they contain private keys.

**Comment by jamilbk** [comment]
Thanks for reporting. Will queue up for a fix.
