### ISSUE TITLE
"Refusing to re-authenticate channel rebind"

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6090]
```
connlib	07:14:50.007814-0700	snownet::allocation: Invalid credentials, refusing to re-authenticate channel bind
connlib	07:14:50.514285-0700	snownet::node: Disconnecting from relay; authentication error rid=88689e4b-3df5-4817-bd51-a976dccf71f7
```

This happens after deploy. I'm not sure yet if it's affecting connectivity since I'm also experiencing #6033 quite heavily today.

**Comment by jamilbk** [comment]
Yeah, I think what possibly happened here is:

- Deploy to staging
- Relays start rotating
- Relay I'm currently on shuts down, Client jumps to another one
- All relays are down (for the current API session I'm on) - no ability to establish new connections
- API is rotated, client reconnects, receives new TURN creds, all is good

cc @AndrewDryga - is it possible that all relays could be rotated before the API VMs, causing a case where my Client won't be able to authenticate with any relay until the portal is restarted, giving my Client new credentials?

**Comment by thomaseizinger** [comment]
> * Relay I'm currently on shuts down, Client jumps to another one

Is your client built with #6060 merged?

**Comment by jamilbk** [comment]
Nah, it wasn't - test flight errored on update. I'll test now.

**Comment by thomaseizinger** [comment]
This is outdated now.
