### ISSUE TITLE
Mark clients/gateways/relays offline sooner

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6095]
Interesting bug:

Severing a Gateway's connection to the portal using `ufw deny out to ...` means it still shows online in the portal up to 45s, due to waiting for a phoenix heartbeat + heartbeat timeout. Source: I just tested this with a live Gateway and a live staging portal.

This means any network partition of a Client, Relay, or Gateway where a TCP RST is _not_ received will cause the portal to think that entity is alive, for up to ~~a minute~ **5** minutes. This means our data plane failover time could be up to `300s + 10s` for Gateways that experience an abrupt network partition.

We may want to reduce the phoenix idle timeout like Chris mentions here:

https://elixirforum.com/t/can-phoenix-channel-detect-client-offline-immediately-like-wifi-disconnected/25104/10

**Comment by jamilbk** [comment]
@AndrewDryga I just tested this with a timer, and I got exactly 5 minutes (!!) for a network partition in the WebSocket to be reflect in the PhoenixChannel on staging. I think the `http` idle_timeout may be that long by default?

In any case I think this may be contributing to some weirdness in some cases.

**Comment by AndrewDryga** [comment]
@jamilbk we set that explicitly last time https://github.com/firezone/firezone/pull/4489/files thinking that clients might want to decrease the heartbeat timeout when battery is low. What we can change is to set that per socket type (reduce for gateway and relays to 30s).

**Comment by jamilbk** [comment]
Yeah that might make sense. We may even want it lower like `10s` since we rely on the WebSocket state for so many things. What do you think?

**Comment by AndrewDryga** [comment]
@jamilbk we can't make it 10s in the portal only because then we need to decrease the heartbeat timeout for relays and gateways (30s right now as I remember). We need portal timeout to be at least 2-3x more than that.

**Comment by jamilbk** [comment]
Yeah I was thinking about that too -- what if we used `5s` for heartbeat and `10s` for timeout here?

Since we rely on our control plane so heavily that might be good.

**Comment by jamilbk** [comment]
This would affect existing clients/gateways though. So we'd need to maybe reduce those first, wait a few months, then change this.

**Comment by jamilbk** [comment]
Fixed in #6112 I believe.
