### ISSUE TITLE
Connlib panic onUpdateResources in CentOS 9

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6148]
<img width="1024" alt="Screenshot 2024-08-02 at 12 05 30 AM" src="https://github.com/user-attachments/assets/750a7680-6124-4b1f-890c-e163a499b0d0">

On staging. Not sure what triggered it - I think adding this service account to the `jamil` group on staging.

Perhaps the version of netlink on CentOS is problematic

**Comment by jamilbk** [comment]
Haven't been able to reproduce.

**Comment by thomaseizinger** [comment]
Appears to be a full channel. That will be hard to reproduce.

**Comment by ReactorScram** [comment]
I think that's the Client's fault, looks like a dupe of #5880. Oops

**Comment by ReactorScram** [comment]
#6184 should mitigate this now, so I'll close this as a duplicate. For the original issue there's a more permanent solution on the way Eventually.

I did reproduce this synthetically by just sleeping the thread that reads connlib callbacks, which caused the channel to overflow.
