### ISSUE TITLE
ux(gui-client): Opening GUI windows "twice" should bring existing to foreground

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6231]
This was a bit tricky to get right on macOS, but will prevent people thinking the GUI is not responding.

**Comment by ReactorScram** [comment]
Might be easy if we're lucky https://docs.rs/tauri/1.7.1/tauri/window/struct.Window.html#method.request_user_attention

**Comment by jamilbk** [comment]
I think it's probably this?

https://docs.rs/tauri/1.7.1/tauri/window/struct.Window.html#method.set_focus

**Comment by ReactorScram** [comment]
edit: nvm, got it ~~Was this Linux or Windows?~~
