### ISSUE TITLE
`channel bind failed: Allocation Mismatch`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6265]
I believe this to be the culprit behind the issue seen in Slack thread:

https://firezonehq.slack.com/archives/C07312PRYE4/p1723474901081049

It appears that a number of Relays are experiencing this issue. Link to Relay logs:

https://drive.google.com/file/d/1H2KefSZw5WzFpDs6Hk9VXwMwwAr6i8Jq/view?usp=sharing

**Comment by jamilbk** [comment]
Should these `channel bind` warnings be `error` instead?

**Comment by thomaseizinger** [comment]
> Should these `channel bind` warnings be `error` instead?

Well, it is hard to say in isolation (from the relay's perspective) whether that is an actual error. I guess we could upgrade them to errors. There is no case where we expect to receive an `Allocation Mismatch` when binding a new channel.

The actual cause is likely on the connlib-side though.

**Comment by thomaseizinger** [comment]
> It appears that a number of Relays are experiencing this issue. Link to Relay logs:
> 
> [drive.google.com/file/d/1H2KefSZw5WzFpDs6Hk9VXwMwwAr6i8Jq/view?usp=sharing](https://drive.google.com/file/d/1H2KefSZw5WzFpDs6Hk9VXwMwwAr6i8Jq/view?usp=sharing)

Are these the only logs? No `INFO`s around that?

**Comment by thomaseizinger** [comment]
Fixed in #6277.
