### ISSUE TITLE
Custom OIDC (authentik) leads to phoenix crashing

### ISSUE THREAD

**Issue by onyxkyr** [CloudFire-LLC/cloudfire#628]
Hello again,

I tried to connect my firezone instance with my authentik instance today.
Based on the google example provided in the `firezone.rb`, I added my authentik OIDC provider as follows:

`/etc/firezone/firezone.rb:`
```
default['firezone']['authentication']['oidc'] = {
  MYAUTHENTIK: {
    discovery_document_uri: "https://MYAUTHENTIK.tld/application/o/firezone/.well-known/openid-configuration",
    client_id: "ID",
    client_secret: "Secret",
    redirect_uri: "https://MYFIREZONE/auth/oidc/MYAUTHENTIK/callback",
    response_type: "code",
    scope: "openid email profile",
    label: "MYAUTHENTIK"
  }
}
```
`
/etc/firezone/firezone-running.json`
```
"oidc": {
        "MYAUTHENTIK": {
          "discovery_document_uri": "https://MYAUTHENTIK.tld/application/o/firezone/.well-known/openid-configuration",
          "client_id": "ID",
          "client_secret": "Secret",
          "redirect_uri": "https://MYFIREZONE/auth/oidc/MYAUTHENTIK/callback",
          "response_type": "code",
          "scope": "openid email profile",
          "label": "MYAUTHENTIK"
        }
    },
```

However, with this settings phoenix crashes and fails to start. I get the following in the phoenix logs:
`/var/log/firezone/phoenix/current`
```
2022-05-18_20:02:18.37394 Crash dump is being written to: erl_crash.dump...done
2022-05-18_20:02:19.05169 Firezone detected a service crash loop. Taking service down. For support please email support@firez.one and include a copy of these crash logs.
2022-05-18_20:12:37.34779 warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
2022-05-18_20:12:40.50633 20:12:40.502 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 192.168.151.163:13000 (http)
2022-05-18_20:12:40.50777 20:12:40.507 [info] Access FzHttpWeb.Endpoint at https://MYFIREZONE.tld
2022-05-18_20:12:40.70594 20:12:40.674 [notice] Application fz_http exited: FzHttp.Application.start(:normal, []) returned an error: shutdown: failed to start child: OpenIDConnect.Worker
2022-05-18_20:12:40.70597     ** (EXIT) an exception was raised:
2022-05-18_20:12:40.70597         ** (MatchError) no match of right hand side value: {:error, :update_documents, "certificates bad format"}
2022-05-18_20:12:40.70597             (openid_connect 0.2.2) lib/openid_connect/worker.ex:55: OpenIDConnect.Worker.update_documents/2
2022-05-18_20:12:40.70597             (openid_connect 0.2.2) lib/openid_connect/worker.ex:23: anonymous fn/1 in OpenIDConnect.Worker.init/1
2022-05-18_20:12:40.70598             (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
2022-05-18_20:12:40.70598             (elixir 1.13.4) lib/enum.ex:1496: Enum.into/3
2022-05-18_20:12:40.70598             (openid_connect 0.2.2) lib/openid_connect/worker.ex:22: OpenIDConnect.Worker.init/1
2022-05-18_20:12:40.70598             (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
2022-05-18_20:12:40.70598             (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
2022-05-18_20:12:40.70598             (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

As far as I can tell my settings seem to be correctly formatted, and I am not sure if there are any other useful logs.

**Comment by jamilbk** [comment]
Thanks for the report @onyxkyr 

Could you ensure the top-level key used for your settings matches the path parameter in your `redirect_uri`? E.g.

```ruby
MYAUTHENTIK: {
...
  redirect_uri: "https://MYFIREZONE/auth/oidc/MYAUTHENTIK/callback"
...
}
```

If those match, it looks like the issue could be due to your JWKS keys/certificates? The error you're hitting is coming from here:

https://github.com/DockYard/openid_connect/blob/e8dfd0033bb3420c1af43653406ccd870900032e/lib/openid_connect.ex#L265

This may help troubleshoot:

https://swagger.io/docs/specification/authentication/openid-connect-discovery/

Is your JWKS endpoint setup correctly in Authentik? Are you able to use it as an IdP for another OIDC consumer app successfully?

Let me know if this helps!

**Comment by onyxkyr** [comment]
The top-level key matches, I just forget it in my intial setting censoring.

The settings should be correct, and I am indeed using authentik as IdP for several other OIDC applications.

Does your OIDC client use custom dns and/or ignors `/etc/hosts`?
Would it be possible to add an option to ignor certificate errors for debugging purposes or make them be more verbose?

**Comment by jamilbk** [comment]
@onyxkyr 

Gotcha. Hmm no, elixir/erlang should just be using the standard system resolver.

> Would it be possible to add an option to ignor certificate errors for debugging purposes or make them be more verbose?

We don't actually handle OIDC auth ourselves, we use [DockYard's OpenID Connect library](https://github.com/DockYard/openid_connect), so this might be tricky at the moment.

Let me do a little more testing and see. We may end up switching to something like https://github.com/ueberauth/oauth2 for more flexibility instead.

**Comment by onyxkyr** [comment]
Before making massive changes, there maybe is a flag for more verbose debug?
I will take a look at it again tomorrw, maybe I will find something.

Authentik is behind a proper ssl connection, but it signs the tokens with its own certificate - others apps had no problems with that thus far. That could be the issue, but I don't think I can change that.

**Comment by jamilbk** [comment]
@onyxkyr Thanks for the additional info. I'm sure you won't be the first one using Authentik+Firezone, so I'll spend some time bringing up a test env to look into this further.

**Comment by jamilbk** [comment]
@onyxkyr 

Hmm I'm not able to reproduce. I just spun up a fresh bare Authentik cluster using Docker Compose, added a local test app for my Firezone dev instance, and auth works fine.

Here's my config:

```ruby
  authentik: {
    discovery_document_uri: "http://localhost:9000/application/o/test/.well-known/openid-configuration",
    client_id: "edbfc178b56204b11004c65c01c160a9e875f481",
    client_secret: "SECRET",
    redirect_uri: "http://localhost:4000/auth/oidc/authentik/callback",
    response_type: "code",
    scope: "openid email profile",
    label: "authentik"
  }
```

Here's my Authentik setup:

<img width="1127" alt="Screen Shot 2022-05-18 at 6 08 54 PM" src="https://user-images.githubusercontent.com/167144/169180834-6310ad68-3e67-4945-bdfc-0b50df74da3c.png">

Here's a screencap if it helps:

https://user-images.githubusercontent.com/167144/169180875-c7d14e09-6826-4798-9206-3a5432140904.mov

Perhaps an issue with your cert or Application config on the Authentik side?

**Comment by jamilbk** [comment]
If you could provide the JSON response from your `jwks` endpoint, I think that might give us a clue. You should be able to get a better error message if you try parsing your `jwks` response using `JOSE.JWK.from(cert_json_str)` from the [Elixir JOSE library](https://hexdocs.pm/jose/JOSE.JWK.html#from/1), as that's the part that seems to be failing in your setup.

**Comment by onyxkyr** [comment]
Your config is complete analog to mine; the only difference I see is that my authentik runs on a different host.

However, I just found the culprit: Your OIDC workers wants to communicate with firezone via https.
I had to also direct my firezone domain to the internal ip of my reverse proxy by adding an appropriate entry into `/etc/hosts` on the machine firezone runs on. Thanks!

**Comment by jamilbk** [comment]
@onyxkyr Ahh! Glad you found the issue. I *think* the OIDC worker tries to use the `default['firezone']['external_url']` which is `https` by default, which would explain your issue :-).
