### ISSUE TITLE
Investigate repeated crates for tauri builds

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6288]
One reason the tauri builds are so slow could be that there are lots of duplicated dependencies. I believe we've looked into this before, but opening just in case we haven't. 

Here are a few examples from https://github.com/firezone/firezone/actions/runs/10376708083/job/28730218971?pr=6287

```
  Downloaded base64 v0.22.1
  Downloaded base64 v0.21.7
  Downloaded base64 v0.13.1
```

```
  Downloaded toml v0.8.12
  Downloaded toml v0.5.11
```

```
  Downloaded toml_edit v0.22.9
  Downloaded toml_edit v0.21.1
  Downloaded toml_edit v0.19.15
```

```
  Downloaded nix v0.29.0
  Downloaded nix v0.28.0
  Downloaded nix v0.27.1
  Downloaded nix v0.25.1
```

```
  Downloaded rand_core v0.6.4
  Downloaded rand_core v0.5.1
```

```
  Downloaded memoffset v0.9.1
  Downloaded memoffset v0.7.1
```

```
  Downloaded indexmap v2.2.6
  Downloaded indexmap v1.9.3
```

**Comment by ReactorScram** [comment]
Yeah. We can try to fix those, but profling the build with `--timings` showed that the biggest offender was `windows` itself, which is also the hardest to change. #5913 might make it better, or worse 🤷‍♀️

**Comment by jamilbk** [comment]
Does `--timings` measure the linking step too? I think that's accounting for a large portion of it, but I'm not sure if/how that's affected by multiple dependencies

**Comment by ReactorScram** [comment]
Not sure. But it said it spent almost 3 minutes on `windows@0.39.0`. Unfortunately Tauri depends on both `0.37.0` and `0.39.0`
<img width="411" alt="image" src="https://github.com/user-attachments/assets/c4573270-1dca-4615-8ccf-a1a2bb36e7f5">

I assume Tauri 2.x will bump this dep, but then we'll lose support for Ubuntu 20.04.

We can get rid of 1 or 2 versions of `windows` that Tauri doesn't need, but last time I measured it, strangely, after repeated measurements, it didn't show any more speedup. So I gave up on it.

**Comment by thomaseizinger** [comment]
> We can get rid of 1 or 2 versions of `windows` that Tauri doesn't need, but last time I measured it, strangely, after repeated measurements, it didn't show any more speedup. So I gave up on it.

If it is early enough in the crate graph, it might just be compiled in parallel and thus not present a bottleneck.

**Comment by thomaseizinger** [comment]
> I assume Tauri 2.x will bump this dep, but then we'll lose support for Ubuntu 20.04.

When Flutter?

**Comment by ReactorScram** [comment]
#5788 

![image](https://github.com/user-attachments/assets/b173ee65-59d0-49a1-a5f3-0e8162d92052)
