### ISSUE TITLE
0.3.13 shows up as version 0.0.0 on deb package and admin interface.

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#629]
Perhaps the version number was entered wrong?

**Comment by jamilbk** [comment]
Ah -- we've updated our release script and I think I know what happened. Let me see if I can get a fix out today and cut a `0.3.14` release.

**Comment by dillfrescott** [comment]
Sounds good to me! :)

**Comment by dillfrescott** [comment]
Could you repoen this? I updated to 0.3.14 and it's still showing up as 0.0.0 in the admin interface.

**Comment by jamilbk** [comment]
Welp, back to the drawing board!

Thanks for reporting -- I'll take a closer look in a bit.

**Comment by dillfrescott** [comment]
Please make sure it isn't just a glitch with my installation and is actually happening by default! Could save a lot of work on your end!

**Comment by jamilbk** [comment]
@DillFrescott fixed in 0.3.15 :-)
