### ISSUE TITLE
bug(android): make sure something can reset the favorites

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6293]
I forgot to hook up the "Reset to defaults" button to reset favorites. Should be simple.

**Comment by ReactorScram** [comment]
I'm stuck on trying to move the `MutableLiveData` for the favorites into `Repository`. I'm getting an undefined reference there. Is `Repository` part of a different module that doesn't import the LiveData stuff?

**Comment by thomaseizinger** [comment]
If doing the UI stuff manually is getting too complicated, we may want to look into https://github.com/firezone/firezone/issues/6384.

**Comment by thomaseizinger** [comment]
Possible fix via https://github.com/firezone/firezone/issues/6700.
