### ISSUE TITLE
logFilter isn't applied to firezone-client-ipc

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6302]
I was trying to debug #6290 on Linux in a VM and I couldn't seem to find where the log level is being set for the IPC service.

It might good to improve UX a little bit here:

- [ ] Add "Viewing logs" section to docs -- "Logs are in /var/log/dev.firezone.client" etc
- [ ] Restart client IPC when log filter changes? Related: #5634

**Comment by thomaseizinger** [comment]
I use the headless-client where i can for this kind of debugging. You can set the log filter via an env variable when it starts up.

**Comment by ReactorScram** [comment]
It's set by the GUI, same as on Windows.

We should definitely use that `tracing` reloader in the IPC service though. This might be easier now that the IPC code is cleaned up and the logging code is in `firezone-logging`
