### ISSUE TITLE
Delayed failure on IPC service when run without elevation

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#6305]
The IPC service needs elevated permissions to make a tunnel but this only becomes apparent when the GUI connects. It then fails but doesn't exit.

It may not be a scenario that happens often but I just ran into this while debugging things. I think the IPC service should hard exit on startup if it is not run with elevated permissions.

**Comment by jamilbk** [comment]
I think it might make restarting the IPC tricky, but I'll let @ReactorScram comment here.

**Comment by ReactorScram** [comment]
If that bug in the elevation check gets cleared up I can have the IPC service call it too

On Linux the elevation check is really simple (Just checks for `$USER` to be `root` I believe) and reliable. On Windows it may be crashing.

**Comment by ReactorScram** [comment]
@thomaseizinger This is with `run-debug`, right? For the production IPC service the error handling might be odd, so I'll implement this but it'll never get tested since Windows and systemd will always run them both elevated.

**Comment by thomaseizinger** [comment]
> @thomaseizinger This is with `run-debug`, right? For the production IPC service the error handling might be odd, so I'll implement this but it'll never get tested since Windows and systemd will always run them both elevated.

Yes. I am not sure how critical it is yeah. I just figured we want to fail early here in some code path. At least on Linux, a user could try and move the tunnel to a user-systemd service which doesn't run as root.
