### ISSUE TITLE
refactor(rust): Forbid HashMap / HashSet using Clippy, then wrap them

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6331]
This is an idea that came up when Thomas found that iterating over the hashes was causing non-determinism in the proptests

It will create some boilerplate code but this way we don't have to completely give up on `HashMap`, we can just swap it out when needed

Original comment: https://github.com/firezone/firezone/pull/6319#pullrequestreview-2243069409

**Comment by ReactorScram** [comment]
I gave it a try and I'm not sure if it's worth it

**Comment by thomaseizinger** [comment]
> I gave it a try and I'm not sure if it's worth it

We have tests now that ensure our proptests stay deterministic so at least on that front, we are covered. Non-determinism in other places may not be as problematic.
