### ISSUE TITLE
NDK not found on GitHub runners?

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#6365]
Just run into this CI failure: https://github.com/firezone/firezone/actions/runs/10466164916/job/28982581204?pr=6361#step:7:38

**Comment by thomaseizinger** [comment]
Another instance: https://github.com/firezone/firezone/actions/runs/10465941894/job/28981970438?pr=6362

**Comment by ReactorScram** [comment]
#6369 fixed this. Looks like GitHub just quit supporting our older NDK version, so I updated it in our files
