### ISSUE TITLE
Menu bar on macOS after sign out -> sign in render bug

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6370]
Seeing this intermittent menu bug on macOS that happens when:

- Launching for the first time
- Signing out and then back in

The bug disappears if I open and close the menu a few times.

Possibly it's a race condition? I.e. favorites are not instantiated before menu is created?

<img width="292" alt="Screenshot 2024-08-20 at 8 43 58 AM" src="https://github.com/user-attachments/assets/baeff2f3-f483-49ee-a3c1-137dd68fb36a">

**Comment by jamilbk** [comment]
Ah I should add that it appears to happen when I have at least one favorite.

**Comment by ReactorScram** [comment]
Replicates here even if I sign out and back in multiple times without quitting the app. I'll take a look

**Comment by ReactorScram** [comment]
Even just cycling a Resource between favorite and non-favorite, sometimes it happens when adding it as a Favorite

**Comment by ReactorScram** [comment]
That blank space at the bottom makes me wonder if we're hitting some glitch in `NSMenu` with the way we call it.

**Comment by jamilbk** [comment]
@ReactorScram I'll have time to pair on this before standup (lunch time pacific ish). I would lean towards this being an unacceptable UX because I realized the first thing users typically do after signing in is open the menu to view Resources.

I have some ideas on what it could be. Will ping @conectado in case he wants to join.
