### ISSUE TITLE
Resolve `A` or `AAAA` depending on Gateway's IPv4 and IPv6 connectivity

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6371]
It seems that we might have a NAT64 bug.

- Use the docker.gateway.firez.one Gateway on staging
- Try to `ping6` a DNS resource through it.
- Observe `Source not allowed` with an IPv4 address in the Client

Tested on macOS

```
connlib	08:58:58.405258-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:02.274852-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:02.762666-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:03.258873-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:04.282836-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:06.266691-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:10.235568-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:18.554400-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
connlib	08:59:34.426347-0700	firezone_tunnel::client: Source not allowed: 34.107.221.82 gid=c5b69857-d9d3-46df-9a63-367cab2faff7 local=192.168.1.225:51113 from=45.32.246.195:46227
```

**Comment by jamilbk** [comment]
Marking as high priority since this will affect any Gateway deployment that has only one stack or the other.

**Comment by jamilbk** [comment]
I'll add that the resource I used was `Route all dotcoms` (**.com) and the host I tried to ping6 was `speed.cloudflare.com`.

**Comment by jamilbk** [comment]
Interestingly, that `34.107.221.82` source address is a GCP address but not one of ours. It looks local to where the Gateway is running. I don't think it's related to the failure -- it's perhaps a leftover NAT session from my previous Client sign-in session. 
I'll try to get a better log.

**Comment by jamilbk** [comment]
Actually I think this is expected and there's ~~not much we can do with our current design~~ aside from detecting this and using NAT64 and NAT46 to fix.

Instead the issue seems to be here that from the Client's perspective, `IPv6` is fine and dandy, so applications will happily try to use IPv6 to connect to DNS Resources.

The problem here is when IPv4-only Gateways resolve Resources and receive IPv6 addresses and then try to connect to them. When this happens, we see lots of `Failed to encapsulate: Unsupported ICMPv6 type: 1` in the logs. This will be an issue for DNS Resources that are not in the customer's control, such as public services.

**Comment by jamilbk** [comment]
Options to fix this:

- [ ] Add IPv6 instructions in the Docker deploy steps in the portal deploy page. This won't fix the issue entirely because many times IPv6 won't be available for some Gateways. For example, this is common for Gateways deployed behind AWS NAT Gateways since those support IPv4 only, and our docs example for deploying with Terraform currently uses that (this is the single public egress IP case)
- [ ] Detect if we're missing IPv4 or IPv6 connectivity and only resolve records corresponding to those stacks, then apply our 6-to-4 or 4-to-6 translation to successfully route back to the Client.

Option (2) above seems the only viable one to fix the issue with decent UX.

**Comment by jamilbk** [comment]
What we could do here is detect the quinn::udp `OS error 49` when we fail to send packets to IPv6 or IPv4 relays and mark those sockets as unusable. This would need to be reset when "roaming" (the Gateways interfaces can change too)

**Comment by thomaseizinger** [comment]
> What we could do here is detect the quinn::udp `OS error 49` when we fail to send packets to IPv6 or IPv4 relays and mark those sockets as unusable. This would need to be reset when "roaming" (the Gateways interfaces can change too)

Unfortuantely, that error isn't bubbled up from quinn but logged internally. I'll inquire with the maintainers on their appetite to change that.

Edit: Opened issue here: https://github.com/quinn-rs/quinn/issues/1971.

**Comment by thomaseizinger** [comment]
We should fix this by extending our NAT to be able to handle ICMP error messages and not just echo requests & replies. See https://github.com/firezone/firezone/issues/5614.
