### ISSUE TITLE
`Couldn't find connection by IP dst=100.93.62.139` after signing out from the Client

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6372]
We get these logspam messages as `WARN` after a Client which was connected to a Gateway signs out. Perhaps they can be `DEBUG`?

```
2024-08-20T16:09:51.366515Z  WARN firezone_tunnel::gateway: Couldn't find connection by IP dst=100.93.62.139
2024-08-20T16:09:51.367130Z  WARN firezone_tunnel::gateway: Couldn't find connection by IP dst=100.93.62.139
2024-08-20T16:09:51.942281Z  WARN firezone_tunnel::gateway: Couldn't find connection by IP dst=100.93.62.139
2024-08-20T16:09:52.522290Z  WARN firezone_tunnel::gateway: Couldn't find connection by IP dst=100.93.62.139
2024-08-20T16:09:53.702237Z  WARN firezone_tunnel::gateway: Couldn't find connection by IP dst=100.93.62.139
2024-08-20T16:09:56.032203Z  WARN firezone_tunnel::gateway: Couldn't find connection by IP dst=100.93.62.139
```

**Comment by thomaseizinger** [comment]
Yeah we can downgrade those. There is nothing we can do if a client goes away and it will happen during normal operation too.

**Comment by thomaseizinger** [comment]
@conectado We floated the idea of indexing the connection by public key instead of client ID. That wouldn't prevent this logs specifically but it would avoid the equivalent ones on the client after signing in again.

What do you think of that?

**Comment by conectado** [comment]
> @conectado We floated the idea of indexing the connection by public key instead of client ID. That wouldn't prevent this logs specifically but it would avoid the equivalent ones on the client after signing in again.
> 
> What do you think of that?

that could require some changes to the portal right? because a client when reusing connections have its client id verified by the portal, that way it can add a resource only to peers corresponding to the client.

**Comment by thomaseizinger** [comment]
> > @conectado We floated the idea of indexing the connection by public key instead of client ID. That wouldn't prevent this logs specifically but it would avoid the equivalent ones on the client after signing in again.
> > What do you think of that?
> 
> that could require some changes to the portal right? because a client when reusing connections have its client id verified by the portal, that way it can add a resource only to peers corresponding to the client.

Yes but adding yet another field wouldn't be difficult. We are already loading information from the database there.

**Comment by jamilbk** [comment]
Changing assignees since I think @conectado should be freed up sooner. Not critical bug would be good to knock out some logging bugs / tech debt

**Comment by conectado** [comment]
> @conectado We floated the idea of indexing the connection by public key instead of client ID. That wouldn't prevent this logs specifically but it would avoid the equivalent ones on the client after signing in again.
> 
> What do you think of that?

@thomaseizinger  I was looking at this issue in more depth, what logs would this prevent on the client? This "rogue packets" wouldn't make it to the client except if the IPs overlap in such a small window of time but this is an astronomically small chance.

In case that happens we would see a `debug` log which seems acceptable for something that is so strange that happens.

**Comment by thomaseizinger** [comment]
> > @conectado We floated the idea of indexing the connection by public key instead of client ID. That wouldn't prevent this logs specifically but it would avoid the equivalent ones on the client after signing in again.
> > What do you think of that?
> 
> @thomaseizinger I was looking at this issue in more depth, what logs would this prevent on the client? This "rogue packets" wouldn't make it to the client except if the IPs overlap in such a small window of time but this is an astronomically small chance.
> 
> In case that happens we would see a `debug` log which seems acceptable for something that is so strange that happens.

When a client signs in and out, the public key changes, right? Meaning any new connection on the gateway gets indexed by a different key and thus previous packets from previous connections no longer get routed to the tunnel. At least that is what I assumed is happening here?

**Comment by thomaseizinger** [comment]
Ah, this is on the gateway. Yeah we just need to downgrade the log I think.
