### ISSUE TITLE
bug(ci): installing ripgrep from binary on macos sometimes times out

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6374]
#### Describe the bug

_A clear and concise description of what the bug is._

#### To Reproduce

_Steps to reproduce the behavior._

#### Expected behavior

_A clear and concise description of what you expected to happen._

#### Screenshots / Logs

https://github.com/firezone/firezone/actions/runs/10475062096/job/29010861147#step:5:115

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_
- _Firezone Version (e.g. 1.0.0 or N/A):_
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

_Add any other context about the problem here._

**Comment by ReactorScram** [comment]
Why are we getting "Payment required" from some Vercel thing? Is `cargo-binstall` hosted on a free tier of Vercel or something? https://github.com/firezone/firezone/actions/runs/10476247113/job/29014727431#step:5:83

**Comment by ReactorScram** [comment]
https://github.com/firezone/firezone/actions/runs/10480170392/job/29027314752#step:5:83 Same thing

**Comment by ReactorScram** [comment]
https://github.com/firezone/firezone/actions/runs/10515793134/job/29136624604

**Comment by thomaseizinger** [comment]
I'll deal with this to make sure it doesn't slow down CI.
