### ISSUE TITLE
Generate ICE credentials for gateway in the portal

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#6404]
For ICE to work, each party typically generates a set of ICE credentials and they exchange it with each other. Once both parties have the remote credentials, they can start to test candidates. The credentials are required because that is how the two parties de-multiplex incoming STUN requests.

Currently, our flow is like this:

1. Client sends a connection intent to the portal
2. Portal tells client, which gateway to use for this resource
3. Client checks if it has a connection and sends "reuse connection" if yes, otherwise it creates a new one and sends ICE credentials to the portal
4. Portal then sends the ICE credentials to the gateway
5. Gateway generates local ICE credentials and sends them to the portal
6. Portal sends the gateway's ICE credentials to the client

If the portal would generate the gateway's ICE credentials, we could save a couple of roundtrips here. In particular, In step 3, when the client sends ICE credentials to portal. The portal could generate the ICE credentials for the gateway and send the pair of credentials to it, basically instructing it to use these credentials. In parallel, the portal can already reply to the client with the pair of ICE credentials that it generated for the gateway.

This allows us to reduce the number of network roundtrips between client/gateway and portal from 4 to 2. Given that the portal is currently only hosted in the US, this should give us a decent speed-up for establishing new connections, especially for all sites customers outside the US.

This also has the convenient side-effect that it will make connection setup on the client infallible in regards to the gateway, i.e. we don't have to wait on the gateway to tell us their credentials which may fail.

**Comment by jamilbk** [comment]
This seems like a good idea. Could you link to where ICE creds are generated in the codebase? My guess is it's trivial to replicate in Elixir.

The caveat here being this will require a version-specific codepath.

**Comment by thomaseizinger** [comment]
> This seems like a good idea. Could you link to where ICE creds are generated in the codebase? My guess is it's trivial to replicate in Elixir.

They are just random sequences of alphanumeric characters. Str0m does it for us right now. The username is 4 chars and the password 22.

**Comment by thomaseizinger** [comment]
> The caveat here being this will require a version-specific codepath.

So the cool part here is that the client can't tell the difference. So this will be compatible with every client, we only need a version-specific code path on the gateway to decide whether we send it the ICE credentials or whether we wait for the gateway to reply with them.

**Comment by AndrewDryga** [comment]
@thomaseizinger ICE credentials are sent as part of `client_payload`? If so, we won't save any roundtrips, that message still needs to be delivered to and replied by the gateway. Extracting part of the payload to it own async message will make things worse, not better.

**Comment by thomaseizinger** [comment]
> @thomaseizinger ICE credentials are sent as part of `client_payload`? If so, we won't save any roundtrips, that message still needs to be delivered to and replied by the gateway. Extracting part of the payload to it own async message will make things worse, not better.

I am not sure how `client_payload` works on the backend but that shouldn't matter if you just think in terms of the JSON that gets sent around.

Assuming that we detect based on the gateway version, whether it supports "being told" its ICE credentials, I don't see how this could possibly be worse? The client will receive a response 2 RTTs earlier because the portal can respond to the client at the same time it sends the connection request to the gateway.

**Comment by thomaseizinger** [comment]
The way I am thinking of implementing this is to introduce a new `setup_connection` message that will supersede `request_connection`. Perhaps we can use this change as an opportunity to split off the "allow access" part from this flow:

1. Assuming that we land https://github.com/firezone/firezone/pull/6403, clients will be able to send `setup_connection` in parallel with requesting access.
2. Starting with a certain version, clients can send a new `setup_connection` message that only includes gateway ID, key and ICE credentials (nothing related to resources).
3. Upon receiving a `setup_connection` message, the portal can generate ICE credentials for the gateway, immediately send those to the client and also send a `setup_connection` message to the gateway. That one will include the client's ICE credentials and the ones generate by the portal for the gateway. This message doesn't need a reply from the gateway then, which means connection setup can start right away.
4. In parallel to all of this, the client can then already send "allow access" messages for all the resources it will want to access over this new connection.

**Comment by thomaseizinger** [comment]
Handled as part of #6461.
