### ISSUE TITLE
Increase `TF_API_TOKEN` timeout for TF deploys

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6410]
It seems that we're likely to hit the timeout when deploying, resulting in `Unauthorized` in the middle of a run. Is it easy to increase this?

**Comment by AndrewDryga** [comment]
I don't think it's can be easily fixed, It looks like the token we set in `TF_API_TOKEN` is exchanged with a short-lived one that is never refreshed
