### ISSUE TITLE
Relay healthcheck threshold seems flipped

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6412]
> custom/elixir/domain/relays/online_relays_count/last_value for firezone-prod VM Instance labels {project_id=firezone-prod} is above the threshold of 11.000 with a value of 24.000.

I think we want below the threshold for this alarm?

https://console.cloud.google.com/monitoring/alerting/incidents/0.ngshfq70wi7f?channelType=slack&project=firezone-prod

**Comment by AndrewDryga** [comment]
Good catch, I did not notice typo on that one
