### ISSUE TITLE
Refactor connlib callbacks to diff / emit state when any of `ip, dns_servers, routes` change

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6423]
In connlib, we emit various callbacks when one of the above mentioned network config elements change. Instead, we should emit a generic `on_network_state_change` including our entire state of these.

We should diff the old state with new state and only emit this callback when that state has changed, to avoid tracking this in each platform-side codebase.

**Comment by thomaseizinger** [comment]
Another way of phrasing this is to merge `on_update_routes` into `on_set_interface_config`. We should probably introduce a struct here to make it easier to pass this data around.

**Comment by thomaseizinger** [comment]
https://github.com/firezone/firezone/pull/6427 paves the way for doing this. We now just need to add the routes to that as well.
