### ISSUE TITLE
disable ANSI terminal colors in log files

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6467]
Presently debugging a Windows system with only Notepad to view logs, and this is a net negative

**Comment by jamilbk** [comment]
Users are also viewing these logs, so I think this makes sense. The color coding doesn't seem worth breaking the readability of the logs for anyone not viewing them in a unix terminal. They also make it hard to debug Android logs during development in Android Studio.

**Comment by jamilbk** [comment]
cc @thomaseizinger I think this is an unfortunate tradeoff we need to make since we're finding that users are looking at these too.

**Comment by thomaseizinger** [comment]
Yeah we can disable them in log files and keep them enabled for stderr logs.
