### ISSUE TITLE
bug(client/windows): Enabling the Internet Resource disconnects me from the Internet, if I'm on Wi-Fi

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6513]
#### Describe the bug

When the Internet Resource is enabled on Windows, nothing works

#### To Reproduce

1. Install Firezone Client 1.3.0 on Windows
2. Enable the Internet Resource
3. Try to load any non-Resource like `1.1.1.1` or `example.com`, it times out

Also Windows changes from the Wi-Fi icon to the "No Internet" icon.

Resources will load if you still have a connection from when the Internet Resource was disabled, e.g.

1. Disable Internet Resource
2. Run `curl -4 -s https://ifconfig.net/ip`, it will show the Gateway's IP
3. Enable Internet Resource
4. Run curl again, it will still show the Gateway's IP

If you don't have a recent connection, Resources don't seem to work.

#### Expected behavior

Expect non-Resources to be tunneled through Gateways when the Internet Resource is enabled

#### Screenshots / Logs

Logs in private Slack: https://firezonehq.slack.com/archives/C067DSY7TFX/p1725045527700329?thread_ts=1725039440.607859&cid=C067DSY7TFX

Interesting parts:

```
[2m2024-08-30T19:18:07.223521Z[0m [34mDEBUG[0m [1mon_not_connected_resource[0m[1m{[0m[3mresource[0m[2m=[0mdca3fcc6-b5e0-470a-bc7b-6446cdd03bb3[1m}[0m[2m:[0m [2mfirezone_tunnel::client[0m[2m:[0m Sending connection intent
[2m2024-08-30T19:18:07.744608Z[0m [34mDEBUG[0m [1mon_not_connected_resource[0m[1m{[0m[3mresource[0m[2m=[0m1bf16ce9-058c-48de-8404-621772dd7e39[1m}[0m[2m:[0m [2mfirezone_tunnel::client[0m[2m:[0m Sending connection intent
[2m2024-08-30T19:18:09.227827Z[0m [34mDEBUG[0m [1mon_not_connected_resource[0m[1m{[0m[3mresource[0m[2m=[0mdca3fcc6-b5e0-470a-bc7b-6446cdd03bb3[1m}[0m[2m:[0m [2mfirezone_tunnel::client[0m[2m:[0m Sending connection intent
[2m2024-08-30T19:18:11.517653Z[0m [34mDEBUG[0m [1mon_not_connected_resource[0m[1m{[0m[3mresource[0m[2m=[0mdca3fcc6-b5e0-470a-bc7b-6446cdd03bb3[1m}[0m[2m:[0m [2mfirezone_tunnel::client[0m[2m:[0m Sending connection intent
[2m2024-08-30T19:18:11.571512Z[0m [34mDEBUG[0m [2mphoenix_channel[0m[2m:[0m Reconnecting to portal on transient client error: websocket connection failed: IO error: tls handshake eof [3mbackoff[0m[2m=[0m1.44404054s [3mmax_elapsed_time[0m[2m=[0mSome(2592000s)
[2m2024-08-30T19:18:13.026175Z[0m [34mDEBUG[0m [2mfirezone_bin_shared::windows[0m[2m:[0m Resolved best route outside of tunnel interface [3msrc[0m[2m=[0m192.168.1.12 [3mdst[0m[2m=[0m34.160.64.79
[2m2024-08-30T19:18:13.190863Z[0m [34mDEBUG[0m [1mon_not_connected_resource[0m[1m{[0m[3mresource[0m[2m=[0m1bf16ce9-058c-48de-8404-621772dd7e39[1m}[0m[2m:[0m [2mfirezone_tunnel::client[0m[2m:[0m Sending connection intent
[2m2024-08-30T19:18:13.583648Z[0m [34mDEBUG[0m [1mon_not_connected_resource[0m[1m{[0m[3mresource[0m[2m=[0mdca3fcc6-b5e0-470a-bc7b-6446cdd03bb3[1m}[0m[2m:[0m [2mfirezone_tunnel::client[0m[2m:[0m Sending connection intent
```

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ 1.3.0
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows 11
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Official 1.3.0 release on GitHub

#### Additional context

Replicates easily on bare metal on the Windows dev laptop

**Comment by conectado** [comment]
Did https://github.com/firezone/firezone/pull/6584 fix this?

**Comment by ReactorScram** [comment]
Yeah I remember we tested it on the same laptop. So I'll close this until it happens again
