### ISSUE TITLE
feat(rust/gui-client): Safe mode for exporting logs

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6546]
(Part of the problem with this is, in #6547, `run_controller` was bailing out every time the app started, which would made it impossible to sign out or export logs. So if we fixed it so `run_controller` didn't bail out for errors over in the IPC service, then this specific case would not have been a problem at all)

As a user, I may have this sequence happen:

1. Sign in
2. Firezone saves the token to disk
3. Firezone crashes in the PhoenixChannel / WinTun / Portal / connlib / DNS control code (what I'm saying is, a lot of crash-sensitive stuff runs after we may have already saved the token)
4. Every time I start Firezone it tries to auto-sign-in, and it crashes

I see 4 obvious options:

1. Have some "safe mode" that doesn't auto-sign-in (Hard for users to find)
2. Have some debug app that lets you clear the token (Hard for users to find)
3. Automatically detect when the last instance crashed and don't auto-sign-in
4. Don't save the token to disk until `TunnelReady`, so if we crash the user has to sign in again (somewhat inconvenient but more reliable than number 3)

**Comment by thomaseizinger** [comment]
If we detect that we crash, can we just open a "Send crash report" window? Can we trigger it from the tray menu?

**Comment by ReactorScram** [comment]
Yeah we have that whole crash dump helper process and we could probably do that a variety of ways but I assume it'll be complicated.

If we can integrate Sentry or hand-roll some telemetry, I would love love to just have a "Number of Client crashes" counter divided by "Number of Client launches" counter. Like if that's not private information, just knowing which versions are crashing and not crashing would make me worry less
