### ISSUE TITLE
Updating a site's name does not update it in the client Resource list

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6560]
Maybe this needs to trigger `onUpdateResources`?

**Comment by AndrewDryga** [comment]
We currently do not subscribe for updates in Gateway names, in theory those should trigger `resource_updated` for all connected gateways.

**Comment by jamilbk** [comment]
@AndrewDryga Not the Gateway name, the Site name. So I update a Site in the admin portal, and the Client doesn't receive the `onUpdateResources` with the associated sites that contains the new name.
