### ISSUE TITLE
Device approvals

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6575]
# User story

As a Firezone administrator, I'd like to ensure that no personal or unapproved devices connect to my network. When a user signs in from a new device, I'd like to receive a notification that I need to approve the device before it can access Resources.

**Comment by AndrewDryga** [comment]
Minimal version of this feature will be shipped on next production release and is already tested on our staging. We will impove it as we get more feedback from target auidence.
