### ISSUE TITLE
bug(connlib): Disconnecting / dropping connlib Sessions should be synchronizable somehow

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6576]
Without this, we can have this sequence happen:

1. We start up connlib
2. `make_tun` fails
3. We bail out of the `connect_to_firezone` function and `Drop` the connlib handle
4. Connlib sends us callbacks while it boots up, even though the Client believes connlib failed to start and is `None`
5. Connlib shuts down even though the Client believes there is no connlib session

https://github.com/firezone/firezone/blob/main/rust/headless-client/src/ipc_service.rs#L513-L522

Happened as a part of a customer issue, but I don't think it was the root cause of anything. It just made debugging harder and makes the client state machine inconsistent.

Cross-link to internal Slack: https://firezonehq.slack.com/archives/C05KAA18L1Z/p1725386253843959?thread_ts=1725385573.829999&cid=C05KAA18L1Z

**Comment by thomaseizinger** [comment]
If you drop the `Sender` that sits within `Session`, we _should_ bail out of the event loop immediately because the receiver will return `None`: https://github.com/firezone/firezone/blob/bfccc1b8364db42ec6cd021c79c09a5d8db1b596/rust/connlib/clients/shared/src/eventloop.rs#L66

**Comment by thomaseizinger** [comment]
If we replace the callbacks with another channel, that problems goes away because we can't send into a channel that has its receiver dropped.

**Comment by ReactorScram** [comment]
Maybe it's on the Client side then, since the Client has a ton of `await`s in it.

This could explain it:

1. Client starts connlib
2. Connlib makes some callbacks which pile up in the MPSC channel
3. The Client is busy for about 15 seconds trying to hook up DNS and stuff
4. The Client fails in `make_tun`, so it drops `Session`
5. The Client catches up on messages it missed during those 15 seconds, resulting in a stale "Tunnel ready" from the dropped connlib `Session`

**Comment by thomaseizinger** [comment]
Yeah that could be possible. I _think_ that may also be possible to fix with a separate MPSC channel. We could wrap it and always check before `next` whether the channel is still open and discard piled-up messages.
