### ISSUE TITLE
bug(rust/gui-client/windows): Internet stops working in certain conditions

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6591]
#### Describe the bug

In some conditions, the computer's Internet stops working.

We aren't sure yet if it's NRPT DNS or routes or a third thing. We've only encountered it while working on higher-priority bugs, so we haven't had time to debug and document it fully.

#### To Reproduce

Not sure yet. Seen it a couple different ways:

1. While doing fault injection and pretending `make_tun` bailed out in #6548's branch, I clicked "Sign In" but the Firezone page didn't load. 
2. It happened on Jamil's laptop after he had closed the lid (maybe Windows suspended?)
3. It also happened on my Windows dev laptop when I closed the lid yesterday.

#### Expected behavior

Expect the Internet to work normally when Firezone is not open.

#### Screenshots / Logs

None yet.

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Windows GUI Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Not sure
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ `main`? Some PR branches?
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Local dev builds mostly. Maybe 1.3.0?

#### Additional context

Seen on my Windows dev laptop and Jamil's Windows laptop.

**Comment by jamilbk** [comment]
I think the issue that happened on my laptop was because IPv4 was disabled and github.com has only A records.
