### ISSUE TITLE
Changing an IP to login into web UI 

### ISSUE THREAD

**Issue by elhananjair** [CloudFire-LLC/cloudfire#662]
Hello, there am new here to install firezone.
I have successfully installed firezone on my fedora server 35. Now at the end of the installation, it shows, **Use these credentials to sign in to the web UI at https://\*.\*.\*.\*.**.
Unfortunately am just trying to set up a VPN behind my firewall on some regular PC that is on some VLAN in my network. Currently firezone picked my public IP which doesn't work for me currently because I didn't have done port forwarding on my firewall, I will do that for the production but for now, am using **zerotier** to expose my local network to the public by creating some private network. 

Before I installed firezone, I created some sub-domain and configured a DNS to point it to an IP from **zerotier**, which is my web app hosting PC IP.  

Now what am trying to achieve is, accessing firezone web UI from the web through this IP Address instead of my public IP address which is used for accessing the internet. The main goal here is to access my web app through firezone only. Thank you. 

![image](https://user-images.githubusercontent.com/69236638/171067264-fdf880c9-05a8-48d6-8b73-42d10fca2b87.png)

**Comment by jamilbk** [comment]
Hey @elhananjair -- this should be possible if I'm understanding correctly. You'll want to do the following:

1. Set `default['firezone']['external_url']` to the URL you plan on using for the web portal
2. Make sure the Endpoint is entered correctly on the `/settings/site` page. This is used to populate generated WireGuard configs.

**Comment by elhananjair** [comment]
> Hey @elhananjair -- this should be possible if I'm understanding correctly. You'll want to do the following:
> 

>     1. Set `default['firezone']['external_url']` to the URL you plan on using for the web portal
Thank you so much that's exactly what I wanted now I can log in to web UI. 
>     2. Make sure the Endpoint is entered correctly on the `/settings/site` page. This is used to populate generated WireGuard configs.
Yes, I changed the IP in settings>defaults>endpoint. 

Can I ask how I let firezone communicate with my webserver now? Currently, I am running nextcloud on that pc using apache web server, so how can I access that through firezone? Thank you.

**Comment by jamilbk** [comment]
> Can I ask how I let firezone communicate with my webserver now? Currently, I am running nextcloud on that pc using apache web server, so how can I access that through firezone? Thank you.

Sorry, I'm a bit unclear on what you're asking. You should just be able to access your webserver after connecting to VPN using its local LAN ip. By default Firezone allows all traffic outbound so you shouldn't need to do anything special other than ensure the Firezone instance is on the same network as your webserver.

**Comment by elhananjair** [comment]
> > Can I ask how I let firezone communicate with my webserver now? Currently, I am running nextcloud on that pc using apache web server, so how can I access that through firezone? Thank you.
> 
> Sorry, I'm a bit unclear on what you're asking. You should just be able to access your webserver after connecting to VPN using its local LAN ip. By default Firezone allows all traffic outbound so you shouldn't need to do anything special other than ensure the Firezone instance is on the same network as your webserver.

Thanks, @jamilbk for replying. 
In my case, my webserver (apache) is listening to port 80 and 443, and Firezone listen to that port too, so am getting a problem running the apache server. 
Therefore,

- How does firezone forward such traffics to the web server in order to access nextcloud after connecting to firezone? 
- Secondly, I am trying to use certificates from my domain so that I can import it locally to secure the communication to the webserver, and I read somewhere that firezone needs certificates too, my question here is where should I use the private and public certificates in order to secure the communication? in firezone or in nextcloud config? Thanks again. 

![image](https://user-images.githubusercontent.com/69236638/171415518-8efd2236-5ac5-4884-8acc-df228010b1ae.png)

**Comment by elhananjair** [comment]
> > > Can I ask how I let firezone communicate with my webserver now? Currently, I am running nextcloud on that pc using apache web server, so how can I access that through firezone? Thank you.
> > 
> > 
> > Sorry, I'm a bit unclear on what you're asking. You should just be able to access your webserver after connecting to VPN using its local LAN ip. By default Firezone allows all traffic outbound so you shouldn't need to do anything special other than ensure the Firezone instance is on the same network as your webserver.
> 
> Thanks, @jamilbk for replying. In my case, my webserver (apache) is listening to port 80 and 443, and Firezone listen to that port too, so am getting a problem running the apache server. Therefore,
> 
>     * How does firezone forward such traffics to the web server in order to access nextcloud after connecting to firezone?
> 
>     * Secondly, I am trying to use certificates from my domain so that I can import it locally to secure the communication to the webserver, and I read somewhere that firezone needs certificates too, my question here is where should I use the private and public certificates in order to secure the communication? in firezone or in nextcloud config? Thanks again.
> 
> 
> ![image](https://user-images.githubusercontent.com/69236638/171415518-8efd2236-5ac5-4884-8acc-df228010b1ae.png)

@jamilbk please help me

**Comment by jamilbk** [comment]
@elhananjair Two services can’t both listen on the same port so you’ll either need to change Apache’s listen port or change Firezone’s.

Details for changing this and specifying an SSL cert should be explained in your config file in the Nginx section, or you can reference the setup guide or config file reference in our docs: https://docs.firezone.dev/

Once your device is connected to the tunnel, you should be able to access the nextcloud service on the internal tunnel IP for the Firezone instance which is 10.3.2.1 by default.

**Comment by elhananjair** [comment]
@jamilbk thank you so much for replying.
I have changed firezone's listening port in Nginx section (`default['firezone']['nginx']['non_ssl_port']` and `default['firezone']['nginx']['ssl_port']`)
![image](https://user-images.githubusercontent.com/69236638/171969511-c6141b44-4eb5-4195-aef1-749f9c812766.png)

Now my apache web server is running well. 
After I did that I tried to browse my domain **without connecting to the tunnel** from my laptop, and unfortunately, I could access nextcloud. But that's not what am looking for as you said I want to access nextcloud only when I am connected to the tunnel.
In addition to this, I couldn't access firezone web UI using the new ports I have set.
![image](https://user-images.githubusercontent.com/69236638/171969953-1ff0208f-89a1-4e9d-ada7-b3282331e114.png)


Do I miss something? Sorry for taking your time @jamilbk

**Comment by jamilbk** [comment]
Hmm. Did you reload the configuration with `firezone-ctl reconfigure`? Is your firewall blocking inbound to those ports?

To close off nextcloud from the outside you could either try changing its bind address to 127.0.0.1 and/or adding a firewall rule to block access from non-tunnel IPs

**Comment by elhananjair** [comment]
@jamilbk thank you so much again 😊.
>Hmm. Did you reload the configuration with firezone-ctl reconfigure? Is your firewall blocking inbound to those ports?

Absolutely, I have opened that port now and it's working, the only thing I should do is add a certificate **lets encrypt** generated into firezone configs to remove this error on browser **The certificate is not trusted because it is self-signed.**

> To close off nextcloud from the outside you could either try changing its bind address to 127.0.0.1 and/or adding a firewall rule to block access from non-tunnel IPs

I thought by default everything will be blocked if you are not connected to the tunnel, my bad I am new to VPN configurations and am really sorry. 
what do you mean by this exactly **try changing its bind address to 127.0.0.1** I didn't fully understand and **adding a firewall rule to block access from non-tunnel IPs** - does firezone gives an IP to internal services? Or how do I know non-tunnel IPs?
