### ISSUE TITLE
feat(storage): ability to download relay similar to gateway or clients

### ISSUE THREAD

**Issue by DoctorFTB** [CloudFire-LLC/cloudfire#6651]
#### Is your feature request related to a problem? Please describe.

I have created a repository for a self-host and I would like to provide the ability to download relay through the site as is done with gateway

#### Describe the solution you'd like

The updated version of relay will be sent to a repository similar to gateway or clients.

#### Describe alternatives you've considered

Getting relay from docker-image

#### Additional context

I want to provide a more convenient way to install FireZone via direct download relay, if possible
Right now it doesn't look very nice..
In page: https://www.firezone.dev/changelog

**Comment by thomaseizinger** [comment]
In our production setup, we always deploy the portal and the relays from the same SHA. So you can link to the same relay docker image as for the portal.

See https://github.com/firezone/firezone/pkgs/container/relay.

**Comment by DoctorFTB** [comment]
But if I want to setup relay on another server - I need to download docker, then extract file (for use in systemd service). But for gateway I can download the file directly from FireZone server

**Comment by DoctorFTB** [comment]
Or do you mean installing the relay on the same server as the portal?

**Comment by thomaseizinger** [comment]
> But if I want to setup relay on another server - I need to download docker, then extract file (for use in systemd service). But for gateway I can download the file directly from FireZone server

You can just run the relay within docker, then you don't need to extract it :)

The relay binary is not versioned like the gateway which is why we don't provide separate artifacts. The version running in production is always built from the same Git SHA as the portal.

> Or do you mean installing the relay on the same server as the portal?

You could run on them on the same server, doesn't really matter.

**Comment by thomaseizinger** [comment]
You may also want to consider podman instead of docker. It can create systemd services from docker containers.
