### ISSUE TITLE
Endpoint to get JSON for the latest versions of all client apps

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#6658]
Blocks #6657 #6304 #6303 #5140

**Comment by AndrewDryga** [comment]
@jamilbk we discussed actually doing in the portal since AppStore / GitHub Releases don't need API tokens. Do you mind if we take that approach? Also, what was the place where we was going to fetch the Google Play version from?

If we do it in the portal the plan is:
- Create `Versions` context, add a GenServer per destination to it that will fetch the latest versions every 5 minutes and store in an ETS table (also do one-off fetch when node boots).
- Add an `api.firezone.dev/versions.json` to expose that information.

APIs:
- Mac/iOS: `curl "http://itunes.apple.com/lookup?bundleId=com.yelp.yelpiphone" | jq`
- Gateway, Linux and Windows Clients `curl -H "Accept: application/vnd.github+json" "https://api.github.com/repos/firezone/firezone/releases" | jq`
- Android: ??

**Comment by jamilbk** [comment]
I was thinking we wouldn't even need to fetch from AppStore / Play store. We could just rollout the new versions when we update the changelog. It might lag a bit but won't hurt anything -- we can use our current `mark:next-version` sentinel to handle it.
