### ISSUE TITLE
Popovers break after live navigation

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6682]
After some live navigation events, popovers fail to open again until the next page refresh.

To reproduce:

- View a client
- Verify it
- Notice popovers fail on the page

**Comment by AndrewDryga** [comment]
@jamilbk I can't reproduce this on staging

**Comment by AndrewDryga** [comment]
Disregard, reproduced. The issue is that Flowbite libraries don't really work with DOM pathcing.
