### ISSUE TITLE
All placeholder text should have 'e.g. ...'

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6711]
All form input placeholders as a consistent rule should have `E.g. <example input here>`

**Comment by AndrewDryga** [comment]
I've updated a few but left the ones that do not give examples (eg. "Name your site", while giving an example for site name is worse than current placeholders). Examples in placeholders are not always great: https://ux.stackexchange.com/questions/49191/placeholder-field-label-or-sample-data

**Comment by jamilbk** [comment]
The site name I would say is one place where it does make sense considering it's an abstract entity, like "E.g. AWS VPC 1". The current auto-generated one I think actually doesn't make a ton of sense since folks are changing these anyway, at least from what I can tell on support calls.

**Comment by jamilbk** [comment]
The point of this issue as I recall was to prepend the sample placeholders with `E.g. ` so that the placeholder is not mistaken for a default value.
