### ISSUE TITLE
ci: Github says our Ubuntu ARM image is still deprecated

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6731]
#### To Reproduce

Check any recent CI run

#### Expected behavior

Expected no warnings

#### Screenshots / Logs

> This workflow ran on a hosted runner that uses the "Base Image for Ubuntu Server 22.04". This image will be deprecated in September 2024. Please setup a new runner to use the "Ubuntu 22.04 by Arm Limited" or "Ubuntu 24.04 by Arm Limited" image. This will help reduce workflow run times as there are pre-installed tools. To view the list of installed software on new images, check out https://github.com/actions/partner-runner-images repository.

#### Platform (please complete the following information)

Github

#### Additional context

https://firezonehq.slack.com/archives/C067DSY7TFX/p1726583076261309

**Comment by jamilbk** [comment]
<img width="979" alt="Screenshot 2024-09-18 at 9 02 09 PM" src="https://github.com/user-attachments/assets/1960d1a4-3046-45b9-a8a9-66d40cfda714">
