### ISSUE TITLE
Identity sync rate limit avoidance

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6748]
If a required scope is missing, it could be possible for a directory sync call to fail and be immediately retried, hitting potential sync issues for the IdP in question.

Would need some way to track / limit how many queries / s we are sending to avoid this holistically.

EDIT: Even if the sync doesn't fail, it's still occurring too often for a customer. The Okta rate limits apply org-wide, not connector-wide, so it would be good to slow these down.

**Comment by AndrewDryga** [comment]
For Okta we should start using webhooks: we can subscribe for various changes and use them not as a source of truth but rather as a trigger to run our normal sync. This will allow us to stop fetching everything on a timer and only do it when the data changed.

**Comment by jamilbk** [comment]
@AndrewDryga  refs https://github.com/firezone/firezone/issues/6793

**Comment by bmanifold** [comment]
> For Okta we should start using webhooks: we can subscribe for various changes and use them not as a source of truth but rather as a trigger to run our normal sync. This will allow us to stop fetching everything on a timer and only do it when the data changed.

@AndrewDryga, I like this idea.  I think we'll still need request rate throttling in that scenario, so adding it now will be beneficial, but not running the job on a constant schedule will be good too.
