### ISSUE TITLE
DNS queries for Teams/365 domains get dropped / hang

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6768]
- We know that Teams/365 can sometimes use TCP queries
- We will drop these silently

We can log when this happens when we see TCP queries.

**Comment by conectado** [comment]
We have yet failed to reproduce this issue in our local environment. 

Microsoft do [lay out what domains, ips and ports](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-teams) should be reachable.

Furthermore, [this link](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide#optimizing-connectivity-to-microsoft-365-services) explains that Microsoft 365 services make use of DNS to determine your location and optimize latency. However this wouldn't explain the kind of latency the customer is facing.


This [link](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-split-tunnel?view=o365-worldwide) Microsoft recommends split tunneling for teams but-- that's what the customer is doing, only the DNS queries are going through Firezone.

**Comment by conectado** [comment]
[This](https://connectivity.office.com) tool can be super useful.

The "automatically detect location" test fails, this could already be a problem?

**Comment by jamilbk** [comment]
Latest signs kind of point to it being a TCP DNS issue. Logs:

https://firezonehq.slack.com/archives/C077VKJGQ3W/p1727443520121739

**Comment by thomaseizinger** [comment]
Should we optimistically close this now that #6944 is merged?
