### ISSUE TITLE
Edgerouter MIPS support

### ISSUE THREAD

**Issue by thotha** [CloudFire-LLC/cloudfire#677]
Is there somewhere a possibility to port Firezone to Edgerouter ER-12 on MIPS CPU or a description to do that?

**Comment by jamilbk** [comment]
Hmm, thanks for the request. This is currently not really possible since we'd need to build Firezone on the same host, but we have some improvements underway to cross-compile Firezone which could potentially make this feasible.

**Comment by jamilbk** [comment]
Quick update: All hope is not lost! This should be feasible in the not too distant future as we re-architect to support multisite configurations. 

cc @conectado

**Comment by jamilbk** [comment]
We probably won't be able to support this any time soon. Closing for now.
