### ISSUE TITLE
Existing WireGuard config import

### ISSUE THREAD

**Issue by thotha** [CloudFire-LLC/cloudfire#678]
Is there a way to install/build the web gui management part without reinstalling wireguard again?
This could be a easier way to use Firezone on architectures not supported yet like Edgerouter, Unifi Dream Machine, ...

**Comment by jamilbk** [comment]
Hmm, could you clarify what you mean by `without reinstalling wireguard again`? Do you mean like importing existing WireGuard config?

**Comment by thotha** [comment]
This is a simple YES

**Comment by jamilbk** [comment]
This should be more feasible now with @akrousset 's `wireguardex` integration into `fz_vpn`.

**Comment by jamilbk** [comment]
Refs firezone/product#111

**Comment by jbtule** [comment]
I'd like to be able  to import `ip, presharedkey, and public key` per `user`. I'm wanting to replace an algo wireguard setup and I don't want to change the configs on the client side machines to simplify the switch. 

Would be interested in an interface to add a custom device from the admin account per user, or a csv import for user and devices, or even a rest API that would let me do it.

**Comment by jbtule** [comment]
Just referencing here, that I was able to use this device creation pre-api hack (https://github.com/firezone/firezone/issues/903#issuecomment-1268799690) as the basis for making a shell script to importing devices from algo into firezone, and successfully did an in place replacement of the vpn server.

**Comment by heywoodlh** [comment]
@jbtule can you share the script as a point of reference?

**Comment by jbtule** [comment]
@heywoodlh  yeah, would only work for reference, so algo stores it's keys in `.pki` folder to use to regenerate a wg0.conf by name, and by convention we had been naming them with email address in algo, so it was the easiest way or me to get all the variables need to add a device. I already had a table with everyone's email and IP address  already. For convenience sake I added the firezone user id into that table (which is a number that firezone increments in order when you add users).

I used some csharp code to write out my batch shell script.

```csharp
foreach (var ee in Employees.Where(it => it.VPN_IP != null).Select(it => new { it.EMAIL, it.VPN_IP, it.TEMP_FIREZONE_ID, it.USERNAME}))
{
	var path = $@"C:\temp\vpn-temp\.pki";
	var pubPath = Path.Combine(path, "public", ee.EMAIL);
	var prePath = Path.Combine(path, "preshared", ee.EMAIL);
	if(File.Exists(pubPath) && File.Exists(prePath)){
		var publicKey = File.ReadAllText(pubPath);
		var preSharedKey = File.ReadAllText(prePath);
		Console.WriteLine($"/opt/firezone/embedded/service/firezone/bin/firezone rpc 'IO.inspect(FzHttp.Devices.create_device(%{{user_id: \"{ee.TEMP_FIREZONE_ID}\", name: \"imported-{ee.USERNAME}\", description: \"algo imported for {ee.EMAIL}\", ipv4: \"{ee.VPN_IP}\", preshared_key: \"{preSharedKey}\", public_key: \"{publicKey}\" }}))'");
	}
}
```

**Comment by AndrewDryga** [comment]
@jbtule sorry for such a long response, this should be possible now to do over API, see https://docs.firezone.dev/reference/rest-api/devices/#post-v0devices

**Comment by AndrewDryga** [comment]
As for regular configuration import I don't think we will be adding this directly as we are building our own client apps to abstract that part away, it will be way more convenient for our users to use them rather than default wg clients and manage config file rotations manually.

Please tell if you have any additional questions and I will reopen the issue.
