### ISSUE TITLE
Suggestion for securing access/double access with same peer

### ISSUE THREAD

**Issue by thotha** [CloudFire-LLC/cloudfire#679]
A suggestion from a non developer and ordinary enduser. 
Right now there is no functionality existing to overcome to problem of multiple access with the same peer credentials which ends up in brocken connections. 

Why not try to implement this:
- First setup as usual
- Then both sides create new key pairs
- Both sides exchange this new keys as required and change the preconfigured keys
- and/or the required sides of the tunnel create a additional identification key and exchange them for identification. This way multiple access with the same peer is secured.

**Comment by jamilbk** [comment]
Hi @thotha! While I certainly appreciate your suggestion, this would require core changes to the WireGuard kernel module and isn't feasible for us to implement any time soon. This will get smoother when have client apps later down the road, but for now I'm going to close this. Device configurations should be considered *private* and stay local to the respective devices they were created for.

Sharing a single configuration among devices is not advised and will (as you noted) result in unexpected behavior.
