### ISSUE TITLE
Add Azure AD OAuth provider

### ISSUE THREAD

**Issue by TristonFelix** [CloudFire-LLC/cloudfire#680]
Hi there 
would it be possible to add Azure as a sso authentication method?

Thanks!

**Comment by jamilbk** [comment]
Hi @TristonFelix! Azure supports OIDC, so you can actually do this today. We have more docs in the works for showing how to set this up: https://github.com/firezone/firezone/pull/615

This will be made more clear as part of the 0.4.0 release. But you should be able to use this today with the `0.3.17` release.
