### ISSUE TITLE
Issue with windows when changing connection

### ISSUE THREAD

**Issue by Intuinewin** [CloudFire-LLC/cloudfire#6802]
#### Describe the bug

We have an issue with our laptops, it seems firezone is choosing the wrong route to contact its api: `Resolved best route outside of tunnel interface`

#### To Reproduce

Not sure if you can reproduce it, but here is what we do:

- Connect to firezone through Ethernet (it works)
- Signout
- Unplug ethernet and enable Wifi
- Try to connect (the connection is successful but the connection to the API fails)

Watch the log and see firezone trying to reach its api through the disconnected network interface

#### Expected behavior

It should connect to the API through the wifi card.

After some research it seems you list interfaces but do not exclude interfaces that are down: https://github.com/firezone/firezone/blob/081c4471136b5104dc79cda8e64a3f51c9ed37fa/rust/bin-shared/src/windows.rs#L217
which is causing some traffic to go to the wrong interface

I tried to patch this and it seems to work but I let you reproduce and test this behavior.

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Latest
- _Firezone Version (e.g. 1.0.0 or N/A):_ Selfhosted
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

_Add any other context about the problem here._

**Comment by ReactorScram** [comment]
I followed the replication steps and actually got an OCSP error when trying to sign in on step 4.

![image](https://github.com/user-attachments/assets/436b2aff-8f20-4abf-8057-0c846f19d59d)

Even if I try to just load app.firez.one without the sign-in URL, I get that. After a few minutes of typing up this comment on the same laptop (So github.com works, but app.firez.one wasn't working), the can now load.

@conectado Doesn't this sound related to the Internet resource fix that was implemented during the offsite?

@Intuinewin I could use some clarity on this part:

> Try to connect (the connection is successful but the connection to the API fails)

You mean the web browser says "You are signed in, you can close this tab", but Firezone never connects, right? And this is the Windows GUI Client 1.3.4, right?

**Comment by Intuinewin** [comment]
Yep all of this is with 1.3.4.

> You mean the web browser says "You are signed in, you can close this tab", but Firezone never connects, right?

Yes

I don't think its related to internet resources.
Maybe I'm not clear but imagine this is my network config:

Ethernet:
 -  Device IP: 10.1.1.10
  - Network: 10.1.1.0/24

Wifi:
  - Device IP: 192.168.1.10
  - Network: 192.168.1.0/24

After I disconnect the ethernet and try to log in, the ipc service prints in its log that the best route is 10.1.1.1 which is totally absurd because the interface is down.

**Comment by thomaseizinger** [comment]
> I don't think its related to internet resources.

We had to do some nasty shenanigans on Windows to get Internet Resources to work :clown_face: 

See https://github.com/firezone/firezone/pull/6032 and https://github.com/firezone/firezone/pull/6584.

> After I disconnect the ethernet and try to log in, the ipc service prints in its log that the best route is 10.1.1.1 which is totally absurd because the interface is down.

When this happens, can you open a new powershell and run `Get-NetRoute` and post the output here? I am wondering whether Windows' routing table is just flat-out wrong or whether there is a bug in what we read from it.

**Comment by Intuinewin** [comment]
Oh ok didn't know.

So,
here is the log
```
2024-09-25T07:44:36.024505Z DEBUG firezone_bin_shared::windows: Resolved best route outside of tunnel interface src=10.14.18.31 dst=<REDACTED_FIREZONE_API_IP>
```

10.14.18.31 is my ethernet ip which is deconnected, my wifi ip is `192.168.90.206`

and here is the log ok the error (sorry its in french: host unreachable):
```
2024-09-25T07:44:36.024979Z DEBUG phoenix_channel: Reconnecting to portal on transient client error: failed to connect socket: Une opération a été tentée sur un hôte impossible à atteindre. (os error 10065) backoff=5.093702174s max_elapsed_time=Some(2592000s)
```

Here is the route table when the bug is occuring
```
ifIndex DestinationPrefix                              NextHop                                  RouteMetric ifMetric PolicyStore
------- -----------------                              -------                                  ----------- -------- -----------
59      255.255.255.255/32                             0.0.0.0                                          256 5        ActiveStore
24      255.255.255.255/32                             0.0.0.0                                          256 25       ActiveStore
3       255.255.255.255/32                             0.0.0.0                                          256 25       ActiveStore
2       255.255.255.255/32                             0.0.0.0                                          256 45       ActiveStore
5       255.255.255.255/32                             0.0.0.0                                          256 5        ActiveStore
22      255.255.255.255/32                             0.0.0.0                                          256 25       ActiveStore
17      255.255.255.255/32                             0.0.0.0                                          256 25       ActiveStore
1       255.255.255.255/32                             0.0.0.0                                          256 75       ActiveStore
59      224.0.0.0/4                                    0.0.0.0                                          256 5        ActiveStore
24      224.0.0.0/4                                    0.0.0.0                                          256 25       ActiveStore
3       224.0.0.0/4                                    0.0.0.0                                          256 25       ActiveStore
2       224.0.0.0/4                                    0.0.0.0                                          256 45       ActiveStore
5       224.0.0.0/4                                    0.0.0.0                                          256 5        ActiveStore
22      224.0.0.0/4                                    0.0.0.0                                          256 25       ActiveStore
17      224.0.0.0/4                                    0.0.0.0                                          256 25       ActiveStore
1       224.0.0.0/4                                    0.0.0.0                                          256 75       ActiveStore
2       192.168.90.255/32                              0.0.0.0                                          256 45       ActiveStore
2       192.168.90.206/32                              0.0.0.0                                          256 45       ActiveStore
2       192.168.90.0/24                                0.0.0.0                                          256 45       ActiveStore
59      169.254.255.255/32                             0.0.0.0                                          256 5        ActiveStore
59      169.254.29.102/32                              0.0.0.0                                          256 5        ActiveStore
59      169.254.0.0/16                                 0.0.0.0                                          256 5        ActiveStore
1       127.255.255.255/32                             0.0.0.0                                          256 75       ActiveStore
1       127.0.0.1/32                                   0.0.0.0                                          256 75       ActiveStore
1       127.0.0.0/8                                    0.0.0.0                                          256 75       ActiveStore
5       10.14.18.255/32                                0.0.0.0                                          256 5        ActiveStore
5       10.14.18.31/32                                 0.0.0.0                                          256 5        ActiveStore
5       10.14.18.0/24                                  0.0.0.0                                          256 5        ActiveStore
2       0.0.0.0/0                                      192.168.90.97                                      0 45       ActiveStore
5       0.0.0.0/0                                      10.14.18.254                                       0 5        ActiveStore
1       ff00::/8                                       ::                                               256 75       ActiveStore
1       ::1/128                                        ::                                               256 75       ActiveStore
```

From what I see in the source code, its seems logic for firezone to choose the ethernet default route `10.14.18.254` as its metric is lower but it shouldn't happen as the interface is down.

Here is a part of the route table when wifi disconnected and ethernet connected:
```
2       0.0.0.0/0                                      192.168.90.97                                      0 45       ActiveStore
5       0.0.0.0/0                                      10.14.18.254                                       0 25       ActiveStore
```

**Comment by thomaseizinger** [comment]
> From what I see in the source code, its seems logic for firezone to choose the ethernet default route `10.14.18.254` as its metric is lower but it shouldn't happen as the interface is down.

Yep, we basically pick the "best" one that exists as if Firezone would not be active.

When you say the interface is "down", what does that mean? Is it simply unroutable or does it also no longer have an IP? What is the output of `ipconfig /all`?

Maybe we need to additionally filter for some flag whether the interface is actually up?

**Comment by thomaseizinger** [comment]
Could you test if https://github.com/firezone/firezone/pull/6810 fixes the issue? Once [this job](https://github.com/firezone/firezone/actions/runs/11029014814/job/30630522787?pr=6810) is finished, you should be able to download a built client.

**Comment by thomaseizinger** [comment]
> I tried to patch this and it seems to work but I let you reproduce and test this behavior.

I only just read this. Curious to see what solution you came up with! :)

**Comment by Intuinewin** [comment]
basically the same solution as #6810 except I remove interfaces that are in IfOperStatusDown or IfOperStatusNotPresent or IfOperStatusLowerLayerDown.
But I think your PR will also work

When I type ipconfig, the interface doesn't have an ip associated with it, its weird that windows keeps it in its routing table

**Comment by thomaseizinger** [comment]
Awesome! Could you try it to confirm? I'll get that one ready for merging then.
