### ISSUE TITLE
[Bug] Cannot set nil to default DNS server

### ISSUE THREAD

**Issue by gnavarroco** [CloudFire-LLC/cloudfire#681]
Hi,

When i set the DNS by default "nil", firezone web interface becomes unresponsive
![Screenshot from 2022-06-06 13-52-20](https://user-images.githubusercontent.com/18214996/172220306-519d47f7-5707-4ab3-9003-aec79878be42.png)

**Comment by jamilbk** [comment]
Thanks for the report @gnavarroco -- we just merged a fix for this: https://github.com/firezone/firezone/pull/675

Let me see if we can cut a release.

**Comment by gnavarroco** [comment]
oht thanks!
