### ISSUE TITLE
Update App Store and Play Store listings to mention log collection

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6816]

**Comment by thomaseizinger** [comment]
Do we have to write something for this or is it just a matter of ticking a box somewhere?

**Comment by jamilbk** [comment]
> Do we have to write something for this or is it just a matter of ticking a box somewhere?

Let's go through it together after Standup today if folks have time.

**Comment by thomaseizinger** [comment]
Completed together after standup!
