### ISSUE TITLE
Resolve overlapping firewall allow/deny rules

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#683]
When rules overlap, it's currently not clear which rule should take preference (allow/deny).

- [ ] Add a `priority` field on rules
- [ ] When rules are added / evaluated, resolve all rules in order of `priority` to apply to the nftable.
Refs #https://discourse.firez.one/t/egress-rules-not-working-as-expected-when-deny-0-0-0-0-0/88/2

**Comment by jamilbk** [comment]
refs #423 
refs firezone/product#392

**Comment by icekom** [comment]
As of version 0.4.5 the order of egress rules is not only ambiguous, but also might change after a restart. I'd argue it should be classified as a bug.

My guess is that the most used configuration is to block access to 0.0.0.0/0 and only allow certain internal IP ranges. Perhaps there should be an option to change forward chain policy to "drop".

**Comment by jamilbk** [comment]
> As of version 0.4.5 the order of egress rules is not only ambiguous, but also might change after a restart. I'd argue it should be classified as a bug.

Thanks for the feedback; we have many improvements planned for the firewall backend, starting with user-scoped named sets in 0.5.0 that @conectado has been working on.

We have some ideas how we'd implement the priority system, but open to hear suggestions from our users if you have any :-). 


> 
> 
> 
> My guess is that the most used configuration is to block access to 0.0.0.0/0 and only allow certain internal IP ranges. Perhaps there should be an option to change forward chain policy to "drop".

This is true for more technical users. What may be the best approach here is to change the forward policy to `drop` but add a default allow rule to permit `0.0.0.0/0, ::/0`.

**Comment by jamilbk** [comment]
@icecom-dg This should be solved with #804 -- it shouldn't be possible to create overlapping rules anymore. Feel free to reopen in case the issue persists.
