### ISSUE TITLE
Use hardware ID for device verification 

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#6837]
Make a best effort to try to read the hardware Unique ID for all platforms to send to the portal before falling back to the stored device ID.

Furthermore, we will not hash this id before sending it to the portal so it's easier for customers to match between the ID seen in the portal and the one on the client.

Also, update the docs to match the new behavior.

**Comment by conectado** [comment]
We used [smbios](https://crates.io/crates/smbios-lib) before to obtain this for all platforms.

**Comment by jamilbk** [comment]
Also, this should match what's shown in the OS "About device" dialogs -- i.e. should match what MDMs and XDRs are likely to read.

**Comment by jamilbk** [comment]
On iOS and Android we may want to look into Enterprise methods of reading hardware IDs.

smbios isn't a reliable cross-platform way to retrieve it, should use manufacturer-provided ways to retrieve a consistent hardware ID.

**Comment by jamilbk** [comment]
@conectado Ok I think we have another solution for mobile. What we should do is push a cert down to the device via MDM, and then verify/use that cert when connecting the portal upon which we can identity the device.

So let's keep the file-based method for Android/iOS for now and hardware ID for desktop.

**Comment by conectado** [comment]
After a call we decided to go with these methods:


| OS  | Method |
| ------------- | ------------- |
| MacOs  | Hardware Id  |
| iOS  | identifierForVendor  |
| Android | Firebase Installation ID |
| Windows | Motherboard Serial through SMBIOS |
| Linux | Motehrboard Serial through SMBIOS |

**Comment by jamilbk** [comment]
@conectado thanks for adding that, we'll just need a minor change to the portal to expose the `external_id` in the client details (show) view.

**Comment by conectado** [comment]
For Windows/Linux smbios availability is not consistent. And other problems could be presented for the other device ids detailed in [here](https://github.com/firezone/firezone/issues/6837#issuecomment-2380060677)

Since the device Id is used for upsert this is the method we decided to go with:

* `device_id` is still generated on clients and stored in a file used for upsert
* We send as additional query params, the following fields if available, maybe more in the future:

| OS  | Method |
| ------------- | ------------- |
| MacOs  | Hardware Id  |
| iOS  | identifierForVendor  |
| Android | Firebase Installation ID |
| Windows | Motherboard Serial through SMBIOS |
| Linux | Motehrboard Serial through SMBIOS |

* These are displayed for the administrator
* The administrator can verify the device
* When the device is verified those fields are stored by the portal
* Then at the point of policy evaulation the portal check these fields to ensure the device is verified

**Comment by jamilbk** [comment]
Let's try to get the MacOS device serial if we can, so that we have `device_uuid`, and `device_serial` for all desktop platforms

**Comment by thomaseizinger** [comment]
> We send as additional query params, the following fields if available, maybe more in the future:

Should we make it part of the user-agent instead? I am a bit concerned that we are passing a lot of variables through many layers. We could change that by just allowing the apps to pass the user-agent down as a single value?

**Comment by jamilbk** [comment]
> > We send as additional query params, the following fields if available, maybe more in the future:
> 
> Should we make it part of the user-agent instead? I am a bit concerned that we are passing a lot of variables through many layers. We could change that by just allowing the apps to pass the user-agent down as a single value?

It's a tradeoff though right? We'd be eating into the HTTP header size limit and then would need parsing logic in the portal to split this up.

**Comment by thomaseizinger** [comment]
> > > We send as additional query params, the following fields if available, maybe more in the future:
> > 
> > 
> > Should we make it part of the user-agent instead? I am a bit concerned that we are passing a lot of variables through many layers. We could change that by just allowing the apps to pass the user-agent down as a single value?
> 
> It's a tradeoff though right? We'd be eating into the HTTP header size limit and then would need parsing logic in the portal to split this up.

The limits are typically at least 4K, right? We should be far off from that. Headers also have a structured format, similar to query params, see https://www.rfc-editor.org/rfc/rfc8941.html. So it shouldn't be necessary to write a parser ourselves.

**Comment by thomaseizinger** [comment]
Outside of that, it seems semantically more correct to include this information in the User-Agent header because it defines the agent itself, similar to the version etc.

**Comment by jamilbk** [comment]
> > > > We send as additional query params, the following fields if available, maybe more in the future:
> > > 
> > > 
> > > Should we make it part of the user-agent instead? I am a bit concerned that we are passing a lot of variables through many layers. We could change that by just allowing the apps to pass the user-agent down as a single value?
> > 
> > 
> > It's a tradeoff though right? We'd be eating into the HTTP header size limit and then would need parsing logic in the portal to split this up.
> 
> The limits are typically at least 4K, right? We should be far off from that. Headers also have a structured format, similar to query params, see https://www.rfc-editor.org/rfc/rfc8941.html. So it shouldn't be necessary to write a parser ourselves.

We've hit this limit before. The session cookie is transmitted in the header. Our current design stores less in the cookie now, but we're still tight on space in the HTTP headers AFAIK. @AndrewDryga might be able to elaborate.

https://github.com/firezone/firezone/issues/1266
https://github.com/firezone/firezone/issues/1621

**Comment by thomaseizinger** [comment]
> > > > > We send as additional query params, the following fields if available, maybe more in the future:
> > > > 
> > > > 
> > > > Should we make it part of the user-agent instead? I am a bit concerned that we are passing a lot of variables through many layers. We could change that by just allowing the apps to pass the user-agent down as a single value?
> > > 
> > > 
> > > It's a tradeoff though right? We'd be eating into the HTTP header size limit and then would need parsing logic in the portal to split this up.
> > 
> > 
> > The limits are typically at least 4K, right? We should be far off from that. Headers also have a structured format, similar to query params, see [rfc-editor.org/rfc/rfc8941.html](https://www.rfc-editor.org/rfc/rfc8941.html). So it shouldn't be necessary to write a parser ourselves.
> 
> We've hit this limit before. The session cookie is transmitted in the header. Our current design stores less in the cookie now, but we're still tight on space in the HTTP headers AFAIK. @AndrewDryga might be able to elaborate.
> 
> #1266 #1621

Oh, the limit is across all HTTP headers? I thought it is per header. Our current `User-Agent` is ~40 chars long.

Can we go the opposite way then and encode everything in the query parameters? It seems unnecessary to spread this information out over multiple places.

**Comment by thomaseizinger** [comment]
Also, from HTTP2 onwards, the path gets encoded as a special header field so it might not matter for this limit, where we put the information, depending on when this limit gets enforced. To prevent DoS attacks, I'd suspect that it gets enforced before parsing them, so it wouldn't be able to special-case `path` or any of the other pseudo headers.

See https://datatracker.ietf.org/doc/html/rfc9113#name-request-pseudo-header-field.

**Comment by AndrewDryga** [comment]
It doesn't really matter if we put it into an `User-Agent` or as a separate param when connecting to a socket. 

- `User-Agent` is semantically more correct, but it requires encoding/parsing the string all the time, which can lead to errors. It's also less convenient as we grow amount of data we send from the clients (later we will send some MDM IDs and might send other stuff about the device too);
- `params` are easier to use and less error-prone.

Whatever option we go with - we should stick with it. If we pick `params` maybe we should not make User-Agent required anymore and only send structured data in params? (I'm personally in favor of this.)

> We've hit this limit before. The session cookie is transmitted in the header. Our current design stores less in the cookie now, but we're still tight on space in the HTTP headers AFAIK. @AndrewDryga might be able to elaborate.

This won't be an issue for WS APIs. No cookies are sent to those endpoints (Rust makes requests, not the browser) so the entire 4kb limit is up for our usage.

**Comment by thomaseizinger** [comment]
> It doesn't really matter if we put it into an `User-Agent` or as a separate param when connecting to a socket.
> 
>     * `User-Agent` is semantically more correct, but it requires encoding/parsing the string all the time, which can lead to errors. It's also less convenient as we grow amount of data we send from the clients (later we will send some MDM IDs and might send other stuff about the device too);
> 
>     * `params` are easier to use and less error-prone.
> 
> 
> Whatever option we go with - we should stick with it. If we pick `params` maybe we should not make User-Agent required anymore and only send structured data in params? (I'm personally in favor of this.)

A third option would be to use more (custom) headers. That would allow for some more separation / grouping of data. I imagine we might need _some_ structure in the future for certain fields? For example, we could group the relay IPs together:

```
FZ-Public-IPs: ipv4=.....; ipv6=.....;
```

I do agree that we should settle on one way of encoding this data.

**Comment by jamilbk** [comment]
I might advise against custom headers. Many WAFs strip these off. Same with weird user agents. If we want to reduce the likelihood of a secure web gateway or web app firewall / proxy molesting our headers might want to keep them as URI params, just a thought.

**Comment by thomaseizinger** [comment]
> I might advise against custom headers. Many WAFs strip these off. Same with weird user agents. If we want to reduce the likelihood of a secure web gateway or web app firewall / proxy molesting our headers might want to keep them as URI params, just a thought.

Good point! Let's cram it all into the query params then :D
