### ISSUE TITLE
Timezone? 

### ISSUE THREAD

**Issue by bcookatpcsd** [CloudFire-LLC/cloudfire#684]
I cannot find in the documentation.. but it looks as if all time it UTC.

/etc/localtime is set correctly on the physical server.. I even set TZ in the run files of the runit processes.. still shows as UTC

Option to configure? 

https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by jamilbk** [comment]
Hey @bcookatpcsd — thanks for opening the issue. Could you clarify where you’re seeing the UTC times? We should be localizing in the web portal via your browser’s TZ.

**Comment by jamilbk** [comment]
Or would this be for the log files?

**Comment by jamilbk** [comment]
Going to close for now to try and keep the backlog groomed -- feel free to request re-opening if this is still a question!
