### ISSUE TITLE
User limit or device limit?

### ISSUE THREAD

**Issue by bcookatpcsd** [CloudFire-LLC/cloudfire#685]
OAuth working great.. what if I don't want a domain user to have an account? 

Is there a group or role that I can assign to control registration?
(this may already exist, but I could not find it..)

Is there a way to get an administrative registration email when an account is created? 
(this does not seem to exist, but would seem useful..)

Is there a way to get an email if you wanted to know when/if a user successfully/unsuccessfully connects? 
(also useful for instant accounting, wanting to confirm for variety of reasons..) 

Device limitation possibility? 

Group1 == 1 device
Group2 == 2 devices

Thank you for listening..

**Comment by jamilbk** [comment]
@bcookatpcsd Answers inline :-)

> OAuth working great.. what if I don't want a domain user to have an account?

Working on that in #515 

> 
> Is there a group or role that I can assign to control registration? (this may already exist, but I could not find it..)

We don't have roles beyond the `unprivileged` and `admin` yet -- as a workaround, could you do this on the OIDC side?
> 
> Is there a way to get an administrative registration email when an account is created? (this does not seem to exist, but would seem useful..)

Hm could you clarify this one? Like a notification to admins?

> Is there a way to get an email if you wanted to know when/if a user successfully/unsuccessfully connects? (also useful for instant accounting, wanting to confirm for variety of reasons..)

Similar to a notification like above?

> 
> Device limitation possibility?
> 
> Group1 == 1 device Group2 == 2 devices

Currently you can set `default['firezone']['max_devices_per_user']` but this option is not role-aware.

> 
> Thank you for listening..

Thanks for the feedback!

**Comment by jamilbk** [comment]
@bcookatpcsd #515 has been released which allows you to control whether users are auto-created from OIDC logins. If you disable that, you can control which users have access by first creating their user account with an empty password so they exist in the system.

**Comment by jamilbk** [comment]
Going to close this for now. Can create individual issues for the questions above not covered in the latest release.
