### ISSUE TITLE
feat(rust/client): automatically upload debug symbols to sentry.io from CI/CD

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6856]
1. Use pnpm to install `sentry-cli`
2. Log in to Sentry with organization auth token from https://firezone-inc.sentry.io/settings/auth-tokens/, sent through Github secrets manager (`SENTRY_TOKEN`)
3. Upload pdb on Windows and dwp on Linux using e.g. `node_modules/.bin/sentry-cli debug-files upload -o firezone-inc -p rust-gui-client-gui target/release/firezone_gui_client.pdb`

**Comment by ReactorScram** [comment]
Could have really used it for this one https://firezone-inc.sentry.io/issues/5961660696/?project=4508008945549312

**Comment by thomaseizinger** [comment]
Done in #7331.
