### ISSUE TITLE
bug(rust/gui-client/windows): delay when quitting related to Sentry

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6873]
#### Describe the bug

The application takes 12 seconds to exit when clicking "Quit" in the menu.

It seems to only happen if Firezone is signed in, and if we're on Windows. Windows is known to be a little slower for tunnel start / stop than Linux.

Hypotheses:

- Inherent to Sentry? - No, it only replicates when Firezone is signed in
- Related to Windows? - Possibly, haven't seen it replicate on Linux
- Sentry is just slow in debug builds - No, happens in release build, and doesn't happen in Linux debug builds
- Related to GUI / tunnel daemon process split? - Maybe. Doesn't seem to happen in Headless Client.
- Related to DNS? - Likely.
- Related to Internet Resource? - Unlikely, replicates even if the Internet Resource is disabled.

#### To Reproduce

1. Start the tunnel daemon (IPC service)
2. Start the GUI
3. Let it sign in
4. Click "Quit" in the menu
5. There's a 5-second delay while trying to flush telemetry
6. There's an extra delay before exiting

#### Expected behavior

Expect the app to quit instantly if there are no errors to send

#### Screenshots / Logs

Windows (bad):

<img width="741" alt="image" src="https://github.com/user-attachments/assets/dd340c4c-2023-48a2-a26f-ec6ad9e04181">

Linux (good):

<img width="726" alt="image" src="https://github.com/user-attachments/assets/c097db72-0aa2-4948-8333-3a105c9c828e">

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ GUI Client GUI process
- _Firezone Version (e.g. 1.0.0 or N/A):_ d2a8155ba (tip of `main`)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Windows
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Built from source

**Comment by thomaseizinger** [comment]
I just hit the same issue on the headless client:

```
^C2024-10-02T00:19:48.828034Z  INFO firezone_headless_client: Caught SIGINT / SIGTERM / Ctrl+C
2024-10-02T00:19:48.828340Z  INFO firezone_telemetry: Stopping telemetry
^R
^C2024-10-02T00:19:53.828572Z ERROR firezone_telemetry: Failed to flush telemetry events to sentry.io
```

This is branched off 14544b27c.
