### ISSUE TITLE
Configure allowed domains for OIDC

### ISSUE THREAD

**Issue by timothymahoney** [CloudFire-LLC/cloudfire#690]
Hi there! Love your project! Had a question about auth:
When I configure OIDC for Google Auth, it works great, allowing me to authenticate with Google. However, it allows any Google account to authenticate and use the VPN. Am I missing something in the setup? On the Google side? Sorry if this is covered elsewhere but couldn't find anything talking about it in the docs.

**Comment by jamilbk** [comment]
Hi @timothymahoney thanks!

Make sure you select “Internal” when creating the OAuth app. More details here: https://docs.firezone.dev/docs/authenticate/google-sso/#step-1---configure-oauth-consent-screen

**Comment by jamilbk** [comment]
@timothymahoney Did this address your issue? If so mind if I close this?

**Comment by timothymahoney** [comment]
This is totally resolved, thank you @jamilbk !
