### ISSUE TITLE
Azure AD SAML Auth & MFA Support

### ISSUE THREAD

**Issue by jdelforno** [CloudFire-LLC/cloudfire#691]
Looks great, the one limiting factor I'm seeing across all OpenVPN servers is SAML / Azure AD Auth with MFA at both an administration level and a VPN level.

Otherwise, this looks really good and promising.

**Comment by jamilbk** [comment]
Thanks for opening the issue @jdelforno.

Could you elaborate a little more on what you're expecting to see from MFA? We have TOTP-based MFA coming out soon in `0.4.0` and have Azure AD working today via the OIDC connector.

**Comment by jamilbk** [comment]
If I'm understanding correctly, these were released in `0.4.0`.

Feel free to reopen this discussion if not. Thanks!
