### ISSUE TITLE
bug(rust/client): `Failed to flush telemetry events to sentry.io`

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6911]
#### Describe the bug

What it says

#### To Reproduce

??

#### Expected behavior

Expected to be able to flush

#### Screenshots / Logs

1. Headless Client https://github.com/firezone/firezone/issues/6873#issuecomment-2387307716
2. CI unit test https://github.com/firezone/firezone/actions/runs/11141264463/job/30961791374?pr=6909#step:6:2155

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_
- _Firezone Version (e.g. 1.0.0 or N/A):_
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

https://firezone-inc.sentry.io/issues/5939881506?project=4508010028728320

**Comment by thomaseizinger** [comment]
Just got this while I had debug logging on, might be a race condition with DNS control:

```
2024-10-04T01:28:26.442794Z  INFO firezone_telemetry: Stopping telemetry
2024-10-04T01:28:26.443460Z DEBUG reqwest::connect: starting new connection: https://o4507971108339712.ingest.us.sentry.io/
2024-10-04T01:28:26.443787Z DEBUG resolve{host=o4507971108339712.ingest.us.sentry.io}: hyper_util::client::legacy::connect::dns: resolving host="o4507971108339712.ingest.us.sentry.io"
^R
2024-10-04T01:28:31.443024Z ERROR firezone_telemetry: Failed to flush telemetry events to sentry.io
```

**Comment by ReactorScram** [comment]
Might be... I thought I just fixed that though lol

**Comment by thomaseizinger** [comment]
> Might be... I thought I just fixed that though lol

Oh, I might not have been on latest `main`.

**Comment by ReactorScram** [comment]
It shouldn't affect you, I'd only observed it on Windows and only fixed it for the GUI Client since I thought it was a race between the GUI and the tunnel daemon: #6874 

The Headless Client should synchronously deactivate DNS control right here https://github.com/firezone/firezone/blob/main/rust/headless-client/src/main.rs#L323

When we exit the async block and `dns_controller` drops

**Comment by thomaseizinger** [comment]
Fixed in https://github.com/firezone/firezone/pull/7109.
