### ISSUE TITLE
bug(rust/gui-client): release number missing from Sentry release tag

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6925]
#### Expected behavior

Expected `gui-client-1.3.7-*`

#### Screenshots / Logs

<img width="289" alt="image" src="https://github.com/user-attachments/assets/b635f1e4-6a03-49f0-9cf7-cab342f53fea">

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_
- _Firezone Version (e.g. 1.0.0 or N/A):_
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

**Comment by ReactorScram** [comment]
It shows up correctly in local builds, at least sometimes. At least on Ubuntu Linux. Could it depend on the Git version or something?
Even as recent as 1.3.9 it's just saying "0825055"

**Comment by ReactorScram** [comment]
#7202 should have fixed this when it merged

**Comment by thomaseizinger** [comment]
This is still an issue. I think the problem is that we create the tag only on releasing but at that point, the artifact has already been built, so it doesn't know that it got promoted to a release. We should probably use the `CARGO_PKG_VERSION` macro instead.
