### ISSUE TITLE
bug(rust/phoenix-channel): flaky unit tests

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6953]
#### Describe the bug

I saw this in CI just now and seen it locally a couple times but can't reproduce it

https://github.com/firezone/firezone/blob/main/rust/phoenix-channel/src/heartbeat.rs#L104

#### To Reproduce

Don't know how to reproduce it

#### Expected behavior

Expected `phoenix-channel` unit tests to be deterministic

#### Screenshots / Logs

**returns_heartbeat_after_interval**

https://github.com/firezone/firezone/actions/runs/11217278313/job/31178495534#step:6:4383
```
thread 'heartbeat::tests::returns_heartbeat_after_interval' panicked at phoenix-channel/src/heartbeat.rs:104:9:
assertion failed: elapsed >= INTERVAL
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**fails_if_not_provided_within_timeout**

This failed within the same minute on 2 separate runners (Windows 2019 and 2022), I wonder if it could be related to a noisy neighbor in the GitHub VMs? Could the test fail if our threads don't get scheduled quick enough?

https://github.com/firezone/firezone/actions/runs/11334462513/job/31520713665#step:6:3639
```
thread 'heartbeat::tests::fails_if_not_provided_within_timeout' panicked at phoenix-channel\src\heartbeat.rs:152:38:
timeout should not resolve
```

https://github.com/firezone/firezone/actions/runs/11334462513/job/31520714119
```
thread 'heartbeat::tests::fails_if_not_provided_within_timeout' panicked at phoenix-channel\src\heartbeat.rs:152:38:
timeout should not resolve
```

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ phoenix-channel
- _Firezone Version (e.g. 1.0.0 or N/A):_ `main`
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ Ubuntu, probably Windows
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ N/A

**Comment by thomaseizinger** [comment]
I ran the test binary in a loop 1000 times and it didn't fail :(

**Comment by ReactorScram** [comment]
Saw it just now on another unit test of `phoenix-channel`. Updated the original post

**Comment by ReactorScram** [comment]
Another pair where both Windows runners, and only Windows, failed.
https://github.com/firezone/firezone/actions/runs/11335501832/job/31523768987
https://github.com/firezone/firezone/actions/runs/11335501832/job/31523769151

**Comment by ReactorScram** [comment]
@thomaseizinger I think this one has your new logging in it https://github.com/firezone/firezone/actions/runs/11349838342/job/31567097532#step:6:4301

Windows once again...

You know I read on Hacker News yesterday that Windows and Linux have opposite behavior for small sleeps? That may not apply inside Tokio ofc.

Linux interprets small sleeps as "You will sleep for at least one granule", which meshes with my thought of "You are lucky if the OS ever schedules you, be grateful"

Windows (If I read correctly) sometimes translates small sleeps into busy waits.

This was in a thread where someone was arguing that waking up the CPU 100 times per second in an otherwise idle app was Good, Actually.

**Comment by ReactorScram** [comment]
These two 
https://github.com/firezone/firezone/actions/runs/11349851924/job/31567118582#step:6:4293
https://github.com/firezone/firezone/actions/runs/11349851924/job/31567123537#step:6:4299

**Comment by ReactorScram** [comment]
Testing on the Macbook in Windows, even at `TIMEOUT * 5` it fails from time to time.

**Comment by ReactorScram** [comment]
Made a test program and I don't see Windows undershooting the sleeps, although I do see a granularity of about 15 ms.

```
Requested sleep time --> Actual
8000 us --> 10395 us
8000 us --> 29510 us
8000 us --> 16665 us
8000 us --> 15756 us
8000 us --> 15213 us
9000 us --> 15455 us
9000 us --> 30821 us
9000 us --> 15081 us
9000 us --> 16063 us
9000 us --> 16640 us
10000 us --> 15596 us
10000 us --> 15168 us
10000 us --> 15583 us
10000 us --> 30643 us
10000 us --> 15224 us
11000 us --> 16021 us
11000 us --> 15334 us
11000 us --> 16723 us
11000 us --> 15126 us
11000 us --> 15618 us
12000 us --> 15156 us
12000 us --> 15972 us
12000 us --> 14683 us
12000 us --> 15784 us
12000 us --> 15395 us

```

**Comment by ReactorScram** [comment]
But granularity could still explain it.
![Image](https://github.com/user-attachments/assets/545a4298-5f66-451b-8c3a-adaf2ca07c26)

We poll both futures and expect the heartbeat to time out in 5 ms.

15 ms later, both futures are ready, Windows wakes us up, and we poll the timeout and panic.

I see this millisecond time scale is just for unit tests. I'll open a PR commenting that it's Windows' fault and increasing the smallest sleep unit to 15 ms.

**Comment by thomaseizinger** [comment]
Ah here are the answers to #7061! Thank you for digging into this. Could knowledge to document. cc @conectado
