### ISSUE TITLE
Prevent using sentinel ranges for DNS upstreams

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#6962]
The proptests discovered this issue which I fixed in [`c8d87f8` (#6943)](https://github.com/firezone/firezone/pull/6943/commits/c8d87f81f39cd1e72f6f6566d462f38bf6286fb8).

I think we knew this but probably worth discussing the following:

- Do we need to document this somewhere?
- Should we block this on the portal?

**Comment by jamilbk** [comment]
Yeah we should probably prevent this with a validation check in the portal. I'll update the title accordingly.

Need to prevent the following ranges from being used as DNS sentinels in the portal:

```
100.64.0.0/10
fd00:2021:1111::/48
```

We already have this validation for Resources, just need to apply it to DNS upstreams too.

**Comment by AndrewDryga** [comment]
@bmanifold I know you have a PR that changes the DNS page already. Let's fix it once your PR is merged
