### ISSUE TITLE
Delete old tags for relay, api & web that contain versions

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#7001]
We still have a bunch of image tags for relay, api and web that have version numbers, for example: https://github.com/firezone/firezone/pkgs/container/api/219661248?tag=1.0.5.

A (self-hosted) user was relying on those and thus was using outdated versions of these components. We should delete all of these tags and make sure all tags are only commit SHA + 1 latest tag.

**Comment by AndrewDryga** [comment]
@thomaseizinger that will break self-hosted environments that are currently working on those old versions (we don't know if they exist and how many of them, but I bet there will be some). Artifacts should be immutable

**Comment by thomaseizinger** [comment]
Well, maybe we should "break" those users to alert them that they are on a really old version? I doubt the current clients & gateways even work with such an old control plane.

In fact, the self-hosted user I was talking to mentioned that things aren't working and we found out that they were following the `1` tag.

**Comment by AndrewDryga** [comment]
@thomaseizinger what is they did what we was asking for - built the clients themselves?

**Comment by thomaseizinger** [comment]
No, I don't think any self-hosted user actually does. I've not encountered one that built it themselves.

**Comment by thomaseizinger** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/5486389?s=64&amp;u=15061e4db68c8b2aac71433521ee4bdd0c21b5af&amp;v=4">@thomaseizinger](https://github.com/thomaseizinger) that will break self-hosted environments that are currently working on those old versions (we don't know if they exist and how many of them, but I bet there will be some). Artifacts should be immutable

I think the main argument here would be that:

- Our artifacts are in fact immutable. They'll continue to exist, we only remove certain tags.
- Breaking those self-hosted users is likely a good thing because it forces them to either change the tag they depend on to explicitly be an outdated SHA or switch to `latest` if they do indeed want to be on the latest version which I think is what most people's intention is when they specify `:1` as their tag

**Comment by AndrewDryga** [comment]
I think @jamilbk should decide.

> Breaking those self-hosted users is likely a good

When you have some sort of app that you rely on and then you reboot the VM or restart the docker and now it doesn't work because can't even pull an image is never a good thing.

**Comment by jamilbk** [comment]
I can see both sides to this. Generally I would lean towards removing them in the spirit of cleaning up tech debt and preventing confusion going forward. However, I'm not sure this is possible in the Github packages UI?

> When you have some sort of app that you rely on

If this is indeed the case, the user should be using a supported version of Firezone, not self-hosting it.

In any case, I don't think it's worth spending time discussing this too much further. Will close to keep our focus on supported versions of Firezone.
