### ISSUE TITLE
chore(rust/gui-client): Use Sentry to report OS versions being used

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#7011]
e.g. "Windows 10", "Windows 11", "Ubuntu 20.04", "Ubuntu 22.04"

Even if they don't send any errors or panics. Just to see if we really need to keep Tauri v1 around until April, or if we could drop it early and save some maintenance hours.

**Comment by thomaseizinger** [comment]
Now part of the context that we attach.
