### ISSUE TITLE
Add refresh-oidc-tokens command to firezone-ctl

### ISSUE THREAD

**Issue by salemgolemugoo** [CloudFire-LLC/cloudfire#702]
Would be super useful while debugging the OIDC connections. Now it's disabling users if something goes wrong during the refreshing process (see: https://github.com/firezone/firezone/pull/605). And you have to wait one hour https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/oidc/refresh_manager.ex#L10 to check your new oidc settings.
Another approach is to make this value https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/oidc/refresh_manager.ex#L10 changeable in the config file.

**Comment by jamilbk** [comment]
This is a great suggestion, thanks @salemgolemugoo. I think adding a manual refresh button at the top of the OIDC Connections table makes sense, e.g.

<img width="910" alt="Screen_Shot_2022-06-13_at_12_50_10_PM" src="https://user-images.githubusercontent.com/167144/173433768-ac52295b-3a38-48a2-b9d6-30acc402e543.png">

**Comment by jamilbk** [comment]
Will be released in 0.4.0
