### ISSUE TITLE
Sentry integration with gateways

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#7099]
```[tasklist]
### DoD
- [ ] https://github.com/firezone/firezone/pull/7103
- [x] Documentation update?
- [x] Do we need to update the "Deploy" page in the portal to mention telemetry?
```

**Comment by thomaseizinger** [comment]
I don't have the permissions to create a sentry project.

**Comment by thomaseizinger** [comment]
@jamilbk Can you comment on the two tasks I added to the above list in terms of docs / communication what we need here?

**Comment by jamilbk** [comment]
> @jamilbk Can you comment on the two tasks I added to the above list in terms of docs / communication what we need here?

Left a comment. I think we'll also want to document how to disable it.

Gateways unlike clients are often running in more sensitive network environments so I imagine admins may want to turn that off.

**Comment by thomaseizinger** [comment]
Okay, I'll add a toggle to turn it off.
