### ISSUE TITLE
GUI client reporting version stuck at 1.3.5

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#7122]
Linux and Windows GUI clients are reporting version 1.3.5 to the portal even though the About window says 1.3.9.

See here for an example: https://app.firez.one/firezone/clients/fbd813df-d495-47f8-ad20-7b62f0f0ecca

refs https://firezonehq.slack.com/archives/C06L41XN05T/p1729515364242069

**Comment by ReactorScram** [comment]
I wonder if the IPC service is accidentally reporting the Headless Client version, which is 1.3.5. I don't think the GUI process ever tells the IPC service what our version number is supposed to be, and the IPC service is built as part of the Headless Client crate.
