### ISSUE TITLE
OIDC <|> VPN session UX improvements

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#724]
Refs #721 

- [x] Allow admins to re-enable their own "Permission to connect to VPN"
- [x] Add a "Delete Tokens" red-styled button next to the "Refresh Tokens" button. When clicked, should display an alert, "Deleting a token will prevent their VPN session from being disabled for any OIDC errors until they log in again. Proceed?"
- [ ] Consider adding a configuration option, `default['firezone']['authentication']['disable_vpn_for_oidc_errors'] = true` that allows an admin to decouple this functionality and disable it for troublesome OIDC providers 👎

**Comment by princemaple** [comment]
> * Add a "Delete Tokens" red-styled button next to the "Refresh Tokens" button. When clicked, should display an alert, "Deleting a token will prevent their VPN session from being disabled for any OIDC errors until they log in again. Proceed?"

With google, once deleted, it takes a revoke to re-connect.

**Comment by princemaple** [comment]
> * Consider adding a configuration option, `default['firezone']['authentication']['disable_vpn_for_oidc_errors'] = true` that allows an admin to decouple this functionality and disable it for troublesome OIDC providers

The refresh would simply not do anything, then.

**Comment by jamilbk** [comment]
> > * Add a "Delete Tokens" red-styled button next to the "Refresh Tokens" button. When clicked, should display an alert, "Deleting a token will prevent their VPN session from being disabled for any OIDC errors until they log in again. Proceed?"
> 
> With google, once deleted, it takes a revoke to re-connect.

Hmm let’s generalize it to “… until the refresh_token is set again”.

I’ll have to do some more research… maybe there’s a More robust way to handle all this

**Comment by jamilbk** [comment]
> > * Consider adding a configuration option, `default['firezone']['authentication']['disable_vpn_for_oidc_errors'] = true` that allows an admin to decouple this functionality and disable it for troublesome OIDC providers
> 
> The refresh would simply not do anything, then.

Let’s skip this change for now then. Need to do more investigation

**Comment by princemaple** [comment]
Should the deletion be per connection? Or all connections

**Comment by jamilbk** [comment]
> Should the deletion be per connection? Or all connections

~~I think all — we want to effectively reset them.~~

Edit: Per-connection is fine

@princemaple Also let’s go ahead with allowing an admin to decouple the oidc refresh -> disconnects vpn config option (
See #721
