### ISSUE TITLE
Make use of Sentry's "user" functionality

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#7248]
I think (needs more research to confirm) that if we use Sentry's `set_user` funtionality (https://docs.rs/sentry/latest/sentry/struct.Scope.html#method.set_user) then Sentry would not only count the events for us but also directly compute, how many different users are affected.

This would be very helpful in triaging issues: An issue that affects many users is more important to handle than an issue that only affects a single user. In addition, several issues might be related so Sentry might group them together for us?

We need to figure out, what information is okay to capture as a user. We could perhaps use the firezone ID? For the purposes of Sentry, it may be good enough to say "1 installation of the app" == "1 user" even if the same user could technically use Firezone on multiple devices.

**Comment by jamilbk** [comment]
> We could perhaps use the firezone ID? For the purposes of Sentry, it may be good enough to say "1 installation of the app" == "1 user" even if the same user could technically use Firezone on multiple devices.

That would be fine
