### ISSUE TITLE
Documentation on how to run behind a different reverseproxy

### ISSUE THREAD

**Issue by gmeks** [CloudFire-LLC/cloudfire#729]
Hey,

For those of us that run homelabs and im sure other senarios we dont have alot of valid IP addresses, and need to put the web interface behind a seperate reverse proxy.

Is it posible to update the documentation on how to do this?

**Comment by jamilbk** [comment]
Yes, this is possible but due to number of reverse proxies out there and the complexity of configuration it may not be feasible to support long term.

Would you be disabling the bundled nginx? Which reverse proxy were you planning to use?

**Comment by gmeks** [comment]
Nginx Proxy Manager is what im using now.

Normaly products will have a setting for "trusted proxy" , and perhaps a setting for what header is forwarded. I dont think you have to support every senario.

But having documentation for 1 senario, most people should be able to figure out how to do it in their setup.

**Comment by jamilbk** [comment]
Related to #731
