### ISSUE TITLE
Broken email template for sign in

### ISSUE THREAD

**Issue by Intuinewin** [CloudFire-LLC/cloudfire#7294]
#### Describe the bug

When receiving the sign in email containing the login token, the button is not clickable.
In the email I see `href=3D{@sign_in_url}` so it seems the templating doesn't work.

#### To Reproduce

- Try to sign in with an email
- Try to click the "Complete Sign In" button

#### Expected behavior

The button should open the admin console and log me in.

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Admin portal
- _Firezone Version (e.g. 1.0.0 or N/A):_ 1.x

**Comment by bmanifold** [comment]
@Intuinewin, thank you for the bug report!  I just put a PR up to fix the issue.
