### ISSUE TITLE
Fix bencher integration in CI

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#7441]
This seems to be consistently failing now. Would be good to tidy it up.

https://github.com/firezone/firezone/runs/33717378016

**Comment by thomaseizinger** [comment]
I looked into this and my conclusion was that the CI env is just too noisy and unstable performance wise to produce accurate numbers.

See https://github.com/firezone/firezone/issues/7243.

**Comment by thomaseizinger** [comment]
Seems to have fixed itself.
