### ISSUE TITLE
bug(connlib): "The destination buffer is too small"

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#7442]
Tracking issue for a problem we've seen rarely pop up in the macOS client but also in CI.

No good data on this issue, but here are the relevant threads:

- https://firezonehq.slack.com/archives/C05KAA18L1Z/p1717597746253799
- https://firezonehq.slack.com/archives/C069H865MHP/p1730758497969819?thread_ts=1730757791.864759&cid=C069H865MHP

**Comment by thomaseizinger** [comment]
This has been fixed in `main` already with https://github.com/firezone/boringtun/pull/26.
