### ISSUE TITLE
Fix passing of `providerStopReason` in macOS so that "You have been signed out" continues to function

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#7468]
With the move the system extension, the gui process no longer knows why the tunnel became disconnected. This was stored in a plaintext file when the tunnel disconnected and then read by the gui process. If it was a 401, the user was shown an alert dialog to sign in again (session expired).

We need to use some other mechanism (Keychain will work) for communicating the last stopped reason back to the gui process.

**Comment by thomaseizinger** [comment]
> We need to use some other mechanism (Keychain will work) for communicating the last stopped reason back to the gui process.

Wouldn't an IPC message be better for this? That is what we do in the Tauri client.

**Comment by jamilbk** [comment]
Ah, yeah the GUI could simply ask for it when it needs it.

However, since this is a tunnel-initiated coms it will require a little more clever state tracking.

**Comment by thomaseizinger** [comment]
> Ah, yeah the GUI could simply ask for it when it needs it.
> 
> However, since this is a tunnel-initiated coms it will require a little more clever state tracking.

Not all IPC actions have to be initiated by the GUI, right? I don't know Apple's IPC mechanism but usually, it is just a two-way socket and you can send messages in both directions.

In the Tauri client, this isn't strictly request-response. Instead, several of them are just events, notifying the other side of something happening. (Like tunnel disconnected).

**Comment by jamilbk** [comment]
The IPC mechanism exposed via the Network Extension API is strictly app -> provider.

We can have bidirectional via the XPC framework, but initial efforts (~1 day) to get that working proved futile. I know it's possible because Apple provides a sample project which has it working out of the box:

https://developer.apple.com/documentation/networkextension/filtering-network-traffic

But for the purposes of this issue and the IPC we need thus far, I'm not sure it's worth adding that complexity just yet. It would mean two different IPC mechanisms for iOS and macOS, while we are currently getting away with just one.
