### ISSUE TITLE
KDE Network Manager - IPv6 Import Failure

### ISSUE THREAD

**Issue by gbe0** [CloudFire-LLC/cloudfire#753]
Importing WireGuard profiles with the KDE Network Manager when IPv6 is enabled for Firezone will fail with this error:

`ipv6.method: method "auto" is not supported for WireGuard`

![image](https://user-images.githubusercontent.com/47361208/175463217-9d033fa6-8ced-478f-b024-e724ae32a80c.png)

Importing IPv4 only profiles does not encounter this same problem.

**Comment by gbe0** [comment]
Example working configuration:
```
[Interface]
PrivateKey = ...
Address = 10.199.32.4/32
MTU = 1420
DNS = 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4

[Peer]
PresharedKey = ...
PublicKey = ...
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 192.0.2.1:51820
PersistentKeepalive = 0
```
Example broken configuration:
```
[Interface]
PrivateKey = ...
Address = 10.199.24.5/32,2001:db8:ffff::1/128
MTU = 1420
DNS = 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4, 2606:4700:4700::1111, 2606:4700:4700::1001, 2001:4860:4860::8888, 2001:4860:4860::8844

[Peer]
PresharedKey = ...
PublicKey = ...
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 192.0.2.1:51820
PersistentKeepalive = 0
```

**Comment by jamilbk** [comment]
Hey @gbe0 -- going to close this for now as we're shifting focus to supporting our own client apps over the WireGuard clients.
