### ISSUE TITLE
Improve "Permission to connect to VPN" messaging / UI

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#765]
Currently, there are 2 reasons a user's VPN session could be disconnected / disabled:

1. OIDC error (set `disabled_at`)
2. Hasn't logged into the Web UI within X window of time

The `VPN Connection` checkbox only conveys (1), while many users seem to be getting caught off-guard by (2).

<img width="337" alt="Screen Shot 2022-06-28 at 9 53 03 AM" src="https://user-images.githubusercontent.com/167144/176236678-93e529c2-ec12-40a6-b2b3-62afec0ee778.png">

Propose changing the Users table to show one of three tags instead of `VPN Connection` checkbox:

1. If `disabled_at` is nil and user has logged in within the `vpn_session_duration` window, show green tag `ACTIVE` with hover text "This user's VPN connection is enabled"
2. If `disabled_at` is set, show red tag `DISABLED` with hover text "This user's VPN connection is disabled by an administrator or OIDC refresh error"
3. If `disabled_at` is nil, but login is past `vpn_session_duration`, show a yellow tag `EXPIRED` with hover text "This user's VPN connection is disabled due to authentication expiration"

**Comment by bcookatpcsd** [comment]
Could there also be a logging event generated.. firezone-ctl tail

Did not show anything related to the event.

**Comment by jamilbk** [comment]
Fixed in #784
