### ISSUE TITLE
Allow configuration of firewall rules in the config file

### ISSUE THREAD

**Issue by antoineozenne** [CloudFire-LLC/cloudfire#798]
Is it possible to allow to define firewall rules in the configuration files ? It would allow to handle all the configuration with IaC, without manual intervention.

**Comment by jamilbk** [comment]
Good question, and unfortunately, no -- not possible at the moment. If you're looking for a way to create rules from the CLI, try this:

```
/opt/firezone/embedded/service/firezone/bin/firezone rpc 'FzHttp.Rules.create_rule(%{destination: "0.0.0.0/0", action: :drop})'
```

We do have plans for a REST API which should make this easier.

**Comment by antoineozenne** [comment]
Ok thank you. Is this command idempotent?

**Comment by jamilbk** [comment]
> Ok thank you. Is this command idempotent?

Yep! We have a unique index for `[destination, action]` pairs, so running again will just return nothing. If you want to see the error you can wrap it in `IO.inspect()`:

```
root@demo:~# /opt/firezone/embedded/service/firezone/bin/firezone rpc 'IO.inspect(FzHttp.Rules.create_rule(%{destination: "0.0.0.0/0", action: :accept}))'
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{
     action: :accept,
     destination: %Postgrex.INET{address: {0, 0, 0, 0}, netmask: 0}
   },
   errors: [
     destination: {"A rule with that IP/CIDR address already exists.",
      [constraint: :unique, constraint_name: "rules_destination_action_index"]}
   ],
   data: #FzHttp.Rules.Rule<>,
   valid?: false
 >}
```

**Comment by antoineozenne** [comment]
Nice! So I can add this command in my Ansible playbook. Thank you @jamilbk!

**Comment by antoineozenne** [comment]
Hi @jamilbk, I have a problem with the command you gave me. This may be a bug.

With the following commands:

```sh
root@host: /opt/firezone/embedded/service/firezone/bin/firezone rpc 'IO.inspect(FzHttp.Rules.denylist())'
# []
root@host: /opt/firezone/embedded/service/firezone/bin/firezone rpc 'IO.inspect(FzHttp.Rules.create_rule(%{destination: "0.0.0.0/0", action: :drop}))'
# {:ok,
#  %FzHttp.Rules.Rule{
#    __meta__: #Ecto.Schema.Metadata<:loaded, "rules">,
#    action: :drop,
#    destination: %Postgrex.INET{address: {0, 0, 0, 0}, netmask: 0},
#    id: 9,
#    inserted_at: ~U[2022-07-15 12:10:53.429272Z],
#    updated_at: ~U[2022-07-15 12:10:53.429272Z],
#    uuid: "8883ee08-7365-4696-9883-f6631a44a120"
#  }}
root@host: /opt/firezone/embedded/service/firezone/bin/firezone rpc 'IO.inspect(FzHttp.Rules.denylist())'
# [
#   %FzHttp.Rules.Rule{
#     __meta__: #Ecto.Schema.Metadata<:loaded, "rules">,
#     action: :drop,
#     destination: %Postgrex.INET{address: {0, 0, 0, 0}, netmask: 0},
#     id: 9,
#     inserted_at: ~U[2022-07-15 12:10:53.429272Z],
#     updated_at: ~U[2022-07-15 12:10:53.429272Z],
#     uuid: "8883ee08-7365-4696-9883-f6631a44a120"
#   }
# ]
```

In the Firezone web app, I correctly see the deny rule for 0.0.0.0/0. Then I start my VPN client, but all traffic goes through, no packets are dropped.

However, if I try to add this rule directly in the web app, the behavior is ok, all packets are dropped.

Is the command to add a deny rule ok? Or is it a bug?

**Comment by princemaple** [comment]
Try this: rpc 'FzHttp.Events.add_rule(FzHttp.Repo.one(FzHttp.Rules.Rule))'

This only works when you have exactly have one rule. We can look into further solutions later.

**Comment by antoineozenne** [comment]
Thank you, but I can't use only one rule. I need to drop all but accept several IPs.

**Comment by jamilbk** [comment]
> Thank you, but I can't use only one rule. I need to drop all but accept several IPs.

Hey @antoineozenne thanks for pointing this out. Ah, the joys of undocumented workarounds :-).

What's happening here is the trigger `Events.add_rule` to add a rule is not executing in that `create_rule` helper. Two options:

1. Issue a `firezone-ctl restart phoenix` after creating all your rules to apply them on application boot up
2. Or, call the `Events.add_rule` helper like @princemaple mentioned above after **each** rule is created to register it with the `fz_wall` backend.

We'll have better automation around all this in a REST API we're working on.

**Comment by jamilbk** [comment]
Refs firezone/product#180

**Comment by antoineozenne** [comment]
Hi @jamilbk, thank you. I already love this REST API. :)

I will test the `restart` solution in a few days. I will keep you informed.

Your refs in your last comment points to a 404.

**Comment by antoineozenne** [comment]
I tried that but all my traffic is dropped, even to `A.B.C.D/32`:

```sh
/opt/firezone/embedded/service/firezone/bin/firezone rpc 'IO.inspect(FzHttp.Rules.create_rule(%{destination: "0.0.0.0/0", action: :drop}))'
/opt/firezone/embedded/service/firezone/bin/firezone rpc 'IO.inspect(FzHttp.Rules.create_rule(%{destination: "A.B.C.D", action: :accept}))'
firezone-ctl restart phoenix
```

Did I miss something?

**Comment by jamilbk** [comment]
@antoineozenne We've improved our rule application logic in 0.5.x -- more specific CIDRs should be taking precedence over less specific ones. Are you able to update to 0.5.2 and give that a shot?

**Comment by antoineozenne** [comment]
Thank you @jamilbk. Unfortunately, I can't update now. We have priority projects to work on. For now we are using version 4. In a while I will update and let you know. ;)

**Comment by jamilbk** [comment]
The REST API will allow you to specify egress rules in JSON format and apply them with `curl` or similar. refs #903

**Comment by antoineozenne** [comment]
> The REST API will allow you to specify egress rules in JSON format and apply them with `curl` or similar. refs #903

Nice! And maybe soon a Terraform provider? :)

**Comment by jamilbk** [comment]
@antoineozenne For Terraform, see our community-contributed modules at https://github.com/firezone/terraform-aws-firezone-vpn and https://github.com/firezone/azure-terraform-firezone.

REST API should be out in 0.7.0, within a week or so™.

**Comment by AndrewDryga** [comment]
@antoineozenne REST API is out, please go ahead and try using it to manage rules and tell me if you have any other questions - I will reopen the issue.
