### ISSUE TITLE
No straightforward way to disable Phoenix crash detection 

### ISSUE THREAD

**Issue by icekom** [CloudFire-LLC/cloudfire#807]
The only way I found to disable crash detection is to edit `/opt/firezone/service/phoenix/finish`, which is clumsy. I think there should be an option to disable it or, even better, use exponential backoff instead of stopping the service forever. The rationale is that it might be crashing because of external dependencies not being ready yet, so retrying a bit later would have fixed it. There are probably more cases where retrying forever is desired (e.g. to reduce the chance of being locked out).

In my use case, the OIDC server might start later than Firezone, so by the time OIDC starts, Phoenix has already crashed five times and disabled itself, requiring manual intervention. In my opinon, crashing IS the correct behaviour for an unavailable external dependency, although right now the `finish` script sends a (kind of misleading) event to PostHog if telemetry is enabled.

**Comment by jamilbk** [comment]
Thanks for the suggestion! I agree, exponential backoff with a configurable rate of decay is more sensible. Let me queue this change for the next release.

It might be worth considering whether an OIDC connect timeout warrants crashing the whole supervision tree, but I’ll leave that discussion for another issue. We have some improvements to be made to the OIDC backend.

**Comment by jamilbk** [comment]
@icecom-dg 

I'll leave the exponential backoff implementation for a later time when we have a bit more data about the various `phoenix` crash scenarios, and OIDC is a bit more robust.

But otherwise you'll be able to disable this in 0.5.0 due out Soon™.

Thanks for the report!
