### ISSUE TITLE
Enable per-group rules

### ISSUE THREAD

**Issue by antoineozenne** [CloudFire-LLC/cloudfire#830]
It would be nice if `Allowed IPs` could be enforced by firewall rules on a per-group level for users connected via SSO. It would enable managing users permissions with Azure AD groups for example.

Ref https://github.com/firezone/firezone/issues/423

**Comment by jamilbk** [comment]
Thanks for the suggestion @antoineozenne!

This is part of a bigger RBAC feature we have in our private backlog. I fear this won't be a trivial task as each OpenID Connect provider follows the standard with their own quirks and limitations, making a one-size-fits-all approach tricky.

SAML should be better-suited for the task. I'll update here as we dig deeper.

**Comment by patschi** [comment]
That feature would be awesome. My two cents: I think implementing the restrictions using firewall would provide way more granularity, instead of just adjusting `Allowed IPs` setting, e.g. also limiting to specific ports.

It would be useful to e.g. add users to groups like "Nextcloud Users", verifying upon connect if the user is in that group and and allowing TCP/443 to the Nextcloud instance.

**Comment by jamilbk** [comment]
Thanks for the awesome feedback @patschi 

We are looking into SAML/SCIM support and would probably want to provide the option to integrate with that as well by mapping Firezone roles/groups to those from the IdP.

**Comment by jamilbk** [comment]
@patschi As a side note, we already support user-scoped, port-based rules as of 0.5.4.

**Comment by EternalDeiwos** [comment]
> This is part of a bigger RBAC feature we have in our private backlog. I fear this won't be a trivial task as each OpenID Connect provider follows the standard with their own quirks and limitations, making a one-size-fits-all approach tricky.

@jamilbk in the generic OIDC case: most IdPs support this by exposing some kind of groups/roles claim on tokens and/or userinfo; its the name of the claim that varies the most. If you added a configurable to resolve the claim from a [JSON path](https://datatracker.ietf.org/doc/draft-ietf-jsonpath-base/) (or similar notation) then you could expect a JSON array of group names or ids from the majority of IdPs.

Unfortunately I don't think there will ever be a solution that fits 100% of IdPs.

I would also like a solution to this to include granting and removing admin privileges to Firezone itself as well.

**Comment by jamilbk** [comment]
@EternalDeiwos JSON path would work. For the admin privs -- would you be expecting that to come in the same `groups` claim or in another, dedicated claim for that?

**Comment by EternalDeiwos** [comment]
@jamilbk likely the same claim but you'll need another configurable to specify what the administrator role is called.

**Comment by jamilbk** [comment]
Thanks for all the input guys! Going to track this work in #1157
