### ISSUE TITLE
Error too many redirects on newest version

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#862]
I changed nothing except just updating firezone

**Comment by dillfrescott** [comment]
I can neither access it via the domain nor the direct ip and port

**Comment by dillfrescott** [comment]
Had to downgrade back to 0.4.5

**Comment by jamilbk** [comment]
cc @conectado -- possible redirect loop from the `force_ssl` changes?

**Comment by jamilbk** [comment]
@DillFrescott Could you elaborate a little more on your config? Specifically any SSL configuration changes you've made from the defaults.

**Comment by dillfrescott** [comment]
Sure. I am using the http port of 7000 and have it reverse proxied with Caddy to vpn.dillfrescott.com. Every other version has worked fine doing that so far.

**Comment by conectado** [comment]
> Sure. I am using the http port of 7000 and have it reverse proxied with Caddy to vpn.dillfrescott.com. Every other version has worked fine doing that so far.

I think it might be the lack of `X-Forwarded-For` header in the request. @DillFrescott Do you have the bundled nginx disabled(`default['firezone']['nginx']['enabled'] = false` in `/etc/firezone/firezone.rb`)?

**Comment by jamilbk** [comment]
Ah I see. We released [official support for external reverse proxies](https://docs.firezone.dev/deploy/reverse-proxies) in 0.5.0. Let me update the Upgrade notes with a section on that.

In the meantime, try this: 

Set `default['firezone']['phoenix']['external_trusted_proxies'] = ['34.34.34.34']` where `34.34.34.34` is the IP of your Caddy server. And ensure the bundled nginx is disabled as @conectado suggested.

**Comment by jamilbk** [comment]
If your Caddy server has an RFC 1918 address (i.e. on the local network), add its IP to the `default['firezone']['phoenix']['private_clients']` array instead.

This is needed to properly resolve remote addresses to prevent client IP spoofing.

**Comment by dillfrescott** [comment]
> I think it might be the lack of `X-Forwarded-For` header in the request. @DillFrescott Do you have the bundled nginx disabled(`default['firezone']['nginx']['enabled'] = false` in `/etc/firezone/firezone.rb`)?

Its commented out currently

**Comment by dillfrescott** [comment]
> In the meantime, try this:
> 
> Set `default['firezone']['phoenix']['external_trusted_proxies'] = ['34.34.34.34']` where `34.34.34.34` is the IP of your Caddy server. And ensure the bundled nginx is disabled as @conectado suggested.

Okay

**Comment by dillfrescott** [comment]
> If your Caddy server has an RFC 1918 address (i.e. on the local network), add its IP to the `default['firezone']['phoenix']['private_clients']` array instead.
> 
> This is needed to properly resolve remote addresses to prevent client IP spoofing.

gotcha

**Comment by dillfrescott** [comment]
I'm going to be honest I have no idea what an RFC 1918 is

**Comment by dillfrescott** [comment]
My caddy server is the same server that firezone is running on

**Comment by dillfrescott** [comment]
I disabled nginx and now it just says cloudflare bad gateway as nothing is listening on port 7000 anymore

**Comment by dillfrescott** [comment]
I dont think its due to the reverse proxy because when I tried to access it directly on localhost:7000 it did the same thing

**Comment by jamilbk** [comment]
@DillFrescott Gotcha. Leave nginx disabled, and instead set `default['firezone']['phoenix']['port'] = 7000`

**Comment by jamilbk** [comment]
Just so I have this right, the setup you had before was:

Cloudflare -> Caddy -> Nginx -> Phoenix (firezone web portal)

And `default['firezone']['nginx']['non_ssl_port'] = 7000`?

**Comment by dillfrescott** [comment]
> @DillFrescott Gotcha. Leave nginx disabled, and instead set `default['firezone']['phoenix']['port'] = 7000`

Ok i will try this

**Comment by dillfrescott** [comment]
> Just so I have this right, the setup you had before was:
> 
> Cloudflare -> Caddy -> Nginx -> Phoenix (firezone web portal)
> 
> And `default['firezone']['nginx']['non_ssl_port'] = 7000`?

Correct

**Comment by jamilbk** [comment]
With 0.5.0, Nginx can be cut out, and you can instead do this:

Cloudflare -> Caddy -> Phoenix (port 7000)

And the following config:

```ruby
default['firezone']['nginx']['enabled'] = false
default['firezone']['phoenix']['port'] = 7000
default['firezone']['phoenix']['private_clients'] = ['127.0.0.1']
```

**Comment by dillfrescott** [comment]
Fixed!

**Comment by dillfrescott** [comment]
Thank you so much!

**Comment by jamilbk** [comment]
Lastly, if you want the Firezone web portal to properly see your client's source IPs you'll want to add Cloudflare's IPs to the trusted proxies list.

Taken from https://www.cloudflare.com/ips/:

```ruby
default['firezone']['phoenix']['external_trusted_proxies'] = %w[
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
172.64.0.0/13
131.0.72.0/22
2400:cb00::/32
2606:4700::/32
2803:f800::/32
2405:b500::/32
2405:8100::/32
2a06:98c0::/29
2c0f:f248::/32
]
```

This will be used to extract the proper client IP from the IP list in the `x-forwarded-for` header (hopefully) passed from Cloudflare.

**Comment by dillfrescott** [comment]
Okay! I'll do this!
