### ISSUE TITLE
Showing as not connected to UI even though I am.

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#863]
https://i.imgur.com/J66qCBH.png

This one isn't a big deal just thought I would let you guys know its doing this no matter how many times I refresh the page.

**Comment by jamilbk** [comment]
Yeah, this is happening because the WebSocket can't connect -- for some reason Caddy isn't properly proxying the WebSocket requests through to Phoenix.

Alternatively, if you were just using Caddy for its ACME support, in 0.5.0 we now have ACME support in Firezone. It's disabled by default, but if you want to enable it (and ditch Caddy) you can do so with something like the following config:

```ruby
default['firezone']['nginx']['enabled'] = true
default['firezone']['ssl']['acme']['enabled'] = true
default['firezone']['nginx']['non_ssl_port'] = 80
default['firezone']['nginx']['ssl_port'] = 443
default['firezone']['ssl']['certificate'] = nil
```

This assumes your server has a valid FQDN set in `default['firezone']['external_url']`

**Comment by dillfrescott** [comment]
Okay! Ill go ahead and close this issue because I didn't know it was an issue with my particular setup!

**Comment by dillfrescott** [comment]
The issue is that I'm also hosting a docker vaultwarden server on the same machine so it would be difficult to get rid of using caddy because it provides a connection to both firezone and bitwarden

**Comment by jamilbk** [comment]
Ah I see. Feel free to leave this issue open for a while -- maybe someone else has a similar configuration and figured out a solution.

It may help to post a screenshot of your browser's JS console showing the details of the WebSocket connect failure.

**Comment by princemaple** [comment]
Can I see your caddy config? Also are you on caddy 1 or caddy 2?

Caddy 2 handles websocket transparently, without you having to do anything.

**Comment by dillfrescott** [comment]
http://vpn.dillfrescott.com {

	reverse_proxy http://localhost:7000
}
https://bitwarden.dillfrescott.com {

	reverse_proxy http://localhost:3000
}

Caddy 2

**Comment by dillfrescott** [comment]
@princemaple I know right? I would expect Caddy to handle proxying stuff like that just automatically

**Comment by princemaple** [comment]
Can you try this instead?

vpn.dillfrescott.com {
    reverse_proxy localhost:7000
}

**Comment by dillfrescott** [comment]
Ok tried it. Caddy doesnt even recognize removing the http as a config change. Its the exact same according to it.

`2022/07/29 21:50:59.235 INFO     config is unchanged`

Also I checked firezone and its still saying not connected btw.

**Comment by dillfrescott** [comment]
To be clear, before 0.5 it was proxying the websocket correctly with nginx between phoenix and caddy

**Comment by dillfrescott** [comment]
I have yet to update to 0.5.1 yet and am still on 0.5.0, does the update handle anything with that?

**Comment by princemaple** [comment]
Any server logs / browser console logs?

**Comment by dillfrescott** [comment]
https://i.imgur.com/K02iZJW.png Yes lol I probably should have checked this

**Comment by jamilbk** [comment]
@DillFrescott Any corresponding log in `firezone-ctl tail phoenix`? What's your `default['firezone']['external_url']` set to?

**Comment by dillfrescott** [comment]
https://bin.idrix.fr/?560fd3a725c353e4#429ofkfwoGw5vv6jK6AguMmhu2ycg9AzQqpzg424T93v

Thats a paste of my entire firezone.rb file.

The logs say:

root@instance-20220719-0115:/# firezone-ctl tail phoenix
2022-07-29_22:28:33.14749   Serializer: Phoenix.Socket.V2.JSONSerializer
2022-07-29_22:28:33.14920   Parameters: %{"token" => "SFMyNTY.g2gDYQFuBgCDTBNMggFiAAFRgA.edTgZz-CE7v9DbX0HkPNWhF0Ain16JbMd4aLnKT-Ggs", "vsn" => "2.0.0"}
2022-07-29_22:28:35.30510 22:28:35.304 [info] REFUSED CONNECTION TO FzHttpWeb.UserSocket in 181µs
2022-07-29_22:28:35.30512   Transport: :websocket
2022-07-29_22:28:35.30512   Serializer: Phoenix.Socket.V2.JSONSerializer
2022-07-29_22:28:35.30512   Parameters: %{"token" => "SFMyNTY.g2gDYQFuBgCDTBNMggFiAAFRgA.edTgZz-CE7v9DbX0HkPNWhF0Ain16JbMd4aLnKT-Ggs", "vsn" => "2.0.0"}
2022-07-29_22:28:41.30015 22:28:41.299 [info] REFUSED CONNECTION TO FzHttpWeb.UserSocket in 142µs
2022-07-29_22:28:41.30017   Transport: :websocket
2022-07-29_22:28:41.30017   Serializer: Phoenix.Socket.V2.JSONSerializer
2022-07-29_22:28:41.30018   Parameters: %{"token" => "SFMyNTY.g2gDYQFuBgCDTBNMggFiAAFRgA.edTgZz-CE7v9DbX0HkPNWhF0Ain16JbMd4aLnKT-Ggs", "vsn" => "2.0.0"}
2022-07-29_22:28:47.30336 22:28:47.303 [info] REFUSED CONNECTION TO FzHttpWeb.UserSocket in 146µs
2022-07-29_22:28:47.30352   Transport: :websocket
2022-07-29_22:28:47.30508   Serializer: Phoenix.Socket.V2.JSONSerializer
2022-07-29_22:28:47.30509   Parameters: %{"token" => "SFMyNTY.g2gDYQFuBgCDTBNMggFiAAFRgA.edTgZz-CE7v9DbX0HkPNWhF0Ain16JbMd4aLnKT-Ggs", "vsn" => "2.0.0"}

**Comment by jamilbk** [comment]
@princemaple Error is likely here: https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/channels/user_socket.ex#L31

I'll do some local testing and see if I can get it fixed. Enjoy your weekend!

**Comment by princemaple** [comment]
@DillFrescott Thanks a lot for the prompt responses!

@jamilbk 🙏

**Comment by dillfrescott** [comment]
Awesome! Sounds good!

**Comment by jamilbk** [comment]
#877 should resolve this and also print some helpful information to your phoenix log showing the `x-forwarded-for` header as seen by Phoenix. It's likely that's not coming through properly (could be Cloudflare's fault).
