### ISSUE TITLE
0.5.1 - Incorrect session IP

### ISSUE THREAD

**Issue by gbe0** [CloudFire-LLC/cloudfire#868]
After upgrade of Firezone to 0.5.1, I have noticed the session IP in the web interface is returned incorrectly. I am accessing the web UI using IPv6 (from a public IPv6 address). The web UI shows this:

![2022-07-28_14-51](https://user-images.githubusercontent.com/47361208/181440151-54fe6dc0-1437-4398-b48f-acaf666de787.png)

My true address starts with 2404.

**Comment by jamilbk** [comment]
@gbe0 Yeah, found this little gem last night. This is a display format error. Will have it fixed in a bit.

Thanks for the report!

**Comment by jamilbk** [comment]
cc @conectado
