### ISSUE TITLE
Cant install firezone 0.5.2 even with nginx disabled.

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#878]
root@instance-20220719-0115:/# apt install ./firezone_0.5.2-ubuntu2004-x64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'firezone' instead of './firezone_0.5.2-ubuntu2004-x64.deb'
The following packages will be upgraded:
  firezone
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/158 MB of archives.
After this operation, 1024 B of additional disk space will be used.
Get:1 /firezone_0.5.2-ubuntu2004-x64.deb firezone amd64 0.5.2-1 [158 MB]
(Reading database ... 132770 files and directories currently installed.)
Preparing to unpack .../firezone_0.5.2-ubuntu2004-x64.deb ...
ERROR: Firezone 0.5+ removes support for disabling SSL redirect!
Instead, disable Nginx and point your SSL-terminating proxy directly to the phoenix app on port 13000. See the docs for more information: https://docs.firezone.dev/deploy/reverse-proxies
dpkg: error processing archive /firezone_0.5.2-ubuntu2004-x64.deb (--unpack):
 new firezone package pre-installation script subprocess returned error exit status 1
firezone has been uninstalled!

Please see our upgrade guide for any version notes that apply:
https://docs.firezone.dev/administer/upgrade

Errors were encountered while processing:
 /firezone_0.5.2-ubuntu2004-x64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@instance-20220719-0115:/# 

----------

It says that even with nginx enabled = false

**Comment by dillfrescott** [comment]
Am I missing something obvious here?

**Comment by akrousset** [comment]
Do you have `default['firezone']['nginx']['force_ssl'] = false` hanging around in the config? Generally at `/etc/firezone/firezone.rb`.

If so you can either comment it our or remove it (suggested) and the install should go forward.

**Comment by dillfrescott** [comment]
Ah, thank you so much!
