### ISSUE TITLE
Add option to set HTTP Strict Transport Security (HSTS) header for nginx

### ISSUE THREAD

**Issue by TDogger** [CloudFire-LLC/cloudfire#879]
Configuration option to add HSTS header for NGINX is currently missing. Should be at least configurable, if not default.

For example;

`default['firezone']['nginx']['hsts_header']=true`

should add the following to the default nginx.conf

`add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;`

ideally the options to set _max-age_ and _includeSubDomains_ should be configurable as well, but could be reasonable defaults.

See;
https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/

**Comment by jamilbk** [comment]
Great suggestion. Should be pretty straightforward; will queue up for the next release.

Thanks!
