### ISSUE TITLE
x_forward_for_header issue when using Caddy 2

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#885]
https://imgur.com/a/E79JSwP

I believe I may have to change something with the config? Not quite sure as I assumed caddy handled that automatically

**Comment by princemaple** [comment]
```ruby
# ## Custom Reverse Proxy
#
# An array of IPs that Firezone will trust as reverse proxies.
#
# Read more here:
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#selecting_an_ip_address
#
# By default the following IPs are included:
# * IPv4: 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
# * IPv6: ::1/128, fc00::/7
#
# If any client requests will actually be coming from these private IPs, add them to
# default['firezone']['phoenix']['private_clients'] below instead of here.
#
# If set to false Firezone will assume that it is not running behind a proxy
default['firezone']['phoenix']['external_trusted_proxies'] = []

# An array of IPs that Firezone will assume are clients, and thus, not a trusted
# proxy for the purpose of determining the client's IP. By default the bundled
# See more here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#selecting_an_ip_address
# This will supersede any proxy configured manually or by default by
# default['firezone']['external_trusted_proxies']
default['firezone']['phoenix']['private_clients'] = []
```

You probably have to set `external_trusted_proxies`. Is you caddy server on a different server?

**Comment by dillfrescott** [comment]
My caddy is on the same machine

**Comment by dillfrescott** [comment]
My `external_trusted_proxies` is set to the Cloudflare ip's

default['firezone']['phoenix']['external_trusted_proxies'] = %w[
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
172.64.0.0/13
131.0.72.0/22
2400:cb00::/32
2606:4700::/32
2803:f800::/32
2405:b500::/32
2405:8100::/32
2a06:98c0::/29
2c0f:f248::/32
]

**Comment by dillfrescott** [comment]
Fixed it by setting `external_trusted_proxies` to `127.0.0.1` and disabling cloudflare proxy!

**Comment by princemaple** [comment]
You don't need to set the loop back ip. There is a list of internal ips that are automatically ignored.

Also I'm not sure if there is a real problem hidden underneath. Maybe @jamilbk or @conectado would like to chime in. What's the proper configuration and possible cause for this case?

**Comment by jamilbk** [comment]
@DillFrescott Thanks for the information and report. We’ve seen some issues picking up the real client IP when using Cloudflare’s reverse proxy in front of Firezone.

In 0.5.2 we added improved logging for these scenarios to hopefully provide more troubleshooting help.

You should be [seeing “Client IP couldn’t be determined!” warnings in your `firezone-ctl tail phoenix` log](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/channels/user_socket.ex#L8) corresponding to this page load that contains the x_forwarded_for header and other connection info as seen by Firezone.

Would you be able to post the relevant logs here or email it to team AT firezone.dev so we can take a deeper look?

**Comment by dillfrescott** [comment]
Ok so I reenabled Cloudflare, and now its still working just listing one of Cloudflare's IP's

**Comment by dillfrescott** [comment]
I believe I'll just leave Cloudflare off. Its a private instance and Caddy handles the tls really well anyways I dont really need Cloudflare's proxy at all.
