### ISSUE TITLE
Firewall rules apply to all interfaces and sources

### ISSUE THREAD

**Issue by icekom** [CloudFire-LLC/cloudfire#896]
Firezone 0.5.2 creates rules in the `forward` chain that apply to all interfaces and only per-user rules check the source address. `postrouting` chain has masquerade rules for all interfaces. It may be good for this to be the default behavior (might save an inexperienced user from security-critical misconfiguration), but there should be a way to configure it, as adding non-scoped rules interferes with unrelated interfaces (one notable case being Kubernetes networking).

**Comment by jamilbk** [comment]
Thanks for the suggestion. Scoping the non-user rules to the firezone wireguard interface only or limiting it to the tunnel subnet makes sense.

cc @conectado

**Comment by jamilbk** [comment]
@icecom-dg Egress rules will be scoped to the Firezone WireGuard interface for now. That work?

We're doing some rearchitecting of the firewall rule logic and will make this more configurable in the future.

**Comment by icekom** [comment]
Yes, that'll do.


Thanks, loving Firezone so far!
