### ISSUE TITLE
1.0 High Availability

### ISSUE THREAD

**Issue by gongjason** [CloudFire-LLC/cloudfire#897]
Features to support high availability deployments:

- [x] Automatic failover
- [x] Load balancing
- [x] Minimal-downtime upgrades

**Comment by tbondarchuk** [comment]
@jamilbk I wanted to try HA setup like follows: NLB => 2xEC2 => RDS but not sure if wireguard config will be replicated from db to all EC2 instances? i.e. when admin opens UI on instance one, add users, configs will be stored to db and instance one’s wireguard config updated — will then instance two notice changes in db, pull configs and reconfigure it’s own wireguard?

I’ve started to setup infra to try that but it takes me a bit longer then expected, so perhaps you can save me some time if firezone does not really work like that? It’s just that https://github.com/firezone/terraform-aws-firezone-vpn seems to use completely different approach by setting primary/failover instances and syncing config via rsync so it got me to question my intended approach.

**Comment by jamilbk** [comment]
> @jamilbk I wanted to try HA setup like follows: NLB => 2xEC2 => RDS but not sure if wireguard config will be replicated from db to all EC2 instances? i.e. when admin opens UI on instance one, add users, configs will be stored to db and instance one’s wireguard config updated — will then instance two notice changes in db, pull configs and reconfigure it’s own wireguard?

There are couple issues with this approach:

1. The WireGuard private key is generated on the Firezone server and never leaves the filesystem. The DB does not contain it, so replicating only the DB will not allow existing peers to communicate with the Firezone server.
1. Load-balancing WireGuard behind the AWS NLB has [its own limitations](https://www.procustodibus.com/blog/2021/02/ha-wireguard-on-aws/#limitations).

I'll be sure to update this issue as we architect HA in Firezone further.

**Comment by jamilbk** [comment]
This _should_ be coming as part of #1769 in 1.0.

**Comment by xeruf** [comment]
Well this would probably be a lot easier with K8s support and a helm chart, wouldn't it? ;)

**Comment by jamilbk** [comment]
@xeruf Possibly, if you're using k8s. Out of curiosity, during an upgrade, what would be an acceptable Pod termination grace period be for clients connected to that Pod?

**Comment by jamilbk** [comment]
Docs: https://www.firezone.dev/kb/deploy/gateways

**Comment by xeruf** [comment]
Nice. At least with OpenVPN, I remember clients reconnected automatically so no grace period was ever necessary for us.

**Comment by jamilbk** [comment]
@xeruf Our clients do reconnect automatically as well if their connection to a gateway is abruptly killed.

The above question was more for dealing with gracefully disconnecting clients with active network flows through a particular gateway. We've discussed internally and have some ideas, but curious to hear what / how users are approaching the problem.
