### ISSUE TITLE
Wrong endpoint placeholder value on settings page

### ISSUE THREAD

**Issue by sergeysedoy97** [CloudFire-LLC/cloudfire#910]
Pages settings/site and users/:id/new_device shows different default endpoint values.

![Screenshot 2022-08-10 133912](https://user-images.githubusercontent.com/48452323/183882266-89700a10-b163-4d12-875d-35093cae711c.png)
![Screenshot 2022-08-10 133928](https://user-images.githubusercontent.com/48452323/183882272-875a0005-084f-43bd-8ed0-20a17d4c1018.png)

**Comment by jamilbk** [comment]
Thanks for the report! Do you have `default['firezone']['wireguard']['endpoint']` set in your config file?

**Comment by sergeysedoy97** [comment]
@jamilbk thank you for great product. Yes endpoint is set to my FQDN, because I need to accept IPv4 and IPv6 connections. And DNS is set to 1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001

**Comment by jamilbk** [comment]
@sergeysedoy97 Does the WireGuard config get generated correctly? It's just the placeholder that's wrong?

**Comment by sergeysedoy97** [comment]
@jamilbk config is correct, problem in placeholder value. On `users/:id/new_device` I see current endpoint value (which is FQDN), but on `settings/site` in placeholder I see IP (which is not endpoint value).
