### ISSUE TITLE
Docker deployment docs

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#913]
Issue to track adding docs around our new Docker image in production.

Current docs need to be made context-aware for situations where Docker and Omnibus differ. E.g. `firezone-ctl` is no longer the way to reload configuration.

refs #260 

@princemaple 's instructions for setting up a working Firezone instance in Docker: Refs #887

**Comment by rucciva** [comment]
Hi @jamilbk , i am experiencing with the Dockerfile.prod and docker-compose.prod.yml right now. one thing i found is that the admin user is not created even with `ADMIN_EMAIL` and `DEFAULT_ADMIN_PASSWORD` are specified.

should i create a separate issue for this?

<img width="990" alt="Screen Shot 2022-09-05 at 15 32 58" src="https://user-images.githubusercontent.com/4647473/188405335-50e0012a-0eab-4515-9e2e-d242c89f8907.png">

**Comment by princemaple** [comment]
The admin can be created/reset by running `docker compose -f docker-compose.prod.yml exec firezone bin/create-or-reset-admin`

**Comment by princemaple** [comment]
See https://github.com/firezone/firezone/pull/887 for details.

**Comment by rucciva** [comment]
thanks @princemaple for the info. But shouldn't it be possible to specify the user from the environment?

**Comment by princemaple** [comment]
Maybe we will do that eventually. It could be part of the start script, so a reset (create on first run) is performed every time the container boots up. It's not officially out yet, as it hasn't been documented.

**Comment by rucciva** [comment]
ah i see, i thought the feature was there since the env variables were there. Thanks @princemaple

**Comment by princemaple** [comment]
The prod image is usable, someone is already running it in prod. It's just that we haven't officially released it, so it might not be in its final shape yet.

**Comment by rucciva** [comment]
well noted @princemaple .

btw, any chance on adding feature to enable specifying egress rule from env variables or file? i personally prefer IaC approach in deploying services.

**Comment by princemaple** [comment]
We are going to add rest API in a bit. That will allow scripting side of IaC. Probably not from environment, unless many people ask for it or Jamil has it in mind but I don't know.
