### ISSUE TITLE
Let's Encrypt / ACME Broken - 0.5.5 Release

### ISSUE THREAD

**Issue by console-cowboy** [CloudFire-LLC/cloudfire#924]
The latest release version's changes have broken ACME issuance and renewal of certifications; rather than only exposing firezone on Port 80 when ACME isn't in use, firezone isn't responding to requests on Port 80 at all, breaking ACME as it looks for the .well-known directory over HTTP and fails to find it.

This issue is not present in 0.5.4, and given that 0.5.5 was only a bugfix release that was meant to implement a toggle on port 80 if ACME isn't enabled, this could probably just be fixed with a regression.

**Comment by jamilbk** [comment]
@console-cowboy This was done to prevent nginx from conflicting with other http servers on the host on port 80 if ACME is disabled.

Maybe I’m misunderstanding, but could you elaborate a bit more on your configuration? I’m curious what you mean by this, if ACME is disabled:

> breaking ACME as it looks for the .well-known directory over HTTP and fails to find it.

**Comment by jamilbk** [comment]
Thanks for the report! This is a strange error — reverted until we can look further into it.
