### ISSUE TITLE
When will OpenWRT be supported on the server

### ISSUE THREAD

**Issue by 8MiYile** [CloudFire-LLC/cloudfire#937]
Hey
i want use firezone in my OpenWRT router
Want to be able to mix work with my LAN IP segment

**Comment by jamilbk** [comment]
Hi! So it's unlikely the web portal will ever run well (if at all) on resource-constrained embedded devices like a home router. The WireGuard and firewall backend should run just fine though. We're rearchitecting things to decouple the portal to allow these types of setups in the near future.

Are you looking to remote tunnel into your LAN while on the road, or moreso looking for a point-to-point tunnel into your work's VPN?

**Comment by 8MiYile** [comment]
> Hi! So it's unlikely the web portal will ever run well (if at all) on resource-constrained embedded devices like a home router. The WireGuard and firewall backend should run just fine though. We're rearchitecting things to decouple the portal to allow these types of setups in the near future.
> 
> Are you looking to remote tunnel into your LAN while on the road, or moreso looking for a point-to-point tunnel into your work's VPN?

remote tunnel my vpn into LAN area
just like openvpn server

**Comment by d-513** [comment]
I would like the firewall backend to be separated, so we could run the VPN itself on the router
