### ISSUE TITLE
Lets Encrypt DNS API Option

### ISSUE THREAD

**Issue by Cave-Johnson** [CloudFire-LLC/cloudfire#962]
Love the new Lets encrypt cert option! It'd be great to get an option to use DNS API authentication as there are a number of use cases where the nginx file method isn't suitable (Multiple services running behind a single IP).

Natively supported by clients like acme.sh (https://github.com/acmesh-official/acme.sh/wiki/dnsapi)

**Comment by jamilbk** [comment]
Hi @Cave-Johnson thanks for the suggestion! Not sure when we'll be able to get to this, or if we will. We actually use `acme.sh` behind the scenes, but accommodating this use case would be non-trivial.

May I recommend [disabling our bundled Nginx and using your own reverse-proxy](https://docs.firezone.dev/deploy/reverse-proxies)? Caddy is fairly easy to set up and works well with Firezone.

We'll be releasing Docker support very soon which provides more flexibility for deploying Firezone and using custom ACME renewal methods like this.

**Comment by Cave-Johnson** [comment]
Dont suppose you have any updates on this now that docker support has rolled out with Caddy?

**Comment by jamilbk** [comment]
@Cave-Johnson You're free to customize the `caddy` service in the `~/.firezone/docker-compose.yml` however you like -- Firezone doesn't terminate SSL so it shouldn't interfere with your preferred ACME configuration.
