### ISSUE TITLE
Web GUI not logging current user out when using back arrows to navigate back to login screen

### ISSUE THREAD

**Issue by ecrawford-0** [CloudFire-LLC/cloudfire#963]
Hello! I was setting up FireZone and I noticed that with the web gui after I sign in, I can use the back arrow on the browser it brings me back to the sign in page without logging the current user out. I can also essentially log back by using the forward on the browser too. Is this expected behavior or a bug?  Thank you for your time and consideration in advanced.

Below is a short gif of me recreating the behavior explained: 

![2022-09-08 14-46-12](https://user-images.githubusercontent.com/61421800/189202855-f0e4535b-495c-47df-add3-917df2143c8a.gif)

**Comment by jamilbk** [comment]
Hi @ecrawford-0 thanks for the report!

This is just how web browsers work. Session cookie lasts 4 hours -- we don't intercept the browser back button to clear the cookie or do anything else special. Clicking log out is the preferred way to log out.
