### ISSUE TITLE
Is there a way to enforce wireguard conf?

### ISSUE THREAD

**Issue by dillfrescott** [CloudFire-LLC/cloudfire#964]
To prevent someone changing the wireguard configuration directly, is there a way to deny the connection if the wireguard profile doesn't identically match the one generated?

**Comment by jamilbk** [comment]
Unfortunately there's not. With client apps this won't be an issue, however. We're busy working on those, due out sometime in Q4 of this year.

**Comment by dillfrescott** [comment]
Okay! Cool!
