### ISSUE TITLE
Admin account with OIDC needs password to change Email

### ISSUE THREAD

**Issue by sebastianbuechler** [CloudFire-LLC/cloudfire#970]
I created a new instance, added OIDC, and logged in with my account. Since I did not create an admin account I will automatically get admin as the first user and see the admin panel. All nice, but when I want to change the email in account settings I can't because it requires there a password. Maybe, in that case, I should not be able to change the email since it comes from OIDC, or if still sensible it should require OIDC confirmation for change. Also, the change password function won't be useful if I'm not mistaken.

**Comment by jamilbk** [comment]
Thanks for the report @sebastianbuechler -- this behavior will likely be changing as part of a refactor we're working on. I'll leave this open to track any relevant changes.

In the meantime, the `firezone-ctl create-or-reset-admin` CLI command will set a default password for the user specified by `default['firezone']['admin_email']`.

**Comment by solariz** [comment]
Thanks, having a question tho. What happens if I have a firezone running with local authentication off. 
Does "firezone-ctl create-or-reset-admin" re-enable it automatically or am I locked out at some point e.g. when my OIDC doesnt work anymore?

**Comment by jamilbk** [comment]
> Thanks, having a question tho. What happens if I have a firezone running with local authentication off. Does "firezone-ctl create-or-reset-admin" re-enable it automatically or am I locked out at some point e.g. when my OIDC doesnt work anymore?

Yeah, you'll need to recover from the CLI. Working on improving UX around this edge case for 0.7.

**Comment by jamilbk** [comment]
Tracking this work in #1123
