### ISSUE TITLE
Allow DNS To be a host to enable dns over tls for android

### ISSUE THREAD

**Issue by bomdia** [CloudFire-LLC/cloudfire#978]
allow to use a name host for dns over tls, in the field for setting dns you can only use ip address but if you add a hostname you can't save it, but for DoT (Dns over TLS) you need to use an hostname to a DoT server (port 853 tcp) this is needed for recent android version to allow the dns to resolve the internal name the part on wireguard side is already implemented and if you manually edit the client config adding the hostname it work without issue

**Comment by jamilbk** [comment]
Thanks for the report! Will queue this in our backlog. Need to test on clients on other platforms.
