### ISSUE TITLE
Add the ability to inject custom CSS

### ISSUE THREAD

**Issue by chrisszeluga** [CloudFire-LLC/cloudfire#989]
The Admin UI is nicely designed, but it would be even nicer if users could easily tweak a few CSS variables to match things like company branding.

A simple solution would be to add a textbox in the Customization tab where admins can include a CSS snippet that would get injected into the page head of the login and admin screens.

**Comment by ihard** [comment]
+1

**Comment by jamilbk** [comment]
This probably won't be be on the radar any time soon due to the security implications.
