### ISSUE TITLE
How to compile Firezone from source?

### ISSUE THREAD

**Issue by m8522s** [CloudFire-LLC/cloudfire#992]
I might have missed the file in the documentation, but how do I compile Firezone on a distribution, which is not on the compatibility list? In my case I am referring to OpenWrt. It would be just great to have Firezone ready for OpenWrt.
Any help is greatly appreciated. Thanks!

**Comment by jamilbk** [comment]
Hi @m8522s -- due to the way Elixir releases work, you would have to build Firezone on OpenWRT. You can see how we build Firezone using Omnibus [here](https://github.com/firezone/firezone/blob/master/.github/workflows/omnibus_build.yml#L63).

**Comment by jamilbk** [comment]
If OpenWRT runs docker, I'd recommend going the Docker route instead.

**Comment by m8522s** [comment]
Thanks. Is there a command, which uses this file to build the app?
